### ISSUE TITLE
Can't use Formik in Blitz app

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#100]
Trying to use Formik in the store example results in 
```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

We need to figure out what is happening here.

**Comment by sijad** [comment]
can you please share your example?

**Comment by flybayer** [comment]
I don't have code for this at the moment. But if you want, you can check out latest canary, and add formik to the store example to see this. Let me know if you need help

**Comment by ryardley** [comment]
I’ll have a check once back from my walk but have you checked we don’t have multiple versions of React?

**Comment by sijad** [comment]
I couldn't reproduce this issue with store example

**Comment by flybayer** [comment]
Weird! Some of the later work in the arch PR must have fixed whatever was the issue. I just verified that I can't reproduce either.

I appreciate you looking into it, but sorry for the wild goose choose!
