### ISSUE TITLE
Yarn link for Blitz CLI is failing on db migrate

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#101]
1. `cd packages/cli`
2. `yarn link`
3. `cd ../../examples/store`
4. `blitz db migrate`

Fails with:
```
~/c/b/e/store> blitz db migrate
Error: spawn prisma ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by ryardley** [comment]
I am struggling to reproduce this:
* `git clone git@github.com:blitz-js/blitz.git`
* `yarn`
* `yarn build`
* `cd examples/store`
* `yarn blitz db migrate`
* `yarn blitz start`

All works fine on canary. After if I try to link I get this:

```
blitz/packages/cli 
➜ yarn link
yarn link v1.22.4
warning There's already a package called "@blitzjs/cli" registered. This command has had no effect. If this command was run in another folder with the same name, the other folder is still linked. Please run yarn unlink in the other folder if you want to register this folder.
✨  Done in 0.05s.
```

Which seems legit. 

I have seen this before at some point though. Possibly cleaning out node_modules fixes it?

**Comment by flybayer** [comment]
- lerna never auto linked the cli package for me
- `yarn blitz db migrate` works fine. `blitz db migrate` doesn't

**Comment by ryardley** [comment]
Ok I can reproduce. This is when blitz is installed I suspect by `pkg` after running `yarn build` at the root.

```
➜ which blitz
/usr/local/bin/blitz
```

```
➜ blitz db migrate
Error: spawn prisma ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by merelinguist** [comment]
Having this error too.

**Comment by ryardley** [comment]
So upon investigation I suspect the issue is that we need to keep the version within the example in sync with lerna or it's dependencies will not install correctly.

**Comment by ryardley** [comment]
Will try to PR soon
