### ISSUE TITLE
`blitz generate pages` should kebab-case all url paths.

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1022]
### What do you want and why?

Currently if you generate pages with two words, like `blitz generate testResult`, the resulting urls will have `/testResults`, but I want it to be `/test-results`.

### Possible implementation(s)

[Here's the place](https://github.com/blitz-js/blitz/blob/canary/packages/generator/src/generators/page-generator.ts#L57) where the pages file path is determined.

**Comment by aem** [comment]
I actually noticed this with the custom generators as well and meant to open this issue 😅 - I think my plan is to change this code to line up with the model generation logic - don't change any casing at all. I think we still want to enforce pluralization in certain places, but at least let people stick with camel/kebab if they'd like

**Comment by flybayer** [comment]
> don't change any casing at all... at least let people stick with camel/kebab if they'd like

Are you saying to not automatically kebab-case url paths?

**Comment by aem** [comment]
> Are you saying to not automatically kebab-case url paths?

That's my gut reaction, to just not be opinionated about it - I definitely know people who prefer camelcase URL paths

**Comment by cr101** [comment]
For SEO best practice use kebab-case url paths. Using a hyphen in your URLs is recommended by Google, because it makes your website easy to read for humans. As an end result, this means that your site will place better on search engines.

**Comment by flybayer** [comment]
Looks like the consensus from slack is that people do what kebab case by default. If someone wants something else, they can use custom templates.

**Comment by aem** [comment]
Sounds good to me. I'll try and pick this up once I clean up + merge the
custom templates PR, if no one else has

**Comment by engelkes-finstreet** [comment]
Are you already working on this @aem? Else I could take this over.

**Comment by flybayer** [comment]
@engelkes-finstreet it's all yours!
