### ISSUE TITLE
Add project scope formatter for `imports` statements

### ISSUE THREAD

**Issue by svobik7** [blitz-js/blitz#1031]
### What do you want and why?

During my last PR I noticed that there were some tracked changes just because different `import ...` statements arrangement. In my experience this adds unnecessary changes to PR and makes it harder to review.

<img width="488" alt="Screenshot 2020-09-09 at 19 03 02" src="https://user-images.githubusercontent.com/761766/92629796-215b3900-f2cf-11ea-8e67-5f9bfb07f369.png">

This was caused by my own VS Code auto-sort-import invoked on save. But my idea is that there can be some project scope formatter to keep imports organized among all developers. So that no one else can re-organize them in differrent way and produce these git changes.

### Possible implementation(s)

I found two possible option (not tested yet):
- ESLint - https://eslint.org/docs/rules/sort-imports
- Prettier - https://github.com/simonhaenisch/prettier-plugin-organize-imports/issues

### Additional context

I think that major requirement here must be that all **organizing must be done automatically** (on save, on commit, etc...) to keep developer out of responsibility of manual re-ordering of anything.

**Comment by engelkes-finstreet** [comment]
Prettier is already used in the project. I think adding a pre-commit hook is the only option since running prettier `on save` is only available if its configured inside your IDE / Editor as far as I know.

@flybayer Are we using anything for pre-commit hooks yet? I can take this over

**Comment by flybayer** [comment]
@engelkes-finstreet yeah we're already running prettier in the pre-commit hook

**Comment by svobik7** [comment]
@engelkes-finstreet have you tried mentioned prettier extension?

**Comment by kripod** [comment]
There is a very reliable ESLint plugin for the purpose of sorting imports: https://github.com/lydell/eslint-plugin-simple-import-sort

**Comment by svobik7** [comment]
@kripod I tested suggested eslint plugin and it works great! Just created PR. 👍
