### ISSUE TITLE
`blitz generate query` does not preserve plurality

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1032]
### What is the problem?

`blitz g query getPrices` generates `app/queries/getPrice.ts` instead of `app/queries/getPrices.ts`. And the name of the query inside the file is `getPrice` instead of `getPrices`

### Steps to Reproduce

1. `blitz g query getPrices`

### Versions

```
0.21.1
```

### Other

The issue is that [this line](https://github.com/blitz-js/blitz/blob/canary/packages/generator/src/generators/query-generator.ts#L15) uses `modelName` which is always singular. Also, the template name is [`__modelName__.ts`](https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/query/__modelName__.ts) which is singular for the same reason.

We might have to add a `rawInputName` to the Generator parent class for things like this.

**Comment by engelkes-finstreet** [comment]
I would like to look into this

**Comment by flybayer** [comment]
@engelkes-finstreet ok, all yours!
