### ISSUE TITLE
supertokens/publicDataStore causes an infinite loop between tabs

### ISSUE THREAD

**Issue by jxe** [blitz-js/blitz#1035]
### What is the problem?

This line in supertokens registers an event handler which watches for localStorage changes and then *makes a localStorage change* in response. This causes an infinite loop between two open tabs.

https://github.com/blitz-js/blitz/blob/8e9f2d097e80d3c68fed3bb2bd56ef7804d361e0/packages/core/src/supertokens.ts#L124

### Steps to Reproduce

1. Open two tabs with an app that uses this code in, say useSession
2. Wait for a session change to trigger the infinite loop
3. Watch CPU spike and your app rerender itself constantly.

### Versions

blitz: 0.21.1

**Comment by flybayer** [comment]
Oops, thank's for reporting this!
