### ISSUE TITLE
Prompt to choose database engine on app creation

### ISSUE THREAD

**Issue by yhoiseth** [blitz-js/blitz#1037]
Extracted from blitz-js/legacy-framework#764. Writing this up as a new issue because blitz-js/legacy-framework#764 was closed.

### What do you want and why?

A way to choose which database engine to use (Postgres or SQLite) on app creation.

### Possible implementation(s)

@flybayer wrote:

> I think we should add a prompt to blitz new that asks if you want sqlite or postgres (same as we do now for form library).

- [ ] For postgres we want to change the role to be an enum instead of a string.

### Additional context

@flybayer also wrote:

> We are going to remove the `provider = ["sqlite", "postgres"]` thing because it's causing too many problems.

(I couldn’t find an issue covering this point.)

**Comment by yhoiseth** [comment]
I don’t think I’ll get around to fixing this any time soon. So I removed myself as an assignee.

**Comment by flybayer** [comment]
Cool no problem! That's perfect @yhoiseth

**Comment by Dohxis** [comment]
I would love to work on this 🙂
