### ISSUE TITLE
Don't run the lambda warming code if not serverless

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#104]
Currently the query/mutation lambdas are always being sent a HEAD request on page load to warm the lambda.

- [ ] We need to automatically detect if running as a traditional server, in which case don't make the HEAD call
- [ ] Open question: should we make the HEAD calls in development? If I'm deploying serverless, then I'd like to see the HEAD calls in development. But if not, I don't want to see them. How should we handle this?

**Comment by Zeko369** [comment]
I'd like to work on this

**Comment by Zeko369** [comment]
I'd like to work on this. We could maybe detect this by finding `firebase.json`, `serverless.yml`, `now.json`?, or just have user add a config flag?

**Comment by flybayer** [comment]
@Zeko369 ok cool!

So if the app is started with `blitz start --production`, we know it is **not** serverless. Serverless only uses `blitz build`.

The above works for production, but in development we have to guess. Checking for `now.json` could work, but you don't have to have to for deploying to Zeit. I'm fine to just always run the HEAD call in development for now. Deal with this optimization later :)

**Comment by flybayer** [comment]
Hey @Zeko369 could you provide a status update on where you're at with this?

**Comment by sijad** [comment]
I can take this if you want

**Comment by flybayer** [comment]
Cool, let's see what @Zeko369 says

**Comment by Zeko369** [comment]
I'll have a PR up today, I can ping you both to review it if you'd like

**Comment by flybayer** [comment]
@Zeko369 ok perfect!

**Comment by Zeko369** [comment]
I had some stuff at work in the meantime, but the PR is up, so you can check it out @flybayer @sijad
