### ISSUE TITLE
Change the new app schema provider to be just `sqlite` instead of an array

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1044]
### What do you want and why?

Change the new app schema provider to be just `sqlite` instead of an array because the array is causing problems and Prisma is going to remove that feature.

We need to make the following change [in our new app schema](https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/app/db/schema.prisma#L5):

```diff
- provider = ["sqlite", "postgres"]
+ provider = "sqlite"
```

Along with this, we need to tweak the wording of [this part in our .env.local](https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/app/.env.local#L4) template.

And lastly, [the docs for switching to postres](https://blitzjs.com/docs/database-overview#switch-to-postgresql) need updated to match this (will now have to also change the provider in the schema).

**Comment by taylorcjohnson** [comment]
Hey @flybayer - I'd be happy to work on this issue over the weekend if help is still needed!

**Comment by flybayer** [comment]
@taylorcjohnson sweet, it's all yours!

**Comment by taylorcjohnson** [comment]
Two quick questions @flybayer 

1. I should also change the wording in `.env.test.local` to match that of `.env.local`, correct?
2. The docs for blitzjs are housed in a separate repository - should I open a separate issue there to modify the "Database Overview" page and its "Switch to PostgreSQL" section?
