### ISSUE TITLE
How to break .prisma file into smaller modules?

### ISSUE THREAD

**Issue by sangdth** [blitz-js/blitz#1046]
### What do you want and why?
My data schema quite huge, it's easier to maintain if I can break them into smaller files.

### Additional context
I've done quite fast research in prisma github repo and seem like they don't implement it yet.

**Comment by SigurdMW** [comment]
Doesn't seem to be supported by Prisma 2 yep: https://github.com/prisma/prisma/issues/2377
Could/would blitz do some magic to support this @flybayer?

**Comment by flybayer** [comment]
Let's hold off for now on doing anything about this in Blitz. Prisma is good at fixing & adding the most important features that people want, so probably they will add this.
