### ISSUE TITLE
Error during blitz npm install

### ISSUE THREAD

**Issue by developer0116** [blitz-js/blitz#1049]
I run `sudo npm i -g blitz`
but there is an error coming below:

AMP Optimizer ERROR Could not write cache file Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/blitz/node_modules/@ampproject/toolbox-optimizer/.cache'

I'd like your advice.

Thanks

**Comment by flybayer** [comment]
Hey @developer0116, I think the issue is because you are using `sudo`. You shouldn't use `sudo` with npm install.

Can you try without `sudo`?

If that still doesn't work, then try `npx blitz new myApp` and see if that works.

**Comment by developer0116** [comment]
npx blitz new myApp works...
Thank you!

**Comment by flybayer** [comment]
Great!
