### ISSUE TITLE
Unresponsive Links on error page 

### ISSUE THREAD

**Issue by SigurdMW** [blitz-js/blitz#1053]
### What is the problem?
When hitting an error, like unauthenticated, and try to add a `Link` on the error page - clicking the link does not make the page rerender. 

### Steps to Reproduce

1. Create a new blitz app
2. Add a `<Link href="/"><a>Home</a></Link>` to the  `RootErrorFallback` in `_app.tsx` that is returned when there is an `AuthenticationError`
3. Go to a page that requires authentication
4. Click the link you added in step 2

Expected: You are routed to the home URL and the page updates
Actual: You are routed to the home URL but the page does not update

### Versions

blitz: 0.21.2-canary.2 (global)
blitz: 0.21.2-canary.2 (local)

output of `blitz --version --verbose`
Windows 10 | win32-x64 | Node: v12.13.1

blitz: 0.21.2-canary.2 (global)
blitz: 0.21.2-canary.2 (local)

  Package manager: yarn
  System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 53.12 GB / 63.74 GB
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.6.2 => 2.6.2
    @prisma/client: 2.6.2 => 2.6.2
    blitz: 0.21.2-canary.2 => 0.21.2-canary.2
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8
    typescript: 4.0.2 => 4.0.2

### Other

Please include applicable logs and screenshots that show your problem.

**Comment by flybayer** [comment]
Thanks, good catch!

Here's the solution. I'm fixing this in the new app template.
```diff
-import { AppProps, ErrorComponent } from "blitz"
+import { AppProps, ErrorComponent, useRouter } from "blitz"
import { ErrorBoundary, FallbackProps } from "react-error-boundary"
import { queryCache } from "react-query"
import LoginForm from "app/auth/components/LoginForm"

export default function App({ Component, pageProps }: AppProps) {
  const getLayout = Component.getLayout || ((page) => page)
+ const router = useRouter()

  return (
    <ErrorBoundary
      FallbackComponent={RootErrorFallback}
+     resetKeys={[router.asPath]}
      onReset={() => {
        // This ensures the Blitz useQuery hooks will automatically refetch
        // data any time you reset the error boundary
        queryCache.resetErrorBoundaries()
      }}
    >
      {getLayout(<Component {...pageProps} />)}
    </ErrorBoundary>
  )
}
```
