### ISSUE TITLE
`blitz start` is significantly slower to start than `next dev`

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1056]
### What is the problem?

Next.js re-uses it's own build cache between `next dev` invocations so that subsequent runs of `next dev` start extremely fast.

But the problem is that we are deleting the entire `.blitz` cache folder, including the next.js cache. This means that `blitz start` is always slow to start.

### Steps to Reproduce

1. Run `blitz start` several times and notice the start time.
2. Run `yarn next .blitz/caches/dev` several times and notice the much faster start time

### Versions

```
0.22.0
```

cc @ryardley

**Comment by ryardley** [comment]
Be happy jump on this
