### ISSUE TITLE
Types for prisma atomic operations on update

### ISSUE THREAD

**Issue by jose-donato** [blitz-js/blitz#1065]
### What do you want and why?

Current blitz.js version throws typescript errors with Prisma Atomic operations on update (increment, decrement, etc. - more info in [prisma docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/crud#atomic-operations-on-update)). 

![image](https://user-images.githubusercontent.com/43375532/93030106-758c5300-f618-11ea-8fc6-718661c51d21.png)

**Temporary fix:**
adding `//@ts-ignore` in the previous line ignores the typescript error and everything works as expected (upvotes field is incremented by one)

![image](https://user-images.githubusercontent.com/43375532/93030120-905ec780-f618-11ea-9e0b-fde2cab40d81.png)

**Comment by flybayer** [comment]
Hey @jose-donato, this is a Prisma issue, and not specific to Blitz, but what's the output of `blitz -v`?

**Comment by jose-donato** [comment]
```
Linux 5.7 | linux-x64 | Node: v12.17.0

blitz: 0.21.1 (global)
blitz: 0.22.1 (local)

  Package manager: npm 
  System:
    OS: Linux 5.7 Kali GNU/Linux Rolling 2020.3
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 6.66 GB / 15.43 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
    Yarn: Not Found
    npm: 6.14.7 - ~/.nvm/versions/node/v12.17.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.6.2 => 2.6.2 
    @prisma/client: 2.6.2 => 2.6.2 
    blitz: 0.22.1 => 0.22.1 
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    typescript: 3.9.7 => 3.9.7 
```

**Comment by flybayer** [comment]
Ok, have you added the feature flag like this?
```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["atomicNumberOperations"]
}
```

**Comment by jose-donato** [comment]
yes

```
datasource db {
  provider = ["sqlite", "postgres"]
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["atomicNumberOperations"]
}
```

**Comment by flybayer** [comment]
Ok! :)
