### ISSUE TITLE
Change blitz server to support `pages` and `api` as siblings instead of nested

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#107]
We just updated the file structure RFC to switch from `routes` and `routes/api` to `pages` and `api`: https://github.com/blitz-js/blitz/pull/74

- The server already supports the `pages` directory
- [ ] `api` directory at top level or nested anywhere inside `app/` should be moved to `pages/api` inside the blitz build directory.
- [x] Presence of `pages/api/` should error.

**Comment by merelinguist** [comment]
“Presence of pages/api/ should error.” fixed by #106

**Comment by flybayer** [comment]
@ryardley where in the server code do we need to make the change for this? We need this for the alpha

**Comment by ryardley** [comment]
@flybayer This isn’t done yet as far as I know. I was hoping to put it in the refactor which aught to be ready ready for testing tomorrow.

**Comment by flybayer** [comment]
@ryardley the refactor includes this?

**Comment by ryardley** [comment]
Will be ready tonight
