### ISSUE TITLE
ALPHA software warning is being added to .zshrc when setting up autocomplete

### ISSUE THREAD

**Issue by pbteja1998** [blitz-js/blitz#1094]
### What is the problem?
When trying to add `blitz autocomplete` with the given instructions, the following is also being appended to `.zshrc` since `blitz` command shows this every time.

```
You are using alpha software - if you have any problems, please open an issue here:
    https://github.com/blitz-js/blitz/issues/new/choose
```

### Steps to Reproduce

1. Run `printf "$(blitz autocomplete:script zsh)" >> ~/.zshrc; source ~/.zshrc` in terminal. 

### Versions

```
output of `blitz --version --verbose`
You are using alpha software - if you have any problems, please open an issue here:
    https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: /Users/bhanuteja.p/.nvm/versions/node/v12.16.2/lib/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/bhanuteja.p/.nvm/versions/node/v12.16.2/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js

macOS Catalina | darwin-x64 | Node: v12.16.2

blitz: 0.22.1 (global)

  Package manager: yarn
  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 274.18 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: Not Found
    @prisma/client: Not Found
    blitz: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```

### Other

Please include applicable logs and screenshots that show your problem.
NOT APPLICABLE

### Potential Solution

I think just changing the documentation should suffice here. If needed, I could change the documentation by adding this info.

**Comment by flybayer** [comment]
Oops, thanks for reporting this! This is now marked available for anyone to work on.

**Comment by pbteja1998** [comment]
Hey @flybayer I would like to work on this. Can you please assign it to me?

**Comment by enricoschaaf** [comment]
I would like to work on this, but I am not quite sure how to tacle this. I found the source of the warning here https://github.com/blitz-js/blitz/blob/68162b406c4d0ee97a94a9019e593720455c423c/packages/blitz/src/bin/cli.ts, but I am not sure how to disable it only for the autocomplete command.
We could monkeypatch it like this for example since blitz will not be in alpha forever, but it doesnt really feel good to do it this way.
```printf "$(blitz autocomplete:script zsh | tail -3)" >> ~/.zshrc; source ~/.zshrc```

**Comment by enricoschaaf** [comment]
Maybe something in this direction, just more pollished?
https://github.com/blitz-js/blitz/blob/68162b406c4d0ee97a94a9019e593720455c423c/packages/blitz/src/bin/cli.ts
```typescript
if(!process.argv.find(argv => argv === "autocomplete:script")?.length) {
  console.log(
    chalk.yellow(
      `You are using alpha software - if you have any problems, please open an issue here:
    https://github.com/blitz-js/blitz/issues/new/choose\n`,
    ),
  )
}

**Comment by flybayer** [comment]
@enricoschaaf yes basically like that! However we are already using [minimist](https://github.com/substack/minimist) further down in the file to parse argv. So you can move that minimist call to the top of the file and then use that for this check instead of `process.argv`

**Comment by enricoschaaf** [comment]
Nice, pull request is on its way, just wondering if you would do it like this or use find, not that familiar with command line tools and wondering if there are any edge cases. Are there any tests I need to modify?

```typescript
  const options = require("minimist")(process.argv.slice(2))
  if(options._[0] === "autocomplete:script") {
    console.log(
      chalk.yellow(
        `You are using alpha software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose\n`,
      ),
    ) 
  }

**Comment by flybayer** [comment]
@enricoschaaf yes I think that should work like that. Don't need to use `.find`
