### ISSUE TITLE
Add ability to run `blitz db reset --force` to skip the prompt

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1096]
### What do you want and why?

Currently `blitz db reset` requires user input, but I want to use the command in a test and CI where user can't answer.

So I want ability to pass `--force` to skip all user prompts

### Possible implementation(s)

Add option to [this file](https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/db.ts)

**Comment by pbteja1998** [comment]
@flybayer I want to work on this issue. Can you please assign it to me.

**Comment by ivandevp** [comment]
Go ahead @pbteja1998 ! 👍
