### ISSUE TITLE
Ctrl+D doesn't work in `blitz console` after awaiting a promise

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1099]
### What is the problem?

Pressing Ctrl+D once time in a node REPL should exit. And it does in `blitz console` until you await a promise, then it stops working

### Steps to Reproduce

1. `blitz console`
1. `await db.user.findMany()`
1.  Press Ctrl+D -> see it doesn't exit.

### Versions

```
blitz: 0.22.2-canary.0 (global)
blitz: 0.22.2-canary.0 (local)

  Package manager: npm
  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 9.62 GB / 64.00 GB
    Shell: 3.1.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.18.3 - /var/folders/gf/xyzbs8n52kz_sxxvpw2psh1r0000gn/T/fnm-shell-5751353/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.6 - /var/folders/gf/xyzbs8n52kz_sxxvpw2psh1r0000gn/T/fnm-shell-5751353/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/cli: 2.4.1 => 2.4.1
    @prisma/client: 2.4.1 => 2.4.1
    blitz: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: 3.9.5 => 3.9.5
```

### Idea to fix:

I think the solution probably is to listen for the `exit` event from the repl and call `process.exit()` as shown here: https://nodejs.org/api/repl.html#repl_event_exit

This would be added here: https://github.com/blitz-js/blitz/blob/canary/packages/repl/src/repl.ts#L91

**Comment by drmas** [comment]
This looks like a good start for me to contribute to this amazing project.
@flybayer can you assign this to me
