### ISSUE TITLE
ctrl+c on blitz db migrate won't stop the process

### ISSUE THREAD

**Issue by eunjae-lee** [blitz-js/blitz#1130]
### What is the problem?

When `blitz db migrate` asks for its name, I hit `ctrl+c` but it just created a migration with the migration name of an empty string.

### Steps to Reproduce

1. Run `blitz db migrate`
2. Hit `ctrl+c`
3. You will see it won't stop, and just create files like `20200920162322/schema.prisma`.

### Versions

```
debug: blitzPkgPath: /Users/eunjaelee/workspace/unfinished-side-projects/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/eunjaelee/workspace/unfinished-side-projects/node_modules/@blitzjs/cli/lib/src/index.js 

macOS Catalina | darwin-x64 | Node: v12.18.0

blitz: 0.22.1 (global)
blitz: 0.22.1 (local)

  Package manager: yarn 
  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 405.85 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: 1.16.0 - /usr/local/Cellar/yvm/3.6.7/shim/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/cli: 2.7.1 => 2.7.1 
    @prisma/client: 2.7.1 => 2.7.1 
    blitz: 0.22.1 => 0.22.1 
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    typescript: 4.0.3 => 4.0.3 
```

### Other

<img width="719" alt="image" src="https://user-images.githubusercontent.com/499898/93716224-e4b0fc80-fb6e-11ea-9855-a3fa9da3b520.png">

**Comment by nitaking** [comment]
I thought this was a problem too!  I agree
it!

**Comment by nitaking** [comment]
I feel that it can be handled by handling keyboard events!

**Comment by cktang88** [comment]
From a quick glance through https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/db.ts#L62 it seems that the actual prompt for name is handled by Prisma, so I couldn't think of a way to actually do this at the Blitz.js CLI level?

**Comment by flybayer** [comment]
I think we can solve it without prompting for a name ourselves. Probably what we need to do is pass through the `sigint` signal to the spawned prisma cli.

**Comment by nitaking** [comment]
I'll try.

**Comment by nitaking** [comment]
I'm not sure if I can handle keyboard events while p-events are processing.
If p-event returns exit 1 with ctrl-c, it will work, but...

**Comment by nitaking** [comment]
I can't determine if it's a ctrl-c exit or not, and the process goes on.

I've placed keypress etc. as the event handler for ctrl-c, but it doesn't work. Hmm, it may be quite troublesome.

Do you know of any libraries other than `p-event` that do this? I want to try it.

**Comment by nitaking** [comment]
try it:

```ts
const cp = require("cross-spawn").spawn(prismaBin, args, {
    stdio: silent ? "ignore" : "inherit",
    env: process.env,
  })
  // console.debug('runPrisma', { step: 4})
  var keypress = require('keypress');
  keypress(process.stdin);
  process.stdin.on('keypress', function (ch, key) {
    console.log('got "keypress"', key);

    if (key && key.ctrl && key.name == 'c') {
      console.debug('CALL ctrl-c')
      process.stdin.pause();
    }
  });

  process.stdin.setRawMode(true);
  process.stdin.resume();

  const sleep = msec => new Promise(resolve => setTimeout(resolve, msec));
  await sleep(2000)

  // const code = await require("p-event")(cp, "exit", {rejectionEvents: []})
  const code = await require("p-event")(cp, "exit", {rejectionEvents: ['error']})

  return code === 0
```

![2020-09-24 01 23 58](https://user-images.githubusercontent.com/10850034/94041090-bfd5b700-fe04-11ea-89b0-6175720bc1bd.gif)

**Comment by nitaking** [comment]
https://github.com/prisma/prisma/blob/b972e05fc9d3de2937c94fafeac2285142adc578/src/packages/migrate/src/commands/MigrateSave.ts#L196

It seems that Prisma is not handling ctrl-c due to the fact that it allows the name to be unentered.

(I haven't been able to find a way to send a sigint signal.)

Either the prisma specs will change or it will send a PR, but it's better to wait
