### ISSUE TITLE
Layout missing in new app?

### ISSUE THREAD

**Issue by cktang88** [blitz-js/blitz#1131]
### What is the problem?

New app fails to compile after generating the initial `project` migration as stated in the initial app page.

### Steps to Reproduce

```bash
blitz new . # create new app in current folder
blitz start
```
Then followed the instructions on the initial app page:
```
blitz generate all project name:string
blitz db generate
```

### Versions

![image](https://user-images.githubusercontent.com/10319942/93718124-a3552880-fb3f-11ea-911b-6e48da0da5db.png)

### Other

Please include applicable logs and screenshots that show your problem.
![image](https://user-images.githubusercontent.com/10319942/93718132-b2d47180-fb3f-11ea-9df6-351ab599dbb6.png)

Notably the output from generating a new app shows the Layout file to be missing:
![image](https://user-images.githubusercontent.com/10319942/93718155-ddbec580-fb3f-11ea-96ca-6c146fc34a44.png)

**Comment by olivralex** [comment]
Hi @cktang88 👋,I'm imagine you're working with default Prisma 2 integration, did you actually execute` blitz db migrate` just after generate the project Model?

**Comment by cktang88** [comment]
Yep, I did execute `blitz db migrate` after generating that model.

I think the issue was I had used the global version of blitz (outdated `0.16.4`) and it was conflicting with the newer local version of blitzjs. Tried again with `npx blitz new .` and the issue seems to be gone!
