### ISSUE TITLE
Nexus Framework integration/recipe

### ISSUE THREAD

**Issue by gabrielcolson** [blitz-js/blitz#1138]
### What do you want and why?
 
I want to be able to use the nexus framework inside a blitz app, which could be ideally set up by a recipe.

### Possible implementation(s)

I kind of made it work in [this repo](https://github.com/gabrielcolson/blitz-nexus) following their guide on [how to make Nexus work with Nextjs](https://nexusjs.org/guides/recipes#use-with-nextjs).

Here are the problems I noted:

- In order to have the schema files get picked up by nextjs you have to `require` them in `api/graphql.ts`:
```
require("app/users/graphql/User")
require("app/users/graphql/Query")
// and many more...
```

- Nexus doesn't support [Absolute import aliases](https://github.com/graphql-nexus/nexus/issues/855) and my `require`s in `api/graphql.ts` and my `import`s in the rest of my code break the `nexus:reflection` script:
```
nexus reflection failed
Error: Cannot find module 'db'
```
- I can't use relative import in `api/graphql.ts` because it breaks the `blitz start` command:
```
error - ./pages/api/graphql.ts:5:0
Module not found: Can't resolve '../users/graphql/User'
```
The fact that the error points to `pages/api/graphql.ts` instead of `app/api/graphql.ts` may indicates that the `require`s are not transpiled correctly by blitz.

- The GraphQL playground doesn't work. I couldn't find any related issue on nexus so it may come from Blitz:
![image](https://user-images.githubusercontent.com/33499903/93871682-51430d00-fccf-11ea-871b-76e02fc2ed78.png)

### Notes
- [This issue](https://github.com/graphql-nexus/nexus/issues/782) tracks the support of serverless by Nexus
- While we find a solution for all of this, I might get back to [`@nexus/schema`](https://github.com/graphql-nexus/schema) and maybe write a recipe for it

**Comment by flybayer** [comment]
Thanks @gabrielcolson! 

This is available to work on for anyone who wants to.

**Comment by gabrielcolson** [comment]
Never mind. The Prisma team just announced they are [stopping the development of the Nexus Framework](https://github.com/prisma-labs/graphql-framework-experiment/issues/1432). I wonder if the integration with `@nexus/schema` is worth a recipe.
