### ISSUE TITLE
Issues when debugging in VSCode

### ISSUE THREAD

**Issue by lazarnikolov94** [blitz-js/blitz#1145]
### What is the problem?
VSCode's nodejs debugger is not working as it should. It runs the process successfully, but no breakpoints are being hit. I'm successfully debugging the front-end using the chrome launch configuration, but I can't debug the server-side code, the mutations for example.
### Steps to Reproduce

1. Create an empty new Blitz project: `blitz new appName` and open in VSCode
2. Create `.vscode` and `launch.json` and add the following launch configuration:
```json
{
    "type": "node",
    "request": "launch",
    "name": "Next: Node",
    "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/blitz",
    "runtimeArgs": ["start", "--inspect"],
    "cwd": "${workspaceFolder}",
    "sourceMapPathOverrides": {
        "webpack:///*": "${workspaceFolder}/*"
    },
    "port": 9229,
    "console": "integratedTerminal"
}
```
3. Hit F5. Add a breakpoint in `app/auth/mutations/login.ts` on line 7 for example. Navigate to the login screen and perform the login process. It should hit the breakpoint, but it doesn't. I've copied and modified the launch script from one of my other Next JS projects in which it works, I am able to debug the server-side code successfully without issues.

### Versions

```
0.23.0
```

### Other
![image](https://user-images.githubusercontent.com/5396211/94059935-6f019680-fde3-11ea-9a41-27af597cbd51.png)

![image](https://user-images.githubusercontent.com/5396211/94059968-7cb71c00-fde3-11ea-9500-2f018b770704.png)

**Comment by ryardley** [comment]
Thanks for reporting this. You might have to add the breakpoint to the development cache `.blitz/caches/dev` as a work around. Perhaps we need to add source maps to the compilation process which might allow for this to work.

**Comment by flybayer** [comment]
Going to close this as stale. Feel free to re-open if needed.

**Comment by jmcelreavey** [comment]
Can we reopen this? I feel it would be really nice to just start the debugger similarly to how you would debug in nextjs?

**Comment by flybayer** [comment]
We can, but there's no action item on this except for finish the nextjs fork migration which is in progress as we speak. This will then automatically fix itself.
