### ISSUE TITLE
New blitz server optimization not handing removed files

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1151]
### What is the problem?

New blitz server optimization not handing when files are removed

### Steps to Reproduce

In the monorepo:

1. `git checkout bug`
2. `blitz start`
3. `git checkout canary`
4. `blitz start`
5. Now access the `/sessions` url and it works, but it should not because `/session` only exists on the `bug` branch, not on the `canary` branch.

### Versions

```
latest canary
```

**Comment by ryardley** [comment]
Hmm interesting. It is designed to manage that maybe I missed a file event. Will investigate.

**Comment by flybayer** [comment]
One one occasion the queries/mutations were removed properly but not the pages. Another time nothing was removed.

**Comment by ryardley** [comment]
Looks like there was a misconfiguration I probably caused and files were never being deleted anyway. Looking at it this morning.
