### ISSUE TITLE
Prefix session cookies with unique identifier

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1153]
### What do you want and why?

Currently all our session cookies are always named the same like `sSessionToken`. This causes a problem when you are running different blitz apps on the same domain, like `localhost` for example. 

This means you can only be logged in to one blitz app on a domain at a time. We should fix this.

### Possible implementation(s)

We want to use some type of unique identifier for the app. For example we could use the name field in package.json by default and also expose a config item in session middleware to set it manually.

One tricky thing is that we also need to know the prefix in the browser to read the right cookies. So somehow this config item will need to be available there.

**Comment by sandulat** [comment]
@flybayer The only solution that comes to my mind is to use the `publicRuntimeConfig` option in the config, instead of passing options to the session middleware.
https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration

If that's ok, I could work on this.
