### ISSUE TITLE
Query object is changing on every render - needs to use useMemo

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1154]
### What is the problem?

`const query = useRouterQuery()` returns a new object on every single render, causing bugs in apps that expect it to only change if the contents of query changed.

### How to fix

[Here's the line of code that needs changed to use `useMemo`](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/use-router-query.ts#L6).

**Comment by TatisLois** [comment]
Hey! I have some time and would like to take this up!

**Comment by flybayer** [comment]
@TatisLois already closed in #1157! (notice that label was `status/in-review`. Issues that are open to work on are labeled `states/ready-to-work-on` :)
