### ISSUE TITLE
useParams and useParam is changing on every render - needs to use useMemo

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1155]
### What is the problem?

`const params = useParams()` returns a new object on every single render, causing bugs in apps that expect it to only change if the contents have changed.

Also have the same problem for `useParam()`

### How to fix

Here's the code for [useParams](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/use-params.ts#L47) and [useParam](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/use-params.ts#L90) that needs optimized to use `useMemo`.

**Comment by bhatvikrant** [comment]
Hey @flybayer is this still available to work on?

**Comment by flybayer** [comment]
@bhatvikrant no, PR is in review (you can tell because it's no longer labeled `status/ready-to-work-on`

**Comment by bhatvikrant** [comment]
Oh okay, @flybayer thankyou
