### ISSUE TITLE
Enforce the required node version to the user using the blitz cli (including blitz new, blitz install, ...)

### ISSUE THREAD

**Issue by jbFeDev** [blitz-js/blitz#1162]
### What is the problem?

If you're on a older Node version (< 12) you'll see what appears like a Node version warning ("You are using an unsupported version of Node.js. **Consider** switching to v12 or newer."), but actually is more required than optional. I could successfully scaffold out the application and build it, even though I'm on an unsupported Node version. The errors appear afterwards when trying to signup or create new models.

### Steps to Reproduce

1. Install/use Node 10.19
2. blitz new blitz-app (you'll see the message)
3. signup

### Versions

```
macOS Catalina | darwin-x64 | Node: v10.19.0

blitz: 0.23.0 (global)
blitz: 0.23.0 (local)

  Package manager: yarn 
  System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 497.67 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v10.19.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/cli: 2.7.1 => 2.7.1 
    @prisma/client: 2.7.1 => 2.7.1 
    blitz: 0.23.0 => 0.23.0 
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    typescript: 4.0.3 => 4.0.3 
```

**Comment by nitaking** [comment]
@jbFeDev Thanks for creating the issue!
