### ISSUE TITLE
[Windows] Error: Failed to parse json from request to /api/projects/queries/getProject

### ISSUE THREAD

**Issue by AxDSan** [blitz-js/blitz#1178]
```
Call Stack
executeRpcCall/promise</_temp4<
..\..\..\node_modules\@blitzjs\core\dist\core.esm.js (1054:0)
```

I get that error when I try to submit an edit for a project. (no additional fields were modified or sent)

This is on a newly made, fresh project (`blitz new projname`), nothing else added outside of the app itself, this is all barebones except I have done `blitz generate all project name:string` and `blitz db migrate` that's all.

**Comment by flybayer** [comment]
@AxDSan sorry about that! Can you try `0.22.1` and see it it works there? I think this is maybe the same issue as #1174

**Comment by AxDSan** [comment]
> 
> 
> @AxDSan sorry about that! Can you try `0.22.1` and see it it works there? I think this is may be the same issue as #1174

Hi Brandon! Certainly!  I will check it out on `0.22.1` and will post back the results 👍

**Comment by flybayer** [comment]
Hmm ok, maybe a windows compatibility thing 🤔

**Comment by AxDSan** [comment]
Just to confirm, I just tested this using WSL in Ubuntu and it just works fine 👍 - It's definitely a Windows issue!

**Comment by flybayer** [comment]
@wKovacs64 any ideas on this?

**Comment by wKovacs64** [comment]
I'll take a look at this as soon as I can - may be a few though. 😬

**Comment by wKovacs64** [comment]
I can't seem to reproduce this on canary nor latest release.

Canary (local):

```
Windows 10 | win32-x64 | Node: v12.18.4

blitz: 0.23.2-canary.3 (local)

  Package manager: npm
  System:
    OS: Windows 10 10.0.18363
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 17.87 GB / 31.91 GB
  Binaries:
    Node: 12.18.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.8.0 => 2.8.0
    @prisma/client: 2.8.0 => 2.8.0
    blitz: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: 4.0.3 => 4.0.3
```

Latest release:

```
Windows 10 | win32-x64 | Node: v12.18.4

blitz: 0.23.2 (local)

  Package manager: yarn
  System:
    OS: Windows 10 10.0.18363
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 18.05 GB / 31.91 GB
  Binaries:
    Node: 12.18.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.8.0 => 2.8.0
    @prisma/client: 2.8.0 => 2.8.0
    blitz: 0.23.2 => 0.23.2
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8
    typescript: 4.0.3 => 4.0.3
```

Works as expected in both environments.

**Comment by svobik7** [comment]
@AxDSan I see no Typescript in your blitz -v output so your app was created as plain-js with `blitz new ... —js`, right?

I faced a similar error today so I think the reason is descibed here #1241. Is that what you see in your terminal output.

**Comment by AxDSan** [comment]
> @AxDSan I see no Typescript in your blitz -v output so your app was created as plain-js with `blitz new ... —js`, right?
> 
> I faced a similar error today so I think the reason is descibed here #1241. Is that what you see in your terminal output.

In my case, it was in a typescript project, it was not generated with the plain js flag.

**Comment by flybayer** [comment]
Closing as stale
