### ISSUE TITLE
Change all generated file paths to be kebab-case

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1185]
### What do you want and why?

Currently for a model of `TestResult` you end up with a path of
```
app/testsResults/pages/test-results/index.tsx
```

And I'm finding that I keep expecting it to instead be

```
app/test-results/pages/test-results/index.tsx
```

I think it's better for everything to be consistent.

### Possible implementation(s)

We would need to change [this method](https://github.com/blitz-js/blitz/blob/canary/packages/generator/src/generators/page-generator.ts#L49) in all the generators.

**Comment by ntgussoni** [comment]
Totally agree, especially since I've had nightmares with git and case sensitivity in folders.

**Comment by Lundbyit** [comment]
Hi, is it ok if I give this one a try?

**Comment by flybayer** [comment]
@Lundbyit absolutely!

**Comment by engelkes-finstreet** [comment]
@Lundbyit [Here](https://github.com/blitz-js/blitz/blob/canary/packages/generator/src/utils/kebab-case.ts) is a utility function to transform camelCase into kebab-case.

**Comment by Lundbyit** [comment]
@engelkes-finstreet Thanks for the pointer.

I'm new to open source and I see that you @brunocrosier have submitted a PR.

Should I continue to work on the issue or will you @brunocrosier continue to work on it?

Another question regarding the issue. Should we change getTargetDirectory method as well to use kebab case in other generators? In that case I would like a chance to do a PR for that.

**Comment by brunocrosier** [comment]
My bad @Lundbyit I missed your comments on this thread. I'm not 100% sure that my PR actually works as I'm having trouble setting up local testing. I honestly have no idea re: `getTargetDirectory`, let's see what @flybayer thinks :)

**Comment by Lundbyit** [comment]
No worries, I'm thinking that both context and modelNames should be camelCased.

So maybe `return camelCaseToKebabCase(context + this.options.modelNames)`?

Not sure how the camelCaseToKebabCase handles '/' though
