### ISSUE TITLE
Dev server not processing moved folders

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1186]
### What is the problem?

Dev server is not processing moved folders

### Steps to Reproduce

1. `blitz g all task name`
2. `blitz db migrate`
3. `blitz start`
4. Access `/tasks` successfully
5. `mkdir app/tasks/pages/admin`
6. `mv app/tasks/pages/tasks app/tasks/pages/admin/`
7. Can't access `/admin/tasks`

You can see files in cache aren't moved:

```
~/c/b/e/store> t .blitz/caches/dev/pages
.blitz/caches/dev/pages
└── tasks
    ├── [taskId]
    │   └── edit.tsx
    ├── [taskId].tsx
    ├── index.tsx
    └── new.tsx
```

### Versions

```
0.23.2-canary.2
```

**Comment by ryardley** [comment]
hmm I can't reproduce at this point

**Comment by flybayer** [comment]
Ok, will close for now
