### ISSUE TITLE
Query remaining cached after navigating via router.push

### ISSUE THREAD

**Issue by johncantrell97** [blitz-js/blitz#1196]
### What is the problem?

After upgrading my version of Blitz to 0.23.2-canary.2 (from 0.21 I believe) I noticed that my queries were being cached even after navigating to different pages.  

### Steps to Reproduce

The flow is start on a list page that performs a query to fetch some models.  Navigate to a /new page that allows you to create a new model that would normally be returned in the list query.  On success of the form submit navigate back to the list page.

In blitz 0.21 the query would be re-run (and cache invalidated) and the new item would appear in the list.  In blitz 0.23.2-canary.2 (and I think it was also happening in 0.22) the new item is not appearing in the list.  This leaves me to believe the query is being cached even when multiple router.push()'s have happened since the initial fetch. 

### Versions

blitz: 0.23.2-canary.2 (global)
blitz: 0.23.2-canary.2 (local)

  Package manager: npm 
  System:
    OS: Linux 4.19 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 4.24 GB / 50.14 GB
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: Not Found
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.7.1 => 2.7.1 
    @prisma/client: 2.7.1 => 2.7.1 
    blitz: 0.23.2-canary.2 => 0.23.2-canary.2 
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    typescript: 4.0.2 => 4.0.2

**Comment by flybayer** [comment]
Yeah react-query changed something here 🤔 

We currently don't do auto cache invalidation. See https://github.com/blitz-js/blitz/issues/586

Here's the work around: https://github.com/blitz-js/blitz/blob/canary/examples/store/app/admin/pages/admin/products/%5Bid%5D.tsx#L16-L17

**Comment by johncantrell97** [comment]
shouldn't react-query's query caches not live after a router.push navigation? seems odd that you should have to know which queries to invalidate cache of when they aren't even on the same page.

**Comment by johncantrell97** [comment]
According to react-query docs the navigation away from the list page should trigger an unmounting of the query, pushing the query cache timeout to start ticking.  When the query is re-mounted upon navigating back to the page:

"Before the cache timeout has completed another instance of useQuery('todos', fetchTodos) mounts. The query immediately returns the available cached value while the fetchTodos function is being run in the background to populate the query with a fresh value."

Sounds like it should immediately display the cached results but also trigger the query again to refresh.  This used to work in blitz but is not happening anymore as far as I can tell.

**Comment by flybayer** [comment]
Ok must be a bug in RQ! Open an issue on RQ if you can make a minimal reproduction with plain RQ.

**Comment by johncantrell97** [comment]
Isn't it possible it's a bug with blitz's wrapper around RQ's useQuery?

**Comment by johncantrell97** [comment]
jk here it is: https://github.com/tannerlinsley/react-query/issues/1059

looks like an issue when using useQuery with suspense enabled like we do in blitz
