### ISSUE TITLE
Add better error message when trying to use regular function with blitz useQuery hooks

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1206]
### What do you want and why?

Currently if you try to use your own regular fetch function with Blitz `useQuery` and related hooks (including `useMutation`), you will get an error like the following:

```
TypeError: Cannot read property 'apiUrl' of undefined
```

We need to change that be a helpful error.

### Possible implementation(s)

Something like this

```
It looks like you are trying to use Blitz's useQuery to fetch from third-party APIs. To do that, import useQuery directly from "react-query".
```

Here's the file where the useQuery source is: https://github.com/blitz-js/blitz/blob/canary/packages/core/src/use-query-hooks.ts

**Comment by jamiedavenport** [comment]
Could I pick this up?

**Comment by Zeko369** [comment]
@jamiedavenport go ahead
