### ISSUE TITLE
`blitz seed` command needs changed to `blitz db seed`

### ISSUE THREAD

**Issue by simonedelmann** [blitz-js/blitz#1220]
### What is the problem?

In the canary documentation the new seeding command is written as `blitz db seed` but actually it is implemented as `blitz seed`. 

(Personally I would prefer `blitz db seed`.)

### Versions

0.23.2-canary.3

**Comment by nitaking** [comment]
Thanks @simonedelmann 
I also think it should match the `blitz db seed`.
