### ISSUE TITLE
Blitz console not loading queries/mutations

### ISSUE THREAD

**Issue by simonedelmann** [blitz-js/blitz#1233]
### What is the problem?

Blitz console does not find any queries/mutations. (Furthermore it does not find any files except those which are in `integrations` or `utils` folder.)

### Steps to Reproduce

1. New blitz app
2. Rename `auth-utils.ts` to `auth.ts` (to avoid side-effects because of kebab-case)
3. Move `auth.ts` to `/integrations` folder
4. Open blitz console and enter `auth`. => It works. 
5. Move `auth.ts` to another location and check if it can be found: 
```
// These works
integrations/auth.ts
utils/auth.ts

// These does not work
integration/auth.ts
app/auth.ts
app/auth/auth.ts
db/auth.ts
/auth.ts
```

The same is for all queries/mutations. There are not found until their files are in `integrations` or `utils`. So seems like the Module resolving is broken somehow. 

### Versions

```
0.23.2-canary.3
```

**Comment by Alucard17** [comment]
Hey @flybayer can I work on this.

**Comment by flybayer** [comment]
@Alucard17 yes!

**Comment by Alucard17** [comment]
Hey @flybayer @simonedelmann as per the code mentioned below,
It expects the queries and mutation should be in app directory, is this behavior intentional or should I change it ?
https://github.com/blitz-js/blitz/blob/bd1063a965eeccfd091a199cdc5c3ab57d4832ba/packages/repl/src/utils/load-blitz.ts#L11

**Comment by flybayer** [comment]
@Alucard17 yes, queries and mutations must be inside app.

**Comment by flybayer** [comment]
@Alucard17 did you make any progress on this? Or should I mark it back for anyone else to work on?

**Comment by flybayer** [comment]
fyi for anyone, related code is here: https://github.com/blitz-js/blitz/blob/canary/packages/repl/src/utils/load-blitz.ts

**Comment by denvaar** [comment]
Is there a workaround for this while it's being worked on?

**Comment by flybayer** [comment]
@denvaar should be able to manually require it inside the repl, something like this:

```
const getUsers = require('app/users/queries/getUsers').default
```
