### ISSUE TITLE
Add `--no-verify` to initial git commit command

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1266]
### What do you want and why?

We run `git commit` during new app setup. We need to add `--no-verify` to the git args to skip running husky during this step, because it's not needed.

### Possible implementation(s)

Here's the line where this needs added: https://github.com/blitz-js/blitz/blob/canary/packages/generator/src/generators/app-generator.ts#L231

**Comment by clgeoio** [comment]
i'll take this one
