### ISSUE TITLE
Issues Serializing Dates in getServerSideProps from ssrQuery / invokeWithMiddleware

### ISSUE THREAD

**Issue by mattfwood** [blitz-js/blitz#1275]
### What is the problem?
When trying to make a server-side query for a model with a `DateTime` object, i'm still getting issues serializing it properly:

![image](https://user-images.githubusercontent.com/22530815/95477865-6dd97900-094e-11eb-81b5-70292da78e1c.png)

![image](https://user-images.githubusercontent.com/22530815/95477889-75008700-094e-11eb-9e25-af796b5d93ca.png)

### Steps to Reproduce

1. Create a model with a `DateTime` field
2. Try to query it through `getServerSideProps` and `invokeWithMiddleware`
3. Page won't render, throwing this error:

```
Error: Error serializing `.tasks[0].createdAt` returned from `getServerSideProps` in "/".
Reason: `object` ("[object Date]") cannot be serialized as JSON. Please only return JSON serializable data types.
```

### Versions

```
macOS Catalina | darwin-x64 | Node: v12.14.1

blitz: 0.24.1 (local)

  Package manager: yarn 
  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 229.56 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - /var/folders/jv/731yqwbj6cv8xzz3dg3qy08r0000gn/T/yarn--1602169845788-0.6291613000501732/node
    Yarn: 1.22.5 - /var/folders/jv/731yqwbj6cv8xzz3dg3qy08r0000gn/T/yarn--1602169845788-0.6291613000501732/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/cli: 2.7.1 => 2.7.1 
    @prisma/client: 2.7.1 => 2.7.1 
    blitz: 0.24.1 => 0.24.1 
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    typescript: 4.0.3 => 4.0.3 
```

I can try putting together a reproduction of this in a bit, but I remember this issue being discussed previously.

I'd be happy to try and fix it, but might need a bit of help being pointed in the right direction.

My best guess right now is to start here?

https://github.com/blitz-js/blitz/blob/canary/packages/core/src/invoke.ts

**Comment by mattfwood** [comment]
Well, after a bit more digging I realized this is probably more of a Next.js issue than Blitz issue.

https://github.com/blitz-js/superjson#using-with-nextjs

If possible, maybe we can check if an object has any `Date` objects, and we could show a more descriptive error saying to use this babel plugin?

**Comment by LoriKarikari** [comment]
There is an issue open to make `superjson` the default: #1043
