### ISSUE TITLE
Export `next/config` in `@blitz/core`

### ISSUE THREAD

**Issue by LoriKarikari** [blitz-js/blitz#1286]
### What do you want and why?

There currently isn't a Blitz equivalent to `next/config`. If you want to use it you have to do `import getConfig from 'next/config'`. This should become `import { getConfig } from 'blitz'`.

### Possible implementation(s)
This export needs to be added to this file: 
https://github.com/blitz-js/blitz/blob/canary/packages/core/src/index.ts

**Comment by davidlutta** [comment]
Hello, open-source noob here 😅 with a question. 
Would the following implementation be satisfactory ? 
```js
export {getConfig as getConfig} from "next/config"
```

**Comment by flybayer** [comment]
@davidlutta this should even work!

```ts
export {getConfig} from "next/config"
```
