### ISSUE TITLE
Mutations incorrectly warns about deprecation even when using invoke()

### ISSUE THREAD

**Issue by aericson** [blitz-js/blitz#1297]
### What is the problem?
Even when using `invoke()` with mutations one will still get the warning `Directly calling queries/mutations is deprecated in favor of invoke(queryFn, params)`. I believe that the cause is that `fromInvoke` is being passed down to the `mutate` function that was returned by react-query which doesn't pass that on to the resolver.

I investigated it and tried to fix it but I got stuck. I can take this issue myself but would need some pointers.

### Steps to Reproduce

Add a mutation call using invoke such as:
```
             const [createProductMutation] = useMutation(createProduct)
-            const product = await createProductMutation({data})
+            const product = await invoke(createProductMutation, {data})
```

You will still see the warning.
### Versions
Using canary branch and examples/store app.
```
You are using alpha software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: /Users/aericson/projects/blitz/packages/blitz/dist/index.js
debug: cliPkgPath: /Users/aericson/projects/blitz/packages/cli/lib/src/index.js 

macOS Big Sur | darwin-x64 | Node: v14.12.0

blitz: 0.24.1 (global)
blitz: 0.24.1 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.0
    CPU: (4) x64 Intel(R) Core(TM) i7-6660U CPU @ 2.40GHz
    Memory: 85.56 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.12.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/cli: Not Found
    @prisma/client: Not Found
    blitz: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: 4.0.3 => 4.0.3 
```

**Comment by AxDSan** [comment]
This is weird, I'm on this and I'm not getting the error anymore (I used to get it before whereas I was doing a direct mutation/query call, but I switched to `invoke()` and it's not happening anymore.)

![](https://i.imgur.com/bgB2fcP.jpg)

**Comment by flybayer** [comment]
@aericson in you example, invoke is not needed. This is correct:

```ts
const [createProductMutation] = useMutation(createProduct)
const product = await createProductMutation({data})
```

Is it possible you have another place in your app that's using the old method of directly calling a resolver? Maybe the `useCurrentUser()` hook or something?

**Comment by aericson** [comment]
> @aericson in your example, invoke is not needed. This is correct:
> 
> ```ts
> const [createProductMutation] = useMutation(createProduct)
> const product = await createProductMutation({data})
> ```
> 
> Is it possible you have another place in your app that's using the old method of directly calling a resolver? Maybe the `useCurrentUser()` hook or something?


It's from the examples/store app when creating a product. I'll take a better look tomorrow.

**Comment by aericson** [comment]
I just checked it again, and I'm pretty sure it's the mutation. I put a print right next to the warning.

<img width="474" alt="Screen Shot 2020-10-12 at 21 23 12" src="https://user-images.githubusercontent.com/692542/95783018-44fc0f80-0cd1-11eb-8c35-a0a964135a29.png">

here is the print:
<img width="280" alt="Screen Shot 2020-10-12 at 21 21 44" src="https://user-images.githubusercontent.com/692542/95783066-58a77600-0cd1-11eb-9fda-9527806dd375.png">

and here is the stacktrace of the exception:
<img width="611" alt="Screen Shot 2020-10-12 at 21 21 53" src="https://user-images.githubusercontent.com/692542/95783037-4fb6a480-0cd1-11eb-8e2e-3bfa5f155b96.png">

**Comment by flybayer** [comment]
Ok yeah I agree. This line needs changed: https://github.com/blitz-js/blitz/blob/canary/packages/core/src/use-mutation.ts#L20. It needs to be changed to have an extra function wrapper similar [to this](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/use-query-hooks.ts#L46-L47).
