### ISSUE TITLE
Requesting Security Review/Pen Testing

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1308]
### What do you want and why?

I want some security professionals to review our authentication code and perform pen testing to see if we possibly have any vulnerabilities.

Here's our docs on auth implementation](https://blitzjs.com/docs/session-management#how-it-works).

And here's the three main files pertaining to auth:

- https://github.com/blitz-js/blitz/blob/canary/packages/core/src/supertokens.ts
- https://github.com/blitz-js/blitz/blob/canary/packages/server/src/supertokens.ts
- https://github.com/blitz-js/blitz/blob/canary/packages/core/src/rpc.ts

**Comment by jose-donato** [comment]
There is any production website live using blitz that we can target?

**Comment by Skn0tt** [comment]
Is it required that you target the live version or could I setup another deployment of quirrel.dev one that's not critical?

**Comment by flybayer** [comment]
Probably you can use https://blitz-jobs.com. Ok @sandulat?

**Comment by jose-donato** [comment]
> Is it required that you target the live version or could I setup another deployment of quirrel.dev one that's not critical?
It would be more realistic doing the pentest on a live version.

> Probably you can use https://blitz-jobs.com. Ok @sandulat?
That would work.

I will try to do everything locally and only if necessary fallback to blitz-jobs.com (if @sandulat gives permission, of course)

**Comment by MrLeebo** [comment]
One thing we could consider doing is set up an opinionated default set of security headers for new blitz apps based on [OWASP Secure Headers](https://owasp.org/www-project-secure-headers/) using [Next.js Custom Headers](https://nextjs.org/docs/api-reference/next.config.js/headers)

**Comment by MrLeebo** [comment]
Here are the header [scan results](https://securityheaders.com/?q=https%3A%2F%2Fquirrel.dev%2F&hide=on&followRedirects=on) for quirrel.dev as an example

**Comment by sandulat** [comment]
@flybayer @jose-donato Sorry for the delay! It's ok to test on https://blitz-jobs.com/.

**Comment by flybayer** [comment]
@MrLeebo great idea on setting up secure headers by default somehow

**Comment by MrLeebo** [comment]
@flybayer I propose [we put a page on blitzjs.com for reporting vulnerabilities](https://github.com/blitz-js/blitzjs.com/issues/271) because even if we perform our own pen testing, there is always the possibility of a non-contributor discovering an issue that we don't know about.
