### ISSUE TITLE
Add CLI e2e tests

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#132]
Currently the only tests for the blitz cli are unit tests. We need to add e2e tests for all the commands to ensure they actually work properly.

You are welcome to submit a PR to add e2e tests to just one command. Don't feel like your PR has to be all or nothing :)

**Comment by ryardley** [comment]
Perhaps this can be related to https://github.com/blitz-js/blitz/issues ? I think it would be nice if we can somehow coordinate these.

**Comment by flybayer** [comment]
Inspiration: https://github.com/lirantal/pie-my-vulns/blob/master/.circleci/config.yml

**Comment by flybayer** [comment]
We sorta have an e2e test on blitz new, so closing this issue. We can open new issues for specific, single e2e tests if needed.
