### ISSUE TITLE
Add incremental config to new app's tsconfig.json

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1346]
### What do you want and why?

Add the following to the [new app template tsconfig](https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/app/tsconfig.json), in the `compilerOptions`.

```
    "incremental": true,
    "tsBuildInfoFile": ".tsbuildinfo",
```

**Comment by dulcehc** [comment]
I will work on this
