### ISSUE TITLE
Font appears to load after content on docs site

### ISSUE THREAD

**Issue by goleary** [blitz-js/blitz#1349]
### What is the problem?
Font appears to load after content on docs site
### Steps to Reproduce

1. goto https://blitzjs.com/docs/tutorial
2. see font of text change after it becomes visible.

### Other

Windows 10 Chrome LTS

**Comment by flybayer** [comment]
We are using a web font, so that's just how this works, unfortunately!

**Comment by goleary** [comment]
That's a bummer.  I would've imagined there's some way to load the font files before displaying the text but perhaps that would also make for a bad experience (longer time till text is visible).

I don't have any experience working with web fonts so this is all conjecture.

What's surprising to me is that even on subsequent visits, I still see the same thing.  I'd also think the font resources could be cached so that a user only experiences this once.
