### ISSUE TITLE
Add help information to `blitz db` command

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#135]
Currently `blitz db` and `blitz db -h` both print an error about an unsupported command.

Both of these should print a list of supported commands.

The alpha user guide lists the supported `blitz db` commands: https://github.com/blitz-js/blitz/blob/flybayer-patch-1/USER_GUIDE.md#blitz-cli-commands

**Comment by sijad** [comment]
can I take this?

**Comment by flybayer** [comment]
@sijad You bet!
