### ISSUE TITLE
Move 'tsc' command to pre-push hook

### ISSUE THREAD

**Issue by egonm12** [blitz-js/blitz#1353]
### What is the problem?
I want to suggest to move the `tsc` command from the `pre-commit` hook to the `pre-push` hook in the Blitz boilerplate project. The reason for this change is that I find myself quite often in the middle of changes where I only want to commit a chunk of it (e.g. a style change). 
Because there is no official way of running `tsc` on specific files you are not able to only check for errors in your staged files. Therefore, when `tsc` is running on the `pre-commit` hook I am not able to commit my changes in chunks when there is a TS error in some other file that is not related at all (unless I use `--no-verify` of course).
If you move `tsc` to the `pre-push` hook you are able to split your commits in chunks while still not being able to push code that breaks your application.

### Steps to Reproduce
1. Make a change in some random file that will trigger a TS error. E.g.
```
// Type 'number' is not assignable to type 'string'
const foo: string = 1;
```
2. Make a change in some other random file that doesn't trigger a TS error.
3. Stage the file that has no TS error
4. When committing this file it will trigger a TS error and you can not commit the change.

**Comment by flybayer** [comment]
You have a great point. Here's where this needs changed: https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/app/package.json#L23

**Comment by machadolucasvp** [comment]
I would appreciate working on that, can I go :) ?

**Comment by JoseRFelix** [comment]
I will be doing this!
