### ISSUE TITLE
Add tests to blitz core

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#14]
Blitz core is currently untested. We need to add comprehensive tests. This would be a good task for anyone who wants it!

Comment below if you're getting ready to work on it

**Comment by jasonblalock** [comment]
I'd love to take a crack at this

**Comment by MrLeebo** [comment]
I checked it out, tried to use the nextjs tests as a template, but the `next-test-utils` dependency isn't public so we'd have to replace that or come at it a different way.

**Comment by jasonblalock** [comment]
Yeah, @MrLeebo  I see what you mean. I was able to copy the test-utils and get that compiling properly (not that I think that's the ideal solution). But there's a ton of config/packages that goes into their integration tests that I'm not sure the right move is to copy it. Not to mention they use selenium for all their stuff and I don't know if that's the direction we want to be entrenched.

I'm going to back away from this one for now. I'm going out of town in a day and it's going to take a deeper dive than I'll have time for this week to build out a testing harness. I don't want to be in the way.

**Comment by emeraldsanto** [comment]
If by any chance this hasn't been taken care of when I get back home on Sunday, I will gladly start working on it!

**Comment by MrLeebo** [comment]
I started a PR (#16), but I'm sure there's more testing to be done.
