### ISSUE TITLE
yarn build returns 0 even if it failed

### ISSUE THREAD

**Issue by hardfire** [blitz-js/blitz#1403]
### What is the problem?
I run `yarn build` and `yarn test` on gitlab ci to run tests. `yarn build` returns 0 even if it fails and this causes the ci enviornment to continue instead of reporting an error.

### Steps to Reproduce

1. setup app to fail on yarn build
2. run `yarn build`
3. run `$?` on cli to see exit code

### Versions
24.3
```
output of `blitz --version --verbose`
```

### Other

Please include applicable logs and screenshots that show your problem.

**Comment by flybayer** [comment]
@hardfire this should be fixed as of `v0.25.0-canary.0` or higher

**Comment by flybayer** [comment]
Should be fixed in `0.25.0`.
