### ISSUE TITLE
Antd and freezenig

### ISSUE THREAD

**Issue by Daidalos117** [blitz-js/blitz#1408]
### What is the problem?
When using Antd, some components make app to freeze. In pure Next.js everything works fine. 
Next version: https://codesandbox.io/s/unruffled-hawking-d188t?file=/pages/index.js
Blitz version: https://codesandbox.io/s/angry-haslett-vpo0m?file=/app/pages/index.tsx
It's slightly different, because I cannot make the less import to work in codesandbox. But it works the same on localhost where less import is working fine.

### Steps to Reproduce

1. Install Blitz & Antd
2. Use select (or any other dynamic) component
3. Try to open it
4. Tab freezes

### Versions

```
macOS Catalina | darwin-x64 | Node: v12.19.0

blitz: 0.24.3 (global)
blitz: 0.24.3 (local)

  Package manager: yarn 
  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 24.00 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.19.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.9.0 => 2.9.0 
    @prisma/client: 2.9.0 => 2.9.0 
    blitz: 0.24.3 => 0.24.3 
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    typescript: 4.0.3 => 4.0.3 
```
I tried to debug it, but I didn't managed to very well. Anyone any idea? Maybe someone with working Antd in Blitz?
Big thanks anyways :)

**Comment by isoppp** [comment]
Same here.
I’m not sure but I doubt this might be something related to Concurrent Mode or the experimental React version that blitz.js is using.
UI Frameworks seem to need to be making a lot of effort to support v17 and especially concurrent mode.

**Comment by Daidalos117** [comment]
Thank you for you reply, you showed me the right direction. I made few test and Antd is cool with React 17, [but doesn't really like the concurrent mode](https://codesandbox.io/s/agitated-feather-bu40g?file=/src/index.js). Closing, because it's not Blitz fault of course.

**Comment by maotora** [comment]
Hi, @Daidalos117 making a follow-up, how did you solve this?

**Comment by MichaelBradetLegris** [comment]
If anyone is still experiencing this, this fix worked for me:

blitz.config.js
```
module.exports = {
  experimental: {
    reactMode: "legacy",
  },
}
```

Reference (in case the API changes):
https://blitzjs.com/docs/blitz-config#experimental

This will presumably get fixed when antd is up and running with the experimental react features. but this will have to do for now.
