### ISSUE TITLE
The blitz dev cache must be busted if blitz version changes.

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1421]
### What do you want and why?

Currently the `.blitz` dev cache is not cleared between `blitz start` invocations for performance. That's great, but we've found that when the blitz version changes we need to bust that cache. 

https://github.com/blitz-js/blitz/issues/1407 is an example error caused by the lack of this.

### Possible implementation(s)

Basically we want to clean the cache anytime the installed blitz version changes.

Setting [this `clean` config item](https://github.com/blitz-js/blitz/blob/canary/packages/server/src/dev.ts#L26) to true will clean the cache. That spot is a possible place to do this.

**Comment by rayandrews** [comment]
Let me elaborate.

If blitz version in `package.json` is changed, we need to set `clean` in config to `true` right?

**Comment by flybayer** [comment]
@rayandrews yes. So we need to cache the blitz version somehow inside `.blitz` so that each time `blitz start` runs, we can check the current blitz version with the cached version.

Also, we need to check the actual installed version of blitz, not just the version range in the app package.json. I think we can get the actual installed version with something like this: 

```ts
const pkgJson = require(path.join(require.resolve('blitz'), 'package.json'))
```

**Comment by rayandrews** [comment]
I see, it makes sense now for the installed version one @flybayer 

However, how about the blitz version inside `.blitz`? Do we just use the `package.json` inside `.blitz` folder?

**Comment by flybayer** [comment]
No, we don't currently story the blitz version. We could add a new file or maybe add a new field to `.blitz/caches/dev/_manifest.json`.

@ryardley any opinion on this?

**Comment by rayandrews** [comment]
I see, we can cached the version via this [function](https://github.com/blitz-js/blitz/blob/canary/packages/server/src/stages/manifest/index.ts#L71)

and re-read it while running in development to make sure the version is same or not @flybayer

**Comment by ryardley** [comment]
Maybe we can store the blitz version in the cache hash?

**Comment by rayandrews** [comment]
could you give me the pointer of the cache hash?

I want to work on this.

is it similar like `file-hash` [here](https://github.com/blitz-js/blitz/blob/canary/packages/file-pipeline/src/pipeline.ts#L80) or different? 

@flybayer @ryardley

**Comment by ryardley** [comment]
@rayandrews I was talking about the file tree hashing happening here: https://github.com/blitz-js/blitz/blob/canary/packages/server/src/build-hash.ts#L26

**Comment by rayandrews** [comment]
CMIIW, it is run only for `production` right?

so for summary:

- hash the `tree.hash` with `blitzVersion` with `sha1(tree.hash + blitzVersion)`
- add this feature to `development`
- and the rest is same like `production` command (checking the hash etc)

am I right? @ryardley

**Comment by ryardley** [comment]
Hmm maybe I am wrong and am misunderstanding this issue.

**Comment by rayandrews** [comment]
Got it @ryardley. 
I understand now thank you.

Count me in and I will make a PR.

Thank you @ryardley @flybayer 

Best Regards
