### ISSUE TITLE
need help! Apps cannot be created in China

### ISSUE THREAD

**Issue by hehehai** [blitz-js/blitz#1425]
### What is the problem?
1.
![image](https://user-images.githubusercontent.com/12692552/98370090-f98d1500-2074-11eb-9232-f7b8cf6e3986.png)
This has always been the case. I have used the agent of NPM in China，But the installation is always in this state

2.
![image](https://user-images.githubusercontent.com/12692552/98370359-6bfdf500-2075-11eb-99d8-2a9446f39466.png)
This is when I execute new after installing Blitz using China's CNPM
![image](https://user-images.githubusercontent.com/12692552/98370435-8637d300-2075-11eb-8db5-8e32ee978ec9.png)
And then it just keeps going like that, and it doesn't move.

It may be a network problem or some dependency packet on local network access anomalies in China.

### Versions

latest

### Other

Please include applicable logs and screenshots that show your problem.

**Comment by flybayer** [comment]
@hehehai are you able to use `yarn` in china? By default `blitz new` will use `yarn` if it's installed.  You can use `blitz new myapp --npm` to use npm even if yarn is installed.

**Comment by flybayer** [comment]
@hehehai what was the solution? Maybe we can make this better

**Comment by hehehai** [comment]
When I use a network proxy it's work, I think it's a network problem, but I'm not sure which part of the dependency download is having a network problem
