### ISSUE TITLE
Trailing whitespace in prisma schema generated by blitz

### ISSUE THREAD

**Issue by akirabaruah** [blitz-js/blitz#1433]
### What is the problem?

Running `blitz generate` leaves trailing whitespace in the generated `schema.prisma` file.

### Steps to Reproduce

1. Run `blitz generate all question text hasMany:choices` then `git diff` to inspect changes in `db/schema.prisma` file. I see something like this:

![image](https://user-images.githubusercontent.com/6751517/98489679-e187d380-21e3-11eb-9753-0bacc750f2a3.png)

### Versions

```
➜ blitz --version --verbose
You are using alpha software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: <project>/node_modules/blitz/dist/index.js
debug: cliPkgPath: <project>/node_modules/@blitzjs/cli/lib/src/index.js 

Linux 5.8 | linux-x64 | Node: v12.19.0

blitz: 0.24.3 (global)
blitz: 0.24.3 (local)

  Package manager: yarn 
  System:
    OS: Linux 5.8 Fedora 32 (Workstation Edition) 32 (Workstation Edition)
    CPU: (4) x64 Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
    Memory: 2.85 GB / 7.46 GB
    Shell: 3.1.2 - /bin/fish
  Binaries:
    Node: 12.19.0 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.14.8 - ~/.local/npm/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.10.2 => 2.10.2 
    @prisma/client: 2.10.2 => 2.10.2 
    blitz: 0.24.3 => 0.24.3 
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    typescript: 4.0.5 => 4.0.5 

```

### Other

Arguably a lower priority, but figured I'd file this issue in case others felt weird about the trailing whitespace too :smile:

**Comment by jamiedavenport** [comment]
Thanks for raising this @akirabaruah! 

I think the relevant files are https://github.com/blitz-js/blitz/blob/canary/packages/generator/src/prisma/model.ts and https://github.com/blitz-js/blitz/blob/canary/packages/generator/src/prisma/field.ts

It's also worth noting that Prettier support has been requested (https://github.com/prisma/prisma/issues/1761) but since there's no timescale for this I think it's worth us sorting out these whitespace issues ourselves.

**Comment by abuuzayr** [comment]
Thanks @akirabaruah, @jamiedavenport !

I'm not entirely sure this is a bad thing though. This has helped me save some time when adding properties to model fields without spending time to format and keep them in line.

**Comment by akirabaruah** [comment]
Yeah, I see the benefit in not having to press the space bar a bunch of times just to align everything :smile:  Ideally, we'd get the best of both worlds (no trailing whitespace and easy alignment) using a tool like prettier.

For Blitz, it might be most productive to focus on getting that prisma prettier support or perhaps using one of the workarounds mentioned in https://github.com/prisma/prisma/issues/1761#issuecomment-721725245 in the meantime. Seems like @flybayer had thoughts on that too.

**Comment by abuuzayr** [comment]
That's true, totally agree that having prettier support would be the best case. If the spaces were not added by the generator however i'd probably add the spaces myself while I am working on the code (though if I'm on something like VS Code I probably can auto-format on save). so its a personal thing, easier for me to make sense of things sometimes. 

Blitz-wise, I have a feeling that @flybayer was referring to prettier being used to format `.prisma` files for git hooks and CI integrations. I also believe the workaround he added for blitz to format the `.prisma` schema is [here](https://github.com/blitz-js/blitz/blob/2efbe7bd51d8ec8a17a730bb9fc4b195ad2bde8b/packages/generator/src/prisma/model.ts#L4), where the `stringifyFieldsForPrinting` function adds spaces so field properties can be in a nice format when we wish to add some. 

So if you'd like, you can try and see if we can skip adding the whitespaces if the field has no properties?

**Comment by flybayer** [comment]
Going to close this in favor of letting prettier/vscode format it. We've added prettier prisma plugin so I think this should be formatted by default now.
