### ISSUE TITLE
NPM is assumed in the `package.json`

### ISSUE THREAD

**Issue by jamiedavenport** [blitz-js/blitz#1439]
### What is the problem?

`npm` is hardcoded in the `package.json` template but it'd be nice for Blitz to detect the package manager and use the correct one.

### Steps to Reproduce

1. `blitz new ...`

The `package.json` contains:
```
"husky": {
    "hooks": {
      "pre-commit": "lint-staged && pretty-quick --staged",
      "pre-push": "tsc && npm run lint && npm run test"
    }
  },
```

### Versions

```
blitz --version --verbose
You are using alpha software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: /Users/jamiedavenport/Documents/blitz/packages/blitz/dist/index.js
debug: cliPkgPath: /Users/jamiedavenport/Documents/blitz/packages/cli/lib/src/index.js 

macOS Mojave | darwin-x64 | Node: v14.13.1

blitz: 0.25.0-canary.2 (global)
blitz: 0.25.0-canary.2 (local)

  Package manager: yarn 
  System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 243.29 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 14.13.1 - ~/.nvm/versions/node/v14.13.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.13.1/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.10.2 => 2.10.2 
    @prisma/client: 2.10.2 => 2.10.2 
    blitz: 0.25.0-canary.2 => 0.25.0-canary.2 
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    typescript: 4.0.5 => 4.0.5 
```

### Other

I think we need to edit the https://github.com/blitz-js/blitz/blob/canary/packages/generator/src/generators/app-generator.ts to add a `packagemanager` template value and then modify https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/app/package.json to use the new template value instead of `npm`.

**Comment by flybayer** [comment]
I'm not totally sure if we want to do this or not 🤔 It would be a tiny improvement, but adds extra complexity to our template generation (we already have two options with JS & TS). Functionally it's same whether npm or yarn is used, and npm basically guaranteed to be installed.

**Comment by jamiedavenport** [comment]
After thinking about this more I do agree with you that in practice it doesn't matter. 

Since `yarn` itself complains about mixing both tools when installing, are we encouraging a bad practice by having both in the same project (even if it's just `npm run` in the git hooks)?

```
yarn
yarn install v1.22.10
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
```

**Comment by flybayer** [comment]
I think the only issue is if you mix installation with yarn/npm. Running scripts should be the same

**Comment by MrLeebo** [comment]
I think this proposal creates more of a maintenance burden and there isn't any benefit that I'm aware of for picking `yarn` over `npm` to run the scripts. Please let me know if you have a reason, but for now I'm going to close this to prioritize other cards.
