### ISSUE TITLE
Get chokidar errors when running blitz start on windows.

### ISSUE THREAD

**Issue by cwray-tech** [blitz-js/blitz#1461]
When starting blitz on a windows machine, the console outputs errors:
```bash
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'
```

**Comment by flybayer** [comment]
@cwray-tech what is the full output of `blitz -vV`?

Also, does this happen on a brand new blitz app?

**Comment by cwray-tech** [comment]
@flybayer I will close this issue.

**The reason that this problem exists is when there are dependencies in the package.json that have not been installed.**

_So, if you are experiencing this issue, make sure to run yarn before running blitz start!!_

### In the root directory where blitz is installed run:
```bash 
yarn 
```

In my case, I had added dependencies and forgot to run yarn before running blitz start the first time. Now that I ran yarn, the command is working fine.

If you run blitz start and then run yarn, **you may need to delete your .blitz folder and re-run blitz start** to see the issue go away.
