### ISSUE TITLE
Update Chakra UI Recipe for 1.0 (currently broken)

### ISSUE THREAD

**Issue by scisteffan** [blitz-js/blitz#1462]
### What is the problem?

After I run `blitz install chakra` I receive error messages on the website. I think it's because chakra has been updated to version 2 and the npm packages have now changed.

### Steps to Reproduce

1. `blitz new chakra-test`
2. `cd chakra-test`
3. `blitz install chakra`
4. `blitz start`

Following error appears:

<img width="649" alt="Screenshot 2020-11-14 at 16 13 15" src="https://user-images.githubusercontent.com/2676185/99151606-5c456880-2694-11eb-8414-e274ae820f44.png">

### Versions

```
steffanharris@Steffans-iMac chakra-test % blitz --version --verbose
You are using alpha software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: /Users/steffanharris/Code/BlitzJS/chakra-test/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/steffanharris/Code/BlitzJS/chakra-test/node_modules/@blitzjs/cli/lib/src/index.js 

macOS Big Sur | darwin-x64 | Node: v12.16.3

blitz: 0.25.0 (global)
blitz: 0.25.0 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 2.10 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v12.16.3/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.11.0 => 2.11.0 
    @prisma/client: 2.11.0 => 2.11.0 
    blitz: 0.25.0 => 0.25.0 
    react: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530 
    react-dom: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530 
    typescript: 4.0.5 => 4.0.5 
```

### Other

Please include applicable logs and screenshots that show your problem.

**Comment by flybayer** [comment]
Here's the code for the recipe: https://github.com/blitz-js/blitz/blob/canary/recipes/chakra/index.ts#L46

Looks like need to add the emotion/react package to that dependency list maybe.

For whoever works on this, you can run test the local recipe code in any app on your computer with `blitz install [PATH_TO_MONOREPO/recipes/chakra`

**Comment by markjackson02** [comment]
Chakra has upgraded from 0.8.0 to 1.0.0. Migration guide here https://chakra-ui.com/docs/migration. The recipe will need to be updated. I would recommend anyone wanting to use Chakra to install it manually instead of using the recipe for now.
