### ISSUE TITLE
`blitz generate model` is not working in certain case

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1475]
### What is the problem?

`blitz g model user session:session` does not work in our auth example. `blitz g model hasOne:session` which does the same thing also fails.

### Steps to Reproduce

1. `cd examples/auth`
1. `blitz g model user session:session`
1. See that `session Session` is not added to the user model

### Other

The code for this is here: https://github.com/blitz-js/blitz/blob/canary/packages/generator/src/prisma/field.ts#L58

**Comment by koolii** [comment]
@flybayer Let me tackle this issue :)

**Comment by mabadir** [comment]
Is the issue happening when adding the new relationship or during the actual migration? For me, I ran the command, and this is the resulting schema:

```
model User {
  id             Int      @id @default(autoincrement())
  createdAt      DateTime @default(now())
  updatedAt      DateTime @updatedAt
  name           String?
  email          String   @unique
  hashedPassword String?
  role           String   @default("user")

  sessions Session[]
  tokens   Token[]
  session  Session
}
```

**Comment by flybayer** [comment]
@mabadir ok must be fixed!
