### ISSUE TITLE
Blitz start fails in real app because can't find @blitzjs/server/register

### ISSUE THREAD

**Issue by hew** [blitz-js/blitz#148]
I tried to run the store example just now, but I'm getting an error that `@blitzjs/server/register` is not available. I looked at the latest NPM versions of the `@blitzjs/server` package, and it doesn't look like any of the canary versions published have the `register` folder. 

So we might just need to push a new release for the server package?

**Comment by flybayer** [comment]
Hey thanks! Two things: npm packages are still wip. But there is also a separate issue with this register thing not being required properly.

**Comment by flybayer** [comment]
Fixed in https://github.com/blitz-js/blitz/commit/45a09911a4cf5810e57cb451a3f9b25b7f796a2c
