### ISSUE TITLE
Change `blitz generate` templates to use field name marked as `@id` instead of always `id`

### ISSUE THREAD

**Issue by adnanfuat** [blitz-js/blitz#1480]
If my custom table/model doesn't have ID field? 
Why cannot be: **id fields will be automated according to my custom id name.**

***

**My table doesn't have id field.**
Instead of id field, My table has "numara" field.

This "numara" field marked as @id automatically ( https://prnt.sc/vkrwf8 )

But although this marking, Generated Files indicate "id" field and so I Get error
https://prnt.sc/vkrvcq (edited) 

workaround:

I edit manually these file one by one with hardcoding..

**Comment by flybayer** [comment]
Thanks for opening this from our slack discussion!

We should definitely make this change, but it will be a lot of work. All our [page templates](https://github.com/blitz-js/blitz/tree/canary/packages/generator/templates/page) and the generator logic will need changed for this.

We currently use `modelNameId` in file names as router parameters, so probably that should also be changed to use a different id name.

Furthermore, probably we should add a config item to blitz.config.js to customize the default name for `id`.

**Comment by JuanM04** [comment]
How this should work with [multiple ID models](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#id-1)?

**Comment by flybayer** [comment]
@JuanM04 I'd say don't support that for now
