### ISSUE TITLE
Have multiple TS errors: suspend, mutation, db not found

### ISSUE THREAD

**Issue by PixelsCommander** [blitz-js/blitz#1483]
### What is the problem?

When trying to build I get multiple TS issues: mutate from useQuery(), context on a session, and db global module are not found by TS. Same problems are highlighted by linting in WebStorm.

I tried to update global blitz then creating project on top of the current folder but this does not help.

<img width="186" alt="Screenshot 2020-11-17 at 08 42 36" src="https://user-images.githubusercontent.com/810671/99572202-9c7a5300-29d4-11eb-8a30-62f9085da16a.png">
<img width="253" alt="Screenshot 2020-11-17 at 08 42 28" src="https://user-images.githubusercontent.com/810671/99572204-9dab8000-29d4-11eb-92ff-49c582195010.png">
<img width="313" alt="Screenshot 2020-11-17 at 08 42 24" src="https://user-images.githubusercontent.com/810671/99572207-9dab8000-29d4-11eb-8b4f-79d43fce72d7.png">

### Steps to Reproduce

1.Not sure I know the root cause. Most likely something to do with blitz versions.

### Versions

```
output of `blitz --version --verbose`

debug: blitzPkgPath: /Users/denisradin/WebstormProjects/EMS/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/denisradin/WebstormProjects/EMS/node_modules/@blitzjs/cli/lib/src/index.js 

macOS Catalina | darwin-x64 | Node: v12.13.0

blitz: 0.25.0 (global)
blitz: 0.25.0 (local)

  Package manager: yarn 
  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 2.83 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.11.0 => 2.11.0 
    @prisma/client: 2.11.0 => 2.11.0 
    blitz: 0.25.0 => 0.25.0 
    react: 0.0.0-experimental-33c3af284 => 0.0.0-experimental-33c3af284 
    react-dom: 0.0.0-experimental-33c3af284 => 0.0.0-experimental-33c3af284 
    typescript: 4.0.5 => 4.0.5 

```

### Other

Please include applicable logs and screenshots that show your problem.

**Comment by flybayer** [comment]
Those are all issues from breaking changes between version. I suggest going back through the release notes and making the few breaking changes as noted there.

Namely rename `mutate` to `setQueryData` and adding the `types.ts` file in the project root.
