### ISSUE TITLE
Running `blitz db seed` on heroku server fails silently

### ISSUE THREAD

**Issue by rap2hpoutre** [blitz-js/blitz#1507]
### What is the problem?

Running `blitz db seed` on heroku server does not run anything (fails silently)

```
➜ heroku run bash
 ›   Warning: heroku update available from 7.46.0 to 7.47.3.
Running bash on ...
~ $ blitz --version
You are using alpha software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose
Linux 4.4 | linux-x64 | Node: v12.19.1
blitz: 0.25.1-canary.3 (local)
...

~ $ blitz db seed
You are using alpha software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose
```

### Steps to Reproduce

1. Deploy  a fresh project on heroku
2. Run `db:seed`

### Expected result

Run seed or fail with an error message

**Comment by flybayer** [comment]
Failing silently is definitely not good.

As to the actual problem, can you make sure `typescript` is in your regular dependencies, not devDependencies? We made that change some time back for new apps because of this very issue I think.

**Comment by flybayer** [comment]
For whoever wants to fix this, looks like we need to catch and log the error here: https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/db.ts#L312

**Comment by rap2hpoutre** [comment]
I would be glad to contribute, I could try to tackle this issue. Do you have any recommendations about log formatting/wording?
