### ISSUE TITLE
Significant build performance issue compared to next.js build

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1509]
### What is the problem?

For the new docs site, we forked the TailwindCSS docs site which is a large next.js app. Then we converted it to a blitz app which you can access at https://github.com/blitz-js/blitzjs.com/commit/5930a40ee580ec8be8df61f43ae1993341e78952

However `blitz build` takes so long it never finishes! Vercel deployments timed out at 45 minutes for that!

By contrast, deploying the original next.js tailwind docs site only took 8 minutes (without build cache, same as blitz scenario)

### Other

Not sure what could be the issue here. Maybe it could be a thing where `next build` uses multi cores but when invoked by the blitz internals it doesn't use multi cores?

**Comment by rayandrews** [comment]
Yes based on skimming on Next codes, it seems like that. Next used the `jest-worker` which encapsulates the node thread workers.

The build process should be similar, unless we introduce performance bottleneck while transforming the `blitz` files (which might be). Every big chunk of promises (calling other file processing methods) should be encapsulated in a worker so it can be parallelized.

This should be the issue, however we need to trace where the problems at first. Is it while building static pages with `next` or while transforming files with `blitz`?

**Comment by flybayer** [comment]
The problem is definitely during the `next build` phase. The blitz build process that copies files to `.blitz` is very quick (it's finished once you see "Prepped for Launch"). And for `blitz build`, there's no runtime component for syncing files, unlike `blitz start`.

**Comment by flybayer** [comment]
So looks like the root problem here was actually some custom build time computation that was in the tailwind site. I discovered this because after deleting most of the tailwind stuff, there was one page that would get stuck in the build and then I found this computation thing.
