### ISSUE TITLE
DB Studio error on new project

### ISSUE THREAD

**Issue by johnslemmer** [blitz-js/blitz#1519]
### What is the problem?

I'm seeing this when trying to open Prisma Studio on a brand new blitz project.

![image](https://user-images.githubusercontent.com/18610918/100029858-09ac3080-2da7-11eb-9704-775ac83780de.png)

### Steps to Reproduce

1. `blitz new test`
1. `cd test`
1. `blitz db studio`
1. navigate to http://localhost:5555/

### Versions

```
debug: blitzPkgPath: /Users/jslemmer/Code/blitz/test/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/jslemmer/Code/blitz/test/node_modules/@blitzjs/cli/lib/src/index.js 

macOS Catalina | darwin-x64 | Node: v14.13.1

blitz: 0.25.0 (global)
blitz: 0.25.0 (local)

  Package manager: yarn 
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 438.61 MB / 16.00 GB
    Shell: 5.0.18 - /usr/local/bin/bash
  Binaries:
    Node: 14.13.1 - ~/.asdf/shims/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.asdf/shims/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/cli: 2.11.0 => 2.11.0 
    @prisma/client: 2.11.0 => 2.11.0 
    blitz: 0.25.0 => 0.25.0 
    react: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530 
    react-dom: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530 
    typescript: 4.1.2 => 4.1.2 
```

**Comment by johnslemmer** [comment]
Also tried this with Node `15.2.1`

**Comment by flybayer** [comment]
hey @johnslemmer, I'm unable to reproduce and this is a prisma specific thing, so I'm going to kindly refer you to the Prisma issues: https://github.com/prisma/prisma/issues

**Comment by johnslemmer** [comment]
FYI if anyone happens to see this bug see the issue over on the Prisma Studio repo: https://github.com/prisma/studio/issues/586
