### ISSUE TITLE
Upon creating new project and running for the first time -> blank screen and "Uncaught TypeError: __webpack_require__(...) is not a function"

### ISSUE THREAD

**Issue by matijaSos** [blitz-js/blitz#1528]
### What is the problem?
When I create a fresh project and try to run it for the first time, I get the blank screen. In the console I get the following message: `Uncaught TypeError: __webpack_require__(...) is not a function`

### Steps to Reproduce

1. Create a new project with `blitz new`
2. Run it with `blitz start`

### Versions
Node 14.5.0

```
output of `blitz --version --verbose`
```
macOS Catalina | darwin-x64 | Node: v14.5.0

blitz: 0.26.0 (global)
blitz: 0.26.0 (local)

  Package manager: npm
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 959.67 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    Yarn: Not Found
    npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.12.0 => 2.12.0
    @prisma/client: 2.12.0 => 2.12.0
    blitz: 0.26.0 => 0.26.0
    react: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530
    react-dom: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530
    typescript: 4.1.2 => 4.1.2

### Other

Please include applicable logs and screenshots that show your problem.

**Comment by flybayer** [comment]
@matijaSos I'm unable to reproduce 🤔 

I did notice a blank screen a couple times on first load, but there was no error as you mentioned. And simply refreshing the page resolved the issue.

**Comment by yutaro-elk** [comment]
I'm having the same problem.


**Versions**
```
macOS Mojave | darwin-x64 | Node: v12.13.0

blitz: 0.26.0 (global)
blitz: 0.26.0 (local)

  Package manager: yarn 
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 427.14 MB / 16.00 GB
    Shell: 5.0.18 - /usr/local/bin/bash
  Binaries:
    Node: 12.13.0 - ~/.nodebrew/current/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.9 - ~/.nodebrew/current/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.12.1 => 2.12.1 
    @prisma/client: 2.12.1 => 2.12.1 
    blitz: 0.26.0 => 0.26.0 
    react: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530 
    react-dom: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530 
    typescript: 4.1.2 => 4.1.2 
```

**Comment by flybayer** [comment]
Ok, can you try something for me? @matijaSos @yutaro-elk 

1. Change the blitz version to `0.25.0` and see if issue is gone
1. Change the blitz version to 0.25.1-canary.1` and see if issue is present or gone
1. Lastly, change blitz version back to `0.26.0` and see if issue still exists

And report the result of each 3 steps

**Comment by flybayer** [comment]
Update, @matijaSos @yutaro-elk  can you try making the changes in your `app/auth/auth-utils.ts` as shown here: https://github.com/blitz-js/blitz/pull/1549/files#diff-0ecc0526f1f27e4da88e4b4de4fcf4453a8406d2287f25f127753d5f18f7c184 ?

Then let me know if that fixes it.

**Comment by flybayer** [comment]
# Solution

Make the following change to `app/auth/auth-utils.ts`

```diff
import SecurePassword from "secure-password"
import db from "db"

-const SP = new SecurePassword()
+const SP = () => new SecurePassword()

export const hashPassword = async (password: string) => {
-  const hashedBuffer = await SP.hash(Buffer.from(password))
+  const hashedBuffer = await SP().hash(Buffer.from(password))
  return hashedBuffer.toString("base64")
}
export const verifyPassword = async (hashedPassword: string, password: string) => {
  try {
-   return await SP.verify(Buffer.from(password), Buffer.from(hashedPassword, "base64"))
+   return await SP().verify(Buffer.from(password), Buffer.from(hashedPassword, "base64"))
  } catch (error) {
    console.error(error)
    return false
```
