### ISSUE TITLE
(CSS) module not found

### ISSUE THREAD

**Issue by gielcobben** [blitz-js/blitz#1531]
### What is the problem?
Since I’ve updated to `v0.26.0` I’m having trouble with importing css files. Maybe it has something todo with #1456 ? I `rm -rf` the directory `.blitz` and installed all versions backwards. Everything works perfect with- and before `v0.25.1-canary.0`. I’m using css modules and a file structure shown below.

##### File structure:
```
/app/users/pages/signin/index.tsx
/app/users/pages/signin/index.module.scss

/app/users/components/SignInForm/index.tsx
/app/users/components/SignInForm/index.module.scss
```

##### How I import css modules:
```
import styles from "./index.module.scss"
```

##### Error:
```
Failed to compile
./pages/users/test/index.tsx:3:0
Module not found: Can't resolve 'users/pages/users/test/index.module.scss'

  1 | import * as React from "react"
  2 | 
> 3 | import styles from "users/pages/users/test/index.module.scss"
  4 | 
  5 | const Test: React.FC = () => {
  6 |   return (
```

### Steps to Reproduce

1. Create a new blitz app by running: `blitz new _bug-css-modules`.
1. Create a new page, for example: `app/users/pages/users/test/index.tsx`
1. Add a css file, for exmaple: `app/users/pages/users/test/index.module.scss`
1. Run the project by running: `blitz start`
1. Navigate to the url of the page you just created: `localhost:3000/users/test`

### Versions

```
debug: blitzPkgPath: /Users/giel/Sites/_bug-css-modules/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/giel/Sites/_bug-css-modules/node_modules/@blitzjs/cli/lib/src/index.js

macOS | darwin-x64 | Node: v12.18.0

blitz: 0.26.0 (global)
blitz: 0.26.0 (local)

  Package manager: yarn
  System:
    OS: macOS 11.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 57.70 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/cli: 2.12.0 => 2.12.0
    @prisma/client: 2.12.0 => 2.12.0
    blitz: 0.26.0 => 0.26.0
    react: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530
    react-dom: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530
    typescript: 4.1.2 => 4.1.2
```

### Other

When you remove `.blitz` in the root directory of you project and downgrade to `0.25.1-canary.0` it works correctly.

**Comment by flybayer** [comment]
@gielcobben I have an integration test for css modules in pages: https://github.com/blitz-js/blitz/blob/canary/examples/store/app/pages/index.tsx#L5

Are you sure it's not the import in `components/` that was breaking? Because I don't have at test for that. Need to add that.

**Comment by flybayer** [comment]
@gielcobben I've added a second integration test in https://github.com/blitz-js/blitz/pull/1538 for css modules outside of pages and it's working fine 🤔 

Could you open a PR with a failing test on the store example or reproduce in a codesandbox? (there's an official blitz template)

**Comment by beeplin** [comment]
it's quite frustrating not being able to use css module in the newest version. Hope it will be solved soon. 🥇

**Comment by gielcobben** [comment]
I still have the same issue. It's weird because it is properly working in Code Sandbox but not locally.

**Comment by flybayer** [comment]
Yeah sorry y'all, been too busy to get to this. Will try to asap.
