### ISSUE TITLE
Place zsh Quotation Note Earlier in Tutorial

### ISSUE THREAD

**Issue by mattbeiswenger** [blitz-js/blitz#1539]
### What is the problem?
When I was running through the tutorial, I got the error `zsh: no matches found: choices:choice[]` when running the command `blitz generate all question text:string choices:choice[]`. I didn't realize how to fix the error until I saw the note for the next command  `blitz generate resource choice text votes:int:default[0] belongsTo:question` that states:
```
Note: in case you use zsh in your terminal, you need to wrap the field with default value in quotes ("") in order to be properly interpreted. Like this: "votes:int:default[0]".
```

In my case, I had to put quotations around `choices:choice[]` in order for the command to run.

It might be better if the note about quotations was given for the first command, or some sort of general note was given early in the tutorial about when quotation marks are needed when running commands.

### Steps to Reproduce
1. Using zsh as your shell, in a new blitz app run `blitz generate all question text:string choices:choice[]`

### Versions
```
blitz: 0.26.0 (global)
blitz: 0.26.0 (local)
```

**Comment by flybayer** [comment]
Good idea, thanks!

**Comment by MrLeebo** [comment]
Looks like this was already resolved by https://github.com/blitz-js/blitzjs.com/pull/292
