### ISSUE TITLE
Completely silent logs

### ISSUE THREAD

**Issue by kitze** [blitz-js/blitz#1550]
### What do you want and why?

Completely silent logs

### Possible implementation(s)

Add a `silent:true` property in blitz config

### Additional context

I would really love to get a 100% clean output so I can actually print something useful in the console and be able to find it without going through 3000 useless messsages.

**Comment by flybayer** [comment]
@kitze This feature is available in [0.27.0-canary.0](https://github.com/blitz-js/blitz/releases/tag/v0.27.0-canary.0)

Add this in `blitz.config.js` to disable blitz logging. The default level is `info`

```
module.exports = {
  log: {
    level: 'fatal'
  }
}
```

**Comment by kitze** [comment]
Thanks!
