### ISSUE TITLE
`useRouter()` throws `TypeError: Cannot read property 'asPath' of null`

### ISSUE THREAD

**Issue by LoriKarikari** [blitz-js/blitz#1555]
### What is the problem?

`useRouter()` throws `TypeError: Cannot read property 'asPath' of null` on some pages. I don't really know what is causing it because some pages work and others don't. ~~When I use `useRouter()` from Next.js everything works fine.~~
edit:  It doesn't work with `next/router` anymore either so I guess it was just randomly working.

### Steps to Reproduce

1. Create a component that uses `useRouter()`
2. Add the component to pages or layout

e.g. In my application, I created a shared Header component with links and I'm using `useRouter()` to get the path to change the color of the active link.

### Versions

```
Linux 4.19 | linux-x64 | Node: v14.4.0

blitz: 0.26.0 (global)
blitz: 0.26.0 (local)
```

**Comment by flybayer** [comment]
If it's not working with `next/router`, then likely a bug in next.js. 

You see this in dev or prod or both?

**Comment by Zeko369** [comment]
I also got this, it happens with next@10.0.3 but not with next@10.0.2, even though they haven't changed anything with [router](https://github.com/vercel/next.js/compare/v10.0.2...v10.0.3 )

**Comment by LoriKarikari** [comment]
I saw this in dev, haven't tested it in prod.

**Comment by flybayer** [comment]
Ok must be a next.js thing then. We don't intercept this

**Comment by LoriKarikari** [comment]
I have updated to `0.27.1` and so far it seems to work again. Going to test more after the weekend and close the issue if I don't encounter any problems.

**Comment by flybayer** [comment]
@reinis7 can you please provide reproduction details?
