### ISSUE TITLE
Error: Trying to use Blitz's useQuery to fetch 3rd party, when its not.

### ISSUE THREAD

**Issue by Kay2dan** [blitz-js/blitz#1560]
### What is the problem?
Post upgrade to v0.26.0, one of my mutation functions, which was working previously, is now giving the error `Error: It looks like you are trying to use Blitz's useQuery to fetch from third-party APIs. To do that, import useQuery directly from "react-query"`. 

While reviewing the source files, I noticed that the code that validates the mutation func, actually looks for whether the mutation func is `isEnhancedResolveRpcClient` & whether process.env has `JEST_WORKER_ID` & `Blitz_Test_Environment` defined. I am a bit confused by this. Why is Jest used to check whether a func is calling internal or external api? and what is RPC client.

````
var validateQueryFn = function validateQueryFn(queryFn) {
  if (!isEnhancedResolverRpcClient(queryFn) && isNotInUserTestEnvironment()) {
    throw new Error("It looks like you are trying to use Blitz's useQuery to fetch from third-party APIs. To do that, import useQuery directly from \"react-query\"");
  }
};
````

And my main question is, how can I resolve this and get this func to pass. All other mutation funcs are working as before, except for this one.

The mutation function is as such:

````
const saveUserFeedback = async (
  userFeedbackType,
  ctx: { session?: SessionContext } = {}
) => {
  try {
  ctx.session?.authorize();
  const { userId } = ctx.session!;

  const { feedbackType, message, response, pageRef } = userFeedbackType;
  return await db.feedback.create({
    data: {
      message,
      about: feedbackType,
      requireResponse: response,
      pageRef,
      user: {
        connect: {
          id: userId!,
        },
      },
    },
  });
  } catch (err) {
    throw err;
  }
};
````

It is consumed within React component as:

`const [saveFeedbackMutation] = useMutation(saveFeedback);
`

### Versions

```
debug: blitzPkgPath: /home/sk/www/aim-high/node_modules/blitz/dist/index.js
debug: cliPkgPath: /home/sk/www/aim-high/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js 

Linux 4.15 | linux-x64 | Node: v12.18.3

blitz: 0.26.0 (global)
blitz: 0.26.0 (local)

  Package manager: npm 
  System:
    OS: Linux 4.15 Linux Mint 19.2 (Tina)
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 5.45 GB / 15.68 GB
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: Not Found
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.x => 2.12.0 
    @prisma/client: 2.x => 2.12.0 
    blitz: 0.26.0 => 0.26.0 
    react: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530 
    react-dom: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530 
    typescript: 4.x => 4.1.2 

```

### Other

Error log:
````
Uncaught Error: It looks like you are trying to use Blitz's useQuery to fetch from third-party APIs. To do that, import useQuery directly from "react-query"
    validateQueryFn core.esm.js:541
    sanitize core.esm.js:550
    useMutation core.esm.js:1424
    ContactForm ContactForm.tsx:15
    ....
````

**Comment by sebastianhoitz** [comment]
I'm also running into this issue. For some reason, the mutation methods are not getting enhanced (at least from what I can see). I would be happy to try to provide a fix for this if someone could point me in a direction to get started on this.

**Comment by flybayer** [comment]
Well shucks, I think this is probably from some of the blitz compilation changes we made. I don't think it's an actual issue with `validateQueryFn`.

Is this only erring in certain situations? I'm confused because we have e2e CI tests covering useMutation (or at least I thought so 😅 ).

First step to track down is go into `.blitz` and find look at the compiled code and figure out exactly what is wrong

**Comment by flybayer** [comment]
And also see if you can open a PR with a failing test, so make sure this doesn't happen again.

**Comment by akboolz** [comment]
I know it sounds stupid but I am having problems when folders or file names have the word "Feedb" (Feedback). "Feed" works but "Feedb" dont.
This issue is just another proof. When I rename them it works.

I either get: 
"It looks like you are trying to use Blitz's useQuery to fetch from third-party APIs" for mutation files if i call them "createFeedback.ts"
or 
"Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined" if i call folder "feedback"

What is this? 😅😅😅

**Comment by Kay2dan** [comment]
> I know it sounds stupid but I am having problems when folders or file names have the word "Feedb" (Feedback). "Feed" works but "Feedb" dont.
> This issue is just another proof. When I rename them it works.
> 
> I either get error: `It looks like you are trying to use Blitz's useQuery to fetch from third-party APIs` for mutation files if i name them "createFeedback.ts
> or
> `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined` if i call folder "feedback"
> 
> Same thing with SCSS files with such name. Seems like all they are just not getting in the build.
> 
> What is this?

Thats interesting. I will find that branch in my code & see if this really is the case. Give me a day or two please to share my findings.

**Comment by flybayer** [comment]
Aha, that explains the issue! in `with-blitz.ts` we have a rule to ignore `db` imports, but apparently that's matching anything with `db` in the string.

Will fix!
