### ISSUE TITLE
react-query-utils/getQueryKey doesn't work when called from inside getStaticProps

### ISSUE THREAD

**Issue by jxe** [blitz-js/blitz#1567]
### What is the problem?

I'm trying to prefetch queries on the server, then ship the react-query cache to the client in a page prop, to reuse the cache on the client, as described [here](https://react-query.tanstack.com/docs/guides/ssr#integrating-with-nextjs). 

Except, this doesn't work:

```typescript
import queryFunction from 'api/queries/queryFunction'
export function getStaticProps(){
  console.log(getQueryKey(queryFunction, {id:1})) 
  // outputs an array with an empty string: [ '', { json: { id: 1 }, meta: undefined } ]
}
```

I'll need the key to be the same on the client and server, in order to reuse the cache. You can check out [this tweet](https://twitter.com/edelwax/status/1333747091525525504?s=20) and [this RFC](https://github.com/blitz-js/blitz/discussions/1530) for more on what I'm up to.

### Versions

```
macOS Big Sur | darwin-x64 | Node: v14.12.0

blitz: 0.18.0 (global)
blitz: 0.26.0 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.1
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 58.09 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.12.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.12.1 => 2.12.1 
    @prisma/client: 2.12.1 => 2.12.1 
    blitz: 0.26.0 => 0.26.0 
    react: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530 
    react-dom: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530 
    typescript: 4.2.0-dev.20201112 => 4.2.0-dev.20201112 
```

**Comment by MrLeebo** [comment]
It looks like the issue is that the query key function falls into this guard clause https://github.com/blitz-js/blitz/blob/canary/packages/core/src/utils/react-query-utils.ts#L61-L64 which is where the empty key is coming from. Looks like the check could be removed, but the comment makes me think that there's more that will need to be changed to make this work. @flybayer can you comment on what that check was added for?

**Comment by flybayer** [comment]
Ok yeah we can rework that a bit so that `emptyQueryFn` is only returned for use by useQuery hooks but not by `getQueryKey`
