### ISSUE TITLE
Command `blitz generate` does not exist on canary. 

### ISSUE THREAD

**Issue by hew** [blitz-js/blitz#157]
Following the instructions in [this document](https://github.com/blitz-js/blitz/blob/canary/USER_GUIDE.md), the user is met with an error when attempting to run the 'blitz generate` command. 

It does not exist as a CLI command.

I tried installing `@blitzjs/cli@latest` and  `@blitzjs/cli@canary` but it's not present on either tag.

**Comment by flybayer** [comment]
Yeah, this is still being worked on! 😅 #40
