### ISSUE TITLE
blitz/cli should throw more specific errors

### ISSUE THREAD

**Issue by Zeko369** [blitz-js/blitz#1579]
# Example

![image](https://user-images.githubusercontent.com/3064377/101269873-852cbb00-3773-11eb-87b2-38b95d96964f.png)

When running any `db` command `runPrisma` is called and if `getPrismaBin` errors out it just throws "Prisma not found". This functions calls `require(@blitzjs/server)` meaning that if it's broken it's still going to throw "Prisma not broken".

# Fix implementation

throw specific error in getPrismBin function and if it's not that, log the thrown error

**Comment by flybayer** [comment]
Here's the code where this needs changed: https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/db.ts#L13

Probably this should log the actual error instead of this custom error.

**Comment by arjundubey-cr** [comment]
@flybayer I would like to work on this issue.
