### ISSUE TITLE
blitz/cli should log more errors

### ISSUE THREAD

**Issue by Zeko369** [blitz-js/blitz#1580]
### Here we're not throwing any errors if there aren't any flags

This results in user not being able to detect what the error is rather just see `exited with code 1`

https://github.com/blitz-js/blitz/blob/909f3b3392c90f51cb93d20d06865702074ece4b/packages/cli/src/commands/db.ts#L246
![image](https://user-images.githubusercontent.com/3064377/101269905-e9e81580-3773-11eb-9cb5-d0f889b35d80.png)

### Possible implementation(s)

Throw unless flag `--silent` is set

**Comment by koolii** [comment]
I read up `How to Contribute`!
@flybayer I would like to work on this issue if anyone has done this yet.

**Comment by flybayer** [comment]
Hey @koolii thanks for your interest! This code is actually getting removed shortly via #1661, so this issue is no longer relevant.
