### ISSUE TITLE
getDb(...).session.findFirst is not a function

### ISSUE THREAD

**Issue by hypervillain** [blitz-js/blitz#1581]
### What is the problem?

When calling `ctx.session.create` in te default Login function, I get a `getDb(...).session.findFirst is not a function` (located in `supertokens.ts` file). I've updated to latest version of blitz with no effect.

I believe the error is related to a mismatch between local and remote migrations as I get an `Error: Local and remote migrations are not in lockstep.` when I try to migrate. But I have close to zero knowledge of Prisma so not sure what's the correct process to update our database without falling into this.

### Steps to Reproduce

Not sure

### Versions

```
macOS Mojave | darwin-x64 | Node: v14.4.0

blitz: 0.18.0 (global)
blitz: 0.27.0 (local)

  Package manager: yarn
  System:
    OS: macOS Mojave 10.14.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 654.23 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: Not Found
    @prisma/client: 2.5.1 => 2.5.1
    blitz: 0.27.0 => 0.27.0
    react: 0.0.0-experimental-33c3af284 => 0.0.0-experimental-33c3af284
    react-dom: 0.0.0-experimental-33c3af284 => 0.0.0-experimental-33c3af284
    typescript: 3.9.7 => 3.9.7
```

### Other

The actual error stack:
```
 Error 	getDb(...).session.findFirst is not a function
error stack:
• supertokens.ts:62 getSession
    node_modules/@blitzjs/server/src/supertokens.ts:62:43
```

**Comment by flybayer** [comment]
Looks like you need to run `yarn add @prisma/cli@latest @prisma/client@latest`. And then if you still get the migration error, run `blitz db reset` to wipe the DB and start fresh.

**Comment by hypervillain** [comment]
Thanks a lot Brandon, it's working now!
