### ISSUE TITLE
Not able to set a custom queryKey using the blitz query hooks

### ISSUE THREAD

**Issue by johnkahn** [blitz-js/blitz#1596]
### What do you want and why?

There is a `queryKey` property of the query hooks options, but looking at the source code it is not being utilized to set the query key. My problem is that for one of my queries the query key changes often due to user input (sorting and filtering), and I would like a query key I set so that I can fetch from the cache easier on other pages.

### Possible implementation(s)

This seems to be the line that needs to be changed.

https://github.com/blitz-js/blitz/blob/e2acb1a6a18f5a2d6331eae10e1e6e950ff1ba7a/packages/core/src/use-query-hooks.ts#L38

```diff
- const queryKey = getQueryKey(queryFn, params)
+ const queryKey = options.queryKey ?? getQueryKey(queryFn, params)
```

> There are similar lines for the other hooks as well that will need to be changed in the same way.

### Additional context

I am willing to make a pull request for this change, but I'm not sure if blitz is using the query keys elsewhere which might result in a larger change needed. I'll keep looking through the codebase in the meantime.

**Comment by flybayer** [comment]
Hey @johnkahn, I think that change should be fine.

Did you by chance try using the Blitz [getQueryKey](https://blitzjs.com/docs/resolver-utilities#getquerykey) utility function?

**Comment by johnkahn** [comment]
Sounds good, I'll make a PR. 👍 

And I was using that originally, but since the params for the query change based on user input I would need to persist the params to a global state to be able to utilize that function when the params change.

**Comment by johnkahn** [comment]
It seems my blitz version is a bit out of date in my project, and I missed the update where `react-query` was downgraded due to the concurrent issue. Unfortunately in version `2.5.12` react-query does not have the option for `queryKey` in the config object. I see two options for adding this functionality without bumping the version, and am wondering which you prefer. IMO I think the second option is better in the long-run as it adds support for both syntax options from `react-query`.

1. Extend the QueryOptions from `react-query` to add `queryKey` as an option
2. Add another function definition in Typescript to support [object syntax](https://react-query.tanstack.com/docs/api#usequery) and update the implementation to work for both definitions

```diff
+ interface UseQueryObjectConfig<T extends QueryFn, TResult> {
+   queryKey: QueryKey
+   queryFn?: T
+   config?: QueryOptions<TResult>
+ }

+ export function useQuery<T extends QueryFn, TResult = PromiseReturnType<T>>(config: UseQueryObjectConfig<T, TResult>);
+ export function useQuery<T extends QueryFn, TResult = PromiseReturnType<T>>(queryFn: T, params: FirstParam<T>, options?: QueryOptions<TResult>);
  export function useQuery<T extends QueryFn, TResult = PromiseReturnType<T>>(
-   queryFn: T,
+   configOrQueryFn: T | UseQueryObjectConfig<T, TResult>,
    params: FirstParam<T>,
    options?: QueryOptions<TResult>,
  ): [TResult, RestQueryResult<TResult>]
```

**Comment by flybayer** [comment]
Let's add the `queryKey` field to `options`, just like the latest react-query. That way when we upgrade, we can simply remove our custom type and everything should keep working.

**Comment by johnkahn** [comment]
Unfortunately I don't believe that `react-query` can be used in the manner I was hoping. My hope was that I could set a queryKey to be just a string, but still pass along the parameters. But it seems that the parameters must be in the key for them to be passed to the function. So I'll need to setup a global state to store the parameters for these calls so that I can get the queryKey using the utility functions.

From what I saw, I don't believe it's currently possible with `react-query`, but I'll let you decide to close this issue just in case you still think it's worth exploring.

**Comment by flybayer** [comment]
You can set a custom query string, but if the query result data is different, it will mix up the cache. In other words, if your query result data is different, the query key needs to be different too.

I think what you want is possible with plain react-query and our `invoke` middleware, and then grab the params from outside the closure.

```ts
import {invoke} from 'blitz'
import {useQuery} from 'react-query'
import getStuff from 'app/queries/getStuff'

const params = {page: 1}

const result = useQuery("myquerykey", () => invoke(getStuff, params))
```
