### ISSUE TITLE
Documentation getting started blitz generate all command does not work

### ISSUE THREAD

**Issue by timReynolds** [blitz-js/blitz#1606]
### What is the problem?

Generation of the relationship in the[ getting started documentation ](https://blitzjs.com/docs/getting-started) doesn't work with latest version of blitz.js from npm. 

The following command and output shows the issues 

```
blitz-example on  master [?] is 📦 v1.0.0 via ⬢ v15.2.0
➜ blitz generate all question text:string choices:Choice[]
zsh: no matches found: choices:Choice[]
```

### Steps to Reproduce

Follow the steps in the tutorial until you get to the following erroring step;
```
blitz generate all question text:string choices:choice[]
```

### Versions

```
➜ blitz --version --verbose
You are using alpha software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: /Users/timreynolds/code/github.com/timreynolds/blitz-example/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/timreynolds/code/github.com/timreynolds/blitz-example/node_modules/@blitzjs/cli/lib/src/index.js

macOS Big Sur | darwin-x64 | Node: v15.2.0

blitz: 0.27.1 (global)
blitz: 0.27.1 (local)

  Package manager: yarn
  System:
    OS: macOS 11.1
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 3.12 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.2.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.10 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: ~2.12 => 2.12.1
    @prisma/client: ~2.12 => 2.12.1
    blitz: 0.27.1 => 0.27.1
    react: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530
    react-dom: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530
    typescript: 4.1.3 => 4.1.3
```

### Other

![Screenshot 2020-12-14 at 09 25 22](https://user-images.githubusercontent.com/168870/102064067-c31e8480-3dee-11eb-9330-408854459e55.png)

**Comment by sebastianhoitz** [comment]
If you are using zsh, you have to escape the parameters. There is a hint further down in the documentation:

> Note: in case you use zsh in your terminal, you need to wrap the field with default value in quotes ("") in order to be properly interpreted. Like this: "votes:int:default[0]".

But yes, this should be more prominent

**Comment by timReynolds** [comment]
@sebastianhoitz right totally missed that, thanks for pointing it out. 

Once I've tried it will close this issue

**Comment by tkumpanenko** [comment]
@sebastianhoitz , @timReynolds - thanks. I've got the same issue with zhs. I think adding just a simple note to docs will be very helpful

**Comment by flybayer** [comment]
Closed in https://github.com/blitz-js/blitzjs.com/pull/292
