### ISSUE TITLE
Support other ESLint configs for blitz new template

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#161]
Currently blitz new generates an app with the create-react-app ESLint config.

The community is divided enough over their preferred eslint config that I think we should support a few other ones and then prompt the user to choose during blitz new generation.

Other configs to support:

- Standard.js

If you want something besides CRA eslint or Standard.js, comment here. We can't support every variation, but we can support the top ones.

And we'll definitely appreciate help implementing this!

**Comment by wKovacs64** [comment]
Love it or hate it, `eslint-config-airbnb` is hugely popular. I'd have a hard time recommending it out-of-the-box for a React app, but that doesn't change the fact that tons of people use it. Whether we want to perpetuate that choice is 🤷‍♂️ .

This is just for initial generation, correct? Users will be able to swap it out with whatever they want afterwards, yeah?

**Comment by flybayer** [comment]
Yes, just for initial generation! 

We could mark the Airbnb option as “warning, only for advanced users” or something lol

**Comment by flybayer** [comment]
No one's asked for this, 👋
