### ISSUE TITLE
blitz generate model is limited to alpha character field names

### ISSUE THREAD

**Issue by christianstrang** [blitz-js/blitz#1610]
### What is the problem?
blitz generate model doesn't allow numbers inside the field name

### Steps to Reproduce

1. run `blitz generate wordlist words200:string`

### Versions

```
0.27.1
```

### Other

/src/prisma/field.ts is limited to alpha characters only while prisma has the following conventions:

- Must start with a letter
- Typically spelled in camelCase
- Must adhere to the following regular expression: [A-Za-z][A-Za-z0-9_]*

https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#model-fields

**Comment by flybayer** [comment]
Yes, you're right, this needs changed.

Here's the code that needs changed: https://github.com/blitz-js/blitz/blob/canary/packages/generator/src/prisma/field.ts#L99
