### ISSUE TITLE
Form values are not parsed before validation

### ISSUE THREAD

**Issue by beerose** [blitz-js/blitz#1636]
### What is the problem?

Form values are not parsed before validation in Blitz setup with React Final Form. 

### Steps to Reproduce

1. Create a new Blitz project with React Final Form
2. Add field `age (number)` to, for example, sign up form (or any other form).
3. Fill input `age` with some value.
4. There's `Expected number, received string` error:
<img width="326" alt="Screenshot 2020-12-20 at 22 58 17" src="https://user-images.githubusercontent.com/9019397/102725416-de215500-4316-11eb-98e2-f59ce3f2f6bb.png">

### Versions

```
macOS Big Sur | darwin-x64 | Node: v12.18.3

blitz: 0.27.1 (local)
```

---

I guess the generated `Form.tsx` has a missing step — a transformation of the values before the validation:
```tsx
validate={(values) => {
  if (!schema) return
  try {
    // if schema.key is zot.number then values[key] = parseFloat(values[key])
    schema.parse(values)
  } catch (error) {
    return error.formErrors.fieldErrors
  }
}}
```

I could submit a PR with a fix if no one else is working on it. 

---

cc @zolwiastyl @hasparus

**Comment by flybayer** [comment]
Hey @beerose! You do that in react-final-form with [the `parse` option](https://final-form.org/docs/react-final-form/types/FieldProps#parse) which you can add to the `useField` options.

```
parse: (value) => Number(value)
```

**Comment by beerose** [comment]
Hey @flybayer! Thanks for the answer. I get it, but the thing is that the starter code doesn't work out of the box with types other than string.  

I was hoping that it could be covered in the generated code — either inside a function that is passed as `validate` prop to `FinalForm` component or inside starter components using `useField` hook. 
The point isn't how to do this, but rather that it would be cool to have other types working out of the box as well. 

It's more of a question of expectations. In my opinion, the starter code should either do less (have fewer abstractions on forms and, for example, use FinalForm inline), or do more (work with different form values types).

**Comment by hasparus** [comment]
Hi folks :wave: 

![image](https://user-images.githubusercontent.com/15332326/103030949-229e3200-455d-11eb-80d8-8e0d1b302fcc.png)

Seeing `"number"` in `LabeledTextField` types I expect I can use it with numbers, and I'd expect it _just works_ with `zod` and the `Form` component from _components/Form.tsx_.

Removing this `"number"` would also solve the problem for me and tell me "write your own number input, mate", this one doesn't support numbers.

**Comment by hasparus** [comment]
![image](https://user-images.githubusercontent.com/15332326/103031642-8543fd80-455e-11eb-8ba2-ae2425cbca85.png)

This change (based on https://github.com/blitz-js/blitz/issues/1636#issuecomment-749729783) would also satisfy that `number` in types IMHO.

**Comment by Kosai106** [comment]
Thanks for the suggestion @hasparus, it solves the issue nicely on my end.

**Comment by flybayer** [comment]
@hasparus @Kosai106 yes, that's a very good change! One of you want to make a PR for that?

**Comment by vivek7405** [comment]
I'm facing the same issue with react-hook-form. Can someone please suggest a fix for the same?

**Comment by beerose** [comment]
@vivek7405 probably this will do it: https://react-hook-form.com/advanced-usage#TransformandParse

**Comment by vivek7405** [comment]
Thanks @beerose, will give it a try
