### ISSUE TITLE
Fix flaky windows test

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1638]
### What do you want and why?

We [skipped this test](https://github.com/blitz-js/blitz/blob/canary/packages/file-pipeline/src/helpers/agnostic-source/agnostic-source.test.ts#L52-L79) in https://github.com/blitz-js/blitz/pull/1635 because it's flaky and messing up our CI. But now we need to properly fix it. 

This is probably easier for someone with a Windows machine to debug and fix.

**Comment by matthieu994** [comment]
Hello @flybayer ! 
I'm on Windows so I thought it would be a good idea to give a hand on this issue. :)

I've set-up the dev environment, changed this line : 
`const testIfNotWindows = process.platform === "win32" ? test : test` 
and this is what I get when I run the tests suite in `agnostic-source` :

```
PS S:\Documents\Freelance\Blitz\packages\file-pipeline\src\helpers\agnostic-source> yarn run test
yarn run v1.22.10
$ tsdx test
 PASS  src/transform.test.ts
 PASS  src/helpers/idle-handler/idle-handler.test.ts      
 PASS  src/helpers/writer/write.test.ts
 PASS  src/helpers/work-optimizer/work-optimizer.test.ts (5.247s)
 PASS  src/helpers/unlink/unlink.test.ts
- Compiling
- Compiling
- Compiling
√ Compiled
√ Compiled
 PASS  src/transform-files/transform-files.test.ts (6.401s)
 PASS  src/transform-files/index.test.ts (6.422s)
√ Compiled
 PASS  src/transform-files/highwatermark.test.ts (7.321s)
 PASS  src/helpers/agnostic-source/agnostic-source.test.ts (10.86s)

Test Suites: 9 passed, 9 total
Tests:       24 passed, 24 total
Snapshots:   0 total
Time:        14.41s
```

I'm on Windows 10 Family, Version 10.0.19042 Build 19042.

**Comment by flybayer** [comment]
Hey thanks for looking into this @matthieu994!

We're actually going to be removing this code (see https://github.com/blitz-js/blitz/discussions/1990), so I think we can just close it.

@all-contributors add @matthieu994 for tests
