### ISSUE TITLE
Cannot import library with `/api` in its path in a file under a `/pages` directory

### ISSUE THREAD

**Issue by blakeley** [blitz-js/blitz#1646]
### What is the problem?

I'm trying to `import { GoogleMap, LoadScript } from '@react-google-maps/api';`, but when I do that I get `Module not found: Can't resolve 'pages/api/index'`

### Steps to Reproduce

1. `yarn add @react-google-maps/api`
2. Add `import { GoogleMap, LoadScript } from '@react-google-maps/api';` to a file under a `/pages` directory
3. Run `blitz start`
4. See error message

### Versions

```
debug: blitzPkgPath: /Users/brandonblakeley/Desktop/shop-dispatch/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/brandonblakeley/Desktop/shop-dispatch/node_modules/@blitzjs/cli/lib/src/index.js 

macOS Big Sur | darwin-x64 | Node: v15.3.0

blitz: 0.27.1 (global)
blitz: 0.27.1 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 49.71 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.14 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: ~2.12 => 2.12.1 
    @prisma/client: ~2.12 => 2.12.1 
    blitz: 0.27.1 => 0.27.1 
    react: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530 
    react-dom: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530 
    typescript: 4.1.3 => 4.1.3
```

### Other

I found a workaround by instead creating a file `app/react-google-maps.ts` that has simply `export * from "@react-google-maps/api"` and importing from there (although this doesn't place nicely with VSCode's autoimport)

**Comment by Skn0tt** [comment]
I‘ll take a look at this.
