### ISSUE TITLE
Blitz Console hangs when trying to create a question in tutorial

### ISSUE THREAD

**Issue by phillipkregg** [blitz-js/blitz#1647]
### What is the problem?
From the "Playing with the API" section of the tutorial,
`let q = await db.question.create({data: {text: "What's new?"}})`

Then, the console hangs with "Loading Modules" message:

![image](https://user-images.githubusercontent.com/1066044/103120229-7f244e80-463c-11eb-97be-9d2568a3ea61.png)

### Steps to Reproduce

1.  Start the Blitz tutorial
2. On the "Playing with the API" section, run `blitz console`
3.  Create a question: `let q = await db.question.create({data: {text: "What's new?"}})`

### Versions
Windows 10 Pro - Version 1909

Blitz and dependencies:

![image](https://user-images.githubusercontent.com/1066044/103120388-15587480-463d-11eb-9900-d7fadd098004.png)

```
output of `blitz --version --verbose`
```

### Other

Please include applicable logs and screenshots that show your problem.

**Comment by phillipkregg** [comment]
Ah, I may have spoken too soon.  It appears that you actually can still enter commands while the "loading modules 1/15" is displayed.  The cursor disappears though, so it appears as though there is still some sort of loading happening.  But if I type 'q' to log the object, it logs to the console.

**Comment by flybayer** [comment]
@phillipkregg did it never finish loading the modules? Does it get stuck every time you open the console?

**Comment by phillipkregg** [comment]
Yes, it seems to get stuck on the "Loading Modules 1/15" message, but after a moment it allows you to enter the blitz console commands, but there is no cursor and no indication that you can actually start entering commands.  I was using the Cmder console on a Windows 10 machine, but I will try it with the Hyper console a little later today when I get some free time.

**Comment by phillipkregg** [comment]
Ok, so I just got home and tried this again in 3 different consoles and can't recreate it.  It seems to be working fine now and displaying a prompt once the modules finish loading.  Seems to have just been a fluke, or a problem with the network I was using when I first found it.  I'll close this one.
