### ISSUE TITLE
Generated file contains type error

### ISSUE THREAD

**Issue by michiomochi** [blitz-js/blitz#1650]
### Steps to Reproduce

1. Execute `blitz generate all note`

### Versions

```
> blitz --version --verbose
You are using alpha software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: /Users/michiomochi/ghq/github.com/refcome/1on1-note/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/michiomochi/ghq/github.com/refcome/1on1-note/node_modules/@blitzjs/cli/lib/src/index.js

macOS Catalina | darwin-x64 | Node: v12.18.3

blitz: 0.27.1 (global)
blitz: 0.27.1 (local)

  Package manager: yarn
  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 10.85 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nodebrew/current/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nodebrew/current/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: ~2.12 => 2.12.1
    @prisma/client: ~2.12 => 2.12.1
    blitz: 0.27.1 => 0.27.1
    react: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530
    react-dom: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530
    typescript: 4.1.3 => 4.1.3
```

### Other

`app/notes/pages/notes/index.tsx`(auto generated file) contains below type error.
This error means `where` args is missing.

<img width="849" alt="CleanShot 2020-12-29 at 13 46 45@2x" src="https://user-images.githubusercontent.com/1830471/103259473-ee06fc00-49dc-11eb-85a6-ac618cb0a07b.png">

I think the cause is in the code below.
https://github.com/blitz-js/blitz/blob/c451a5d55e20b5ef67622c438b9f5ad6429f0275/packages/generator/templates/page/index.tsx#L18

**Comment by flybayer** [comment]
Looks like probably you need to run `blitz db migrate` after that command in order for the types to be generated. (or if you did, restart your editor)

The error shown says `required in type Pick<any, "where" ...>` but it should be `Pick<Prisma.FindManyNoteArgs, "where"`. So the `any` there means the types aren't being picked up :)
