### ISSUE TITLE
Add cookie `domain` config option to `sessionMiddleware`

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1664]
### What do you want and why?

Ability to set the cookie `domain` for Blitz session middleware. Originally requested here: https://github.com/blitz-js/blitz/discussions/1557

### Possible implementation(s)

1. Add `domain` as optional config item on [`SessionConfig`](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/supertokens.ts#L18)
2. Modify [`sessionMiddleware`](https://github.com/blitz-js/blitz/blob/canary/packages/server/src/supertokens.ts) to use that setting and pass it to the usages of `cookie.serialize()` which takes `domain` as a config option.

Tip: this implementation is the same as the `sameSite` config option. So if in doubt, check how that config item is used inside `cookie.serialize()`.

**Comment by rembrandtreyes** [comment]
I just read up on the contributing guidelines and I am looking forward to contributing to Blitz!

🙌 I'll tackle this issue.
