### ISSUE TITLE
blitz new <App> breaks... Found: react@0.0.0-experimental-4ead6b530, Could not resolve peer dependency

### ISSUE THREAD

**Issue by tobkle** [blitz-js/blitz#1668]
### What is the problem?
blitz new <App> breaks

### Steps to Reproduce

1. run: blitz new app

### Versions
```
You are using alpha software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: /Users/tobiasklemmer/.nvm/versions/node/v15.5.0/lib/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/tobiasklemmer/.nvm/versions/node/v15.5.0/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js

macOS Big Sur | darwin-x64 | Node: v15.5.0

blitz: 0.27.1 (global)

  Package manager: npm
  System:
    OS: macOS 11.1
    CPU: (8) x64 Apple M1
    Memory: 198.14 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.5.0 - ~/.nvm/versions/node/v15.5.0/bin/node
    Yarn: Not Found
    npm: 7.3.0 - ~/.nvm/versions/node/v15.5.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: Not Found
    @prisma/client: Not Found
    blitz: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```

### Other

Please include applicable logs and screenshots that show your problem.

npm ERR!

 ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: app@1.0.0
npm ERR! Found: react@0.0.0-experimental-4ead6b530
npm ERR! node_modules/react
npm ERR!   react@"0.0.0-experimental-4ead6b530" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=16.13.1" from react-error-boundary@2.3.2
npm ERR! node_modules/react-error-boundary
npm ERR!   react-error-boundary@"2.3.2" from the root project

**Comment by tobkle** [comment]
got it working with Node 12.20.0

**Comment by Blanen** [comment]
Same issue and saying "use this specific version" is not really an acceptable solution in my opinion.

Blitz should obviously be able to do this with any supported version and especially the latest LTS.

**Comment by flybayer** [comment]
The core problem here is that npm did a terrible thing and changed how peer dependencies works... Best solution is to use `npm install --legacy-peer-deps` for now.

As for the particular issue mentioned in OP, it's an issue with the peer dependencies defined in [react-error-boundary](https://github.com/bvaughn/react-error-boundary). It should allow react@experimental. There's probably other dependencies with the same issue, unfortunately.

**Comment by emgoto** [comment]
I tried a couple of packages and was experiencing the same issue (very confusing!) I switched to Node 12.20.0 and got it working.

**Comment by flybayer** [comment]
@emgoto sorry about that, that issue is fixed in latest canary release via https://github.com/blitz-js/blitz/pull/1859

Solution: Add `legacy-peer-deps=true` to `.npmrc`
