### ISSUE TITLE
Error "Failed to parse publicDataStr" occur when PublicData including semicolon string

### ISSUE THREAD

**Issue by kyken** [blitz-js/blitz#1675]
### What is the problem?
When handling session data of blitz, I set a string including a semicolon as publicData, an exception `Failed to parse publicDataStr` has occur.

### Steps to Reproduce

1. clone blitz repo and checkout v0.28.0
2. modify `examples/auth` to include publicData to semicolon
3. execute `useSession`  and error occurs

### Versions

```
macOS Big Sur | darwin-x64 | Node: v12.18.0

blitz: 0.28.0 (local)

  Package manager: npm 
  System:
    OS: macOS 11.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 358.47 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.0 - ~/.nodebrew/current/bin/node
    Yarn: 1.22.10 - ~/.nodebrew/current/bin/yarn
    npm: 6.14.4 - ~/.nodebrew/current/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/cli: 2.12.0 => 2.12.0 
    @prisma/client: 2.12.0 => 2.12.0 
    blitz: 0.28.0 => 0.28.0 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: 4.1.3 => 4.1.3 
```

### Other
codes and screenshot 

```signup.ts
import {Ctx} from "blitz"
import db from "db"
import {hashPassword} from "app/auth/auth-utils"
import * as z from "zod"

export const SignupInput = z.object({
  email: z.string().email(),
  password: z.string().min(10).max(100),
})
export type SignupInputType = z.infer<typeof SignupInput>

export default async function signup(input: SignupInputType, {session}: Ctx) {
  // This throws an error if input is invalid
  const {email, password} = SignupInput.parse(input)

  const hashedPassword = await hashPassword(password)
  const user = await db.user.create({
    data: {email, hashedPassword, role: "us;er"},
    select: {id: true, name: true, email: true, role: true},
  })

  await session.create({userId: user.id, roles: [user.role]})

  return user
}
```

<img width="1097" alt="スクリーンショット 2021-01-05 20 11 59" src="https://user-images.githubusercontent.com/20137120/103639826-508a6a00-4f92-11eb-83f0-88953e7a3296.png">

**Comment by flybayer** [comment]
Hey @kyken, thanks for reporting, this is a bug.

For whoever wants to fix:

- Currently the the publicDataToken has the payload inside an array. This was used in the past but no longer needed.
- Change [`createPublicDataToken()`](https://github.com/blitz-js/blitz/blob/canary/packages/server/src/supertokens.ts#L308-L311) to not be an array. Instead just have the plain data.
- Change [`parsePublicDataToken`](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/utils/tokens.ts#L9) to work without the array (remove the parse array part)
