### ISSUE TITLE
Warning when running tests in `package/installer`

### ISSUE THREAD

**Issue by rembrandtreyes** [blitz-js/blitz#1682]
### What is the problem?
Running tests inside of `package/installer` and noticed a warning when tests run
### Steps to Reproduce

1. `cd packages/installer`
2. `yarn test`

### Versions

```
debug: blitzPkgPath: /Users/rreyes/open-source/blitz/packages/blitz/dist/index.js
debug: cliPkgPath: /Users/rreyes/open-source/blitz/packages/cli/lib/src/index.js 

macOS Catalina | darwin-x64 | Node: v15.0.1

blitz: 0.27.1 (global)
blitz: 0.28.0 (local)

  Package manager: yarn 
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 326.17 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.0.1 - ~/.nvm/versions/node/v15.0.1/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.0.3 - ~/.nvm/versions/node/v15.0.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/cli: Not Found
    @prisma/client: Not Found
    blitz: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: 4.1.3 => 4.1.3 
```

### Other

Please include applicable logs and screenshots that show your problem.

![Screen Shot 2021-01-07 at 3 40 14 PM](https://user-images.githubusercontent.com/15057964/103957118-dd523680-50fe-11eb-8d6c-5564f4a6133b.png)

**Comment by flybayer** [comment]
Thanks for the issue!

**Comment by tarunama** [comment]
Maybe related this issues.
https://github.com/vadimdemedes/yoga-layout-prebuilt/issues/8
https://github.com/facebook/yoga/issues/898

`yoga-layout-prebuilt` still not support Node.js 12.

**Comment by tarunama** [comment]
@flybayer 
Hi, My conclusion of this issue is outside `blits.js`
This issue is depending on `yoga-layout-prebuilt` package.
So, could retriage `status/icebox` or valid label, does not close this issue.

**Comment by flybayer** [comment]
Ok thank you @tarunama!
