### ISSUE TITLE
`tsConfig` is depecrated and will be removed in ts-jest 27

### ISSUE THREAD

**Issue by rembrandtreyes** [blitz-js/blitz#1683]
### What do you want and why?
In the next major version (27), ts-jest will be removing key `tsConfig` and its being replaced with `tsconfig`

There are 4 locations with the deprecated key in the `jest.config.js` files
1. cli
2. generator
3. installer
4. repl

### Possible implementation(s)
Find/Replace `tsConfig` with `tsconfig`

### Additional context
Warning from console: `ts-jest[config] (WARN) The option `tsConfig` is deprecated and will be removed in ts-jest 27, use `tsconfig` instead`

**Comment by MrLeebo** [comment]
Thanks for writing this up!

**Comment by koolii** [comment]
I would like to work on this issue if anyone has done this yet :)

**Comment by koolii** [comment]
I tried to make a PR to finish this issue in advance.
I'll drop above if @rembrandtreyes or someone has already got this.

**Comment by rembrandtreyes** [comment]
@koolii thanks for the PR. I wrote this up so someone else can work on it. Your PR should be good 😄

**Comment by koolii** [comment]
@rembrandtreyes Thank you for the reply :)
I would appreciate it!
