### ISSUE TITLE
Add section to contributor guide about setting the yarn policy

### ISSUE THREAD

**Issue by ryardley** [blitz-js/blitz#169]
**EDIT:** See [this comment below](https://github.com/blitz-js/blitz/issues/169#issuecomment-617051503) on what to document.
---

**What is the problem?**

Cannot add dependencies to packages 

**Steps to Reproduce:**

1. Pull canary
1. `yarn`
2. `cd ./examples/server`
3. `yarn add --dev metro-memory-fs`
4. Get Yarn error:

```
blitz/packages/server on  canary [$] via ⬢ v12.16.1
➜ y add --dev metro-memory-fs
yarn add v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "workspace-aggregator-9a9eee98-3e2b-4313-8906-d5ceff4a6f7d > @testing-library/react@10.0.3" has unmet peer dependency "react@*".
warning "workspace-aggregator-9a9eee98-3e2b-4313-8906-d5ceff4a6f7d > @testing-library/react@10.0.3" has unmet peer dependency "react-dom@*".
warning "workspace-aggregator-9a9eee98-3e2b-4313-8906-d5ceff4a6f7d > next@9.3.5" has unmet peer dependency "react@^16.6.0".
warning "workspace-aggregator-9a9eee98-3e2b-4313-8906-d5ceff4a6f7d > next@9.3.5" has unmet peer dependency "react-dom@^16.6.0".
warning "workspace-aggregator-9a9eee98-3e2b-4313-8906-d5ceff4a6f7d > @blitzjs/core > react-query@1.2.9" has unmet peer dependency "react@^16.6.3".
warning "workspace-aggregator-9a9eee98-3e2b-4313-8906-d5ceff4a6f7d > @blitzjs/server > null-loader@4.0.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-9a9eee98-3e2b-4313-8906-d5ceff4a6f7d > store > react-final-form@6.4.0" has incorrect peer dependency "react@^16.8.0".
warning "workspace-aggregator-9a9eee98-3e2b-4313-8906-d5ceff4a6f7d > next > styled-jsx@3.2.5" has unmet peer dependency "react@15.x.x || 16.x.x".
warning "workspace-aggregator-9a9eee98-3e2b-4313-8906-d5ceff4a6f7d > next > use-subscription@1.1.1" has unmet peer dependency "react@^16.8.0".
error An unexpected error occurred: "expected workspace package to exist for \"@wessberg/rollup-plugin-ts\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/rudiyardley/projects/blitz/blitz/packages/server/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Versions:**
 - Blitz: 0.5.0-canary.1
 - OS: macOS

Suspect it has to do with installing dependencies on the root. Not sure if this is a yarn thing or not.

**Comment by flybayer** [comment]
I have seen this too. Re-running `yarn` at the root fixed it for me.

Not sure what the fix is though 🤔

**Comment by ryardley** [comment]
> Re-running yarn at the root fixed it for me.

Unfortunately that doesn't seem to help. 🤔

**Comment by flybayer** [comment]
Oh wait, this is an issue with yarn >1.19.1.

You have to run `yarn policies set-version 1.19.1` at the root 🤦  Yarn is such a bummer these days

**Comment by ryardley** [comment]
Ahhh ok that crap again. Must have reverted somehow.

**Comment by flybayer** [comment]
We need to add a section to the contributor guide that, after cloning, you need to run `yarn policies set-version 1.19.1` 

Also add to the troubleshooting section about what to do if you get this error:
```
An unexpected error occurred: "expected workspace package to exist for \"@wessberg/rollup-plugin-ts\"
```

**Comment by wKovacs64** [comment]
FYI, I've got my Yarn policy set to 1.19.1 and still get this occasionally (maybe after installing a new dependency - working on something else and haven't had a chance to investigate further). 🤔

**Comment by cardotrejos** [comment]
Can take this issue?

**Comment by flybayer** [comment]
@cardotrejos yes! So add a section that says if you get that above error, try setting the yarn policy thing.
