### ISSUE TITLE
blitz generate all should adapt to the chosen default form 

### ISSUE THREAD

**Issue by kenneho** [blitz-js/blitz#1691]
### What do you want and why?

I chose `react-final-form` as the default form when bootstrapping the project. When running `blitz generate all product`, however, it doesn't seem to provide a Final Form setup. In order to convert `product` to be using Final Form in the same way say the stock `login` form does, there seems to be some rewrite I'd have to make, especially if I try and reuse the way it's setup up with the stock `login` form. I would be great if `blitz generate all ...` would create forms according to the default form. 

### Possible implementation(s)

If info about the chosen default form is available, `blitz generate all` could take this into account when creating forms. Else, one could add a parameter to `blitz generate all` so that the user could provide info about which form to use. 

### Additional context

In addition to the form itself, it would be great if the form fields were placed in a `validations` file, just as the stock `login` setup does, so that the form could use this data to validate to the form.

**Comment by flybayer** [comment]
Yes! Will have to wait until we refactor and improve some of the codegen infrastructure first, so putting in icebox for the moment.
