### ISSUE TITLE
Fails tests around DataBase and Prisma at @examples/store

### ISSUE THREAD

**Issue by koolii** [blitz-js/blitz#1701]
### What is the problem?

it happens errors when I exec `yarn test`.

it seems that the following test is weird.

`prisma generate && blitz prisma migrate deploy --preview-feature && blitz db seed && blitz build && blitz start --production -p 3099`

### Steps to Reproduce

1. exec `git pull upstream canary`
2. check commit id `git log |grep '^commit' |head -1|awk '{print $2}'` => `62efe3f4eefc371bb57a7a5d1a2d5275c03a27a9`
3. exec `yarn test` at blitz's root

### Versions

```
output of `blitz --version --verbose`

% blitz --version --verbose~
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

macOS Catalina | darwin-x64 | Node: v14.15.3

blitz: 0.29.0-canary.0 (local)

  Package manager: yarn
  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.44 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.3/bin/yarn
    npm: 6.14.9 - ~/.nvm/versions/node/v14.15.3/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: Not Found
    @prisma/client: Not Found
    blitz: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: 4.1.3 => 4.1.3
```

### Other

Please include applicable logs and screenshots that show your problem.

<img width="1474" alt="スクリーンショット 2021-01-12 19 36 23" src="https://user-images.githubusercontent.com/3866581/104304245-7ffb2280-550e-11eb-8cd1-102687ac918b.png">
<img width="668" alt="スクリーンショット 2021-01-12 19 37 27" src="https://user-images.githubusercontent.com/3866581/104304261-86899a00-550e-11eb-8367-fc8911bfe282.png">

**Comment by flybayer** [comment]
This is because of the prisma upgrade.


### Solution

`rm examples/store/db/db.sqlite`

And repeat for any of the other example apps if needed

**Comment by koolii** [comment]
I understood it all :) thank you for telling me.
Let me ask you a question. 
Don't it need to delete it(or them) automatically? or just delete it by myself at this time because only uses prisma from now on?

**Comment by flybayer** [comment]
Just needs deleted one time for this upgrade

**Comment by koolii** [comment]
OK, I appreciate it :), Closing here!
