### ISSUE TITLE
Tool To Visualize App Changes Between Versions (copy and tweak this tool from React Native)

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1703]
### What do you want and why?

As time goes on we make changes to the new app template that existing blitz apps might want. As well as breaking changes here in the pre-1.0 era.

Currently it's difficult to see the changes between version, especially when jumping multiple versions at once.

The solution is a web tool to visualize the changes between versions [just like react native has](https://react-native-community.github.io/upgrade-helper/).

### Possible implementation(s)

This should be fairly straightforward by modifying the react-native one. How it works is that you create a new branch for each release like `release/0.28.0` and generate a new blitz app on that branch. They have a script that automates this process. Then the web UI will fetch the diff between branches straight from the Github API.

1. I have already forked https://github.com/react-native-community/rn-diff-purge to a new blitz repo: https://github.com/blitz-js/versions-diff
2. Need to delete all the RN release branches and stuff
3. Modify the scripts to generate a blitz app instead of react-native app
4. Push new release branches for existing versions of Blitz
4. Update branding, like favicon, etc

I will give direct access to this repo to whoever wants to work on this.

**Comment by matthieu994** [comment]
Hello @flybayer !
I would like to work on this :)
I've already started to change commands and I'm trying to find out what needs to be modified for Blitz.

**Comment by flybayer** [comment]
Awesome! Let me know if you have any questions

**Comment by matthieu994** [comment]
Thanks ! Can I have access to the repo ?

**Comment by flybayer** [comment]
@matthieu994 done. Accept here: https://github.com/blitz-js/versions-diff/invitations

**Comment by matthieu994** [comment]
Hello @flybayer !

Any idea how to skip this : 
```
? Your global blitz version is outdated. Upgrade? … 
▸ Yes - Upgrade to 0.31.1
  No - Continue with old version (0.30.4) - NOT recommended
```
when I run `npx blitz@0.30.4 new BlitzDiffApp` ?
Because the script is gonna run the `new` command for each and every version of Blitz, and it would be super cool if we don't have to press 'No', and then `React Final Form` for every run.

**Comment by matthieu994** [comment]
Hello !
Turns out rn-diff-purge uses 2 repos to generate the github.io webpage. I've forked the second one : https://github.com/matthieu994/upgrade-helper

There are still bugs, especially with the react-diff-view library. (see console)
And the canary versions are removed from the version selector.
I will look into this, but you can already have a look and maybe deploy somewhere. :)

**Comment by flybayer** [comment]
@matthieu994 thank you!

I've been swamped this week, but I'll try to review asap

**Comment by flybayer** [comment]
@matthieu994 ok wow, this is so cool!! 👉  https://github.com/blitz-js/versions-diff

I've ported your repo here: https://github.com/blitz-js/versions-diff-web And it's now auto deployed to https://diff.blitzjs.com (but broken, like you said)

**Comment by flybayer** [comment]
Also did you figure out how what I need to do to get it automated?
