### ISSUE TITLE
Meta: Form-Based Issue Templates

### ISSUE THREAD

**Issue by Skn0tt** [blitz-js/blitz#1704]
### What do you want and why?

The Next.js repository has [form-based issue templates](https://github.com/vercel/next.js/issues/new?assignees=&labels=template%3A+bug&template=1.bug_report.yml&title=). I quite like this and I think we should also adopt it.

### Possible implementation(s)

Take a look at Next's [issue templates](https://github.com/vercel/next.js/tree/canary/.github/ISSUE_TEMPLATE) and adapt it to our liking.

### Additional context

<img width="931" alt="Screenshot 2021-01-12 at 20 26 15" src="https://user-images.githubusercontent.com/14912729/104362696-6d83e780-5514-11eb-981b-42bbab3bb2dd.png">

**Comment by flybayer** [comment]
Oh interesting. That's an early access thing. I sent an email, so we'll see what happens.

**Comment by sinn22** [comment]
Hi! I would like to do this issue! May I do it?

**Comment by Skn0tt** [comment]
You're very welcome to! We'll have to wait for the feature to become publicly available, though.

**Comment by flybayer** [comment]
Actually our repo is now in the beta program. I've just been focused on the beta release instead of adding this :)

**Comment by sinn22** [comment]
Thank you for replay!
I didn't know this feature is not public.
Should I start this issue when this feature is public released?

**Comment by flybayer** [comment]
# Issue Forms Alpha


## Set up instructions


1. Add a new YAML file and name it `.github/ISSUE_TEMPLATE/template.yml`, where “template.yml” is the name of your form (e.g., "bug_report.yml").
2. Open up the [documentation site](https://gh-community.github.io/issue-template-feedback/alpha/). Now, in the body of your YAML file, try creating a new issue template form using the docs. You can also try converting one of your previous issue templates to the new structure.

**Comment by sinn22** [comment]
OK! I`ll create PR. Thanks!
