### ISSUE TITLE
React-hook-form intermittent infinite loop with AuthenticationError / ErrorBoundary in Firefox

### ISSUE THREAD

**Issue by shrugs** [blitz-js/blitz#1708]
### What is the problem?

With the default ErrorBoundary, when a query throws an AuthenticationError, a sometimes infinite render loop occurs in firefox.

I've narrowed some of the behavior down to the firefox browser, and then further narrowed some of the behavior to a blitz app with forms using `react-hook-form`.

### Steps to Reproduce

1. clone the repo
2. `yarn`
3. `blitz prisma migrate --preview-feature`
4. `yarn start`
5. go to http://localhost:3000/questions/id/edit in firefox with the console open
6. notice the infinite render loop, if it occurs. otherwise, notice the volume of thrown errors
7. compare that to chrome, which only throws once or twice before rendering `LoginForm`
8. in the case of an infinite render loop, tab away from the page and return to see that the ErrorBoundary has correctly rendered the LoginForm

Reproductions:

1. https://github.com/shrugs/blitz-auth-loop-final-form
  - `blitz new test` (final-form), `blitz install chakra`, `blitz generate all question name`
  - this one doesn't infinite loop
2. https://github.com/shrugs/blitz-auth-loop-hook-form
  - `blitz new test2` (react-hook-form), `blitz install chakra`, `blitz generate all question name`
  - this one does seem to infinite loop

### Versions

I can reproduce in 0.28.0 and 0.29.0.

```
debug: blitzPkgPath: /Users/matt/Desktop/test/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/matt/Desktop/test/node_modules/@blitzjs/cli/lib/src/index.js 

macOS Big Sur | darwin-x64 | Node: v15.5.1

blitz: 0.29.0 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.05 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.5.1 - ~/.nvm/versions/node/v15.5.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.3.0 - ~/.nvm/versions/node/v15.5.1/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: ~2.14 => 2.14.0 
    @prisma/client: ~2.14 => 2.14.0 
    blitz: 0.29.0 => 0.29.0 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: 4.x => 4.1.3 
```

**Comment by flybayer** [comment]
Thanks for the detailed issue! 

You have a typo in this section: the link doesn't match the name in parenthesis
> 1. [shrugs/blitz-auth-loop-final-form](https://github.com/shrugs/blitz-auth-loop-final-form)
> 
> * `blitz new test` (react-hook-form), `blitz install chakra`, `blitz generate all question name`
> * this one doesn't infinite loop
> 
> 1. [shrugs/blitz-auth-loop-hook-form](https://github.com/shrugs/blitz-auth-loop-hook-form)
> 
> * `blitz new test2` (final-form), `blitz install chakra`, `blitz generate all question name`
> * this one does seem to infinite loop

**Comment by flybayer** [comment]
Please update react and react-dom to `0.0.0-experimental-6a589ad71` and test again

**Comment by shrugs** [comment]
i'm still seeing the behavior in https://github.com/shrugs/blitz-auth-loop-hook-form after only updating react to that tag. the reproduction is based on blitz2 - do you think it's worth updating to blitz@latest, ensuring the app still builds, and testing again? or is the problem definitely on the react side, and that wouldn't be a good use of time?

**Comment by flybayer** [comment]
Thanks! And yes definitely worth upgrading to latest blitz and testing again.

**Comment by shrugs** [comment]
nice! I've verified that the reproduction, with blitz 0.33.0 using the (currently default after `blitz new`) react version `0.0.0-experimental-3310209d0`, does not loop in firefox. i didn't try react version `0.0.0-experimental-6a589ad71` since it seemed unnecessary.

here's the version that worked: https://github.com/shrugs/blitz-3-auth-loop-hook-form

**Comment by remjx** [comment]
I'm running into this issue while trying to upgrade to Blitz  0.34.0. I tried both React versions `0.0.0-experimental-3310209d0` and `0.0.0-experimental-6a589ad71` in both Chrome and Firefox. 

`ctx.session.$authorize()` is throwing in the query, then it keeps retrying the query in an infinite loop instead of redirecting.
