### ISSUE TITLE
Models that ends with a number trigger a bug in the pluralization function 

### ISSUE THREAD

**Issue by kenneho** [blitz-js/blitz#1713]
### What is the problem?

Models that ends with a number triggers a bug in the pluralization function.

From @flybayer on Slack: 
> This is a bug in your pluralization function! We make all folder names plural but we need to disable that for numbers.

### Steps to Reproduce

1.Run `blitz generate all test002`

```
CREATE    app/test002-s/pages/test002-s/[test002Id]/edit.tsx
CREATE    app/test002-s/pages/test002-s/[test002Id].tsx
CREATE    app/test002-s/pages/test002-s/index.tsx
CREATE    app/test002-s/pages/test002-s/new.tsx
CREATE    app/test002S/components/Test002Form.tsx
CREATE    app/test002S/queries/getTest002.ts
CREATE    app/test002S/queries/getTest002S.ts
CREATE    app/test002S/mutations/createTest002.ts
CREATE    app/test002S/mutations/deleteTest002.ts
CREATE    app/test002S/mutations/updateTest002.ts
```

### Versions

```
output of `blitz --version --verbose`
```

### Other

Please include applicable logs and screenshots that show your problem.

**Comment by flybayer** [comment]
Duplicate https://github.com/blitz-js/blitz/issues/1715

**Comment by kenneho** [comment]
Sorry, got an error from Github when trying to register the issue, so I got registered twice.
