### ISSUE TITLE
Performance: don't call findDuplicates for every file

### ISSUE THREAD

**Issue by malkomalko** [blitz-js/blitz#1729]
### What do you want and why?

Doing some debugging while figuring out how to dev locally using yalc, and I found that the below code is being called for every file.

https://github.com/blitz-js/blitz/blob/66d8aa48a783b36343cd03bf26d98c7eff9dc897/packages/server/src/stages/pages/index.ts#L79-L103

### Possible implementation(s)

A simple enhancement would be to only check for duplicates after all the files have been parsed as it's meant to throw an error if duplicates are found.

**Comment by flybayer** [comment]
Putting in icebox because this should be fixed by this coming change: https://github.com/blitz-js/blitz/discussions/1990

**Comment by flybayer** [comment]
This code was removed awhile back
