### ISSUE TITLE
CLI doesn't handle typos gracefully

### ISSUE THREAD

**Issue by aem** [blitz-js/blitz#173]
#153 prompted a thought about how we could better support users who mistype commands. Currently we just display an error message and a list of all possible commands. I posed the following thought:

> I wonder if we could compute some kind of distance algorithm (e.g. https://github.com/trekhleb/javascript-algorithms/tree/master/src/algorithms/string/levenshtein-distance) and then suggest a command to run instead, maybe even with a way for the user to run it immediately? An interaction like this might be cool:

```bash
$ blitz nwe

Command `nwe` not found.

# only if we compute a close match, cache that
# command until the next CLI invocation
Did you mean to run the `new` command? If so run `blitz -y`
```

> The next invocation would always clear the cache, regardless of what's called, but if the command is `blitz -y` we'll execute the cached command, passing in the same arguments as before if any were supplied.

@flybayer proposed an additional nice functionality might even be to prompt the user directly, to avoid having to invoke the CLI again. This has the added benefit of not needing to persist information to disk somewhere.

**Comment by flybayer** [comment]
Guess what.. oclif already has this. It was just broken. Upgrading oclif fixed it. Here's what we get now:

```
~/c/blitz> blitz dd

 ›   Warning: dd is not a blitz command.
Did you mean db? [y/n]:
```

**Comment by aem** [comment]
Oh even better. I thought that comment was just referring to the help text! I'll go ahead and close this then
