### ISSUE TITLE
Disable `react-query` suspense when using legacy React

### ISSUE THREAD

**Issue by anteprimorac** [blitz-js/blitz#1732]
### What do you want and why?
Currently switching `reactMode` experimental option to `legacy` requires going to every `useQuery` call and setting `suspense` to `false`.

### Possible implementation(s)
Make `defaultQueryConfig.suspense` dependable on `reactMode` experimental option.

**Comment by malkomalko** [comment]
👋🏻 Ante.  An amazing community member posted this gist for helping with the above https://gist.github.com/Zeko369/a0bd1acbb6feeeee512294f9ab6d44e7.

❓ Do we want to think about swapping this in during the compilation phase as a default if we know that we're using legacy mode.
