### ISSUE TITLE
Next/Image Invalid URL

### ISSUE THREAD

**Issue by marciomrb** [blitz-js/blitz#1737]
Hello, I got this error 
```
Error: Invalid src prop (http://cdn.dota2.com/apps/dota2/images/heroes/axe_vert.jpg) on `next/image`, hostname "cdn.dota2.com" is not configured under images in your `next.config.js`
```

but in my blitz.config.js

```
const { sessionMiddleware, simpleRolesIsAuthorized } = require("@blitzjs/server")

module.exports = {
  middleware: [
    sessionMiddleware({
      isAuthorized: simpleRolesIsAuthorized,
    }),
  ],
  images: {
    domains: [
      "cdn.dota2.com",
      "api.dota2brasil.com.br",
      "cdn.stratz.com",
    ],
  }, 
}
```

**Comment by flybayer** [comment]
Can you link a reproduction repo?

And next time please keep the Github bug template including instructions like including output of `blitz -vV`.

**Comment by MrLeebo** [comment]
@marciomrb This appears to be working as far as I can tell. You may need to restart your dev server for the config to take effect. I tried to create a repro, but the image loaded successfully. https://codesandbox.io/s/quirky-greider-d2ku4?file=/blitz.config.js

Feel free to re-open if there's something I missed.
