### ISSUE TITLE
Error when trying to run the migration to my mysql database

### ISSUE THREAD

**Issue by javierfuentesm** [blitz-js/blitz#1746]
### What is the problem?

I made the changes to connect to my remote mysql server ,but when I run 
blitz prisma migrate dev --preview-feature
To create the User and Session table in my database
I got this error 

![image](https://user-images.githubusercontent.com/19244527/104996490-9234ff00-59ed-11eb-9fbc-342bb02b7681.png)

### Versions

```
output of `blitz --version --verbose`
```
![image](https://user-images.githubusercontent.com/19244527/104996520-a1b44800-59ed-11eb-99c9-905e146cdac3.png)

### Other

Please include applicable logs and screenshots that show your problem.

**Comment by flybayer** [comment]
Hey @javierfuentesm, this is a Prisma issue so you'll need to open an issue on [the Prisma github](https://github.com/prisma/prisma) or ask in the prisma slack. :)
