### ISSUE TITLE
Queries run before session data is fully loaded

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1752]
### What is the problem?

Queries run while `session.isLoading === true`. This causes the following code to first run with wrong input data:

```ts
const session = useSession()
const [data] = useQuery(getData, {where: {id: session.userId}})
```

### Steps to Reproduce

1. Use above query and watch server logs. You will see `{where: {id: undefined}}`

### Versions

```
0.29.2
```

### Other

I attempted a fix in https://github.com/blitz-js/blitz/pull/1751 but that didn't work because `useEffect` doesn't run when a component is suspended. However the use query hooks do re-render if `router` changes (which we depend on by waiting for `router.isReady === true` before running the query).

### How To Fix

We need to change `useSession` and publicdata implementation to use React Context instead of the proxy thing we are using currently. 

- Add our own `SessionContext` provider to keep session data
- Change `useSession` to use from that context. 
- Add a new `withBlitzAppRoot` HOC which will wrap the component with `SessionContext.Provider` (you can test by manually adding to `_app.tsx`
- Add babel plugin to automatically wrap default export in `_app` with `withBlitzAppRoot`
  - Our babel config is here: https://github.com/blitz-js/blitz/blob/canary/packages/babel-preset/src/index.ts
  - You can add `packages/babel-preset/src/add-blitz-app-root.ts` and then import and include that file in the above preset file.

**Comment by jan-wilhelm** [comment]
could you explain briefly what's causing this? From my understanding, I would've assumed that useSession simply suspends while loading, causing React to stop rendering and not calling any consecutive hooks.

**Comment by flybayer** [comment]
`useSession` doesn't use suspense (maybe it should)

**Comment by mtford90** [comment]
Seem to be experiencing something like this myself. If I log into my app, some of the queries run before the session is configured - this causes an AuthenticationError which boots the user back to the login screen immediately.

If I then refresh the page all is well & the user is logged in.

**Comment by mtford90** [comment]
As expected the following workaround seems to fix this issue:

```ts
import { useSession } from "@blitzjs/core"
import { FirstParam, PromiseReturnType, QueryFn } from "@blitzjs/core/dist/packages/core/src/types"
import { QueryOptions } from "react-query"
import { useQuery } from "blitz";

// TODO: Remove this once Blitz prevents queries being fired when the session is loading
export function useSessionSafeQuery<T extends QueryFn, TResult = PromiseReturnType<T>>(queryFn: T, params: FirstParam<T>, options?: QueryOptions<TResult>) {
  const session = useSession();
  const enabled = options?.enabled

  return useQuery<T, TResult>(queryFn, params, {
    ...options,
    enabled: enabled && !session.isLoading
  })
}
```

On a side note, amazing work with this library @flybayer & co - I've been converting our nextjs/graphql monolith over to Blitz as an experiment - and the amount of boilerplate that's disappearing is amazing.

**Comment by mtford90** [comment]
Note: the above workaround does NOT work with suspense due to the fact that `useSession` itself does not suspend. Perhaps it should?

I've only just started digging into the Blitz codebase & this is also my first time experimenting with `Suspense` in general -  but I was able to hack together a way to suspend `useSession`. It works but it's ugly & I had to modify `publicDataStore`...

@flybayer I'm sure you have a better idea of how to implement this - would love to hear how you'd attack this problem.

```ts
const suspendedPublicData = suspend(
  (() =>
    new Promise<PublicData>((resolve) => {
      if (publicDataStore.lastUpdate) {
        resolve(publicDataStore.lastUpdate)
      } else {
        const subscription = publicDataStore.observable.subscribe((data) => {
          resolve(data)
          subscription.unsubscribe()
        })
      }
    }))()
)

export const useSuspendedSession = () => {
  const [publicData, setPublicData] = useState(publicDataStore.lastUpdate || suspendedPublicData())

  useIsomorphicLayoutEffect(() => {
    // Initialize on mount
    const subscription = publicDataStore.observable.subscribe(setPublicData)
    return subscription.unsubscribe
  }, [])

  return { ...publicData }
}

// TODO: Remove this once Blitz prevents queries being fired when the session is loading
export function useSessionSafeQuery<T extends QueryFn, TResult = PromiseReturnType<T>>(
  queryFn: T,
  params: FirstParam<T>,
  options?: QueryOptions<TResult>
) {
  useSuspendedSession() // Ensure that session has been initialised before queries execute
  return useQuery<T, TResult>(queryFn, params, options)
}
