### ISSUE TITLE
Files compiled or cached in ./blitz are not deleted, when renaming or delete from src

### ISSUE THREAD

**Issue by kivi** [blitz-js/blitz#1756]
### What is the problem?

When I create a file app, it will also created in ./blitz/caches/dev
When I delete or rename the file, it is not deleted or renamed  from>./blitz/caches/dev

### Steps to Reproduce

1.  create a file in app/auth/pages
2. delete that file
3. check in ./blitz/caches/dev/pages - the file created in step 1. will still be here

### Versions

blitz: 0.29.2

**Comment by flybayer** [comment]
Related issue (maybe duplicate): https://github.com/blitz-js/blitz/issues/1712
