### ISSUE TITLE
Prisma case-insensitive filtering not working

### ISSUE THREAD

**Issue by vonphlpp** [blitz-js/blitz#1768]
Hi, can't use [case-insensitive](https://www.prisma.io/docs/concepts/components/prisma-client/case-sensitivity#options-for-case-insensitive-filtering) filtering in a query like:

```
const users = await prisma.user.findMany({
  where: {
    email: {
      endsWith: "prisma.io",
      mode: "insensitive", 
    },
  },
});
```
Without ```   mode: "insensitive" ``` it is working. I get the error:
```
Argument email: Got invalid value 
{
  endsWith: 'prisma.io',
  mode: 'insensitive'
}
on prisma.findManyUser. Provided Json, expected StringFilter or String.
```
and ts-error: 
```
Type '{ endsWith: string; mode: string; }' is not assignable to type 'string | StringFilter | undefined'.
  Object literal may only specify known properties, and 'mode' does not exist in type 'StringFilter'.
```
Version:
```
 "blitz": "0.29.2",
  "@prisma/cli": "~2.14",
  "@prisma/client": "~2.14",
```

Thx for any help.

**Comment by flybayer** [comment]
Hey @vonphlpp, not sure what the issue here. It's prisma specific, so please open an issue in their repo: https://github.com/prisma/prisma

:)
