### ISSUE TITLE
Blitz file path replacement in logs is broken

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#178]
**What is the problem?**

Blitz server isn't swapping out the file paths properly in the Next.js output. See the wrong output in the log below.

**Steps to Reproduce:**

1. Delete `examples/store/node_modules/@prisma/client`
2. Run `blitz build` in the store example

**Versions:**

- Blitz: canary
- OS: macOS

**Supporting Documentation**
```
~/c/b/e/store> blitz b
✔ Blitz is ready
Warning: You have enabled experimental feature(s).
Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

Creating an optimized production build

Failed to compile.

/Users/b/c/blitz/examples/store/.blitz/caches/build/app/_rpc/products/mutations/createProduct.ts
ERROR in /Users/b/c/blitz/examples/store/.blitz/caches/build/app/_rpc/products/mutations/createProduct.ts(1,13):
1:13 Module '"../../../../../../../../../../../../../Users/b/c/blitz/examples/store/.blitz/caches/build/db"' has no exported member 'ProductCreateArgs'. Did you mean to use 'import ProductCreateArgs from "../../../../../../../../../../../../../Users/b/c/blitz/examples/store/.blitz/caches/build/db"' instead?
  > 1 | import db, {ProductCreateArgs} from 'db'
      |             ^
    2 |
    3 | export default async function createProduct(args: ProductCreateArgs) {
    4 |   const product = await db.product.create(args)


> Build error occurred
Error: > Build failed because of webpack errors
    at build (/Users/b/c/blitz/node_modules/next/dist/build/index.js:13:900)
```

**Comment by ryardley** [comment]
I never actually implemented it on build. I didn't think it was as important as during it during `blitz start`

**Comment by flybayer** [comment]
I've seen this same thing in blitz start

**Comment by flybayer** [comment]
Would it be easier to build directly into `/.blitz` or something top level so there's only 1 path item to modify instead of 3 levels?

**Comment by ryardley** [comment]
Playing around I moved the build folder out to its own folder and ran yarn install and next on the project which should then run just like a normal next app. I get the same sort of error. 

```
projects/blitz/build via ⬢ v12.16.1
➜ y next build
yarn run v1.22.4
$ /Users/rudiyardley/projects/blitz/build/node_modules/.bin/next build
Warning: You have enabled experimental feature(s).
Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

Creating an optimized production build

Failed to compile.

/Users/rudiyardley/projects/blitz/build/app/_rpc/products/mutations/createProduct.ts
ERROR in /Users/rudiyardley/projects/blitz/build/app/_rpc/products/mutations/createProduct.ts(1,13):
1:13 Module '"../../../../../../../../../Users/rudiyardley/projects/blitz/build/db"' has no exported member 'ProductCreateArgs'. Did you mean to use 'import ProductCreateArgs from "../../../../../../../../../Users/rudiyardley/projects/blitz/build/db"' instead?
  > 1 | import db, {ProductCreateArgs} from 'db'
      |             ^
    2 |
    3 | export default async function createProduct(args: ProductCreateArgs) {
    4 |   const product = await db.product.create(args)


> Build error occurred
Error: > Build failed because of webpack errors
    at build (/Users/rudiyardley/projects/blitz/build/node_modules/next/dist/build/index.js:13:900)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This makes me think that the copious relative pathing must be either a next or a webpack issue. It might be worth exploring if there is a webpack configuration we can provide.

---

Secondly, our rpc stuff isn't captured by the error path replacement possibly because file history isn't preserved. (Basically that section is still a bit on the hacky side and I didn't really overhaul during the refactor because I wanted to setup the basic patterns first so others can work on the rules code.)

**Comment by flybayer** [comment]
Ok thank's for checking this. Maybe it's related to the experimental Next feature we are using for jsconfig/tsconfig baseUrl. 

We could try with the latest next canary.

This isn't critical.

**Comment by flybayer** [comment]
Still showing the super ugly file path in latest blitz canary.

**Comment by abuuzayr** [comment]
I get this error sometimes too, on Ubuntu 18.04. But sometimes I also don't get this error. How do I bypass this in the meantime when I need to run `blitz build`?
