### ISSUE TITLE
has no exported member 'PrismaClient'

### ISSUE THREAD

**Issue by estevanjantsk** [blitz-js/blitz#1783]
### What is the problem?

When I install all deps and everything to run the project, then I access db/index.ts you will see this warning in your VSCode:

import { PrismaClient } from "@prisma/client" -> has no exported member 'PrismaClient'

### Steps to Reproduce

1. access db/index.ts (using vscode)
2. you will see the message

### Versions

```
macOS Mojave | darwin-x64 | Node: v14.15.3

blitz: 0.29.3 (local)

  Package manager: yarn 
  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 18.48 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.14.9 - ~/.nvm/versions/node/v14.15.3/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: ~2.14 => 2.14.0 
    @prisma/client: ~2.14 => 2.14.0 
    blitz: 0.29.3 => 0.29.3 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: 4.1.3 => 4.1.3 `
```

### Possible FIX

So I did a quick research and I've found this link: https://github.com/prisma/prisma/issues/2584#issuecomment-646414549
So I added this new line: 
![image](https://user-images.githubusercontent.com/461342/105576644-e5f07100-5d7c-11eb-991d-83d9694b23f9.png)

Restarted my server and ts server (I think what matters here is ts server) and all the "prisma type errors" went away. So I think this line should be added to the code that blitz generates :). This will even fix an error that Brandon had here (https://youtu.be/jjYd67R-Mi4?t=3124) =)

**Comment by flybayer** [comment]
Hey @estevanjantsk, that change is not needed for this work. Sounds like the main issue you had is the VSCode TS server which we can't do anything about unfortunately.

If you still have an issue with this, then open an issue in the prisma repo where they can help better: prisma/prisma: Modern database access (ORM alternative) for Node.js & TypeS…
