### ISSUE TITLE
Directory styles are not unified

### ISSUE THREAD

**Issue by marina-ki** [blitz-js/blitz#1784]
### What do you want and why?

`$ blitz g all userGroups` generates these files.

```
CREATE    app/user-groups/pages/user-groups/[userGroupId]/edit.tsx
CREATE    app/user-groups/pages/user-groups/[userGroupId].tsx
CREATE    app/user-groups/pages/user-groups/index.tsx
CREATE    app/user-groups/pages/user-groups/new.tsx
CREATE    app/userGroups/components/UserGroupForm.tsx
CREATE    app/userGroups/queries/getUserGroup.ts
CREATE    app/userGroups/queries/getUserGroups.ts
CREATE    app/userGroups/mutations/createUserGroup.ts
CREATE    app/userGroups/mutations/deleteUserGroup.ts
CREATE    app/userGroups/mutations/updateUserGroup.ts
```

Directory names should be unified to camel case or ~~snake case~~ kebab-case. I think camel case would be better.

#### Versions
```
0.29.3
```

**Comment by nitaking** [comment]
We need to decide which scope and which case(camel case or snake case) you want to use.

**Comment by nitaking** [comment]
@flybayer 

@marina-ki 's idea: 

```
app/userGroups/pages/user-groups/new.tsx
```

Only under `pages/**` should be snake case. I agree too.

**Comment by MrLeebo** [comment]
To clarify, `user-groups` is kebab-case, if it were snake_case, it would be `user_groups`. We definitely want to use kebab-case for pages/** for better SEO, and I agree with using camelCase for the module folder names.

**Comment by flybayer** [comment]
Well that's odd. This was supposed to be fixed in https://github.com/blitz-js/blitz/pull/1554 🤔 

All the directories should be kebab-case.

**Comment by marina-ki** [comment]
Can i work on this issue?

**Comment by flybayer** [comment]
@marina-ki yes!

**Comment by tarunama** [comment]
@marina-ki 
Please add version information to issue description, and confirm to reproduct in `blitz@latest` ?

**Comment by flybayer** [comment]
@tarunama I already confirmed it's broken in latest blitz.

But yeah @marina-ki, when opening an issue please keep the version info like is in the new issue template and include output of `blitz -vV`.

**Comment by marina-ki** [comment]
Oh, I'm sorry! added the version info :+1:
