### ISSUE TITLE
Setup memory file system for tests

### ISSUE THREAD

**Issue by ryardley** [blitz-js/blitz#179]
**What do you want and why do you want it?.**
We need to setup an in-memory file system for our file writing mocks here https://github.com/blitz-js/blitz/tree/canary/packages/server/test

Problem that is happening occasionally is that if a test fails to clean up the file system the files left over could be accidentally checked into git also an inmem fs would have a clean up/ reset method we could call on beforeEach.

Also this should theoretically speed up our tests as they would require less disk access.

**Possible implementation(s)**
Possibly metro-memory-fs mem-fs memfs or jest-plugin-fs not sure which one is best

**Background**
I had a super quick go but was getting errors on first pass so I put it down and wrote this up to see if anyone wants to have a go. I think there is going to be a bit of investigation to work out what's going on.

**Comment by dajinchu** [comment]
down to try working on this
