### ISSUE TITLE
useQuery return null query parameter and when getInitialProps in _app.ts (from v0.29.3)

### ISSUE THREAD

**Issue by matthieuh** [blitz-js/blitz#1795]
### What is the problem?

Migrating from 0.28 to 0.29.3 I'm starting to experience a reproducible issue. If a getInitialProps is added in _app.ts (even if not advised to do it) then adding a query parameter in any app route is breaking useQuery hooks returning always `null.`

### Steps to Reproduce

=> https://codesandbox.io/s/busy-brahmagupta-j52mw

- Add a getInitialProps in _app.ts
- Create a page having a useQuery hook console logging its value
- Add a query parameter in the URL
- Refresh your page having the useQuery hook
- You should see that the value is always `null`

### Versions

```
blitz --version --verbose
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: /Users/matthieuhostache/workspace/perso/budg/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/matthieuhostache/workspace/perso/budg/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js

macOS Big Sur | darwin-x64 | Node: v12.13.1

blitz: 0.29.3 (global)
blitz: 0.29.3 (local)

  Package manager: npm
  System:
    OS: macOS 11.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 19.68 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.13.1/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: ~2.15 => 2.15.0
    @prisma/client: ~2.15 => 2.15.0
    blitz: 0.29.3 => 0.29.3
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    typescript: 4.0.3 => 4.0.3
```

### Other

https://user-images.githubusercontent.com/1550192/105819838-0442b080-5fb9-11eb-8e42-24aecc3f00be.mov

**Comment by Zeko369** [comment]
Hey @matthieuh ,

first, next and therefor blitz deprecated `getInitialProps` in favour of `getServerSideProps` (same thing but new name). Even though
```
export const getInitialProps = () => {} // works
App.getInitialProps = () => {} // breaks
```

second, add types where you can so you can see errors before they happen, you were returning `{cookies: string}` and next expects `{props: {}}` from getServerSideProps function
```tsx
export const getServerSideProps: GetServerSideProps = async (ctx) => {
  // ctx.req?.headers?.cookie

  return { props: {} }
}
```

Also don't know if you're planning on using cookies for anything besides auth check out [nookies](https://github.com/maticzav/nookies)

**Comment by matthieuh** [comment]
I haven't seen anywhere in the doc saying that getInitialProps is deprecated. In NextJS it's not it's just recommended to not use it in _app.js disabling static optimization on all your app pages. Moreover ```export const getInitialProps = () => {}``` is not something working and IMO even if not recommended it should work.

**Comment by Zeko369** [comment]
Ok I expressed it wrong, it's not depracted per say, it's just [not used any more](https://nextjs.org/docs/api-reference/data-fetching/getInitialProps) since there is an alternative method getServerSideProps that does the same thing, and in this specific case doesn't have the bug you're describing

() => {} was just a shorthand for a function example, sorry if it was missleading

Can you try using either `export const getInitialProps` or `export const getServerSideProps` or even `App.getServerSideProps`, becuase all of these seem to work fine on my machine.

Also the main reason I'm suggesting using getServerSideProps instead of getInitialProps is that although they're the same the types exported by blitz are `GetServerSideProps` so it could get confusing in the future when someone is looking at the code and sees

```ts
export const getInitalProps: GetServerSideProps
```

**Comment by matthieuh** [comment]
In NextJS `getServerSideProps` can't be used in `_app.js` only `App.getServerSideProps` works. That's why it's problematic if using it app is stuck using query parameters...

**Comment by flybayer** [comment]
@Zeko369 `getInitialProps` is not deprecated and is still used very heavily in many apps. It's here to stay. Yes, if `gSSP` can be used, that's better but still need `gIP` for many things.

**Comment by flybayer** [comment]
@matthieuh this issues _sounds like_ a bug in Next.js with their `router.isReady` logic. Because we use that flag to determine when to run the query.

You could test the latest next.js canary to see if fixed using yarn resolutions in package.json

```
  "resolutions": {
    "next": "10.0.6-canary.8"
  },
```
Run `yarn` after adding that

**Comment by matthieuh** [comment]
Trying with next `10.0.6-canary.8` I get `Error: Cannot find module 'webpack'` and testing with next `10.0.6-canary.0` it's compiling but I'm getting the same issue.

**Comment by flybayer** [comment]
Ok will sit on this until next stable next.js release and test again

**Comment by MrLeebo** [comment]
We've had a couple of releases since then. What is the status of this issue now?

**Comment by MrLeebo** [comment]
Closing for staleness
