### ISSUE TITLE
`blitz install` has a bad error message if recipe doesn't exist

### ISSUE THREAD

**Issue by chrisbull** [blitz-js/blitz#1803]
### What do you want and why?

When running `blitz install chakra` you get an error that says `no such file or directory, open './package.json'` 

This was my own dumb fault cause it's supposed to be `chakra-ui` not `chakra` 

A suggestion would be to provide an error like `"chakra" is not a valid recipe name"

An even better suggestion would be to allow for an auto-selection (and multi-selection) feature in the cli to select all the recipes you want in one go.

**Comment by flybayer** [comment]
Oh yes, thank you @chrisbull! We do want to add auto selection, but will take this particular issue just for fixing the error message.

For whoever wants to work on this, here is the file and code that needs fixed: https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/install.ts#L167

It looks like we do have a check there and an error message but that code isn't being ran for some reason.

That command is set up so you can pass a local file path like `blitz install ../recipes/something`. And it seems it's going down that path in this case.

**Comment by rince** [comment]
@flybayer 
I'd like to tackle this issue :)

**Comment by flybayer** [comment]
@rince all yours! :)
