### ISSUE TITLE
Does not support URL with unicode or space?

### ISSUE THREAD

**Issue by ctrngk** [blitz-js/blitz#1814]
### What is the problem?
1. about.tsx within "a b" folder was created in app/pages/. Visiting /a b/about does not work
2. unicode folder-name within app/pages is not working too
### Steps to Reproduce

```
output of `blitz --version --verbose`
```
macOS Mojave | darwin-x64 | Node: v15.2.1

blitz: 0.29.7 (global)
blitz: 0.29.7 (local)

**Comment by Zeko369** [comment]
This is a Next.js (which blitz is built upon) bug so no fixing on our side :disappointed:

**Comment by flybayer** [comment]
@ctrngk follow this issue for unicode: https://github.com/vercel/next.js/issues/15896

In a quick search I did not see an issue for a space in the url, so feel free to open an issue for that there :)
