### ISSUE TITLE
Api route async exports must be anonymous functions, but eslint complains

### ISSUE THREAD

**Issue by camsloanftc** [blitz-js/blitz#1819]
### What is the problem?
When creating an [external api route](https://blitzjs.com/docs/api-routes), it seems that you need to export the function in a  specific way (not sure if intentional or a bug):

```js
// This works
export default async (req, res) => {
  res.status(200).json({ data: "hello" })
}
```

```js
// This does not work
export default async function handler (req, res) {
  res.status(200).json({ data: "hello" })
}
```

```js
// This does not work either

async function handler () {
  res.status(200).json({ data: "hello" })
}

export default handler
```

Part of the problem is that blitz eslint config has an eslint rule that complains when you do the way that works:
`Assign arrow function to a variable before exporting as module default eslintimport/no-anonymous-default-export`

So you naturally refactor it and break things.

### Steps to Reproduce

1. Create an api route in `/app/api/custom-route.ts` using blitzt
2. Add the code from above as your handler
3. Call your api and you will get `API resolved without sending a response for /api/v1/tours/4, this may result in stalled requests.` in your server terminal logs when you try to export one of the last two ways.
4. Check your eslint rules

### Versions

```
debug: REDACTED
debug: cliPkgPath: REDACTED

macOS Catalina | darwin-x64 | Node: v14.15.0

blitz: 0.30.0-canary.2 (global)
blitz: 0.30.0-canary.2 (local)

  Package manager: yarn 
  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 4.81 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: ~2.15 => 2.15.0 
    @prisma/client: ~2.15 => 2.15.0 
    blitz: 0.30.0-canary.2 => 0.30.0-canary.2 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: 4.1.3 => 4.1.3 
```

### Other

Temp solution: For now, I am overriding this eslint rule to get around it:
```
module.exports = {
  extends: ["blitz"],
  overrides: [
    {
      files: ["**/api/**/*.ts"],
      rules: {
        "import/no-anonymous-default-export": "off",
      },
    },
  ],
}

```

Please include applicable logs and screenshots that show your problem.
![image](https://user-images.githubusercontent.com/16295659/106289797-b5468680-6217-11eb-9e2f-c867d4df0fc8.png)
![image](https://user-images.githubusercontent.com/16295659/106289833-bc6d9480-6217-11eb-8b9b-3267834d92e7.png)

**Comment by flybayer** [comment]
I just ran into this today too.

Issue is a bug in babel-plugin-superjson-next which is included in `blitz/babel` preset: https://github.com/blitz-js/babel-plugin-superjson-next/pull/37

Workaround is use `next/babel` or an older version of babel-plugin-superjson-next. But that fix should be published very soon

**Comment by camsloanftc** [comment]
Got it thanks! We can close this out.
