### ISSUE TITLE
Blitz start crashes if files with special permissions exist even if in .gitignore list

### ISSUE THREAD

**Issue by jnielson94** [blitz-js/blitz#1829]
### What is the problem?

When there are directories with special permissions in the root folder (might cause problems elsewhere but that's where mine was), `blitz start` crashes when trying to check that directory for `.gitignore` files.

### Steps to Reproduce

1. Create an empty folder, say `test-access`
1. Add a file inside that folder `touch test-access/test.ts`
1. Add to `.gitignore` as `test-access`
1. Remove all permissions to easily emulate a folder created by another user (like `root` or `postgres`): `chmod 000 test-access`
1. Run `blitz start` - ideally this step "works" but it crashes.

* These steps have been purposefully simplified. The actual scenario I ran into involves docker and WSL2, but I tested these steps on my mac and they caused the same issue.

### Versions

<details>
<summary>Blitz Versions</summary>

```
debug: blitzPkgPath: /home/j/underbelly/agency-metrics-v2/node_modules/blitz/dist/index.js
debug: cliPkgPath: /home/j/underbelly/agency-metrics-v2/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js 

Linux 5.4 | linux-x64 | Node: v14.15.3

blitz: 0.29.2 (local)

  Package manager: npm 
  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 20.53 GB / 24.91 GB
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.5.0 - ~/.nvm/versions/node/v14.15.3/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.14.0 => 2.14.0 
    @prisma/client: 2.14.0 => 2.14.0 
    blitz: 0.29.2 => 0.29.2 
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8 
    typescript: 4.0.5 => 4.0.5 
```

</details>

### Other

It seems like [this section of code checking directories for .gitignore files](https://github.com/blitz-js/blitz/blob/canary/packages/server/src/parse-chokidar-rules-from-gitignore.ts#L42-L44) is causing the crash. I tried using `suppressErrors: true` in there and made it farther but there was another spot where it crashed due to the special permissions.

<details>
<summary>Screenshot of running through the reproduction steps</summary>

![screenshot of running through the reproduction steps](https://user-images.githubusercontent.com/13559161/106330124-ee92ec80-623f-11eb-856c-5664d0301721.png)

</details>

**Comment by flybayer** [comment]
Thanks for the bug report!

**Comment by flybayer** [comment]
Putting in icebox because this should be fixed by this coming change: https://github.com/blitz-js/blitz/discussions/1990
