### ISSUE TITLE
Set-Cookie appears to be called twice if there is no anonymous session present.

### ISSUE THREAD

**Issue by camsloanftc** [blitz-js/blitz#1837]
### What is the problem?
I am attempting to set an auth cookie on a non-blitz app client, calling my blitz api login queries. 

It appears as though this triggers the blitz server to send back duplicates of each of the session cookies, and so the session that gets added to the database on session.$create never gets set on the client.

This means I cannot access protected routes because I am sending the wrong credentials to the server on each subsequent request.

### Steps to Reproduce

1. Create a blitz new app
2. Create a new account from you blitz server
3. Call the default signup function from another client in the browser, or a rest client like insomnia or postman
```json
// json body for rest call to http://localhost:3000/auth/mutations/signup
{
	"params": {
		"email": "email@whatever.com",
		"password": "yourpassword"
	},
	"meta": {}
}
```
4. Look at the response cookies. You will see 8 cookies being sent back to the client, 4 of which are duplicates. The images further below show this.
5. In insomnia, I have no problem making requests to protected routes after. It appears to accept the correct cookies, perhaps by chance. In chrome however (and I am assuming other browsers), the wrong set of cookies are set, and so subsequent requests to protected routes cannot be authorized. 

### Versions

```sh
# output of `blitz --version --verbose`

debug: blitzPkgPath: /Users/camsloan/Documents/development/hopscotch/hopscotch-monorepo/hopscotch-app/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/camsloan/Documents/development/hopscotch/hopscotch-monorepo/hopscotch-app/node_modules/@blitzjs/cli/lib/src/index.js 

macOS Catalina | darwin-x64 | Node: v14.15.0

blitz: 0.30.0-canary.2 (global)
blitz: 0.30.0-canary.4 (local)

  Package manager: yarn 
  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 2.73 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: ~2.15 => 2.15.0 
    @prisma/client: ~2.15 => 2.15.0 
    blitz: 0.30.0-canary.4 => 0.30.0-canary.4 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: 4.1.3 => 4.1.3 
```

### Other

Please include applicable logs and screenshots that show your problem.

This image shows the 8 cookies being returned by the server:
![image](https://user-images.githubusercontent.com/16295659/106400958-808d2780-63ef-11eb-865d-7fc1416b6390.png)

This image shows the response headers from the same request:
![image](https://user-images.githubusercontent.com/16295659/106401172-b5e64500-63f0-11eb-8e54-7813caab9fd9.png)

These are all local tokens so not too worried about sharing them.

**Comment by camsloanftc** [comment]
My current workaround is to make an initial all to a query endpoint called `get-anon-token` which just returns "ok" and sets the anonymous session cookie. Then immediately after, I can send another request including those cookies and the anti-csrf token. This works as intended and will only set the 4 cookies needed.

**Comment by JuanM04** [comment]
@camsloanftc I'm unable to replicate that with `v0.30.0-canary.13`. Can you confirm if it's still happening with this version?

**Comment by camsloanftc** [comment]
I will be updating to the latest canary this week at which point I can try again and report back!

**Comment by camsloanftc** [comment]
I am a bit late on the upgrade - but I just got back up to date with the latest version `"blitz": "0.32.1",` and I am still encountering this issue.

I noticed something just now in some testing. If I call `await ctx.session.$setPublicData({})` more than once in a request - each time will add another set of all the blitz cookies to the `set-cookie` header.

For demonstration purposes:
```typescript
    await ctx.session.$setPublicData({ seenTours: [] })
    await ctx.session.$setPublicData({ seenTours: [] })
    await ctx.session.$setPublicData({ seenTours: [] })
    await ctx.session.$setPublicData({ seenTours: [] })
    await ctx.session.$setPublicData({ seenTours: [] })
    await ctx.session.$setPublicData({ seenTours: [] })
    await ctx.session.$setPublicData({ seenTours: [] })
    await ctx.session.$setPublicData({ seenTours: [] })
```
This will result in returning 24 headers being set. I think that when setPublicData is being called here, it is not removing the previous `set-cookie` headers which ends up in them piling on top of one another instead of overriding the previous value of the same name.

![image](https://user-images.githubusercontent.com/16295659/110857421-d5da1580-8286-11eb-8ed3-66aff6381be7.png)

**Comment by flybayer** [comment]
@camsloanftc ah yes! Probably all we need is to first call our [`removeHeader`](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/server/auth/sessions.ts#L445) function inside our [`setHeader`](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/server/auth/sessions.ts#L438) function.
