### ISSUE TITLE
the discord invite link has expired

### ISSUE THREAD

**Issue by nyn0x** [blitz-js/blitz#1848]
### What is the problem?
Hi, the discord invite link has expired.

On slack and on https://blitzjs.com/

(https://discord.com/invite/epMSc7Mpvt)

**Comment by flybayer** [comment]
I am unable to reproduce. I created that invite link to never expire. So must have been a temporary fluke. Can you try again?

**Comment by nyn0x** [comment]
oh maybe, yeah it works now !
