### ISSUE TITLE
More robust authorization mechanism

### ISSUE THREAD

**Issue by lcswillems** [blitz-js/blitz#1858]
### What do you want and why?

I have a `Post` model and a `User` model. Each post has `authorId` field. I want to authorize a user to edit a post only if it is the author. How could I do with the current authorization mechanism? It seems to be only based on the `role` field.

**Comment by Skn0tt** [comment]
Hi @lcswillems! You can implement any authorization rules by throwing `AuthenticationError` when a user makes a request that he isn't authorized to.

**Comment by lcswillems** [comment]
Thank you for your answer!
