### ISSUE TITLE
Allow to embed a Blitz.js app

### ISSUE THREAD

**Issue by lcswillems** [blitz-js/blitz#1877]
### What do you want and why?

I have a Blitz.js website. However, I can't embed it in an iframe. I get a CRSF token error. How can I embed it?

**Comment by flybayer** [comment]
I've asked my security guy about this. Will report back!

**Comment by lcswillems** [comment]
Thank you!

**Comment by lcswillems** [comment]
Is there a way to temporary disable the CSRF verification?

**Comment by markhughes** [comment]
@lcswillems can you show us the error you get?

**Comment by lcswillems** [comment]
I get this:

![image](https://user-images.githubusercontent.com/5437552/107188862-ba11f400-69e8-11eb-9946-74dbc22754a2.png)

The CSRF token is not sent during the request.

**Comment by lcswillems** [comment]
I have activated the debugging mode and I get this:

```
[BLITZ] No antiCSRFToken cookie found
```

This is weird because the token is in the cookies.

**Comment by lcswillems** [comment]
The error is on my side! I embed the Blitz.js app in a Chrome Web Extension but cookies are not enabled. This is weird because I was sure that the equivalent Next.js version was working but I am surely wrong. Sorry for the inconvenience!
