### ISSUE TITLE
Tailwind Recipe fails with Blitz v 0.29.7

### ISSUE THREAD

**Issue by SigurdMW** [blitz-js/blitz#1879]
### What is the problem?
Getting error when trying to run `blitz install tailwind`: 

λ blitz install tailwind
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

    Error: Cannot find module 'module-alias'

### Steps to Reproduce

1. Run  `blitz install tailwind` with a newly installed Blitz@0.29.7 on Windows

### Versions

λ blitz --version --verbose
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: C:\git\kurs\dotjs-leaderboardd\node_modules\blitz\dist\index.js
debug: cliPkgPath: C:\git\kurs\dotjs-leaderboardd\node_modules\@blitzjs\cli\lib\src\index.js

Windows 10 | win32-x64 | Node: v12.20.1

blitz: 0.29.7 (global)
blitz: 0.29.7 (local)

  Package manager: yarn
  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 52.26 GB / 63.74 GB
  Binaries:
    Node: 12.20.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/cli: ~2.14 => 2.14.0
    @prisma/client: ~2.14 => 2.14.0
    blitz: 0.29.7 => 0.29.7
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    typescript: 4.1.3 => 4.1.3

### Other

Please include applicable logs and screenshots that show your problem.

**Comment by dkozickis** [comment]
Hi! 

I have same issue with Node 12/14, on OS X. 

```
╰─ blitz -v
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

macOS Mojave | darwin-x64 | Node: v12.18.4

blitz: 0.29.7 (global)
blitz: 0.29.7 (local)

  Package manager: yarn
  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 205.32 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.18.4 - ~/n/bin/node
    Yarn: 1.22.5 - ~/n/bin/yarn
    npm: 6.14.6 - ~/n/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/cli: ~2.14 => 2.14.0
    @prisma/client: ~2.14 => 2.14.0
    blitz: 0.29.7 => 0.29.7
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    typescript: 4.1.3 => 4.1.3
```

**Comment by merodiro** [comment]
I'm having this issue with all recipes and not just tailwind

**Comment by C-reddd** [comment]
Same issue for me as well.

macOS Big Sur | darwin-x64 | Node: v14.15.4

blitz: 0.29.7 (global)
blitz: 0.29.7 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.95 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: ~2.14 => 2.14.0 
    @prisma/client: ~2.14 => 2.14.0 
    blitz: 0.29.7 => 0.29.7 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: 4.1.3 => 4.1.3

**Comment by vkivia** [comment]
Same issue with: 0.30.0-canary.2

blitz: 0.30.0-canary.2 (global)
blitz: 0.30.0-canary.2 (local)

**Comment by flybayer** [comment]
Sorry about that folks!

This is an easy fix. Need to add `module-alias` as a dependency to the config package here: https://github.com/blitz-js/blitz/blob/canary/packages/config/package.json

One of you want to make a PR for that? (use an exact version number `2.2.2`)

**Comment by alii** [comment]
Can do! 👍
