### ISSUE TITLE
Set up Windows CI test runner

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#188]
**What do you want and why do you want it?.**
Most of us are on macOS or Linux and easily break things from running on Windows.

We need a CI windows test runnner to ensure we always run good on Windows too.

**Possible implementation(s)**

We are currently using Github actions. I'm not sure if this supports windows? We can add another CI service for windows if needed.

**Comment by wKovacs64** [comment]
We need to get this going ASAP, I can't keep up with all the Windows issues, haha! 😅 

Most projects I've seen targeting Windows in CI use AppVeyor, but it appears [GitHub Actions supports Windows Server 2019](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#github-hosted-runners). I'll try to mess around with this tomorrow.

**Comment by flybayer** [comment]
Awesome, let me know if you need any help from me! Slack DM or a direct tag here in GH are the best ways to get my attention
