### ISSUE TITLE
0.30.0-canary.6 - Reset password doesn't submit form and throws an error

### ISSUE THREAD

**Issue by Slein2012** [blitz-js/blitz#1884]
### What is the problem?
If a password reset link is requested via forget-password everything works fine, but when opening the link to reset-password?token=... it is not possible to submit the form. There is no error message in the browser's console or in the executing terminal. When commenting the form's schema with //schema={ResetPassword} , the form submits, but throws the error: 
ERROR resetPassword() 
 Error  1 validation issue(s)

  Issue #0: invalid_type at token
  Required

### Steps to Reproduce

1. blitz new app
2. run blitz, create an account and logout
3. go to forget-password and insert email, then click on the generated reset-password link
4. insert new password and confirm password, submit -> nothing happens
5. comment schema={ResetPassword} in app\auth\pages\reset-password.tsx -> submitting works, but throws error invalid_type at token

### Versions

debug: blitzPkgPath: *\node_modules\blitz\dist\index.js
debug: cliPkgPath: *\node_modules\blitz\node_modules\@blitzjs\cli\lib\src\index.js 

Windows 10 | win32-x64 | Node: v14.15.0

blitz: 0.30.0-canary.6 (local)

  Package manager: npm
  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
    Memory: 470.78 MB / 7.95 GB
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.16 => 2.16.0
    blitz: 0.30.0-canary.6 => 0.30.0-canary.6
    prisma: ~2.16 => 2.16.0
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    typescript: 4.1.3 => 4.1.3

### Other

Error message from step five:
```
INFO resetPassword() Starting with input: 
{
  password: '[***]',
  passwordConfirmation: '[***]'
}
20:45:47.879 ERROR resetPassword() 
 Error  1 validation issue(s)

  Issue #0: invalid_type at token
  Required

details:
{
  errors: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [
        'token'
      ],
      message: 'Required'
    }
  ],
  addError: [Function (anonymous)],
  addErrors: [Function (anonymous)],
  flatten: [Function (anonymous)]
}
error stack:
• ZodError.ts:124 ZodError
    node_modules\zod\src\ZodError.ts:124:5

• parser.ts:170 <anonymous>
    node_modules\zod\src\parser.ts:170:17

• resolver.ts:297 <anonymous>
    node_modules\@blitzjs\core\src\resolver.ts:297:42

• resolver.ts:264 _callee$
    node_modules\@blitzjs\core\src\resolver.ts:264:26

• runtime.js:63 tryCatch
    node_modules\node_modules\regenerator-runtime\runtime.js:63:40

• runtime.js:293 invoke
    node_modules\node_modules\regenerator-runtime\runtime.js:293:22

• runtime.js:118 <anonymous>
    node_modules\node_modules\regenerator-runtime\runtime.js:118:21

• core.cjs.development.js:39 asyncGeneratorStep
    node_modules\@blitzjs\core\dist\core.cjs.development.js:39:24

• core.cjs.development.js:61 _next
    node_modules\@blitzjs\core\dist\core.cjs.development.js:61:9

• core.cjs.development.js:68 <anonymous>
    node_modules\@blitzjs\core\dist\core.cjs.development.js:68:7

• core.cjs.development.js:57 <anonymous>
    node_modules\@blitzjs\core\dist\core.cjs.development.js:57:12

• resolver.ts:261 <anonymous>
    node_modules\@blitzjs\core\src\resolver.ts:261:3

• rpc.ts:45 _callee$
    node_modules\@blitzjs\server\src\rpc.ts:45:30

• runtime.js:63 tryCatch

• runtime.js:293 invoke
    node_modules\node_modules\regenerator-runtime\runtime.js:293:22
```

**Comment by flybayer** [comment]
@Slein2012 I'm unable to reproduce. Can you provide a repo or codesandbox with your issue?

![image](https://user-images.githubusercontent.com/8813276/107291056-8e692b00-6a35-11eb-9641-36bbddaee34e.png)

**Comment by Slein2012** [comment]
I have set up a repository. I hope this helps, because I don't know exactly what information I can use to help. https://github.com/Slein2012/blitzjs-bug

**Comment by Slein2012** [comment]
I have to add that I have been using React Hook Form. I just installed blitz with React Final Form and the password reset works fine.

**Comment by sleventyeight** [comment]
I had this same issue.  Not sure if it's related only to React Hook Form but the token parameter is not being passed to the schema resolver and the error message isn't displaying.   I'm sure there's a better way but I added a hidden input field so I could register the field with RHF.

`<HiddenInputField name="token" />`

**Comment by flybayer** [comment]
I've fixed this in https://github.com/blitz-js/blitz/pull/1902. Check that out to see the proper fix.

**Comment by Slein2012** [comment]
Thank you, it works as it should, with the small change I suggested.
