### ISSUE TITLE
Wrong `useSession` return type

### ISSUE THREAD

**Issue by lcswillems** [blitz-js/blitz#1891]
### What is the problem?

In the following code, `session.userId` has the type `number`. However, in `session.userId` can also be undefined if the user is not authenticated.

```ts
const session = useSession();
session.userId // has type number
```

Here the type should be `number | undefined`.

**Comment by flybayer** [comment]
Good catch!

This is an easy fix. [This type](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/supertokens.ts#L60-L62) needs updated to look like this:

```ts
export interface PublicDataWithLoading extends PublicData {
  userId: PublicData["userId"] | null
  isLoading: boolean
}
```

**Comment by rodrigoehlers** [comment]
I‘d like to fix this tomorrow, if that‘s fine.
