### ISSUE TITLE
Do newly created apps still need to import React?

### ISSUE THREAD

**Issue by emgoto** [blitz-js/blitz#1921]
### What do you want and why?
I know from React 17 you [no longer need](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#whats-different-in-the-new-transform) the `import React from 'react';` line.

If I remove that line from `app/auth/components/SubmissionForm.tsx` it seems like it still renders as well.

### Possible implementation(s)

Remove all instances of `import React from 'react';` from the blitz start template.

**Comment by flybayer** [comment]
Thanks @emgoto, I think this is resolved in the lastest canary release: https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/form/__ModelName__Form.tsx
