### ISSUE TITLE
Canary 13 breaks running blitz dev from a new blitz app or after upgrading from canary 12

### ISSUE THREAD

**Issue by Lani** [blitz-js/blitz#1936]
### What is the problem?
Updating  from canary 12 to 13 and running `npm run dev` gives the following error.
```bash
[Error: ENOENT: no such file or directory, open '/home/user/code/b-canary-2/.blitz/build/_manifest.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/user/code/b-canary-2/.blitz/build/_manifest.json'
}
npm ERR! code 1
npm ERR! path /home/user/code/b-canary-2
npm ERR! command failed
npm ERR! command sh -c blitz dev

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-02-14T20_08_44_741Z-debug.log
```

I tried deleting `.blitz` and `node_modules` and `package-lock.json` and running `npm i' again, but it didn't help.

Then I first ran `npm run build` and `npm run start`, after that `npm run dev` printed out the whole `_manifest.json` in the console and it started working again.

I just tested and the same error occurs if you do a `blitz new my-app` and then try to run `blitz dev`.

### Steps to Reproduce

1. `npm i -g blitz@canary`
2. `blitz new my-app`
3. `cd my-app`
4. `blitz dev`

### Versions

```
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: /home/user/code/b-canary-2/node_modules/blitz/dist/index.js
debug: cliPkgPath: /home/user/code/b-canary-2/node_modules/@blitzjs/cli/lib/src/index.js 

Linux 5.8 | linux-x64 | Node: v15.8.0

blitz: 0.30.0-canary.13 (global)
blitz: 0.30.0-canary.13 (local)

  Package manager: npm 
  System:
    OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 839.02 MB / 7.46 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 15.8.0 - ~/.nvm/versions/node/v15.8.0/bin/node
    Yarn: Not Found
    npm: 7.5.1 - ~/.nvm/versions/node/v15.8.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.16 => 2.16.1 
    blitz: 0.30.0-canary.13 => 0.30.0-canary.13 
    prisma: ~2.16 => 2.16.1 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: 4.1.5 => 4.1.5 
```

#### Workaround
Run `blitz build` before running `blitz dev`.

**Comment by AndriusBartulis** [comment]
This happened to me too. I got around the issue by first running blitz build and then blitz dev worked.

**Comment by malkomalko** [comment]
Just doing some initial triage here and this code looks like it should be creating a manifest if it doesn't exist https://github.com/blitz-js/blitz/pull/1933/files#diff-7ecf655de14f9da25f6bcda0675376fb3e199e607395955d69828a664aefb39aR83-R87 so this feels like a high priority bug.
