### ISSUE TITLE
A way to plug/hook in somewhere with createStagePages

### ISSUE THREAD

**Issue by markhughes** [blitz-js/blitz#1937]
### What do you want and why?

A way to plug/hook in somewhere with `createStagePages` in the `server` package, to modify the source as it goes out to NextJS.

### Possible implementation(s)

**blitz.config.js**
```
const { MyCoolHook } = require('./my-cool-hook');

module.exports = {
  ...
  
  createStageHooks: {
    pages: [ MyCoolHook ]
  }
  
  ...
}
```

**my-cool-hook.ts**
```
const myCoolHook = ({ filename, filepath, filedestination, src }) => {
  if (filePath.indexOf('/app/sample-thing/') != -1) {
    src = ... // Do some cool sample modifications with jscodeshift
  }
  
  // Make changes to the build/copy process in next.js based on return values (filename, flepath, src)
  return { filename, filepath, src };
}

export default myCoolHook

```

Inside of my example, we could add additional actions to the create stages in the server package. 

### Additional context

References from my research I used:

- https://github.com/blitz-js/blitz/blob/canary/packages/server/src/build.ts 
- https://github.com/blitz-js/blitz/blob/canary/packages/file-pipeline/src/transform.ts

**If you can point me in the right direction I can help build this too.** I believe this sort of feature would be ground-breaking and allow incredible development opportunities for third party integrations!

**Comment by MrLeebo** [comment]
Couldn't you accomplish this in a more flexible manner by making my-cool-hook.ts a babel plugin?

**Comment by markhughes** [comment]
@MrLeebo I've tried this but it only seemed to process _after_ it was thrown into Next, so I had no path information from my next project.

**Comment by flybayer** [comment]
I think this is a good idea!

**Comment by flybayer** [comment]
Update: we're getting rid of our custom compiler: https://github.com/blitz-js/blitz/discussions/1990

**Comment by markhughes** [comment]
@flybayer can you give an example, please? I cannot see how to run a babel transformation before blitz.

**Comment by flybayer** [comment]
@markhughes what change do you want to make? The more specific code you can give, the better I can help

**Comment by markhughes** [comment]
@flybayer apologies I wrote out an example but for some reason I didn't post it.. not sure what happened there.

I'm working on a feature flag handler. Essentially, I want to be able to enable and disable large portions of the application based on a `features` folder.

For example, this is the "download-page" feature I've built, the features folder lives in the `app` directory:

```
...
features/download-page/index.ts
features/download-page/models/...
features/download-page/components/...
features/download-page/pages/download/index.tsx
features/download-page/pages/download/help.tsx
features/download-page/mutations/setDownload.tsx
features/download-page/queries/getDownload.tsx
...
```

The index.ts file contains a callback function to determine if the feature is enabled. 

So now, I want to run a babel transformation that will add middleware to the queries, mutations, and pages to call back to the index.ts.

I'm fairly confident in writing for babel, but I've tried already and the transformations happen after blitz has done its own transformations.. meaning I've lost my directory structure.

**Comment by flybayer** [comment]
@markhughes ok got it. So after we fork next.js, that directory structure will stay the same (it won't be moved in the build like it is now). I think then babel will work for you?

**Comment by markhughes** [comment]
@flybayer sure. But there is no current solution, right? I assume the process of forking and getting up a stable build of it up will take some time.

**Comment by flybayer** [comment]
@markhughes yes. I'm thinking a few weeks. If you want to add a stage hook in the meantime, we can do that.

**Comment by flybayer** [comment]
You could probably also get along with https://github.com/ds300/patch-package without any changes to blitz core
