### ISSUE TITLE
 EPERM: operation not permitted,  on   /.next

### ISSUE THREAD

**Issue by Extra-Extra-Dev** [blitz-js/blitz#1943]
### What is the problem?
Getting an EPERM error on the .next folder AFTER/at-the-end-of build process. 

Could be causing problems downstream/during other/subsequent builds.

Was in chat with FlyBayer who asked to document.

EDIT/ADDING to ticket:
1) first run .next directory not made
2) second run .next directory is made

### Steps to Reproduce

1. npx blitz build

### Versions

debug: blitzPkgPath: C:\clients\XXXX\Canary13Test\node_modules\blitz\dist\index.js
debug: cliPkgPath: C:\clients\XXXX\Canary13Test\node_modules\@blitzjs\cli\lib\src\index.js

Windows 10 | win32-x64 | Node: v14.15.4

blitz: 0.30.0-canary.13 (local)

  Package manager: yarn
  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Memory: 3.04 GB / 15.65 GB
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.16 => 2.16.1
    blitz: 0.30.0-canary.13 => 0.30.0-canary.13
    prisma: ~2.16 => 2.16.1
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    typescript: 4.1.5 => 4.1.5

### Other

npx blitz build
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

√ Compiled
Loaded env from C:\clients\XXXX\Canary13Test\.env
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

info  - Creating an optimized production build...
info  - Using external babel configuration from C:\clients\XXXX\Canary13Test\babel.config.js
info  - Compiled successfully
info  - Collecting page data...
info  - Generating static pages (0/10)
info  - Generating static pages (2/10)
info  - Generating static pages (4/10)
info  - Generating static pages (7/10)
info  - Generating static pages (10/10)
info  - Finalizing page optimization...

Page                                                           Size     First Load JS
┌ ○ /                                                          4.92 kB         135 kB
├   /_app                                                      0 B             130 kB
├ ○ /404                                                       2.39 kB         133 kB
├ λ /api/auth/mutations/changePassword                         0 B             130 kB
├ λ /api/auth/mutations/forgotPassword                         0 B             130 kB
├ λ /api/auth/mutations/login                                  0 B             130 kB
├ λ /api/auth/mutations/logout                                 0 B             130 kB
├ λ /api/auth/mutations/resetPassword                          0 B             130 kB
├ λ /api/auth/mutations/signup                                 0 B             130 kB
├ λ /api/projects/mutations/createProject                      0 B             130 kB
├ λ /api/projects/mutations/deleteProject                      0 B             130 kB
├ λ /api/projects/mutations/updateProject                      0 B             130 kB
├ λ /api/projects/queries/getProject                           0 B             130 kB
├ λ /api/projects/queries/getProjects                          0 B             130 kB
├ λ /api/users/queries/getCurrentUser                          0 B             130 kB
├ ○ /forgot-password                                           3.07 kB         133 kB
├ ○ /login                                                     3.27 kB         133 kB
├ ○ /projects                                                  3.33 kB         133 kB
├ ○ /projects/[projectId]                                      3.61 kB         134 kB
├ ○ /projects/[projectId]/edit                                 3.4 kB          134 kB
├ ○ /projects/new                                              2.99 kB         133 kB
├ ○ /reset-password                                            3.29 kB         133 kB
└ ○ /signup                                                    3.14 kB         133 kB
+ First Load JS shared by all                                  130 kB
  ├ chunks/640352f8857dc4da04af8907d78aa1c5bbcd3496.1fb517.js  42.2 kB
  ├ chunks/905cd02448c073ade164c352eb36416db51f4e09.e88f1e.js  9.8 kB
  ├ chunks/commons.3352e0.js                                   15.6 kB
  ├ chunks/e737505ec2628cd4b92a3310a06440ed60fb096b.cb68fa.js  8.69 kB
  ├ chunks/framework.9a4971.js                                 45.1 kB
  ├ chunks/main.abe7b4.js                                      6 kB
  ├ chunks/pages/_app.8b0294.js                                2.03 kB
  └ chunks/webpack.245f04.js                                   751 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

[Error: EPERM: operation not permitted, stat 'C:\clients\XXXX\Canary13Test\.next'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'stat',
  path: 'C:\\clients\\XXXX\\Canary13Test\\.next'
}

**Comment by Extra-Extra-Dev** [comment]
EDIT/ADDING:
1) first run .next directory not made
2) second run .next directory is made

**Comment by Extra-Extra-Dev** [comment]
new experiences today on Canary@14:

NPX BLITZ BUILD:

... files inside the file structure seemed locked..(sorry I didn't note it, files regarding one of my pages) gave a warning... couldn't build. .. multiple tries.

Closed VS Code

Tried BUILD again : FAILED with this error.
Tried BUILD again with SUCCESS immediately after.
  
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

[Error: EPERM: operation not permitted, unlink 'C:\clients\XXXXX\.blitz\build\.next'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\clients\\XXXXX\\.blitz\\build\\.next'
}

**Comment by Extra-Extra-Dev** [comment]
(Canary 14)   
Here's another sequence captured.  1 .2 3. attempts to build. the 4rd makes it  then ends on an error.  Not the first time i've seen "stuckness" on "integrations" and "auth" folders sequence.  


PS C:\clients\XXXXXX> npx blitz build
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

  errno: -4048,
  code: 'EPERM',
  syscall: 'lstat',
  path: 'C:\\clients\\XXXXXX\\.blitz\\build\\integrations'
}
PS C:\clients\XXXXXX> npx blitz build
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

[Error: EPERM: operation not permitted, unlink 'C:\clients\XXXXXX\.blitz\build\app\auth'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\clients\\XXXXXX\\.blitz\\build\\app\\auth'
}
PS C:\clients\XXXXXX> npx blitz build
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

[Error: EPERM: operation not permitted, unlink 'C:\clients\XXXXXX\.blitz\build\db'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\clients\\XXXXXX\\.blitz\\build\\db'



Then 4th attempt BUILDS and ends with:

[Error: EPERM: operation not permitted, stat 'C:\clients\Choop\XXXXXX\.next'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'stat',
  path: 'C:\\clients\\XXXXXX\\.next'
}


5 command.. completely goes through the process with no error.

**Comment by flybayer** [comment]
Going to close because it should be fixed.

And if not fixed now, it will be fixed by  https://github.com/blitz-js/blitz/discussions/1990
