### ISSUE TITLE
Issues running blitz dev or blitz start on Windows

### ISSUE THREAD

**Issue by Roesh** [blitz-js/blitz#1944]
### What is the problem?
On Windows, there are issues related to file permissions (file deletion, file unlinking etc.) that cause the blitz dev or blitz start command to crash.

Here is one scenario that I have encountered:
On Windows, after the prisma schema is update, and a migration is applied, trying to run blitz start or blitz dev produces the following error:

```
[Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Roshan\Documents\DeleteMe\windowsPerms\.next\static\chunks'] {
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\Roshan\\Documents\\DeleteMe\\windowsPerms\\.blitz\\build\\.next\\static\\chunks'
}
```

### Steps to Reproduce

1. On Windows, create a new Blitz app using `blitz new <appname>`, then navigate to the created <appname> directory 
2. If on 0.30.0-canary.13, run `blitz build` to create the .blitz folder
3. Update the schema.prisma file with a new data model
4. Run `blitz prisma migrate dev --preview-feature`
5. Run `blitz dev` or `blitz start`
6. You should see the command fail, with the above error message

### Versions

```
debug: blitzPkgPath: C:\Users\Roshan\Documents\DeleteMe\windowsPerms\node_modules\blitz\dist\index.js
debug: cliPkgPath: C:\Users\Roshan\Documents\DeleteMe\windowsPerms\node_modules\blitz\node_modules\@blitzjs\cli\lib\src\index.js 

Windows 10 | win32-x64 | Node: v15.8.0

blitz: 0.30.0-canary.13 (global)
blitz: 0.30.0-canary.13 (local) 

  Package manager: npm
  System:
    OS: Windows 10 10.0.18363
    CPU: (16) x64 AMD Ryzen 7 2700 Eight-Core Processor
    Memory: 11.16 GB / 15.93 GB
  Binaries:
    Node: 15.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 7.5.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.16 => 2.16.1
    blitz: 0.30.0-canary.13 => 0.30.0-canary.13
    prisma: ~2.16 => 2.16.1
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    typescript: 4.1.5 => 4.1.5
```

**Comment by flybayer** [comment]
Thanks!

Related: https://github.com/blitz-js/blitz/issues/1836

**Comment by flybayer** [comment]
Hey, please update to https://github.com/blitz-js/blitz/releases/tag/v0.30.1 and see if this is fixed or not there :)

**Comment by Roesh** [comment]
Nice!

Ok, replicated on the machine this was initially occurring on, and I didn't get the issue. 

Used my windows laptop as well for good measure and I don't get the issue there either with 0.30.1

However, based on previous experience, these issues seem to go away for like one day but recur a day or two later, so I'm going to try reproducing again tomorrow and Sunday to be 100% sure before marking this as fixed. 

I'm kinda liking the Linux experience though, so I might personally hop on there for good because of this issue haha, so it's not all bad

**Comment by Roesh** [comment]
Day 2, no issues on both computers when I do the steps manually (Edit schema.prisma, run migrate commands)

However, I did try and test running example scaffold command, blitz generate all project name:string, and that throws an error :(

√ Run 'prisma migrate dev' to update your database? (Y/n) · true
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn prisma ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn prisma',
  path: 'prisma',
  spawnargs: [ 'migrate', 'dev', '--preview-feature' ]
}

Switched to my desktop and I get the same error there as well.

Would you like me to open a separate issue for the above? I'd like to do one more test for this same issue tomorrow before closing, but I can keep open if you'd like to use it for this spawn prisma ENOENT issue

**Comment by birksy89** [comment]
I think I'm running into a similar issue.

![image](https://user-images.githubusercontent.com/4971630/108602418-b774ae80-7399-11eb-839e-c32aff4e771e.png)

```
Windows 10 | win32-x64 | Node: v14.15.4

blitz: 0.30.1 (global)
blitz: 0.30.1 (local) 

  Package manager: yarn
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    Memory: 6.78 GB / 15.95 GB
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - ~\AppData\Roaming\npm\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.17 => 2.17.0
    blitz: 0.30.1 => 0.30.1
    prisma: ~2.17 => 2.17.0
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0     
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: 4.1.5 => 4.1.5
```

I'm also surprised that it says `Package manager: yarn`, as I use NPM.

**Comment by flybayer** [comment]
That error on `blitz generate` is a separate error and fixed here: https://github.com/blitz-js/blitz/pull/1979

**Comment by Roesh** [comment]
Nice! OK, tested again and didn't get this specific error on both pcs, I'll close this issue now.
