### ISSUE TITLE
TypeScript does not identify invalid CSS/SCSS module paths

### ISSUE THREAD

**Issue by remjx** [blitz-js/blitz#1947]
### What do you want and why?

This PR https://github.com/blitz-js/blitz/pull/1929 declares `*.module.css` files as valid for import. This means it is possible to `import styles from some-file-that-doesnt-exist.module.css` and TypeScript compiles without any error.

Is there any way it can check that the file actually exists?

### Possible implementation(s)

Unknown

### Additional context

N/A

**Comment by flybayer** [comment]
@remjx I'm not aware of any way to do that via TS, but if the file is missing the build will fail.
