### ISSUE TITLE
Login form keeps showing up even if already authenticated

### ISSUE THREAD

**Issue by davidroulier** [blitz-js/blitz#1948]
### What is the problem?

Authenticated page is constantly asking me to reauthenticate when trying to access a protected page, even if I'm already authenticated.

### Steps to Reproduce

1. Created a blitz app with blitz@canary14
2. Generated a "todo" model with `blitz generate all todo`
3. Try to access to `http://localhost:3000/todos/new`
4. Login form shows up
5. Authenticate successfully with correct credentials
6. Pages reload and shows login form again

### Versions

```
output of `blitz --version --verbose`
macOS Big Sur | darwin-x64 | Node: v14.15.4

blitz: 0.30.0-canary.8 (global)
blitz: 0.30.0-canary.14 (local)

  Package manager: yarn
  System:
    OS: macOS 11.2.1
    CPU: (8) x64 Apple M1
    Memory: 17.52 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.5.0 - /opt/homebrew/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.16 => 2.16.1
    blitz: 0.30.0-canary.14 => 0.30.0-canary.14
    prisma: ~2.16 => 2.16.1
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    typescript: 4.1.5 => 4.1.5
```

### Other

Please include applicable logs and screenshots that show your problem.

Here is the error output in my JavaScript console

```
core.esm.js?e252:173 Uncaught AuthenticationError: You must be logged in to access this
react_devtools_backend.js:2430 The above error occurred in the <BlitzInnerRoot> component:

    at BlitzInnerRoot (webpack-internal:///../../node_modules/@blitzjs/core/dist/core.esm.js:830:5)
    at Layout (webpack-internal:///./app/core/layouts/Layout.tsx:14:20)
    at ErrorBoundary (webpack-internal:///../../node_modules/react-error-boundary/dist/react-error-boundary.umd.js:40:37)
    at App (webpack-internal:///./pages/_app.tsx:28:25)
    at BlitzOuterRoot (webpack-internal:///../../node_modules/@blitzjs/core/dist/core.esm.js:855:34)
    at ErrorBoundary (webpack-internal:///../../node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:23:47)
    at ReactDevOverlay (webpack-internal:///../../node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:73:23)
    at Container (webpack-internal:///../../node_modules/next/dist/client/index.js:149:5)
    at AppContainer (webpack-internal:///../../node_modules/next/dist/client/index.js:632:24)
    at Root (webpack-internal:///../../node_modules/next/dist/client/index.js:763:24)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

**Comment by flybayer** [comment]
@davidroulier actually I'm not able to reproduce 🤔 

Can you provide more detailed reproduction instructions?

**Comment by davidroulier** [comment]
> @davidroulier actually I'm not able to reproduce 🤔
> 
> Can you provide more detailed reproduction instructions?

I gave it a new try this morning with fresh blitz install and the same issue keeps happening.

I did exactly what I explained on "Steps to reproduce". 

So yeah, I don't know how to be more specific :(

**Comment by davidroulier** [comment]
Just to be extra sure, I made a fresh install of blitz (non canary), and everything is working fine.

I was afraid to do something wrong when using Blitz, but...since it's working, there might be definitely an issue with the latest canary version.

```
macOS Big Sur | darwin-x64 | Node: v14.15.4

blitz: 0.29.7 (global)
blitz: 0.29.7 (local)

  Package manager: yarn
  System:
    OS: macOS 11.2.1
    CPU: (8) x64 Apple M1
    Memory: 37.13 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.5.0 - /opt/homebrew/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: ~2.14 => 2.14.0
    @prisma/client: ~2.14 => 2.14.0
    blitz: 0.29.7 => 0.29.7
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    typescript: 4.1.5 => 4.1.5
```

**Comment by flybayer** [comment]
@davidroulier where in the reproduction steps do you sign up (and also log out so that you can log back in)?

**Comment by flybayer** [comment]
@davidroulier can you record a [loom video](https://www.loom.com/) showing exactly what you are doing?

**Comment by davidroulier** [comment]
I don't know what I did yesterday....

It's working now.

I'm so sorry for wasting your time :( 

Maybe I had two installations of blitz cli (canary and non canary), or I have changed "postgres" to "postgresql" (just like it's recommended it prisma documentation). I don't know, but it's working now.
