### ISSUE TITLE
'blitz routes' breaks a project - Error: Cannot find module '[APP_FOLDER_PATH]/.next/server/pages-manifest.json'

### ISSUE THREAD

**Issue by thropx** [blitz-js/blitz#1955]
### What is the problem?

'blitz routes' breaks a project, and it starts throwing Error: Cannot find module '[APP_FOLDER_PATH]/.next/server/pages-manifest.json' error

### Steps to Reproduce

1. **blitz new testApp**
2. **cd testApp**
3. **blitz dev**
4. Go to localhost:3000 and see the default page load
5. **Ctrl-C** to terminate "blitz dev"
6. **blitz routes**
7. Verify that the routes are displayed
8. **blitz dev**
9. Go to localhost:3000

RESULT: Internal Server Error

Console: 
Error: Cannot find module '[APP_FOLDER_PATH]/.next/server/pages-manifest.json'

### Versions

```
$ blitz --version --verbose
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: [APP_FOLDER_PATH]/node_modules/blitz/dist/index.js
debug: cliPkgPath: [APP_FOLDER_PATH]/node_modules/@blitzjs/cli/lib/src/index.js 

macOS Mojave | darwin-x64 | Node: v14.15.0

blitz: 0.30.0 (global)
blitz: 0.30.0 (local)

  Package manager: yarn 
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 331.96 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 14.15.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/client: ~2.17 => 2.17.0 
    blitz: 0.30.0 => 0.30.0 
    prisma: ~2.17 => 2.17.0 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: 4.1.5 => 4.1.5
```

**Comment by MrLeebo** [comment]
I was able to repro this. As a workaround, running `blitz build` resolves the error.

Shortened repro steps:

```bash
blitz new repro
cd repro
blitz dev
# cmd+t to open a new terminal tab
open http://localhost:3000/
blitz routes # refresh browser to get the error
```

**Comment by thropx** [comment]
Yes, `blitz build` resolves the error, but calling `blitz routes` again, breaks it again,  with what looks like a different error..
