### ISSUE TITLE
Security improvement: Bind to 127.0.0.1 host instead of 0.0.0.0

### ISSUE THREAD

**Issue by Immortalin** [blitz-js/blitz#1956]
### What is the problem?
Blitz binds to 0.0.0.0 during development mode instead of 127.0.0.1 for localhost. The former exposes the app to the public/external network which may be undesirable for security.
### Steps to Reproduce

`blitz dev`
```
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
```
### Versions

```
blitz: 0.30.0 on WSL2
```

**Comment by MrLeebo** [comment]
Good suggestion. This issue comes from [nextjs](https://github.com/vercel/next.js/issues/20137) but probably won't change soon because it is potentially a breaking change for existing devs. Since we're in beta we can change the default with much less potential for backlash.

**Comment by FDiskas** [comment]
Also if you expose just 127.0.0.1 - this will not work on dockerized dev environment

**Comment by flybayer** [comment]
Can we detect if in a docker environment and default to 127.0.0.1 if in docker?
