### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by nainardev** [blitz-js/blitz#196]
have a CHANGELOG.md or write important chnages in [GitHub Releases](https://github.com/blitz-js/blitz/releases)

Its difficult to know whats changed between releases

**Comment by flybayer** [comment]
Yes, totally! I'll have GH releases set up for the alpha launch on Friday. At the moment, I'm posting changes in [our slack](https://slack.blitzjs.com)

**Comment by flybayer** [comment]
Github releases now set up!

**Comment by nainardev** [comment]
Thanks, waiting for documentation. Bye 👋
