### ISSUE TITLE
Getting type error while building the app

### ISSUE THREAD

**Issue by karthikeyan676** [blitz-js/blitz#1961]
### What is the problem?
I'm getting the type error while building the application. 

### Steps to Reproduce
Just install the new project with the help of CLI and build the project with `blitz build`

### Versions

```
 blitz --version --verbose
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: /Users/karthik/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/karthik/node_modules/@blitzjs/cli/lib/src/index.js

macOS Big Sur | darwin-x64 | Node: v14.15.4

blitz: 0.30.0 (global)
blitz: 0.29.7 (local)

  Package manager: npm
  System:
    OS: macOS 11.1
    CPU: (8) x64 Apple M1
    Memory: 36.00 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```

Please include applicable logs and screenshots that show your problem.

![image](https://user-images.githubusercontent.com/24937683/108404257-a74bba80-7245-11eb-915e-ce4af5202c3d.png)

**Comment by karthikeyan676** [comment]
I guess it's because of the blitz local version. If someone tells how to remove the local cache would be great.

**Comment by Roesh** [comment]
I am unsure of the best method to upgrade the Blitz version, so I'll defer to anyone who can help with that.

You'll still need to update the session.create function call and any others to the new syntax, session.create is now session.$create:
[https://github.com/blitz-js/blitz/issues/1919](url)

**Comment by flybayer** [comment]
@karthikeyan676 that's a bit odd. Your local version is `0.29.7` which uses `session.create` so you shouldn't get that type error.

Does it still error if you run `npx blitz build`?

**Comment by karthikeyan676** [comment]
I found the problem. It's because earlier I had a dummy package JSON with `0.29.7`th version and whenever I try to install blitz it was using the local node_modules blitz instead of the global. Now I deleted that package JSON with node_modules. Now it's working perfectly. Thanks, @Roesh and @flybayer. I'm closing this issue now.
