### ISSUE TITLE
Need to refactor blitz new replaceDependencies: possibility for race condition failure

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#197]
**What do you want and why do you want it?.**
We are using Promise.all() in `packages/cli/src/generators/app.ts` to replace dependencies and each dependency update function is writing the updates to the package.json on disk.

This is a problem because the file writes could be overwritten for each other.

The replaceDependencies functions should return an object and then everything should be written to package.json at one time.

```ts
    await Promise.all([
      replaceDependencies(pkg, this.destinationPath(), pkgDependencies, 'dependencies'),
      replaceDependencies(pkg, this.destinationPath(), pkgDevDependencies, 'devDependencies'),
      replaceBlitzDependency(pkg, this.destinationPath(), this.options.version),
    ])
```

**Comment by Zeko369** [comment]
I'll handle this
