### ISSUE TITLE
Change session cookie prefix to have an explict config instead of using package.json `name` field

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1972]
### What do you want and why?

Currently we are using the name field of your `package.json` for setting the session cookie prefix. [As @lcswillems highlighted](https://github.com/blitz-js/blitz/issues/1957#issuecomment-781992049), this isn't ideal.

So we should change this to be an explicit config:

```diff
module.exports = {
  middleware: [
    sessionMiddleware({
+      cookiePrefix: "myApp",
      isAuthorized: simpleRolesIsAuthorized,
    }),
  ],
}
```

And we'll add that to templates for new apps.

### Possible implementation(s)

1. Update config type: https://github.com/blitz-js/blitz/blob/canary/packages/core/src/supertokens.ts#L21
2. Change `sessionMiddleware` implementation to return `name` and `config` static properties on the function, something like this:

```ts
export const sessionMiddleware = (sessionConfig: Partial<SessionConfig> = {}): Middleware => {
  assert(
    sessionConfig.isAuthorized,
    "You must provide an authorization implementation to sessionMiddleware as isAuthorized(userRoles, input)",
  )
  config = {
    ...defaultConfig,
    ...sessionConfig,
  } as Required<SessionConfig>

  const middleware = async (req, res, next) => {
    if (req.method !== "HEAD" && !res.blitzCtx.session) {
      // This function also saves session to res.blitzCtx
      await getSessionContext(req, res)
    }
    return next()
  }
  middleware.name = 'blitzSessionMiddleware'
  middleware.config = {
    cookiePrefix:
  }
  return middleware
}
```
3. Change the blitz runtime data function to read `config.middleware`, find middleware with `name = 'blitzSessionMiddleware'` and then get the cookie prefix config from that:
   - Here: https://github.com/blitz-js/blitz/blob/canary/packages/core/src/blitz-data.tsx#L11-L17
4. Add `cookiePrefix` to new app template as `cookiePrefix: "__name__"`:
   - Here: https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/app/blitz.config.js#L4-L8

**Comment by piotrski** [comment]
Can I grab this one?

**Comment by flybayer** [comment]
Yes!!

**Comment by flybayer** [comment]
Let me know if you have any questions as you go

**Comment by piotrski** [comment]
I was thinking about adding type and config properties to [Middleware type](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/types.ts#L84-L88), but I'm not sure if it will be useful somewhere else?
```tsx
export type Middleware<MiddlewareConfig = {}> = { (
  req: MiddlewareRequest,
  res: MiddlewareResponse,
  next: MiddlewareNext,
):Promise<void> | void
  type?: string
  config?: MiddlewareConfig
}
```

**Comment by flybayer** [comment]
That's a good idea!

**Comment by markhughes** [comment]
Could `cookiePrefix` be a callback function as well, with some basic information? e.g. the path?

**Comment by piotrski** [comment]
We could do this, but I will let you dynamically change the prefix, which can break the authentication. @markhughes what,s your intended use case?

**Comment by markhughes** [comment]
Yep, my use case is to have two different authentication areas of the app... maybe a more ideal process here is conditional middleware?

**Comment by flybayer** [comment]
@markhughes can you open a new issue for your use case and please include as much detail as possible about the problem you're trying to solve.

**Comment by markhughes** [comment]
@flybayer thinking about the approach a bit more and will do :)
