### ISSUE TITLE
NotFoundError has `undefined` `statusCode` in `_app.tsx`

### ISSUE THREAD

**Issue by zigomir** [blitz-js/blitz#1980]
**What is the problem?**

Opening http://localhost:3000/projects/40 I'd expect to see good old `404` and not `400` status code.

I get `400` because this line of code in `_app.tsx`

```js
<ErrorComponent statusCode={error.statusCode || 400} title={error.message || error.name} />
```

but I'd expect error's `statusCode` being `404` when I throw `NotFoundError` like so:

```js
if (!project) throw new NotFoundError()
```

**What are detailed steps to reproduce this?**

1. blitz new app
2. blitz generate all project name:string
3. blitz dev
4. create account & login

open http://localhost:3000/projects/1

**Run `blitz -v` and paste the output here:**

```
macOS Big Sur | darwin-x64 | Node: v15.9.0

blitz: 0.30.1 (global)
blitz: 0.30.1 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.2.1
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Memory: 1.32 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.9.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.5.3 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.17 => 2.17.0 
    blitz: 0.30.1 => 0.30.1 
    prisma: ~2.17 => 2.17.0 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: 4.1.5 => 4.1.5 
```

**Comment by flybayer** [comment]
Yep, bug, thanks for reporting! Will publish a fix here shortly
