### ISSUE TITLE
Can't debug application using breakpoint and node debugger

### ISSUE THREAD

**Issue by karimsx** [blitz-js/blitz#1983]
**What is the problem?**

Hello everonye,

I tried to debug blitjz using launch.json file in vscode, but the debugger can't attach to the 9229 port even if blitz lunched with inspect and the debugger web-socket is correctly setup and working. the error is coming from the fact that vscode try to get `localhost:9229/json/list` and get a 503 error ( even if working in browser)

i tried webstorm, he can successfully attach to node debugger, but no breakpoint is working 

launch.json

{
    "version": "0.2.0",
    "configurations": [
      {
        "type": "node",
        "request": "attach",
        "name": "Launch Program",
        "skipFiles": [
          "<node_internals>/**"
        ],
        "port": 9229
      }
    ]
  }

That would be awesome if there is a sample example to debug using most used code editor : vscode / webstorm

**What are detailed steps to reproduce this?**

Lunch a new project and try to debug

**Run `blitz -v` and paste the output here:**

```
Linux 5.10 | linux-x64 | Node: v14.12.0

blitz: 0.30.2 (global)
blitz: 0.30.2 (local)

  Package manager: yarn 
  System:
    OS: Linux 5.10 Manjaro Linux
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 4.40 GB / 15.62 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.12.0 - ~/.nvm/versions/node/v14.12.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.12.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.12.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.17 => 2.17.0 
    blitz: 0.30.2 => 0.30.2 
    prisma: ~2.17 => 2.17.0 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: 4.1.5 => 4.1.5 
```

**Comment by flybayer** [comment]
Sorry about that! Probably to get breakpoints working, you need to add them to the code inside `.blitz/build`. Not sure if we can fix that at the debugger level or not.

**Comment by flybayer** [comment]
Putting in icebox because this should be fixed by this coming change: https://github.com/blitz-js/blitz/discussions/1990

**Comment by jmcelreavey** [comment]
Any progress on this one? :)

**Comment by flybayer** [comment]
Not fixed yet, but definitely lots of progress on the nextjs fork migration. Several PRs already released and this one https://github.com/blitz-js/blitz/pull/2516 in progress
