### ISSUE TITLE
Support `server.ts` (Custom Server with Typescript)

### ISSUE THREAD

**Issue by BjoernRave** [blitz-js/blitz#1987]
### What do you want and why?

I would like to use Typescript in my custom server.

### Possible implementation(s)

Detect if a `server.ts` file exists, compile it and use it as it is being used right now.

**Comment by flybayer** [comment]
Idea: use esbuild to bundle server.ts https://github.com/co-base/co.base/blob/be76dad44c4ae07135196c286e858e8a1247dc64/server-build.js
