### ISSUE TITLE
`blitz test` does not pick up .env.test.local

### ISSUE THREAD

**Issue by verekia** [blitz-js/blitz#2006]
**What is the problem?**

`blitz test` does not seem to load the right environment variables. It loads `.env.local` but not `.env.test.local`.

In `.env.local` I have `DATABASE_URL="Dev_Database"`
In `.env.test.local` I have `DATABASE_URL="Testing_Database"`

When running `npm test` or `yarn test`, the test suite uses `Testing_Database` as expected.
When running `blitz test`, the test suite uses `Dev_Database`.

**What are detailed steps to reproduce this?**

1. Have some env variables used in testing such as `DATABASE_URL`
2. Compare `npm test` with `blitz test`

**Run `blitz -v` and paste the output here:**

```
macOS Big Sur | darwin-x64 | Node: v15.3.0

blitz: 0.30.4 (global)
blitz: 0.30.4 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.0.1
    CPU: (8) x64 VirtualApple @ 2.50GHz processor
    Memory: 72.71 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.14 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.17 => 2.17.0 
    blitz: 0.30.4 => 0.30.4 
    prisma: ~2.17 => 2.17.0 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: 4.2.2 => 4.2.2 

```

**Comment by flybayer** [comment]
Issue here is that we need to set `process.env.NODE_ENV = test` before loading env variables. However I'm considering removing this command entirely. I've never used it and I doubt many others have either. I'll ask around.

So for now use, `yarn test` or `npm run test`
