### ISSUE TITLE
Seeding dates seems to throw Prisma error

### ISSUE THREAD

**Issue by jmcelreavey** [blitz-js/blitz#2009]
**What is the problem?**

This is a strange one, I've raised it on the prisma github too, basically I'm trying to seed a date of birth. When I use faker or chance and pass in the date (even doing `.toDate`) it errors with "out-of-range datetime" however if I simply pass "new Date()" with the same value it works fine

**What are detailed steps to reproduce this?**

1. Create a schema.prisma with a DateTime field (SQLite)
2. Implement a seeder that populates it (in my case called a create() mutator) 
3. Using faker or chance generate a random date and call the create mutator
4. Older dates (before 1970) seem to cause it to implode 

**Run `blitz -v` and paste the output here:**

```
 Package manager: yarn 
  System:
    OS: Linux 4.19 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (5) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 1.77 GB / 3.84 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.17 => 2.17.0 
    blitz: 0.30.2 => 0.30.2 
    prisma: ~2.17 => 2.17.0 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: 4.1.5 => 4.1.5 
```

**Comment by jmcelreavey** [comment]
This is the only way I have got it to work so far:

```
    var dob = faker.date.between(new Date("1900-01-01"), new Date("2020-01-01"))
    dob = new Date(dob.getFullYear() + "-" + (dob.getMonth() + 1) + "-" + dob.getDate())
```

**Comment by flybayer** [comment]
Thanks @jmcelreavey probably we should close this since it's a prisma issue. Maybe you can link to the prisma issue you opened?

**Comment by MrLeebo** [comment]
You can track the progress of this issue at https://github.com/prisma/prisma/issues/5854
