### ISSUE TITLE
tsc throw error on blitz beta version

### ISSUE THREAD

**Issue by usman-coe** [blitz-js/blitz#2014]
**What is the problem?**

I cannot push code with tsc run on pre-push 

**What are detailed steps to reproduce this?**

1. create a new blitz app
2. connect to repository
3. push code to my repository

**Run `blitz -v` and paste the output here:**

```
Windows 10 | win32-x64 | Node: v14.15.5

blitz: 0.30.5 (global)
blitz: 0.30.5 (local) 

  Package manager: yarn
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 8.37 GB / 15.73 GB
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.17 => 2.17.0
    blitz: 0.30.5 => 0.30.5
    prisma: ~2.17 => 2.17.0
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    typescript: 4.2.2 => 4.2.2
```

this is error
![image](https://user-images.githubusercontent.com/2543952/109374911-51cd7880-78eb-11eb-97e0-971f7dba247f.png)

**Comment by flybayer** [comment]
Thanks @usman-coe! Turns out this is a bug in typescript 4.2.

Solution: downgrade to typescript 4.1

Typescript bug: https://github.com/microsoft/TypeScript/issues/42773

**Comment by usman-coe** [comment]
Thanks @flybayer
