### ISSUE TITLE
invoke returning Promise<any> rather than query return type

### ISSUE THREAD

**Issue by Swapnull** [blitz-js/blitz#2016]
**What is the problem?**

Originally asked: https://discord.com/channels/802917734999523368/814627766694838293/814822759519354892

When doing `invoke(someQuery, {})`, the type returned should be whatever `someQuery` returns. It seems to be `Promise<any>`. 

**What are detailed steps to reproduce this?**

Repo with example: https://github.com/Swapnull/invoke-any-error-blitz

Can also be tested by generating crud using `blitz generate crud myModel` and then trying to use `invoke(getMyModel, {})` somewhere in code. 

**Run `blitz -v` and paste the output here:**

```
macOS Big Sur | darwin-x64 | Node: v15.5.1

blitz: 0.30.5 (global)
blitz: 0.30.5 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 58.35 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.5.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.3.0 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.17 => 2.17.0 
    blitz: 0.30.5 => 0.30.5 
    prisma: ~2.17 => 2.17.0 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: 4.2.2 => 4.2.2 ```

**Comment by flybayer** [comment]
Probably we need to use our `Await` utility type to extract the true return type here
