### ISSUE TITLE
Use Vite instead of Webpack/Next.js

### ISSUE THREAD

**Issue by brillout** [blitz-js/blitz#2022]
Author of [vite-plugin-ssr](https://github.com/brillout/vite-plugin-ssr) here.

Would be lovely if Blitz rebases on top of [Vite](https://vitejs.dev/).

Vite has unprecedented DX.
 - Order of magnitude faster dev speed & HMR.
 - Lazy transpiling for scaling up to thousands of modules with no hit on dev speed.
 - No unnecessary complex configuration (looking at you webpack.config.js).
 - Native SSR support.

It seems like Next.js is not interested in switching to Vite.

Is using Vite + `vite-plugin-ssr` something Blitz would be interested in?

Note that while `vite-plugin-ssr` does require slightly more boiplerplate than Next.js (two files really), it's actually easier to use than Next.js because it has a less intrusive design than Next.js. Basically, `vite-plugin-ssr` can *easily* and *naturally* be used with any tool such as Redux, or even Preact, Inferno, Solid, etc. The [`vite-plugin-ssr` React Tour](https://github.com/brillout/vite-plugin-ssr#react-tour) gives a preview of `vite-plugin-ssr`'s delightful simple design.

**Comment by flybayer** [comment]
Hey! Thanks for reaching out. The Blitz community is currently very happy about being built on Next.js, and we have no plans to switch to something else. We're confident Next.js will bring similar dev DX performance to vite.

Additionally, unless I missed it, vite-plugin-ssr does not provide API routes like Next.js, and this is a critical feature for Blitz.

**Comment by brillout** [comment]
Thank you for your answer! 

> We're confident Next.js will bring similar dev DX performance to vite.

👍 Looking forward to see how Next.js & webpack are going to catch up. Exciting times.

> vite-plugin-ssr does not provide API routes like Next.js

Yes `vite-plugin-ssr` only does SSR. It can however be used with [Wildcard API](https://github.com/brillout/wildcard-api) (we briefly talked about it previously).

I'm aware that do-one-thing-do-it-well is not beginner friendly. I'm actually thinking of building a framework on top Vite and Telefunc (I'm going to rename Wildcard API to Telefunc) that is beginner oriented. I guess we are going to end up "competing", too bad I would have much preferred Blitz to be that framework built on top of `vite-plugin-ssr` and Telefunc. But I understand your perspective.
