### ISSUE TITLE
Create a DigitalOcean Kubernetes 1-click app for the DO Marketplace

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#2031]
### What do you want and why?

We are adding a Blitz image to the Digital Ocean marketplace (they contacted me to start this process)

To do this, you submit a PR to https://github.com/digitalocean/marketplace-kubernetes with the blitz setup.

Once that PR is made, let me know, and I'll finish the submission process with DO.

---

We're also adding a regular droplet image setup here: https://github.com/blitz-js/blitz/issues/2030

**Comment by LucasUnplugged** [comment]
Maybe this is wide open, but is the idea here that the kubernetes image would be for a serverless deployment?

I'm new to the k8s ecosystem (and to blitz.js, for that matter), but have been digging into this quite a bit. I'm looking at using a FaaS platform for that purpose — most likely Fission.

I'm still in the process of trying this setup locally, but it would be amazing to have a 1-click Blitz.js FaaS on DO!

**Comment by flybayer** [comment]
> is the idea here that the kubernetes image would be for a serverless deployment?

I honestly have no idea 😅

**Comment by LucasUnplugged** [comment]
No worries 😄 I'll keep this task in mind, as I get to know Blitz and Kubernetes better. I'd be happy to contribute, if/when I'm capable of doing so.
