### ISSUE TITLE
Update zod to v3

### ISSUE THREAD

**Issue by androsj** [blitz-js/blitz#2055]
### What do you want and why?

I just noticed blitz is using zod v1, both internally and in generated apps.

How do you feel about updating to v3?

Here's the branch with the list of breaking changes:
https://github.com/colinhacks/zod/tree/v3

**Comment by flybayer** [comment]
We'll definitely upgrade to v3 as soon as it's stable!

**Comment by androsj** [comment]
Gotcha. I thought maybe it was "stable enough", even though it's still tagged as alpha.

👍🏻✌🏻

**Comment by zanami** [comment]
_May 17, 2021: Zod v3 is now in stable release!_
