### ISSUE TITLE
ctx object is empty in Vercel Cloud Functions

### ISSUE THREAD

**Issue by jhonnymichel** [blitz-js/blitz#2063]
### What is the problem?

After updating my blitz app from 0.25.0 to 0.31.0 (It was very straight forward even with breaking changes, kudos to your docs and changelogs), my Vercel builds have a very specific problem: ctx objects are empty inside mutations and queries. Looks similar to #862, but I have my blitz updated. I even updated the login/signup mutations to use the latest version.

On my local computer I can build for production and `blitz start` and the app will work normally. In fact, right now I have a mirror for the app on a VPS and everything works fine. but at the Vercel mirror I cannot login and create accounts (both mirrors connected to the same database pool).

### What are detailed steps to reproduce this?

1. Clone and deploy this repo into Vercel https://github.com/jhonnymichel/fitx
2. Try to create an account and pay attention to the Vercel Cloud Function logs

### Run `blitz -v` and paste the output here:

```
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

macOS Big Sur | darwin-x64 | Node: v12.10.0

blitz: 0.31.0 (global)
blitz: 0.31.0 (local)

  Package manager: yarn
  System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 78.49 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/client: 2.17.0 => 2.17.0
    blitz: 0.31.0 => 0.31.0
    prisma: 2.17.0 => 2.17.0
    react: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8
    react-dom: 0.0.0-experimental-7f28234f8 => 0.0.0-experimental-7f28234f8
    typescript: 4.1.5 => 4.1.5
```

<img width="859" alt="image" src="https://user-images.githubusercontent.com/7006387/110077394-ce85aa00-7d64-11eb-9977-4c1d44a7036d.png">

**Comment by flybayer** [comment]
I'm looking into this now

**Comment by flybayer** [comment]
Fixed in https://github.com/blitz-js/blitz/releases/tag/v0.31.1

**Comment by rodrigoehlers** [comment]
Awesome @flybayer I deployed my app yesterday and was confused why I couldn't create accounts or login. Didn't look into it yet, but it'll probably be resolved now. Also thanks @jhonnymichel for bringing this up!

**Comment by jhonnymichel** [comment]
Yep, updated and redeployed to Vercel and now I can login!

**Comment by quatick** [comment]
Hi, I think it worth to be mention, I also have the issue after upgrading the blitz version.
I have the v0.32.1 on **Vercel** with the problem, and unfortunately, downgrading to v0.31.1 doesn't help.
Does someone have an idea on how to resolve this issue ?

PS: Thank you for all the amazing work about blitz, it is truly a life changer, love it !

**Comment by flybayer** [comment]
@quatick is your issue with gSSP or gSP? If so, see workaround here: https://github.com/blitz-js/blitz/issues/794

**Comment by quatick** [comment]
Hi @flybayer , none of the two, it is call with useMutation `const [loginMutation] = useMutation(login)` in a react component.

Do you have some ideas why this could happens to help me narrowing down the issue ?

**Comment by quatick** [comment]
Ok I found the issue ! This is coming from the module `next-transpile-modules` which I integrated to `blitz.config` in order to import Pusher.io correctly.
Tooks me far too long to debug.
Thank you for your support.

**Comment by maxfi** [comment]
@quatick I'm also using `next-transpile-modules` and am having the same issue. How did you resolve this? TIA! 🙏

**Comment by quatick** [comment]
@maxfi I just removed `pusher` and `next-transpile-module` as I hesitated between pusher and firebase.
I think every new version of next could break `next-transpile-module` and adding blitz (even more with the fork next repo) will add even more instability, I choose to avoid using the module.

**Comment by maxfi** [comment]
@quatick thanks for the clarification. I was hoping to still use `next-transpile-module` but you're right that it will most likely cause more pain than it's worth down the track.

**Comment by flybayer** [comment]
> (even more with the fork next repo) 

The fork will make blitz much more stable. Perhaps next-transpile-modules will work once that is complete
