### ISSUE TITLE
No parent relationship

### ISSUE THREAD

**Issue by nikolay** [blitz-js/blitz#2064]
### What is the problem?

There's no parent relationship between `teacher` and `school` anywhere. The DB migration SQL, the Prisma schema, etc. have no mention of school with teacher!

### What are detailed steps to reproduce this?

1. `blitz generate all school name:string`
2. `blitz generate all teacher name:string --parent=school`

### Run `blitz -v` and paste the output here:

```
$ blitz -v
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

macOS Big Sur | darwin-x64 | Node: v15.11.0

blitz: 0.31.0 (global)
blitz: 0.31.0 (local)

  Package manager: yarn
  System:
    OS: macOS 11.2.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.06 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.11.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.0 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.17 => 2.17.0
    blitz: 0.31.0 => 0.31.0
    prisma: ~2.17 => 2.17.0
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    typescript: ~4.1 => 4.1.5
```

**Comment by flybayer** [comment]
Hey @nikolay, this is definitely sub-optimal UX right now.

You need to include `belongsTo:school` for the prisma relationship to be added.

So: `blitz generate all teacher name:string belongsTo:school --parent=school`

**Comment by nikolay** [comment]
Thank you, @flybayer! I probably will fix the documentation, because it doesn't really have it in the basic example.

**Comment by flybayer** [comment]
@nikolay oh, yes it should! A PR would be greatly appreciated

**Comment by flybayer** [comment]
Fixed via documentation
