### ISSUE TITLE
Running yarn dev to run development version fails on Windows

### ISSUE THREAD

**Issue by Roesh** [blitz-js/blitz#2072]
### What is the problem?

After forking and downloading the blitz repository on Windows, running the `yarn` command, running `yarn dev` causes the following error
```
PS C:\Users\Roshan\Documents\Blitz\blitz> yarn dev
yarn run v1.22.10
$ preconstruct dev && concurrently --names "typecheck,cli,templates" -c "blue,green,yellow,magenta" -p "{name}" "npm:dev:tsc" "npm:dev:cli" "npm:dev:templates"
��� info project is valid!
��� error [Error: EPERM: operation not permitted, symlink 'C:\Users\Roshan\Documents\Blitz\blitz\packages\babel-preset\src\index.ts' -> 'C:\Users\Roshan\Documents\Blitz\blitz\packages\babel-preset\dist\blitzjs-babel-pr
et.esm.js'] {
��� error   errno: -4048,
��� error   code: 'EPERM',
��� error   syscall: 'symlink',
��� error   path: 'C:\\Users\\Roshan\\Documents\\Blitz\\blitz\\packages\\babel-preset\\src\\index.ts',
��� error   dest: 'C:\\Users\\Roshan\\Documents\\Blitz\\blitz\\packages\\babel-preset\\dist\\blitzjs-babel-preset.esm.js'
��� error }
��� info If want to learn more about the above error, check https://preconstruct.tools/errors
��� info If the error is not there and you want to learn more about it, open an issue at https://github.com/preconstruct/preconstruct/issues/new
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### What are detailed steps to reproduce this?

1. Forking and download the blitz repository at https://github.com/blitz-js/blitz 
2. Clone your fork onto a Windows machine
3. Run the `yarn` command
4. Run the `yarn dev`  command

### Run `blitz -v` and paste the output here:

```
Windows 10 | win32-x64 | Node: v15.8.0

blitz: 0.31.0 (global)
blitz: 0.31.0 (local)

  Package manager: npm
  System:
    OS: Windows 10 10.0.18363
    CPU: (16) x64 AMD Ryzen 7 2700 Eight-Core Processor
    Memory: 5.37 GB / 15.93 GB
  Binaries:
    Node: 15.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.6.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.17.0 => 2.17.0
    blitz: 0.31.0 => 0.31.0
    prisma: 2.17.0 => 2.17.0
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    typescript: 4.1.5 => 4.1.5
```

**Comment by flybayer** [comment]
@Roesh can you try running `yarn reset` and then `yarn dev` and see if that works?

**Comment by flybayer** [comment]
A workaround is to manually run `preconstruct watch`, then remove `preconstruct dev` from that script and run `yarn dev` also.

**Comment by Roesh** [comment]
Hm, so doing yarn reset and yarn dev doesn't solve it, but the preconstruct watch one does.

I downloaded @preconstruct/cli separately, and ran preconstruct watch in one terminal, and ran yarn dev in another and I'm seeing the changes I made.

Question though, I assumed that the process needs to be left running for any changes to take effect, however, I closed both the terminals running preconstruct watch and yarn dev and I ran blitz install in the example folder, and the changes that I made to the prompts even after yarn dev wasn't running showed up. I'm assuming that some changes don't require yarn dev to be running in a terminal to take effect?

**Comment by flybayer** [comment]
Right, `yarn preconstruct watch` must be running to pick up changes.

Could you open an issue in https://github.com/preconstruct/preconstruct with the exact steps to reproduce this in our repo?

**Comment by Roesh** [comment]
mitchell from the preconstruct repo mentioned that `You need to enable Windows Developer Mode so that Preconstruct can create symlinks - https://www.howtogeek.com/292914/what-is-developer-mode-in-windows-10/`

I did so and it fixed this issue.

Adding a section for preconstruct errors to the docs: https://github.com/blitz-js/blitzjs.com/pull/401
