### ISSUE TITLE
Nested Pages do not resolve public paths correctly

### ISSUE THREAD

**Issue by michaelminhvo** [blitz-js/blitz#2086]
### What is the problem?

Nested pages, say "localhost:3000/nested/broken" will correctly render images from `/public` folder only if we reference the image by navigating one folder up with `<img src="../logo.png" />`, ideally it should work with `<img src"logo.png" />`.

This is because if we use a shared component in "core/components" that references an image from `public`, that shared component will only work for pages at the same path level, and not for nested paths. For example a shared menu header with an icon that is shared between all pages.

### Paste all your error logs here:

N/A

### Paste all relevant code snippets here:

```
const Broken: BlitzPage = () => {
  return (
    <div className="container">
      Logo links "logo.png"
      <img src="logo.png" />
      Logo links "../logo.png"
      <img src="../logo.png" />
    </div>
  );
};
```

### What are detailed steps to reproduce this?

1. I've attached a sample forked project here with a page showing the output:

https://codesandbox.io/s/youthful-sky-5gzht

Visit the nested page at https://5gzht.sse.codesandbox.io/nested/broken

### Run `blitz -v` and paste the output here:

```
blitz 0.31.1
```

Output when visiting 
<img width="1172" alt="Screen Shot 2021-03-07 at 3 34 32 PM" src="https://user-images.githubusercontent.com/1610756/110253923-c1caa700-7f5a-11eb-8d52-091801e1f915.png">

blitz -v screenshot
<img width="278" alt="Screen Shot 2021-03-07 at 3 35 03 PM" src="https://user-images.githubusercontent.com/1610756/110253979-01918e80-7f5b-11eb-848c-677428168247.png">

**Comment by kevinlangleyjr** [comment]
@michaelminhvo, it looks like you're referencing the static file incorrectly according to the [documentation](https://blitzjs.com/docs/static-files).

You should be referencing the static file with the root slash, i.e. `/logo.png` instead of `logo.png`.

**Comment by michaelminhvo** [comment]
> @michaelminhvo, it looks like you're referencing the static file incorrectly according to the [documentation](https://blitzjs.com/docs/static-files).
> 
> You should be referencing the static file with the root slash, i.e. `/logo.png` instead of `logo.png`.

Thanks. This fixes it.
