### ISSUE TITLE
ProductForm in examples warms up BOTH update and create lambdas on every page

### ISSUE THREAD

**Issue by Zeko369** [blitz-js/blitz#209]
**What is the problem?**
ProductForm warms up `updateProduct` and `createProduct` lambdas, regardless of whether it's new or edit page.

**Steps to Reproduce:**

1. `yarn blitz start` in examples/store
2. Open console/network

**Versions:**

- Blitz: 0.6.0-canary.0
- OS: macOS 10.15.3 (19D76)

```
debug: monorepo
debug: pkgPath: /Users/franzekan/blitz/mine/node_modules/@blitzjs/cli 

env: darwin-x64 node-v12.16.1
blitz: 0.6.0-canary.0 (global)
blitz: 0.6.0-canary.0 (local)
```

**Supporting Documentation**
Please include applicable logs and screenshots that show your problem.

**Comment by flybayer** [comment]
This is because the JS is preloaded for both. I'm not quite sure how we could optimize this 🤔

**Comment by ryardley** [comment]
Can certainly do it with a babel transform and internal API change but I think the benefit is not worth slowing down the compilation. If we could reliably somehow use regex to transform the code it could work and remain fast.
