### ISSUE TITLE
Add cli command: blitz start

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#21]
- [ ] `blitz start` should start the Next.js development server by spawning `next dev`
- [ ] `blitz s` should run `blitz dev`
- [ ] `blitz start --production` or `blitz start -p` should run `next build && next start`
- [ ] Add tests

**Comment by Leigh-M** [comment]
I am still seeing: "Warning: start is not a blitz command." with blitz start - I do have blitz installed and run npm i

**Comment by flybayer** [comment]
@Leigh-M if you have an issue, you need to either open a new issue or ask for help in the Blitz discord. This issue was closed over a year ago 😅
