### ISSUE TITLE
Unable to 'Add record' in Prisma Studio if not all fields are filled even if they are not required

### ISSUE THREAD

**Issue by tom-richter** [blitz-js/blitz#2126]
### What is the problem?

I can't add a new record in prisma studio if not all fields are filled, even if they can be null. By clicking on 'Add record' this is logged into the browser console: `row index for ensureIndexVisible: 0` By clicking on the 'Save change' button nothing happens. If using prisma in a non-blitz project this issue doesn't occur.

### Paste all your error logs here:

Browser Console log:
```
invalid row index for ensureIndexVisible: 0
```
Nothing logged into the blitz console.

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1. Create a new blitz project
2. Add this to your schema.prisma:
```
model Test {
  id          Int     @id @default(autoincrement())
  name        String
  description String?
}
```
3. Run `blitz prisma migrate dev` and `blitz prisma studio`
4. Try adding a new record in the Test table with an empty description field

### Run `blitz -v` and paste the output here:

```
Linux 5.8 | linux-x64 | Node: v12.18.3

blitz: 0.33.0 (global)
blitz: 0.33.0 (local)

  Package manager: npm 
  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 637.68 MB / 15.52 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: Not Found
    npm: 7.6.3 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.17 => 2.17.0 
    blitz: 0.33.0 => 0.33.0 
    prisma: ~2.17 => 2.17.0 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: ~4.1 => 4.1.5 
```

![Screenshot from 2021-03-18 15-24-49](https://user-images.githubusercontent.com/68494402/111644737-67560400-8800-11eb-96c1-7433f101d480.png)

**Comment by MrLeebo** [comment]
Are you sure you're using prisma 2.17 in the non-blitz context? I can repro this in 2.17, but if I upgrade to 2.19 the issue goes away, but 2.19 has a different bug where it doesn't save your edits unless ​you blur the textbox before you click "Save changes"

**Comment by tom-richter** [comment]
You're right, I was using a newer version of prisma in the non-blitz context. If I update to prisma 2.19 this bug also goes away in my blitz app, so it wasn't a blitz issue.
