### ISSUE TITLE
`id` fields using uuid Prisma type are overwritten every time `blitz generate` modifies a model

### ISSUE THREAD

**Issue by Southclaws** [blitz-js/blitz#2127]
### What do you want and why?

I wanted to use UUIDs for all my `id` fields in models. So I updated my schema to:

```
  id         String   @id @default(uuid())
```

And the relevant zod schemas:

```ts
const UpdateThing = z
  .object({
    id: z.string(),
...
```

But any future changes to the model, such as `blitz generate resource thing field:type` results in:

```diff
const UpdateThing = z
  .object({

-     id: z.string(),
+     id: z.number(),
    name: z.string(),  })
  .nonstrict()
```

Which isn't a huge problem, I can just update the model myself, run `prisma generate` and make any necessary schema changes myself but it kind of makes the `blitz generate` tooling useless to me.

### Possible implementation(s)

The ability to declare a preferred identifier strategy via Blitz config would be useful. It would keep things declarative and consistent and reduce the need for inference and manual editing.

Inferring the users changes to the schema is another option. If Blitz tooling could see that the previously generated fields named `id` are using some other type (`String`), it could avoid touching them.

### Additional context

Prisma offers a couple of additional identifier types: uuid() and [cuid()](https://github.com/ericelliott/cuid) which have their own use-cases outside of a simple incrementing number.

**Comment by MrLeebo** [comment]
That's for reporting this. The `blitz generate` tools are not feature-complete yet; they're basically templates that do a couple of value substitutions. Until they get smarter I think it's better to do manual editing once you've set up your app.
