### ISSUE TITLE
Blitz synchronizer should report different during runtime than during start

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#213]
**What is the problem?**

We have a nice spinner and success message for at the start of blitz start, but this same message is being shown if the server is already running and you change a file.

During runtime I think we should only show error messages. Don't show spinner or success.

**Supporting Documentation**
```
> Using "webpackDevMiddleware" config function defined in default.
[ info ]  bundled successfully, waiting for typecheck results...
[ wait ]  compiling ...
[ info ]  bundled successfully, waiting for typecheck results...
[ ready ] compiled successfully - ready on http://localhost:3000
Processing file...db/schema.prisma
✔ Prepped for launch
Processing file...db/schema.prisma
✔ Prepped for launch
Processing file...app/admin/pages/admin/index.tsx
✔ Prepped for launch
```

**Comment by merelinguist** [comment]
So you want all this:

```
Processing file...db/schema.prisma
✔ Prepped for launch
Processing file...db/schema.prisma
✔ Prepped for launch
Processing file...app/admin/pages/admin/index.tsx
✔ Prepped for launch
```

gone during runtime?

**Comment by flybayer** [comment]
Yes, just like you get with plain Next.js

**Comment by flybayer** [comment]
Re-opened because #369 broke `blitz start/build` when published to npm. It worked fine in the monorepo, but not after published to npm.

It logged `◢ Preparing for launch⏎` then exits with non-0 exit code

```
/p/t/dogs> blitz start
You are using alpha software - if you have any problems, please open an issue here:
  https://github.com/blitz-js/blitz/issues/new/choose

◢ Preparing for launch⏎
```

Reverted in https://github.com/blitz-js/blitz/pull/384

**Comment by flybayer** [comment]
@ryardley false alarm. Still failing when published to npm without that.

I'll merge that PR back in, but first figuring out this other issue
