### ISSUE TITLE
Custom error page for 403 error?

### ISSUE THREAD

**Issue by ericvicenti** [blitz-js/blitz#2131]
### What is the problem?

Is it possible to customize the 403 error page? This might be a feature request instead of a bug.

[Blitz allows](https://blitzjs.com/docs/error-pages#customizing-the-error-page) a custom error page defined in `app/pages/_error.tsx`

The page accepts a statusCode prop, so I incorrectly assumed that 403 errors would be handled by this page. But the 403 error looks like the next.js default error.

Thank you for the excellent work on Blitz!

### Paste all your error logs here:

n/a

### Paste all relevant code snippets here:

Custom _error.tsx .. (taken from docs)
```ts
function Error({ statusCode }) {
  return (
    <p>
      {statusCode ? `An error ${statusCode} occurred on server` : "An error occurred on client"}
    </p>
  )
}

Error.getInitialProps = ({ res, err }) => {
  const statusCode = res ? res.statusCode : err ? err.statusCode : 404
  return { statusCode }
}

export default Error
```

### What are detailed steps to reproduce this?

1. Create a custom `app/pages/_error.tsx` according to the documentation: https://blitzjs.com/docs/error-pages#customizing-the-error-page
2. Cause a 403 error by:
2a. Create a page which contains a query: `const [foo] = useQuery(getFoo, null)`
2b. Create a query which throws an AuthorizationError: 
```ts
export default async function getFoo(_input: null, { session }: Ctx) {
  if (!session.userId) throw new AuthorizationError()
```
3. Test prod build with `blitz build` and `blitz start`
4. Load the page and trigger an authorization error. Notice that the component in `app/pages/_error.tsx` is not shown!

### Run `blitz -v` and paste the output here:

```
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

macOS Big Sur | darwin-arm64 | Node: v15.11.0

blitz: 0.32.1 (global)
blitz: 0.32.1 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.2.1
    CPU: (8) arm64 Apple M1
    Memory: 1015.81 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.6.0 - /opt/homebrew/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.18.0 => 2.18.0 
    blitz: 0.32.1 => 0.32.1 
    prisma: ~2.18.0 => 2.18.0 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: ~4.2.3 => 4.2.3 
```

**Comment by MrLeebo** [comment]
@ericvicenti The code that you're probably looking for is `if (error instanceof AuthorizationError)` in https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/app/app/pages/_app.tsx#L35-L41 from the default app template. 

Queries and mutations are implemented as RPC calls internally and don't reflect their HTTP status code in the response. So the status code is always 200 OK and the error is serialized inside the RPC response body. Instead, you can check that the error is an instance of the expected error class, because the full error object gets serialized to the front-end to create an invisible transition between your front-end and back-end code.

**Comment by ericvicenti** [comment]
@MrLeebo , thank you, that makes perfect sense.

I added some docs in this PR here, to help smooth this out for the next round of newbies: https://github.com/blitz-js/blitzjs.com/pull/418
