### ISSUE TITLE
provide default <a> behaviour, i.e. normal non-SPA navigation

### ISSUE THREAD

**Issue by toinbis** [blitz-js/blitz#2135]
### What do you want and why?
I'd expect a standard HTTP-based navigation as a primary option of how my frontend works. Like with Rails or django - each click generates a http request and retrieves http response. There is so much things js navigation makes impossible, i.e. decent client+server side web analytics. IMHO all-around frameworks should surely support both means of navigation. Not arguing here which is better, just stating that supporting both as first-class citizens should be considered.

Also am not 100% it's not currently possible, but JS-based navigation is surely presented as default one as of now.

Thanks for consideration!

**Comment by flybayer** [comment]
Hey @toinbis, we actually do support that. You don't have to use the `<Link>` component, but it will be a poorer experience because it will do hard page transitions which kill the entire react app and restart it on the next page. Whereas with the `<Link>` component, the react app stays booted and simply changes the page component, resulting in a nice, fast page transition.

**Comment by MrLeebo** [comment]
`<Link>` components fallback to `<a>` and still work when JS is disabled, don't they?

**Comment by toinbis** [comment]
Thanks a lot @flybayer, @MrLeebo !

`it will be a poorer experience because it will do hard page transitions` - I'd argue (things are getting opinionated from here, haha) it's the (complete) oposite:

a) consistent experience for each pageview - instead of two completely different experiences visiting same page from external VS internal click.
b) consistent experience with how pageview happens browsing websites all-over-the internet. I.e. Click -- browser reload button/indicator changes state from "refresh" to "x" -- small delay - page is ready.

Websites behaving as websites, apps behaving as apps - that's what I was aiming for and am super happy Blitz support both use cases! :) But this is very conceptual discussion we're diving into, as for the scope of the ticket, I'd say we can close it!

Thanks again @flybayer & @MrLeebo for jumping in and elaborating!
