### ISSUE TITLE
Add a better faunadb integration example 

### ISSUE THREAD

**Issue by noga-aviator** [blitz-js/blitz#2139]
### What do you want and why?

The current faunadb example doesn't show how to include the forgotPassword and resetPassword mutations. Could it be added ?

**Comment by flybayer** [comment]
Yes! Until we get that, you can compare signup mutations between fauna and a default blitz app. And then apply the same difference to the forgot/reset password mutations.

**Comment by g3offrey** [comment]
I wanted to try out FaunaDB so I can work on this issue and propose a pull request. 😄

**Comment by yusiflinurlan** [comment]
@flybayer , Hello! Can you please assign this to me?
