### ISSUE TITLE
Provide a better error message for non-resolvers in queries folders

### ISSUE THREAD

**Issue by JohnGrisham** [blitz-js/blitz#2140]
### What do you want and why?

Provide a better error message when placing files in queries folders that aren't resolvers. Or determine a better way to indicate that a file is a query.

Bonus points: Maybe a config setting?

### Possible implementation(s)

- Provide a better error message
- Determine a better way to indicate that a file is a query

Possibly add a configuration setting to change the default folder name where queries live.

### Additional context

Currently, only resolvers are allowed in queries folders.

I created an interfaces folder for holding general types and inside that folder was a queries folder. I placed query-related types inside that folder and received the error below.

![image](https://user-images.githubusercontent.com/32438099/112313531-f5edd980-8c75-11eb-852c-d84c4dfbb272.png)

**Comment by flybayer** [comment]
Thanks @JohnGrisham! This is blocked pending integration of next.js fork
