### ISSUE TITLE
Allow manual configuration of the react-query `key`

### ISSUE THREAD

**Issue by jorisre** [blitz-js/blitz#2146]
### What do you want and why?

*What?*
I want to be able to change manually the react-query cache key

*Why?*
I want to display multiples results based on different react-query keys, for example:
- Home list
- Search list
- Etc ...

It allows us to have multiples results in cache and improve the UX or trigger a new request when the key change.

### Possible implementation(s)

I'm pretty new to Blitz, here is some idea.

One possible implementation:

```ts
import type { AnyQueryKey } from "react-query"

const [...] = useQuery(getProject, params, { key:  `my-key` }) // Key is of type AnyQueryKey and it's optional
```

[`getQueryKey` util](https://github.com/blitz-js/blitz/blob/54796b6afd5de9e9b0fa7c2781962f482688e3bd/packages/core/src/utils/react-query-utils.ts#L76) could have a third optional arg:

```ts
export function getQueryKey<TInput, TResult, T extends QueryFn>(
  resolver: T | Resolver<TInput, TResult> | EnhancedResolverRpcClient<TInput, TResult>,
  params?: TInput,
  key?: string // <= 🆕
) {
  if (typeof resolver === "undefined") {
    throw new Error("getQueryKey is missing the first argument - it must be a resolver function")
  }

  return getQueryKeyFromUrlAndParams(sanitize(resolver)._meta.apiUrl, params, key) // Pass down the key
}
```

react-query v2 impacted hooks:
- `useQuery`
- `usePaginatedQuery`
- `useInfiniteQuery`

### Additional context

Here is the original discussion: https://github.com/blitz-js/blitz/discussions/2128

Maybe related to [Upgrade react-query to v3 - #2012](https://github.com/blitz-js/blitz/issues/2012) because some hooks are deprecated in v3 [(usePaginatedQuery)](https://react-query.tanstack.com/guides/migrating-to-react-query-3#usepaginatedquery-has-been-deprecated-in-favor-of-the-keeppreviousdata-option)

**Comment by flybayer** [comment]
I just gave an update at https://github.com/blitz-js/blitz/discussions/2128#discussioncomment-535723

Does that solve your use case?
