### ISSUE TITLE
TypeScript issues in custom server

### ISSUE THREAD

**Issue by ericvicenti** [blitz-js/blitz#2160]
I'm trying to build an application with WebSockets, implemented in TypeScript, that can connect to the database/prisma.

### What do you want and why?

TypeScript support for custom server files, which can access "db"

In `app/server/server.ts`, I want to write the following:

```ts
import { createServer } from "http"
import * as dotenv from "dotenv"
import blitz from "blitz/custom-server"
import { parse } from "url"
import WebSocket from "ws"
import express from "express"
import db from "db"

dotenv.config()

const dev = process.env.NODE_ENV !== "production"

const app = blitz({ dev })

const defaultPort = dev ? 3001 : 3000
const port = process.env.PORT ? Number(process.env.PORT) : defaultPort

async function startServer() {
  // await connectNotifications()
  const server = express()
  const handle = app.getRequestHandler()
  server.use(
    express.static(__dirname + "/public", {
      maxAge: "30d",
    })
  )
  server.use((req: any, res: Response) => {
    const parsedUrl = parse(req.url, true)
    return handle(req, res, parsedUrl)
  })
  const httpServer = createServer(server)

  const wss = new WebSocket.Server({
    server: httpServer,
  })
  await new Promise<void>((resolve, reject) => {
    httpServer.listen(port, () => {
      resolve()
    })
    httpServer.on("error", reject)
  })

  wss.on("connection", (socket: WebSocket) => {
    // here I want to use "db"
  })
}

startServer().catch((err) => {
  console.error(err)
})

```

I know Nextjs/Vercel do not really care about custom server files. But I'd hope Blitz would have support for support for this sort of thing. (After all, websocket support is not very helpful unless you can talk to the db or the rest of your server code).

### Possible implementation(s)

I'm currently trying to do this with `ts-node` and a custom `tsconfig.server.json`. The main difference in the server tsconfig is `"module": "commonjs", "outdir": "dist"`

My dev command is: `    "dev": "NODE_ENV=development nodemon --watch server -e js,ts,tsx --exec 'ts-node --project tsconfig.server.json app/server/Server.ts'",`

There are two issues I have seen, preventing my custom `Server.ts` from working when I run `yarn dev`

1. Absolute imports do not work. Eg. `import db from "db"` is broken. Workaround is relative paths: `import db from "../../db"

2. Next fires an error which I don't understand and could not get past: 
```
Error: > Couldn't find a `pages` directory. Please create one under the project root
    at findPagesDir (/Users/ericvicenti/dev/aven/node_modules/next/lib/find-pages-dir.ts:28:9)
    at new DevServer (/Users/ericvicenti/dev/aven/node_modules/next/server/next-dev-server.ts:101:21)
    at NextServer.createServer (/Users/ericvicenti/dev/aven/node_modules/next/server/next.ts:104:14)
    at /Users/ericvicenti/dev/aven/node_modules/next/server/next.ts:121:28
    at NextServer.prepare (/Users/ericvicenti/dev/aven/node_modules/next/server/next.ts:87:20)
```

### Additional context

Related issues: https://github.com/blitz-js/blitz/issues/1987 https://github.com/blitz-js/blitz/issues/303

**Comment by ericvicenti** [comment]
Thanks for the response @flybayer. I guess there is no support for typescript in the server file? I have used this approach with Next before. With blitz I can't get past the blitz pages directory error. Is there anything i can pass into `blitz({ dev })` that can help configure the pages directory?

Unfortunately WS+TS support is important for me, and I may be forced to go back to bare Next.js.

I understand this is super tricky stuff because of Next+Webpack constraints. Ideally the server.ts would be bundled by the same system.. the tsc and ts-node approach I use is a total hack. (but at least it worked with next...)

**Comment by flybayer** [comment]
@ericvicenti your tsc approach should work exactly the same with Blitz. Can you link a repo that reproduces this?

**Comment by ericvicenti** [comment]
Here is my blitz repo where I am trying to add a TypeScript server file: 

https://github.com/co-base/co.base/tree/72785c87b33ea0310c12d873722a05130906213a

You can see all the clumsy attempts I have made: `yarn dev1` `yarn dev2` and `yarn dev3` are all broken 😭. (`yarn dev` runs blitz without the custom server file)

`dev1` reaches the "pages directory" issue above.

`dev2` is a bad approach (and I should feel bad 😂). strange errors happen.

`dev3` reaches an error: "Error: Cannot find module './blitz.config.js'"

This "legacy" repo uses Next, and similar approaches with `tsc` and `ts-node` work fine: https://github.com/co-base/legacy

Thanks for your help on this! I'd be happy to help with documentation when this is resolved, or I can publish an example Blitz app that demonstrates TypeScript+WebSockets.

**Comment by flybayer** [comment]
@ericvicenti oh my, I'm so sorry. With Blitz, you don't actually run your custom server.

1. Add a `server.js` file at your project root
2. Run `blitz dev`,  `build build`, and `build start` will all automatically use your custom server

But you'll still need nodemon to run tsc `server.ts -> server.js` and restart `blitz dev`. (Until we get custom server TS support added)

See https://blitzjs.com/docs/custom-server

**Comment by ericvicenti** [comment]
No worries, I realize I am on the bleeding edge! 🔥

But that was one of the first approaches I tried. I just added `yarn dev4` on that repo to demonstrate. 

`"dev4": "tsc server.ts --esModuleInterop && blitz start",`

I also added `server.js` to my .gitignore file, because it is not a source file in this case.

But the TS build fails, it gets confused when it sees blitz stuff.

<img width="1246" alt="Screen Shot 2021-04-01 at 12 46 13 PM" src="https://user-images.githubusercontent.com/1483597/113346123-4dc8b800-92e8-11eb-8bc1-c374a4271943.png">

Sorry if I am doing dumb things with tsc here.. I am very spoiled by having tools like CRA and Next hide the complexity from me.

**Comment by flybayer** [comment]
@ericvicenti I got you going: https://github.com/co-base/co.base/pull/40

**Comment by ericvicenti** [comment]
Thanks for the help @flybayer . I am still having troubles with the configuration so I responded here:

https://github.com/co-base/co.base/pull/40#issuecomment-812592214

Let me know if I should just wait for full TS support on the blitz server side. I don't want to take up your time on work-arounds.

I am also considering maybe separating out the "front end" and the "back end" into separate node applications, where the "back end" supports websockets and is compiled with esbuild. Let me know what strategy you recommend.
