### ISSUE TITLE
useAuthentication hook run before the component gets mounted

### ISSUE THREAD

**Issue by MANTENN** [blitz-js/blitz#2163]
### What do you want and why?
So this is a request of: https://twitter.com/mantennn/status/1375349353821298692.

I want the `useAuthentication` to redirect the user without any mounting and flashes. I want it because this would provide a better UX for users.

### Possible implementation(s)
The `_app` component can have a provider which would periodically and on route change grab the stored token. The `useAuthenticated` hook can use the context state value which would be able to run checks if the user is authenticated without mounting the component to the DOM thereby removing the need for useEffect and running unnecessary computations, API fetches, etc.   

How might we do this?
Create a `Context.Provider` developers can use in `_app`
`tokenValidator` = grab the local storage value and return the decoded token value or (null/undefined if there is no token or its invalid)
setTimeout(period of 15 minutes run `tokenValidator`)
routeListener(on route change run `tokenValidator`)
`useAuthenticated` grabs the value from `Context.Provider` and validates it.

**Comment by flybayer** [comment]
Thanks @MANTENN. We already support part of this via `Page.authenticate = true` [(docs)](https://blitzjs.com/docs/authorization#secure-your-pages). You will not see a flash of content with that. However it does mount the page in the background and run any useEffect hooks.

We could do what you are asking for not actually mounting the the page, but this will prevent the static page optimization. Currently the page's loading state is rendered at build time and loads instantly when a user visits. But if we don't mount until auth is verified, then we can't render the loading page at build time. So probably this would be an opt-in feature.

**Comment by MrLeebo** [comment]
You can also authenticate in getServerSideProps, along with any initial data fetches so you can render the page without hitting a loading state.

```ts
export async function getServerSideProps({ req, res }) {
  const session: SessionContext = await getSession(req, res)
  if (!session.$isAuthorized()) return { redirect: { destination: "/login" } }

  const data = (...)

  return { props: { data } }
}
```

**Comment by MANTENN** [comment]
> You can also authenticate in getServerSideProps, along with any initial data fetches so you can render the page without hitting a loading state.
> 
> ```ts
> export async function getServerSideProps({ req, res }) {
>   const session: SessionContext = await getSession(req, res)
>   if (!session.$isAuthorized()) return { redirect: { destination: "/login" } }
> 
>   const data = (...)
> 
>   return { props: { data } }
> }
> ```

Yup, I am aware of the ServerSide prop my proposal was for client side routing.

**Comment by MANTENN** [comment]
> Thanks @MANTENN. We already support part of this via `Page.authenticate = true` [(docs)](https://blitzjs.com/docs/authorization#secure-your-pages). You will not see a flash of content with that. However it does mount the page in the background and run any useEffect hooks.
> 
> We could do what you are asking for not actually mounting the the page, but this will prevent the static page optimization. Currently the page's loading state is rendered at build time and loads instantly when a user visits. But if we don't mount until auth is verified, then we can't render the loading page at build time. So probably this would be an opt-in feature.

Closing as this is what I was requesting.
