### ISSUE TITLE
Shallow routing does not maintain state

### ISSUE THREAD

**Issue by svo393** [blitz-js/blitz#2168]
### What is the problem?

When changing url query through <Link>  or router.push with { shallow: true } the page acts like it is the first render. It defeats the purpose of using usePaginatedQuery, making react-query loose it's last successfully resolved data from previous page. In Next.js that doesn't happen.

### Paste all your error logs here:

```
N/A
```

### Paste all relevant code snippets here:

```
N/A
```

### What are detailed steps to reproduce this?

1. Go to [https://codesandbox.io/s/cranky-tereshkova-bveyr?file=/app/pages/router.tsx]
2. Go to /router?page=2 in the internal browser
3. Click links
4. Check the console

### Run `blitz -v` and paste the output here:

```
Blitz CodeSandbox Example from blitz.com home page
```

**Comment by flybayer** [comment]
Closed in #2173
