### ISSUE TITLE
No request sent with `useInfiniteQuery` when query params change

### ISSUE THREAD

**Issue by jorisre** [blitz-js/blitz#2172]
### What is the problem?

ℹ️I haven't tested with other hooks _(useQuery, ...)_

When using `useInfiniteQuery` with `initialData` and passing params dynamically no request is sent.
I got this problem only if I use `initialData`, if I don't use it, all works well.

Example fo the problem:
![blitz-ss](https://user-images.githubusercontent.com/7545547/112736952-faa4dd00-8f56-11eb-8606-4a62210e94f7.gif)

### Paste all your error logs here:

No log because no error :)

### Paste all relevant code snippets here:

The repo: https://github.com/jorisre/blitzjs-search-with-react-query

https://github.com/jorisre/blitzjs-search-with-react-query/blob/main/app/pages/projects/index.tsx#L41

```ts
const where = searchText ? { where: { name: { contains: searchText } } } : {}

  const [groups, { isFetchingMore, fetchMore, canFetchMore }] = useInfiniteQuery(
    getProjects,
    (page = { take: ITEMS_PER_PAGE, skip: 0 }) => {
      return { ...page, ...where }
    },
    {
      suspense: false,
      getFetchMore: (lastGroup) => lastGroup.nextPage,
      initialData: [projects], // Comment this line to get the page works
    }
  )
```

### What are detailed steps to reproduce this?

Here is the minimal reproduction repo https://github.com/jorisre/blitzjs-search-with-react-query

1. Clone the repo, install deps
2. Run seeds: `blitz db seed`
3. Start the project `yarn dev`
4. Create an account
5. Go to http://localhost:3000/projects
6. Try to search a person by name _(nothing happen)_. Remove one char from the search input and the request is triggered

**Expected**
When the query params change, a new request should happen and returns the new result

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v14.12.0

blitz: 0.33.0 (global)
blitz: 0.33.0 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 1.86 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.12.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.npm-packages/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.19.0 => 2.19.0 
    blitz: 0.33.0 => 0.33.0 
    prisma: 2.19.0 => 2.19.0 
    react: 0.0.0-experimental-a77dd13ed => 0.0.0-experimental-a77dd13ed 
    react-dom: 0.0.0-experimental-a77dd13ed => 0.0.0-experimental-a77dd13ed 
    typescript: ~4.2.3 => 4.2.3 
```

**Comment by flybayer** [comment]
Thank you!
