### ISSUE TITLE
Can't access DEV Server on WSL2 (Windows Subsystem Linux)

### ISSUE THREAD

**Issue by garytube** [blitz-js/blitz#2180]
### What is the problem?

I'm running Ubuntu in a WSL2. 

When i run `blitz run dev` I can't access it via localhost:3000 or 127.0.0.1:3000. I think there is a issue with the network interface binding. #1956

once I added the custom server snippet (https://blitzjs.com/docs/custom-server) everything works like a charm.

BlitzJS is the only framework where I have this issue. NextJS works just fine

### Paste all your error logs here:

localhost:3000 timeout

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1. In WSL2 -> blitz new myapp
2. blitz run dev

### Run `blitz -v` and paste the output here:

Linux 5.4 | linux-x64 | Node: v14.15.1

blitz: 0.33.1 (global)
blitz: 0.33.1 (local)

  Package manager: yarn
  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 6.34 GB / 12.25 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.6.3 - ~/.nvm/versions/node/v14.15.1/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.19 => 2.19.0
    blitz: 0.33.1 => 0.33.1
    prisma: ~2.19 => 2.19.0
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    typescript: ~4.1 => 4.1.5

**Comment by flybayer** [comment]
@garytube two questions:

1. Does `blitz dev --hostname 0.0.0.0` work?
2. In a vanilla next.js project, does `next dev --hostname 127.0.0.1` work?

**Comment by garytube** [comment]
`blitz dev`
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
```
no access 

`blitz dev --hostname 0.0.0.0`
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000  
```
no access 

**NextJS**

 `npx next dev --hostname 127.0.0.1`
```
ready - started server on http://127.0.0.1:3000
```
no access

---- 

In all cases the Server is running just fine. I did a simple `curl -I -X GET http://localhost:3000``  **inside** WSL
```
HTTP/1.1 200 OK
Cache-Control: no-store, must-revalidate
X-Powered-By: Next.js
ETag: "4531-JkKhGIHg5NXiVKbjVKmQ1O/2ibo"
Content-Type: text/html; charset=utf-8
Content-Length: 17713
Vary: Accept-Encoding
Date: Mon, 05 Apr 2021 18:34:01 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

I'm pretty sure it's not directly a blitzJS problem but something is not playing nice.

Any idea what else to check?

PS:
i used blitzJS before (~6 month)  and had no issues.

**Comment by flybayer** [comment]
Hmm that's really weird. We don't change anything about the networking binding except setting a default `hostname` unless you specify it. Do you get any compile errors?

**Comment by garytube** [comment]
found it.

 Powershell: `netsh interface portproxy show all` listed a rouge port proxy was running...    I don't know where that came from but once I deleted it, everything works fine.
 
 sorry @flybayer   ;)

ps:
thank you for all the work


close
