### ISSUE TITLE
Invalidate Query not working on blitz@0.34.0-canary.0

### ISSUE THREAD

**Issue by BjoernRave** [blitz-js/blitz#2184]
### What is the problem?

Queries are not being invalidated correctly on the latestet `canary` version

### Paste all your error logs here:

```

```

### Paste all relevant code snippets here:

```

```

### What are detailed steps to reproduce this?

1. Fetch data
2. use `invalidateQuery` to invalidate results

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v12.16.3

blitz: 0.33.0 (global)
blitz: 0.34.0-canary.0 (local)

  Package manager: npm 
  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 93.27 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/client: 2.20.1 => 2.20.1 
    blitz: 0.34.0-canary.0 => 0.34.0-canary.0 
    prisma: 2.20.1 => 2.20.1 
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    typescript: 4.2.3 => 4.2.3 
```

**Comment by flybayer** [comment]
Hey @BjoernRave, I'm unable to reproduce. I added a working integration test in https://github.com/blitz-js/blitz/pull/2194.

Can you provide a reproduction? Ideally you could update that integration test and submit a failing PR.

After running `yarn build` or `yarn dev` in the repo root, you can run that test with this:

```
yarn testheadless --testPathPattern "integration/queries" -t invalidateQuery
```
