### ISSUE TITLE
blitz command not working in mac

### ISSUE THREAD

**Issue by mauriarmora** [blitz-js/blitz#2187]
### What is the problem?

I installed blitz but the blitz command is not working in the mac terminal, so I cannot do blitz 'new appName'. I tried installing it with sudo, updating node (I have it in version 14.16.0), but still it says: 'command not found: blitz'

### Paste all your error logs here:

```
zsh: command not found: blitz
```

### Paste all relevant code snippets here:

```
 blitz new blitzTesting
```

### What are detailed steps to reproduce this?

1. Install blitz using 'sudo npm install -g blitz'
2. Try creating a new blitz app or use any blitz command

### Run `blitz -v` and paste the output here:

```
I cannot run 'blitz -v' because the blitz command is not working
```

**Comment by Maastrich** [comment]
It might be because you ran npm with sudo, the package is installed for your super user but not for the normal user.
Try running `npm install blitz -g` (or better `yarn global add blitz`)

**Comment by Maastrich** [comment]
I'll mark this issue as close, feel free to reopen it if it is still not resolved

**Comment by shubhsk88** [comment]
I already did that. The problem I am getting when I am generating the model for one to many relationships 
- `blitz generate model user postvotes:Postvote[] `
and it shows that 
```zsh
zsh: no matches found: postvotes:Postvote[]
```

**Comment by MrLeebo** [comment]
@shubhsk88 looks like you're running zsh. By default, it uses square brackets for pattern matching, so when you want to run a command that contains brackets, you will need to escape them (or disable the pattern matching).

```
blitz generate model user postvotes:Postvote\[\]
```

**Comment by flybayer** [comment]
Or do this: `blitz generate model user "postvotes:Postvote[]"`
