### ISSUE TITLE
react-query 3 upgrade doesn't play nicely with Preact Suspense

### ISSUE THREAD

**Issue by wescopeland** [blitz-js/blitz#2191]
### What is the problem?

Up until 0.33.1, Blitz.js and Preact played together perfectly, with no errors or hitches of any kind.

As of 0.34.0-canary.0, Blitz's `useQuery` hook (and probably useMutation, but I haven't tried) appears to be having issues with preact/compat's `<Suspense />` component. The hooks go into infinite loops, unable to resolve their promises.

### Paste all your error logs here:

```
Promise { <pending> }
Promise { <pending> }
Promise { <pending> }
Promise { <pending> }
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
Promise { <pending> }
Promise { <pending> }
Promise { <pending> }
```

### Paste all relevant code snippets here:

```
// Works.
const { userId } = useSession({ suspense: false });

// Causes an infinite loop.
const { userId } = useSession();
```

### What are detailed steps to reproduce this?

1. Use Preact with your Blitz.js app.
2. Use a `useSession` hook somewhere in the code.

A minimal reproduction can be found at https://github.com/wescopeland/preact-blitz-0.34.0-canary.0

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v14.15.5

blitz: 0.33.1 (global)
blitz: 0.34.0-canary.0 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.2.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 292.01 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.5 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @preact/compat:  0.0.4 
    @prisma/client: ~2.20 => 2.20.1 
    blitz: 0.34.0-canary.0 => 0.34.0-canary.0 
    prisma: ~2.20 => 2.20.1 
    react: Not Found
    react-dom: Not Found
    typescript: ~4.2 => 4.2.4 
```

**Comment by flybayer** [comment]
I don't think this has anything to do with react-query. Commenting out the useQuery stuff in `/` and it still doesn't work.

I ran `yarn add blitz@latest` in your repo and removed the query error reset from `_app`. Now I don't see Promiseloading in the terminal, but it's still very much broken. I see the following in the browser console:

```
index.tsx?8abf:516 Uncaught (in promise) TypeError: _reactDom.default.unstable_createRoot is not a function
    at renderReactElement (index.tsx?8abf:516)
    at doRender (index.tsx?8abf:794)
    at renderError (index.tsx?8abf:455)
    at _callee2$ (index.tsx?8abf:436)
    at tryCatch (runtime.js?a89a:63)
    at Generator.invoke [as _invoke] (runtime.js?a89a:293)
    at Generator.eval [as next] (runtime.js?a89a:118)
    at asyncGeneratorStep (asyncToGenerator.js?4db8:3)
    at _next (asyncToGenerator.js?4db8:25)
    at eval (asyncToGenerator.js?4db8:32)
    at new Promise (<anonymous>)
    at eval (asyncToGenerator.js?4db8:21)
    at _render (index.js:519)
    at render (index.js:456)
    at eval (next-dev.js?53bc:85)
    at eval (fouc.js?937a:14)
```

Which seems to point to a preact concurrent mode issue

**Comment by wescopeland** [comment]
Interesting - in my real app I have concurrent mode disabled because I'm using Material UI.

**Comment by flybayer** [comment]
Ok then yeah I think it's a Preact issue that we can't do anything about

**Comment by wescopeland** [comment]
> Ok then yeah I think it's a Preact issue that we can't do anything about

Ok, no worries! I will switch back to React.
