### ISSUE TITLE
Add cli command: blitz test

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#22]
- [ ] `blitz test` should run the `test` script in package.json. 
- [ ] `blitz t` should run `blitz test`
- [ ] Add tests

**Comment by camilo86** [comment]
If still open, I can submit a PR for this later today

**Comment by flybayer** [comment]
Yep, still open. Go for it! @camilo86

**Comment by camilo86** [comment]
Just sent a PR for this issue https://github.com/blitz-js/blitz/pull/30 Let me know what you think
