### ISSUE TITLE
Throw an error if using a query with useMutation or a mutation with useQuery

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#2200]
### What do you want and why?

Throw an error if using a query with useMutation or a mutation with useQuery. These have different expectations and behavior, so we need to throw an error in this case.

### Possible implementation(s)

Split [sanitize](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/utils/react-query-utils.ts#L82) into `sanitizeQuery` and `sanitizeMutation` and add the type check `queryFn._meta.type` should be `query` or `mutation`, so you know which type is actually being passed in.

### Additional context

https://discord.com/channels/802917734999523368/802989186495152149/830524607429476413

**Comment by Mokshit06** [comment]
Hey, I am interested in working on this issue
