### ISSUE TITLE
Rename `types.d.ts` to `global.d.ts` 

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#2201]
### What do you want and why?

`types.ts` and `types.d.ts` sometimes conflict and don't work properly, so we need to rename [types.d.ts](https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/app/types.d.ts) to `global.d.ts`

This is simple, just rename the file.

**Comment by paulm17** [comment]
Can you add:

```
declare module "*.svg" {
  const content: string
  export default content
}
```

So that it's ready for those who will use svg?

**Comment by flybayer** [comment]
@paulm17 yeah we can add that in another PR, but do we actually support svg out of the box? 😅
