### ISSUE TITLE
`CancelledError` when clicking Logout on 0.34.0-canary.3

### ISSUE THREAD

**Issue by malkomalko** [blitz-js/blitz#2207]
### What is the problem?

There's an error with the logout mutation with a fresh project install.  Looks like this is an error after upgrading `react-query`.  I'm not quite sure yet if this is happening for other mutations, but my guess is it might be.

### Paste all your error logs here:

```
| eval | @ | mutation.js?5088:103
| Promise.catch (async) |   |  
| execute | @ | mutation.js?5088:96 `node_modules/react-query/es/core/mutation.js?5088`
| mutate | @ | mutationObserver.js?3317:83 `node_modules/react-query/es/core/mutationObserver.js?3317`
> return this.currentMutation.execute();
| _callee$ | @ | index.tsx?db76:22
> await logoutMutation()
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1. Generate a new project with `0.34.0-canary.3`
2. Sign up
3. Open up dev tools
4. Logout
5. Notice you see a `CancelledError`

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v15.3.0

blitz: 0.34.0-canary.3 (global)
blitz: 0.34.0-canary.3 (local)

  Package manager: yarn
  System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 6.59 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.3.0 - ~/.nvm/versions/node/v15.3.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v15.3.0/bin/yarn
    npm: 7.0.14 - ~/.nvm/versions/node/v15.3.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1
    blitz: 0.34.0-canary.3 => 0.34.0-canary.3
    prisma: ~2.20 => 2.20.1
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    typescript: ~4.2 => 4.2.4
```

**Comment by flybayer** [comment]
Thanks @malkomalko. I see this too, but everything is functioning properly. Not sure why it's happening. Maybe in `rpc-client` under the `HEADER_SESSION_REVOKED` section we need to first "cancel" all queries before running `queryClient.clear()`

**Comment by malkomalko** [comment]
The mutation works, but if you want to redirect after a logout, it won't do that redirect until a refresh.  For now you have to catch it.  I'll try to dig in here a bit.

**Comment by flybayer** [comment]
oh, ok yeah not so good then

**Comment by rodrigoehlers** [comment]
I'm having the exact same problem. Wrapping the call to `signOutMutation` in a `try`/`catch` block, therefore completing the following call to `router.push` fixes it for now. I've started seeing this behaviour since I upgraded my project to the latest release which at time of writing is `0.34.3`.

**Comment by acornellier** [comment]
I'm getting the exact same thing on 0.34.3
