### ISSUE TITLE
Ability to increase bodyParse sizeLimit inside a mutation

### ISSUE THREAD

**Issue by Swapnull** [blitz-js/blitz#2210]
### What do you want and why?
I want to be able to increase the bodyParser sizeLimit in a mutation. 
I am trying to create a file upload on my project and the mutation works great until I try to use a file above 1mb and we hit a `Error: Body exceeded 1mb limit` error. 

Although this is achievable by using a custom api route, I have managed to do everything else with `useMutation` and `useQuery` so far in my project, so it would be odd to switch over to a `fetch` style mutation for this specific reason. The high number of different ways you do the same task, the more confusing the code becomes. 

### Possible implementation(s)
The solution would hopefully be in the same vein as what we have already on API routes. 
```
export const config = {
  api: {
    bodyParser: {
      sizeLimit: "2mb",
    },
  },
};
```
### Additional context

I asked this question on Discord https://discord.com/channels/802917734999523368/814628067788062750/829659097917423627 and was informed "There's currently no way to do that, but you can open an issue for it. Workaround is to use a custom API route"

**Comment by flybayer** [comment]
Thanks! I'll keep this in mind with the nextjs fork integration. I should be able to add this at the same time.
