### ISSUE TITLE
Add better `select` support for resolvers

### ISSUE THREAD

**Issue by oceandrama** [blitz-js/blitz#2211]
### What do you want and why?

Now you can pass `select` option from `Prisma` API to your resolvers and it works well
```ts
import {Ctx} from "blitz"
import db, {Prisma} from "db"

interface GetUsersInput
  extends Pick<Prisma.UserFindManyArgs, "where" | "orderBy" | "skip" | "take" | "select"> {}

async function getUsers(input: GetUsersInput, ctx: Ctx) {
  return db.users.findMany(input)
}
```

```ts
const [users] = useQuery(getUsers, {select: {id: true}})
// users: [{id: 1}, {id: 2}]
```
But the type of users will always be `User[]`, no matter what you pass in `select` option
Even if just call `getUser` without `useQuery`
```ts
const users = await getUsers({select: {id: true})
// users: [{id: 1}, {id: 2}], but the type is still User[]
```

You can improve you typings like this
```ts
import {Ctx} from "blitz"
import db, {Prisma} from "db"

interface GetUsersInput<S extends Prisma.UserSelect>
  extends Pick<Prisma.UserFindManyArgs, "where" | "orderBy" | "skip" | "take"> {
  select: S
}

export default async function getUsers<S extends Prisma.UserSelect>(
  input: GetUsersInput<S>,
  ctx: Ctx
) {
  return db.user.findMany<{ select: S } & Omit<Prisma.UserSelect, "select" | "include">>(input)
}
```
Now, if you call `getUsers` directly, it will work
```ts
const users = await getUsers({select: {id: true})
// users: [{id: 1}, {id: 2}], and the type is {id: number}[]
```

But if you call it in `useQuery` result type will be `{}[]`
```ts
const [users] = useQuery(getUsers, {select: {id: true}})
// users: [{id: 1}, {id: 2}], but the type is {}[]
```
### Possible implementation(s)

I don't know does `react-query` support generic parameters, but it will be great to support `select` options in you resolvers and and it to new application template

### Additional context

The comment with Prisma `findMany` generic typings
https://github.com/prisma/prisma/issues/3372#issuecomment-773195871

**Comment by flybayer** [comment]
Thanks @oceandrama. Here's our useQuery hook: https://github.com/blitz-js/blitz/blob/canary/packages/core/src/use-query-hooks.ts#L33. We already use a generic, so I'm not sure if it's possible with current Typescript to make what you want. If it's possible, then we can certainly do it.

However, a word of caution, if you are allowing `select` from the frontend, you need to add a `zod` input schema for your query to only allow selecting certain fields. Otherwise anyone could select private fields like password, token, etc.

**Comment by veigamann** [comment]
@oceandrama any updates on this? did you manage to get correct typings with `useQuery`?

**Comment by flybayer** [comment]
This is a limitation of typescript. Sadly, nothing we can do to fix it.
