### ISSUE TITLE
Generators don't support string IDs

### ISSUE THREAD

**Issue by shubhsk88** [blitz-js/blitz#2215]
### What is the problem?

In order to ensure more safety on the user id. I tried to change the `Id` to `cuid` mode .But that changes is not reflecting in my future relationship models and it is still taking the reference as `Int` in the other models 

### Paste all your error logs here:

`blitz generate resource subscription belongsTo:user belongsTo:community isFavourite:boolean:default=false`

### Paste all relevant code snippets here:

`blitz generate resource subscription belongsTo:user belongsTo:community isFavourite:boolean:default=false`

### What are detailed steps to reproduce this?

1.Change the User id in schema model to string
2. try to run the `blitz generate resource subscription belongsTo:user belongsTo:community isFavourite:boolean:default=false`
3. It will still show the Prisma schema in the relationship  ` userId Int`

### Run `blitz -v` and paste the output here:

```
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

macOS Big Sur | darwin-x64 | Node: v14.15.4

blitz: 0.33.1 (local)

  Package manager: yarn
  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Apple M1
    Memory: 248.53 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.volta/tools/image/node/14.15.4/bin/node
    Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
    npm: 6.14.10 - ~/.volta/tools/image/node/14.15.4/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: ^4.2.4 => 4.2.4
```

**Comment by flybayer** [comment]
Yeah, this is a known issue. Generators don't yet support string id's, sorry about that
