### ISSUE TITLE
session not working when putting in production

### ISSUE THREAD

**Issue by karimsx** [blitz-js/blitz#2216]
### What is the problem?

After setting up my project in local, i pushed my code to a vps and used it as a server.

everything work as expected but authentication, specifically, when i try to login, the authentication process go well, user is fetched with correct password, and is redirected. but after been redirect to the correct page, the user is  redirect again to login page as if is was not logged in  (because of page required authentication `page.authenticate = true`).

i think its something going on with the session, i couldn't find any problem because the same code is working locally with `blitz dev` and `blitz start`

in the server console, there wasn't any error, but authentication error.

it will be easier if you check this video :

https://streamable.com/f3yclg

### Paste all your error logs here:

```react_devtools_backend.js:2556 t: You must be logged in to access this```

### Paste all relevant code snippets here:

Login Mutation
```
import { AuthenticationError, resolver, SecurePassword } from "blitz"
import db from "db"
import { LoginZ } from "../validations"
import { Role } from "types"

export const authenticateUser = async (rawEmail: string, rawPassword: string) => {
  const email = rawEmail.toLowerCase().trim()
  const password = rawPassword.trim()
  const user = await db.user.findFirst({ where: { email } })
  if (!user) throw new AuthenticationError("invalid username password")

  const result = await SecurePassword.verify(user.hashedPassword, password)

  if (result === SecurePassword.VALID_NEEDS_REHASH) {
    // Upgrade hashed password with a more secure hash
    const improvedHash = await SecurePassword.hash(password)
    await db.user.update({ where: { id: user.id }, data: { hashedPassword: improvedHash } })
  }

  const { hashedPassword, ...rest } = user
  return rest
}

export default resolver.pipe(resolver.zod(LoginZ), async ({ email, password }, ctx) => {
  // This throws an error if credentials are invalid
  const user = await authenticateUser(email, password)

  await ctx.session.$create({ userId: user.id, role: user.role as Role })

  return user
})

```

Custom server

```
const { createServer } = require("http")
const { parse } = require("url")
const blitz = require("blitz/custom-server")

const dev = process.env.NODE_ENV !== "production"
const app = blitz({ dev })
const handle = app.getRequestHandler()

app.prepare().then(() => {
  createServer((req, res) => {
    // Be sure to pass `true` as the second argument to `url.parse`.
    // This tells it to parse the query portion of the URL.
    const parsedUrl = parse(req.url, true)
    const { pathname, query } = parsedUrl

    handle(req, res, parsedUrl)
  }).listen(3000, (err) => {
    if (err) throw err
    console.log("> Ready on http://localhost:3000")
  })
})

```

### What are detailed steps to reproduce this?

1. put blitz on a vps with this custom server/mutation

### Run `blitz -v` and paste the output here:

```
blitz: 0.33.1 (local)

  Package manager: yarn 
  System:
    OS: Linux 5.10 Manjaro Linux
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 1.32 GB / 15.62 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.0/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.19 => 2.19.0 
    blitz: 0.33.1 => 0.33.1 
    prisma: ~2.19 => 2.19.0 
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    typescript: ~4.1 => 4.1.5 


```

**Comment by MrLeebo** [comment]
Hi @karimsx, it looks like your production URL is being served insecurely over HTTP, instead of HTTPS. The auth token is stored in a secure cookie, so it will not be used for insecure connections.

Make sure your authenticated routes are served as HTTPS so the session information can't be intercepted and stolen while it's on its way been the server and the client.

**Comment by karimsx** [comment]
Hey @MrLeebo, i see, for the moment, i'm using the vps as a development server to work with my client, is there anyway to bypass it temporarily while waiting for the website domain/ssl ?

Thanks you for you fast and precise response ;)

**Comment by MrLeebo** [comment]
You can set the environment variable `DISABLE_SECURE_COOKIES=true` to [disable](https://github.com/blitz-js/blitz/blob/563720bb5798b0c43d6858ffe502d19d78be1c5b/packages/core/src/server/auth/sessions.ts#L491) it.
