### ISSUE TITLE
Deployment on vercel fails for canary.4 / y.0

### ISSUE THREAD

**Issue by sakulstra** [blitz-js/blitz#2225]
### What is the problem?

I just tested the new canary as i wanted to checkout the cool new things that happened since canary.0, but I started facing problems on deployment. In essence it does no loner work on vercel at all. Downgrading to a canary.0 fixes the issue again.

### Paste all your error logs here:

```
```
20:58:53.591 | https://nextjs.org/telemetry
-- | --
20:59:04.458 | info  - Creating an optimized production build...
20:59:04.904 | info  - Using external babel configuration from /vercel/path0/babel.config.js
20:59:30.085 | warn  - Compiled with warnings
20:59:30.095 | /vercel/path0/node_modules/next/dist/next-server/server/load-components.js
20:59:30.095 | Critical dependency: the request of a dependency is an expression
20:59:30.096 | /vercel/path0/node_modules/next/dist/next-server/server/load-components.js
20:59:30.096 | Critical dependency: the request of a dependency is an expression
20:59:30.096 | /vercel/path0/node_modules/next/dist/next-server/server/require.js
20:59:30.096 | Critical dependency: the request of a dependency is an expression
20:59:30.096 | /vercel/path0/node_modules/next/dist/next-server/server/require.js
20:59:30.096 | Critical dependency: the request of a dependency is an expression
20:59:30.096 | /vercel/path0/node_modules/next/dist/next-server/server/require.js
20:59:30.096 | Critical dependency: the request of a dependency is an expression
20:59:30.096 | /vercel/path0/node_modules/@prisma/client/runtime/index.js
20:59:30.096 | Critical dependency: the request of a dependency is an expression
20:59:30.097 | /vercel/path0/node_modules/@ethersproject/providers/node_modules/ws/lib/buffer-util.js
20:59:30.097 | Module not found: Can't resolve 'bufferutil' in '/vercel/path0/node_modules/@ethersproject/providers/node_modules/ws/lib'
20:59:30.097 | /vercel/path0/node_modules/@genql/runtime/node_modules/ws/lib/buffer-util.js
20:59:30.097 | Module not found: Can't resolve 'bufferutil' in '/vercel/path0/node_modules/@genql/runtime/node_modules/ws/lib'
20:59:30.097 | /vercel/path0/node_modules/subscriptions-transport-ws/node_modules/ws/lib/buffer-util.js
20:59:30.097 | Module not found: Can't resolve 'bufferutil' in '/vercel/path0/node_modules/subscriptions-transport-ws/node_modules/ws/lib'
20:59:30.097 | /vercel/path0/node_modules/@ethersproject/providers/node_modules/ws/lib/validation.js
20:59:30.097 | Module not found: Can't resolve 'utf-8-validate' in '/vercel/path0/node_modules/@ethersproject/providers/node_modules/ws/lib'
20:59:30.097 | /vercel/path0/node_modules/@genql/runtime/node_modules/ws/lib/validation.js
20:59:30.097 | Module not found: Can't resolve 'utf-8-validate' in '/vercel/path0/node_modules/@genql/runtime/node_modules/ws/lib'
20:59:30.097 | /vercel/path0/node_modules/subscriptions-transport-ws/node_modules/ws/lib/validation.js
20:59:30.097 | Module not found: Can't resolve 'utf-8-validate' in '/vercel/path0/node_modules/subscriptions-transport-ws/node_modules/ws/lib'
20:59:30.097 | info  - Collecting page data...
20:59:31.248 | > Build error occurred
20:59:31.248 | Error: No native build was found for platform=linux arch=x64 runtime=node abi=83 uv=1 libc=glibc node=14.15.4 webpack=true
20:59:31.248 | loaded from: /
20:59:31.248 | at Function.module.exports.Kuq/.load.path (/vercel/path0/.next/serverless/pages/deposits.js:72238:9)
20:59:31.249 | at load (/vercel/path0/.next/serverless/pages/deposits.js:72200:30)
20:59:31.249 | at Object.<anonymous> (/vercel/path0/.next/serverless/pages/deposits.js:195840:90)
20:59:31.249 | at Object.s4Il (/vercel/path0/.next/serverless/pages/deposits.js:195844:30)
20:59:31.249 | at __webpack_require__ (/vercel/path0/.next/serverless/pages/deposits.js:23:31)
20:59:31.249 | at Object.tp+b (/vercel/path0/.next/serverless/pages/deposits.js:199620:14)
20:59:31.249 | at __webpack_require__ (/vercel/path0/.next/serverless/pages/deposits.js:23:31)
20:59:31.249 | at Object.Xd3h (/vercel/path0/.next/serverless/pages/deposits.js:119188:25)
20:59:31.249 | at __webpack_require__ (/vercel/path0/.next/serverless/pages/deposits.js:23:31)
20:59:31.249 | at Object.iDoL (/vercel/path0/.next/serverless/pages/deposits.js:156491:20) {
20:59:31.249 | type: 'Error'
20:59:31.249 | }
20:59:31.415 | error Command failed with exit code 1.
20:59:31.415 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
20:59:31.441
```
```

### Paste all relevant code snippets here:

There are no relevant code snippets.

### What are detailed steps to reproduce this?

1. deploy a app with latest blitz canary to vercel.

### Run `blitz -v` and paste the output here:

```
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

Linux 5.4 | linux-x64 | Node: v12.14.0

blitz: 0.33.0 (global)
blitz: 0.34.0-y.0 (local)

  Package manager: yarn 
  System:
    OS: Linux 5.4 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 886.68 MB / 15.52 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v12.14.0/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.21.0 => 2.21.0 
    blitz: 0.34.0-y.0 => 0.34.0-y.0 
    prisma: 2.21.0 => 2.21.0 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: 4.1.2 => 4.1.2 
```

I tested on canary .4 as well facing the exact same issue.

**Comment by flybayer** [comment]
Thanks @sakulstra I'll fix

**Comment by flybayer** [comment]
Fixed in https://github.com/blitz-js/blitz/releases/tag/v0.34.0-canary.5

**Comment by sakulstra** [comment]
wow, what a response time <3, thx a lot!

**Comment by flybayer** [comment]
Please tell my boss, maybe I'll get a promotion 😂
