### ISSUE TITLE
Getting "ReferenceError: questionId is not defined" when following the official tutorial

### ISSUE THREAD

**Issue by RageBill** [blitz-js/blitz#2229]
### What is the problem?

I was following the tutorial up until the end of [this point](https://blitzjs.com/docs/tutorial#delete-question-mutation). When going to the route `localhost:3000/questions`, an error shows up. The code generated by following the tutorial was obviously different from the example snippets shown in the tutorial.

### Paste all your error logs here:

```
Unhandled Runtime Error
ReferenceError: questionId is not defined
```

### Paste all relevant code snippets here:

```

  23 | {questions.map((question) => (
  24 |   <li key={question.id}>
> 25 |     <Link href={Routes.ShowQuestionPage({ [questionId]: question.id })}>
     |                                           ^
  26 |       <a>{question.text}</a>
  27 |     </Link>
  28 |   </li>
```

### What are detailed steps to reproduce this?

1. Follow every steps in [tutorial](https://blitzjs.com/docs/tutorial).
2. The generated Question page was obviously different from [what is shown in the tutorial](https://blitzjs.com/docs/tutorial#question-pages).
3. The above error is shown when following the tutorial up until the end of [this point](https://blitzjs.com/docs/tutorial#delete-question-mutation), right when going to the route `localhost:3000/questions`.

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-arm64 | Node: v15.14.0

blitz: 0.34.0 (global)
blitz: 0.34.0 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
    Memory: 718.41 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.14.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.7.6 - /opt/homebrew/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1 
    blitz: 0.34.0 => 0.34.0 
    prisma: ~2.20 => 2.20.1 
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    typescript: ~4.2 => 4.2.4 

```

**Comment by RageBill** [comment]
Figured I could change `[questionId]: question.id` to `questionId: question.id` and also update the Routes Manifest types as suggested in [this PR](https://github.com/blitz-js/blitz/pull/2228) to get this problem fixed.

**Comment by flybayer** [comment]
@RageBill how did you get the code of `Routes.ShowQuestionPage({ [questionId]: question.id })}` with the `[]`s in there?

**Comment by RageBill** [comment]
@flybayer I believe it is from this command: `blitz generate all question text:string`. I was simply following the tutorial step-by-step.

**Comment by malkomalko** [comment]
Fixing here: https://github.com/blitz-js/blitz/pull/2245.
