### ISSUE TITLE
Scaffold initial Blitz GUI

### ISSUE THREAD

**Issue by merelinguist** [blitz-js/blitz#223]
**What do you want and why do you want it?.**
After conversations in Slack around the GUI, I would like to implement the basic architecture for our GUI, allowing other work to start around it.

**Possible implementation(s)**
Naturally, we should of course use Blitz. I definitely think we should not try to mess around with Electron et al; not only would it likely add extra bugs and performance costs, it seems like it would be a big complicating factor for development, raising extra questions like distribution and updates. To me, the logical thing seems to be to just expose the gui as a command from our cli. This is what, for example, Prisma does for Prisma Studio.

This would look something like:

```sh
$ blitz gui

Starting Blitz GUI...

✨ Done. Open http://localhost:4000 to start building your app.
```

From this point, the user should essentially never have to touch the command line. They could generate new parts of their app, perhaps edit their schema, and even update their local install of Blitz through the interface.

**Additional context**

Juan has done a great job designing [some initial screens](https://www.figma.com/file/DT6brjOLyh95TXRnfcU3gB/Blitz-GUI?node-id=0%3A1&viewport=513%2C432%2C0.17566201090812683). @quirk0o is also interested in some of the design behind the GUI.

**Comment by Zeko369** [comment]
Do you have some code already setup?

**Comment by merelinguist** [comment]
@Zeko369 I have been playing around with it yes. I will PR something relatively soon, which you can review if you’d like. Also, if you’re keen to work on this, I’ll probably need some help integrating with the CLI once I’ve done the initial stuff. Look out for some issues 😄

**Comment by Zeko369** [comment]
@merelinguist can't wait
