### ISSUE TITLE
Can't use pgbouncer for database migrations

### ISSUE THREAD

**Issue by edgarasben** [blitz-js/blitz#2230]
### What is the problem?

Everytime I want to do a database migration I have to switch from pgbourcer connection string to a regular postgres and back to pgbouncer after the migration.

It's time consuming and prone to error when you have to switch every time.

It seems to be the Prima issue [#6485](https://github.com/prisma/prisma/issues/6485).

Does this have to be solved in Prisma first or is it possible to mitigate it on Blitz level?

### Paste all your error logs here:

```
Error: Database error: Error querying the database: db error: ERROR: unexpected response from login query
   0: sql_migration_connector::flavour::postgres::sql_schema_from_migration_history
             at migration-engine/connectors/sql-migration-connector/src/flavour/postgres.rs:270
   1: sql_migration_connector::sql_database_migration_inferrer::calculate_drift
             at migration-engine/connectors/sql-migration-connector/src/sql_database_migration_inferrer.rs:57
   2: migration_core::api::DevDiagnostic
             at migration-engine/core/src/api.rs:97
```

### Paste all relevant code snippets here:

```
-
```

### What are detailed steps to reproduce this?

1. Edit `.env.local` and add `postgres://postgres:XXX@YYY:6543/postgres?pgbouncer=true` (where XXX is password and YYY is database name)
2. Run initial migration `blitz prisma migrate dev`
3. Migration will fail (error pasted above).
4. Go to `.env.local` again and switch to a regular postgres: `postgres://postgres:XXX@YYY:5432`
5. Run the migration again and it works fine.

I have to do the switch every time I want to do a migration.

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v14.15.1

blitz: 0.33.1 (global)
blitz: 0.33.1 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 313.02 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 7.8.0 - ~/.nvm/versions/node/v14.15.1/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.19 => 2.19.0 
    blitz: 0.33.1 => 0.33.1 
    prisma: ~2.19 => 2.19.0 
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    typescript: ~4.1 => 4.1.5 
```

**Comment by flybayer** [comment]
Interesting, I thought this worked fine for me in the past. Maybe Prisma changed this.

Do you have an idea for how Blitz could help with this?

**Comment by flybayer** [comment]
> Ideally this was not needed at all, and Blitz could figure out how to modify the string for migration (like removing pg bouncer part and changing the port). But I am not an expert at this.

I don't think this is possible, because the pgbouncer url is totally different than the direct DB connection. It's not just the port and query param that's different.

**Comment by edgarasben** [comment]
I thought so. In my case that was actually the only difference.

**Comment by flybayer** [comment]
@edgarasben ok interesting. We definitely couldn't rely on that because most of the time they are totally different.

**Comment by edgarasben** [comment]
Understood.

> I think Jan had a great idea in the Prisma issue I mentioned. "Set a different ENV var value only when running Migrate" e.g. PRISMA_MIGRATIONS_URL.
Would this be an elegant enough solution?

**Comment by flybayer** [comment]
@edgarasben yeah we could add `EXPERIMENTAL_PRISMA_MIGRATION_URL` as a workaround until Prisma finds a solution

**Comment by edgarasben** [comment]
@flybayer I guess that would save some manual work for everyone every time migrating schema while using pgbouncer.

**Comment by flybayer** [comment]
We haven't had any other requests for this, so going to close. Can revist if we get more demand.

**Comment by jelling** [comment]
Here's how I handle the mirgation mode vs production mode issue for PgBouncer. I'm using Heroku and they set the PgBouncer url as `DATABASE_CONNECTION_POOL_URL`  and the regular db string is in `DATABASE_URL`.

So my `schema.prisma` uses the PgBouncer config looks this;

```
datasource db {
  provider = "postgres"
  url      = env("DATABASE_CONNECTION_POOL_URL")
}
```

And the `migrate` command in `package.json` looks like below, overwriting the default bouncer connection string with the non-bouncer string at runtime.

```
{
    "migrate": "DATABASE_CONNECTION_POOL_URL=$DATABASE_URL blitz prisma migrate dev",
}
```
