### ISSUE TITLE
useQuery runs in infinite loop when query throws AuthenticationError

### ISSUE THREAD

**Issue by remjx** [blitz-js/blitz#2233]
### What is the problem?

`useQuery` gets called in an infinite loop if query throws `AuthenticationError`

### Paste all your error logs here:

Server is flooded with:
```
19:07:53.309 ERROR getUser()
 AuthenticationError  You must be logged in to access this
details:
{
  name: 'AuthenticationError',
  statusCode: 401
}
```

Note: `getUser` is just an arbitrary query that throws `AuthenticationError`

### Paste all relevant code snippets here:

See replication details below

### What are detailed steps to reproduce this?

The issue is replicated on this branch in the `examples/auth` example: https://github.com/remjx/blitz/tree/issue-replication/usequery-infinite-loop/examples/auth 
Use compare view to see the changes I made to replicate the issue: https://github.com/blitz-js/blitz/compare/canary...remjx:issue-replication/usequery-infinite-loop

Replication steps: 

1. Add a `useQuery` hook in a component 
```
const [data] = useQuery(getUser, { where: { id: session.userId || undefined }})
```

2. In the query, run `ctx.session.$authorize()`
3. `npm run dev` and log in to the app. The query will be called successfully.
4. Try to log out of the app. It gets caught in suspense and server logs are flooded as the query is called in an infinite loop.

### Run `blitz -v` and paste the output here:

```
Windows 10 | win32-x64 | Node: v14.6.0

blitz: 0.34.0 (global)
blitz: 0.34.0 (local)

  Package manager: npm
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 4800HS with Radeon Graphics
    Memory: 3.01 GB / 15.42 GB
  Binaries:
    Node: 14.6.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.19.0 => 2.19.0
    blitz: 0.34.0 => 0.34.0
    prisma: 2.19.0 => 2.19.0
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    typescript: 4.1.5 => 4.1.5
```

**Comment by flybayer** [comment]
@remjx I'm unable to reproduce in auth example 😐 

I've also added an auth integration test in https://github.com/blitz-js/blitz/pull/2240.

Would you be able to try and update that integration test with a failing test case for this?
