### ISSUE TITLE
No MutationFunction after upgrading to 0.34

### ISSUE THREAD

**Issue by DLevai94** [blitz-js/blitz#2234]
### What is the problem?

Can't build Blitz project after upgrading to 0.34, because it can't find the `MutationFunction` type.

### Paste all your error logs here:

```
Type error: Module '"blitz"' has no exported member 'MutationFunction'.
```

### Paste all relevant code snippets here:

```
import { Ctx, MutationFunction } from 'blitz';
```

### What are detailed steps to reproduce this?

1. Upgrade Blitz project to 0.34

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v12.22.1

blitz: 0.33.0 (global)
blitz: 0.34.0 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Apple M1
    Memory: 267.71 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.6.0 - /opt/homebrew/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.21.2 => 2.21.2 
    blitz: 0.34.0 => 0.34.0 
    prisma: 2.21.2 => 2.21.2 
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    typescript: 4.2.4 => 4.2.4 
```

**Comment by flybayer** [comment]
How were you using that type?

**Comment by DLevai94** [comment]
> How were you using that type?

`const createProject: MutationFunction<Project, CreateProjectInput> = async ({ data }, ctx: Ctx) => {`

**Comment by flybayer** [comment]
@DLevai94 ah, that type was actually for something else.

Instead of that use `import {Resolver} from 'blitz'` and use it instead (same signature)
