### ISSUE TITLE
"Invalid Hook Call" from React when installing Styled Components Recipe

### ISSUE THREAD

**Issue by andyshand** [blitz-js/blitz#2237]
### What is the problem?

When creating a new Blitz.js project with `blitz new` and then installing the Styled Components recipe with `blitz styled-components`, the following error is shown in the console. 

This appears to prevent Styled Components from working properly too.

### Paste all your error logs here:

```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

### Paste all relevant code snippets here:

N/A

### What are detailed steps to reproduce this?

1. `blitz new projectname`
2. `blitz install styled-components`
3. `blitz dev`

### Run `blitz -v` and paste the output here:

```
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

macOS High Sierra | darwin-x64 | Node: v14.16.0

blitz: 0.34.0 (global)
blitz: 0.34.0 (local)

  Package manager: yarn 
  System:
    OS: macOS High Sierra 10.13.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 1.20 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.0/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1 
    blitz: 0.34.0 => 0.34.0 
    prisma: ~2.20 => 2.20.1 
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    typescript: ~4.2 => 4.2.4 
```

**Comment by flybayer** [comment]
Well @andyshand, I looked into this and it appears to be a bug with styled-components.

See https://github.com/styled-components/styled-components/issues/3394 and https://github.com/styled-components/styled-components/issues/3409.

So as far as I can tell, there's not much we can do besides using an older version of react experimental
