### ISSUE TITLE
Blitz repository inaccessible on Windows

### ISSUE THREAD

**Issue by wKovacs64** [blitz-js/blitz#224]
**What is the problem?**

Windows users can no longer pull in changes (or perform a fresh clone) as of #187 being merged due to invalid characters in some of the template filenames.

```
error: invalid path 'packages/cli/templates/mutation/create<%= ModelName %>.ts.ejs'
error: invalid path 'packages/cli/templates/mutation/delete<%= ModelName %>.ts.ejs'
error: invalid path 'packages/cli/templates/mutation/update<%= ModelName %>.ts.ejs'
error: invalid path 'packages/cli/templates/query/get<%= ModelName %>.ts.ejs'
```

**Steps to Reproduce:**

1. `git clone git@github.com:blitz-js/blitz.git` on Windows 10

**Versions:**

N/A

**Supporting Documentation**

https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

**Comment by flybayer** [comment]
@aem

**Comment by aem** [comment]
Oof. I guess we could use the same strategy I used with the `[id]` directories and use a custom placeholder rather than the built-in yeoman template functionality. `create__ModelName__.ts` can be transformed with something like this:

```js
const matches = path.match(/__([\w]*)__/)
const templateValue = matches[1] || ''
path.replace(`__${templateValue}__`, this.options[templateValue])
```

Seem reasonable?

**Comment by aem** [comment]
I can make this change later today, or if we have someone who's new to the Slack and wants to contribute, this is a great first issue for someone interested in the CLI. Relatively small change, but touches a few different pieces of the generator architecture
