### ISSUE TITLE
Blitz needs to restart after schema change and CRUD generated

### ISSUE THREAD

**Issue by osirvent** [blitz-js/blitz#225]
**What is the problem?**

`TypeError: Cannot read property 'findMany' of undefined` after schema changed and CRUD
generated

**Steps to Reproduce:**

1. Follow initial example (User Model and generate CRUD for user)
2. With `blitz` started, add a new model on the schema (i.e. `Comment`) .
3. `blitz db migrate`
4. `blitz generate all comment`
5. go to http://localhost:3000/comments
6. appears `TypeError: Cannot read property 'findMany' of undefined` error on the browser
7. appears `> Running getComments(null)
✕ getComments failed: TypeError: Cannot read property 'findMany' of undefined` on the console
8. Restart Blitz
9. Everything OK

**Versions:**

```
debug: local
debug: pkgPath: /Users/osirvent/dev/blitzjs/tests/test2/node_modules/@blitzjs/cli

macOS Catalina darwin-x64 node-v12.16.2

blitz: 0.6.2 (global)
blitz: 0.6.2 (local)
```

**Supporting Documentation**
`×TypeError: Cannot read property 'findMany' of undefined
getComments
./app/_rpc/comments/queries/getComments.ts:4

  1 | import db, {FindManyCommentArgs} from 'db'
  2 | 
  3 | export default async function getComments(args: FindManyCommentArgs) {
> 4 |   const comments = await db.comment.findMany(args)
  5 | 
  6 |   return comments
  7 | }

    at /Users/osirvent/dev/blitzjs/tests/test2/node_modules/
blitzjs/server/dist/server.cjs.development.js:1610:34
    at _catch (/Users/osirvent/dev/blitzjs/tests/test2/node_modules/
blitzjs/server/dist/server.cjs.development.js:1566:18
    at /Users/osirvent/dev/blitzjs/tests/test2/node_modules/
blitzjs/server/dist/server.cjs.development.js:1609:32
apiResolver
/Users/osirvent/dev/blitzjs/tests/test2/node_modules/next/dist/next-server/server/api-utils.js:46:15
processTicksAndRejections
internal/process/task_queues.js:97:5
async DevServer.handleApiRequest
/Users/osirvent/dev/blitzjs/tests/test2/node_modules/next/dist/next-server/server/next-server.js:464:9
async Object.fn
/Users/osirvent/dev/blitzjs/tests/test2/node_modules/next/dist/next-server/server/next-server.js:386:37
async Router.execute
/Users/osirvent/dev/blitzjs/tests/test2/node_modules/next/dist/next-server/server/router.js:134:32
async DevServer.run
/Users/osirvent/dev/blitzjs/tests/test2/node_modules/next/dist/next-server/server/next-server.js:506:29
async DevServer.handleRequest
/Users/osirvent/dev/blitzjs/tests/test2/node_modules/next/dist/next-server/server/next-server.js:150:20
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.`

---

# How To Fix

See https://github.com/blitz-js/blitz/issues/225#issuecomment-704596217

**Comment by aem** [comment]
if we can either find a JS tool similar to [entr](http://eradman.com/entrproject/) or leverage `nodemon` somehow it should be pretty easy to restart the sevrer there. Or maybe even reuse some logic from the synchronizer to detect changes? @ryardley thoughts?

**Comment by ryardley** [comment]
So just reading this I would say the issue is that because prisma generates new types etc. and they aren't loaded into next. Perhaps we can flag certain file changes (`prisma.schema` perhaps?) as tabling a restart of next?

**Comment by flybayer** [comment]
I suspect this is because prisma client is inside node_modules and Next doesn't expect files in there to change.

Maybe we only need to modify the webpack config?

**Comment by ryardley** [comment]
If we can get away with only modifying watched files in webpack then that would be simpler as to be reactive we would want to setup something that looks like a "next manager" to listen for a specific event and restart the server.

**Comment by flybayer** [comment]
Related #426

**Comment by clearink** [comment]
Is there a solution?

**Comment by flybayer** [comment]
@clearink I think the original issue might be fixed. But regardless, I'm sure there's a way to fix it. No-one has had time to dig into it yet, but anyone is welcome to do so!

Our current new app template has this in `db/index.ts`

```ts
let prisma: PrismaClient

if (process.env.NODE_ENV === "production") {
  prisma = new PrismaClient()
} else {
  // Ensure the prisma instance is re-used during hot-reloading
  // Otherwise, a new client will be created on every reload
  global["prisma"] = global["prisma"] || new PrismaClient()
  prisma = global["prisma"]
}

export default prisma
```

That is so that we don't run out of too many db connections during hot code reloading in dev. But I think that also may prevent reloading the schema without a restart.

Could you try removing that and see if a restart if still needed for schema changes?

**Comment by flybayer** [comment]
Solution is to add https://github.com/williamluke4/next-prisma-plugin to our [`withBlitz`](https://github.com/blitz-js/blitz/blob/canary/packages/server/src/with-blitz.ts) webpack wrapper and to remove the `globalThis` stuff from [the new app template](https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/app/db/index.ts).

**Comment by tconroy** [comment]
Hey @flybayer 👋  it seems the `globalThis` stuff has been removed from the app template since this ticket was originally opened. Does that mean the only remaining step is to add the `next-prisma-plugin` to `withBlitz`? Have a branch locally with that change, happy to push it up. :-)

**Comment by flybayer** [comment]
Hey @tconroy, I haven't added `next-prisma-plugin` yet because it's still experimental from prisma and I don't know if it works with webpack 5. Also it doesn't it with our `globalThis` caching which we still do inside `enhancePrisma`.

So need to test that prisma plugin with webpack 5 plus change it to work with `globalThis`.
