### ISSUE TITLE
Tests fail when upgrading to 0.34.1 (Prisma version mismatch?)

### ISSUE THREAD

**Issue by dmin** [blitz-js/blitz#2254]
### What is the problem?

I just upgraded my Blitz app to `0.34.1` (from `0.33.0`), following all instructions for breaking changes. After upgrading, all tests were failing (just the default app template tests, I have not added any). I re-read the release notes and noticed that version `0.33.1` upgraded Prisma to `2.19` in the app template. Doing the same in my app fixed the problem.

I didn't dig any deeper, but wanted to share the issue, as it might be worth including Prisma version changes in the breaking changes instructions.

Thanks for all the great work on Blitz - it's been a pleasure to work with!

### Paste all your error logs here:

```
PASTE_HERE (leave the ``` marks)
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
PASTE_HERE (leave the ``` marks)
```

**Comment by flybayer** [comment]
Thanks @dmin, I just added a note to the 0.33.1 release about that.
