### ISSUE TITLE
Add required arguments to create query validation when using blitz generate all

### ISSUE THREAD

**Issue by agustif** [blitz-js/blitz#2257]
### What do you want and why?
I would like zod validations to be auto-generated too
The more information the better!

so when running:
`blitz generate all photo name:string slug:string
```js
const CreatePhoto = z
  .object({
    name: z.string(),
    slug: z.string(),,
  })
  .nonstrict()
```

Instead of 

```js
const CreatePhoto = z
  .object({
    name: z.string()
  })
  .nonstrict()
```

So an app compiles after generator run, maybe this has been discarded bc bad idea idk, couldn't find any issue about it

**Comment by flybayer** [comment]
This will be fixed by https://github.com/blitz-js/blitz/pull/2134!

**Comment by MrLeebo** [comment]
Closing this as a duplicate of the linked PR
