### ISSUE TITLE
Default image optimizator causes error on `blitz export` (even if it's not used)

### ISSUE THREAD

**Issue by ormarek** [blitz-js/blitz#2279]
### What is the problem?

Been just wandering through options in Blitz.js CLI and typed `blitz export` just for testing purposes and it couldn't be performed due to `default Image Optimization used by next` even if <Image /> component from `next/image` is not used and as far as I know it is only initialized if it's used.

### Paste all your error logs here:

```
Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
  Possible solutions:
    - Use `next start` to run a server, which includes the Image Optimization API.
    - Use any provider which supports Image Optimization (like Vercel).
    - Configure a third-party loader in `next.config.js`.
    - Use the `loader` prop for `next/image`.
  Read more: https://nextjs.org/docs/messages/export-image-api
    at /Users/marek/Apps/test/frontend/node_modules/next/dist/export/index.js:14:785
    at async Span.traceAsyncFn (/Users/marek/Apps/test/frontend/node_modules/next/dist/telemetry/trace/trace.js:5:584)
```

### Paste all relevant code snippets here:

Just the code that we're left with after completing tutorial - nothing less, nothing more

### What are detailed steps to reproduce this?

1. Install blitz
2. Create new blitz application
3. Go through tutorial
4. Type `blitz export` in terminal

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v14.16.1

blitz: 0.34.3 (global)
blitz: 0.34.3 (local)

  Package manager: yarn
  System:
    OS: macOS 11.3
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 365.32 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1
    blitz: 0.34.3 => 0.34.3
    prisma: ~2.20 => 2.20.1
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    typescript: ~4.2 => 4.2.4
```

**Comment by YukioSenpai** [comment]
Hello guys, any updates on this issue ?

**Comment by flybayer** [comment]
Update! The solution is remove the `sessionMiddleware` import from `blitz.config.js`. That's not compatible with `blitz export`

I've just opened a PR that adds a helpful error for this case.
