### ISSUE TITLE
Build custom bot for issue & PR automation (Switch from Zenhub to GH Projects)

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#228]
**What do you want and why do you want it?.**
I'm currently using Zenhub for tracking issues and PRs and their statuses, but it's slow, clunky, is too hard to keep accurate. Also annoying that you have to install a browser extension to use it.

So let's use a Github Project board and let's write some serverless functions for automating everything exactly like we want.

Also our tags are a mess.

### Goal

- Issues & PRs always have accurate and meaningful labels.
- A project board that's always up to date and accurate with maximum automation
- Project board column location and `status/*` tags have automatic two-way sync

Here's what I think I want:

### Tags

- `kind/bug`
- `kind/feature-change`
- `kind/question`
- `kind/bad-experience`
- `kind/rfc`
- `kind/discussion`
- `kind/duplicate`
- `scope/cli`
- `scope/core`
- `scope/server`
- `scope/examples`
- `scope/gui`
- `scope/meta`
- `status/triage`
- `status/icebox`
- `status/ready-to-work-on`
- `status/assigned`
- `status/in-progress`
- `status/in-review`
- `status/done`
- `status/blocked`
- `good first issue`
- `good second issue`
- `needs investigation`
- `needs more information`
- `priority/high`
- `priority/low`

## Project Board

The GH `Dashboard` project will be the center of this.

All new issues and PRs should be automatically added to this project board

#### Triage

- New issues go here
- Auto tagged: `status/triage` 
- Maintainer actions:
	- Label appropriate `kind/*`
	- Label appropriate `scope/*`
	- Move to Read to work on column OR tag `status/ready-to-work-on` (same result)

#### Ready to Work On

- Issues that are ready to work on go here.
- Auto tagged: `status/ready-to-work-on`

#### Assigned

- Issues that have been assigned to or claimed by someone go here
- Auto tagged: `status/assigned`

#### In Progress

- Issues that have a PR attached
- Draft PRs.
- PR is auto moved here if created as draft or converted to draft
- Auto tagged: `status/in-progress`

#### In Review

- PRs that are out of draft status
- Issues usually won't go here
- Auto tagged: `status/in-review`

#### Done

- All closed issues and merged PRs
- Auto tagged: `status/done`

### Other

- PRs not ready for review are always in draft state. After review, if it needs changes it'll be converted back to draft.
- A change of `status/*` tag will automatically move the issue to the corresponding board column
- Enforce only 1 `status/*` tag at a time. If a new `status/*` tag is added, the previous tag is automatically removed.

### Implementation

We can write from scratch or use something like [Probot](https://probot.github.io/docs/hello-world/)

We'll host it on Vercel/Zeit under our Blitz account.

https://medium.com/the-andela-way/how-to-build-a-power-up-for-your-github-project-board-for-project-management-344d5b380a68

---

I'd like y'alls input on this! cc/ @ryardley @merelinguist 

If you want to build this, comment here! I'm happy to help provide more info or guidance.

**Comment by ryardley** [comment]
Probot looks like a great way to go as a means to customise GH. Automate as much as possible I say. We don't really want to have to deal with that sort of stuff day to day. Having said that one thing around workflow I have been thinking that is cool is the idea of using draft PRs to self assign tasks. Perhaps it makes sense to work that in to this automated workflow somehow?

**Comment by flybayer** [comment]
@ryardley Can you explain more what about what you are thinking for the draft PR/assign thing?

**Comment by merelinguist** [comment]
No objections to any of this! Definitely on board with using GH Projects

**Comment by Zeko369** [comment]
Looking forward to this 😍

**Comment by Zeko369** [comment]
@flybayer I’d like to hop on this tomorrow when I finish e2e tests

**Comment by flybayer** [comment]
@Zeko369 will you able to get to this very soon or can someone else take it?

**Comment by flybayer** [comment]
Heads up: Probot is already being started in #257

**Comment by flybayer** [comment]
@dajinchu can start work on this right away. So I'm letting him take this over since we need it asap.

You should collaborate with @karankiri for #257

**Comment by dajinchu** [comment]
we are live!
