### ISSUE TITLE
SuperJSON babel plugin causes prefetched queryKeys to miss the cache

### ISSUE THREAD

**Issue by MrLeebo** [blitz-js/blitz#2280]
### What is the problem?

Alright that title is a bit of a mouthful, but here's what's happening.

Blitz is set up to allow you to prefetch queries while server-rendering the component. The `<BlitzProvider>` component accepts a dehydratedState prop, [as seen here](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/blitz-app-root.tsx#L89), which you can populate by returning 
```ts
return { props: { dehydratedState: dehydrate(queryClient) } }
``` 
from your `getServerSideProps` method.

The problem is, that the prop gets processed by [babel-plugin-superjson-next](https://github.com/blitz-js/blitz/blob/bc0c7287ecd35c5e9e5f22b16bfdcf88b7d7145a/packages/babel-preset/src/index.ts#L12) which changes the shape of the queryKey, causing the cache lookup to miss.

As a fix, I think the plugin could be changed to ignore the `dehydratedState` prop when transforming `getServerSideProps` and `getStaticProps`. Or the plugin could accept a user-configurable list of props to ignore, and we put `dehydratedState` in that list in the blitz preset.

### Paste all your error logs here:

No error. The server renders the Suspense fallback and makes an extra POST to fetch the query.

### Paste all relevant code snippets here:

```ts
const user = useCurrentUser()
```

```ts
export async function getServerSideProps(ctx: GetServerSidePropsContext) {
  const queryClient = new QueryClient()
  await queryClient.prefetchQuery(getQueryKey(getCurrentUser), () =>
    invokeWithMiddleware(getCurrentUser, null, ctx)
  )

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    }
  }
}
```

### What are detailed steps to reproduce this?

1. In a fresh blitz app, create a page that invokes `useCurrentUser()`
2. Prefetch the getCurrentUser query using the getServerSideProps snippet shown
3. Refresh the page and notice in the DevTools networking tab that the server rendered the Suspense fallback (the cache missed)
4. Check the queryCache and notice that there are two entries, with and without SuperJSON metadata

### Run `blitz -v` and paste the output here:

```
macOS Catalina | darwin-x64 | Node: v14.15.4

blitz: 0.35.0-canary.2 (local)

  Package manager: yarn 
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.31 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1 
    blitz: 0.34.3 => 0.35.0-canary.2 
    prisma: ~2.20 => 2.20.1 
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    typescript: ~4.2 => 4.2.4
```

### Please include below any other applicable logs and screenshots that show your problem:

Expected queryKey:
<img width="405" alt="expected" src="https://user-images.githubusercontent.com/2754163/116509189-8082b380-a888-11eb-897d-400d90ba6386.png">

Actual queryKey:
<img width="332" alt="actual" src="https://user-images.githubusercontent.com/2754163/116509198-85dffe00-a888-11eb-90f3-10fc418b1471.png">

**Comment by Skn0tt** [comment]
That's an interesting one! Let me know if I got this right:

`getQueryKey(getCurrentUser)` returns something different depending on wether it's called on the client vs on the server. That is because of `babel-plugin-superjson-next`. Correct?

**Comment by MrLeebo** [comment]
Right, looks like [this](https://github.com/blitz-js/babel-plugin-superjson-next/blob/main/src/tools.tsx#L24) is where the replacement happens.
