### ISSUE TITLE
Runtime Error when using react 17.0.2 dependency

### ISSUE THREAD

**Issue by niklasgrewe** [blitz-js/blitz#2282]
### What is the problem?

my `package.json` looks like this:

```json
"dependencies": {
   "react": "0.0.0-experimental-6a589ad71",
   "react-dom": "0.0.0-experimental-6a589ad71"
}
```
when i try to update these dependencies to

```json
"dependencies": {
   "react": "17.0.2",
   "react-dom": "17.0.2"
}
```
i get the runtime errors:

```
Uncaught (in promise) Error: Cancel rendering route
Uncaught (in promise) TypeError: _reactDom.default.unstable_createRoot is not a function
```

### Paste all your error logs here:

```
Uncaught (in promise) Error: Cancel rendering route
Uncaught (in promise) TypeError: _reactDom.default.unstable_createRoot is not a function
```

### Paste all relevant code snippets here:

`package.json`

```json
"dependencies": {
   "react": "17.0.2",
   "react-dom": "17.0.2"
}
```

### What are detailed steps to reproduce this?

1. generate a new blitz app
2. install all dependencies
3. install `react@latest` and `react-dom@latest`
4. run blitz dev

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-arm64 | Node: v15.14.0

blitz: 0.34.3 (global)
blitz: 0.34.3 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
    Memory: 223.36 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.14.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.7.6 - /opt/homebrew/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1 
    blitz: 0.34.3 => 0.34.3 
    prisma: ~2.20 => 2.20.1 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    typescript: ~4.2 => 4.2.4
```

### Please include below any other applicable logs and screenshots that show your problem:

<img width="382" alt="Bildschirmfoto 2021-04-29 um 12 24 40" src="https://user-images.githubusercontent.com/61348836/116536970-e81b1c00-a8e5-11eb-926f-13fe0fd42d6c.png">

**Comment by flybayer** [comment]
By default we have react concurrent mode enabled which requires react@experimental. React v18, the next release, will support this at which time we won't need experimental.

If for some reason you want to disable concurrent mode (to support React 17), then you can do as shown here: https://blitzjs.com/docs/blitz-config#react-mode

**Comment by niklasgrewe** [comment]
thanks I did not know that, then this case can be closed
