### ISSUE TITLE
make --parent accept grandparents too.

### ISSUE THREAD

**Issue by agustif** [blitz-js/blitz#2284]
### What do you want and why?
I would like to be able to pass multiple folders to parent flag, so for example a note inside a task inside a project would be.

```
blitz generate all notes --parent project/task
```

### Possible implementation(s)
Right now I just do --parent task and manually move the generated files inside [taskId] folder
Then I proceed to add projectId useParam and pass it to edit route etc...

How might we do this?
No idea
### Additional context
Nice to have, not a bug

**Comment by flybayer** [comment]
@agustif sounds like a good idea. To make sure I understand, can you list the exact pages paths that `blitz generate pages notes --parent project/task` would create?

**Comment by agustif** [comment]
> @agustif sounds like a good idea. To make sure I understand, can you list the exact pages paths that `blitz generate pages notes --parent project/task` would create?
Hello @flybayer, thank you so answering to your question:

So basically, It would generate the same underlying pages but under pages/projects/[projectSlug]/tasks instead of projects/tasks directly.
```
grandparent on  master is 📦 v1.0.0 via ⬢ v14.16.0 took 34s
➜ blitz generate pages project
CREATE    app/pages/projects/[projectId].tsx
CREATE    app/pages/projects/[projectId]/edit.tsx
CREATE    app/pages/projects/index.tsx
CREATE    app/pages/projects/new.tsx
CREATE    app/projects/components/ProjectForm.tsx


grandparent on  master [?] is 📦 v1.0.0 via ⬢ v14.16.0 took 3s
➜ blitz generate pages tasks --parent=projects

CREATE    app/pages/projects/[projectId]/tasks/[taskId].tsx
CREATE    app/pages/projects/[projectId]/tasks/[taskId]/edit.tsx
CREATE    app/pages/projects/[projectId]/tasks/index.tsx
CREATE    app/pages/projects/[projectId]/tasks/new.tsx
CREATE    app/tasks/components/TaskForm.tsx


grandparent on  master [?] is 📦 v1.0.0 via ⬢ v14.16.0 took 2s
➜ blitz generate pages notes --parent=tasks
CREATE    app/pages/tasks/[taskId]/notes/[noteId].tsx
CREATE    app/pages/tasks/[taskId]/notes/[noteId]/edit.tsx
CREATE    app/pages/tasks/[taskId]/notes/index.tsx
CREATE    app/pages/tasks/[taskId]/notes/new.tsx
CREATE    app/notes/components/NoteForm.tsx
```
I'd like to be:
➜ blitz generate pages notes --parent=projects/tasks

```
CREATE    app/pages/projects/[projectId]/tasks/[taskId]/notes/[noteId].tsx
CREATE    app/pages/projects/[projectId]/tasks/[taskId]/notes/[noteId]/edit.tsx
CREATE    app/pages/projects/[projectId]/tasks/[taskId]/notes/index.tsx
CREATE    app/pages/projects/[projectId]/tasks/[taskId]/notes/new.tsx
CREATE    app/notes/projects/[projectId]/components/NoteForm.tsx


I've thought maybe adding the multiple path with / slash could be optional, and if I do --parent task, the generator looks for where the pages of

> @agustif sounds like a good idea. To make sure I understand, can you list the exact pages paths that `blitz generate pages notes --parent project/task` would create?

Thinking of this maybe this makes too long urls, Idk, maybe default approach is better but having options for both would be good?

**Comment by flybayer** [comment]
Ok great, thanks.

So the best practice in this case is to use "shallow routing" which is to only nest one level deep. I.e. use this:

```
CREATE    app/pages/tasks/[taskId]/notes/[noteId].tsx
CREATE    app/pages/tasks/[taskId]/notes/[noteId]/edit.tsx
CREATE    app/pages/tasks/[taskId]/notes/index.tsx
CREATE    app/pages/tasks/[taskId]/notes/new.tsx
```

Because the taskId gives you all the data you need. You can look up projectId.

What do you think?

**Comment by agustif** [comment]
> Ok great, thanks.
> 
> So the best practice in this case is to use "shallow routing" which is to only nest one level deep. I.e. use this:
> 
> ```
> CREATE    app/pages/tasks/[taskId]/notes/[noteId].tsx
> CREATE    app/pages/tasks/[taskId]/notes/[noteId]/edit.tsx
> CREATE    app/pages/tasks/[taskId]/notes/index.tsx
> CREATE    app/pages/tasks/[taskId]/notes/new.tsx
> ```
> 
> Because the taskId gives you all the data you need. You can look up projectId.
> 
> What do you think?

Think you're right, can close this, gonna ditch the full url thing as not really needed and adds code contrary to DRY's, had to add params for the parent and grandparent to routes etc which was a PITA...

Will try shallow routing!
