### ISSUE TITLE
Optional catch-all routes not handled correctly by the routes codegen script

### ISSUE THREAD

**Issue by kirakik** [blitz-js/blitz#2286]
### What is the problem?

I've identified an issue in the autogenerated `Routes`. It seems it doesn't [handle optional catch-all routes](https://blitzjs.com/docs/api-routes#dynamic-api-routes) correctly. 

### Paste all your error logs here:

```
Type error: ',' expected.

   7 |
   8 | export const Routes: {
>  9 |   HomePage(query: { [...answersId: string | number } & ParsedUrlQueryInput): RouteUrlObject;
     |                                                    ^
  10 |   ForgotPasswordPage(query?: ParsedUrlQueryInput): RouteUrlObject;
  11 |   LoginPage(query?: ParsedUrlQueryInput): RouteUrlObject;
  12 |   ResetPasswordPage(query?: ParsedUrlQueryInput): RouteUrlObject;

```

### Paste all relevant code snippets here:

N/A

### What are detailed steps to reproduce this?

1. Create a page with an optional catch-all route (e.g. `pages/[[...slug]].tsx`
2. Run `blitz codegen`
3. Run `blitz build`
4. The build fails because the generated Routes typing is missing a square bracket

### Run `blitz -v` and paste the output here:

```
blitz: 0.34.3 (global)
blitz: 0.34.3 (local)

  Package manager: yarn
  System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 54.01 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.21.1 - /usr/local/Cellar/yvm/3.4.0/shim/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1
    blitz: 0.34.3 => 0.34.3
    prisma: ~2.20 => 2.20.1
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    typescript: ~4.2 => 4.2.4
```

### Please include below any other applicable logs and screenshots that show your problem:

I've narrowed it down to one specific function: `parseParametersFromRoute`, located [here](https://github.com/blitz-js/blitz/blob/0a37ea4de858826d00f67d010fc0786e454b3172/packages/server/src/stages/route-import-manifest/route-import-manifest.ts#L88)

You can see it by adding the following extra test [here](https://github.com/blitz-js/blitz/blob/0a37ea4de858826d00f67d010fc0786e454b3172/packages/server/src/stages/route-import-manifest/route-import-manifest.test.ts#L7):

```ts
expect(parseParametersFromRoute("posts/[[...openedCommentPath]]")).toEqual({
    parameters: [],
    multipleParameters: ["openedCommentPath"],
  })
```

I'm happy to fix the issue myself!

**Comment by Skn0tt** [comment]
Thanks for reporting! The issue likely has to do with https://github.com/blitz-js/blitz/blob/canary/packages/server/src/stages/route-import-manifest/route-import-manifest.ts. Looking forward to your PR :D
