### ISSUE TITLE
Fix some npm/yarn warnings

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#229]
**What is the problem?**

We need to fix these warnings that show when installing blitz:

```
warning blitz > @blitzjs/server > path-is-absolute@2.0.0: This package is no longer relevant as Node.js 0.12 is unmaintained.
11:51:15.282  

warning blitz > @blitzjs/core > @types/serialize-error@4.0.1: This is a stub types definition. serialize-error provides its own type definitions, so you do not need this installed.

npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
```

**Comment by ryardley** [comment]
i thought there was a PR somewhere that got rid of path-is-absolute?

**Comment by ryardley** [comment]
Hmm wasn't refactored from the server.

**Comment by flybayer** [comment]
No, that other PR was `find-parent-dir` I think

**Comment by enzoferey** [comment]
Can I do this ? 😁

**Comment by flybayer** [comment]
@enzoferey yes you can do this!

We can't do anything about warnings that come because of other packages, like Next. We can only fix issues that we are adding ourself.
