### ISSUE TITLE
Setting trailingSlash: true in the blitz configuration creates 308 redirects for all api requests.

### ISSUE THREAD

**Issue by cashmagnet** [blitz-js/blitz#2294]
### What is the problem?

API requests for blitz, from either await direct function calls inside useEffects or useQuery calls are not being created with consideration for the trailingSlash config.

### What are detailed steps to reproduce this?

1. create new blitz application
2. update blitz.config.js as below 
````
const { sessionMiddleware, simpleRolesIsAuthorized } = require("blitz")

module.exports = {
  middleware: [
    sessionMiddleware({
      isAuthorized: simpleRolesIsAuthorized,
    }),
  ],
  trailingSlash: true,

  /* Uncomment this to customize the webpack config
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    // Note: we provide webpack above so you should not `require` it
    // Perform customizations to webpack config
    // Important: return the modified config
    return config
  },
  */
}

````

3. run your the blitz server (development or production, no difference) 
4. open up network tab in browser debugging tools
5. navigate to the login screen - http://localhost:3000/login/
6. you will see the getCurrentUser request is being requested without a trailing slash. 

### Run `blitz -v` and paste the output here:

```
Windows 10 | win32-x64 | Node: v12.18.2

blitz: 0.34.3 (global)
blitz: 0.34.3 (local)

  Package manager: yarn
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 16.19 GB / 31.92 GB
  Binaries:
    Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1
    blitz: 0.34.3 => 0.34.3
    prisma: ~2.20 => 2.20.1
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    typescript: ~4.2 => 4.2.4

```

**Comment by flybayer** [comment]
### To Fix

1. Add trailingSlash to the blitz runtime data: https://github.com/blitz-js/blitz/blob/canary/packages/core/src/blitz-data.tsx#L13
2. Update [`getApiUrlFromResolverFilePath`](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/rpc-client.ts#L161) to add trailing slash if `getBlitzRuntimeData().trailingSlash` is true.
