### ISSUE TITLE
Add top level await support for blitz console

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#230]
**What do you want and why do you want it?.**

We were enabling top level await in our binaries using this:
```
#!/usr/bin/env node --experimental-repl-await
```

But that [doesn't work on Linux](https://github.com/nxtep-io/ts-framework-cli/issues/1), which also breaks production deployments, like to Vercel/Zeit. So I had to remove it for now.

We need to add this back in some other fully cross platform way.

**Possible implementation(s)**

I already tried the same approach as https://github.com/nxtep-io/ts-framework-cli/pull/10 . This works good on macOS and Linux, but breaks on windows since windows doesn't have bash.

So I'm sort of stumped at how to do this. Maybe create a separate bin for the repl that we can spawn from the console command?

**Comment by Zeko369** [comment]
Looking into this

**Comment by flybayer** [comment]
Someone else is welcome to try and add this cross-platform.
