### ISSUE TITLE
Blitz: command not found

### ISSUE THREAD

**Issue by NaseerAkbari** [blitz-js/blitz#2314]
### What is the problem?

Hello guys, 
I have installed the [nodejs from this online help](https://www.geeksforgeeks.org/installation-of-node-js-on-linux/) successfully then followed the online tutorial. now, when I wanna execute the downloaded project, shows such an error like the screen shot. 
any idea, what I have done not correct? 
thanks guys for your help. 

### Paste all your error logs here:

```
PASTE_HERE (leave the ``` marks)
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
PASTE_HERE (leave the ``` marks)
```

### Please include below any other applicable logs and screenshots that show your problem:

<img width="801" alt="Screenshot 2021-05-08 at 10 50 02 AM" src="https://user-images.githubusercontent.com/54404798/117533107-26ea5980-afeb-11eb-83b5-c50ac35fa704.png">

**Comment by MrLeebo** [comment]
Hi, can you provide the output from `blitz -v`?

**Comment by flybayer** [comment]
@MrLeebo that won't work because blitz isn't installed.

@NaseerAkbari looks like blitz didn't successfully install. See that `error mem-fs-editor The engine node is incompatible` line? That means you have Node v10 which isn't supported.

I recommend using https://github.com/Schniz/fnm to install a newer version of Node, like v14. Then install blitz and it should work.

**Comment by bartoszkrawczyk2** [comment]
Hi,

I have the same issue. My node version is 16.13.0, I've run `yarn global add blitz`, installed successfully with message:
```
success Installed "blitz@0.44.0" with binaries:
      - blitz
```

But when I try to create new project I get an error:
```
zsh: command not found: blitz
```

Do I have to add it manually to PATH? It would be great to provide instructions in documentation.

**Comment by flybayer** [comment]
@bartoszkrawczyk2 unfortunately that's a package manager issue and there's nothing we can do on our side. Maybe try using a different version of yarn or using npm instead.

**Comment by bartoszkrawczyk2** [comment]
Thanks @flybayer , installing with npm instead of yarn did help :)
