### ISSUE TITLE
Can't use dependent queries

### ISSUE THREAD

**Issue by carllippert** [blitz-js/blitz#2317]
### What is the problem?

Type system gets angry when passing query params as function like described in docs () => ({where: {...}}, {enabled: user}) etc. 

Also when breaking by trying to go sans "args as function" get the "Module not found: Can't resolve 'fs'"

### Paste all your error logs here:

```
PASTE_HERE (leave the ``` marks)
```

### Paste all relevant code snippets here:

```
 const [books] = useQuery(getBooks, { orderBy: { title: "asc" }, where: { userId: user.id } })
  const [chapters] = useQuery(
    getChapters,
    () => ({ where: { bookId: books.books[0].id }, orderBy: { number: "asc" } }, { enabled: books })
  )
  const [{ pages }] = useQuery(
    getPages,
    () => (
      { where: { bookId: books.books[0].id, chapterId: chapters.chapters[0].id }, orderBy: { number: "asc" }, take: 1 },
      { enabled: chapters }
    )
  )
```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v14.15.1

blitz: 0.33.1 (global)
blitz: 0.34.3 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Apple M1
    Memory: 26.87 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/client: ~2.19 => 2.19.0 
    blitz: 0.34.3 => 0.34.3 
    prisma: ~2.19 => 2.19.0 
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    typescript: ~4.1 => 4.1.5 
```

**Comment by flybayer** [comment]
@carllippert ah, sorry about that! Our docs were wrong and should not have the query args returned by a function. I've just fixed that.

Here's the proper way:

```ts
const [user] = useQuery(getUser, { where: { id: props.query.id } })
const [projects] = useQuery(getProjects, { where: { userId: user.id } }, { enabled: user }))
```

Just using the `enabled` option, but passing args as usual

**Comment by flybayer** [comment]
@carllippert same way. But if you have more than two dependent queries, you are much better off to make a new Blitz query resolver that returns all the data you need in one shot. This will result in better perf and better UX.

```ts
const [user] = useQuery(getUser, { where: { id: props.query.id } })
const [projects] = useQuery(getProjects, { where: { userId: user.id } }, { enabled: user }))
const [tasks] = useQuery(getTasks, { where: { stuff } }, { enabled: projects }))
```

"Possibly undefined" is because that's the reality when a query is possibly disabled. You need to handle this. Example: if (not defined) throw error (or render loading or something).

**Comment by flybayer** [comment]
Closing this as I believe our code is working correctly
