### ISSUE TITLE
Add context path to blitz generate

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#232]
**What do you want and why do you want it?.**

Currently blitz generate command generates all files at the top level. So `blitz generate all tasks` puts the tasks files at `app/tasks/*`.

We need to add a context/namespace support that works like this:

```
blitz generate all admin/tasks
```
generates all the normal tasks files but at `app/admin/tasks/*`

General format is:

```
blitz generate TYPE [CONTEXT_PATH/]MODEL
```

- The model name is always the last segment of the input path.
- The `/app/` path is always implicit. 
- The context path can be many layers deep like `/clients/admin/internal/`

**Comment by aem** [comment]
For queries and mutations this is pretty self-explanatory. For pages, will the context path also create a path prefix or just a top-level page with a logical organization in the file system? As a concrete example, using the `admin/tasks` example above, which of the following would we generate:

1. `app/admin/tasks/pages/admin/index.tsx`
2. `app/admin/tasks/pages/admin/tasks/index.tsx`
3. `app/admin/tasks/pages/tasks/index.tsx`
4. `app/admin/pages/admin/tasks/index.tsx`
5. `app/admin/pages/tasks/index.tsx`

I could make arguments for any of them based on how our file structure works

**Comment by flybayer** [comment]
The context path will not go inside `pages/`, so the result would be (3)

`--parent` will be used for page nesting

We might need to add another flag later for arbitrary page nesting
