### ISSUE TITLE
Support async `initServer` hook

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#2324]
### What do you want and why?

Support async `experimental.initServer` hook so that the server is not started until the promise returned from initServer resolves.

Original discussion: https://github.com/blitz-js/blitz/pull/2256#discussion_r629454953

### Possible implementation(s)

Move to [this](https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/next-server/server/next-server.ts#L255-L257) to [here](https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/server/lib/start-server.ts#L12)

**Comment by g3offrey** [comment]
I am working on that.
