### ISSUE TITLE
Support req and res within Blitz Passport strategies 

### ISSUE THREAD

**Issue by CarterMcAlister** [blitz-js/blitz#2329]
### What do you want and why?
Currently, there is no way to include custom params and use them within Blitz passport strategies. 
This prevents you from being able to do things like pass referral codes or invite codes when using the built in Blitz Passport integration.

### Possible implementation(s)

Add support for accessing `req` and `res` within Passport strategies, similarly to the way `ctx` is accessible.  

### Additional context

My use case is passing a referral code along when a user signs up for the first time through a SSO Passport strategy

**Comment by flybayer** [comment]
### Implementation

Here's how I'm proposing to support this:

```diff
-export default passportAuth((ctx) => ({
+export default passportAuth(({ctx, req, res}) => ({
  successRedirectUrl: "/",
  errorRedirectUrl: "/",
  strategies: [
```

Will that work for you?

This is the line of code that needs changed: https://github.com/blitz-js/blitz/blob/canary/packages/core/src/server/auth/passport-adapter.ts#L39

**Comment by CarterMcAlister** [comment]
@flybayer yes I believe so, thanks for pointing me in the right direction. I should have some time this evening to put up a PR for this change.

**Comment by doncicuto** [comment]
Hi @flybayer, I have the same issue and was willing to use req and res to be able to manage invitation codes. If you want to assign this issue to me, I think I'm ready to create a pull request right now following your previous guidelines and comments. Thanks!

**Comment by abuuzayr** [comment]
awesome, thanks @doncicuto ! I have assigned you as requested
