### ISSUE TITLE
Globally enable suppressFirstRenderFlicker

### ISSUE THREAD

**Issue by acornellier** [blitz-js/blitz#2330]
### What do you want and why?

I'd like to enable `suppressFirstRenderFlicker` for all pages by default. My website has some styling not know to the server, that can only be applied client-side. This feature is very useful for hiding a very obnoxious flicker.

Having to enable it manually for every single page is a little cumbersome.

### Possible implementation(s)

Perhaps in `blitz.config.js`?

**Comment by flybayer** [comment]
Good idea.

Let's add it via blitz config like this:

```ts
{
  pages: {
    suppressFirstRenderFlicker: true
  }
}
```
