### ISSUE TITLE
Support optional disabling of server hot reloading

### ISSUE THREAD

**Issue by andreasasprou** [blitz-js/blitz#2332]
### What do you want and why?

It's pretty frustrating when there are some common deps used in `server.ts` that are changed in a way that doesn't warrant a server reload in practice.

### Possible implementation(s)

```typescript
// blitz/packages/server/src/dev.ts 

const blitzConfig = getConfig()

await startCustomServer(buildFolder, config, { watch: !blitzConfig.disableServerHotReload })
```

```javascript
// blitz.config.(js|ts)

module.exports = {
  disableServerHotReload: true,
}
```

**Comment by flybayer** [comment]
Good idea!

Let's do the config like this:

```ts
module.exports = {
  customServer: {
  }
}
```

**Comment by markhughes** [comment]
@andreasasprou did you want to implement this one? If not, @flybayer I could take this.

**Comment by andreasasprou** [comment]
> @andreasasprou did you want to implement this one? If not, @flybayer I could take this.

Go ahead mate
