### ISSUE TITLE
Page.authenticate should prevent the page component from rendering at all when user is not authenticated

### ISSUE THREAD

**Issue by dbachrach** [blitz-js/blitz#2337]
### What do you want and why?

```
const Home: BlitzPage = () => {
  const user = useCurrentUser()
  return <div>Hello {user.name}</div>
}

Home.authenticate = true
```

When I load this page with a logged-out user, I would expect the `Home.authenticate = true` to restrict this component from even executing when there is not a current user. The actual behavior is:

```
Unhandled Runtime Error
TypeError: Cannot read property 'name' of null
```

I can add a guard for the no user case, which prevents the issue:

```
if (!user) {
    return <div>No user</div>
}
```

But it did not mesh with my understanding of Page.authenticate. From the docs:

> Set Page.authenticate = true on all pages that require a user to be logged in. If a user is not logged in, an AuthenticationError will be thrown and caught by your top level Error Boundary.

I think the AuthenticationError should be raised prior to the page component rendering at all. 

As an extension to this, it would be nice to have `useCurrentUser()` return a non-optional user when the page has `authenticate = true`. That may be tricky/impossible for typescript though.

### Possible implementation(s)

I think the issue stems from

```
const BlitzInnerRoot = (props: ComponentPropsWithoutRef<BlitzPage>) => {
    useAuthorizeIf(Page.authenticate === true)

    return <Page {...props} />
}

export const useAuthorizeIf = (condition?: boolean) => {
  useEffect(() => {
    if (condition && !publicDataStore.getData().userId) {
      const error = new AuthenticationError()
      delete error.stack
      throw error
    }
  })
}
```

Since this is in an effect, the initial render is not going to throw an error, so the page component will have a chance to render with the user being null.

**Comment by flybayer** [comment]
Thank you! You are right.

I forget why I put that in a useEffect, but I think it was because I was getting react hydration errors if we threw straight in the render function. 

So this may take some fiddling and testing to figure out the best way to resolve it.

**Comment by mtford90** [comment]
Similar to this - I also noticed that `useAuthenticatedSession` can actually result `userId: null` which is not reflected in the typings
