### ISSUE TITLE
Can't resolve modules placed in 'app/(. +)pages/' path

### ISSUE THREAD

**Issue by okmr-d** [blitz-js/blitz#2341]
### What is the problem?

This error has occurred when I tried to import 'app/web-pages/queries/getWebPages' module

<img width="975" alt="screenshot" src="https://user-images.githubusercontent.com/4679138/118236722-64f6ea00-b4d1-11eb-971d-b2b70fc39457.png">

I tried moving "app/web-pages" to "app/aaapages", but that didn't work.
I tried moving "app/web-pages" to "app/web-page", and it worked fine.

It seems to happen in 'app/(. +)pages' path.

### Paste all your error logs here:

```
error - ./app/pages/web-pages/index.tsx:4:0
Module not found: Can't resolve 'app/web-pages/queries/getWebPages'
  2 | import { Head, Link, usePaginatedQuery, useRouter, BlitzPage, Routes } from "blitz"
  3 | import Layout from "app/core/layouts/Layout"
> 4 | import getWebPages from "app/web-pages/queries/getWebPages"
  5 | 
  6 | const ITEMS_PER_PAGE = 100
  7 | 
```

### Paste all relevant code snippets here:

```
N/A
```

### What are detailed steps to reproduce this?

1. Run `blitz generate all WebPage` command and it will generate the following files:
```
app/pages/web-pages/[webPageId]/edit.tsx
app/pages/web-pages/[webPageId].tsx
app/pages/web-pages/index.tsx
app/pages/web-pages/new.tsx
app/web-pages/components/WebPageForm.tsx
app/web-pages/queries/getWebPage.ts
app/web-pages/queries/getWebPages.ts
app/web-pages/mutations/createWebPage.ts
app/web-pages/mutations/deleteWebPage.ts
app/web-pages/mutations/updateWebPage.ts
```

2. Run `blitz dev`

3. Open `http://localhost:3000/web-pages`

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-arm64 | Node: v15.12.0

blitz: 0.34.3 (global)
blitz: 0.34.3 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
    Memory: 70.95 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.12.0 - ~/.anyenv/envs/nodenv/versions/15.12.0/bin/node
    Yarn: 1.22.10 - ~/.anyenv/envs/nodenv/versions/15.12.0/bin/yarn
    npm: 7.6.3 - ~/.anyenv/envs/nodenv/versions/15.12.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1 
    blitz: 0.34.3 => 0.34.3 
    prisma: ~2.20 => 2.20.1 
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    typescript: ~4.2 => 4.2.4 
```

**Comment by flybayer** [comment]
Thanks for the report! Looks like a bug in our regex here: https://github.com/blitz-js/blitz/blob/canary/packages/server/src/stages/pages/index.ts#L8

And we need to add a test case for this in this file: https://github.com/blitz-js/blitz/blob/canary/packages/server/src/stages/pages/pages-path-transformer.test.ts

**Comment by Patil2099** [comment]
@flybayer I would love to help on this issue. Can you provide me examples of what strings should be accepted in the regular exp?

**Comment by flybayer** [comment]
@Patil2099 great! The regex should only match `/pages/` not `/web-pages/`, `/pages1/` or anything else besides an exact folder name of `pages`

**Comment by flybayer** [comment]
Fixed in https://github.com/blitz-js/blitz/pull/2502
