### ISSUE TITLE
Error while create-a-new-app steps in Introduction section

### ISSUE THREAD

**Issue by yogeshwar607** [blitz-js/blitz#2344]
### What is the problem?

For the first time setup from [blitzjs](https://blitzjs.com/docs/get-started#create-a-new-app) , using below commands  throws error 

- blitz new myAppName
- cd myAppName
- blitz dev

Solution is after  running  prisma commands from [here](https://blitzjs.com/docs/cli-prisma)  , its works fine 

Issue is very small & easy to fix but might be problematic for new users 

### Paste all your error logs here:

```
![Uploading image.png…]()
```

### Paste all relevant code snippets here:

![image](https://user-images.githubusercontent.com/10059011/118322060-276b7e80-b51c-11eb-8f2b-19edcc2724fe.png)

### What are detailed steps to reproduce this?

1. Use [blitz documentation](https://blitzjs.com/docs/get-started#create-a-new-app) first time setup

### Run `blitz -v` and paste the output here:

```
macOS Catalina | darwin-x64 | Node: v14.16.1

blitz: 0.34.3 (global)
blitz: 0.34.3 (local)

  Package manager: yarn 
  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 22.75 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /Users/yogi/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.12 - /Users/yogi/.nvm/versions/node/v14.16.1/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1 
    blitz: 0.34.3 => 0.34.3 
    prisma: ~2.20 => 2.20.1 
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    typescript: ~4.2 => 4.2.4 
```

**Comment by flybayer** [comment]
The solution is to manually run `blitz prisma migrate` and then run `blitz dev`.

However that shouldn't be needed. Probably there was an error during `blitz new`, but you didn't include that log in your post. Can you post that?

**Comment by yogeshwar607** [comment]
@flybayer 

Trying to replicate again , update blitz to `blitz: 0.35.0 (global)` , got another error 

`blitz new` commands is successful with below output  , it created `blitz.config.ts` file but `blitz dev` is checking for `blitz.config.js` 

<img width="1148" alt="Screenshot 2021-05-19 at 5 55 19 AM" src="https://user-images.githubusercontent.com/10059011/118739316-ce2a8480-b866-11eb-993f-c41fea247542.png">

```
blitz -v 
macOS Catalina | darwin-x64 | Node: v14.16.1

blitz: 0.35.0 (global)
blitz: 0.1.0 (local)

  Package manager: yarn 
  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 70.86 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /Users/yogi/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.12 - /Users/yogi/.nvm/versions/node/v14.16.1/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    prisma: Not Found
    react: ^17.0.1 => 17.0.2 
    react-dom: ^17.0.1 => 17.0.2 
    typescript: Not Found


```

Error logs -

```
(node:5167) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/funnel/Code/oss/influencer-marketing-UI/blitz.config.js'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.buildConfig (/Users/funnel/.config/yarn/global/node_modules/@blitzjs/config/dist/blitzjs-config.cjs.dev.js:71:30)
    at Object.run (/Users/funnel/.config/yarn/global/node_modules/@blitzjs/cli/lib/src/index.js:14:14)
    at main (/Users/funnel/.config/yarn/global/node_modules/blitz/cli/dist/blitz-cli.cjs.dev.js:94:9)
    at Object.<anonymous> (/Users/funnel/.config/yarn/global/node_modules/blitz/cli/dist/blitz-cli.cjs.dev.js:118:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5167) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5167) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jesseweed** [comment]
I ran into a similar problem, I was able to get it to work eventually, but here's my repro steps for posterity:

1. `yarn global add blitz`
2. `blitz new testapp`
3. Then I get this error straight away:
```
node:fs:487
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/Volumes/Web/projects/blitz.config.js'
    at Object.openSync (node:fs:487:3)
    at Object.readFileSync (node:fs:388:35)
    at Object.buildConfig (/Users/jesse/.config/yarn/global/node_modules/@blitzjs/config/dist/blitzjs-config.cjs.dev.js:71:30)
    at Object.run (/Users/jesse/.config/yarn/global/node_modules/@blitzjs/cli/lib/src/index.js:14:14)
    at main (/Users/jesse/.config/yarn/global/node_modules/blitz/cli/dist/blitz-cli.cjs.dev.js:94:9)
    at Object.<anonymous> (/Users/jesse/.config/yarn/global/node_modules/blitz/cli/dist/blitz-cli.cjs.dev.js:118:1)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Volumes/Web/projects/blitz.config.js'
}
```

4. After that failing twice, I ran `touch blitz.config.js`
5. run `blitz new testapp` one more time
6. success!

So it seems that it's looking for a config file that's possibly incorrectly linked? It's possible there's meant to be a blitz.config.js file in that location, but it's a level up from the directory the app created in, so that doesn't seem right.

Weirdly, I tried again later in a new iTerm 2 tab, and it worked fine, no need to add a `touch blitz.config.js` file. So it could also just be that you need to switch to a new tab/window after install before running `blitz new` for the first time? ¯\_(ツ)_/¯

Anyway, it works for me now, just some info in case it helps anybody later.

**Comment by flybayer** [comment]
This should be fixed in https://github.com/blitz-js/blitz/releases/tag/v0.35.1
