### ISSUE TITLE
Avoid using Node 16 - will crash

### ISSUE THREAD

**Issue by marcnjaramillo** [blitz-js/blitz#2349]
### What is the problem?

**Learned this the hard way. I hope this helps others avoid this problem.**

I needed to update Node to be able to install blitz, and I just ran `nvm install node` which installed Node 16. I was able to successfully install blitz, but when I tried to sign up I got a "TypeError - Failed to fetch" message in the browser, and the error message below in the console. It's really not helpful at all, and after several Google searches I found this [bug report](https://github.com/prisma/prisma/issues/6682) on Github that says Node 16 is not recommended for use with the current version of Prisma Client, and this [SO post](https://stackoverflow.com/questions/67293899/error-assertion-args3-isint32-failed-using-a-simple-create-in-prismajs) that also said the current version of Prisma Client does not support Node 16.

I downgraded down to the last LTS of Node, and I was able to successfully sign up.

### Paste all your error logs here:

```
../src/node_http_parser.cc:567:static void node::(anonymous namespace)::Parser::Initialize(const FunctionCallbackInfo<v8::Value> &): Assertion `args[3]->IsInt32()' failed.
 1: 0x10935f7f5 node::Abort() (.cold.1) [/Users/marcjaramillo/.nvm/versions/node/v16.1.0/bin/node]
 2: 0x108016969 node::Abort() [/Users/marcjaramillo/.nvm/versions/node/v16.1.0/bin/node]
 3: 0x1080167d1 node::Assert(node::AssertionInfo const&) [/Users/marcjaramillo/.nvm/versions/node/v16.1.0/bin/node]
 4: 0x10803367f node::(anonymous namespace)::Parser::Initialize(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/marcjaramillo/.nvm/versions/node/v16.1.0/bin/node]
 5: 0x108208275 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/Users/marcjaramillo/.nvm/versions/node/v16.1.0/bin/node]
 6: 0x108207848 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/marcjaramillo/.nvm/versions/node/v16.1.0/bin/node]
 7: 0x108206dff v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/marcjaramillo/.nvm/versions/node/v16.1.0/bin/node]
 8: 0x108a907b9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/Users/marcjaramillo/.nvm/versions/node/v16.1.0/bin/node]
```

### Paste all relevant code snippets here:

No code snippet

### What are detailed steps to reproduce this?

1. Install Node 16
2. Run `yarn global add blitz`
3. Create a new app and cd into it
4. Run `blitz dev`
5. Sign up a new user

### Run `blitz -v` and paste the output here:

```
macOS Catalina | darwin-x64 | Node: v16.1.0

blitz: 0.34.3 (global)
blitz: 0.34.3 (local)

  Package manager: yarn 
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 1.97 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.1.0 - ~/.nvm/versions/node/v16.1.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.11.2 - ~/.nvm/versions/node/v16.1.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1 
    blitz: 0.34.3 => 0.34.3 
    prisma: ~2.20 => 2.20.1 
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    typescript: ~4.2 => 4.2.4 
```

**Comment by flybayer** [comment]
Thanks @marcnjaramillo. Since this is a Prisma bug, I'll go ahead and close it. But it's here for anyone who searches for this in our repo

**Comment by dukejones** [comment]
thanks
