### ISSUE TITLE
Support nonce in BlitzScript

### ISSUE THREAD

**Issue by markhughes** [blitz-js/blitz#2353]
### What do you want and why?
`<BlitzScript />` to take a `nonce`.

Currently `<NextScript />` can take a `nonce` but `<BlitzScript />` does not.

https://github.com/vercel/next.js/blob/canary/packages/next/pages/_document.tsx#L241-L244

### Possible implementation(s)

Add support to `blitz-script.tsx` for this optional prop and pass that to `NextScript` and `BlitzData`

### Additional context

This lets us set up strict content security policies.

**Comment by markhughes** [comment]
Happy to take this one on for a quick implementation :)

**Comment by flybayer** [comment]
Sweet, all yours! @markhughes
