### ISSUE TITLE
Update to Zod v3

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#2356]
### What do you want and why?

Zod v3 just released: https://twitter.com/colinhacks/status/1394326019855749129

[Read the Zod upgrade guide](https://github.com/colinhacks/zod/blob/master/MIGRATION.md)

- [x] We need to update our new app template to use v3: https://github.com/blitz-js/blitz/tree/canary/packages/generator/templates/app
  - I don't *think* there's any breaking changes but not sure because GH release notes don't say anything.
- [x] We need to update our blitz generate templates to work with v3: https://github.com/blitz-js/blitz/tree/canary/packages/generator/templates
  - Remove `.nonstrict()` since v3 uses that by default
- [x] We need to make sure `resolver.zod` works with v3
- [x] Change from the `import * as z` to the new `import {z} from` syntax
- [ ] Update our new app form template error handling to use new zod error feature: https://twitter.com/colinhacks/status/1394326038570799105

**Comment by mabadir** [comment]
Hi @flybayer, I will work on this one.

**Comment by mabadir** [comment]
Hello @flybayer; any thoughts of how best to test the changes? Should I bootstrap application under each template and write the test cases for a form?

**Comment by flybayer** [comment]
> * [ ]  Update our new app form template error handling to use new zod error feature: [twitter.com/colinhacks/status/1394326038570799105](https://twitter.com/colinhacks/status/1394326038570799105)

This wasn't fixed in that PR, so opened a new issue for it: https://github.com/blitz-js/blitz/issues/2412
