### ISSUE TITLE
Error: No QueryClient set, use QueryClientProvider to set one

### ISSUE THREAD

**Issue by andrei-scripcaru** [blitz-js/blitz#2360]
### What is the problem?

Is anyone experiencing the following error upon using `useQuery` / `useMutation`?

`Error: No QueryClient set, use QueryClientProvider to set one`

Error appears with both `latest` and `canary` Blitz version tags. Works well with `0.33.1`.

**Comment by flybayer** [comment]
Do you have `blitz/babel` set as the preset in `babel.config.js`? Sounds like you have `next/babel`, but it should be `blitz/babel`

**Comment by andrei-scripcaru** [comment]
> Do you have `blitz/babel` set as the preset in `babel.config.js`? Sounds like you have `next/babel`, but it should be `blitz/babel`

Hey! Thanks for the reply, I've got `blitz/babel` and I rolled back everything to `0.33.1` to be able to work.

![image](https://user-images.githubusercontent.com/67165117/118881234-830e8100-b8fb-11eb-95a2-76430eced275.png)

**Comment by flybayer** [comment]
Ok you should be able to upgrade to 0.35.0. Just make sure to address all breaking changes in the release notes.

**Comment by andrei-scripcaru** [comment]
> Ok you should be able to upgrade to 0.35.0. Just make sure to address all breaking changes in the release notes.

Thanks!
