### ISSUE TITLE
Implement useQuery prefetching

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#237]
Both of the following should cache the `getProduct` query, same as if it was used with `useQuery`

```ts
const product = await getProduct({where: {id: props.id}})
```

```tsx
<button onMouseEnter={() => getProduct({where: {id: productId}})}>
  View Product
</button>
```

- This functionality needs to be added in the `rpc.ts` file in the `core` package. 
- It needs to use the same computed cache key as used inside the blitz `useQuery`.
- It needs to use [`queryCache.setQueryData`](https://github.com/tannerlinsley/react-query#querycachesetquerydata) from react-query to actually set the cache

Then end-result is that once prefetched like shown above, then the next call of `useQuery(getProduct, {where: {id: productId}})` will return the cached data.

**Comment by flybayer** [comment]
Let me know if you want to work on this but need more information about how to build it!

**Comment by ivandevp** [comment]
Hey @flybayer ! I can work on this. I'll probably need more information but I can start by checking how `react-query` works for this case and understand how to add it to Blitz ⚡.

**Comment by flybayer** [comment]
@ivandevp sounds good! :)
