### ISSUE TITLE
Error: The cookie prefix used has invalid characters.

### ISSUE THREAD

**Issue by jesseweed** [blitz-js/blitz#2372]
### What is the problem?

When creating a new app that has a `.` in the name (i.e.  `test.app`),  setting this as the `cookiePrefix` in `blitz.config.ts` throw the error `Error: The cookie prefix used has invalid characters. Only alphanumeric characters, "-"  and "_" character are supported`.

I was able to get it working but just changing the value of  `cookiePrefix` to just `testapp`, so not a big deal. But should consider adding some kind of filter to strip out any chars that aren't allowed in cookies if that key is going to be set automatically.

### Paste all your error logs here:

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /Volumes/Web/projects/test.app/.env
Error: The cookie prefix used has invalid characters. Only alphanumeric characters, "-"  and "_" character are supported
    at assert$1 (/Volumes/Web/projects/test.app/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.dev.js:488:25)
    at sessionMiddleware (/Volumes/Web/projects/test.app/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.dev.js:630:3)
    at Object.<anonymous> (/Volumes/Web/projects/test.app/.blitz/blitz.config.js:24:40)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Object.newLoader [as .js] (/Volumes/Web/projects/test.app/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Paste all relevant code snippets here:

```
import { sessionMiddleware, simpleRolesIsAuthorized } from "blitz"

module.exports = {
  middleware: [
    sessionMiddleware({
      // this is the code that throws the error
      cookiePrefix: "test.app",
      isAuthorized: simpleRolesIsAuthorized,
    }),
  ],
  /* Uncomment this to customize the webpack config
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    // Note: we provide webpack above so you should not `require` it
    // Perform customizations to webpack config
    // Important: return the modified config
    return config
  },
  */
}

```

### What are detailed steps to reproduce this?

1. `blitz new test.app`
2. `cd test.app`
3. `yarn dev`

the project will build successfully, but it crashes almost right after starting with the invalid character error.

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v15.2.0

blitz: 0.35.0 (global)

  Package manager: npm
  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 25.04 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.2.0 - ~/.fnm/current/bin/node
    Yarn: 1.22.10 - ~/.fnm/current/bin/yarn
    npm: 7.0.8 - ~/.fnm/current/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```

**Comment by kyashrathore** [comment]
if you initiated your app with some name like `new.app` it adds a cookie prefix in blitz.config.js file you can change the dot something like underscore or dash.

**Comment by flybayer** [comment]
Thanks @jesseweed, you are absolutely right we should automatically replace invalid characters.

### How to fix

1. Add a new field [here](https://github.com/blitz-js/blitz/blob/canary/packages/generator/src/generators/app-generator.ts#L41) called `safeNameSlug` that takes appName but replaces any invalid chars with `-`
   1. [Here's the regex](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/server/auth/sessions.ts#L155) we use to validate the cookie name.
2. Change [this line](https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/app/blitz.config.ts#L6) to use `__safeNameSlug__` instead of `__name__`
