### ISSUE TITLE
Add cli command: blitz db migrate

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#24]
- [ ] `blitz db migrate` should effectively run `prisma2 migrate save --experimental && prisma2 migrate up --experimental`
- [ ] Add tests

**Comment by tsawan** [comment]
@flybayer can you comment if blitz db will have more options (commands) in the future? This may require us to structure this command in a specific way ( I need to read more from oclif docs ).

**Comment by flybayer** [comment]
Sure, some possible examples:

```
blitz db seed
blitz db migrate
blitz db setup
```

**Comment by tsawan** [comment]
@flybayer do you want 'd' alias for 'db'? and how about replacing setup with init since 's' alias is already taken by 'seed'?

**Comment by flybayer** [comment]
Don't alias `db` since it's already so short. Don't add `seed` and `setup` yet, let's wait till we know how to implement those. But `blitz db init` is fine. Might be better than `setup` anyways.
