### ISSUE TITLE
Implement the `blitz routes` command

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#240]
**What do you want and why do you want it?.**

We want a single command, `blitz routes`, that nicely lists all http endpoints in the app. This is especially useful since we can have many `pages` folders throughout the app.

- pages
- api routes
- query & mutation endpoints

For example, here's how rails does it. 

![image](https://user-images.githubusercontent.com/8813276/80277164-5c414380-8717-11ea-8ac4-c5bb9d9a45e0.png)

**Comment by mikeattara** [comment]
Let me have a go at this

**Comment by ryardley** [comment]
Be nice if this could be serializable so that you could use it to generate sitemaps

**Comment by flybayer** [comment]
@ryardley great point!

**Comment by flybayer** [comment]
@mikeattara have you been able to make any progress on this?

**Comment by merelinguist** [comment]
@mikeattara Do you mind if I work on this?

**Comment by flybayer** [comment]
@merelinguist it's been three months so I think the answer is yes 😄

**Comment by TatisLois** [comment]
@merelinguist how's this going, anyway I can support?

**Comment by rayandrews** [comment]
I try to create simple implementation of this issue and get this results:

```json
{
  "/Users/rayandrew/Projects/contributing/blitz/examples/auth/pages/404.tsx": {
    "uri": "/404",
    "verb": "GET",
    "type": "pages"
  },
  "/Users/rayandrew/Projects/contributing/blitz/examples/auth/pages/index.tsx": {
    "uri": "/index",
    "verb": "GET",
    "type": "pages"
  },
  "/Users/rayandrew/Projects/contributing/blitz/examples/auth/pages/ssr.tsx": {
    "uri": "/ssr",
    "verb": "GET",
    "type": "pages"
  },
  "/Users/rayandrew/Projects/contributing/blitz/examples/auth/pages/api/auth/[...auth].ts": {
    "uri": "/api/auth/[...auth]",
    "verb": "ANY",
    "type": "api"
  },
  "/Users/rayandrew/Projects/contributing/blitz/examples/auth/pages/api/auth/mutations/login.ts": {
    "uri": "/api/auth/mutations/login",
    "verb": "POST",
    "type": "rpc"
  },
  "/Users/rayandrew/Projects/contributing/blitz/examples/auth/pages/api/auth/mutations/logout.ts": {
    "uri": "/api/auth/mutations/logout",
    "verb": "POST",
    "type": "rpc"
  },
  "/Users/rayandrew/Projects/contributing/blitz/examples/auth/pages/api/auth/mutations/signup.ts": {
    "uri": "/api/auth/mutations/signup",
    "verb": "POST",
    "type": "rpc"
  },
  "/Users/rayandrew/Projects/contributing/blitz/examples/auth/pages/login.tsx": {
    "uri": "/login",
    "verb": "GET",
    "type": "pages"
  },
  "/Users/rayandrew/Projects/contributing/blitz/examples/auth/pages/signup.tsx": {
    "uri": "/signup",
    "verb": "GET",
    "type": "pages"
  },
  "/Users/rayandrew/Projects/contributing/blitz/examples/auth/pages/api/users/mutations/trackView.ts": {
    "uri": "/api/users/mutations/trackView",
    "verb": "POST",
    "type": "rpc"
  },
  "/Users/rayandrew/Projects/contributing/blitz/examples/auth/pages/api/users/queries/getCurrentUser.ts": {
    "uri": "/api/users/queries/getCurrentUser",
    "verb": "POST",
    "type": "rpc"
  },
  "/Users/rayandrew/Projects/contributing/blitz/examples/auth/pages/api/users/queries/getUser.ts": {
    "uri": "/api/users/queries/getUser",
    "verb": "POST",
    "type": "rpc"
  },
  "/Users/rayandrew/Projects/contributing/blitz/examples/auth/pages/api/users/queries/getUsers.ts": {
    "uri": "/api/users/queries/getUsers",
    "verb": "POST",
    "type": "rpc"
  },
  "/Users/rayandrew/Projects/contributing/blitz/examples/auth/pages/users/index.tsx": {
    "uri": "/users/index",
    "verb": "GET",
    "type": "pages"
  }
}
```

any thoughts for improvement? @flybayer 

I think it needs some improvement on `uri` field (especially the ones with param) to be more meaningful

**Comment by flybayer** [comment]
@rayandrews WOW, nice!!! PR that puppy!

Few thoughts:
- Replace `ANY` with `*`
- Remove `(.:format)` 
- I think the parameter is good, display in brackets, same as the page name.
- Probably want to display the file path in the results too (original file path, not the compiled path inside `.blitz`)

**Comment by rayandrews** [comment]
Got it @flybayer!

Here is the updated screenshot:
![image](https://user-images.githubusercontent.com/4437323/99502054-27485700-29af-11eb-86de-bd82bea0d919.png)

Notice that the `/wow` URI is coming from `blitz.config.js`.
I modify the API to be like this. I think this is good to have so users can add their own additional sitemap entries.

```js
module.exports = {
	sitemap: (routeCache) => [{uri: "/wow", type: "pages", verb: "get" /* path: */}],
};
```

What do you think?

I will open PR and connect this issue (quite a lot of changing, but I create tests to support
