### ISSUE TITLE
Queued queries starts after logout one last time

### ISSUE THREAD

**Issue by antonykamp** [blitz-js/blitz#2401]
### What is the problem?

hey :)

I have a query with a refetchIntervall, which should only run if the user is logged in. The problem is that after logging out, the query starts one last time. 

It looks like a queued query call is executed although it should no longer.

### Paste all your error logs here:

I don't have an error message except for the thrown AuthenticationError :)

### Paste all relevant code snippets here:

I build a small example:

https://github.com/antonykamp/entel/tree/find-logout-bug

The important parts are 
- the file with the query call: https://github.com/antonykamp/entel/blob/find-logout-bug/app/pages/index.tsx
- the dummy query: https://github.com/antonykamp/entel/blob/find-logout-bug/app/queries/checkLogin.ts
- the mutations of the signup, login, logout process: https://github.com/antonykamp/entel/tree/find-logout-bug/app/mutations

### What are detailed steps to reproduce this?

You need nodejs and docker :)

1. `git clone https://github.com/antonykamp/entel/tree/find-logout-bug`
2. `cd entel`
3. `npm i`
4. create `.env.local` including `POSTGRES_USER`, `POSTGRES_USER`, `POSTGRES_DB`, `DATABASE_URL`
5. `docker-compose up -d`
6. `blitz prisma migrate dev --preview-feature`
7. `blitz dev`

### Run `blitz -v` and paste the output here:

```
Linux 4.19 | linux-x64 | Node: v14.16.0

blitz: 0.34.3 (global)
blitz: 0.34.3 (local)

  Package manager: npm 
  System:
    OS: Linux 4.19 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 2.08 GB / 5.80 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.11.2 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.19 => 2.19.0 
    blitz: 0.34.3 => 0.34.3 
    prisma: ~2.19 => 2.19.0 
    react: >=0.14.0 => 17.0.2 
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    typescript: ~4.2.4 => 4.2.4 
```

### Please include below any other applicable logs and screenshots that show your problem:

![image](https://user-images.githubusercontent.com/45163503/119864791-4b1ac580-bf1b-11eb-8196-5cf55eaa6a60.png)

[`checkLogin`](https://github.com/antonykamp/entel/blob/find-logout-bug/app/queries/checkLogin.ts) should run every 2sec if the user is logged in (see the [query-call](https://github.com/antonykamp/entel/blob/131bacda97237c808402d4ba1a0240c2ee9ad2fa/app/pages/index.tsx#L10)). 

The first `checkLogin` call works fine because somebody is logged in. But after calling the [`logout` mutation](https://github.com/antonykamp/entel/blob/131bacda97237c808402d4ba1a0240c2ee9ad2fa/app/pages/index.tsx#L17), it's called one last time.
The [`getCurrentUser` call](https://github.com/antonykamp/entel/blob/131bacda97237c808402d4ba1a0240c2ee9ad2fa/app/pages/index.tsx#L49) returns `null` (nobody is logged in).

**Comment by flybayer** [comment]
Could you test this in https://github.com/blitz-js/blitz/releases/tag/v0.36.2? Because we made a fix that may affect this.

**Comment by antonykamp** [comment]
Sorry :/ it still does not work, unfortunately.
(I updated the branch https://github.com/antonykamp/entel/tree/find-logout-bug)

**Comment by remjx** [comment]
I think polling login status on an interval is an anti-pattern. Can you explain your use case?

**Comment by antonykamp** [comment]
Hm.. oke :D
In my use case, I want to fetch the users' groceries-lists from a database regularly (because they can change their status). Calling the query should only be possible if the user logged in.

**Comment by remjx** [comment]
Look into `cacheTime` and `staleTime` options on useQuery, they might be more appropriate but I haven't played with them to understand how they work.

Also keep in mind the user session cookie has an expiration that you can change.

I think refetchInterval is overkill because refetchOnWindowFocus is enabled by default, and I think this would catch the scenario of data changing 99.999%+ of the time unless they are logged in and active on multiple devices at the same time, and for a grocery app I don't see that happening. 

Databases like Google Firestore allow you to "subscribe" to a query to keep data in sync across devices. That is much more efficient than polling for changes.

Sorry this doesn't address your problem directly, but I think it will help you architect your code so it might make your problem a non-issue.

**Comment by antonykamp** [comment]
Thank you @remjx 🙏 Your hints were very helpful! I thought earlier that `staleTime` and `refetchInterval` are "the same thing". But that's not correct, because when I use `staleTime` the described errors don't occur! 🥳 

But why do these occur when I use `refetchInterval`? 🤔

**Comment by remjx** [comment]
https://react-query.tanstack.com/guides/caching explains how cacheTime and staleTime works. I think you'll want to leave them at default values actually.
