### ISSUE TITLE
add READMEs to blitz recipes

### ISSUE THREAD

**Issue by Talor-A** [blitz-js/blitz#2403]
### What do you want and why?

it's not very easy to understand what each recipe in the blitz recipe directory does without browsing the source of each one :( . It would be nice to have READMEs in each one, giving a quick overview of what the recipe does and links to more documentation. 

As an example, `gh-action-yarn-postgres` : the package.json description (the first place I'd check when I didn't find a README) says "The Blitz Recipe for adding github actions workflow with postgres". How do I know what problem this solves and why I'd want it? (I'm not picking on this recipe specifically, it's just an example). it's not that I can't browse the source and discover what it does, but one of the strengths of blitz is the community's commitment to great (and I mean really, all of the blitz docs are GREAT) documentation, so it feels strange that the recipes don't have individual docs too.

### Possible implementation(s)

add README.md to each recipe with something like:

```
## title of the recipe
< explanation of what problem this recipe solves >

## more information
< link to e.g. chakra homepage for chakra-ui recipe >

## contributors
< list of authors >
```

**Comment by MrLeebo** [comment]
Great idea!

**Comment by nsantos16** [comment]
I can take this issue :)

**Comment by flybayer** [comment]
@nsantos16 yes! There's quite a few recipes, so instead of assigning this to you for all of them, just open PRs for as many/few as you want :)

**Comment by beerose** [comment]
Update: only the `theme-ui` recipe is left :)

**Comment by beerose** [comment]
Thank you all for your contributions!
