### ISSUE TITLE
Implement blitz db reset command

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#241]
**What do you want and why do you want it?.**

Sometimes during dev things get out of wack and you need a sledgehammer.

`blitz db reset` should totally delete the database and then run migration to create the db fresh.

- Prompt user for confirmation
- Should work with SQLite, Postgres, and Mysql
- Should force close any existing connections to the DB. (A postgres `DROP TABLE` command will fail if anything is connected to it)

**Comment by LoriKarikari** [comment]
I'm up for this one 😊

**Comment by ryardley** [comment]
Would it be worth considering a blitz db seed command as well?

**Comment by flybayer** [comment]
@ryardley yes definitely!

**Comment by vavdoshka** [comment]
in case if someone will read this - this is how I managed to do it as of today:

`blitz prisma migrate reset && blitz db seed` with postgres DB.
