### ISSUE TITLE
Update our form templates to use new Zod error feature

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#2412]
### What do you want and why?

Currently [our `<Form>` templates](https://github.com/blitz-js/blitz/tree/canary/packages/generator/templates/app/_forms) use [`error.formErrors.fieldErrors`](https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/app/_forms/formik/Form.tsx#L40) to report zod form errors. 

But this doesn't work with nested objects in the form, so we need to update it to use `error.format()`. Example: https://twitter.com/colinhacks/status/1394326038570799105

For the other two, change to use `error.format()`.

**Comment by swinner2** [comment]
Was looking at this one. It looks like `error.format()` returns a formatted error object like 
`{ _errors: [], email: { _errors: [ 'Invalid email' ] } }`. Final-form expects an error object like `{ email: 'Invalid email'  }` . So does this task involve transforming the new zod object to be compatible with final-form/formik? 

Also, for `react-hook-form` it looks like those steps are already done to me, is this correct?

**Comment by flybayer** [comment]
> So does this task involve transforming the new zod object to be compatible with final-form/formik?

Yes

> Also, for react-hook-form it looks like those steps are already done to me, is this correct?

Ah, yes you are right!

**Comment by swinner2** [comment]
Looks like something like this would work 
```
          let formattedErrors = {}
          let errors = error.format()
          for (const key in errors) {
            if (key === "_errors") {
              continue
            }
            formattedErrors[key] = errors[key]["_errors"][0]
          }
          
          return formattedErrors
```
I'm not an expert on js at all so I'm not sure if this is the best way to transform an object. Would this transform code go into some kind of util we can import? If so, where would that util go?

**Comment by flybayer** [comment]
> Would this transform code go into some kind of util we can import? If so, where would that util go?

Yes I think so. You could put it in `packages/core/src/utils/index.ts`.

Make sure it works with nested form data too.

Actually, you might can copy most of the code from here: https://github.com/react-hook-form/resolvers/blob/master/zod/src/zod.ts

**Comment by swinner2** [comment]
@flybayer Could you check out the PR #2441? I think the function does the thing, but I'm not sure if the code is the best. So appreciate any feedback.

Also, how do we get the function into the form components? We need to use the function here https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/app/_forms/finalform/Form.tsx#L33
