### ISSUE TITLE
Third party recipes aren't found with Blitz v0.36.2

### ISSUE THREAD

**Issue by danestves** [blitz-js/blitz#2416]
### What is the problem?

With the latest version of Blitz i tried to install third party recipes but the script says that could not find remote recipe
![image](https://user-images.githubusercontent.com/31737273/120084664-03717680-c0a0-11eb-9837-5a454aa8ab3d.png)

### Paste all your error logs here:

```bash
✕ Could not find recipe "Nisaju/auth-tailwind"

Please provide one of the following:

1. The name of a recipe to install (e.g. "tailwind")
   - Available recipes listed at https://github.com/blitz-js/blitz/tree/canary/recipes
2. The full name of a GitHub repository (e.g. "blitz-js/example-recipe"),
3. A full URL to a Github repository (e.g. "https://github.com/blitz-js/example-recipe"), or
4. A file path to a locally-written recipe.
```

### Paste all relevant code snippets here:

```bash
blitz install Nisaju/auth-tailwind
```

### What are detailed steps to reproduce this?

1. Install a `blitz new blitzApp`
2. Execute `blitz install Nisaju/auth-tailwind`

### Run `blitz -v` and paste the output here:

```bash
macOS Big Sur | darwin-x64 | Node: v14.17.0

blitz: 0.36.2 (global)

  Package manager: npm 
  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 117.73 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.14.0 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```

**Comment by Anjianto** [comment]
@danestves Hmmm.... I can install this recipe with the same version of Blitz. But i don't if this install with macOS, i use Linux Ubuntu and it still good. Maybe you can try with nisaju/auth-tailwind, it also work for me. And maybe someone can try if use macOS

Sir, @flybayer can you try this, please?
