### ISSUE TITLE
Change all user facing references of "next.js" to "blitz.js"

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#2434]
### What do you want and why?

As we move towards full integration of the next.js fork, we need to change all user facing references to "next.js" to Blitz.

### Possible implementation(s)

Search through all the code inside `nextjs/packages/next/` folder and make the following changes:

- `next.config.js` -> `blitz.config.js`
- `Next.js` -> `Blitz.js` 
- All CLI commands. Example: `next start` -> `blitz start`

You do *not* need to update code comments, variables names or anything. This task is only for updating user facing text in things like error messages and help text.

**Important Note:** this will also require updating a lot of integration tests inside `nextjs/test/` which test user facing strings. So search through this folder as well and update what you can find. Then you can push and let CI run all the tests, see the errors, and update more tests as needed.

**Comment by NamamiShanker** [comment]
I'll take up this issue

**Comment by ashikka** [comment]
Hey! I was already working on this. Can you review my PR?
