### ISSUE TITLE
Add a setPublicData(userId, publicData) API to update active user sessions (i.e. update a user's role)

### ISSUE THREAD

**Issue by lksnmnn** [blitz-js/blitz#2449]
### What do you want and why?
I want to be able to update publicData in users' sessions, such that the changes are reflected and used, when the user is doing the next request.

My example use case is changing a user's role. Assuming a user has the role ADMIN and I want to change that user's role to USER, then ideally I could update the user's session such that the new role is being enforced in future requests done by said user.

Right now I need to delete all active sessions of that user to make sure that the user has no ADMIN access anymore. As the user does not expect to be forcefully logged out, the UX for this is quite bad.

### Possible implementation(s)

How might we do this?
Write a helper function which updates all active sessions of a user with the provided session data.

```ts
export const setPublicData = async (userId, publicData) {
   await db.session.update({ where: { userId }, data: { publicData } }) 
}
```

### Additional context

See discord discussion: https://discord.com/channels/802917734999523368/843912213399601192/850068347453440030

**Comment by lksnmnn** [comment]
Ha, I've hacked this together in our app and this seems to work.

```
import db from "db"

export const setPublicData = async (userId: string, publicData) => {
  const publicDataString = JSON.stringify(publicData)
  // update all of the user's sessions
  await db.session.updateMany({ where: { userId }, data: { publicData: publicDataString } })
}
```

**Comment by flybayer** [comment]
Yes!! Definitely need this. Your code looks pretty much like we need with one exception. 

Currently all `setPublicData` calls **merge** values with existing publicData. So probably we should take the same approach here? Our current code to do this is here: https://github.com/blitz-js/blitz/blob/canary/packages/core/src/server/auth/sessions.ts#L927-L935


For whoveever wants to work on this:

- Add this new API to https://github.com/blitz-js/blitz/blob/canary/packages/core/src/server/auth/sessions.ts
- Add new API export to this file: https://github.com/blitz-js/blitz/blob/canary/packages/core/src/server/index.ts

**Comment by lksnmnn** [comment]
I've added this rudimentary version of a `setPublicData` function. It *works* but the corresponding user will expierence weird CSRF / Invalid Session issues. So maybe there is another bug, that will surface during development.

Since all sessions of a user could potentially be in use, we need to update each session with the new data. An additional merging step is not needed (?).

Here is my current code:

```ts
import db from "db"

export const setPublicData = async (userId: string, newPublicData) => {
  const sessions = db.session.findMany({ where: { userId } }) // maybe only update sessions that are not expired
  for (const session of sessions) {
    const publicData = JSON.stringify({
      ...(session.publicData ? JSON.parse(session.publicData) : {}),
      ...newPublicData,
    }) 
    await db.session.update({ where: { handle: session.handle }, data: { publicData } })
  }
}
