### ISSUE TITLE
Page.authenticate should (optionally) keep current query parameters in the next query parameter when redirectingTo

### ISSUE THREAD

**Issue by lksnmnn** [blitz-js/blitz#2450]
### What do you want and why?
When I use `Page.authenticate` to redirect an unauthenticated user to some page, I want current query parameters to be included in the `next` redirect path.

In the following example I am on `MyPage` with a query parameter set (`token=abcd`).

```ts
// current behaviour
MyPage.authenticate = {
  redirectTo: "/login"
}
// redirects to  /login?next=/my-page

// new feature
MyPage.authenticate = {
  redirectTo: "/login",
  redirectBackTo: "/my-page", // defaults to current page
  includeQueryParameter: true // defaults to false, as this is the current behavoir
}
// redirects to /login?next=/my-page?token=abcd
```

Please imagine URL encoding for the next query parameter value ;)

My use case is that the user clicks on a link including a token query paramter used for joining an org. The user needs to be logged in for this to work, so I do need to redirect the user to the login page. After the user logged in the user should be redirected back to the previous page including that token.

My solution now (since I had that gSSP bug) is to build that next parameter manually and redirect using a `useEffect` hook

```
  useEffect(() => {
    if (!session.userId) {
      router.push(Routes.LoginPage({ next: `/join-team?token=${token}` }))
    }
  }, [session, token])
  ```

### Possible implementation(s)
```
MyPage.authenticate = {
  redirectTo: "/login",
  redirectBackTo: "/my-page", // defaults to current page
  includeQueryParameter: true // defaulst to false, as this is the current behavoir
}
```

**Comment by flybayer** [comment]
Thanks @lksnmnn!

What about including query params by default? Seems like probably most people would want this.

As for the API, I'm thinking this may be better:

```ts
MyPage.authenticate = {
  redirectTo: {
    path: '/login',
    next: "/my-page", // defaults to current page
    includeQueryParameters: false // defaults to true
  }
}
```

**Comment by lksnmnn** [comment]
> As for the API, I'm thinking this may be better:

Yes. Naming is hard. I think including the params by default is what a user would expect.
