### ISSUE TITLE
Relative imports are broken when used in pages

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#246]
**What is the problem?**

Relative imports like `import x from '../../x'` are broken when used inside pages.

This is because we compile pages to a different structure but aren't updating the file path.

**Workaround**

Always import from the project root, so `import x from 'app/components/x'`

**Implementation**

During the build step, maybe we can just transform the relative import into an absolute import from the project root?

**Comment by MrLeebo** [comment]
@flybayer Won't transforming the path at build time mean that the imports still won't work during unit tests? Or do tests perform the same build steps?

**Comment by ryardley** [comment]
> During the build step, maybe we can just transform the relative import into an absolute import from the project root?

Great idea

**Comment by ryardley** [comment]
> @flybayer Won't transforming the path at build time mean that the imports still won't work during unit tests? Or do tests perform the same build steps?

You probably won't be able to unit test pages that use relative imports as RPC won't be available.

**Comment by flybayer** [comment]
Relative imports would still work for unit tests since blitz doesn't do any compiling during this.

Relative imports only break when blitz compiler puts the pages in a different directory structure inside `.blitz/caches/`

**Comment by mbrookson** [comment]
@flybayer Think I've found an issue related to this.

It seems like the relative import fix above doesn't seem to work for css files.

![image](https://user-images.githubusercontent.com/20131783/86845134-f707b800-c0a0-11ea-8845-0792b92bdf16.png)

![image](https://user-images.githubusercontent.com/20131783/86845262-23bbcf80-c0a1-11ea-8b46-6bcb2b76c45a.png)

The file `app/styles/styles.css` exists. However, in `app/pages/_app.tsx` I can't seem to import the css with a relative path.
- `import app/styles/styles.css` - Works ✅
- `import ../styles/styles.css` - Doesn't work ❌

Tested the same thing for the sibling `theme.ts` file and that works both ways.
- `import { theme } from app/styles/theme` - Works ✅
- `import { theme } from ../styles/theme` - Also works ✅

**Comment by flybayer** [comment]
@mbrookson can you test this again in `0.16.3`? (just released) I think #733 probably fixed that.

**Comment by mbrookson** [comment]
@flybayer It is indeed fixed in `0.16.3` 🎉
