### ISSUE TITLE
BlitzConfig is missing typings for some nextjs configurations

### ISSUE THREAD

**Issue by lksnmnn** [blitz-js/blitz#2466]
### What is the problem?

When extending the `BlitzConfig` with nextjs specific configurations like `images`, `env` or external configs (`pwa`), TS throws type errors.

Quoting from Dan Greaves  [comment on Discord](https://discord.com/channels/802917734999523368/814627656611397692/852072311073931274)

> @lksnmnn annoyingly, next doesn't actually type all the config options, even though they work just fine. In the `BlitzConfig` type (https://github.com/blitz-js/blitz/blob/canary/packages/config/src/index.ts#L15), note that it extends `PublicNextConfig` (https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/next-server/server/config-shared.ts#L12). I think `BlitzConfig` should actually extend `NextConfig` (https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/next-server/server/config-shared.ts#L69) which includes the` Record<string, any>` which allows you to put any other key in, which matches Next. Either that or the missing types need to be added into `BlitzConfig`. I would probably open an issue for it and see what the blitz guys think.

With a temporary solution on top:
> In the mean time, you can change your config type to `BlitzConfig & Record<string, any>` - that will allow you to add the images key without typescript complaining about it.
It's referenced this way in the actual Blitz documentation too, so it should work: https://blitzjs.com/docs/image-optimization#domains

### Paste all your error logs here:

```
type images does not exist on BlitzConfig
```

### Paste all relevant code snippets here:

```
const config: BlitzConfig = {
   ...
  images: {
    domains: ["localhost"],
  },
 ...
}
```

### What are detailed steps to reproduce this?

n/a

### Run `blitz -v` and paste the output here:

```
acOS Catalina | darwin-x64 | Node: v14.17.0

blitz: 0.36.4 (global)
blitz: 0.37.0 (local)

  Package manager: yarn 
  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 29.16 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 7.16.0 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1 
    blitz: 0.37.0 => 0.37.0 
    prisma: ~2.20 => 2.20.1 
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    typescript: ~4.2 => 4.2.4 
```

**Comment by flybayer** [comment]
Thanks @lksnmnn!

For whoever wants to work on this. let's fix `BlitzConfig` to also extend from `Record<string, any>` which needs changed here: https://github.com/blitz-js/blitz/blob/canary/packages/config/src/index.ts#L15

**Comment by dangreaves** [comment]
Hey @flybayer - is there a reason we shouldn't extend [NextConfig](https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/next-server/server/config-shared.ts#L69), rather than adding the `Record` type ourselves?
