### ISSUE TITLE
Disable scripts on blitz install

### ISSUE THREAD

**Issue by prisis** [blitz-js/blitz#2467]
### What do you want and why?

Package/Recipe scripts are run on blitz install repo/name 

### Possible implementation(s)

Disable scripts on blitz install

### Additional context

Example:  
 

```
{
    "scripts": {
        "preinstall": "node verify-node-version.cjs",
        "postinstall": "husky install"
    },
}
```

**Comment by prisis** [comment]
Disable maybe only all default npm scripts, tbd.

**Comment by flybayer** [comment]
Thanks! For whoever wants to work on this, you can change the install args here: https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/install.ts#L247

**Comment by prisis** [comment]
If im correct than "node-sass" will be not installed too, because its use the scripts to build some needed stuff, bit tricky

**Comment by flybayer** [comment]
Any deps you need should be specified as dependencies, which should work, right?

**Comment by flybayer** [comment]
I guess this is a tricky question on whether to ignore scripts or not 🤔

**Comment by prisis** [comment]
Yeah, its what i was thinking to, you adding all needed deps in the index.ts so it should work, i dont know a use case for scripts in recipes.  
  
Checked gatsby  but didnt find anything about scripts there

**Comment by prisis** [comment]
Looks likes nobody has a problem with it, would create a PR asap
