### ISSUE TITLE
Generated Edit Page Has Buggy Form Behavior

### ISSUE THREAD

**Issue by dbachrach** [blitz-js/blitz#2481]
### What is the problem?

The generated Edit page for a model has the following buggy behavior: If a user types into the form, clicks outside of the browser window and then clicks back into the browser window, the form will be reverted to the original content. I've tracked down why this happens. The edit page has a `react-query` query with default behavior. This means the query is re-fetched frequently (e.g. window refocus). Each time that query runs, the resulting value gets sent into the form as it's `initialValues`. The issue is that this payload object is not shallow equal after each query re-fetch. So the form thinks it gets a new `initialValues` and it wipes what the user has typed in and resets it. 

react-query has some form of query result equality checking built in to prevent this. However, the equality they perform does not handle date equality so it seems. Since the default Prisma models contain  `createdAt` and `updatedAt` date fields, react-query incorrectly thinks the response is different each time. You can actually tweak your `getProjects` blitz query to only return `id` and `name`, and the form behaves properly. Change:

```
const project = await db.project.findFirst({
    where: { id }
})
```

to:

```
const project = await db.project.findFirst({
    where: { id },
    select: { name: true, id: true },
})
```

So one option is to try to work with the react-query folks to see if this is intentional or if we can augment the default equality check (some discussion here: https://github.com/tannerlinsley/react-query/discussions/433).

The other option, which may in fact be more proper, is to simply add `{ staleTime: Infinity }` in the Edit page template when calling `useQuery`. Since the user is editing the data, it's probably correct to "freeze" the data in time when this page loads and never refetch it.

Happy to make a PR if we want to go with the `staleTime` fix.

### Paste all your error logs here:

```
n/a
```

### Paste all relevant code snippets here:

```
n/a
```

### What are detailed steps to reproduce this?

1. `blitz new newapp`
2. `cd newapp`
3. `blitz generate all project name:string`
4. `blitz dev`
5. Login so you can access localhost:3000/projects
6. Create a new project with name "Test"
7. Navigate to edit the project (http://localhost:3000/projects/1/edit)
8. Start typing in the name field to change the name to "Test123"
9. Click your mouse outside the browser window
10. Click your mouse inside the browser window
11. The text field is changed from "Test123" to "Test"

### Run `blitz -v` and paste the output here:

```
macOS Mojave | darwin-x64 | Node: v14.16.0

blitz: 0.37.0 (global)
blitz: 0.37.0 (local)

  Package manager: yarn
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 106.83 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/client: 2.24.1 => 2.24.1
    blitz: 0.37.0 => 0.37.0
    prisma: 2.24.1 => 2.24.1
    react: 0.0.0-experimental-0eea57724 => 0.0.0-experimental-0eea57724
    react-dom: 0.0.0-experimental-0eea57724 => 0.0.0-experimental-0eea57724
    typescript: ~4.2 => 4.2.4

```

**Comment by flybayer** [comment]
Thank you @dbachrach!!

1. We should open an issue or PR to react-query to fix Date equality since this is very common case for us.
2. The `staleTime` approach sounds reasonable, but it seems that if the data does change then the user may care to know about it, right?
  - my current solution for this problem is passing a deep equals function to `initialValuesEqual` prop on react final form. So an alternative to `staleTime` is add a deepEquals function to blitz core (inline `fast-deep-equals`) and add this to the template.

What do you think?

**Comment by dbachrach** [comment]
1. Yes I'll open an issue in react-query
2. Yeah I think this is a tricky UX issue. If you are editing a field and someone else changes it while you are editing, it would be nice to know that that has occured, but you also wouldn't want to just clear the form to the new value. The user might be writing a long piece of text and suddenly have it all deleted. I'm trying to think of any form experiences in apps that deal with this. Everything I can think of treats it as frozen data. You also have things like Google Docs level collab editing, but that seems different. I'm interested to see what the community thinks about this.

**Comment by flybayer** [comment]
Ok you've made a fair point. Let's go with the `staleTime` fix

**Comment by flybayer** [comment]
And add a comment in the template next to staleTime saying why it's there

**Comment by dbachrach** [comment]
So this specific issue is now fixed but to trigger less react re-renders, we should consider adding something like this to the main app:

```
import { QueryClient } from "blitz"
import fastDeepEqual from "fast-deep-equal"

new QueryClient({
  defaultOptions: {
    queries: {
      isDataEqual: fastDeepEqual,
    },
  },
});
```

**Comment by flybayer** [comment]
@dbachrach want to PR that? Let's export `deepEqual` as a core utility for people to use
