### ISSUE TITLE
Importing db in custom server throws an error

### ISSUE THREAD

**Issue by smashboy** [blitz-js/blitz#2490]
### What is the problem?

Hello everyone! I'm setting up a custom server and I've encountered weird bug with db import. I don't know why, but if I import db after my utils, blitz wont start. If I import db before utils import everything is working fine.

![image](https://user-images.githubusercontent.com/30213662/122099720-01871180-ce1b-11eb-8acb-2764cbbcd68f.png)

### Paste all your error logs here:

```
/sandbox/.blitz/custom-server.js:49
var EnhancedPrisma = (0, import_blitz.enhancePrisma)(import_client.PrismaClient);
                                                    ^

TypeError: (0 , import_blitz.enhancePrisma) is not a function
    at Object.<anonymous> (/sandbox/.blitz/custom-server.js:49:53)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

### Paste all relevant code snippets here:

Codesandox reproduciton: [LINK](https://codesandbox.io/s/blitz-db-import-issue-t6nyp?file=/server/someListener.ts)

### What are detailed steps to reproduce this?

1. Just change import order of `utils` and `db` in `server/someListener.ts`

### Run `blitz -v` and paste the output here:

```
Windows 10 | win32-x64 | Node: v14.17.0

blitz: 0.33.1 (global)
blitz: 0.37.0 (local)

  Package manager: yarn
  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 6.74 GB / 15.95 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.22.1 => 2.22.1
    blitz: 0.37.0 => 0.37.0
    prisma: 2.22.1 => 2.22.1
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    typescript: ~4.1 => 4.1.5
```

**Comment by flybayer** [comment]
Thanks for this issue! It must have something to do with esbuild which we use to bundle the custom server 🤔

**Comment by flybayer** [comment]
@smashboy so sorry for the long delay here.

This is so odd. Can you share your code where import order matters and which file paths those are?

**Comment by smashboy** [comment]
@flybayer Here is a gist with main files that are related to this issue: https://gist.github.com/smashboy/5b64ba6044a69cc44d242a9dc111a559. There are comments in `updateTwitchEventReward.ts` that are describing an issue. Hope it will help.

**Comment by flybayer** [comment]
@smashboy thank you. This is so weird. These files are processed by webpack, not esbuild like the custom server.

Does it work if you import using a relative path like `import db from '../../../db'`?

**Comment by flybayer** [comment]
It appears like maybe the issue is if you import db after importing something from blitz. The pattern so far is that if db import is first in the file, it works, right?

**Comment by smashboy** [comment]
> @smashboy thank you. This is so weird. These files are processed by webpack, not esbuild like the custom server.
> 
> Does it work if you import using a relative path like `import db from '../../../db'`?

@flybayer Looks like the issue is in [next-translate](https://www.npmjs.com/package/next-translate#add-next-translate-plugin) plugin that I'm using. I'm not able to reproduce this error if I remove it from `blitz.config.ts`. Also let me remind that I'm using custom server, maybe this information also can be helpful.

Relative path reacts the same and I start to think that db import order does not matter, because I've launched fresh server with db imported after imports from blitz and it worked, but when I moved db import to top it brakes again. So it brakes after changing import order and it is hard to reproduce this error consistently. Like I've just changed import order again and it was not working until I remounted component.

**Comment by smashboy** [comment]
@flybayer As it is kind of another issue, should I open a new issue for that? There is one more issue when using next-translate with blitzjs.

**Comment by smashboy** [comment]
@flybayer Should I open another issue, because this latest one is kind of not ralated? I also have another issue with next-translate that I did not opened yet.

**Comment by flybayer** [comment]
@smashboy you can open another issue for next-translate, although likely it requires a fix inside next-translate itself

And can you try latest `blitz@canary` release to see if the issue goes away, or if not, share the error and stack trace you get with that release.
