### ISSUE TITLE
Allow RouteURLObject in GetServerSideProps redirect

### ISSUE THREAD

**Issue by remjx** [blitz-js/blitz#2519]
### What do you want and why?

[Currently](https://blitzjs.com/docs/redirects#on-the-server), the expected type of GetServerSideProps' `redirect.destination` is `string`. 

It would be nice if we could pass one of our Route Manifest objects into this field.

### Possible implementation(s)

- ~Add a `toString()` method to the route manifest~ (will be covered by https://github.com/blitz-js/blitz/issues/2829)
- Update type of `redirect.destination` to handle RouteURLObject

### Additional context

N/A

**Comment by flybayer** [comment]
Great idea! Let's modify redirect.destination type

To implement we need to modify the following and maybe more:
- https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/types/index.d.ts#L45
- https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/next-server/server/next-server.ts#L1527
- https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/build/webpack/loaders/next-serverless-loader/page-handler.ts#L367
- https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/next-server/server/render.tsx#L324

**Comment by esemeniuc** [comment]
This is very much requested as well! I am doing manual string concatenation as a workaround
