### ISSUE TITLE
Anchor tags append `/pages` to links

### ISSUE THREAD

**Issue by ospfranco** [blitz-js/blitz#2521]
### What is the problem?

I was following the third party login tutorial, when the time came to create a link to the `/api/auth/[service]` endpoint, I placed the anchor tag in my component:

```
<a href="/api/auth/github">
	Login with Github
</a>
```

However, when I click on the link I get redirected to:

`http://localhost:3000/pages/api/auth/gihub`

the `pages` part of the URI is being prepended to a blank blitz project.

### Paste all your error logs here:

No Error logs

### Paste all relevant code snippets here:

```
<a href="/api/auth/github">
	Login with Github
</a>
```

### What are detailed steps to reproduce this?

1. Create any <a> link and the href will get prefixed with a `pages/`

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v14.17.0

blitz: 0.38.1 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.4
    CPU: (8) x64 Apple M1
    Memory: 356.86 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.volta/tools/image/node/14.17.0/bin/node
    Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
    npm: 6.14.13 - ~/.volta/tools/image/node/14.17.0/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  npmPackages:
    @prisma/client: 2.24.1 => 2.24.1 
    blitz: 0.38.1 => 0.38.1 
    prisma: 2.24.1 => 2.24.1 
    react: 0.0.0-experimental-0eea57724 => 0.0.0-experimental-0eea57724 
    react-dom: 0.0.0-experimental-0eea57724 => 0.0.0-experimental-0eea57724 
    typescript: 4.3.4 => 4.3.4 
```

**Comment by flybayer** [comment]
That's odd. What's the code you have in the `/api/auth/[service]` route?

**Comment by ospfranco** [comment]
I followed the guide on the website: https://blitzjs.com/docs/passportjs

I have nothing out of the ordinary, but the name of the file is: `/api/auth/[...auth].ts`

**Comment by flybayer** [comment]
Ok thanks @ospfranco. We just need someone who's interested to investigate.

Can you also post the contents of your blitz.config.js?

**Comment by ospfranco** [comment]
```
import { BlitzConfig, sessionMiddleware, simpleRolesIsAuthorized } from "blitz"

const config: BlitzConfig = {
  middleware: [
    sessionMiddleware({
      cookiePrefix: "numbra",
      isAuthorized: simpleRolesIsAuthorized,
    }),
  ],
  /* Uncomment this to customize the webpack config
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    // Note: we provide webpack above so you should not `require` it
    // Perform customizations to webpack config
    // Important: return the modified config
    return config
  },
  */
}
module.exports = config
```

**Comment by ospfranco** [comment]
I keep testing this and the behavior looks really broken, I replaced the partial href to a full http address and the output is still `pages/[my route]`.


<img width="2181" alt="Screenshot 2021-07-01 at 11 09 47" src="https://user-images.githubusercontent.com/1634213/124098583-f2c86d80-da5c-11eb-966f-7e79f02c9abb.png">

**Comment by ospfranco** [comment]
Anyways, using the router hook and directly pushing the route is working, just in case anybody else runs into the same issue

**Comment by flybayer** [comment]
@ospfranco ah! I bet I know why, and it should already be fixed. Can you test `0.38.3-canary.1` and see it that fixes it?

**Comment by ospfranco** [comment]
I got the following error on my terminal after upgrading and trying to run `blitz dev`
```bash
/Users/osp/Developer/numbra osp@airness git:(main*)
yarn blitz dev
yarn run v1.22.10
$ /Users/osp/Developer/numbra/node_modules/.bin/blitz dev
 ›   Warning: dev is not a blitz command.
Did you mean help? [y/n]: (node:53593) [MODULE_NOT_FOUND] Error Plugin: @blitzjs/cli: Cannot find module '/Users/osp/Developer/numbra/node_modules/@blitzjs/cli/lib/src/check-before-running'
Require stack:
- /Users/osp/Developer/numbra/node_modules/@oclif/config/lib/config.js
- /Users/osp/Developer/numbra/node_modules/@oclif/config/lib/index.js
- /Users/osp/Developer/numbra/node_modules/@oclif/command/lib/command.js
- /Users/osp/Developer/numbra/node_modules/@oclif/command/lib/index.js
- /Users/osp/Developer/numbra/node_modules/@blitzjs/cli/lib/src/index.js
- /Users/osp/Developer/numbra/node_modules/blitz/cli/dist/blitz-cli.cjs.dev.js
- /Users/osp/Developer/numbra/node_modules/blitz/cli/dist/blitz-cli.cjs.js
module: @oclif/config@1.17.0
task: runHook init
plugin: @blitzjs/cli
root: /Users/osp/Developer/numbra/node_modules/@blitzjs/cli
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)

 ›   Error: Run blitz help for a list of available commands.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ospfranco** [comment]
Just as another data point, I seem to have ran into the same issue, when doing a `fetch` request to a custom api endpoint:

```ts
const response = await window.fetch(`/api/reports/${report.id}/pdf`, {
      method: "POST",
      credentials: "include",
    })
    ```

**Comment by ospfranco** [comment]
Just as another data point, I have run into the same issue when trying to query a custom endpoint via fetch (and axios):

```ts
const triggerPdfDownload = async () => {
    try {
      const response = await axios({
        method: "POST",
        url: `http://localhost:3000/api/reports/${report.id}/pdf`,
        withCredentials: true,
      })
    } catch (e) {
      console.warn("error fetsching pdf", e)
    }
  }
```

somehow the server tries to return a `pages/` component, instead of calling the `api/` component

**Comment by flybayer** [comment]
Alright, I fixed that Cannot find module error and made a full release: https://github.com/blitz-js/blitz/releases/tag/v0.38.3

Let me know if that fixes this or not

**Comment by ospfranco** [comment]
Hi, I just tried it with both latest releases (0.38.3 and 0.38.4) and neither of them works still

**Comment by ospfranco** [comment]
Sorry! there was a small mistake on my part, but anchor links are now properly working, thanks a lot!

**Comment by ospfranco** [comment]
Seems this broke again, I'm now creating a different app, and whenever I try log via OAuth I get a very brief error flash

![723ab66a-4815-4430-9319-4d10e0d13af3](https://user-images.githubusercontent.com/1634213/138179569-934eec59-32b8-4082-9a67-069d018a270d.png)
