### ISSUE TITLE
`generate all question text:string` creates forms/resolvers with `name` rather than `text`

### ISSUE THREAD

**Issue by corysimmons** [blitz-js/blitz#2530]
### What is the problem?

I followed [the tutorial instructions](https://blitzjs.com/docs/tutorial#scaffolding-code-for-our-models) and it seems like [the question was created correctly](https://user-images.githubusercontent.com/224636/123285249-e1bab200-d4da-11eb-996b-73dea1d4791d.png) in the schema.

![image](https://user-images.githubusercontent.com/224636/123285723-4b3ac080-d4db-11eb-87aa-534dcda3d760.png)

But when I go to use the form or mutations, it asks for the `name`. I don't know where it is getting that from... I would expect it to reference `text` everywhere since the command was `blitz generate all question`**`text:string`**.

<img src="https://user-images.githubusercontent.com/224636/123285953-7ae9c880-d4db-11eb-904a-199a0065db7f.png" width="200">

It seems like even the types break.

![image](https://user-images.githubusercontent.com/224636/123286157-ac629400-d4db-11eb-9108-2fda5dc9e2d6.png)

### Paste all your error logs here:

```
10:43:50.948 INFO createQuestion() Starting with input:
{
  name: 'panda'
}
10:43:50.959 ERROR createQuestion()
 Error
Invalid `prisma.question.create()` invocation:

{
  data: {
    name: 'panda',
    ~~~~
+   text: String,
?   createdAt?: DateTime,
?   updatedAt?: DateTime
  }
}

Unknown arg `name` in data.name for type QuestionCreateInput. Did you mean `text`?
Argument text for data.text is missing.

Note: Lines with + are required, lines with ? are optional.

details:
{
  clientVersion: '2.25.0'
}
error stack:
• index.js:32546 validate
    node_modules/@prisma/client/runtime/index.js:32546:19

• index.js:34652 _executeRequest
    node_modules/@prisma/client/runtime/index.js:34652:17

• index.js:34597 consumer
    node_modules/@prisma/client/runtime/index.js:34597:23

• index.js:34599 <anonymous>
    node_modules/@prisma/client/runtime/index.js:34599:47

• async_hooks.js:197 runInAsyncScope
    async_hooks.js:197:9

• index.js:34599 _request
    node_modules/@prisma/client/runtime/index.js:34599:25

• index.js:34707 then
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1. `npm install -g blitz --legacy-peer-deps`
2. `blitz new my-blitz-app`
3. `blitz generate all question text:string`
4. `blitz dev`
5. Navigate to http://localhost:3000/questions/new
6. Enter anything into the input and submit

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v14.17.1

blitz: 0.38.1 (global)
blitz: 0.38.1 (local)

  Package manager: yarn
  System:
    OS: macOS 11.4
    CPU: (8) x64 Apple M1
    Memory: 147.97 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.18.1 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.25.0 => 2.25.0
    blitz: 0.38.1 => 0.38.1
    prisma: 2.25.0 => 2.25.0
    react: alpha => 18.0.0-alpha-d7dce572c
    react-dom: alpha => 18.0.0-alpha-d7dce572c
    typescript: ~4.3 => 4.3.4
```

**Comment by flybayer** [comment]
Hey @corysimmons! Sorry for the abnormally long delay here. This is a know issue that we address in the tutorial.

We are currently tracking this in https://github.com/blitz-js/blitz/issues/2038 and will be fixed with https://github.com/blitz-js/blitz/pull/2134. So I'm going to go ahead and close this as duplicate. Hopefully that's ok :)
