### ISSUE TITLE
Add support for application/database monitoring i.e. Prometheus/Grafana, Sentry, etc

### ISSUE THREAD

**Issue by remjx** [blitz-js/blitz#2539]
### What do you want and why?

To monitor the status of application and database using [Prometheus](https://prometheus.io/)/[Grafana](https://grafana.com/), [Sentry](https://sentry.io), or others. 

### Possible implementation(s)

- Ensure blitz exposes necessary code to be able to wrap API calls (queries/mutations) with the monitoring SDKs. Brandon mentioned adding "error middleware" to capture/track any errors.
- Since Blitz is the "_Full Stack_ React Framework", create a new section in docs to outline how to set this up
- Add recipes (this is the lowest priority and would be a _nice-to-have_ after the first two bullets above)

### Additional context

Here is the guide to setup Sentry with a Next.js app but not everything is applicable Blitz https://docs.sentry.io/platforms/javascript/guides/nextjs/

As a workaround before this is supported natively, you can add try/catches with Sentry.captureException inside each query/mutation.

**Comment by kdasme** [comment]
Picked blitz for my project, my current plan is to set up something like https://github.com/jochen-schweizer/express-prom-bundle to provide node/web server metrics. Sentry is also vital at this point.

🤞 will report back in a few weeks. Or ping me if I forget to! :)
