### ISSUE TITLE
Default logo for development site should be different version of the blitz logo

### ISSUE THREAD

**Issue by elmehalawi** [blitz-js/blitz#2544]
### What do you want and why?

This is a small quality of life change, but it would be nice if the default logo included in blitz is a different version from the one used on the blitz website. This would make it really easy to distinguish a tab with a dev site from tabs with the blitz documentation

### Possible implementation(s)

For example, the colors could be inverted so that it's white on purple instead. Alternatively, the background could be changed to black in the dev logo.

### Additional context

An example of this would be what hasura does:

<img width="159" alt="Screen Shot 2021-07-04 at 7 43 54 PM" src="https://user-images.githubusercontent.com/2058016/124404352-2c6cd300-dd00-11eb-9552-f75932b04d66.png">

**Comment by flybayer** [comment]
Good idea, thank you!

Currently we just have favicon file in the `/public` folder. To do this, I think we'd need to specifically link to it using `<Head>`, right? 

Here's the template file for _app where we can do that: https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/app/app/pages/_app.tsx

**Comment by Ghosts** [comment]
> Good idea, thank you!
> 
> Currently we just have favicon file in the `/public` folder. To do this, I think we'd need to specifically link to it using `<Head>`, right?
> 
> Here's the template file for _app where we can do that: https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/app/app/pages/_app.tsx

Wouldn't just swapping out the `facivon.ico`  [in the public folder](https://github.com/blitz-js/blitz/tree/canary/packages/generator/templates/app/public) with one that isn't purple work too?

**Comment by Ghosts** [comment]
> @Ghosts no, because as is that file provides the icon for both dev and production. We have to manually link to different files based on dev/prod in order to swap it.

Ah gotcha - I thought the intent was just to differentiate a site using Blitz from the docs site _for_ blitz by having different favicons.

**Comment by elmehalawi** [comment]
Personally, I would just be happy with the whole dev site changing, since in production I'm going to replace it with a real icon anyway. It's just that in the early stages of development, I'm not focused on the bookkeeping stuff like the icon so I leave the default, and that makes it hard to distinguish it from the docs, which I also have open.

**Comment by flybayer** [comment]
Oh oh, I misread the original issue! Sorry about that. Then yes all we need to do is replace the favicon in our template.

Here's all the current options we have: https://github.com/blitz-js/art/tree/master/Favicons But we can make a new one if needed too.
