### ISSUE TITLE
Chakra-ui recipe should update the LabeledTextField with Chakra's Input component

### ISSUE THREAD

**Issue by laubonghaudoi** [blitz-js/blitz#2550]
Right now, installing Chakra UI with the recipe does not update the `LabeledTextField` component. The recipe should update the raw HTML `<input></input>` with Chakra's `<Input></Input>` component.

### Suggested Fixes

In `app/core/components/LabeledTextField`, make the following changes(omitting the imports):

```diff
- export interface LabeledTextFieldProps extends PropsWithoutRef<JSX.IntrinsicElements["input"]>
+ export interface LabeledTextFieldProps extends ComponentPropsWithoutRef<typeof Input>

- <input disabled={isSubmitting} {...register(name)} {...props} />
+ <Input disabled={isSubmitting} {...register(name)} {...props} />
```

Maybe the `<style jsx>{`...`}</style>` should also be removed, and the `<div></div>`should also be updated with Chakra's `<Box></Box>`.

**Comment by flybayer** [comment]
Thanks! For whoever wants to work on this, the chakra recipe file is here: https://github.com/blitz-js/blitz/blob/canary/recipes/chakra-ui/index.ts

**Comment by muyiwaolu** [comment]
Happy to work on this if nobody else wants to.

**Comment by abuuzayr** [comment]
@muyiwaolu you are very welcome to, thank you!

**Comment by laubonghaudoi** [comment]
Just asking, should the recipe also replace the `<div>` with Chakra's `<Box>`, also the `<button>` with Chakra's `<Button>`? Also if we do this, the recipe should also remove unnecessary `<style global jsx>` in the codes.

**Comment by kenneho** [comment]
> Just asking, should the recipe also replace the `<div>` with Chakra's `<Box>`, and the `<button>` with Chakra's `<Button>`? And we can probably replace `<form>` with Chakra's `<Form>` too, not sure if it is okay to do that.

In my opinion going for Chakra's <Box> and <Button> sounds like a good idea. 

Regarding using Chakra's Form: Are you referring to usage in the file Form.tsx? If so, at least in my (default) setup, I'm using FinalForm, and would probably prefer to continue using this.

**Comment by muyiwaolu** [comment]
@laubonghaudoi Right now, I've updated the recipe to replace the `div` with Chakra's `Box` (as well as sorting out imports). What benefit would replacing the form bring?

**Comment by laubonghaudoi** [comment]
> @laubonghaudoi Right now, I've updated the recipe to replace the `div` with Chakra's `Box` (as well as sorting out imports). What benefit would replacing the form bring?

Replacing it with Chakra's `<FormControl>` should provide more control to the form's aesthetics, like `colorScheme`. But other than that I don't know if there is any other benefit.

**Comment by flybayer** [comment]
> @laubonghaudoi Right now, I've updated the recipe to replace the `div` with Chakra's `Box` (as well as sorting out imports). What benefit would replacing the form bring?

Personally I'm not sure it's worth it for us to maintain switching out divs since it doesn't have a visual impact, but if you already have it done, probably fine to leave for now :)

**Comment by laubonghaudoi** [comment]
@muyiwaolu This issue is closed but I am thinking can we also replace the error message div with Chakra's `<FormErrorMessage>`. At the moment this recipe creates a `LabelTextField` like this:

```tsx
<FormControl {...outerProps}>
  <FormLabel>
    {label}
    <Input disabled={isSubmitting} {...register(name)} {...props} />
  </FormLabel>
  {error && (
    <div role="alert" style={{ color: "red" }}>
      {error}
    </div>
  )}
</FormControl>
```
And I am looking to change into this:
```tsx
<FormControl isInvalid={error} {...outerProps}>
  <FormLabel>
      {label}
    <Input disabled={isSubmitting} {...register(name)} {...props} />
  </FormLabel>

  {error && <FormErrorMessage>{error}</FormErrorMessage>}
</FormControl>
```

I think it is better to integrate with Chakra's `<FormErrorMessage>` instead of `<div>`, what do you think?

**Comment by flybayer** [comment]
@laubonghaudoi I'm fine with that if that's something you think a lot of Chakra folks would like!
