### ISSUE TITLE
All pages return 404 with `blitz dev` after upgrading to 0.38.3 on Windows

### ISSUE THREAD

**Issue by remjx** [blitz-js/blitz#2552]
### What is the problem?

0.38.2 is working fine, but when I try to load any page locally with 0.38.3, I get a 404 error.

In CI, my Cypress tests are able to load the pages without issue.

### Paste all your error logs here:

```
✔ Compiled
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5

> Found a change in blitz.config.js. Restart the server to see the changes in effect.
event - compiled successfully
event - build page: /_error
```

I don't know if this is related, but the "Restart the server to see the changes in effect" keeps showing up even after re-running `blitz dev`

### Paste all relevant code snippets here:

N/A

### What are detailed steps to reproduce this?

1. Upgrade from 0.38.2 to 0.38.3
2. Run `blitz dev`
3. Try to load a page

### Run `blitz -v` and paste the output here:

```
$ blitz -v 
Windows 10 | win32-x64 | Node: v14.16.1

blitz: 0.38.2 (global)
blitz: 0.38.3 (local)

  Package manager: npm
  System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 AMD Ryzen 7 4800HS with Radeon Graphics
    Memory: 6.26 GB / 15.42 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.24.1 => 2.24.1
    blitz: 0.38.3 => 0.38.3
    prisma: 2.24.1 => 2.24.1
    react: ^18.0.0-alpha-c96b78e0e => 18.0.0-alpha-ed6c091fe-20210701
    react-dom: ^18.0.0-alpha-c96b78e0e => 18.0.0-alpha-ed6c091fe-20210701
    typescript: ^4.3.2 => 4.3.5
```

**Comment by flybayer** [comment]
I'm unable to reproduce in my production app and we have integration tests for this.

Can you try deleting `.blitz` and `.next` and see if the issue persists? It should be cleared automatically, but worth a shot.

**Comment by Mohron** [comment]
Seeing the same issue to include the "Found a change in blitz.config.js. Restart the server to see the changes in effect." when running `blitz dev`

```
Windows 10 | win32-x64 | Node: v14.17.0

blitz: 0.38.3 (local)

  Package manager: yarn
  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 11.86 GB / 31.94 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: ^2.25.0 => 2.26.0
    blitz: ^0.38.3 => 0.38.3
    prisma: ^2.25.0 => 2.26.0
    react: 18.0.0-alpha-ed6c091fe-20210701 => 18.0.0-alpha-ed6c091fe-20210701
    react-dom: 18.0.0-alpha-ed6c091fe-20210701 => 18.0.0-alpha-ed6c091fe-20210701
    typescript: ^4.3.5 => 4.3.5
```

**Comment by flybayer** [comment]
Oh, both of you are on windows. I will fix

**Comment by remjx** [comment]
@flybayer i tried deleting `.blitz` in my root and re-running `blitz dev` but am still getting 404 errors on every page.

**Comment by markhughes** [comment]
@remjx they have solved it in https://github.com/blitz-js/blitz/pull/2554 so when that's in and released you'll be good to go :)
