### ISSUE TITLE
Be able to handle what the response will be from an query

### ISSUE THREAD

**Issue by davidsoderberg** [blitz-js/blitz#2560]
### What do you want and why?
Let's say I like to serve images stored on a S3 storage or even directly from server disk.
In this case it would also be good to be able to have an GET method instead of POST.

### Possible implementation(s)
We could add one more param in the query function like we today have context.
Like an api definition where the developer can decide stuff like:
- http method
- content type that are served from it
- other stuff that would be cool to be able to change as a developer

Of course this should be optional but would make Blitz more customizable...

### Additional context
I already love Blitz and I have only worked with it for a week 😄

**Comment by remjx** [comment]
Static files/images can be served directly https://blitzjs.com/docs/static-files why do you want an API route for it?
There is also built-in image optimization https://blitzjs.com/docs/image-component

Does this work for your use case? If not, can you please elaborate on what you are trying to accomplish?

**Comment by davidsoderberg** [comment]
No it do not lets say that I have I am building a topic based comments like Github issues for example and like to host the profil images in an s3 bucket and do not like to expose the s3 links. So I use Blitz api like an image proxy and can also add some checks before responding with the image.

**Comment by davidsoderberg** [comment]
Also this maybe could be used for receiving file upload, so I like to be able to  change how the query works to be able to do these custom things.

**Comment by MrLeebo** [comment]
If you need to set the method or content type of a request, you can implement it as an API Route https://blitzjs.com/docs/api-routes. There's no reason to add that kind of customization to queries/mutations, because they act as an abstraction from the HTTP protocol... if you don't want to work with an abstraction, you can just leverage the HTTP directly using API Routes.
