### ISSUE TITLE
Soft delete

### ISSUE THREAD

**Issue by itsazzad** [blitz-js/blitz#2563]
### What do you want and why?

- Soft delete middleware: https://www.prisma.io/docs/concepts/components/prisma-client/middleware/soft-delete-middleware
- Soft Deleting: https://laravel.com/docs/master/eloquent#soft-deleting

### Possible implementation(s)

Middleware?

**Comment by MrLeebo** [comment]
@itsazzad What exactly are you asking for? You could add the proposed middleware in the prisma docs to your `db/index.ts` file and be all set, no?

**Comment by MrLeebo** [comment]
Closing this for lack of information
