### ISSUE TITLE
Add session info (or maybe context) to the redirectAuthenticatedTo

### ISSUE THREAD

**Issue by tafelito** [blitz-js/blitz#2575]
### What do you want and why?

Based on the conversation we had over discord, it would be nice to have a a way to pull the session data when using `redirectAuthenticatedTo` to make it easier to redirect to different places depending on the user's session 

### Possible implementation(s)

After implementing this, redirectAuthenticatedTo would look like something like this `Page.redirectAuthenticatedTo = (session) => session.onboarded ? '/dashboard' : '/onboarding'`

### Additional context

This can prevent duplicating getServerSideProps logic just for this use case

**Comment by flybayer** [comment]
Thank you! This will be good to add. We should just tweak the API slightly so that it passes in an object. Will allow us to add other things in the future.

```ts
Page.redirectAuthenticatedTo = ({session}) => session.onboarded ? '/dashboard' : '/onboarding'
```

**Comment by bravo-kernel** [comment]
This would be awesome as I am trying to redirect to `/{session.username}`
