### ISSUE TITLE
⚠️ security problem with passwords on default scaffolded app

### ISSUE THREAD

**Issue by uvero** [blitz-js/blitz#2577]
Hi, entirely new here, going in raw. Looking at the code, I found code that made me suspect that passwords are saved in the database by hashing alone. I registered two users with the same password, have the same hashed password in the database. This is a common security breach. Password security requires at least hash & salt.

I would implement it myself for you and PR but this isn't really my league, nor my expertise, really, you may want to find someone who knows more about security than me.

Best regards,
Yuval D.

**Comment by flybayer** [comment]
Thanks @uvero. We leverage https://github.com/emilbayes/secure-password for the hashing which automatically salts them.

So I'm a bit surprised by your report. Can you include code snippets to reproduce?

Here's a quick test I did. On first glance they **appear** the same but they are actually different.
```
⚡️ > await b.SecurePassword.hash('hello')
'JGFyZ29uMmlkJHY9MTkkbT02NTUzNix0PTIscD0xJFpWUHlYMkppdkVJVk5xdENsL1M1ZlEkTXhTbWRXMzNrem9rRHQvNmdvdGFWN1Iza0JQR21PVEwxYnBxaVRXdGFZRQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
⚡️ > await b.SecurePassword.hash('hello')
'JGFyZ29uMmlkJHY9MTkkbT02NTUzNix0PTIscD0xJEhYOFBLNkF4Umw4WDZtdzhhZTl6aUEkMWxQSVY0NXVIVC85QUZDNVlFSVJFRFNPa3BIbllobUxFbDFoZ3B1MUlWWQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
```

**Comment by MrLeebo** [comment]
Closing this since passwords are already salted
