### ISSUE TITLE
useParam hook returns undefined in tests

### ISSUE THREAD

**Issue by Gabrielgvl** [blitz-js/blitz#2582]
### What is the problem?

I was trying to implement some tests in a page which uses the useParam hook. I tried to mock the param in the render, however, it does not seems to work as the param is undefined.

### Paste all your error logs here:

```
PASTE_HERE (leave the ``` marks)
```

### Paste all relevant code snippets here:

Here is how I tried to mock it:
```
const renderPage = () => render(<ShowWalletPage />, { router: { params: { walletId: mockWalletId } } });
```

### What are detailed steps to reproduce this?

1. Add useParam to a page.
2. Mock it using params inside router.

### Run `blitz -v` and paste the output here:

```
Linux 4.19 | linux-x64 | Node: v15.14.0

blitz: 0.38.5 (global)
blitz: 0.38.5 (local)

  Package manager: yarn 
  System:
    OS: Linux 4.19 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 4.85 GB / 11.70 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 15.14.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.7.6 - /usr/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.26.0 => 2.26.0 
    blitz: 0.38.5 => 0.38.5 
    prisma: 2.26.0 => 2.26.0 
    react: alpha => 18.0.0-alpha-310187264-20210716 
    react-dom: alpha => 18.0.0-alpha-310187264-20210716 
    typescript: ~4.3 => 4.3.5 
```

**Comment by flybayer** [comment]
Thanks! I think to fix this we need to adjust some code inside nextjs core. Not sure where exactly. But in there, on first render we can check if running in a jest test via env variable. If yes, then set params on first render. Otherwise on second render as it currently does.

**Comment by midgethoen** [comment]
Im running into `useParam(s)`, `useRouter().params` all returning `undefined` on first render.
It seems to re-render after that and return the correct param, so its only noticable in the console.

is this the same issue?
relevant code:

`.app/pages/[handle]/settings/teams/index.tsx`
```tsx
//...
const TenantTeamsSettingsPage: BlitzPage<Props> = (props) => {
  const { handle } = useRouter().params
  if (typeof handle !== "string") {
    throw new Error("Failed param assertion")
  }
//...
```

**Comment by flybayer** [comment]
@midgethoen that is a separate issue and is caused by a fundamental law of react that first render must match static HTML. You can use `Page.suppressFirstRenderFlicker=true` to hide the first render. See https://blitzjs.com/docs/pages#first-render-ux
