### ISSUE TITLE
Having multiple domains with the same locale causes router redirections to incorrect domain

### ISSUE THREAD

**Issue by divpreet** [blitz-js/blitz#2584]
### What is the problem?

We have multiple domains with the same locale defined in the config. Something like this in the blitz.config file:-
```
i18n: {
    locales: ["au", "us", "uk", "ca"],
    defaultLocale: "au",
    domains: [
      {
        domain: "app.test.domain.com.au",
        defaultLocale: "au",
      },
      {
        domain: "app.domain.com.au",
        defaultLocale: "au",
      },
      {
        domain: "app.ca.domain.com",
        defaultLocale: "ca",
      },
      {
        domain: "app.test.ca.domain.com",
        defaultLocale: "ca",
      },
    ],
  }
```

Running the app on `app.test.ca.domain.com` and triggering a `router.push()` where `router = useRouter()` redirects to the first matched domain with the same locale ie `app.ca.domain.com` in this case.

Seems like `detect-domain-locale` has the domain matcher method that does not expect duplicate locales?

Is this expected?

### Paste all your error logs here:

```
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1. Define multiple domains with same locale for the internationalization settings in blitz.config
2. Run the application with the second domain with a common locale
3. Trigger a route change by using `route.push()` where `route = useRouter()`
4. Notice the redirection to the first matching domain with the locale.

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v14.17.0

blitz: 0.38.4 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 533.26 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: Not Found
    blitz: 0.38.4 => 0.38.4 
    prisma: Not Found
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    typescript: 4.3.5 => 4.3.5 
```

**Comment by flybayer** [comment]
Hi @divpreet. This comes from Next.js — looks like a bug. Is it the same as this? https://github.com/vercel/next.js/issues/22795

**Comment by divpreet** [comment]
Thanks @flybayer, looks like that is the same issue.

**Comment by flybayer** [comment]
Cool — ok to close this one then?

**Comment by divpreet** [comment]
Sure.
