### ISSUE TITLE
db migrate throws error "Can't reach database server at `localhost`:`5432`"

### ISSUE THREAD

**Issue by jlkiri** [blitz-js/blitz#260]
### What is the problem?

`blitz db migrate` does not work

Throws the following error:

```
$ C:\dev\blitzapp\node_modules\.bin\blitz db migrate
You are using alpha software - if you have any problems, please open an issue here:
  https://github.com/blitz-js/blitz/issues/new/choose

Error: P1001: Can't reach database server at `localhost`:`5432`
```

### Steps to Reproduce:

1. Create a fresh project with `blitz new`
2. Add

```
model Project {
  id      Int      @default(autoincrement()) @id
  name    String
}
```
to `schema.prisma`

3. Run `blitz db migrate`

### Versions:

```
Windows 10 | win32-x64 | Node: v12.15.0

blitz: 0.6.4 (global)
blitz: 0.6.4 (local)

Done in 3.16s.
```

**Comment by ryardley** [comment]
It is possible your DATABASE_URL env var is not populated or is pointing to the wrong location. What have you set DATABASE_URL env var to?

**Comment by flybayer** [comment]
Yeah this means you either don't have Postgres installed or it's using a different configuration than default.

I'm assuming you don't have it installed. I'm not sure of a great walkthrough on how to do this for windows, but here's a couple options:

- https://www.postgresqltutorial.com/install-postgresql/
- https://www.youtube.com/watch?v=SPab5WhO18g

Let us know how it goes!

**Comment by jlkiri** [comment]
Oh I see. I just didn't expect `postgresql` to be *required* for the "enter some commands and see how everything updates" introduction you see after running `blitz start`. It worked after I set up my database. I guess it wasn't obvious enough 😅

**Comment by flybayer** [comment]
Ok cool — yeah we need to add this to the new app template page. Here's the issue for this: https://github.com/blitz-js/blitz/issues/282
