### ISSUE TITLE
ENOENT error when trying to install blitz recipe

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#2608]
You get an ENOENT error if you `rm -rf .blitz && blitz install [name]` 

### Discussed in https://github.com/blitz-js/blitz/discussions/2596

<div type='discussions-op-text'>

<sup>Originally posted by **spidertwin2** July 25, 2021</sup>
`blitz install chakra-ui` gives the output -

```
◢ Cloning GitHub repository for chakra-ui recipe
     Error: ENOENT: no such file or directory, 
     mkdir '/Users/spidertwin/Desktop/myapp/.blitz/recipe-install'
     Code: ENOENT
◤ Cloning GitHub repository for chakra-ui recipe%  
```

running my project on macOS Big Sur 11.4

🐰 </div>

### Workaround

1. Run `blitz dev`
2. Stop `blitz dev`
3. Run `blitz install RECIPE`

**Comment by flybayer** [comment]
To fix, we need to change this line: https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/install.ts#L142

I think this should be all that's needed. Need to test and see.

```diff
-require("fs-extra").mkdirSync(recipeDir)
+require("fs-extra").mkdirSync(recipeDir, { recursive: true })
```

**Comment by meehawk** [comment]
Hi @flybayer can I take this up?

**Comment by abuuzayr** [comment]
absolutely @meehawk !
