### ISSUE TITLE
`setQueryData` seems to break resources typing

### ISSUE THREAD

**Issue by ugogo** [blitz-js/blitz#2609]
### What is the problem?

When using `useQuery`, the resources' type seems to get lost when destructuring `setQueryData`

### Paste all your error logs here:

-

### Paste all relevant code snippets here:

-

### What are detailed steps to reproduce this?

Inspect typing with and without `setQueryData`

### Run `blitz -v` and paste the output here:

```
$ npx blitz -v
macOS Big Sur | darwin-x64 | Node: v16.3.0

blitz: 0.38.4 (local)

  Package manager: yarn
  System:
    OS: macOS 11.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 23.64 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.20.1 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.26.0 => 2.26.0
    blitz: 0.38.4 => 0.38.4
    prisma: 2.26.0 => 2.26.0
    react: alpha => 18.0.0-alpha-ed6c091fe-20210701
    react-dom: alpha => 18.0.0-alpha-ed6c091fe-20210701
    typescript: ~4.3 => 4.3.5
````

### Please include below any other applicable logs and screenshots that show your problem:

Here, `plannings` has the correct type
```
const [{ plannings }] = useQuery(getPlannings, {...})
```
![CleanShot 2021-07-28 at 08 01 48@2x](https://user-images.githubusercontent.com/5040476/127366268-8ba54c1c-abda-4f96-ab22-a7df52e9d60c.jpg)

But when using `setQueryData`, `plannings` has lost its typing

```
const [{ plannings }, { setQueryData }] = useQuery(getPlannings, {...})
```
![CleanShot 2021-07-28 at 08 02 12@2x](https://user-images.githubusercontent.com/5040476/127366263-45717900-f6f8-42fa-ad15-16660ec6d3e3.jpg)

**Comment by flybayer** [comment]
Thanks! This is ready for someone to work on. Code is here: https://github.com/blitz-js/blitz/blob/canary/packages/core/src/use-query-hooks.ts#L35

**Comment by beerose** [comment]
Hey @ugogo! 

I tried reproducing it with Blitz examples and my side project, and  I did see an `any` type in a tooltip a few times due to a VS Code lag. However, it was in various configurations — with and without destructuring `setQueryData`, or with destructuring some other field.
Did you notice this issue outside of your editor  — e.g. with tsc not reporting an error that would happen if the value wasn't an `any`?

**Comment by ugogo** [comment]
hey @beerose 
Just tried `npx tsc` with `"noImplicitAny": true` in my `tsconfig.json` and it's throwing an error when trying to map the resource
Like in this example
![CleanShot 2021-07-30 at 08 37 58@2x](https://user-images.githubusercontent.com/5040476/127611474-388b012f-e312-4c5e-84e3-b495021646cc.jpg)

**Comment by arvinf07** [comment]
I want to work on this issue!
