### ISSUE TITLE
Blitz compile errors should be shown in the browser

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#261]
### What do you want and why?

Currently blitz compile errors only show in the console. 

1. `blitz start`
2. Create a duplicate page route by having the same page route in two different `pages` folders
3. An error will be shown in the terminal, but not in the browser

We should show errors in the browser, just like next.js compile errors do.

**Comment by kwakuben** [comment]
I could work on this if some knowledge base/documentation is provided.

**Comment by flybayer** [comment]
Hey @kwakuben I'm not actually sure how to do this 😅 This is probably best for someone who has a good grasp of blitz already and can spend time digging into it.

**Comment by kwakuben** [comment]
Right. Feel free to pass me some easier tasks once they arise. Still looking through for something to do

**Comment by flybayer** [comment]
Putting in icebox because this may be fixed by: https://github.com/blitz-js/blitz/discussions/1990. Or at least the implementation will be changed by that

**Comment by flybayer** [comment]
Will be resolved after nextjs fork integration
