### ISSUE TITLE
Change blitz version to be pinned in new app template

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#262]
### What do you want and why?

Currently `blitz new myapp` results in the blitz version being set to `latest`. We need to change that so the latest explicit version is set, just like we are doing with the other dependencies.

- If cliVersion is canary, then blitz version should be set to most recent version of `canary` release tag
- Else, blitz version should be set to most recent version of `latest` release tag

Code: https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/generators/app.ts#L54..L62

**Comment by Skn0tt** [comment]
I'm down to help with this issue.
