### ISSUE TITLE
RedirectError breaks Cypress tests via uncaught exception

### ISSUE THREAD

**Issue by akbo** [blitz-js/blitz#2633]
### What is the problem?

The Cypress tests of my app's signup and login flows fail, although the app works as expected. This can be reproduced with a new blitz app with `blitz@0.38.6` and `blitz@v0.39.0-canary.0`.

From the error message, it looks like blitz's RedirectError isn't caught, leading to Cypress failing the test due to an uncaught exception. As far as I understand, RedirectError is triggered by `BlitzPage.redirectAuthenticatedTo` when the signup or login is successful.

Cypress supports turning off failing tests due to uncaught exceptions, but that feels like a hack.

This issue was already discussed and fixed in #2518. In contrast to the problem reported in that issue, RedirectError for some reason doesn't show up in the browser's console, but only fails the Cypress test.

### Paste all your error logs here:

```
cypress_runner.js:175886 RedirectError: The following error originated from your application code, not from Cypress.

  > /

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
    at run (http://localhost:3000/__cypress/runner/cypress_runner.js:155817:21)
    at $Cy.cy.<computed> [as visit] (http://localhost:3000/__cypress/runner/cypress_runner.js:156290:11)
    at __stackReplacementMarker (http://localhost:3000/__cypress/runner/cypress_runner.js:155297:13)
    at Context.runnable.fn (http://localhost:3000/__cypress/runner/cypress_runner.js:156514:21)
    at callFn (http://localhost:3000/__cypress/runner/cypress_runner.js:112246:21)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:112233:7)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:162519:28
From previous event:
    at Object.onRunnableRun (http://localhost:3000/__cypress/runner/cypress_runner.js:162507:17)
    at $Cypress.action (http://localhost:3000/__cypress/runner/cypress_runner.js:152598:28)
    at Test.Runnable.run (http://localhost:3000/__cypress/runner/cypress_runner.js:160649:13)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:3000/__cypress/runner/cypress_runner.js:112905:10)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:113031:12
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:112814:14)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:112824:7
    at next (http://localhost:3000/__cypress/runner/cypress_runner.js:112726:14)
    at http://localhost:3000/__cypress/runner/cypress_runner.js:112792:5
    at timeslice (http://localhost:3000/__cypress/runner/cypress_runner.js:106718:27)
```

### Paste all relevant code snippets here:

None, all required code is contained in a new blitz app.

### What are detailed steps to reproduce this?

1. `blitz new reproduce`
2. `cd reproduce`
3. `blitz dev`
4. Run the following Cypress test

```
const random = (length = 8) => {
  return Math.random().toString(16).substr(2, length)
}

describe("Blitz Sign Up", () => {
  it("Signs up", () => {
    cy.visit("http://localhost:3000")

    cy.contains("Sign Up").click()

    // Use a random email address so we can run this test many times from any Cypress instance without having to reset the database.
    cy.get("input[name=email]").type(random() + "@example.com")
    cy.get("input[name=password]").type("0123456789")
    cy.get("button").click()

    // Do a random thing so Cypress test fails (it apparently doesn't fail if only the very last thing you do throws an uncaught exception).
    cy.contains("Documentation").click()
  })
})
```

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v14.17.4

blitz: 0.38.6 (global)
blitz: 0.38.6 (local)

  Package manager: yarn
  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.18 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.4 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/opt/node@14/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.28.0 => 2.28.0
    blitz: 0.38.6 => 0.38.6
    prisma: 2.28.0 => 2.28.0
    react: alpha => 18.0.0-alpha-e3b76a85c-20210802
    react-dom: alpha => 18.0.0-alpha-e3b76a85c-20210802
    typescript: ~4.3 => 4.3.5
```

I also tested this with `blitz@v0.39.0-canary.0`

### Please include below any other applicable logs and screenshots that show your problem:

<img width="1787" alt="Screenshot 2021-08-03 at 10 20 25" src="https://user-images.githubusercontent.com/1926271/128304297-30c9dde1-3137-4012-a461-63c3ca435d25.png">

**Comment by flybayer** [comment]
Thanks @akbo!

**Comment by akbo** [comment]
I am starting to look into this and here is what I found up to this point:

- The problem also fails a cypress test in the 'auth' example app (can be found under `examples/auth` in this repo)
- A workaround for this problem is to explicitly tell Cypress to ignore uncaught exceptions due to `RedirectError` by adding this to `cypress/support/index.ts` in your project:

```
Cypress.on("uncaught:exception", (err, runnable, promise) => {
  if (err.name === "RedirectError") {
    return false
  }
})
```

**Comment by akbo** [comment]
Ok, after some more research, I gather this: the problem is caused by the way React's error boundary behaves in development. For more info, check out this comment and the corresponding issue on the Cypress repo: https://github.com/cypress-io/cypress/issues/7196#issuecomment-680126693

I am out of my depth here, but from what I have read in https://github.com/cypress-io/cypress/issues/7196#issuecomment-624803349 (same issue as the above link), the two options we have appear to be 

1) the workaround I posted in the previous comment, but this needs to happen in the application code of each app, not the framework code
2) define a `window.onerror` in blitz that handles RedirectError and then calls Cypess's window.onerror, if Cypress is detected to be running (no idea if this is feasible)

What do you think?

**Comment by akbo** [comment]
I implemented the second option from the above comment in my fork: https://github.com/akbo/blitz/commit/ea816ca3c87bebdc776218c8651b5803334835bb

Will create a pull request next.
