### ISSUE TITLE
`redirectAuthenticatedTo` does not call queries when redirecting from a dynamic route

### ISSUE THREAD

**Issue by CarterMcAlister** [blitz-js/blitz#2636]
### What is the problem?

When redirecting from a dynamic route, the queries are not called on the page you are redirected to.
`redirectAuthenticatedTo` works fine if the page is not a dynamic route.

I've tried redirecting to a non-dynamic route first as a workaround, and this did not work.

I believe this [this issue](https://github.com/blitz-js/blitz/issues/2527) may be related

### Paste all relevant code snippets here:

Reproduction repo: https://github.com/CarterMcAlister/blitzjs-redirect-bug-example

### What are detailed steps to reproduce this?

1. Pull down the reproduction repo
2. Sign up and log in
3. go to `/test/[example]`
4. You will be redirected to the home page
5. `getCurrentUser` call hangs, and the `<UserInfo>` component will stay in a suspense state

**Comment by CarterMcAlister** [comment]
Note: the `useRedirectAuthenticated` hook **does** work properly on dynamic routes

**Comment by flybayer** [comment]
Ok, thanks @CarterMcAlister!
