### ISSUE TITLE
Changing getStaticProps/getServerSideProps does not trigger fast refresh

### ISSUE THREAD

**Issue by nickluger** [blitz-js/blitz#2661]
### What is the problem?

Changing `getStaticProps` or `getServerSideProps` should trigger a fast refresh or at least a reload of the page automatically, and the function should re-run. Currently, you have to manually reload the browser page, to make `getStaticProps` re-run.

Could be an upstream issue, not sure about that: https://github.com/vercel/next.js/issues/19230

### Paste all your error logs here:

No logs

### Paste all relevant code snippets here:

```js
export async function getStaticProps(context) {
  // Never shown, i.e. does not re-run this function, even if you make changes to it
  console.log("Running getStaticProps...")
  return {
    props: {
      foo: 2
    },
  }
}
```

### What are detailed steps to reproduce this?

1.  `blitz new my-app`
2. `cd my-app`
3. Add a simple `getStaticProps` to the `index.tsx` page
4. `blitz dev`
5. Change something → See `[Fast Refresh] rebuilding`, but nothing really happens, `getStaticProps` does not run...

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v14.17.5

blitz: 0.39.0 (global)
blitz: 0.39.0 (local)

  Package manager: yarn
  System:
    OS: macOS 11.5.2
    CPU: (8) x64 Apple M1
    Memory: 17.49 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - /var/folders/0t/qf92ltfx37jblv7t_3_7v8mh0000gn/T/fnm_multishells/19665_1629374154385/bin/node
    Yarn: 1.22.11 - /var/folders/0t/qf92ltfx37jblv7t_3_7v8mh0000gn/T/fnm_multishells/19665_1629374154385/bin/yarn
    npm: 6.14.14 - /var/folders/0t/qf92ltfx37jblv7t_3_7v8mh0000gn/T/fnm_multishells/19665_1629374154385/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.29.1 => 2.29.1
    blitz: 0.39.0 => 0.39.0
    prisma: 2.29.1 => 2.29.1
    react: alpha => 18.0.0-alpha-64f83a6fd-20210819
    react-dom: alpha => 18.0.0-alpha-64f83a6fd-20210819
    typescript: ~4.3 => 4.3.5

```

**Comment by Talor-A** [comment]
same issue for making changes to the page layout.

**Comment by flybayer** [comment]
Thanks @nickluger, most likely this is an upstream issue. 

@Talor-A sounds like a separate issue, so open a new issue for that if you want.
