### ISSUE TITLE
Blitz Dev server crashes for unknown reasons upon trying to load webpage

### ISSUE THREAD

**Issue by AbhinavMir** [blitz-js/blitz#2667]
### What is the problem?

I had a BlitzJS project running with Prisma, Postgres and Tailwind that seems to crash upon certain changes I can't quite put a finger on. This happened in an earlier project with some changes to the schema.prisma, but here nothing much had changed for this error to occur. 

### Paste all your error logs here:

No error, the server just crashes. I'm confident there are no errors elsewhere (VS Code would've pointed me to - if any).

### Paste all relevant code snippets here:

Not sure which Code Snippet to provide.

### What are detailed steps to reproduce this?

1. Create an App
2. Migrate and Push DB
3. Crash

Sorry for the poorly raised issue, but I genuinely have no clue what's causing this crash.

### Run `blitz -v` and paste the output here:

```
Linux 5.11 | linux-x64 | Node: v14.17.5

blitz: 0.38.6 (global)
blitz: 0.39.0 (local)

  Package manager: npm 
  System:
    OS: Linux 5.11 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 491.27 MB / 7.65 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: Not Found
    Yarn: Not Found
    npm: Not Found
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.29.1 => 2.29.1 
    blitz: 0.39.0 => 0.39.0 
    prisma: 2.29.1 => 2.29.1 
    react: alpha => 18.0.0-alpha-b6ff9ad16-20210820 
    react-dom: alpha => 18.0.0-alpha-b6ff9ad16-20210820 
    typescript: ~4.3 => 4.3.5 
```

**Comment by flybayer** [comment]
@AbhinavMir I understand you said there was no error logged, but could you still paste the logs from your terminal when this happens? With something like this, we need as much info as possible.

1. What changes did you make before this started happening?
2. When it crashes, how do you recover?
3. Does it still crash with an earlier version of your codebase?

Lastly, you can try testing the latest `blitz@canary` release and see it's improved.

**Comment by flybayer** [comment]
@AbhinavMir any update on this?

**Comment by AbhinavMir** [comment]
@flybayer absolutely missed this. We can temporarily close this for now, I remade the project without error. If I get it again, we can open it maybe. Unable to reproduce.
