### ISSUE TITLE
Add ability to define project-wide page default options

### ISSUE THREAD

**Issue by anteprimorac** [blitz-js/blitz#2692]
### What do you want and why?

My use case for this is an internal app that will require authentication to access all pages except the login page.

### Possible implementation(s)

```js
// blitz.config.js
module.exports = {
  // ...
  pageDefaults: {
    authenticate: true,
  }.
};
```

**Comment by MrLeebo** [comment]
Good suggestion!

Ideally, the config should apply to all of the page options and not just `authenticate`. As far as I know, the options are `authenticate`, `redirectAuthenticatedTo`, `suppressFirstRenderFlicker`, and `getLayout`. It would also be good to add a page to the Blitz docs documenting all of these options together. Right now they are spread out across different sections.

https://blitzjs.com/docs/pages

**Comment by flybayer** [comment]
Sweet! My first thought is to nest the config like this to provide for more future flexibility:

```ts
module.exports = {
  // ...
  pages: {
    defaults: {
      authenticate: true,
    }
  }.
};
```
