### ISSUE TITLE
Add package manager prompt to `blitz new`

### ISSUE THREAD

**Issue by itsMapleLeaf** [blitz-js/blitz#2694]
### What do you want and why?

A prompt to skip installing modules, e.g. `Install modules with yarn? (Y/n)`

### Possible implementation(s)

Would definitely prefer it as a prompt, since a flag has to be remembered and/or looked up preemptively. But if a prompt doesn't work, a CLI flag is... fine ¯\\\_(ツ)\_/¯

One _could_ also add pnpm to the list, but we'll just go through this song and dance again if another package manager gets popular. Would rather default to the common case, but let people install themselves in the uncommon case.

### Additional context

Waiting for an unnecessary npm/yarn install lengthens "time to code" by multiple minutes, enough time for me to get distracted by something else 😂

**Comment by flybayer** [comment]
Yes yes, thank you!

My preference is to add a multiple-select option during blitz new (like the current form prompt) that let's you choose from the following:

```
- npm
- yarn
- pnpm
- skip
```

We can always add more over time. And I think we should only show pnpm option if it's installed. Same for yarn.
