### ISSUE TITLE
prisma db update fails during `blitz generate all`

### ISSUE THREAD

**Issue by Vandivier** [blitz-js/blitz#2696]
### What is the problem?

See image below. After running `blitz generate all` I am asked if I would like to update DB + Prisma. If I say `yes` then I get an error.

![image](https://user-images.githubusercontent.com/5559355/132150130-6cdc107f-68c2-4a58-b8eb-25c09a8b07e9.png)

### Paste all your error logs here:

```
PASTE_HERE (leave the ``` marks)
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1. launch Railway blitz.js starter
2. globally install blitz cli + `yarn add @blitzjs/server`
3. `blitz generate all futurecast mainText:string castToken:uuid` in my case

### Run `blitz -v` and paste the output here:

```
$ blitz -v
Windows 10 | win32-x64 | Node: v16.2.0

blitz: 0.39.0 (global)
blitz: 0.38.5 (local)

  Package manager: yarn
  System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
    Memory: 8.12 GB / 19.86 GB
  Binaries:
    Node: 16.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.20.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.17 => 2.17.0
    blitz: 0.38.5 => 0.38.5
    prisma: ~2.17 => 2.17.0
    react: alpha => 18.0.0-alpha-c76e4dbbc-20210722
    react-dom: alpha => 18.0.0-alpha-c76e4dbbc-20210722
    typescript: 4.1.5 => 4.1.5
```

### Please include below any other applicable logs and screenshots that show your problem:
stream here: https://www.youtube.com/watch?v=wwp3WLSjr4A

**Comment by Vandivier** [comment]
my starter when deployed also tells me I should say yes to prisma migrate which is having an issue:

![image](https://user-images.githubusercontent.com/5559355/132151413-beae4f7c-b953-4d16-9637-85a197f42a35.png)

**Comment by flybayer** [comment]
@Vandivier ah, it looks like you have too old of a prisma version for that version of Blitz. Can you try upgrading to latest prisma version?

**Comment by Vandivier** [comment]
@flybayer yep, everything looks good! Seems like both Vercel and Railway have out-of-date starters that don't cooperate w v0.39+ blitzJs CLI - building new project from cli and importing is the way to go!
