### ISSUE TITLE
blitz generate uuid

### ISSUE THREAD

**Issue by Vandivier** [blitz-js/blitz#2711]
### What do you want and why?

I want my Prisma schema correctly generated with uuid data type when I run:
`blitz generate all futurecast mainText:string castToken:uuid`

This is for developer convenience when making a new model with a uuid.

should output like this:
```
model Futurecast {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  mainText  String
  castToken String   @default(uuid())
}
```

**Comment by Roesh** [comment]
If no one else would like to take it on after finishing the generators PR, hoping to finish that by end of week

**Comment by Vandivier** [comment]
@Roesh I should be able to jump on this starting Tuesday but feel free if u got it before then :)

**Comment by Roesh** [comment]
Hey @Vandivier! You can go ahead and have it assigned, I'll be working on the documentation and more testing for that PR I mentioned

**Comment by Vandivier** [comment]
kind of depends on https://github.com/blitz-js/blitz/issues/2806

I cloned the repo and ran tests to ensure passage before making any changes, and tests were failing.

If above is merged, then tests pass, and I consider that a starting point for the present issue
