### ISSUE TITLE
Facing issues after deployed to vercel

### ISSUE THREAD

**Issue by FSE-Hyd-Raju** [blitz-js/blitz#2716]
### What is the problem?

Hi Team,

I developed a blitz app and deployed it to vercel. I am trying to access the application. When I sign up got the error saying TypeError: Cannot read property '$create' of undefined. But the user got created in db. Also I tried logging in with the created user, Getting the same error. I am not getting what I am missing. Please help.

![image](https://user-images.githubusercontent.com/9348371/133233827-843d7aee-8838-4df1-bd5b-d9be261caaaa.png)

**Comment by andreasasprou** [comment]
Me too

**Comment by andreasasprou** [comment]
Any updates on this @flybayer?

**Comment by flybayer** [comment]
Sorry, haven't had a chance to look at this. Should be able to today or tomorrow.
