### ISSUE TITLE
CSRFTokenMissmatch for anonymous sessions

### ISSUE THREAD

**Issue by lksnmnn** [blitz-js/blitz#2718]
### What is the problem?

There might be 2 Problems:

1. For anonymous sessions, the `blitz_sAntiCSRFToken` is being removed, while the `blitz_sAnonymousSessionToken` is not. 
2. If the above mentioned state is reached, users can only recover by deleting the session token.

We've got several reports from users, where the scenario (1) happened. If this is the case, the user can't log in (or use any other query/mutation) due to `CSRFTokenMissmatch` errors. These errors are correct, since this looks like a CSRF attempt, but the user can only recover by manually removing cookies.

I have not yet figured out why and how the cookie is being removed and why the anon session token is not. The only difference between these is the `httpOnly` flag. It is completly possible, that the browser removes `httpOnly=false` cookies after some time, leaving us with a broken app.

I've described this issue also in Discord: https://discord.com/channels/802917734999523368/887430673730789407/887430678751359047

### Paste all your error logs here:

```
CSRFTokenMissmatch
```

### Paste all relevant code snippets here:

Server:
https://github.com/blitz-js/blitz/blob/cefb5c18ce659d29f8c916e16bd8fa512dc4f168/nextjs/packages/next/stdlib-server/auth-sessions.ts#L785-L813

Client:
https://github.com/blitz-js/blitz/blob/cefb5c18ce659d29f8c916e16bd8fa512dc4f168/nextjs/packages/next/data-client/auth.ts#L107

### What are detailed steps to reproduce this?

1. Visit a production blitz app
2. Visit again after _some_ time
3. See that only the `blitz_sAnonymousSessionToken` cookie is still there.
4. Trigger a query / mutation

Obviously, the invalid state can also be reached by manually deleting the `blitz_sAntiCSRFToken`. 

### Run `blitz -v` and paste the output here:

```
macOS Catalina | darwin-x64 | Node: v14.17.1

blitz: 0.38.5 (global)
blitz: 0.38.5 (local)

  Package manager: yarn 
  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 33.70 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.1/bin/yarn
    npm: 7.20.1 - ~/.nvm/versions/node/v14.17.1/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.26.0 => 2.26.0 
    blitz: 0.38.5 => 0.38.5 
    prisma: 2.26.0 => 2.26.0 
    react: 18.0.0-alpha-ed6c091fe-20210701 => 18.0.0-alpha-ed6c091fe-20210701 
    react-dom: 18.0.0-alpha-ed6c091fe-20210701 => 18.0.0-alpha-ed6c091fe-20210701 
    typescript: ~4.3 => 4.3.3 
```

**Comment by lksnmnn** [comment]
I was able to _reproduce_ this (once) in all browsers (FF, Chrome, Safari), after re-visiting the production app after ~1 month or so. All non `httpOnly` cookies where gone, only the `blitz_sAnonymousSessionToken` was there. I am still not 100% that this is the browsers doing or if this is an issue in Blitz or our implementation.

However, if the user is in this state, we _could_ recover by fetching the `AntiCSRFToken` from the server using a GET request. I.e. if the client finds no `blitz_sAntiCSRFToken` cookie, it should attempt to request an `AntiCSRFToken` token from the server, which either re-uses the current `AnonymousSessionToken` or sets a new session, as we do already.

Alternatively, we could reduce the lifespan of the _anonymous_ cookies or even make them only last the current session (?).

**Comment by flybayer** [comment]
Ok yes, I can confirm that browsers are now removing non httpOnly cookies after ~7 days...

I'm currently working on https://github.com/blitz-js/blitz/issues/2746, then will find a solution for this one

**Comment by lksnmnn** [comment]
I am not sure if this is 100% correct. We have this issue when logging a user in, so only an anonymous session exists. However, antiCSRF checks are still needed in this case, to prevent https://en.wikipedia.org/wiki/Cross-site_request_forgery#Forging_login_requests

So, if the browser was to delete the localStorage (after 7 days as well?), we would end up in the same invalid state (no antiCSRF token, but an anonymous session token). 

We were able to reproduce this, by using "removing website data from the last 24h" in Chrome and then trying to log in again.
