### ISSUE TITLE
AuthenticationError not working and loop

### ISSUE THREAD

**Issue by m0rdreck** [blitz-js/blitz#2721]
### What is the problem?

Hello,

I use AuthenticationError for protect article page on website.

I use this in Query i load my article and in the query i get information for know if user have the authorization for read this.

When i go on this i'm redirect to login page no problem.

But if i go on one page where i have the authorization and after i going to the page where i don't have.

The AuthenticationError is loading in loop and i'm never rediret to login page.

i add to this post loom where you can see first time the error i'm on public page and go on private and after i going to hompage of website and return to protected article and now i'm redirect.

Can i have error with cache ? i use all time same query sometime private, sometime public

### Paste all your error logs here:

```
17:11:46.139 ERROR
getPublicPageContentSlug()
 AuthenticationError  Vous devez vous connecter pour consulter la page
details:
{
  name: 'AuthenticationError',
  statusCode: 401
}
17:11:46.388 INFO getPublicPageContentSlug() Starting with input:
17:11:46.396 
ERROR getPublicPageContentSlug()
 AuthenticationError  Vous devez vous connecter pour consulter la page
details:
{
  name: 'AuthenticationError',
  statusCode: 401
}

```

### Paste all relevant code snippets here:

```
import { resolver, NotFoundError, Ctx, AuthenticationError } from "blitz"
import db from "db"
import * as z from "zod"

const GetPageSlugContent = z.object({
  // This accepts type of undefined, but is required at runtime
  slug: z.string().optional().refine(Boolean, "Required"),
})

export default resolver.pipe(resolver.zod(GetPageSlugContent), async ({ slug }, ctx: Ctx) => {
  const pageContent = await db.pageContent.findFirst({
    where: { slug, state: true },
    include: { file: true, link: true, anchor: true, groupeAgents: true },
  })

  if (
    (!ctx.session.$isAuthorized("ADMIN") &&
      pageContent != null &&
      pageContent.groupeAgents != null &&
      pageContent.groupeAgents.length > 0 &&
      ctx.session != null &&
      ctx.session.groupeAgent != null &&
      pageContent.groupeAgents.filter((i) => {
        if (ctx != null && ctx.session != null && ctx.session.groupeAgent != null) {
          return ctx.session.groupeAgent.indexOf(i.id) !== -1
        }
        return false
      }).length === 0) ||
    (!ctx.session.$isAuthorized("ADMIN") &&
      (ctx.session == null || (ctx.session && ctx.session.groupeAgent == null)) &&
      pageContent != null &&
      pageContent.groupeAgents != null &&
      pageContent.groupeAgents.length > 0)
  ) {
    throw new AuthenticationError(
      `Vous devez vous connecter pour consulter la page "${pageContent.title}"`
    )
  }
  if (!pageContent) throw new NotFoundError()

  return pageContent
})
```

### What are detailed steps to reproduce this?

1.Hard to give you more information.

### Run `blitz -v` and paste the output here:

```
Windows 10 | win32-x64 | Node: v15.8.0

blitz: 0.39.0 (local)

  Package manager: npm
  System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Memory: 11.53 GB / 31.92 GB
  Binaries:
    Node: 15.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.5.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1
    blitz: 0.39.0 => 0.39.0
    prisma: 2.20 => 2.20.1
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    typescript: ~4.2 => 4.2.4

```

### Please include below any other applicable logs and screenshots that show your problem:

https://www.loom.com/share/2466c87247a3484ea3a2c958d2dcb958

**Comment by flybayer** [comment]
Hey @m0rdreck sorry for the delay here.

So is the query actually executing in a loop (i.e. you see server logs for the query repeating)?

In the loom, I see the login form appear, which I assume is from catching authenticationerror. But then I don't see you trying to navigate to another page.

By default, as long as you import `ErrorBoundary` from `blitz`, it will be automatically reset when the page location changes. Is your page url changing? Loom doesn't show this part.

**Comment by m0rdreck** [comment]
Hello @flybayer,

Yes in the server console, I see that the request is called multiple times as well as the authentication error.

After many loops, we are redirected to the login page.

Thank for help

**Comment by m0rdreck** [comment]
Hello @flybayer,

Yes the location changes.

**Comment by flybayer** [comment]
@m0rdreck ok, is this app on github? If not, can you make an open repo with the minimal code to reproduce this?

**Comment by m0rdreck** [comment]
Hello @flybayer,

I found the problem, but i don't have a solution, i try to explain it :

I Have one url exemple page/{slug}

When i'm on page/test1 and i click on link page/test2

Same component, same page with dynamic slug.

The page is not reloading.

For example, on mobile, the menu doesn't close because i think the component is not reloading.

Only the component where i use the query to get page content is reloading.

How to force reload all component on this link ?

**Comment by m0rdreck** [comment]
Hello @flybayer,

The solution i make 2 query

First time i query the group of user (dynamic role).

After i redirect user in front if he don't have the authorization.

After i query the information if user have authorization i request page data.

I make github demo when i have little time.
