### ISSUE TITLE
generate prisma schema with optional column don't work - no matches found: <column-name>:string?

### ISSUE THREAD

**Issue by fmgono** [blitz-js/blitz#2747]
### What is the problem?

I want to generate new table with command 
`blitz generate resource master/shifts code:string:unique name:string? from:string? to:string? isActive:boolean:default=true`

because [the docs](https://blitzjs.com/docs/cli-generate#model-fields) said that if you want to set column to be optional, then add `?` after type (e.g: string?>)

but when i type that, i got an error

### Paste all your error logs here:

```
zsh: no matches found: name:string?
```

### Paste all relevant code snippets here:

```
blitz generate resource master/shifts code:string:unique name:string? from:string? to:string? isActive:boolean:default=true
```

### What are detailed steps to reproduce this?

1. create new blitz project with this command `blitz new odtendance && cd odtendance/ && blitz install chakra-ui`
2. change db from sqlite to postgresql
3. run command `blitz generate resource master/shifts code:string:unique name:string? from:string? to:string? isActive:boolean:default=true`

### Run `blitz -v` and paste the output here:

```
❯ blitz -v
Linux 5.8 | linux-x64 | Node: v14.17.0

blitz: 0.39.0 (global)
blitz: 0.39.0 (local)

  Package manager: npm 
  System:
    OS: Linux 5.8 Zorin OS 16
    CPU: (4) x64 Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz
    Memory: 178.33 MB / 9.60 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: Not Found
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.31.0-integration-undici-4.3 => 2.31.0-integration-undici-4.3 
    blitz: 0.39.0 => 0.39.0 
    prisma: 2.31.0-integration-undici-4.3 => 2.31.0-integration-undici-4.3 
    react: alpha => 18.0.0-alpha-b1a1cb116-20210924 
    react-dom: alpha => 18.0.0-alpha-b1a1cb116-20210924 
    typescript: ~4.3 => 4.3.5 
```

### Please include below any other applicable logs and screenshots that show your problem:

![image](https://user-images.githubusercontent.com/31404706/134815183-d97e62f8-0c2d-4599-bd4f-52cfb992f1a5.png)

**Comment by beerose** [comment]
Hey @fmgono! Thanks for the report. It looks like when you're using `zsh` you need to wrap the field with type in quotes (`""`). The following command worked for me in zsh:
```
blitz generate resource master/shiftst code:string:unique "name:string?" "from:string?" "to:string?" isActive:boolean:default=true
```

Though, it should be documented or fixed so that the same command works in all terminals.

**Comment by fmgono** [comment]
Thank you @beerose , this is work as expected!
