### ISSUE TITLE
Prompt user to create DB or run migration from in browser error page

### ISSUE THREAD

**Issue by kandros** [blitz-js/blitz#275]
### What do you want and why?

Recently I saw this presentation video of Phoenix LiveView (at 1:40)and found interesting that the application was able to detect that a migration was not run and asked to do it right from the error page

https://youtu.be/MZvmYaFkNJI?t=103

**Comment by flybayer** [comment]
That's an amazing idea!

**Comment by flybayer** [comment]
Probably a prerequisite for this is adding a custom Blitz development error page. Currently we just have the default Next.js one
