### ISSUE TITLE
Loading a mutation via `blitz console` fails silently due to a missing ENV var

### ISSUE THREAD

**Issue by beerose** [blitz-js/blitz#2751]
### Discussed in https://github.com/blitz-js/blitz/discussions/2745

> The mutation in question was not being loaded because it referenced an environment variable that was missing. This meant the code would compile via `npm run build` but when console loads mutations it apparently evaluates the code in a run-time fashion even prior to the mutation. Unfortunately, though, if it fails due a missing ENV var it does so silently.

_Originally posted by @jelling in https://github.com/blitz-js/blitz/discussions/2745#discussioncomment-1387880_

**Comment by g3offrey** [comment]
I am working on a solution, that enables the debug mode when run with the verbose flag.

**Comment by jelling** [comment]
@g3offrey what do you think of making it display errors by default, meaning even without a debug flag? My thinking is that the console is designed almost exclusively for technical users. At a minimum, I don't think a console command (or module load) should ever fail silently. A middle ground might be writing errors to a log but only displaying an abbreviated trace message unless the debug flag is set.

**Comment by g3offrey** [comment]
Yes that what I did finally. I always display the errors. I also documented the previously existing DEBUG flags, I think they could have helped in your initial case. You can find my contributions here : 
https://github.com/blitz-js/blitzjs.com/pull/560
https://github.com/blitz-js/blitz/pull/2792
