### ISSUE TITLE
Add Test Setup to `blitz new` template

### ISSUE THREAD

**Issue by Skn0tt** [blitz-js/blitz#277]
### What do you want and why?

The template should encompass a working test-setup to reduce boilerplate and plumbing.
Due to popularity with the React community, I'd advocate for Jest as the test runner.

### Possible implementation(s)

Add a Jest setup to the template.

### Additional context

Since testing is an important part of app dev, we should make it as easy as possible. Maybe some utilities for mocking out queries/mutations would be good to decouple frontend and backend testing.

**Comment by eliasjohansson** [comment]
+1, would be really sweet with a jest configuration in the template. Would love to see react-testing-library examples from the template aswell. 
Looks like this has been discussed before (#97), parts of it might already be in the works.

**Comment by flybayer** [comment]
Also Cypress!

**Comment by flybayer** [comment]
Good discussion on the Redwood forums that we might can learn from: https://community.redwoodjs.com/t/testing-in-redwood/482/13

**Comment by nilaeus** [comment]
Would it be reasonable to add code coverage as well? Or could that be a recipe? Or even a thing at all?
I've been trying to get coverage set up using Cypress, but it tests the cache, and results are incomprehensible.

**Comment by flybayer** [comment]
Yeah, code coverage config would be great too!
