### ISSUE TITLE
[Feature Request]: Add i18n 

### ISSUE THREAD

**Issue by Fghurayri** [blitz-js/blitz#279]
### What do you want and why?

i18n is immensely needed in any web __framework__. 

### Possible implementation(s)

The Nextjs community are yet to agree on the best possible way to implement i18n while keeping SSR / SSG / Serverless working as expected.

Can this be solved by Blitz?

### Additional context

https://github.com/zeit/next.js/discussions/10651

**Comment by flybayer** [comment]
I've never implemented i18n myself, but I agree Blitz should solve this.

So I'd love to hear proposals or ideas on how we should do this!!

**Comment by waptik** [comment]
So after going through all possible solutions/examples, [with-i18n-rosetta](https://github.com/zeit/next.js/tree/canary/examples/with-i18n-rosetta) looks like the best possible solution at the moment ([demo](https://with-i18n-rosetta.now.sh/)) . No difficult setup nor extra build steps.
Besides, you can also use your locales as packages and easily import them in your projects like how [Uppy](https://uppy.io/docs/uppy/#locale) does it.

**Comment by flybayer** [comment]
Awesome, thank you @waptik.

So the Next.js team is working on an official i18n solution. I think we should wait and see that before doing something ourselves.

Only bummer is they haven't given a timeline.

**Comment by waptik** [comment]
@flybayer 😱 wow, that's great news 😋. I think an official solution is the best way to go, especially if it's coming from the authors.
So it's worth waiting 😊
Thanks for sharing the good news

**Comment by wescopeland** [comment]
A quick update on this: [next-i18next now supports serverless i18n from their beta branch](https://github.com/vercel/next.js/discussions/10651#discussioncomment-34992). The implementation relies on path rewrites, which are currently behind an experimental flag but [will be GA on the next stable release](https://github.com/vercel/next.js/pull/14978#issuecomment-659761936).

**Comment by flybayer** [comment]
The [Next.js RFC on i18n Routing](https://github.com/vercel/next.js/discussions/17078) has just been posted!

**Comment by jan-wilhelm** [comment]
any news on this, now that NextJS 10 is used in Blitz and includes official support for i18n routing?

**Comment by flybayer** [comment]
@jan-wilhelm no news! Now that that's released, it's up to y'all to decide if there's more stuff that we should add on top of that in blitz.

**Comment by jan-wilhelm** [comment]
After working with "raw" NextJS i18n for a while, I've found [`next-translate`](https://github.com/vinissimus/next-translate) to be a small and very intuitive library for i18n. I would suggest using this for Blitz too, but I am not sure if it works with Blitz's way of moving NextJS `pages` around. Maybe somebody can try that out? I'm quite busy these days, but could help with that sometime soon.
