### ISSUE TITLE
blitz generate CLI command fails to generate files

### ISSUE THREAD

**Issue by Amaro-Koberle** [blitz-js/blitz#2804]
### What is the problem?

This is the first issue I ever posted on GitHub, please excuse if it is inappropriate in some way.

I am trying to follow the introductory tutorial at https://blitzjs.com/docs/tutorial

However, when I get to the part called "Scaffolding code for our models", I get stuck.
When I run `blitz generate all question text:string` in the CLI, I get an error.

I tried to restart the ES Lint and TypeScript servers, I uninstalled and reinstalled blitz, I created the app both using yarn and npm – I always run into the same error.

When I replace the type `all` of the `blitz generate` command with type `model`, I do NOT get that error. It will successfully add some lines to the schema.prisma file. Any other type such as `resource`, `crud`, `query`, `mutation` or `pages` will also throw a similar error, although the files which the error message reports as having failed to generate change from type to type.

I hope this helps and I hope this is an actual bug rather than some obvious mistake on my part as I do not wish to waste anyone's time. Be that as it may, I'd love to learn how to not run into this error.

### Paste all your error logs here:

```
✕ Error generating __modelIdParam__/edit.tsx
✕ AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/amaro/Dropbox (Personal)/My Mac (Amaro’s MacBook Pro)/Desktop/developer/blitz-tutorial/node_modules/@blitzjs/generator/dist/templates/page/__modelIdParam__/edit.tsx
```

### Paste all relevant code snippets here:

```
// no coding needed to arrive at this error
```

### What are detailed steps to reproduce this?

Following this tutorial (https://blitzjs.com/docs/tutorial) should generate the error as soon as you run `blitz generate all question text:string`.

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v14.17.4

blitz: 0.40.0 (global)
blitz: 0.40.0 (local)

  Package manager: npm 
  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 6.01 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.20.6 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 3.1.1 => 3.1.1 
    blitz: 0.40.0 => 0.40.0 
    prisma: 3.1.1 => 3.1.1 
    react: alpha => 18.0.0-alpha-f2c381131-20211004 
    react-dom: alpha => 18.0.0-alpha-f2c381131-20211004 
    typescript: ~4.3 => 4.3.5
```

**Comment by flybayer** [comment]
Thanks @Amaro-Koberle! This is odd.

So `node_modules/@blitzjs/generator/dist/templates/page/__modelIdParam__/edit.tsx` file does not exist?

Does the `node_modules/@blitzjs/generator/dist` folder exist?

Does the `node_modules/blitz/node_modules/@blitzjs/generator/dist` folder exist?

**Comment by Amaro-Koberle** [comment]
Thanks for the swift reply @flybayer!

node_modules/@blitzjs/generator/dist/templates/page/__modelIdParam__/edit.tsx DOES exist.

```
import {Suspense} from "react"
import {Head, Link, useRouter, useQuery, useMutation, useParam, BlitzPage, Routes} from "blitz"
import Layout from "app/core/layouts/Layout"
import get__ModelName__ from "app/__modelNamesPath__/queries/get__ModelName__"
import update__ModelName__ from "app/__modelNamesPath__/mutations/update__ModelName__"
import {__ModelName__Form, FORM_ERROR} from "app/__modelNamesPath__/components/__ModelName__Form"

export const Edit__ModelName__ = () => {
  const router = useRouter()
  const __modelId__ = useParam("__modelId__", "number")
  if (process.env.parentModel) {
    const __parentModelId__ = useParam("__parentModelId__", "number")
  }
  const [__modelName__, {setQueryData}] = useQuery(
    get__ModelName__,
    {id: __modelId__},
    { 
      // This ensures the query never refreshes and overwrites the form data while the user is editing.
      staleTime: Infinity 
    }
  )
  const [update__ModelName__Mutation] = useMutation(update__ModelName__)

  return (
    <>
      <Head>
        <title>Edit __ModelName__ {__modelName__.id}</title>
      </Head>

      <div>
        <h1>Edit __ModelName__ {__modelName__.id}</h1>
        <pre>{JSON.stringify(__modelName__, null, 2)}</pre>

        <__ModelName__Form
          submitText="Update __ModelName__"
          // TODO use a zod schema for form validation
          //  - Tip: extract mutation's schema into a shared `validations.ts` file and
          //         then import and use it here
          // schema={Update__ModelName__}
          initialValues={__modelName__}
          onSubmit={async (values) => {
            try {
              const updated = await update__ModelName__Mutation({
                id: __modelName__.id,
                ...values
              })
              await setQueryData(updated)
              router.push(
                process.env.parentModel
                  ? Routes.Show__ModelName__Page({ __parentModelId__: __parentModelId__!, __modelId__: updated.id })
                  : Routes.Show__ModelName__Page({ __modelId__: updated.id }),
              )
            } catch (error: any) {
              console.error(error)
              return {
                [FORM_ERROR]: error.toString(),
              }
            }
          }}
        />
      </div>
    </>
  )
}

const Edit__ModelName__Page: BlitzPage = () => {
  if (process.env.parentModel) {
    const __parentModelId__ = useParam("__parentModelId__", "number")
  }

  return (
    <div>
      <Suspense fallback={<div>Loading...</div>}>
        <Edit__ModelName__ />
      </Suspense>

      <p>
        <if condition="parentModel">
          <Link href={Routes.__ModelNames__Page({ __parentModelId__: __parentModelId__! })}>
            <a>__ModelNames__</a>
          </Link>
          <else>
            <Link href={Routes.__ModelNames__Page()}>
              <a>__ModelNames__</a>
            </Link>
          </else>
        </if>
      </p>
    </div>
  )
}

Edit__ModelName__Page.authenticate = true
Edit__ModelName__Page.getLayout = (page) => <Layout>{page}</Layout>

export default Edit__ModelName__Page
```
![image](https://user-images.githubusercontent.com/53105057/136076613-9a05fbff-30fa-4404-a021-16047a4a1d5b.png)

4 imports are underlined with red squiggles. 

All of the errors read `Cannot find module 'app/...'`

`get__ModelName__`, `update__ModelName__` and `__ModelName__Form` all actually do not exist. `app/core/layouts/Layout` however, DOES exist. In it, `<Head>` is underlined with red squiggles. The error looks like this:
![image](https://user-images.githubusercontent.com/53105057/136078009-d84a1c93-43c3-4811-9461-1b8a1ec049b9.png)
The file otherwise contains this:
```
import { ReactNode } from "react"
import { Head } from "blitz"

type LayoutProps = {
  title?: string
  children: ReactNode
}

const Layout = ({ title, children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>{title || "blitz-tutorial"}</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {children}
    </>
  )
}

export default Layout
```

I hope that helps

**Comment by flybayer** [comment]
@Amaro-Koberle to confirm, the below is what you see?

```diff
-node_modules/@blitzjs/generator/dist/templates/page/__modelIdParam__/edit.tsx 
+node_modules/@blitzjs/generator/dist/templates/page/modelIdParam/edit.tsx 
```

If that's the case, I highly suspect something goofy in your local environment. Maybe a shell or anti virus or something that is stripping out the `__X__` from file names.

Are you able to try in a new user account on your computer, or another computer or something?

**Comment by beerose** [comment]
Thank you for letting us know, @Amaro-Koberle! I'm closing this issue then, but feel free to reopen if it happens again, or it turns out to be Blitz related after all.
