### ISSUE TITLE
field.ts type errors

### ISSUE THREAD

**Issue by Vandivier** [blitz-js/blitz#2805]
### What is the problem?

As a developer, I notice some type errors in this file. Image below, but here's one error text snippet:
`Property 'group' is missing in type '{ type: "attribute"; kind: "field"; name: string; }' but required in type 'Attribute'.`

![image](https://user-images.githubusercontent.com/5559355/136058454-e6660274-dc79-4882-b992-a6d44373b91a.png)

### Paste all your error logs here:

see above

### Paste all relevant code snippets here:

see above

### What are detailed steps to reproduce this?

1. Fresh clone "version": "0.40.0", on Oct 5 (`This branch is even with blitz-js:canary.`)
2. `yarn` within `blitz/packages/generator` (I did not yarn at top-of-repo)
3. open `blitz/packages/generator/package.json` in vs code
4. see some red stuffs :)

### Run `blitz -v` and paste the output here:

```
$ blitz -v
Windows 10 | win32-x64 | Node: v16.2.0

blitz: 0.39.0 (global)
blitz: 0.40.0 (local)

  Package manager: npm
  System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
    Memory: 7.06 GB / 19.86 GB
  Binaries:
    Node: 16.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.20.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```

**Comment by flybayer** [comment]
Hey, did you first run `yarn dev` or `yarn build` as it states [in the contributing docs](https://blitzjs.com/docs/contributing#development-setup)?

**Comment by Vandivier** [comment]
Good call i didn't...will check and ya that will prob fix it if it's a prisma thing right?

**Comment by Vandivier** [comment]
`yarn buildpkg` resolved the issue (+ close VS Code + Open VS Code to make red squiggles go away)
