### ISSUE TITLE
Put generated zod schemas into a separate file

### ISSUE THREAD

**Issue by Talor-A** [blitz-js/blitz#2815]
### What do you want and why?

Per #2754,
The current `generate` script crates queries / mutations with a zod schema in the same file. When users attempt to export this schema to use in e.g. form validation, it will fail as all imports from query / mutation files are replaced. 

Instead, it would be great if they were in a separate file to avoid this unexpected behavior. 

### Possible implementation(s)

For one solution, whenever queries & mutations are generated create a folder such as `validations/` or `schemas/` containing these zod schemas that both the UI and server code can import. 

### Additional context

See #2754

**Comment by Talor-A** [comment]
> Couldn't it be a single file, e.g. `schemas.ts` or `validators.ts` containing all the schemas in a particular queries/mutations directory, for example: `users/queries/validators.ts`? 

I'm not sure, do all files in a ` queries` directory get transformed? Or would this not be an issue?

**Comment by flybayer** [comment]
👆 @beerose's comment as the correct approach here imo.

**Comment by meehawk** [comment]
@beerose is this still relevant? If so I'd love to take it

**Comment by flybayer** [comment]
@meehawk yes!
