### ISSUE TITLE
make RouteURLObject work directly with res.redirect

### ISSUE THREAD

**Issue by okmr-d** [blitz-js/blitz#2816]
### What do you want and why?
Currently, the expected type of API route' `res.redirect` is string.

It would be nice if we could pass one of our Route Manifest objects into this field.

### Possible implementation(s)

(1) ~add toString() method to RouteURLObject~ (will be covered by blitz-js/blitz#2829).

(2) make RouteURLObject work directly with res.redirect.

### Additional context
similar issue: https://github.com/blitz-js/legacy-framework/issues/79

I think (1) would be convenient, because we can use it anywhere else (for example, canonical tags).

**Comment by beerose** [comment]
Ideally, we could have both implementations. The first one could also cover this issue: https://github.com/blitz-js/blitz/issues/2829 (the suggested solution is slightly different but also works). To keep things tidy, I'll rename this issue to `make RouteURLObject work directly with res.redirect` (solution number 2), and solution number 1 will be covered by https://github.com/blitz-js/blitz/issues/2829. Hope that works.
