### ISSUE TITLE
Feature Request: Bulma Recipe

### ISSUE THREAD

**Issue by vivek7405** [blitz-js/blitz#2835]
### What do you want and why?

I want to add the Bulma CSS framework to the project using Blitz recipe because I am not a CSS expert and Bulma provides a rich set of components which are customisable. Again, Bulma is a popular CSS framework and it is also being used in the Hactoberfest app. 

### Possible implementation(s)

Need to integrate Bulma in the bare Blitz app and see what files are added/changed and come up with a Blitz recipe for making the appropriate changes to the project.

### Additional context

Here's the link to the Bulma website: https://bulma.io

**Comment by vivek7405** [comment]
> Saw this mentioned in introductions. Welcome @vivek7405 👋
> 
> Isn't Bulma **just** a css library? I think all you need to do is add via npm and then globally import the css file in _app.js?

Hi @paulm17 👋🏻

I installed bulma and node-sass and imported the App.sass file (with all the bulma variables and imports) in _app.js.
But, there were errors regarding Node Sass version being incompatible:
```
error - ./node_modules/next/dist/compiled/css-loader/cjs.js??ruleSet[1].rules[5].oneOf[7].use[1]!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ruleSet[1].rules[5].oneOf[7].use[2]!./node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[5].oneOf[7].use[3]!./node_modules/next/dist/compiled/sass-loader/cjs.js??ruleSet[1].rules[5].oneOf[7].use[4]!./app/App.sass
Error: Node Sass version 6.0.1 is incompatible with ^4.0.0 || ^5.0.0.
```

I then installed the specific Node Sass version 4.14.1 and then it worked.

Just thought it would be easier to configure with a recipe for Bulma, but we can probably think of it at a later stage if we have other items on priority.

**Comment by paulm17** [comment]
Hi @vivek7405 Did you follow https://nextjs.org/docs/basic-features/built-in-css-support#sass-support ?  Maybe it is better than node-sass?

Let me know, if this works or not.

Thanks
