### ISSUE TITLE
file storage abstraction layer and transform API

### ISSUE THREAD

**Issue by fleck** [blitz-js/blitz#2845]
### What do you want and why?

A file storage abstraction layer and transform API. Similar to https://edgeguides.rubyonrails.org/active_storage_overview.html

### Possible implementation(s)

My current setup in a blitz app:

The storage driver is based on @slynova/flydrive. This allows for the same API for s3 (and by extension most competing object storage services), Google Cloud Storage, and local (mostly for development/testing)

It's a "proxy based architecture" meaning request for an original image or transformed image comes to blitz and then blitz proxies the request from the service to the users browser. This greatly simplifies a couple of aspects of file handling:

- blob storage services generally don't recommend publicly accessible URLs, this results in having to sign temporary urls to access the file (this was a pain point in the original Active record setup...).
- proxying simplifies CDN caching of files

The setup I currently have is built around API routes:

```bash
│  *   │ app/api/files/create.ts                               │ /api/files/create                               │ API  │
│  *   │ app/api/files/[key]/[filename].ts                     │ /api/files/[key]/[filename]                     │ API  │
│  *   │ app/api/files/[key]/variant/[variation]/[filename].ts │ /api/files/[key]/variant/[variation]/[filename] │ API  │
```

create.ts is based on busboy

The model of a file is

```ts
model File {
  id          Int      @id @default(autoincrement())
  key         String   @unique
  hash        String?  @unique
  name        String
  contentType String
  metadata    Json     @default("{}")
  byteSize    Int
  serviceName String
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
}
```

In the UI I have a hook with the following API for uploading a file:

```ts
// it's based on react dropzone, localURL is for when a user wants to display a preview of the image while it's uploading.
const { localURL, getRootProps, fileInput, getInputProps, filename, file, progress, done } =
  useFileUpload()
```

for consuming the file:

```ts
// The second argument is an optional transform.
<img src={urlFor(image, "rotate")} />
```

transforms would be defined something like this:

```ts
export const transformFunctions = {
  rotate: (file: NodeJS.ReadableStream) => file.pipe(sharp().rotate(90)),
}
```

Transforms are lazy. The first time a transform is requested the original is loaded from the service, the transform is applied and the result is stored in the service so we don't have to re-apply the transform for subsequent requests.

### Additional context

Active Storage is one of my favorite features from rails and having something similar in blitz would be great. What would be the best way to go about integrating a file storage/access/transform API into blitz? I'd be happy to work on a PR if the core team is looking to add this kind of functionality to blitz.

**Comment by fleck** [comment]
anybody interested I have a recipe setup if you wanna kick the tires and provide feedback!

https://github.com/fleck/file-depot#install

**Comment by beerose** [comment]
@fleck it looks awesome! Do you want to create a PR with your recipe?

Also, is there a way to not use sharp? As it's a native module it can cause a lot of problems and increase the barrier of entry for new contributors or cause problems for existing ones (that is if you want to create a PR to blitz).

**Comment by fleck** [comment]
@beerose great! I'll work on getting a PR ready. Good idea on not using sharp by default. I'll see if I can get it to work with https://github.com/oliver-moran/jimp and then comment out a sharp based solution (sort of how blitz defaults to sqllite, but has postgresql settings commented out as many users will ultimately want that).
