### ISSUE TITLE
`blitz generate` doesn't properly handle relations

### ISSUE THREAD

**Issue by chrisjkr** [blitz-js/blitz#2864]
### What is the problem?

When generating a Prisma model, `blitz generate` ignores the fact that we also have to add a relation definition to a target model.

### Paste all your error logs here:

```
Error: Schema parsing
error: Error validating field `a` in model `b`: The relation field `a` on Model `B` is missing an opposite relation field on the model `A`. Either run `prisma format` or add it manually.
```

### Paste all relevant code snippets here:

See below

### What are detailed steps to reproduce this?

1. `blitz generate model a name:string`
2.`blitz generate model b name:string relation:A` 

This will produce an invalid model.

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v16.9.1

blitz: 0.41.1 (global)
blitz: 0.41.1 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Apple M1
    Memory: 93.39 MB / 16.00 GB
    Shell: 3.2.0 - /usr/local/bin/fish
  Binaries:
    Node: 16.9.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.20.5 - /opt/homebrew/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  npmPackages:
    @prisma/client: 3.3.0 => 3.3.0 
    blitz: 0.41.1 => 0.41.1 
    prisma: 3.3.0 => 3.3.0 
    react: alpha => 18.0.0-alpha-b81de8633-20211019 
    react-dom: alpha => 18.0.0-alpha-b81de8633-20211019 
    typescript: ~4.3 => 4.3.5 
```

**Comment by beerose** [comment]
Or we can call `prisma format` inside of `blitz generate` command.

**Comment by flybayer** [comment]
I think Prisma used to add that automatically, but now it seems they error lol. Prisma format seems like a good solution.

**Comment by thisdotrob** [comment]
Is the plan still to open a separate PR for this? I found my way to this issue I as I couldn't work out how to cleanly use `blitz g` to generate models with relationships, as the docs suggests it should.

**Comment by thisdotrob** [comment]
Something to note; running `blitz prisma format` to create the missing opposite relation does not set the `fieldName` as I'd expect.

For example, running the below
```
blitz g model Foo
blitz g model Bar foos:Foo[]
blitz prisma format 
```

will result in the following on the Foo model
```
  Bar       Bar?     @relation(fields: [barId], references: [id])
  barId     Int?
```

I would have expected the `fieldName` to be `bar` not `Bar`.

**Comment by thisdotrob** [comment]
Also, what should happen when using `belongsTo`?

E.g.:
```
blitz g model Foo
blitz g model Bar belongsTo:Foo
blitz prisma format
```
will result in the following on the `Foo` model:
```
  Bar       Bar[]
```

It assumes there should be a one-many relationship Foo -> Bar, but the user may want a one-one relationship.

Also, if it is a one-many relationship, I would expect the `fieldName` to be `bars` not `Bar`...

**Comment by flybayer** [comment]
hmm ok, sounds like we can't just rely on prisma format then.

```
blitz g model Foo
blitz g model Bar belongsTo:Foo
```

should result in 
```
model Foo {
  bars       Bar[]
}
```
