### ISSUE TITLE
When redirecting to oauth endpoint, a page redirection error popups

### ISSUE THREAD

**Issue by ospfranco** [blitz-js/blitz#2871]
### What is the problem?

I implemented third party login via oauth in my app, followed the steps in the official documentation, however, when I do the redirection to the `/api/auth/oauth2` endpoint, the page resolution algorithm kicks in and fails to find a page under `/pages/api/auth/oauth2`, therefore there is a brief error flash:

![138179569-934eec59-32b8-4082-9a67-069d018a270d](https://user-images.githubusercontent.com/1634213/138445018-57dfed51-dabe-4f40-92a1-3ba43f7dcb03.png)

Afterwards the redirection works, but its scary to see the big error when logging in

### Paste all your error logs here:

```
NO LOGS
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1. Create an oauth login endpoint
2. Try to login

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-arm64 | Node: v15.14.0

blitz: 0.41.1 (global)
blitz: 0.41.1 (local)

  Package manager: yarn
  System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 137.00 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v15.14.0/bin/yarn
    npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
    Watchman: 2021.08.02.00 - /opt/homebrew/bin/watchman
  npmPackages:
    @prisma/client: 3.2.1 => 3.2.1
    blitz: 0.41.1 => 0.41.1
    prisma: 3.2.1 => 3.2.1
    react: alpha => 18.0.0-alpha-f6abf4b40-20211020
    react-dom: alpha => 18.0.0-alpha-f6abf4b40-20211020
    typescript: ~4.3 => 4.3.5
```

**Comment by beerose** [comment]
@ospfranco are you using `Link` component for auth buttons? If yes, I think the issue is that Next tries to navigate to a Next page without reloading the app, so using `a` should work fine (a will direct the user to an URL as a new page). 

@flybayer correct me if I'm wrong, but shouldn't there always be `a` for links to auth API?

**Comment by ospfranco** [comment]
Ah, you are right, I was using a `<Link/>`! Sorry, my bad!
