### ISSUE TITLE
Request to a github action for contributors

### ISSUE THREAD

**Issue by Jassi10000** [blitz-js/blitz#2883]
### What do you want and why?
Blitsz is an awesome and an engaging repository , plus due to hacktoberfest'21 many open source enthusiasts ( preferably students who are first time contributors ) open issues and PRs which eventually help repo to grow
I think there should be a github action to welcome  contributors on their each issue and PR
The more information the better!

### Possible implementation(s)

How might we do this?
For this I would like to add a Github Action to automate the welcoming stuff . It looks good and engaging

**Comment by flybayer** [comment]
I think I agree with @beerose. It's always better if a human responds than a bot.

**Comment by Jassi10000** [comment]
Ok sure , no issues

**Comment by beerose** [comment]
I'm closing this issue then. But thanks for an idea @Jassi10000 — we may reconsider it in the future!
