### ISSUE TITLE
Add `deepEqual` utility to stdlib and use it for `initialValuesEqual` in `react-final-form` template

### ISSUE THREAD

**Issue by beerose** [blitz-js/blitz#2895]
### What do you want and why?

If a user has a react-final-form with a JS Set (or Map) in the initial values, the form resets on some activities, e.g. switching to another tab.

### Possible implementation(s)

This can be fixed by using the `initialValuesEqual` prop:

```jsx
import deepEqual from "fast-deep-equal"

    <FinalForm
      initialValues={initialValues}
      initialValuesEqual={deepEqual}
```

We can add a `deepEqual` utility to our `stdlib` and then add it to final form template. We can use the `nextjs` compiled lib setup to add `fast-deep-equal`.

File where we can export `deepEqual`: https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/stdlib/index.ts

Form template: https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/app/_forms/finalform/Form.tsx#L29

### Additional context

https://github.com/blitz-js/legacy-framework/issues/217

**Comment by meehawk** [comment]
@beerose can i take this up?

**Comment by meehawk** [comment]
@beerose sorry for the delay, gonna take this up this week. Had been travelling the previous week

**Comment by beerose** [comment]
> @beerose sorry for the delay, gonna take this up this week. Had been travelling the previous week

Ok! Let us know if you have any questions
