### ISSUE TITLE
[Feature] `blitz db seed` can be receive the file option

### ISSUE THREAD

**Issue by dhythm** [blitz-js/blitz#2898]
### What do you want and why?
`blitz db seed` always refers `db/seeds.ts`, it may be useful to refer another path like `db/mock.ts`.
The reason why I think so that we sometimes want to prepare mock DB to check behaviors, but not want to rewrite `db/seed.ts` for temporary check.

So, I think that adding the file option to `blitz db seed` like `blitz db seed -f db/mock.ts` would help us much more.

### Possible implementation(s)

if cli receives the file option, `seedPath` uses the received file.
if not, `seedPath` uses `db/seeds` by default.

https://github.com/blitz-js/blitz/blob/51d91c3c9d2b89e01dd4a5f9478146cff278ae90/packages/cli/src/commands/db.ts#L15

### Additional context
Thanks for all blitz members. This framework is great!.

**Comment by beerose** [comment]
Thanks for the issue! That's a good idea to have a file option
