### ISSUE TITLE
useMutation does not have a type error for mutation without required input

### ISSUE THREAD

**Issue by tmcw** [blitz-js/blitz#2918]
### What is the problem?

On a clean Blitz install, find a mutation with an argument, like:

```ts
await signupMutation(values)
```

Editing that mutation to a version without an argument, like

```ts
await signupMutation()
```

Will pass TypeScript's type checking, but will trigger an error in Zod because you've called the underlying mutation endpoint with `undefined` instead of an object. This appears to root in the custom types that Blitz has for a mutation function here:

https://github.com/blitz-js/blitz/blob/f6354d2dd5928f34c331377c1fe9b406b3940429/nextjs/packages/next/data-client/react-query.tsx#L340-L348

Which allow the first argument to be omitted.

### Paste all your error logs here:

```
PASTE_HERE (leave the ``` marks)
```

### Paste all relevant code snippets here:

```
14:33:08.593 ERROR signup()
 ZodError  [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [],
    "message": "Required"
  }
]
details:
{
  issues: [
    {
      code: 'invalid_type',
      expected: 'object',
      received: 'undefined',
      path: [],
      message: 'Required'
    }
  ],
  format: [Function (anonymous)],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  flatten: [Function (anonymous)],
  name: 'ZodError'
}
error stack:
• ZodError.ts:140 ZodError
    node_modules/zod/src/ZodError.ts:140:5

• types.ts:72 handleResult
    node_modules/zod/src/types.ts:72:19

• types.ts:216 <anonymous>
    node_modules/zod/src/types.ts:216:12
```

### What are detailed steps to reproduce this?

1. Initialize any Blitz project
2. Remove the first argument from a mutation that requires its first argument.

### Run `blitz -v` and paste the output here:

```
macOS Monterey | darwin-x64 | Node: v16.7.0

blitz: 0.42.0 (global)
blitz: 0.42.0 (local)

  Package manager: yarn
  System:
    OS: macOS 12.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 884.07 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.7.0 - ~/n/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 3.4.1 => 3.4.1
    blitz: 0.42.0 => 0.42.0
    prisma: 3.4.1 => 3.4.1
    react: 18.0.0-alpha-5ca4b0433-20211020 => 18.0.0-alpha-5ca4b0433-20211020
    react-dom: 18.0.0-alpha-5ca4b0433-20211020 => 18.0.0-alpha-5ca4b0433-20211020
    typescript: ~4.4 => 4.4.4


```

**Comment by flybayer** [comment]
There are two use cases we want to support here:

1. No first arg
```ts
// client
await doThingMutation()

// server
export default doThing(_: any, ctx: Ctx) {}
```

2. Required first arg
```ts
// client
// @expect-ts-error
await doThingMutation()

// server
export default doThing(id: number, ctx: Ctx) {}
```

When I was creating the types some time ago, I couldn't figure out how to support both, so I only got the first case to work. But probably there is a way to make them both work.

**Comment by shaohaolin** [comment]
What is thought on setting first argument to required? Doing so will prevent possible bugs and fix typing, at the expense of having to call the function as `mutate(undefined)` when the mutation does not have any variables.
