### ISSUE TITLE
[Feature] Create alpha example with knex or pg driver instead of prisma

### ISSUE THREAD

**Issue by Johnson444** [blitz-js/blitz#292]
Thank you very much for Blitz and also that you don't focus on GraphQL. I share your opinion that GraphQL is great but might be to heavy for indie developers.

### What do you want and why?

Following up on your twitter tweet it would be cool to add an example to the alpha that explains how to use blitz with native db driver instead of prisma.

I am interested mostly how to share the db connection between files. Is it enough to connect to the database at start up of blitz and import / export it to all javascript files, or do I have to do more to support a shared connection.

### Possible implementation(s)

I feel knex implementation would be best as it's widely used and support multiple databases. Alternative would be pg driver.

### How might we do this?

Implement simple CRUD app with at least two pages.

### Additional context

https://twitter.com/blitz_js/status/1254706828014911488
http://knexjs.org
https://github.com/brianc/node-postgres

**Comment by aem** [comment]
Hm. So I like the idea of letting people work in the environment they work best, but my concern about not being opinionated about Prisma is that we lose some control over the ecosystem and lose the ability to have a truly batteries-included implementation. For example, it would be quite challenging to truly support an arbitrary database abstraction with `blitz generate`, if we make it easy to not use Prisma then I think we'll find a lot of users upset that they don't have access to some of the CLI features until after they're too invested in their new DB engine.

A good corollary is Rails and ActiveRecord. Rails is _very_ opinionated about ActiveRecord (while still letting you use whatever DB you'd like under the hood, mysql, pg, etc.) which means that, yes, you're stuck with ActiveRecord even if you don't like it, but the `rails` CLI becomes infinitely more useful. While the scaffolding + generation part of Rails is nice, what truly makes it **magical** is the data layer, and I anticipate the same for Blitz. If we can effectively use Prisma to generate most of the code for our users so they don't have to touch anything in the data layer, Blitz's value will be obvious and immediate. If we allow a user to swap out their data layer then Blitz becomes not much more than a light wrapper around Next.js.

**Comment by ryardley** [comment]
I think it would be fine so long as we provided a plugin architecture around it. We should be developing in such a way to enable this.

**Comment by aem** [comment]
I think that's fair, but currently we're fully baked in on Prisma right now. I think we should put this on the backlog until #242 is fleshed out. Until then We don't really know how to architect the CLI to support this. Maybe we should have an architecture call about #242 soon?

**Comment by flybayer** [comment]
@Johnson444 is only wanting an example here, not an integration. We can explore a plugin integration later.

But for now someone can go ahead and create an example app that uses Knex instead of Prisma. The generators will generate code that can't be used without modification, but this is better than nothing for now.

**Comment by aem** [comment]
👍 works for me, I assumed they wanted want an example that's reasonably serviced by the CLI. If we're fine with an example that requires more manual work to iterate then this seems good to give people an idea of the flexibility of the framework

**Comment by Johnson444** [comment]
hey Aem,

I know the scope of this suggestion is clarified. I still feel I need to send you a reply to your first message as it is an important topic you raised and wanted to give you my insight of why I don't like Prisma.

As disclaimer, I am in a weird spot :-) I know SQL, vanilla JS, HTML, CSS. I recently switched from PHP to Node.js as I wanted to focus on JS for backend and frontend. So all the "middlelayer" stuff like SSR is new to me. That is why I am so excited for Blitz as I hope it can help me with it.
  
I fully hear you with loosing control of the ecosystem but Prisma is not the right tool for me. I understand that it gives awesome type support and I guess it can also help very well with table migrations. 

But for me the power of SQL is the dynamic query language. I can use auxiliary statements, CASE expression, subqueries, JSONB,  json_agg / array_agg and much more. 

I missed all this freedom using Prisma 1 and while prisma 2 offers way more flexibility I still see a lot of this either not possible or super complicated to do. As it still locks me in to their query builder syntax.

I don't know ActiveRecord but I assume that it's an ORM similar to Eloquent in Laravel. The main differences to Prisma is that it allows me to create own scopes, set relationships, or use RAW statements within my query. This allows me to break out if I need to. Again, I don't see this as easy in Prisma.

That is why I prefer Knex or TypeORM as ryadley proposed.  

Anyway I am just an indie developer who has fun building stuff in his free time. So I might not be your main target. I am still very thankful for all your work and super hyped to see it grow :-)

**Comment by flybayer** [comment]
@Johnson444 I'm confident we can have a nice knex plugin integration for folks like you. Blitz is DB agnostic, so we're setting it up that the db layer is easily swappable. We're definitely not trying to force everyone to use Prisma!

For what it's worth, Prisma 2 does have a `db.raw('SELECT ...')` api that gives you direct access to the DB.

**Comment by Johnson444** [comment]
oh that is cool.  just looked at the query builder syntax.. I steel feel the pain of prisma 1 .. but maybe I will give it another shot one day.
