### ISSUE TITLE
"@mui/icons-material" missing

### ISSUE THREAD

**Issue by hugo4711** [blitz-js/blitz#2933]
### What is the problem?

mui dependencies like "@mui/icons-material" are missing

### Paste all your error logs here:

```
PASTE_HERE (leave the ``` marks)
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
PASTE_HERE (leave the ``` marks)
```

**Comment by beerose** [comment]
Hi @hugo4711, could you provide more details? Is the `@mui/icons-material` dependency required for a project to build & run after installing the material recipe?

**Comment by beerose** [comment]
I just tried this recipe and it seems to work correctly — any additional dependencies are up to the users. I'm closing the issue — feel free to reopen with more details.
