### ISSUE TITLE
`Blitz codegen` fails to create Route when there is a comment between JSX component and default if use getLayout and authenticate

### ISSUE THREAD

**Issue by jahilliard** [blitz-js/blitz#2944]
### What is the problem?

See video in more section, but route won't be generated if there is a comment between blitz page and `export default`.  Only able to reproduce while using the `[PAGE].authenticate` and/or `[PAGE]..getLayout`

### Paste all your error logs here:

NA

### Paste all relevant code snippets here:

NA

### What are detailed steps to reproduce this?

1. see video

### Run `blitz -v` and paste the output here:

```
Linux 5.4 | linux-x64 | Node: v16.12.0

blitz: 0.42.4 (global)
blitz: 0.38.6 (local)

  Package manager: yarn 
  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Xeon(R) CPU @ 2.80GHz
    Memory: 2.62 GB / 62.81 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.12.0 - ~/.nvm/versions/node/v16.12.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.12.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.12.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.28.0 => 2.28.0 
    blitz: 0.38.6 => 0.38.6 
    prisma: 2.28.0 => 2.28.0 
    react: alpha => 18.0.0-alpha-6f3fcbd6f-20210730 
    react-dom: alpha => 18.0.0-alpha-6f3fcbd6f-20210730 
    typescript: ~4.3 => 4.3.5 
```

### Please include below any other applicable logs and screenshots that show your problem:

https://www.loom.com/share/be90b4d0116642129657bb1886bf41dc

**Comment by beerose** [comment]
That's weird. Thanks for reporting
