### ISSUE TITLE
Logout redirect between pages with oposite auth state redirects can't be done cleanly

### ISSUE THREAD

**Issue by ricardoSlv** [blitz-js/blitz#2959]
### What is the problem?

With the folowing pages:

- Page A -> Redirects Unauthorized users to Login Page
- Home Page -> Redirects Authorized users to Page B

If we're on page A and want to do a logout and redirect to Home Page, we have no way of doing that without causing issues on the site.

1.  If we call router.redirect(Home Page) and then logout mutation, the site executes the routing before the mutation, but since Home redirects authenticated users to Page B, and the logout mutation hasn't finished, i end up in Page B.

2.  If call the logout mutation and then router.redirect(Home Page), the site executes the mutation but flickers on the login page(due to the redirect Page A has), and only then redirects to the Home Page.

### Paste all relevant code snippets here:

```js
HomePage.redirectAuthenticatedTo = Routes.PageB()

PageA.authenticate = { redirectTo: Routes.LoginPage() }

// Option 1 - Ends up in Page B
<Button onClick={async () => {
                  await router.push(Routes.Home())
                  await logoutMutation()
}}/>

// Option 2 - Flickers Login Page
<Button onClick={async () => {
                  await logoutMutation()
                  await router.push(Routes.Home())
}}/>
```

**Comment by beerose** [comment]
Thanks!
