### ISSUE TITLE
Pipe yarn/npm output to log file rather than stdout

### ISSUE THREAD

**Issue by aem** [blitz-js/blitz#296]
### What do you want and why?

The `blitz new` process looks scary because of all of the `npm`/`yarn` install output. We should hide this from the user and instead show them a nice loading spinner and maybe even some helpful docs to read while the process is running.

### Possible implementation(s)

`cross-env` should give us a way to pipe the output to, well, not the console. Worst case we can update the terminal command to `> ./[name]/blitz-log.log` or something.

**Comment by eliasjohansson** [comment]
I can look into this!

**Comment by flybayer** [comment]
We should show more progress than just a spinner. Ideally we could just hide all the warnings and leave the rest. 

Npm has a log level flag we can use but yarn doesn’t.

**Comment by ryardley** [comment]
We can run `yarn --json` which serializes output (we should do this too eventually)

**Comment by eliasjohansson** [comment]
So set loglevel for npm and manually format yarn output with `--json`? Looks like npm is going to implement a json flag aswell: https://docs.npmjs.com/misc/config#json. So maybe we can handle both the same way further down the road.
