### ISSUE TITLE
Blitz Console TypeScript Ctx error

### ISSUE THREAD

**Issue by dvnrsn** [blitz-js/blitz#2988]
### What is the problem?

[Short Discord Mention](https://discord.com/channels/802917734999523368/870041934046060615/910998525003825162)

When running `blitz console`, I experience the following error

```
Property 'session' does not exist on type 'Ctx'
```

Linting passes fine locally and in CI

### What are detailed steps to reproduce this?

1.  I thought this happened with new blitz apps but perhaps I was mistaken. It's happening on an aged blitz application (that has been updated).
2. Basically any use of ctx.session is breaking blitz console

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v14.18.0

blitz: 0.41.1 (global)
blitz: 0.42.0 (local)

  Package manager: npm
  System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.55 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    Yarn: Not Found
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 3.4.2 => 3.4.2
    blitz: 0.42.0 => 0.42.0
    prisma: 3.4.2 => 3.4.2
    react: 0.0.0-experimental-13455d26d-20211104 => 0.0.0-experimental-13455d26d-20211104
    react-dom: 0.0.0-experimental-13455d26d-20211104 => 0.0.0-experimental-13455d26d-20211104
    typescript: 4.4.4 => 4.4.4
```

### Please include below any other applicable logs and screenshots that show your problem:

<img width="291" alt="image" src="https://user-images.githubusercontent.com/9112811/142639456-2d671caf-5897-4c1d-a095-8abc13e54c37.png">

**Comment by beerose** [comment]
Thanks for creating the issue!

**Comment by jmar777** [comment]
Thought I would mention that I ran into this as well while working through the intro tutorial.

In my case, `ctrl + d` and then running `npx blitz console` again (with no changes made) got me past the issue. Perhaps a race condition or "first run" bug?

**Comment by chrisj-back2work** [comment]
In my case, the errors occur every time I open the console. I'm using Blitz 0.45.3.

**Comment by beerose** [comment]
Should be fixed by https://github.com/blitz-js/blitz/pull/3863 (as we switched to esbuild)
