### ISSUE TITLE
[Feature Request] Possible to make anonymous session at passportAuth

### ISSUE THREAD

**Issue by kyoungduck** [blitz-js/blitz#3004]
### What do you want and why?

I want to make anonymous session at passportAdapter. For now, I can only return error or publicData to passport `done` callback.
But I just want to make anonymous session(private session).

Because I need to get user information after third party authorized. For example, when I try to implement "Login with blizzard account" I can use [passport-bnet](https://github.com/Blizzard/passport-bnet) but, blizzard never give me the user's email. So I need to get email from use after blizzard authentication finished. So I try to set blizzard auth information to anonymous session. But for now, I can't put `null` to `userId`(if userId is null, I must give exception to callback first argument).
![image](https://user-images.githubusercontent.com/16463746/143732859-54a43ffc-ce81-4dc4-ba91-e46028667a3e.png)

### Possible implementation(s)

Make possible like this.
```
done(null, { privateData:{}, redirectUrl: "REDIRECT_URL" })
```

I think it must fix `VerifyCallbackResult` type.

```
export type VerifyCallbackResult = {
  publicData?: PublicData
  privateData?: Record<string, any>
  redirectUrl?: string
}
```

### Additional context

I was talking about this at Discord. [link](https://discord.com/channels/802917734999523368/870041934046060615/910190456921534514)

**Comment by beerose** [comment]
I'm going to close this issue and move the discussion back to Discord.
