### ISSUE TITLE
Tailwindcss is not working in Blitz project

### ISSUE THREAD

**Issue by AngelEngineer314** [blitz-js/blitz#3018]
### What is the problem?

I already installed Tailwindcss but the classes are not reflected on project.
And when I reinstall Tailwindcss module, it is error like "Error: Cannot find module 'next/dist/server/lib/logging'".

### Paste all your error logs here:

```
Error: Cannot find module 'next/dist/server/lib/logging
```
$ blitz install tailwind
    Error: Cannot find module 'next/dist/server/lib/logging'
    Require stack:
    - F:\share_folder\Develop_work\React\React_Project\21-12-03_Blitz\works\at-front\.blitz\recipe-install\node_modules\@blitzjs\installer\dist\blitzjs-installer.cjs.dev.js
    - F:\share_folder\Develop_work\React\React_Project\21-12-03_Blitz\works\at-front\.blitz\recipe-install\node_modules\@blitzjs\installer\dist\blitzjs-installer.cjs.js
    - F:\share_folder\Develop_work\React\React_Project\21-12-03_Blitz\works\at-front\.blitz\recipe-install\index.ts
    - F:\share_folder\Develop_work\React\React_Project\21-12-03_Blitz\works\at-front\node_modules\@blitzjs\cli\lib\src\commands\install.js
    - F:\share_folder\Develop_work\React\React_Project\21-12-03_Blitz\works\at-front\node_modules\@blitzjs\cli\node_modules\@oclif\command\node_modules\@oclif\config\lib\plugin.js
    - F:\share_folder\Develop_work\React\React_Project\21-12-03_Blitz\works\at-front\node_modules\@blitzjs\cli\node_modules\@oclif\command\node_modules\@oclif\config\lib\config.js
    - F:\share_folder\Develop_work\React\React_Project\21-12-03_Blitz\works\at-front\node_modules\@blitzjs\cli\node_modules\@oclif\command\node_modules\@oclif\config\lib\index.js
    - F:\share_folder\Develop_work\React\React_Project\21-12-03_Blitz\works\at-front\node_modules\@blitzjs\cli\node_modules\@oclif\command\lib\command.js
    - F:\share_folder\Develop_work\React\React_Project\\21-12-03_Blitz\works\at-front\node_modules\@blitzjs\cli\node_modules\@oclif\command\lib\index.js
    - F:\share_folder\Develop_work\React\React_Project\21-12-03_Blitz\works\at-front\node_modules\@blitzjs\cli\lib\src\index.js
    - C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\blitz\cli\dist\blitz-cli.cjs.dev.js
    - C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\blitz\cli\dist\blitz-cli.cjs.js
    Code: MODULE_NOT_FOUND

### Paste all relevant code snippets here:
import {
  AppProps,
  ErrorBoundary,
  ErrorComponent,
  AuthenticationError,
  AuthorizationError,
  ErrorFallbackProps,
  useQueryErrorResetBoundary,
  Router,
} from "blitz";
import "animate.css";
import "tailwindcss/tailwind.css";
import "app/core/styles/global.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { ThemeProvider } from "app/core/context/ThemeContext";

export default function App({ Component, pageProps }: AppProps) {
  const getLayout = Component.getLayout || ((page) => page);

  return (
    <ErrorBoundary
      FallbackComponent={RootErrorFallback}
      onReset={useQueryErrorResetBoundary().reset}
    >
      <ThemeProvider>{getLayout(<Component {...pageProps} />)}</ThemeProvider>
    </ErrorBoundary>
  );
}

### What are detailed steps to reproduce this?

1. npm modules are not installed and not working on blitz project with tailwindcss, ...

### Run `blitz -v` and paste the output here:

Windows 10 | win32-x64 | Node: v14.17.5

blitz: 0.44.0 (global)

  Package manager: npm
  System:
    OS: Windows 10 10.0.19043
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 5.67 GB / 15.88 GB
  Binaries:
    Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found

### Please include below any other applicable logs and screenshots that show your problem:

![2021-12-04 at 15-37-18](https://user-images.githubusercontent.com/61710721/144713447-16608de3-f3e1-4137-9623-854bfdb44591.png)

**Comment by beerose** [comment]
Could you try reinstalling Blitz? (or upgrade to the latest version?)

**Comment by beerose** [comment]
I suppose that this issue is related to: https://github.com/blitz-js/blitz/issues/2765. I'm going to close it as a duplicate.
