### ISSUE TITLE
Missing typescript for paginate function

### ISSUE THREAD

**Issue by IRediTOTO** [blitz-js/blitz#3038]
### What is the problem?

Hi, I just want report missing ts of `paginate` , that made `useQuery ` in client lost ts too
![image](https://user-images.githubusercontent.com/15695252/145013355-afacd174-eb40-499d-936a-77299525468b.png)
![image](https://user-images.githubusercontent.com/15695252/145013393-43d43186-f0bf-42da-b399-e88252b29200.png)
![image](https://user-images.githubusercontent.com/15695252/145013981-c1aa100a-9129-4b19-9389-e55466d12467.png)

### Paste all your error logs here:

You dont need this

### Paste all relevant code snippets here:

```
const {
      items: tags,
      hasMore,
      nextPage,
      count,
    } = await paginate({
      skip,
      take,
      count: () => db.tag.count({ where }),
      query: (paginateArgs) => db.tag.findMany({ ...paginateArgs, where, orderBy }),
    });

const [tagsQueryData, { isLoading: isLoadingTagsQuery }] = useQuery(
    getTags,
    { take: 250 },
    { staleTime: Infinity, suspense: false }
  );
```

### What are detailed steps to reproduce this?

1. This is default code when call useQuery on client

### Run `blitz -v` and paste the output here:

```
Windows 10 | win32-x64 | Node: v14.18.1

blitz: 0.44.3 (local)

  Package manager: yarn
  System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 4.76 GB / 15.92 GB
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.3 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: 3.6.0 => 3.6.0
    blitz: 0.44.3 => 0.44.3
    prisma: 3.6.0 => 3.6.0
    react: 18.0.0-alpha-5ca4b0433-20211020 => 18.0.0-alpha-5ca4b0433-20211020  
    react-dom: 18.0.0-alpha-5ca4b0433-20211020 => 18.0.0-alpha-5ca4b0433-20211020
    typescript: 4.5.2 => 4.5.2
```

**Comment by beerose** [comment]
Hi! So the generated types for `paginate` function include `Awaited` type. It was added in the new typescript `4.5`, and it looks like you have it, but most likely you have an older version in VS Code. The `any` issue will disappear once you set the `4.5.x` TS version in your editor. In VS Code you'll have to find `Select TypeScript version` in the command palette, and then pick the one from node_modules:

<img width="568" alt="Screenshot 2021-12-08 at 15 39 50" src="https://user-images.githubusercontent.com/9019397/145227478-3f98b6e6-b3d8-4fe1-9f77-0a1553fa7423.png">

<img width="809" alt="Screenshot 2021-12-08 at 15 39 57" src="https://user-images.githubusercontent.com/9019397/145227466-3e49c5b3-fa9a-43d1-8c84-a53d44bfc79b.png">

I'm closing this issue then. But feel free to reopen if that doesn't solve the problem.
