### ISSUE TITLE
Error while trying to push to Github repo

### ISSUE THREAD

**Issue by JithinKS97** [blitz-js/blitz#3039]
### What is the problem?

When I try to push to GitHub a clean install of Blitz, I get this error

### Paste all your error logs here:

```
/Users/userName/Desktop/projects/viteclout/node_modules/blitz/jest-preset/global-setup.js:2
import {loadEnvConfig} from "@blitzjs/env"
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

### Paste all relevant code snippets here:

N/A

### What are detailed steps to reproduce this?

1. Clean install blitz js with typescript setup
2. Try to push to Github repo

### Run `blitz -v` and paste the output here:

N/A

**Comment by beerose** [comment]
Fixed in https://github.com/blitz-js/blitz/pull/3027. Please upgrade to the latest Blitz version!
