### ISSUE TITLE
Make Auth middleware Blitz-agnostic

### ISSUE THREAD

**Issue by brillout** [blitz-js/blitz#3069]
### What do you want and why?

I want to use Blitz's auth middleware independently of Blitz.

### Additional context

I agree that the ecosystem has (un-)bundling phases, but I think it would benefit everyone if we collaborate more on foundational tools such as authentication.

Follow up of https://twitter.com/flybayer/status/1471130369177042944.

**Comment by flybayer** [comment]
@brillout do you like blitz auth better than next-auth? If so, why?

**Comment by brillout** [comment]
Both have their merits, but regardless of how both compare, the more agnostic middlewares we have the better for the ecosystem.

**Comment by flybayer** [comment]
Likely will happen. See https://github.com/blitz-js/blitz/discussions/3075
