### ISSUE TITLE
Cannot find type definition file for 'example' on git push

### ISSUE THREAD

**Issue by trchristensen** [blitz-js/blitz#3084]
### What is the problem?

Like the title says, I'm getting a type definition error every time I try to push my commit to github.  Seems like a dependency issue. I am surprised no one else is getting this error? This has happened several times (every time) to me on fresh blitz projects with no changes.

### Paste all your error logs here:

```
anon@Anon project % git push -u origin main
error TS2688: Cannot find type definition file for 'example'.
  The file is in the program because:
    Entry point for implicit type library 'example'

error TS2688: Cannot find type definition file for 'src'.
  The file is in the program because:
    Entry point for implicit type library 'src'


Found 2 errors.

husky - pre-push hook exited with code 2 (error)
error: failed to push some refs to 'https://github.com/trchristensen/project.git'
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1. blitz new project
2.  git init
3. git add .
4. git commit -m 'init commit'
5. git branch -M main
6. git remote add origin https://github.com/trchristensen/[project].git
7. git push -u origin main

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-arm64 | Node: v14.17.1

blitz: 0.44.4 (global)
blitz: 0.44.4 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 102.98 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.1 - /opt/homebrew/opt/node@14/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 6.14.13 - /opt/homebrew/opt/node@14/bin/npm
    Watchman: 2021.09.06.00 - /opt/homebrew/bin/watchman
  npmPackages:
    @prisma/client: 3.x => 3.6.0 
    blitz: 0.44.4 => 0.44.4 
    prisma: 3.6.0 => 3.6.0 
    react: 18.0.0-beta-149b420f6-20211119 => 18.0.0-beta-149b420f6-20211119 
    react-dom: 18.0.0-alpha-5ca4b0433-20211020 => 18.0.0-alpha-5ca4b0433-20211020 
    typescript: ~4.5 => 4.5.4 
```

**Comment by beerose** [comment]
Hi! 

That's weird. I tried that with a new app (yarn, full template) and worked fine. Have you made any changes? You can also try to delete node modules and install them again.

You can temporarily disable the `tsc` step in `.husky/prepush` script, so that you can push. Of course, that's not the solution but can help until the issue is resolved.

**Comment by trchristensen** [comment]
Hi, thanks for the reply. I've tried deleting the modules and reinstalling. This has happened on 3 separate installs so not sure what the issue is. I will disable tsc for now. Appreciate the help!
