### ISSUE TITLE
blitz prisma migrate dev - error

### ISSUE THREAD

**Issue by Ajeethkumar-r** [blitz-js/blitz#3086]
### What is the problem?

I create model in database - SQLlite and try to migrate it using the command 'blitz prisma migrate dev' and I got error below

### Paste all your error logs here:

```
PASTE_HERE (leave the ``` marks)
```
_Error: Unable to require(`C:\Users\ajeet\Documents\blitzApp\joy\node_modules\prisma\node_modules\@prisma\engines\query_engine-windows.dll.node`)

The specified module could not be found.

\\?\C:\Users\ajeet\Documents\blitzApp\joy\node_modules\prisma\node_modules\@prisma\engines\query_engine-windows.dll.node_

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
PASTE_HERE (leave the ``` marks)
```
![Screenshot (6)](https://user-images.githubusercontent.com/87157528/146756892-0fa25705-aded-457c-8314-42da693edee7.png)

**Comment by beerose** [comment]
Hi @Ajeethkumar-r! 

Here's a related issue: https://github.com/prisma/prisma/issues/9940 with a possible fix which is installing Microsoft Visual C++ 2015 Redistributable.

I'm going to close this issue, as it is related to Prisma and tracked in their repo.
