### ISSUE TITLE
[Meta] Ditch ZenHub for GH Projects

### ISSUE THREAD

**Issue by Skn0tt** [blitz-js/blitz#314]
### What do you want and why?

Having both ZenHub and GitHub Projects enabled is confusing. We should be focusing on usage of one of the tools and disable the other.

@flybayer advocated against ZenHub and Pro-Github Projects.

### Possible implementation(s)

Disable ZenHub, remove it from Contribution Documentation.
Start filing Issues and PRs in GH Projects.

**Comment by flybayer** [comment]
Duplicate: https://github.com/blitz-js/blitz/issues/228

:)

**Comment by Skn0tt** [comment]
Haha ... 😅
