### ISSUE TITLE
support `blitz prisma --help` in addition to existing `blitz prisma -h`

### ISSUE THREAD

**Issue by Vandivier** [blitz-js/blitz#3170]
### What do you want and why?

support `blitz prisma --help` in addition to existing `blitz prisma -h`

Why? just because `--help` is a common CLI flag that redirects to `-h` so this can save us a few keystrokes.

### Possible implementation(s)

literally just when --help is called, redirect the reference to -h or even call the other command explicitly as a subroutine

**Comment by beerose** [comment]
Hey, thanks for the suggestion! With the new toolkit, we'll probably improve the CLI but won't be working on it before that. I'm therefore closing this issue.
