### ISSUE TITLE
Migrate `ErrorBoundary` to `blitz-next`

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#3197]
- [x] https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/stdlib/error-boundary.tsx
- [x] https://github.com/blitz-js/blitz/blob/canary/nextjs/test/unit/error-boundary.unit.test.tsx
- [x] https://github.com/blitz-js/blitz/blob/canary/nextjs/test/unit/error-boundary-hook.unit.test.tsx

**Comment by beerose** [comment]
Closed in https://github.com/blitz-js/blitz/pull/3229
