### ISSUE TITLE
Migrate `useParam` and `useParams` to `blitz-next`

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#3206]
- [ ] [And it's tests](https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/client/router.ts#L204-L271)
- [ ] https://github.com/blitz-js/blitz/blob/canary/nextjs/test/unit/router-hooks.unit.test.ts#L36-L257

**Comment by piotrski** [comment]
Can I grab this task?

**Comment by beerose** [comment]
Sure! @piotrski

**Comment by markhughes** [comment]
Hey @piotrski how'd you go with this one? I'd be keen to take it on otherwise.

**Comment by markhughes** [comment]
@flybayer did you want this exported from blitz or blitz-next? We could change it to be more framework agnostic?

**Comment by beerose** [comment]
> @flybayer did you want this exported from blitz or blitz-next? We could change it to be more framework-agnostic?

It looks like it's not related to Next, so we can export it from `blitz` package instead

**Comment by piotrski** [comment]
So sorry guys, I've been pretty busy at work and didn't notice that @beerose had assigned me to this task. @markhughes if you want, you can grab it. The current implementation uses `useRouter` from `next.js`, so it's unlikely to be able to move that to core, but there are some url helpers that are also used by `blitz-auth`, so it might be a good idea to move them to core.

**Comment by beerose** [comment]
Ah yeah, @piotrski is right — `useParams/useParam` is strictly related to Next. Let's add it to `blitz/next` then.

**Comment by markhughes** [comment]
Although useParam and useParams are currently strictly related to next I think it could easily be ported to other frameworks? If the plan is to be a reusable toolkit it might be worthwhile :) but I suppose you could write it individually for each implementation too.

**Comment by flybayer** [comment]
@markhughes let's put it in next for now, we can abstract it later. Our current target is _something_ working for React Miami :D

**Comment by flybayer** [comment]
Hey @markhughes, we'd like to get this done this week. If you aren't able this week, that's fine, we can take it over.

**Comment by markhughes** [comment]
no worries @flybayer i'm fairly busy with work this week, so I wouldn't be able to until the weekend :)

**Comment by beerose** [comment]
Closed in #3269
