### ISSUE TITLE
Migrate `paginate` utility to `blitz`

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#3208]
- [ ] https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/stdlib-server/index.ts#L21-L84
- [ ] https://github.com/blitz-js/blitz/blob/canary/nextjs/test/unit/paginate.unit.test.ts

**Comment by beerose** [comment]
https://github.com/blitz-js/blitz/pull/3266
