### ISSUE TITLE
Migrate `zod-utils` to `blitz`

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#3209]
- [x] https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/stdlib/zod-utils.ts
- [x] https://github.com/blitz-js/blitz/blob/canary/nextjs/test/unit/zod-utils.unit.test.ts

**Comment by beerose** [comment]
https://github.com/blitz-js/blitz/pull/3233
