### ISSUE TITLE
Enable React Fast Refresh

### ISSUE THREAD

**Issue by merelinguist** [blitz-js/blitz#322]
### What do you want and why?

We should enable Fast Refresh for apps by default.

### Implementation

1. Add the fastRefresh flag inside the `withBlitz` config wrapper
```
  experimental: {
    reactRefresh: true
  }
```
2. Upgrade Next.js to latest canary (>= `9.3.7-canary.5`)

See here for an explanation: https://github.com/zeit/next.js/pull/12008

**Comment by Timer** [comment]
This feature is not ready to be enabled by default. Please do not enable it for all users until (at a minimum) https://github.com/zeit/next.js/pull/12222 has been landed.

**Comment by merelinguist** [comment]
@timer Oh, okay! I saw a tweet from Dan asking people to try it out so I assumed it was at least alpha-ready. Thanks so much for the heads up 👍

**Comment by Timer** [comment]
https://twitter.com/dan_abramov/status/1255233660317503490

**Comment by flybayer** [comment]
Thanks @timer!

Reopening this because we still want to do it at some point

**Comment by Timer** [comment]
Good to enable now if the underlying Next version is `^9.3.7-canary.5` or newer.

**Comment by flybayer** [comment]
Awesome, thank you @Timer!!

**Comment by simonpeterdebbarma** [comment]
Thank you very much, @dwightwatson !
