### ISSUE TITLE
Proposal to add SASS as a standard style

### ISSUE THREAD

**Issue by skorotkiewicz** [blitz-js/blitz#3242]
### What do you want and why?
Adding SASS as a standard style to Blitz.js

### Possible implementation(s)
> How might we do this?

`yarn add sass` ¯\\\_(ツ)\_/¯

PS. I really love blitz.js! Thank you @flybayer for creating such a great project!

**Comment by beerose** [comment]
Hmm, I think that the app template is meant to be as minimal as possible (hence no style libraries) so that people can add style libraries of their choice after creating a new project.

**Comment by MrLeebo** [comment]
@skorotkiewicz Can you describe what it is you want to achieve from sass that you can't already accomplish with postcss? Generally having node-sass as a dependency has been a pain-point in a dev's project set-up experience, not exactly made it smoother.
