### ISSUE TITLE
cli: add `blitz start` and `blitz build` etc

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#3248]
- [ ] `blitz next CMD` will be special cased, such that all nextjs commands like `blitz dev`, `blitz lint`, etc will run `blitz next dev`, etc.
- [ ] Set `process.env.__NEXT_PROCESSED_ENV = 'true` to skip nextjs env loading

**Comment by dillonraphael** [comment]
Idea:
Commands like `blitz dev` should check if user is using `next` or `remix`, then fetch cli commands from appropriate separate package. This will keep the cli agnostic and consistent with blitz toolkit vision.

**Comment by beerose** [comment]
https://github.com/blitz-js/blitz/pull/3272
