### ISSUE TITLE
Add windows testing support to CI

### ISSUE THREAD

**Issue by dillonraphael** [blitz-js/blitz#3271]
Currently when the tests run on windows os the following error happens:

```
Error: spawn cmd.exe ENOENT
 ⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
WebDriverError: chrome not reachable
```

**Comment by siddhsuresh** [comment]
Hey @dillonraphael @beerose, I saw this issue as one of the points to be completed for the stable release. Can I open a PR to add the windows testing to the workflow?

**Comment by beerose** [comment]
> Hey @dillonraphael @beerose, I saw this issue as one of the issues to be completed for the stable release. Can I open a PR to add the windows testing to the workflow?

That would be amazing!
