### ISSUE TITLE
Migrate `resolver` to `blitz` core

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#3279]
Migrate these files:
- [ ] https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/stdlib-server/resolver.ts
- [ ] https://github.com/blitz-js/blitz/blob/canary/nextjs/test/unit/resolver.unit.test.ts

to the new toolkit `main` branch

**Comment by beerose** [comment]
https://github.com/blitz-js/blitz/pull/3307
