### ISSUE TITLE
🔥Add RpcClientPlugin

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#3283]
Things to get working:

- [ ] Accepts reactQueryOptions which are passed to QueryClient initialization
- [ ] Initialize queryClient inside RpcClientPlugin() (currently code is in blitz-next)
- [ ] Default suspense: true
- [ ] Set globalThis.__BLITZ_SUSPENSE_ENABLED to the suspense config inside the plugin setup
 - [ ] Replace all instances of process.env.__BLITZ_SUSPENSE_ENABLED with globalThis.__BLITZ_SUSPENSE_ENABLED 

---

After this, all queries & mutations with auth should be working correctly

**Comment by beerose** [comment]
Closed in https://github.com/blitz-js/blitz/pull/3302
