### ISSUE TITLE
Migrate react-query integration tests to toolkit

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#3291]
- [ ] https://github.com/blitz-js/blitz/blob/canary/nextjs/test/unit/use-mutation.unit.test.tsx
- [ ] https://github.com/blitz-js/blitz/blob/canary/nextjs/test/unit/use-query.unit.test.tsx

**Comment by beerose** [comment]
Fixed in https://github.com/blitz-js/blitz/pull/3557
