### ISSUE TITLE
Migrate react-query unit test to blitz-rpc

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#3295]
- [ ] https://github.com/blitz-js/blitz/blob/canary/nextjs/test/unit/react-query-utils.unit.test.ts

**Comment by ganeshmani** [comment]
@beerose can I work on this issue?

**Comment by beerose** [comment]
Sure, @ganeshmani!

**Comment by beerose** [comment]
Hey @ganeshmani, how's it going with the tests migration?

**Comment by beerose** [comment]
https://github.com/blitz-js/blitz/pull/3340
