### ISSUE TITLE
Bug: husky hooks not being installed on `blitz new`

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#330]
### What is the problem?

Husky hooks aren't being installed for new apps because the git repo is being initialized after dependency install

### Steps to Reproduce: 

1. `blitz new myapp`
2. Change a file
3. Commit the the change
4. Notice the pre-commit hook doesn't run

### Versions:

Latest canary

### Possible fix

I think we need to run `git init` before dependencies are installed, but then run the initial `git commit` after they are installed (to have the lock file in the first commit)

**Comment by peaonunes** [comment]
I would be happy to collaborate on that 😄

**Comment by merelinguist** [comment]
@peaonunes Awesome! Have a look at our [contributing guide](https://github.com/blitz-js/blitz/blob/canary/CONTRIBUTING.md), and then feel free to create a pull request when you’re ready.
