### ISSUE TITLE
Resolve all suspense issues

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#3301]
Nextjs https://github.com/vercel/next.js/releases/tag/v12.1.2-canary.0 breaks how our react-query hooks render loading screens during static prerendering.

Before, throwing an infinite promise caused nextjs to render the loading screen on the server. But now, the server just hangs forever waiting for data to load.

This could be a bug in nextjs or at least unintentional. Need to sync up with their team to figure out what to do about this.

Check browser console for errors.

**Update 4/27:** we fixed the infinite loading by throwing an error on the server (https://github.com/blitz-js/blitz/pull/3332) but now we still get a flash of unstyled content

**Update 5/2:** next@canary fixed unstyled content issue, now current issue is the react error popup in development: 
![image](https://user-images.githubusercontent.com/8813276/166320687-115dc887-5787-4904-bb6c-36aba9ddd6e2.png)

**Comment by flybayer** [comment]
Next.js issue opened here: https://github.com/vercel/next.js/issues/36526

**Comment by dillonraphael** [comment]
Some resources collected from googling:

- https://github.com/tannerlinsley/react-query/discussions/2942
- https://github.com/tannerlinsley/react-query/discussions/3173
- https://codesandbox.io/s/nextjs-react-rc-9h7d3e?file=/pages/_app.js (codesandbox with react-query working with react 18 and nextjs 12.1.1)

**Comment by flybayer** [comment]
Relevant: https://github.com/vercel/next.js/issues/35564

**Comment by flybayer** [comment]
I've closed this issue: https://github.com/vercel/next.js/issues/36526

And opened two new ones:
- https://github.com/vercel/next.js/issues/36636 (this is the same problem we are currently seeing, so hopefully this will fix our issue too)
- https://github.com/vercel/next.js/issues/36634 (not directly affecting us, but something we noticed in our research)

**Comment by flybayer** [comment]
Update: I talked with @acdlite this week and they are adding an API to React within 2-3 weeks for forcing rendering of suspense fallback on the server. This will solve all our problems.

**Comment by flybayer** [comment]
### Our current workaround it that inside `withBlitz` we render nothing on the server.

This will cause SEO problems if you are depend on static content.

**Comment by flybayer** [comment]
PR opened on next.js: https://github.com/vercel/next.js/pull/38207

**Comment by StringKe** [comment]
How to work around this prompt temporarily?

**Comment by phuctm97** [comment]
> Update: I talked with @acdlite this week and they are adding an API to React within 2-3 weeks for forcing rendering of suspense fallback on the server. This will solve all our problems.

@flybayer Did React/Next.js team actually release the API to render suspense fallback on the server? I'm struggling to find solution for the same issue :/. Thank you 🙏!
