### ISSUE TITLE
Any blitz CMD will run the associated .bin file

### ISSUE THREAD

**Issue by dillonraphael** [blitz-js/blitz#3306]
Running any `blitz **cmd**` will run the associated `.bin` file from `node_modules/.bin/**cmd**` and will inject the env variables using the `loadEnvConfig` which is exported from `packages/blitz/src/env-utils.ts`, as well as passing all arguments.

(Note: Using the `arg` package you can traverse arguments that aren't flags, ie. `--flag` like so: `args._`)

**Comment by beerose** [comment]
https://github.com/blitz-js/blitz/pull/3310
