### ISSUE TITLE
Convert app examples to use Blitz Toolkit

### ISSUE THREAD

**Issue by beerose** [blitz-js/blitz#3319]
- [ ] auth (in progress, @ganeshmani)
- [ ] no-prisma
- [ ] plain-js
- [ ] static
- [ ] store

**Comment by ganeshmani** [comment]
@beerose I would like to work on this one.

**Comment by beerose** [comment]
Sure @ganeshmani! Can you tell us which example you'd like to convert? I think that since there are many of them then many people can work on this issue and cover as many or as little as they want.

**Comment by ganeshmani** [comment]
@beerose I would like to work `auth` .

**Comment by Himanxu1** [comment]
I would like to work on this but i need some guidance !
what to do ?

**Comment by mrcampbell** [comment]
Same!  I could work on `no-prisma`

**Comment by siddhsuresh** [comment]
Hey, @beerose can I work on this? I can convert the plain-js, static and the store examples to use Blitz Toolkit as the other two have been taken by others. Should I create a PR for each or should I do it in a single PR?
