### ISSUE TITLE
Blitz install errors due to missing postinstall script (v2.0.0-alpha.10)

### ISSUE THREAD

**Issue by stfnsr** [blitz-js/blitz#3324]
### What is the problem?

I generated a new blitz app with v2.0.0-alpha.10, and an error occurred during install.
According to the error message, the postinstall script at `node_modules/@blitzjs/next/src/scripts/postinstall.js` is missing.
From what i can tell, the entire scripts folder is currently left out of the published package because it is included neither in the [build config](https://github.com/blitz-js/blitz/blob/main/packages/blitz-next/build.config.ts) nor in the [files entry in package.json](https://github.com/blitz-js/blitz/blob/main/packages/blitz-next/package.json#L20).

### Paste all your error logs here:

```
[4/4] 🔨  Building fresh packages...
[9/11] ⢀ @blitzjs/next
[-/11] ⢀ waiting...
[7/11] ⢀ prisma
[8/11] ⢀ blitz
error /Users/stefan/dev/try/blitzapp/node_modules/@blitzjs/next: Command failed.
Exit code: 1
Command: node src/scripts/postinstall.js
Arguments: 
Directory: /Users/stefan/dev/try/blitzapp/node_modules/@blitzjs/next
Output:
node:internal/modules/cjs/loader:942
  throw err;
  ^

Error: Cannot find module '/Users/stefan/dev/try/blitzapp/node_modules/@blitzjs/next/src/scripts/postinstall.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
```

### Paste all relevant code snippets here:

```

```

### What are detailed steps to reproduce this?

1. Install Blitz CLI v2.0.0-alpha.10
2. Generate new project via `blitz new`

### Run `blitz -v` and paste the output here:

```
Blitz.js v2.0.0-alpha.10
```

**Comment by beerose** [comment]
Thanks for the report! This is something we're aware of and @dillonraphael is currently working on it!

**Comment by dillonraphael** [comment]
2.0.0-alpha.18 fixes this issue
