### ISSUE TITLE
When using the alpha tag in generator templates, it installs `2.0.0-alpha.1` instead of latest alpha version

### ISSUE THREAD

**Issue by dillonraphael** [blitz-js/blitz#3333]

**Comment by stfnsr** [comment]
Seems like 2.0.0-alpha.1 was the last version tagged as alpha, 2.0.0-alpha.18 is tagged as latest:
https://www.npmjs.com/package/@blitzjs/auth?activeTab=versions

**Comment by dillonraphael** [comment]
> Seems like 2.0.0-alpha.1 was the last version tagged as alpha, 2.0.0-alpha.18 is tagged as latest: https://www.npmjs.com/package/@blitzjs/auth?activeTab=versions
> 
> At least that's what it looks like for the packages in the `@blitzjs` namespace, `blitz` itself seems tagged correctly https://www.npmjs.com/package/blitz?activeTab=versions

good catch @stfnsr

**Comment by dillonraphael** [comment]
Fixed the generator to use the latest tag on `@blitzjs/rpc` & `@blitzjs/auth` because of the following message: `@blitzjs/rpc is being published to **latest** rather than **alpha** because there has not been a regular release of it yet`.
