### ISSUE TITLE
Fix `useQuery` rules of hooks violation

### ISSUE THREAD

**Issue by ryardley** [blitz-js/blitz#334]
### What do you want and why?

We unfortunately accidentally have had a rules of hooks violation:

https://github.com/blitz-js/blitz/blob/canary/packages/core/src/useQuery.ts#L49

__To avoid a breaking change:__

Investigate switching on hooks configuration to swap out noop objects so we don't have to run hooks in an if

### Possible implementation(s)

```ts
const paginatedData =  usePaginated(paginated, queryFunction , queryObject)
const nonPaginatedData =  useNonPaginated(paginated, queryFunction , queryObject)

return paginated ? paginatedData : nonPaginatedData
```

We may want to ensure that the manual option is set to `true` for whatever react-query hook is running with noop data.

**Comment by eliasjohansson** [comment]
Hmm, did we just implement hooks validation? Did not think of this. It's unfortunate react-query doesnt have a `skip` parameter like apollo useQuery..

**Comment by ryardley** [comment]
I found a `manual` property that might work for our needs but needs to be tested

**Comment by flybayer** [comment]
The other solution is simply not support the paginated value changing — throw an error if `paginated` ever changes

**Comment by Skn0tt** [comment]
I'm not that familiar with useQuery's characteristics, but wouldn't smth like this work?

```ts
useQuery([key, skip], ([key, skip]) => {
  if (skip) {
    return Promise.resolve(null);
  }
  return fetcher(key);
})
```

**Comment by eliasjohansson** [comment]
Yea something like that. Im off work tomorrow so can have a go at fixing it then. If  nobody else jumps on it while im sleeping 😅

**Comment by MrLeebo** [comment]
What's wrong with going forward with two separate `useQuery()` and `usePaginatedQuery()` hooks? A boolean parameter that toggles the behavior of a function might as well be two functions.

**Comment by eliasjohansson** [comment]
Hm, yeah im starting to feel like it makes more sense with seperate hooks as well. Especially when we will make `useInfiniteQuery` seperate. Also people who have used react-query before will be more familiar.

**Comment by flybayer** [comment]
As discussed in the other PR, we will change to have separate hooks for each, just like react-query

**Comment by flybayer** [comment]
Closing this because I opened #517 for separating the hooks.
