### ISSUE TITLE
Add cli shortcuts for every command

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#3347]
`blitz b` -> `blitz build`
`blitz p` -> `blitz prisma`
`blitz c` -> `blitz console`

etc

**Comment by damilolarandolph** [comment]
Hey @flybayer! I would like to handle this

**Comment by damilolarandolph** [comment]
@beerose  @flybayer I just realized that most of the commands already have aliases. Only the `new` command doesn't. I thinking `$blitz -h` should list all commands as well as their aliases to make this more obvious.

**Comment by beerose** [comment]
> I thinking `$blitz -h` should list all commands as well as their aliases to make this more obvious.

Yeah, we should have that. Let's make the `-h` info better then.

**Comment by datner** [comment]
took initiative and went ahead closing this, I hope it's ok :)

**Comment by beerose** [comment]
Closed in https://github.com/blitz-js/blitz/pull/3410
