### ISSUE TITLE
I would like an alternative for getServerSideProps and getStaticProps

### ISSUE THREAD

**Issue by nitedani** [blitz-js/blitz#3363]
### What do you want and why?
I would like an alternative for getServerSideProps and getStaticProps. They are too much boilerplate. The dehydration/hydration should be centralized.

Right now it looks like this:

```ts
export const getServerSideProps = async (context) => {
  const queryClient = new QueryClient()
  // IMPORTANT: the second argument to getQueryKey must exactly match the second argument to useQuery down below
  const queryKey = getQueryKey(getProject, {
    where: { id: context.params?.projectId },
  })
  await queryClient.prefetchQuery(queryKey, () =>
    invokeWithMiddleware(
      getProject,
      { where: { id: context.params?.projectId } },
      context
    )
  )

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}

function ProjectPage(props) {
  const [project] = useQuery(getProject, { where: { id: props.id } })
  return <div>{project.name}</div>
}

export default ProjectPage
```

It would become this:

```ts

function ProjectPage(props) {
  const [project] = useQuery(getProject, { where: { id: props.id } })
  return <div>{project.name}</div>
}

export default ProjectPage

```

Just for comparsion, in nuxt3 it looks like this:

```ts
<script setup>
const { data } = await useAsyncData('project', () => $fetch('/api/project'))
</script>

<template>
    <div>{data.name}</div>
</template>
```

I would like blitz to go in the same direction and create a function something like:

```ts
useAsyncData<T>(key:string, cb: () => T | Promise<T>): { data, loading, error, refetch, ... }
```

On the server side, the response to the browser would be sent when all of the useAsyncData callbacks resolved. The transfer of state from server to browser would be handled by the framework.

**Comment by beerose** [comment]
Hey @nitedani, this is the new setup for hydration with the Blitz Toolkit: https://canary.blitzjs.com/docs/query-usage#prefetching (we removed the boilerplate and you don't have to pass `dehydratedState` explicitly). How does this look to you?

**Comment by nitedani** [comment]
It's better, but I think it's still too repetitive. I would need to jump in the code back and forth the prefetchBlitzQuery and useQuery. Is there a way to completely omit getServerSideProps, but still archive the same behavior? Is a custom react hook, implementing what getServerSideProps does, possible? I could supply getProject to this hook, then on the server it would directly call the server code, and on the browser it would do the network request. It would also handle the transfer of state from server to browser.


```
import { gSSP } from "app/blitz-server"
import getProject from "app/projects/queries/getProject"

export const getServerSideProps = gSSP(async ({ ctx }) => {
  await context.prefetchBlitzQuery(getProject, {
    where: { id: context.params?.projectId },
  })
  return { props: {} }
})

function ProjectPage(props) {
  const [project] = useQuery(getProject, { where: { id: props.id } })
  return <div>{project.name}</div>
}

export default ProjectPage
```
Could be:
```
function ProjectPage() {
  const [project] = someHook(getProject, { where: { id: props.id } })
  return <div>{project.name}</div>
}
```

**Comment by beerose** [comment]
No, you'd still need getServerSideProps/getStaticProps, but we removed the prefetching boilerplate required:
```ts
import { gSSP } from "app/blitz-server"
import getProject from "app/projects/queries/getProject"

export const getServerSideProps = gSSP(async ({ ctx }) => {
  await ctx.prefetchBlitzQuery(getProject, {
    where: { id: context.params?.projectId },
  })

  return { props: {} }
})

function ProjectPage(props) {
  const [project] = useQuery(getProject, { where: { id: props.id } })
  return <div>{project.name}</div>
}

export default ProjectPage
```
