### ISSUE TITLE
Module '"blitz"' has no exported member 'validateZodSchema'

### ISSUE THREAD

**Issue by Vahor** [blitz-js/blitz#3364]
### What is the problem?

Using the latest blitz toolkit, it seems that the 'blitz' module does not export everything ?

I've already tried to uninstall blitz (`npm uninstall -g blitz` and `yarn global remove blitz
` ) and even tried to remove the blitz folder (found in `which blitz`).

### Paste all your error logs here:

```
Failed to compile.

./app/core/components/Form.tsx:4:10
Type error: Module '"blitz"' has no exported member 'validateZodSchema'.

  2 | import { Form as FinalForm, FormProps as FinalFormProps } from "react-final-form"
  3 | import { z } from "zod"
> 4 | import { validateZodSchema } from "blitz"
    |          ^
  5 | export { FORM_ERROR } from "final-form"
  6 |
  7 | export interface FormProps<S extends z.ZodType<any, any>>
info  - Checking validity of types .

error - ESLint: Failed to load config "eslint-config-next" to extend from. Referenced from: /Users/nathan/Projets/blitz/app/.eslintrc.js


```

In a github actions log on another project (this one is using yarn workspaces/turborepo)
```
admin:build: ../../packages/db/index.ts
admin:build: Attempted import error: 'enhancePrisma' is not exported from 'blitz' (imported as 'enhancePrisma').
..
admin:build: ../../node_modules/@blitzjs/next/node_modules/debug/src/node.js
admin:build: Module not found: ESM packages (supports-color) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals
```

### Paste all relevant code snippets here:

N/A

### What are detailed steps to reproduce this?

1. `blitz new app` (first choice to everything)
2. cd app
3. blitz build

### Run `blitz -v` and paste the output here:

```
Blitz.js v2.0.0-alpha.24
```

**Comment by beerose** [comment]
Thanks!

**Comment by beerose** [comment]
Closed in https://github.com/blitz-js/blitz/pull/3368
