### ISSUE TITLE
Figure out how to run CI action on PR that is created with changesets GitHub action

### ISSUE THREAD

**Issue by dillonraphael** [blitz-js/blitz#3379]
Currently, changesets automatically creates a PR when a changeset file is found.

We must merge this PR into main so we can release a new version. The issue is the CI won't run on the PR that is created by the changeset action. This is a known issue with Github Actions.

There are workarounds: https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs

**Comment by flybayer** [comment]
Will merge PR without worrying about CI because this PR has no code changes
