### ISSUE TITLE
Controller should return 404 if the requested resource doesn't exist

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#34]
For example, you have a PostController with a `show` action. You request the `/posts/100` route but a post with id 100 doesn't exist in the DB. The Blitz controller should detect this and return a 404.

- [ ] Show action should return 404 if resource doesn't exist
- [ ] Update action should return 404 if resource doesn't exist
- [ ] Delete action should **not** return 404 if resource doesn't exist, because the intended result is a success
- [ ] Add tests for the above — the tests must actually use prisma because prisma may or may not throw errors on above actions, and prisma may change (still pre-release). You can use the prisma sqlite adapter for this.

Currently, Prisma returns null for `db.findOne` instead of throwing an error. So we may need to wrap db to get the functionality we want. I've contacted the Prisma team to ask about this, so this is issue is on hold for now.

**Comment by flybayer** [comment]
Related prisma issues:

- https://github.com/prisma/prisma2/issues/1762
- https://github.com/prisma/prisma-client-js/issues/544

**Comment by cr101** [comment]
Also consider that URLs opening with both slash & without slash create duplicate content issue in Google - https://support.google.com/webmasters/thread/6407607?hl=en

`/posts/100` and `/posts/100/` are treated as two separate pages by the Google bot

**Comment by cr101** [comment]
Next.js 9.3 handles 404s for non-existent routes - https://nextjs.org/blog/next-9-3#automatic-static-optimization-for-404
