### ISSUE TITLE
Can't resolve 'child_process'  - while going through User guide on win10

### ISSUE THREAD

**Issue by bushbass** [blitz-js/blitz#343]
### What is the problem?
Following the user guide on my windows 10 and when I get to the step where you go to /projects I get an error

### Steps to Reproduce: 

I took notes on my attempts: https://github.com/bushbass/myFirstBlitzApp/blob/master/notes.md

### Versions:

```
[Add the output of `blitz --version --verbose` here]
$ blitz --version --verbose
You are using alpha software - if you have any problems, please open an issue here:
  https://github.com/blitz-js/blitz/issues/new/choose

debug: global
debug: pkgPath: C:\Users\Laptop\AppData\Roaming\npm\node_modules\blitz\node_modules\@blitzjs\cli\lib\src\index.js

Windows 10 | win32-x64 | Node: v12.16.2

blitz: 0.7.0 (global)


```

### Supporting Documentation

Please include applicable logs and screenshots that show your problem.
See the link to my notes as above

**Comment by eliasjohansson** [comment]
Thanks for the issue! Super helpful with the detailed notes. :)

**Comment by wKovacs64** [comment]
Thank you, @bushbass - excellent detail! Sorry for the troubles.

From glancing at your notes, you ran into a lot of issues I haven't seen yet but the first error you got looks like #299. We need to nip this one in the bud. 😅

**Comment by reiwa** [comment]
The same error:

```
$ node -v
v12.11.1
```

```
$ npx blitz --version --verbose
You are using alpha software - if you have any problems, please open an issue here:
  https://github.com/blitz-js/blitz/issues/new/choose

debug: local
debug: pkgPath: /Users/reiwa/GitHub/tu-blitz/node_modules/@blitzjs/cli 

macOS Catalina | darwin-x64 | Node: v12.11.1

blitz: 0.7.0 (global)
blitz: 0.7.0 (local)
```

**Comment by bushbass** [comment]
I'm admittedly a newbie so I don't know if this makes any difference, but I noticed in console it said: 
```
C:/Users/Laptop/development/myFirstBlitzApp4/node_modules/@prisma/client/runtime/index.js
Module not found: Can't resolve 'child_process' in 'C:\Users\Laptop\development\myFirstBlitzApp4\node_modules\@prisma\client\runtime'

```
does it matter that it's using backslash and forward slash?  Sorry if this is a total newb question.

**Comment by reiwa** [comment]
I tried import and call `db` function in `app/pages/index.tsx` : https://github.com/reiwa/blitz-issue-299

**Comment by flybayer** [comment]
Yeah, like @reiwa said, @bushbass are you by chance using `db` inside a component?

I opened an issue for making this error actually helpful: https://github.com/blitz-js/blitz/issues/385

**Comment by flybayer** [comment]
**To clarify:** you will get the `child_process` error if you try to use `db` from a react component. The solution is to only use `db` inside queries/mutations, and then use queries/mutations in your components.

We have issue #385 for improving the UX of this, so closing this issue.

If you still have questions about this, comment in #385! Then everything is consolidated there.

**Comment by flybayer** [comment]
If you are still having the `child_process` bug and aren't importing the db into a component, then please install the new blitz version `0.8.2` and see if that fixes it!

**Comment by nyn0x** [comment]
Same for me when I try [user guide](https://github.com/blitz-js/blitz/blob/canary/USER_GUIDE.md)
After run `blitz generate all project` et navigate to localhost:3000/projects, I've got this issue:
`Can't resolve 'child_process'`


`Windows 10 | win32-x64 | Node: v12.16.3

blitz: 0.9.0 (global)
blitz: 0.9.0 (local)`

**Comment by flybayer** [comment]
This should be fixed in the next release! 👉 https://github.com/blitz-js/blitz/pull/451
