### ISSUE TITLE
[server] Blitz server tests are failing on Windows

### ISSUE THREAD

**Issue by wKovacs64** [blitz-js/blitz#345]
### What is the problem?

Blitz tests are failing on Windows after merging #323.

### Steps to Reproduce: 

1. Clone repo
1. `yarn`
1. `yarn test`

### Versions:

Windows 10

### Supporting Documentation

<details>
<pre>
@blitzjs/server: FAIL test/api-routes.test.ts
@blitzjs/server:   ● Dev command › should copy the correct files to the dev folder
@blitzjs/server:     expect(received).toEqual(expected) // deep equality
@blitzjs/server:     - Expected
@blitzjs/server:     + Received
@blitzjs/server:       Object {
@blitzjs/server:     -   "children": Array [
@blitzjs/server:     -     Object {
@blitzjs/server:     -       "name": "blitz.config.js",
@blitzjs/server:     -     },
@blitzjs/server:     -     Object {
@blitzjs/server:     -       "name": "next.config.js",
@blitzjs/server:     -     },
@blitzjs/server:     -     Object {
@blitzjs/server:     -       "children": Array [
@blitzjs/server:     -         Object {
@blitzjs/server:     -           "children": Array [
@blitzjs/server:     -             Object {
@blitzjs/server:     -               "name": "bar.ts",
@blitzjs/server:     -             },
@blitzjs/server:     -             Object {
@blitzjs/server:     -               "name": "foo.ts",
@blitzjs/server:     -             },
@blitzjs/server:     -           ],
@blitzjs/server:     -           "name": "api",
@blitzjs/server:     -         },
@blitzjs/server:     -       ],
@blitzjs/server:     -       "name": "pages",
@blitzjs/server:     -     },
@blitzjs/server:     -   ],
@blitzjs/server:         "name": ".blitz-rules",
@blitzjs/server:       }
@blitzjs/server:       55 |   it('should copy the correct files to the dev folder', async () => {
@blitzjs/server:       56 |     const tree = directoryTree(devFolder)
@blitzjs/server:     > 57 |     expect(tree).toEqual({
@blitzjs/server:          |                  ^
@blitzjs/server:       58 |       name: '.blitz-rules',
@blitzjs/server:       59 |       children: [
@blitzjs/server:       60 |         {name: 'blitz.config.js'},
@blitzjs/server:       at test/api-routes.test.ts:57:18
@blitzjs/server:       at step (../../node_modules/tslib/tslib.js:139:27)
@blitzjs/server:       at Object.next (../../node_modules/tslib/tslib.js:120:57)
@blitzjs/server:       at ../../node_modules/tslib/tslib.js:113:75
@blitzjs/server:       at Object.__awaiter (../../node_modules/tslib/tslib.js:109:16)
@blitzjs/server:       at Object.<anonymous> (test/api-routes.test.ts:55:57)
@blitzjs/server: √ Prepped for launch
@blitzjs/server: √ Prepped for launch
@blitzjs/server: PASS test/build.test.ts
@blitzjs/server: - Preparing for launch
@blitzjs/server: FAIL test/zeit-now.test.ts
@blitzjs/server:   ● Build command ZEIT › should copy the correct files to the build folder
@blitzjs/server:     expect(received).toEqual(expected) // deep equality
@blitzjs/server:     - Expected
@blitzjs/server:     + Received
@blitzjs/server:       Object {
@blitzjs/server:         "children": Array [
@blitzjs/server:           Object {
@blitzjs/server:             "name": "blitz.config.js",
@blitzjs/server:           },
@blitzjs/server:     -     Object {
@blitzjs/server:     -       "name": "next-zeit.config.js",
@blitzjs/server:     -     },
@blitzjs/server:     -     Object {
@blitzjs/server:     -       "name": "next.config.js",
@blitzjs/server:     -     },
@blitzjs/server:     -     Object {
@blitzjs/server:     -       "children": Array [
@blitzjs/server:     -         Object {
@blitzjs/server:     -           "name": "bar.tsx",
@blitzjs/server:     -         },
@blitzjs/server:     -         Object {
@blitzjs/server:     -           "name": "foo.tsx",
@blitzjs/server:     -         },
@blitzjs/server:     -       ],
@blitzjs/server:     -       "name": "pages",
@blitzjs/server:     -     },
@blitzjs/server:         ],
@blitzjs/server:         "name": ".blitz-build",
@blitzjs/server:       }
@blitzjs/server:       52 |   it('should copy the correct files to the build folder', async () => {
@blitzjs/server:       53 |     const tree = directoryTree(buildFolder)
@blitzjs/server:     > 54 |     expect(tree).toEqual({
@blitzjs/server:          |                  ^
@blitzjs/server:       55 |       name: '.blitz-build',
@blitzjs/server:       56 |       children: [
@blitzjs/server:       57 |         {name: 'blitz.config.js'},
@blitzjs/server:       at test/zeit-now.test.ts:54:18
@blitzjs/server:       at step (../../node_modules/tslib/tslib.js:139:27)
@blitzjs/server:       at Object.next (../../node_modules/tslib/tslib.js:120:57)
@blitzjs/server:       at ../../node_modules/tslib/tslib.js:113:75
@blitzjs/server:       at Object.__awaiter (../../node_modules/tslib/tslib.js:109:16)
@blitzjs/server:       at Object.<anonymous> (test/zeit-now.test.ts:52:59)
@blitzjs/server: FAIL test/rules.test.ts
@blitzjs/server:   ● Dev command › should copy the correct files to the dev folder
@blitzjs/server:     expect(received).toEqual(expected) // deep equality
@blitzjs/server:     - Expected
@blitzjs/server:     + Received
@blitzjs/server:       Object {
@blitzjs/server:     -   "children": Array [
@blitzjs/server:     -     Object {
@blitzjs/server:     -       "name": "blitz.config.js",
@blitzjs/server:     -     },
@blitzjs/server:     -     Object {
@blitzjs/server:     -       "name": "next.config.js",
@blitzjs/server:     -     },
@blitzjs/server:     -     Object {
@blitzjs/server:     -       "children": Array [
@blitzjs/server:     -         Object {
@blitzjs/server:     -           "name": "bar.tsx",
@blitzjs/server:     -         },
@blitzjs/server:     -         Object {
@blitzjs/server:     -           "name": "foo.tsx",
@blitzjs/server:     -         },
@blitzjs/server:     -       ],
@blitzjs/server:     -       "name": "pages",
@blitzjs/server:     -     },
@blitzjs/server:     -   ],
@blitzjs/server:         "name": ".blitz-rules",
@blitzjs/server:       }
@blitzjs/server:       49 |   it('should copy the correct files to the dev folder', async () => {
@blitzjs/server:       50 |     const tree = directoryTree(devFolder)
@blitzjs/server:     > 51 |     expect(tree).toEqual({
@blitzjs/server:          |                  ^
@blitzjs/server:       52 |       name: '.blitz-rules',
@blitzjs/server:       53 |       children: [
@blitzjs/server:       54 |         {name: 'blitz.config.js'},
@blitzjs/server:       at test/rules.test.ts:51:18
@blitzjs/server:       at step (../../node_modules/tslib/tslib.js:139:27)
@blitzjs/server:       at Object.next (../../node_modules/tslib/tslib.js:120:57)
@blitzjs/server:       at ../../node_modules/tslib/tslib.js:113:75
@blitzjs/server:       at Object.__awaiter (../../node_modules/tslib/tslib.js:109:16)
@blitzjs/server:       at Object.<anonymous> (test/rules.test.ts:49:57)
@blitzjs/server: √ Prepped for launch
@blitzjs/server: √ Prepped for launch
@blitzjs/server: FAIL test/dev.test.ts
@blitzjs/server:   ● Dev command › when run normally › calls spawn with the patched next cli bin
@blitzjs/server:     expect(received).toBe(expected) // Object.is equality
@blitzjs/server:     Expected: "\\dev\\.blitz-dev"
@blitzjs/server:     Received: "C:\\dev\\.blitz-dev"
@blitzjs/server:       146 |       const blitzDev = join(rootFolder, '.blitz-dev')
@blitzjs/server:       147 |       expect(nextUtilsMock.nextStartDev.mock.calls[0][0]).toBe(nextPatched)
@blitzjs/server:     > 148 |       expect(nextUtilsMock.nextStartDev.mock.calls[0][1]).toBe(blitzDev)
@blitzjs/server:           |                                                           ^
@blitzjs/server:       149 |     })
@blitzjs/server:       150 |   })
@blitzjs/server:       151 | })
@blitzjs/server:       at test/dev.test.ts:148:59
@blitzjs/server:       at step (../../node_modules/tslib/tslib.js:139:27)
@blitzjs/server:       at Object.next (../../node_modules/tslib/tslib.js:120:57)
@blitzjs/server:       at fulfilled (../../node_modules/tslib/tslib.js:110:62)
@blitzjs/server: Test Suites: 4 failed, 6 passed, 10 total
@blitzjs/server: Tests:       4 failed, 1 skipped, 19 passed, 24 total
</pre>
</details>

cc @dajinchu

**Comment by dajinchu** [comment]
investigating...
