### ISSUE TITLE
2.0 stable launch

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#3475]
- Product hunt
- hacker news
- office hours/livestream/q&a with special guests?
- inspiration from Redwood's 1.0 launch?
- email newsletter

**Comment by beerose** [comment]
Hey @Israel-Laguan. We do have an alpha version currently and people are testing it and upgrading from the legacy framework to the toolkit. We first released alpha at the end of April and recently made more public announcements. Before stable, we will also have a beta release. Is that what you meant or am I missing something?

**Comment by Israel-Laguan** [comment]
Can you kindly point me to the description about using it? Sorry if I miss it. I would live to test in a toy project I am about to start.

**Comment by beerose** [comment]
Sure, here you go: https://alpha.blitzjs.com/

**Comment by Israel-Laguan** [comment]
Thanks, checking right now!

**Comment by datner** [comment]
I'm so excited for this, are there any updates on this? I can barely wait ahahahah
