### ISSUE TITLE
Blitz Alpha Error "no query or mutation resolvers found" on Windows

### ISSUE THREAD

**Issue by christianstrang** [blitz-js/blitz#3478]
### What is the problem?

Installing Blitz alpha on windows works fine, but as soon as I run blitz dev and try to access localhost:3000, the page shows up shortly, then turns to 500 - internal server error.
The console error message is "Error: no query or mutation resolvers found".
On Linux the same setup runs without an error.

### Paste all your error logs here:

```
λ blitz dev
Loaded env from C:\DEV\Projects\blitz-alpha\myAppName\.env.local
Loaded env from C:\DEV\Projects\blitz-alpha\myAppName\.env
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
wait  - compiling...
event - compiled client and server successfully in 1337 ms (209 modules)
wait  - compiling / (client and server)...
wait  - compiling...
event - compiled client and server successfully in 286 ms (260 modules)
wait  - compiling /api/rpc/[[...blitz]]...
wait  - compiling...
event - compiled client and server successfully in 263 ms (275 modules)
[blitzSessionMiddleware] Starting handler...
Starting sessionMiddleware...
error - Error: No query or mutation resolvers found
wait  - compiling /_error (client and server)...
wait  - compiling...
event - compiled client and server successfully in 87 ms (276 modules)
```

### Paste all relevant code snippets here:

```
blitz new myAppName
cd myAppName
blitz dev
http://localhost:3000
```

### What are detailed steps to reproduce this?

1. execute run blitz new myAppName on Windows
2. pick Typescript, full, npm, React Final Form
3. cd myAppName
4. blitz dev
5. access http://localhost:300

### Run `blitz -v` and paste the output here:

```
λ blitz -v
Loaded env from C:\DEV\Projects\blitz-alpha\myAppName\.env.local
Loaded env from C:\DEV\Projects\blitz-alpha\myAppName\.env
Blitz version: 2.0.0-alpha.45 (global)
Blitz version: 2.0.0-alpha.46 (local)
Windows 10 | win32-x64 | Node: v16.15.1


 Package manager: npm

  System:
    OS: Windows 10 10.0.19044
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 21.10 GB / 31.91 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @prisma/client: 3.9.0 => 3.9.0
    blitz: 2.0.0-alpha.46 => 2.0.0-alpha.46
    next: 12.1.6 => 12.1.6
    prisma: 3.9.0 => 3.9.0
    react: 18.0.0 => 18.0.0
    react-dom: 18.0.0 => 18.0.0
    typescript: ^4.5.3 => 4.7.4
```

**Comment by Vandivier** [comment]
plz take a look in closed issue above for some useful details related to this issue

**Comment by Vandivier** [comment]
using `Blitz version: 2.0.0-alpha.56 (global)` I can't even `blitz new foobar` (nor can I `npx blitz@2.0.0-alpha.56 new foobar`) I immediately get sent to 
```
Error: Cannot find module 'blitz'
Require stack:
- D:\workspace\noop.js
```

**Comment by christianstrang** [comment]
> using `Blitz version: 2.0.0-alpha.56 (global)` I can't even `blitz new foobar` (nor can I `npx blitz@2.0.0-alpha.56 new foobar`) I immediately get sent to
> 
> ```
> Error: Cannot find module 'blitz'
> Require stack:
> - D:\workspace\noop.js
> ```

same

**Comment by beerose** [comment]
The issue with queries and mutations on Windows was addressed here: https://github.com/blitz-js/blitz/pull/3581, while the issue with CLI is being tracked here: https://github.com/blitz-js/blitz/issues/3566. Current workaround is to run `blitz new <project name> --skip-upgrade`
