### ISSUE TITLE
Remove purgecss from tailwind example

### ISSUE THREAD

**Issue by merelinguist** [blitz-js/blitz#348]
### What do you want and why?

Tailwind now supports purgecss by default! We should use this rather than including it in the example’s `postcss.config.js`

### Possible implementation(s)

1. Upgrade tailwind to the latest version

2. Uninstall `postcss`

3. Remove `postcss` related code from `examples/tailwind/postcss.config.js`

4. Edit the `tailwind.config.js` as described here https://github.com/tailwindcss/tailwindcss/releases/tag/v1.4.0

**Comment by Jfelix61** [comment]
Would love to work on this!
