### ISSUE TITLE
Toolkit: Rewriting API route, breaks RPC?

### ISSUE THREAD

**Issue by paulm17** [blitz-js/blitz#3489]
### What is the problem?

With legacy, I was able to update the api endpoint.

```
{
    source: "/api/:path*",
    destination: "http://localhost:3100/api/:path*",
},
```

### Paste all your error logs here:

```
error - Error: connect ECONNREFUSED ::1:3100
```

### Paste all relevant code snippets here:

```
const nextConfig = {
  async rewrites() {
    return [
      ...
      {
        source: "/api/:path*",
        destination: "http://localhost:3100/api/:path*",
      },
    ]
  },
  webpack(config) {
    config.module.rules.push({
      test: /\.svg$/,
      use: ["@svgr/webpack"],
    })

    return config
  },
}
```

### What are detailed steps to reproduce this?

Change next.config.js and restart

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-alpha.40 (global)
Blitz version: 2.0.0-alpha.47 (local)
macOS Monterey | darwin-arm64 | Node: v18.4.0


 Package manager: npm

  System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 4.64 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.4.0/bin/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v18.4.0/bin/npm
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    next: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```

### Please include below any other applicable logs and screenshots that show your problem:

![rpc error](https://i.imgur.com/aereegV.png)

**Comment by Zeko369** [comment]
If my other blitz app is hosted on 3100, still works just fine

**Comment by Zeko369** [comment]
Then I get the error, but that's ok, since the backend is off?

**Comment by paulm17** [comment]
Sure, but is Prisma still working for you?

**Comment by paulm17** [comment]
Hopefully this provides more context:

Used to wok:
Blitz legacy:  https://www.loom.com/share/a4355e385d7d4b66b69ddfab3273f5e6

Doesn't work:
Blitz Toolkit: https://www.loom.com/share/a1b37cfbe0914032b775f6ebf322eb18

**Comment by Zeko369** [comment]
@paulm17 Wait so you have 2 apps, and you want to connect them? (i.e. one 3000 and another 3001?) or do you have one app and want to rewrite the rest of the API to some other app? or ?

If you have some time let's hop on a discord call since i'm not sure I still fully understand what you think?
