### ISSUE TITLE
getQueryData function

### ISSUE THREAD

**Issue by edrickleong** [blitz-js/blitz#3490]
### What do you want and why?

I want an exported `getQueryData` function that takes in a resolver. 

Instead of having to get the query key manually, such as below
```ts
const queryKey = getQueryKey(getTasks, { taskListId })
const tasks = queryClient.getQueryData<PromiseReturnType<typeof getTasks>>(queryKey)
```

I want to be able to write
```ts
const tasks = getQueryData(getTasks, { taskListId }))
```

### Possible implementation(s)

Add a function `getQueryData` similar to the `setQueryData` function defined in `react-query-utils` as below. https://github.com/blitz-js/blitz/blob/e1fc695d24f6dd85eba8ffce9f88e357edfb562d/nextjs/packages/next/data-client/react-query-utils.ts#L166

### Additional context

The main use case I have for this is to do optimistic updates. See [example](https://react-query.tanstack.com/guides/optimistic-updates#updating-a-list-of-todos-when-adding-a-new-todo) from react query docs.

**Comment by pivotrooky** [comment]
Hi!
I would like to work this issue since it is marked as a good first issue.
Would that be ok?

**Comment by abuuzayr** [comment]
absolutely @pivotrooky ! give us a shout if you need any help

**Comment by Himanxu1** [comment]
Hey , I want to work on this issue ..
Assign this to me .
@abuuzayr

**Comment by pivotrooky** [comment]
Oh, ok. @Himanxu1 I'd only just started, so fine by me :D @abuuzayr 

> Hey , I want to work on this issue .. Assign this to me . @abuuzayr

**Comment by Himanxu1** [comment]
OK @pivotrooky .I am also a beginner

**Comment by beerose** [comment]
Hey @Himanxu1, I think @pivotrooky meant that he was already assigned to this issue :) In general, it's helpful to look at the discussion and see if someone was already assigned or created a PR or mentioned that they are going to work on an issue. This way, we can avoid working on the same things and any future confusion. I hope you can decide between you two who's going to work on this one :)

**Comment by pivotrooky** [comment]
@beerose I'd like to free up this issue, there'll be plenty of issues to work on in the future.
Could you please unassign me? 
I'm not sure if the option to do it myself is available as I'm not yet a collaborator but, if it is, I can't find seem to find the button. 
Thank you very much!

**Comment by edrickleong** [comment]
I have talked to @Himanxu1 about picking up this ticket on discord and he's ok with passing this to me. Could this be assigned to me instead?

**Comment by beerose** [comment]
> I have talked to @Himanxu1 about picking up this ticket on discord and he's ok with passing this to me. Could this be assigned to me instead?

Sure!
