### ISSUE TITLE
Ugly error on [id] when trying to view item that doesn't exist in the DB

### ISSUE THREAD

**Issue by osirvent** [blitz-js/blitz#350]
### What is the problem?
TypeError: project is null

### Steps to Reproduce: 

Try to access to an item that doesn't exist through route `http://localhost:3000/projects/3`

### Versions:

```
debug: local
debug: pkgPath: /Users/osirvent/dev/blitz/test/test2/node_modules/@blitzjs/cli

macOS Catalina | darwin-x64 | Node: v12.16.2

blitz: 0.7.0 (global)
blitz: 0.7.0 (local)
```

### Supporting Documentation

<img width="360" alt="imagen" src="https://user-images.githubusercontent.com/5927133/80650299-0a305300-8a74-11ea-9ad2-d3118b5426aa.png">

**Comment by MrLeebo** [comment]
This is a good observation. It would be easy to add a null check to the page template, but I don't think that every page in the app should have to check for null. Seems to me like the query should just throw a ModelNotFound error on a missing ID lookup and `blitz new` should generate a generic NotFound page component to route those errors.

**Comment by flybayer** [comment]
Yes @MrLeebo I think you are right that throwing an error and having an auto 404 component would be best for this.

**Comment by flybayer** [comment]
The query generator now has the following:

```
  if (!__modelName__) throw new NotFoundError()
```

So this issue is fixed!
