### ISSUE TITLE
Workout better file system mocking for tests

### ISSUE THREAD

**Issue by ryardley** [blitz-js/blitz#352]
### What do you want and why?

We now have mock-fs handling our in memory tests but there are issues with it in the broader sense. 

https://github.com/blitz-js/blitz/pull/347#pullrequestreview-403152892

* Needs to work on windows
* Act as a fs overlay
* Can be reset per test

### Possible implementation(s)

unionfs/memfs

**Comment by Skn0tt** [comment]
Also, mock-fs doesn't work with oclif.

**Comment by ryardley** [comment]
@Skn0tt fair point if we want something that will be universal.
