### ISSUE TITLE
Toolkit: Include queries/mutations in other workspaces when using TurboRepo

### ISSUE THREAD

**Issue by paulm17** [blitz-js/blitz#3522]
### What is the problem?

Using the legacy version of toolkit, this problem didn't exist.  Unfortunately for the toolkit.  I have this issue...

I have the following workspaces:

```
- apps
  - saas
  - fe
- modules
- packages
 - ui
```

I have multiple queries/mutations combinations inside modules and packages/ui.  Which are outside of the standard blitz installations.  Saas and Fe in this instance.

Unfortunately when blitz is running, any queries which is outside of a blitz installation does not execute.

### Paste all your error logs here:

```
[blitzSessionMiddleware] Starting handler...
Starting sessionMiddleware...
wait  - compiling /_error (client and server)...
error - Error: No resolver for path: /getPexelsData
    at handleRpcRequest (/Users/paul/development/src/[project]/node_modules/@blitzjs/rpc/dist/index-server.cjs:122:13) {
  page: '/api/rpc/[[...blitz]]'
```

In order to side step this bug, I'm having to create a symlink to the /pages/api/rpc folder, such as:

> ln -s ../../../../../packages/ui/components/picker/imagePicker/overlay/api/pexels/queries/getPexelsData.ts .

But this will be annoying to do for each queries/mutations combo 😢 

### What are detailed steps to reproduce this?

- Create a turborepo directory, have 2 workspaces.  
- First workspace "apps" have a directory which includes a blitz installation.
- Second workspace "packages" have a directory which includes a queries/mutations combination and an index.tsx which executes queries.

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-alpha.40 (global)
Blitz version: 2.0.0-alpha.50 (local)
macOS Monterey | darwin-arm64 | Node: v18.4.0


 Package manager: npm

  System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 426.09 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.4.0/bin/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v18.4.0/bin/npm
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    next: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```

### Please include below any other applicable logs and screenshots that show your problem:

![alt text](https://i.imgur.com/XYRKPYo.png)

**Comment by paulm17** [comment]
I broke down 😓 and symlinked the component to the /app/core/components directory.  Works fine now.  But it's the same (spiritually) as what I was trying to do with modules.  

Would be nice if there was an extended options, where I could put in the directories to scan for when creating the rpc routes.

**Comment by dillonraphael** [comment]
As you said `[[...blitz]]` currently scans a specific directory. I can see us adding the ability to set a custom directory. Feel free to start an RFC discussion.
