### ISSUE TITLE
Global suppressFirstRenderFlicker

### ISSUE THREAD

**Issue by paulm17** [blitz-js/blitz#3535]
### What do you want and why?
Seems like suppressFirstRenderFlicker is on a per page basis.

Would be awesome to have the ability to set this on a global basis and not think about it.  But still have the option to use Layout or Page to toggle it.  I'm sure someone else can make a case for it to be global, but on a particular page have it off...  lots of use cases not doubt!

Edit: For the toolkit please!

Thanks

**Comment by beerose** [comment]
Thanks for the suggestion!

**Comment by Zeko369** [comment]
Referencing a similar idea from #2692

**Comment by paulm17** [comment]
Yes, it would be amazing to have a page.authenticate or page.redirectTo and also have the ability to override on a layout or page basis also.

So Global -> Layout -> Page in that order.  😄
