### ISSUE TITLE
Toolkit: Upgrade React-Query to V4.

### ISSUE THREAD

**Issue by paulm17** [blitz-js/blitz#3543]
### What do you want and why?

The toolkit currently ships with 3.39.0.  Would be nice to upgrade Blitz to v4.

Is it a case of changing the version number?  Or there's a little more to it?

I have an edge case that I cannot seem to squash with v3.  

V4 has support for lazy queries: https://tanstack.com/query/v4/docs/guides/disabling-queries#lazy-queries

Whereas V3 doesn't seem to mention them.  🤷‍♂️ 

If it doesn't seem to be too complicated, wouldn't mind tackling it... 😄 

----------

So here is the upgrade guide:  https://tanstack.com/query/v4/docs/guides/migrating-to-react-query-4

This may be breaking changes to apps, so I don't know how [the team] want to handle this?

**Comment by Zeko369** [comment]
While I agree that we need to move to RQ4 at some point, doesn't `enabled: false` work the same way in RQ3 as it does in RQ4?

[react query 3 docs for that](https://react-query-v3.tanstack.com/guides/disabling-queries#_top)

**Comment by paulm17** [comment]
No, remember we went though this on discord.  I thought being able to set a mounted state and via useEffect set it to true and on that refresh, the useQuery option would then be true.

It seemed to only work once and now just doesn't work.

I'd wager pausing/disabling queries is not the same as lazy loading.  I haven't looked at the RQ code, but I'm 🙏  that V4 has improvements.

**Comment by paulm17** [comment]
Reached out to the tanstack discord and was pointed to 

> https://tkdodo.eu/blog/react-query-fa-qs#how-can-i-pass-parameters-to-refetch

I haven't tried it yet, but maybe worth linking to in Blitz own docs.  Or maybe I'm an outlier as not many will hit this issue? 🤷‍♂️
