### ISSUE TITLE
pnpm: Module not found: ESM packages (supports-color) need to be imported

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#3580]
1. Generate a new app with `2.0.0-alpha.56`
   - have to use `blitz new testblitz --skip-upgrade` flag because of https://github.com/blitz-js/blitz/issues/3566
   - select pnpm
3. Run `blitz build`
4. See the below errors
   - **Note:** these don't fail the build, but it causes all of blitzjs logging to not have any formatting or color

```
> testblitz@1.0.0 build /private/tmp/testblitz
> blitz build

Loaded env from /private/tmp/testblitz/.env.local
Loaded env from /private/tmp/testblitz/.env
info  - Linting and checking validity of types
info  - Creating an optimized production build
warn  - Compiled with warnings

./node_modules/.pnpm/debug@4.3.3/node_modules/debug/src/node.js
Module not found: ESM packages (supports-color) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals
```

Problem is that supports-color v9 is esm, and we need to stay with v8 because we are on debug v4. Maybe we add a pnpm resolution in our package's package.json to fix it?

## Workaround

In your app:
```
pnpm i supports-color@8
```

**Comment by Zeko369** [comment]
Since we can't really upgrade to `supports-color@9`, I'd just add this to the `package.json`
```json
  "resolutions": {
    "supports-color": "8"
  },
```
