### ISSUE TITLE
enhancePrisma is undefined

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#3582]
This doesn't happen in every app, which is confusing to me, but we definitely have a code bug here.

![image](https://user-images.githubusercontent.com/8813276/180420997-53018057-173c-4ebe-86e6-3e2eec291a13.png)

### Problem & FIx

Currently we are only exporting `enhancePrisma` in the [server entrypoint](https://github.com/blitz-js/blitz/blob/main/packages/blitz/src/index-server.ts#L9), but we need to export it in the [browser entrypoint](https://github.com/blitz-js/blitz/blob/main/packages/blitz/src/index-browser.tsx)

- [ ] Move [`runPrisma` util](https://github.com/blitz-js/blitz/blob/main/packages/blitz/src/prisma-utils.ts#L58-L79) into a different file, because we don't want it in the browser entrypoint
- [ ] Move enhancePrisma export to the index-browser file
- [ ] Add [this code from legacy blitz](https://github.com/blitz-js/legacy-framework/blob/main/nextjs/packages/next/build/webpack-config.ts#L1113-L1125) webpack to [withBlitz webpack config](https://github.com/blitz-js/blitz/blob/57a53fa3c2d6b98e9f96145fd595a72ce7731476/packages/blitz-rpc/src/index-server.ts#L78-L104):

**Comment by datner** [comment]
I'll try to do that ✋🏻
