### ISSUE TITLE
Passport integration doc updates?

### ISSUE THREAD

**Issue by sherryxiao1988** [blitz-js/blitz#3594]
[The passport integration page ](https://blitzjs.com/docs/passportjs#1-add-the-passport-js-api-route) is outdated and not linked from the left main Navbar anymore.

The error I've been getting follow the above tutorial is:
```
error - (api)/pages/api/auth/[...auth].js (4:28) @ eval
TypeError: (0 , blitz__WEBPACK_IMPORTED_MODULE_0__.passportAuth) is not a function
  2 | import { Strategy as GoogleStrategy } from "passport-google-oauth20"
  3 |
> 4 | export default passportAuth(({ ctx, req, res }) => ({
    |                            ^
  5 |   successRedirectUrl: "/",
  6 |   errorRedirectUrl: "/",
  7 |   strategies: [
```

Can anyone take a look to see what's need to be changed to work?

Thanks.

**Comment by beerose** [comment]
Are you using legacy blitz or the new alpha?

**Comment by Zeko369** [comment]
This looks like new alpha, since this problem only happens on new alpha (happened to 2 people already), and that's a missing wrap of `api()`

```ts
export default api(passportAuth(...))
```

**Comment by beerose** [comment]
Docs are updated now: https://github.com/blitz-js/blitzjs.com/commit/fc6781bd84460f9e39e5a5289f33064861ae4f03. Closing the issue.

**Comment by sherryxiao1988** [comment]
Thanks a lot!

**Comment by sherryxiao1988** [comment]
Still getting the same error after adding api:

```
error - (api)/pages/api/auth/[...auth].js (6:15) @ eval
TypeError: (0 , blitz__WEBPACK_IMPORTED_MODULE_0__.passportAuth) is not a function
  4 |
  5 | export default api(
> 6 |   passportAuth(({ ctx, req, res }) => ({
    |               ^
  7 |     successRedirectUrl: "/",
  8 |     errorRedirectUrl: "/",
  9 |     strategies: [
  ```
