### ISSUE TITLE
Call many requests when build in production env using Docker

### ISSUE THREAD

**Issue by linhltn** [blitz-js/blitz#3597]
### What is the problem?

Currently the server is calling many requests when build in production environment using Docker, it only happens in  GET Method

I tried running Dev mode on the server, everything is fine, and I only get this issue when I build with Docker
Even the built-in function of blitzjs when creating a new project, getCurrentUser() has the same problem.

https://www.youtube.com/watch?v=T9SWNtQm_v0

### Paste all your error logs here:

```
PASTE_HERE (leave the ``` marks)
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

inux 5.4 | linux-x64 | Node: v14.18.2

blitz: 0.45.4 (global)
blitz: 0.45.4 (local)

  Package manager: yarn 
  System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (4) x64 Intel Xeon E312xx (Sandy Bridge, IBRS update)
    Memory: 1.49 GB / 7.23 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.18.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 3.15.1 => 3.15.1 
    blitz: 0.45.4 => 0.45.4 
    prisma: 3.15.1 => 3.15.1 
    react: 18.0.0 => 18.0.0 
    react-dom: 18.0.0 => 18.0.0 
    typescript: ~4.5 => 4.5.5 

PASTE_HERE (leave the ``` marks)

**Comment by StringKe** [comment]
@beerose  https://github.com/blitz-js/blitz/issues/3595 Seems to be the same problem?

**Comment by beerose** [comment]
> @beerose #3595 Seems to be the same problem?

Yes, it looks like it. I think this issue is not related to refetchInterval, but the result (infinite requests) is the same. Also, for you it's not related to Docker, right?

**Comment by linhltn** [comment]
I need help @beerose 🆘

**Comment by cesarve77** [comment]
same issue in production when you run it in port 3000 (not 80)

**Comment by WaysToGo** [comment]
is this fixed?
