### ISSUE TITLE
Codemod only transfers a string value of `cookiePrefix`

### ISSUE THREAD

**Issue by dillonraphael** [blitz-js/blitz#3603]
### What is the problem?

The codemod searches for `cookiePrefix` and assumes there is always a string as the value. This won't work all the time because there can also be a ternary statement. (eg: 
```
cookiePrefix: process.env.APP_ENV === "production" ? "app-production" : "app-dev",
```
)

**Comment by beerose** [comment]
If cookie prefix is undefined we should throw an error telling people to fix it manually.
