### ISSUE TITLE
Allow passing port to blitz start

### ISSUE THREAD

**Issue by dwightwatson** [blitz-js/blitz#361]
### What do you want and why?
I want to be able to run the development server on a different port, in case I'm running multiple Blitz apps side by site, or I'm using port 3000 for something else. Next.js lets you do this with the `-p` or `--port` flag - for example `next start -p 8000`.

### Possible implementation(s)
This is a little hairy because `blitz start` already has a flag `-p` for production. I'd like to propose instead that `-p` be used for port as it's more consistent with Next.js, and then use a different flag like `--production` instead. I actually think that's a win/win because it's much more explicit and obvious when you're starting the server in production mode.

I **think** it's a matter of accepting a port argument in the CLI and forwarding it to the `startNextDev` method.

### Additional context
Off the top of my head a number of other development servers use `-p` for the port - like Gatsby and Rails. I feel that it's pretty conventional in a way and so it would help Blitz to be consistent.

**Comment by merelinguist** [comment]
Thanks for the issue! This is an interesting problem, but I think your proposed solution sounds the most sensible. I’m interested to see whether anyone has any ideas for preferred flags for the production startup, and then this would be a good first issue.

**Comment by flybayer** [comment]
@dwightwatson your point about `-p` is very good. I definitely overlooked that.

Also, it turns out we already have an issue open for this port thing: https://github.com/blitz-js/blitz/issues/301

So I'll close this in favor of that one, but I'll comment over there about changing the flag.

**Comment by dwightwatson** [comment]
I did search but that issue didn’t come up bizarrely! Thanks 😊
