### ISSUE TITLE
Blitz RPC logging is not using our standard logger and does not match legacy log output

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#3614]
### What do you want and why?

[All these console logs](https://github.com/blitz-js/blitz/blob/main/packages/blitz-rpc/src/index-server.ts#L171-L245) should be changed to use [our standard logger](https://github.com/blitz-js/blitz/blob/main/packages/blitz/src/logging.ts#L32).

### Possible implementation(s)

All the logging code should be copied [from our legacy code](https://github.com/blitz-js/legacy-framework/blob/main/nextjs/packages/next/server/api-utils.ts#L174-L276). The logging output should match **exactly** the output of legacy blitz.

**Comment by Himanxu1** [comment]
Hey @flybayer  I want to work on this issue .
I want more information.
What exactly needs to be done

**Comment by Himanxu1** [comment]
Should I change console.info(),console.error() to log.info() . log.error()

**Comment by beerose** [comment]
> Should I change console.info(),console.error() to log.info() . log.error()

We should use the `baseLogger` (https://github.com/blitz-js/blitz/blob/main/packages/blitz/src/logging.ts#L32) insetad of `console.x`.
