### ISSUE TITLE
Unhandled Runtime Error Error: The server could not finish this Suspense boundary, likely due to an error during server rendering. Switched to client rendering.

### ISSUE THREAD

**Issue by sherryxiao1988** [blitz-js/blitz#3623]
### What is the problem?

<img width="836" alt="image" src="https://user-images.githubusercontent.com/1202426/181344966-ad8474f6-1a6d-4902-ac0a-d2e571ef7f14.png">

I tested this only happens when adding passport auth with Google (tried to add the auth file to a new sample repo, reproduced the issue).  

### Paste all your error logs here:

Server side log:
```
xiaoshundan-macbookpro2:tokenpass xiaoshundan$ blitz dev
Loaded env from /Users/xiaoshundan/workspace/tokenpass/.env.local
Loaded env from /Users/xiaoshundan/workspace/tokenpass/.env
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 647 ms (275 modules)
wait  - compiling /404 (client and server)...
event - compiled client and server successfully in 176 ms (280 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
wait  - compiling / (client and server)...
event - compiled client and server successfully in 128 ms (325 modules)
[Rendering Suspense fallback...]
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
[Rendering Suspense fallback...]
[Rendering Suspense fallback...]
wait  - compiling /api/rpc/[[...blitz]]...
event - compiled successfully in 136 ms (91 modules)
[blitzSessionMiddleware] Starting handler...
Starting sessionMiddleware...
Starting with input: null
Result: null
Next.js serialization:1ms
Finished: resolver:0ms serializer:1ms total:1ms
```

Client side error:
```
Unhandled Runtime Error
Error: The server could not finish this Suspense boundary, likely due to an error during server rendering. Switched to client rendering.

Call Stack
updateDehydratedSuspenseComponent
node_modules/react-dom/cjs/react-dom.development.js (21469:0)
updateSuspenseComponent
node_modules/react-dom/cjs/react-dom.development.js (21129:0)
beginWork
node_modules/react-dom/cjs/react-dom.development.js (22379:0)
beginWork$1
node_modules/react-dom/cjs/react-dom.development.js (27219:0)
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js (26392:0)
workLoopSync
node_modules/react-dom/cjs/react-dom.development.js (26303:0)
renderRootSync
node_modules/react-dom/cjs/react-dom.development.js (26271:0)
performConcurrentWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js (25577:0)
workLoop
node_modules/scheduler/cjs/scheduler.development.js (266:0)
flushWork
node_modules/scheduler/cjs/scheduler.development.js (239:0)
MessagePort.performWorkUntilDeadline
node_modules/scheduler/cjs/scheduler.development.js (533:0)
```

### Paste all relevant code snippets here:

Please check:
https://github.com/sherryxiao1988/blitz-passport-error/blob/main/pages/api/auth/%5B...auth%5D.ts

### What are detailed steps to reproduce this?

I created a repo with this error:

https://github.com/sherryxiao1988/blitz-passport-error

### Run `blitz -v` and paste the output here:

```
xiaoshundan-macbookpro2:blitz-example xiaoshundan$ blitz -v
Loaded env from /Users/xiaoshundan/workspace/blitz-example/.env.local
Loaded env from /Users/xiaoshundan/workspace/blitz-example/.env
Blitz version: 2.0.0-alpha.58 (global)
Blitz version: 2.0.0-alpha.58 (local)
macOS Monterey | darwin-x64 | Node: v16.15.1


 Package manager: npm

  System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 557.58 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  npmPackages:
    @blitzjs/auth: alpha => 2.0.0-alpha.58
    @blitzjs/next: alpha => 2.0.0-alpha.58
    @blitzjs/rpc: 2.0.0-alpha.58 => 2.0.0-alpha.58
    @prisma/client: 3.9.0 => 3.9.0
    blitz: 2.0.0-alpha.58 => 2.0.0-alpha.58
    next: 12.2.0 => 12.2.0
    prisma: 4.0.0 => 4.0.0
    react: 18.0.0 => 18.0.0
    react-dom: 18.0.0 => 18.0.0
    typescript: ^4.5.3 => 4.7.4
```

**Comment by sherryxiao1988** [comment]
I tried delete the [...auth] file and the passport related dependencies, but this error seems to be here to stay.

**Comment by sherryxiao1988** [comment]
I saw this in the server log:
```
Starting sessionMiddleware...


Error while processing the request
[CSRFTokenMismatchError] { statusCode: 401 }
```

**Comment by sherryxiao1988** [comment]
Attached a vscode debugger, I saw this:
![image](https://user-images.githubusercontent.com/1202426/181423921-dccb3620-f342-4276-be81-f16f0baeff4f.png)

**Comment by sherryxiao1988** [comment]
![image](https://user-images.githubusercontent.com/1202426/181425046-b07a0cb9-396c-4576-a3f3-a02a657500f5.png)
Wonder if this one it's more related? I deleted all the style jsx, but still have the same error.

**Comment by sherryxiao1988** [comment]
The error disappeared after updating everything to `2.0.0-alpha.60`

**Comment by sherryxiao1988** [comment]
Still experiencing this issue after updating somehow. The issue disappeared for a while and then reappeared.

**Comment by sherryxiao1988** [comment]
The problem disappears when I put `useSession({suspense: false})` everywhere, but this is not ideal.

**Comment by sherryxiao1988** [comment]
Actually downgrade `@blitzjs@auth` `@blitzjs/next` and `@blitzjs/rpc` back to the "alpha" version solved my problem. Maybe some bugs were introduced at later versions.

**Comment by sherryxiao1988** [comment]
Still getting this error even after downgrading the versions (after adding more components on the page)

**Comment by sherryxiao1988** [comment]
Fixed! Was some server side error.

**Comment by janvennemann** [comment]
@sherryxiao1988 How did you figure out what caused the issue? I'm seeing this to as soon as i use anything that triggers a suspense fallback like `useSession` or `useQuery`. I have the components wrapped in a `Suspense` and even tried adding a `Suspense` directly in my `_app` to catch all, but to no avail. Everything works fine as soon as client side rendering takes over.

**Comment by sherryxiao1988** [comment]
@janvennemann I thought I fixed this issue but I didn't. Let me explain a little bit more and also reopen this issue so mainters could help take a look.

I thought what happend to me was this: https://nextjs.org/docs/messages/react-hydration-error

In short words, If your rendering depends on some objects that only exists in the client side (e.g., the window object). Server side pre-rendering will have different result than the browser side first rendering. 

I thought that's why I had those errors. I fixed them based on the soultion provided in the link but I then quickly realized I had things that's totatlly the same in server side and client side, but still getting those errors - `anything that triggers a suspense fallback like useSession or useQuery` as you said).

One workaround is :

```
  const [ssr, setSsr] = useState(true)

  useEffect(() => {
    setSsr(false)
  })
```

Then when rendering do:

```
return (
          {!ssr && (
            <Suspense fallback="Loading...">
              <UesrInfo />
            </Suspense>
          )}
)
```
So the component won't render until the `ComponenetDidMount`, so before that server side pre-rendring is the same with the broswer side rendering. But this workaround definately negates the benefits that Next give (all the benefts of SSR). 

I was unsure whether this was only my newbie's problem since I am very new to Next and Blitzjs and I have't written any frontend code for ~3ys.

**Comment by sherryxiao1988** [comment]
Hi @beerose I saw you edit the tags of this issue. Has the root cause been identifed already?

Thanks a lot!

**Comment by beerose** [comment]
Hey @sherryxiao1988, unfortunately not yet. Maybe @dillonraphael has some ideas as he was working on a fix.

**Comment by dillonraphael** [comment]
@sherryxiao1988 We patch your nextjs with a fix for this whenever `blitz codegen` is called. It happens on the postinstall script for `@blitzjs/next`.

Can you try updating to the latest alpha version?

Also after checking your repo, you seem to have a version mismatch between packages. Some are `alpha` & some are hardcoded. I just tested your repo with all the versions set to `2.0.0-alpha.65` & it all seems to be working. I will close this now.

**Comment by noxify** [comment]
Thanks for the hint @dillonraphael :)

I have added the following line to the `scripts` section in the `package.json` to make sure the fix is working even when i add a new package to my repo :) ( since I had the same problem after installing a new package )

```
    "postinstall": "blitz codegen"

```

**Comment by beerose** [comment]
Still happening after a fresh install. Using latest version @dillonraphael

**Comment by dillonraphael** [comment]
> Still happening after a fresh install. Using latest version @dillonraphael

Hmm not for me. Not able to replicate.

**Comment by sherryxiao1988** [comment]
I am still seeing this error in 2.0.0-beta.1

**Comment by flybayer** [comment]
@sherryxiao1988 in development or production? If production, then that is fixed in [v2.0.0-beta.2](https://github.com/blitz-js/blitz/releases/tag/v2.0.0-beta.2)

**Comment by sherryxiao1988** [comment]
Thanks @flybayer. Updating the version to v2.00-beta.2 fixed it.

**Comment by vivek7405** [comment]
@dillonraphael I am facing this issue after upgrading to blitz 2.0

I am using v2.0.0-beta.19

Can you please guide how to fix the issue?

**Comment by frissonlabs** [comment]
It looks like this occurs again on v2.00-beta.23. I used the default app template (`blitz new`) and simply added `const session = useSession()` to the `Layout` component (`Layout.tsx`), and this error pops up. It goes away if I use `const session = useSession({ suspense: false })`, but is that a band-aid?
