### ISSUE TITLE
ship vscode debug launch.json

### ISSUE THREAD

**Issue by Vandivier** [blitz-js/blitz#3624]
### What do you want and why?

blitz already ships with some vscode-specific files. The docs explain how to create an appropriate launch.json to debug using vs code. Why not simply ship a prebuilt launch config file?

### Possible implementation(s)

Include launch.json either at the top level or within the .vscode folder

### Additional context

existing debug doc
https://blitzjs.com/docs/troubleshooting#vscode

**Comment by beerose** [comment]
Good idea!

**Comment by siddhsuresh** [comment]
Hey, @beerose can I work on this?
