### ISSUE TITLE
misleading out of date notice at `blitz dev` time

### ISSUE THREAD

**Issue by Vandivier** [blitz-js/blitz#3625]
### What is the problem?

fresh install with blitz 2.0.0-alpha.59, install went fine but when i `blitz dev` i get a misleading log:

![image](https://user-images.githubusercontent.com/5559355/181395601-eb6e4688-5e6a-487f-9c0e-f206411c1bd0.png)

### Paste all your error logs here:

```
PASTE_HERE (leave the ``` marks)
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
John Vandivier@DESKTOP-MMSRKCH MINGW64 /d/workspace/github/kahneman (main)
$ blitz --version
Loaded env from D:\workspace\github\kahneman\.env.local
Loaded env from D:\workspace\github\kahneman\.env
Blitz version: 2.0.0-alpha.59 (global)
Blitz version: 2.0.0-alpha.59 (local)
Windows 10 | win32-x64 | Node: v16.2.0


 Package manager: npm

  System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
    Memory: 8.41 GB / 19.86 GB
  Binaries:
    Node: 16.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.20.6 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @blitzjs/auth: alpha => 2.0.0-alpha.59
    @blitzjs/next: alpha => 2.0.0-alpha.59
    @blitzjs/rpc: alpha => 2.0.0-alpha.59
    @prisma/client: 4.0.0 => 4.0.0
    blitz: 2.0.0-alpha.59 => 2.0.0-alpha.59
    next: 12.2.0 => 12.2.0
    prisma: 4.0.0 => 4.0.0
    react: 18.0.0 => 18.0.0
    react-dom: 18.0.0 => 18.0.0
    typescript: ^4.5.3 => 4.7.4
```

### Please include below any other applicable logs and screenshots that show your problem:

only other thing i would note is that i am using yarn for deps, although `blitz -v` thinks it's npm

**Comment by beerose** [comment]
Thanks for the report!

**Comment by beerose** [comment]
Closing in favor of https://github.com/blitz-js/blitz/issues/3566
