### ISSUE TITLE
Blitz generate creating broken files

### ISSUE THREAD

**Issue by markdav** [blitz-js/blitz#3633]
### What is the problem?

Blitz newbie disclaimer.  Tried adding an entity:

```
blitz generate all competition
```
It codegend a bunch of files but many of them had glitches:  

Update mutation:

![image](https://user-images.githubusercontent.com/5741188/181606379-b7a7f316-73c4-4779-8724-48bba5968be0.png)

pages - e.g. edit:

![image](https://user-images.githubusercontent.com/5741188/181607200-c0145e39-2ce9-43f6-a362-029f4119128c.png)

Main glitches:
- When the entity in the prisma schema has an id other than "id" the generated code doesn't seem right (I think I saw another defect around here which seemed similar.  E.g. in this case, many of the statements have "where id:" rather than "where competitionId".  
- In the update file it was missing an import for Ctx
- the input wasn't provided properly to the db.update statement (shouldn't it be in the "data" attribute?)
- Some other files were missing an "await" before the router.push

I think it should be 

update mutation:
![image](https://user-images.githubusercontent.com/5741188/181607575-d4899ebf-a1a3-48c1-8246-74ce51c5e924.png)

edit page:
![image](https://user-images.githubusercontent.com/5741188/181607447-5903f953-421a-4e2c-b3c1-46ff5468788d.png)

### Paste all your error logs here:

```
PASTE_HERE (leave the ``` marks)
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-alpha.57 (global)
Blitz version: 2.0.0-alpha.57 (local)
Windows 10 | win32-x64 | Node: v16.15.1


 Package manager: npm

  System:
    OS: Windows 10 10.0.16299
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 15.70 GB / 31.88 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @blitzjs/auth: alpha => 2.0.0-alpha.57
    @blitzjs/next: alpha => 2.0.0-alpha.57
    @blitzjs/rpc: alpha => 2.0.0-alpha.57
    @prisma/client: 3.9.0 => 3.9.0
    blitz: 2.0.0-alpha.57 => 2.0.0-alpha.57
    next: 12.2.0 => 12.2.0
    prisma: 4.0.0 => 4.0.0
    react: 18.0.0 => 18.0.0
    react-dom: 18.0.0 => 18.0.0
    typescript: ^4.5.3 => 4.7.4
```

### Please include below any other applicable logs and screenshots that show your problem:
The schema I added to the prisma db had other fields:

```
model Competition {
  competitionId Int      @id @default(autoincrement())
  name          String
  description   String
  location      String
  startDate     DateTime
  endDate       DateTime
  federation    String
}
```
Note sure if the "pages" template was supposed to generate ui elements for these fields or not, but it didn't - just the "name" one.

_No response_

**Comment by beerose** [comment]
Hey! Thanks for the report — we'll update the templates accordingly (I think we have a regression). 

What Blitz version are you using?

**Comment by markdav** [comment]
Blitz version: 2.0.0-alpha.57 (global)
Blitz version: 2.0.0-alpha.57 (local)
Windows 10 | win32-x64 | Node: v16.15.1


 Package manager: npm

  System:
    OS: Windows 10 10.0.16299
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 15.70 GB / 31.88 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @blitzjs/auth: alpha => 2.0.0-alpha.57
    @blitzjs/next: alpha => 2.0.0-alpha.57
    @blitzjs/rpc: alpha => 2.0.0-alpha.57
    @prisma/client: 3.9.0 => 3.9.0
    blitz: 2.0.0-alpha.57 => 2.0.0-alpha.57
    next: 12.2.0 => 12.2.0
    prisma: 4.0.0 => 4.0.0
    react: 18.0.0 => 18.0.0
    react-dom: 18.0.0 => 18.0.0
    typescript: ^4.5.3 => 4.7.4

**Comment by beerose** [comment]
Hey @markdav, the issue with Ctx in resolver files was fixed in one of the recent releases. The router no-floating-promises problem will be fixed here: https://github.com/blitz-js/blitz/pull/3848
