### ISSUE TITLE
getSession error after clearing Cookies

### ISSUE THREAD

**Issue by sherryxiao1988** [blitz-js/blitz#3640]
### What is the problem?

<img width="831" alt="image" src="https://user-images.githubusercontent.com/1202426/181807836-0c53eb06-6197-4943-bf83-74b0745181f3.png">

<img width="786" alt="image" src="https://user-images.githubusercontent.com/1202426/181809071-a8f7cc3d-bcfb-49d9-bcc3-4bdf2de05ec4.png">

### Paste all your error logs here:

```
error - TypeError: Cannot read properties of undefined (reading 'secureCookies')
    at setAnonymousSessionCookie (/Users/xiaoshundan/workspace/tokenpass/node_modules/@blitzjs/auth/dist/index-server.cjs:352:34)
    at createNewSession (/Users/xiaoshundan/workspace/tokenpass/node_modules/@blitzjs/auth/dist/index-server.cjs:491:5)
    at createAnonymousSession (/Users/xiaoshundan/workspace/tokenpass/node_modules/@blitzjs/auth/dist/index-server.cjs:556:16)
    at getSession (/Users/xiaoshundan/workspace/tokenpass/node_modules/@blitzjs/auth/dist/index-server.cjs:148:27)
    at async getServerSideProps (webpack-internal:///./pages/index.tsx:31:21)
    at async Object.renderToHTML (/Users/xiaoshundan/workspace/tokenpass/node_modules/next/dist/server/render.js:573:20)
    at async doRender (/Users/xiaoshundan/workspace/tokenpass/node_modules/next/dist/server/base-server.js:917:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/Users/xiaoshundan/workspace/tokenpass/node_modules/next/dist/server/base-server.js:1022:28)
    at async /Users/xiaoshundan/workspace/tokenpass/node_modules/next/dist/server/response-cache.js:69:36 {
  page: '/'
```

### Paste all relevant code snippets here:

```
export const getServerSideProps = async ({ req, res }) => {
  console.log("req is", req)
  const session = await getSession(req, res)

  return { props: { initialPublicData: session.$publicData } }
}
```

### What are detailed steps to reproduce this?

1. create a session normally
2. clear the Cookies

### Run `blitz -v` and paste the output here:

```
blitz -v
Loaded env from /Users/xiaoshundan/workspace/tokenpass/.env.local
Loaded env from /Users/xiaoshundan/workspace/tokenpass/.env
Blitz version: 2.0.0-alpha.58 (global)
Blitz version: 2.0.0-alpha.61 (local)
macOS Monterey | darwin-x64 | Node: v16.15.1


 Package manager: npm

  System:
    OS: macOS 12.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 9.39 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-alpha.61 => 2.0.0-alpha.61
    @blitzjs/next: 2.0.0-alpha.61 => 2.0.0-alpha.61
    @blitzjs/rpc: 2.0.0-alpha.61 => 2.0.0-alpha.61
    @prisma/client: 4.1.0 => 4.1.0
    blitz: 2.0.0-alpha.61 => 2.0.0-alpha.61
    next: 12.2.0 => 12.2.0
    prisma: 4.1.0 => 4.1.0
    react: 18.0.0 => 18.0.0
    react-dom: 18.0.0 => 18.0.0
    typescript: ^4.5.3 => 4.7.4
```

**Comment by beerose** [comment]
Hey @sherryxiao1988, I just tried to reproduce it with the following steps:

1. Create a new Blitz app (v2.0.0-alpha.64)
2. Add your code snippet to `index.tsx` (the getServerSideProps)
3. Start dev server 
4. Sign up
5. Clear cookies

I didn't get this error, though. After I removed cookies, the UI got updated to a logged-out user, and a new anonymous session was created. The console.log `console.log("req is", req)` was printed correctly. 

Is there anything else that could trigger that? Also, could you try the newest Blitz (maybe it was fixed along with something else)? If that doesn't help, would you mind providing us with a repo with a reproduction?

**Comment by sherryxiao1988** [comment]
Hi @sherryxiao1988 , thanks a lot for taking a look. Instead of using Sessions, I used query to get the current user from the database to avoid this problem. I am closing this issue for now, but if I come across it again I will let you know.
