### ISSUE TITLE
Self-closing tag ignored by node selector in upgrade-legacy codemod

### ISSUE THREAD

**Issue by Bobberta** [blitz-js/blitz#3641]
### What is the problem?

I ran into an "unexpected error" while running the `upgrade-legacy` codemod, at the `update imports in the _document file` step: 
```TypeError: Cannot read property 'name' of null```

I dug into the code and managed to identify the reason for that error.
See l.941: https://github.com/blitz-js/blitz/blob/922bc276d95829b58d99b7a9f78f2af8e9b358a2/packages/codemod/src/upgrade-legacy.ts#L941
We are looking for the opening element for `DocumentHead` 

In my case, `DocumentHead` was empty, and was written as a self-closing tag: `<DocumentHead />` , thus making it invisible for this query, since we are looking for a node with an `openingElement` with a name of DocumentHead.

Changing `<DocumentHead />` to `<DocumentHead><DocumentHead/>` has fixed the issue.

### Paste all your error logs here:

```
✖ update imports in the _document file
TypeError: Cannot read property 'name' of null
This is an unexpected error. Please ask for help in the discord #general-help channel. https://discord.blitzjs.com
```

### Paste all relevant code snippets here:

_document.tsx
```
import { Document, Html, DocumentHead, Main, BlitzScript } from "next/document";
import React from 'react';
import { DocumentContext } from 'blitz';

class MyDocument extends Document {
  static async getInitialProps(ctx: DocumentContext) {
    const initialProps = await Document.getInitialProps(ctx);
    return {
      ...initialProps,
      styles: React.Children.toArray([initialProps.styles]),
    };
  }

  render() {
    return (
      <Html lang="en">
        <DocumentHead />
        <body>
          <Main />
          <BlitzScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
```

### What are detailed steps to reproduce this?

1. Add a self-closing `DocumentHead` tag in `_document.tsx`
2. Run `npx @blitzjs/codemod upgrade-legacy`

### Run `blitz -v` and paste the output here:

```
alpha
```

**Comment by beerose** [comment]
Thanks for the report. Will fix that soon!
