### ISSUE TITLE
Toolkit: Auth - Passport - Custom strategy name

### ISSUE THREAD

**Issue by noxify** [blitz-js/blitz#3686]
### What do you want and why?

While trying to implement the third party login via passportjs I have currently the challenge to change the strategy name.

There are some providers which have a static strategy name ( e.g. [twitter](https://github.com/jaredhanson/passport-twitter/blob/master/lib/strategy.js#L54)  ) and there are some providers ( in my case https://github.com/panva/node-openid-client ) which have a generic name ( e.g. the [issuer hostname](https://github.com/panva/node-openid-client/blob/main/lib/passport_strategy.js#L70) ).

It would be good to have an additional/optional property in the strategy definition to override the default strategy name.

### Possible implementation(s)

Add a new optional property ( `name` or `alias`? ) to the definition to override the default strategy name.

**What needs to be changed?**

* Update the type definition for [`BlitzPassportStrategy`](https://github.com/blitz-js/blitz/blob/main/packages/blitz-auth/src/server/passport-adapter.ts#L41)
* Update the [`assert`](https://github.com/blitz-js/blitz/blob/main/packages/blitz-auth/src/server/passport-adapter.ts#L111) to check if there is a strategy with the given name 
* Update the [`passport.use`](https://github.com/blitz-js/blitz/blob/main/packages/blitz-auth/src/server/passport-adapter.ts#L118) call and pass the strategy name as first argument <br>( `passport.use(<name>, <strategy)` instead of `passport.use(<strategy>)`)
* Update documentation

### Additional context

If you want, I can provide a PR with the changes

**Comment by beerose** [comment]
This is a good idea, thanks for creating this issue! 

Here's a relevant passport-adapter code: https://github.com/blitz-js/blitz/blob/83b355900b592f75a0f51d29fad266c0bf3464a1/packages/blitz-auth/src/server/passport-adapter.ts. Would be awesome if you could create a Pr for that! Let me know if you have any questions :)

**Comment by noxify** [comment]
@beerose - you can assign it to me, will give it a try
