### ISSUE TITLE
invalidateQuery not working without params

### ISSUE THREAD

**Issue by medihack** [blitz-js/blitz#3725]
### What is the problem?

In v2.0.0-alpha.70 `invalideQuery` does not work anymore without providing the optional `params`. So `invalidateQuery(getUsers)` does not work, but `invalidateQuery(getUsers, {})` does work.

### Paste all your error logs here:

None

### Paste all relevant code snippets here:

See above

### What are detailed steps to reproduce this?

See above

### Run `blitz -v` and paste the output here:

Blitz version: 2.0.0-alpha.67 (global)
Blitz version: 2.0.0-danger.67 (local)
Linux 5.15 | linux-x64 | Node: v16.16.0

 Package manager: npm

  System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 AMD EPYC 7B13
    Memory: 41.35 GB / 62.81 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  npmPackages:
    @blitzjs/auth: ^2.0.0-alpha.70 => 2.0.0-danger.67 
    @blitzjs/next: ^2.0.0-alpha.70 => 2.0.0-danger.67 
    @blitzjs/rpc: ^2.0.0-alpha.70 => 2.0.0-danger.67 
    @prisma/client: ^4.1.1 => 4.2.1 
    blitz: ^2.0.0-alpha.70 => 2.0.0-danger.67 
    next: ^12.2.2 => 12.2.5 
    prisma: ^4.1.1 => 4.2.1 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: 4.6.3 => 4.6.3

**Comment by beerose** [comment]
Thanks for the report! We'll look into it soon

**Comment by beerose** [comment]
For whoever is going to look into this issue: we probably need to look into how queryKey is generated. We probably generate a different query key if `useQuery` doesn't have params vs in `invalidateQuery`.

**Comment by Zeko369** [comment]
The problem here is that if nothing is passed to `invalidateQuery` it assumes undefined as a value and passed that to the serializer.

**Comment by medihack** [comment]
Will this fix be merged for the next beta? When the query has non-optional parameters, you can't just do `invalidateQuery(getUsers, {})` but have to cast the empty object to `any`. It is also [against the documentation](https://blitzjs.com/docs/resolver-client-utilities#arguments-1) (_"If you don't provide this, it will invalidate all resolver queries"_).

**Comment by Zeko369** [comment]
@medihack This should be fixed in the next beta, #3728
