### ISSUE TITLE
Minified React Error with Production Build

### ISSUE THREAD

**Issue by lnguyenfx** [blitz-js/blitz#3726]
### What is the problem?

Newly created projects using `blitz new` (with all default settings selected) output a "Minifed React error" in the console when run as a production build.

### Paste all your error logs here:

```
framework-fc97f3f1282ce3ed.js:1 
        
Uncaught Error: Minified React error #419; visit https://reactjs.org/docs/error-decoder.html?invariant=419 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Lu (framework-fc97f3f1282ce3ed.js:1:88313)
    at di (framework-fc97f3f1282ce3ed.js:1:121964)
    at is (framework-fc97f3f1282ce3ed.js:1:106937)
    at os (framework-fc97f3f1282ce3ed.js:1:106865)
    at as (framework-fc97f3f1282ce3ed.js:1:106728)
    at qi (framework-fc97f3f1282ce3ed.js:1:101872)
    at S (framework-fc97f3f1282ce3ed.js:1:138081)
    at MessagePort.T (framework-fc97f3f1282ce3ed.js:1:138615)
```

### Paste all relevant code snippets here:

```
blitz create test-project
cd test-project
npm run build
blitz start
```

### What are detailed steps to reproduce this?

1. Execute `blitz new test-project` command
2. Select 'TypeScript' as project's language
3. Select 'Full - includes DB and auth (Recommended)` as app template
4. Select 'Yes' to install dependences (with npm)
5. Select 'React Final Form (recommended)' as form library
6. Execute `cd test-project` command
7. Execute `echo -e '\nSESSION_SECRET_KEY="this_is_a_test_secret_key_012345"' >> .env.local`
8. Execute `npm run build` command
9. Execute `blitz start` command
10. Open 'http://localhost:3000' in the browser
11. Open the console window in the Developer tools panel
12. Observe the error

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-alpha.71 (global)
Blitz version: 2.0.0-alpha.71 (local)
Windows 11 | win32-x64 | Node: v16.16.0


 Package manager: npm

  System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
    Memory: 18.07 GB / 31.87 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @blitzjs/auth: 2.0.0-alpha.71 => 2.0.0-alpha.71
    @blitzjs/next: 2.0.0-alpha.71 => 2.0.0-alpha.71
    @blitzjs/rpc: 2.0.0-alpha.71 => 2.0.0-alpha.71
    @prisma/client: 4.0.0 => 4.0.0
    blitz: 2.0.0-alpha.71 => 2.0.0-alpha.71
    next: 12.2.0 => 12.2.0
    prisma: 4.0.0 => 4.0.0
    react: 18.0.0 => 18.0.0
    react-dom: 18.0.0 => 18.0.0
    typescript: ^4.5.3 => 4.7.4
```

### Please include below any other applicable logs and screenshots that show your problem:

![image](https://user-images.githubusercontent.com/1874876/184551361-1ec23d9f-79a9-4803-b018-03e3f0c29b36.png)

**Comment by beerose** [comment]
Thanks for the report! We'll look into it soon!
