### ISSUE TITLE
Update eslint config with upgrade-legacy codemod

### ISSUE THREAD

**Issue by FlorianWendelborn** [blitz-js/blitz#3737]
### What is the problem?

ESLint doesn’t work after migrating to Blitz V2. The [documentation page](https://blitzjs.com/docs/eslint-config) uses the same code snippet that exists in my repo so it’s unclear how to resolve this.

### Paste all your error logs here:

```
$ eslint --ext .js,.ts,.tsx . --fix

Oops! Something went wrong! :(

ESLint: 8.22.0

ESLint couldn't find the config "blitz" to extend from. Please check that the name of the config is correct.

The config "blitz" was referenced from the config file in "./.eslintrc.js".

If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.
```

### Paste all relevant code snippets here:

```ts
module.exports = {
	extends: ['blitz']
}
```

### What are detailed steps to reproduce this?

1. Make an `.eslintrc.js` which attempts to extend from `blitz`

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.1 (local)
macOS Big Sur | darwin-x64 | Node: v16.16.0


 Package manager: npm

  System:
    OS: macOS 11.6.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 213.43 MB / 32.00 GB
    Shell: 3.3.1 - /usr/local/bin/fish
  Binaries:
    Node: 16.16.0 - /var/folders/qx/3nty7c0x6hzd8_q8nkbqq50m0000gn/T/yarn--1660575023904-0.5016463859620897/node
    Yarn: 1.22.19 - /var/folders/qx/3nty7c0x6hzd8_q8nkbqq50m0000gn/T/yarn--1660575023904-0.5016463859620897/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  npmPackages:
    @blitzjs/auth: Not Found
    @blitzjs/next: Not Found
    @blitzjs/rpc: Not Found
    @prisma/client: Not Found
    blitz: Not Found
    next: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: ^4.7.4 => 4.7.4 
```

(versions not showing is probably a blitz + lerna interoperability issue)

**Comment by madhenry** [comment]
Perhaps just

`yarn add -D eslint-config-next`

and

```js
module.exports = {
	extends: ['next']
}
```

?

Not sure though

**Comment by FlorianWendelborn** [comment]
I ended-up going for this solution. I’m not 100% sure that it’s the correct thing to do but it was the best I could come up with.

1. `yarn add -D eslint-config-blitz`
2. `extends: ['blitz']`

I don’t know if this is the intended way to use it and the documentation or migration codemod should certainly be improved so I’ll leave this open

**Comment by CarlosZiegler** [comment]
Same problem here :)

**Comment by beerose** [comment]
We should cover that in the upgrade-legacy codemod.

The new eslint config should look like this:

```
// .eslintrc.js

module.exports = require("@blitzjs/next/eslint")
```

So you shouldn't need to install a new dependency — eslint config is included in the `@blitzjs/package`.

**Comment by siddhsuresh** [comment]
Hey @beerose @dillonraphael could I work on this?

**Comment by FlorianWendelborn** [comment]
@beerose so customizing eslint is no longer possible with blitz 2? That makes it pretty much unusable

**Comment by FlorianWendelborn** [comment]
FYI, I had to add `eslint-config-next` to my `devDependencies`.

```
Oops! Something went wrong! :(

ESLint: 8.22.0

ESLint couldn't find the config "eslint-config-next" to extend from. Please check that the name of the config is correct.

The config "eslint-config-next" was referenced from the config file in "./node_modules/@blitzjs/next/eslint.js".

If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.
```

Other than that, I only ran into issues that are related to me using a lerna monorepo. I resolved them by only adding this config file to `packages/web/.eslintrc.js` (my blitz package):

```ts
module.exports = {
	extends: ['../../node_modules/@blitzjs/next/eslint'],
	parserOptions: {
		project: 'tsconfig.json',
		tsconfigRootDir: __dirname,
		sourceType: 'module',
	},
}
```
