### ISSUE TITLE
Add Material-UI example app

### ISSUE THREAD

**Issue by cr101** [blitz-js/blitz#374]
Example project that uses [Material-UI](https://github.com/mui-org/material-ui)

**Comment by Skn0tt** [comment]
Thank you for that idea, sounds good to me 👍🏻 Would you be open to provide a PR? 🙈

**Comment by Jfelix61** [comment]
I would love to take this issue.

**Comment by flybayer** [comment]
Awesome @Jfelix61! Let us know if you need any help!

**Comment by lednhatkhanh** [comment]
I was trying the exact same thing and stumbled upon a problem: Everything I put inside the `Head` tag of `_app.tsx` and `_document.tsx` are not being loaded, I don't know whenever this is my mistake or not, please refer to this repo for more details: https://github.com/lednhatkhanh/blitz-shop just clone and run `blitz start` since it doesn't have any data yet.

**Comment by lednhatkhanh** [comment]
UPDATE: So rendering `<DocumentHead />` allows the style to be rendered, but now the button doesn't have the ripple effect when being clicked at all.

**Comment by Jfelix61** [comment]
The implementation is almost done, and Material UI works. However, I'm getting a mismatch of classes between the server and the client. 

![image](https://user-images.githubusercontent.com/21092519/80893558-66c48580-8ca1-11ea-83e6-1bbad84e8b08.png)

Tried with vanilla Next.js and it works just fine. Something must be going on with blitz code generation. Any ideas @flybayer?

**Comment by Jfelix61** [comment]
After some long investigation. It seems it is a problem with React's experimental version. `16.13.1` seems to be working just fine. Most likely concurrent mode is not very compatible with Material UI server side rendering styles yet.

**Comment by Jfelix61** [comment]
> UPDATE: So rendering `<DocumentHead />` allows the style to be rendered, but now the button doesn't have the ripple effect when being clicked at all.

I am getting the same problem with the ripple effect. I have disabled Blitz config and tried to run the server and the ripple works, therefore something must be going on in blitz/server. Will be investigating...

**Comment by flybayer** [comment]
Closed in #840!

You can now run:
```
blitz install material-ui
```
