### ISSUE TITLE
Error when trying to install a recipe

### ISSUE THREAD

**Issue by whaleAPI** [blitz-js/blitz#3740]
### What is the problem?

when I want to install the chakra ui recipe it gives me an error

### Paste all your error logs here:

$ blitz install chakra-ui
Loaded env from C:\Users\Parcero\Desktop\wallet\.env.local
Loaded env from C:\Users\Parcero\Desktop\wallet\.env
Error: Cannot find module 'install'
Require stack:
- C:\Users\Parcero\Desktop\wallet\noop.js

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

Blitz version: 2.0.0-beta.1 (global)
Blitz version: 2.0.0-beta.1 (local)
Windows 10 | win32-x64 | Node: v16.15.1

 Package manager: npm

  System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Pentium(R) Gold G5400 CPU @ 3.70GHz
    Memory: 2.48 GB / 7.87 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.1 => 2.0.0-beta.1
    @blitzjs/next: 2.0.0-beta.1 => 2.0.0-beta.1
    @blitzjs/rpc: 2.0.0-beta.1 => 2.0.0-beta.1
    @prisma/client: 4.0.0 => 4.0.0
    blitz: 2.0.0-beta.1 => 2.0.0-beta.1
    next: 12.2.0 => 12.2.0
    prisma: 4.0.0 => 4.0.0
    react: 18.0.0 => 18.0.0
    react-dom: 18.0.0 => 18.0.0
    typescript: ^4.5.3 => 4.7.4

### Please include below any other applicable logs and screenshots that show your problem:

![Screenshot_5](https://user-images.githubusercontent.com/95057356/184787454-e18c1433-84b6-49bf-a1bc-2c3bdb62da92.png)

**Comment by DataCrusade1999** [comment]
refer to #3253 it's not supported yet.

**Comment by emersonlaurentino** [comment]
any news about it? I have the same problem

**Comment by whaleAPI** [comment]
> 

refer to [#3253](https://github.com/blitz-js/blitz/issues/3253) it's not supported yet.
