### ISSUE TITLE
TypeScript linting errors for styled-jsx

### ISSUE THREAD

**Issue by waxidiotic** [blitz-js/blitz#3744]
### What is the problem?

I was working through the tutorial when I was checking out the `LabeledTextField.tsx` component and VS Code immediately had a red squiggle under `jsx` in `<style jsx>`. The same thing happens for `<style global>`.

### Paste all your error logs here:

```
Type '{ children: string; jsx: true; }' is not assignable to type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'.
  Property 'jsx' does not exist on type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'.
```

### Paste all relevant code snippets here:

```
<style jsx>{`
  label {
    display: flex;
    flex-direction: column;
    align-items: start;
    font-size: 1rem;
  }
  input {
    font-size: 1rem;
    padding: 0.25rem 0.5rem;
    border-radius: 3px;
    border: 1px solid purple;
    appearance: none;
    margin-top: 0.5rem;
  }
`}</style>
```

### What are detailed steps to reproduce this?

1.  Create a new TypeScript Blitz app with all of the defaults via the Blitz CLI.
2. Open the project in VS Code.
3. Navigate to `/app/core/components/LabeledTextField.tsx` (or anywhere else `styled-jsx` is used).
4. Wait a few seconds for the linting to show the error in the editor.

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.1 (global)
Blitz version: 0.1.0 (local)
macOS Monterey | darwin-arm64 | Node: v16.15.1


 Package manager: npm

  System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 82.72 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  npmPackages:
    @blitzjs/auth: Not Found
    @blitzjs/next: Not Found
    @blitzjs/rpc: Not Found
    @prisma/client: Not Found
    blitz: Not Found
    next: ^12.2.0 => 12.2.0
    prisma: Not Found
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^4.5.5 => 4.7.4
```

### Please include below any other applicable logs and screenshots that show your problem:

I initially reported this via [Discord](https://discord.com/channels/802917734999523368/1008859617176059955).

**Comment by gcavanunez** [comment]
Hi, updating the following packages should mitigate the lint error

```
"next": "12.2.5",
"react": "18.2.0",
"react-dom": "18.2.0",
"@types/react": "18.0.14",
```

I believe in your case it should just be the next version

**Comment by waxidiotic** [comment]
Yup, everything is fine after updating those packages. Thanks!
