### ISSUE TITLE
reset-password.tsx page is missing

### ISSUE THREAD

**Issue by sfarrowGR** [blitz-js/blitz#3747]
### What is the problem?

After creating a new project with the Blitz cli, using the reset password fails as the page the email directs to does not exist.

### Paste all your error logs here:

```
none - when clicking the link the email a 404 page is returned
```

### Paste all relevant code snippets here:

none

### What are detailed steps to reproduce this?

1. Create a new app.
2.  blitz dev
3. create user
4. log out
5. click login
6. click forgot password link
7. enter email and click reset
8. view preview email
9. click the link in email.

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.1 (global)
Blitz version: 2.0.0-beta.1 (local)
macOS Monterey | darwin-arm64 | Node: v16.15.1


 Package manager: npm

  System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 390.56 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.17.0 - /usr/local/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.1 => 2.0.0-beta.1 
    @blitzjs/next: 2.0.0-beta.1 => 2.0.0-beta.1 
    @blitzjs/rpc: 2.0.0-beta.1 => 2.0.0-beta.1 
    @prisma/client: 4.0.0 => 4.0.0 
    blitz: 2.0.0-beta.1 => 2.0.0-beta.1 
    next: 12.2.0 => 12.2.0 
    prisma: 4.0.0 => 4.0.0 
    react: 18.0.0 => 18.0.0 
    react-dom: 18.0.0 => 18.0.0 
    typescript: ^4.5.3 => 4.7.4 


```

**Comment by beerose** [comment]
Thanks for the report. It will be soon fixed by https://github.com/blitz-js/blitz/pull/3743
