### ISSUE TITLE
Add custom template usage back to toolkit 

### ISSUE THREAD

**Issue by madaxen86** [blitz-js/blitz#3748]
The legacy version supported the use of custom templates.
Docs: 
[Custom templates](https://blitzjs.com/docs/cli-generate#custom-templates)
[blitz.config.ts](https://blitzjs.com/docs/cli-generate#custom-templates)
This does not work at the moment.
`blitz generate` will always use the default templates instead.
@beerose

**Comment by siddhsuresh** [comment]
@beerose can I work on this and add this back to the generate command? If so, should I add the option for the custom template folder in the ```next.config.js``` or in the ```app/blitz-server.ts``` or is some other location preferred?

**Comment by beerose** [comment]
@siddhsuresh we were thinking about using `export default` in `app/blitz-server.ts` for this. Something like:

```
// app/blitz-server.ts

export const {api} = setupBlitzServer(...)

const config = {
  customTemplates: ...
  // .. 
}

export default config
```
