### ISSUE TITLE
LinkedIn Login

### ISSUE THREAD

**Issue by cr101** [blitz-js/blitz#375]
Add simple app to demo Linkedin login

**Comment by Skn0tt** [comment]
Thanks for taking the time to create the issue 🎉 I think this has to wait until after https://github.com/blitz-js/blitz/issues/326 is implemented, since Blitz' auth implementation will rely on middleware.

**Comment by merelinguist** [comment]
I imagine that Passport has a strategy for LinkedIn login, so this also depends on https://github.com/blitz-js/blitz/issues/752

**Comment by flybayer** [comment]
#752 is already implemented!

[Here's the docs](https://blitzjs.com/docs/auth#third-party) on using the passport.js adapter.

I'm not sure it makes sense to add an example now? Probably better is to simply make a recipe for it.

**Comment by merelinguist** [comment]
@flybayer Agreed. I think we should put as much of this kind of stuff in recipes as possible, and leave examples for demos of feature implementations.
