### ISSUE TITLE
Body exceeded 1mb limit error in blitzjs mutations

### ISSUE THREAD

**Issue by karimsx** [blitz-js/blitz#3762]
### What do you want and why?

augment size limit received by blitzjs mutations

### Possible implementation(s)

expres bodyparser

**Comment by potikhanovsergey** [comment]
It's described in docs

<img width="690" alt="image" src="https://user-images.githubusercontent.com/71494201/185783721-30199a2b-8c04-44aa-b2e7-cbc3fd7c0684.png">

**Comment by karimsx** [comment]
@potikhanovsergey its for api routes, is it working for mutation files?

**Comment by beerose** [comment]
If you're using Blitz 2.0, you can do it in the RPC API route (`pages/api/rpc/[[...blitz]].ts`):

```
import {rpcHandler} from "@blitzjs/rpc"
import {api} from "app/blitz-server"

export default api(rpcHandler({onError: console.log}))

export const config = {
  api: ...
}
```
