### ISSUE TITLE
Hydration error while using redirectAuthenticatedTo (v2.0.0-beta.2)

### ISSUE THREAD

**Issue by medihack** [blitz-js/blitz#3767]
### What is the problem?

When using `redirectAuthenticatedTo` I end up with an error in the console (see error log below). It is missed by the ErrorBoundary of `_app` and only logged in the browser console. This can be easily reproduced in a freshly created blitz app. There was a similar error that was closed (#3528) with a PR, but the described error here still happens in v2.0.0-beta.2.

### Paste all your error logs here:

```
Warning: An error occurred during hydration. The server HTML was replaced with client content in <div>. 
See more info here: https://nextjs.org/docs/messages/react-hydration-error next-dev.js:20:25

Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
    React 8
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    EventHandlerNonNull* scheduler.development.js:571
    <anonymous> scheduler.development.js:633
    NextJS 4
    <anonymous> index.js:6
    NextJS 4
    React 2
    NextJS 4
    <anonymous> React
    NextJS 4
    <anonymous> index.js:8
    NextJS 4
    <anonymous> index.js:21
    NextJS 4
    <anonymous> next-dev.js:3
    NextJS 7
next-dev.js:20:25

```

### Paste all relevant code snippets here:

An example repository (nearly fresh setup with example user and test page) can be found here: https://github.com/medihack/blitz-app/tree/test-redirect
If you use this Gitpod link then the database is already migrated and seeded with a test user: https://gitpod.io/#https://github.com/medihack/blitz-app/tree/test-redirect

### What are detailed steps to reproduce this?

1. Clone the above repository (or use the Gitpod link and continue with step 6)
2. `yarn install`
3. `blitz prisma migrate dev`
4. `blitz db seed`
5. `blitz dev`
6. Go to / (when using Gitpod simply do `gp preview $(gp url 3000)`
7. Login with email "test@test.com" and password "test"
8. Go to /test-redirect
9. Watch the console

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.2 (global)
Blitz version: 2.0.0-beta.2 (local)
Linux 5.15 | linux-x64 | Node: v16.16.0


 Package manager: npm

  System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 AMD EPYC 7B13
    Memory: 15.09 GB / 62.80 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.2 => 2.0.0-beta.2 
    @blitzjs/next: 2.0.0-beta.2 => 2.0.0-beta.2 
    @blitzjs/rpc: 2.0.0-beta.2 => 2.0.0-beta.2 
    @prisma/client: 4.0.0 => 4.0.0 
    blitz: 2.0.0-beta.2 => 2.0.0-beta.2 
    next: 12.2.5 => 12.2.5 
    prisma: 4.0.0 => 4.0.0 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.5.3 => 4.7.4
```

**Comment by dillonraphael** [comment]
Hey @medihack we're going to investigate this ASAP

**Comment by flybayer** [comment]
Ok @medihack, this is actually normal and expected behavior with all of our auth-related redirects. The implementation throws a RedirectError, causing the first render on the client to be different than the static HTML. Which is especially important in then case where you don't want an unauthenticated user to see an authenticated page.

So as long as your app continues to work correctly after the redirect, then you are good. But if you are seeing any problematic behavior like buttons not working or something, then let us know.

**Comment by medihack** [comment]
Ok, thanks. Good to know. When I see red in the console and read "error" I normally think that there is something wrong there ;-) And no, nothing seems to be broken on the page after the redirect.

**Comment by flybayer** [comment]
We changed the implementation and this is fixed in https://github.com/blitz-js/blitz/pull/3842

**Comment by medihack** [comment]
That's cool ... keep the console clear :-) Thanks for letting me know!
