### ISSUE TITLE
Codemods should probably run on components directory

### ISSUE THREAD

**Issue by tmcw** [blitz-js/blitz#3770]
### What is the problem?

One of the codemods that's currently implemented will also look at the `components` directory to scan for components to upgrade:

https://github.com/blitz-js/blitz/blob/b72d1215c3c0741810e55d79ead8b130d0607797/packages/codemod/src/upgrade-legacy.ts#L1138

But the rest don’t:

https://github.com/blitz-js/blitz/blob/b72d1215c3c0741810e55d79ead8b130d0607797/packages/codemod/src/upgrade-legacy.ts#L891

I think they should? My application certainly imports routing-related logic into `components` - this might be against some clean-coding notion but it isn't against any advice from Blitz's docs and doesn't cause any real-world issues in my experience.

It'd be nice if most of the upgrade-related codemods ran over both app _and_ components.

### Paste all your error logs here:

```
PASTE_HERE (leave the ``` marks)
```

### Paste all relevant code snippets here:

```
components/placemark_inner_public.tsx:12:37 - error TS2305: Module '"blitz"' has no exported member 'Routes'.

12 import { ErrorBoundary, Head, Link, Routes, useQuery } from "blitz";
```

### What are detailed steps to reproduce this?

1. Have a Blitz application that imports query-related modules into components.

### Run `blitz -v` and paste the output here:

```

 Package manager: npm

  System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M2
    Memory: 659.17 MB / 24.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.volta/tools/image/node/16.16.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.11.0 - ~/.volta/tools/image/node/16.16.0/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.2 => 2.0.0-beta.2
    @blitzjs/next: 2.0.0-beta.2 => 2.0.0-beta.2
    @blitzjs/rpc: 2.0.0-beta.2 => 2.0.0-beta.2
    @prisma/client: ^4 => 4.2.1
    blitz: 2.0.0-beta.2 => 2.0.0-beta.2
    next: 12.2.0 => 12.2.0
    prisma: ^4 => 4.2.1
    react: ^18.0.0 => 18.2.0
    react-dom: ^18.0.0 => 18.2.0
    typescript: ~4.6 => 4.6.4
```

**Comment by dillonraphael** [comment]
@tmcw Actually, the opposite seems to be happening here. The 3rd argument in `getAllFiles` is an array for directories to ignore. 

Where is your `components` directory located?

**Comment by tmcw** [comment]
My components directory is located just at the root of my project, so a path would be like `components/trial_banner.tsx`. It appears that all components have been excluded from some of the transforms.

**Comment by dillonraphael** [comment]
> My components directory is located just at the root of my project, so a path would be like `components/trial_banner.tsx`. It appears that all components have been excluded from ~some of the transforms~ / actually - all of the transforms. Not seeing any changes to components files.

Out side the `app` directory right? We can update the codemod to look in a `component` directory outside the `app` directory.

**Comment by tmcw** [comment]
TBD, this might just be a corner case that only my application was doing - I don't think there's any rule that all your tsx files need to be in `app`, but there's also no suggestion that you should put them in the root directory. Might make more sense for people to move their other files into `app` before running the codemod.
