### ISSUE TITLE
Load custom log config from `setupBlitzServer`

### ISSUE THREAD

**Issue by dillonraphael** [blitz-js/blitz#3772]
### What is the problem?

We're currently missing the ability to load custom a custom config for `baseLogger()` found in the blitz package.

We should be loading the config here https://github.com/blitz-js/blitz/blob/3d950f77721d3ba766379445dd1e5e4ee5a08080/packages/blitz/src/logging.ts#L35-L40

and add a property called `log` to the object argument in `setupBlitzServer`

eg.
```ts
export const { gSSP, gSP, api } = setupBlitzServer({
  plugins: [
    AuthServerPlugin({
      ...authConfig,
      storage: PrismaStorage(db),
      isAuthorized: simpleRolesIsAuthorized,
    }),
  ],
  log: {
    type: "pretty"
  }
})
```

**Comment by siddhsuresh** [comment]
Hey @dillonraphael @beerose can I work on this?

**Comment by beerose** [comment]
Closing this issue in favour of https://github.com/blitz-js/blitz/issues/3706 (https://github.com/blitz-js/blitz/issues/3706 was created earlier than this one).
