### ISSUE TITLE
Only generate prisma client if it has not been generated

### ISSUE THREAD

**Issue by dillonraphael** [blitz-js/blitz#3775]
### What is the problem?

Currently the prisma client is being generated on most commands as part of the `codegen-tasks.ts` file (https://github.com/blitz-js/blitz/blob/3d950f77721d3ba766379445dd1e5e4ee5a08080/packages/blitz/src/cli/utils/codegen-tasks.ts#L40-L50)

Since it's a big performance hit, we should only be generating the prisma client once.

**Comment by siddhsuresh** [comment]
Hey @dillonraphael can I work on this?

**Comment by beerose** [comment]
> Hey @dillonraphael can I work on this?

Sure!
