### ISSUE TITLE
Generating prisma client fails when using global `blitz dev` command

### ISSUE THREAD

**Issue by dillonraphael** [blitz-js/blitz#3776]
### What is the problem?

Fails to generate the prisma client when running `blitz dev` with the global cli. It works when using `npx blitz dev`.

### Paste all your error logs here:

```shell
~ > blitz dev
...
Generating Prisma client{
  "code": "ENOENT"
}
...
```

**Comment by beerose** [comment]
The issue seems to result from the wrong path for `schema.prisma`. I believe that it will be fixed by https://github.com/blitz-js/blitz/pull/3855
