### ISSUE TITLE
Documentation pages out of date with latest Blitz

### ISSUE THREAD

**Issue by tmcw** [blitz-js/blitz#3786]
### What is the problem?

As far as I can tell, the expectation is that Blitzjs.com should be documenting v2 and any defects in that should be reported, but happy to not open issues if not 😆 

Some doc pages that are out of date:

- https://blitzjs.com/docs/eslint-config - the "default eslint config" is not the default anymore, and doesn't work anymore.
- https://blitzjs.com/docs/testing - the `test/utils.tsx` file is no longer generated.

### Paste all your error logs here:

(this is for docs)

### Paste all relevant code snippets here:

(this is for docs)

### What are detailed steps to reproduce this?

(this is for docs)

### Run `blitz -v` and paste the output here:

(this is for docs)

**Comment by beerose** [comment]
Thanks for reporting this! The eslint config should be updated and live in a few minutes. We'll cover testing soon too!
