### ISSUE TITLE
Codemod could/should update test environment

### ISSUE THREAD

**Issue by tmcw** [blitz-js/blitz#3787]
Right now if you run the codemod, you go from having a testing setup to generally not having one - none of the new testing dependencies are updated, `test/utils.tsx` isn't fully updated, any custom or basic jest configuration is not there.

It'd be very nice if the codemod updated the testing rig by installing necessary dependencies and setting up the jest configuration.

**Comment by beerose** [comment]
Good point! Thanks for reporting it
