### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by elbarto132** [blitz-js/blitz#3798]
### What is the problem?

After creating a new blitz app using "blitz new...", changing into the directory and trying to run "blitz install tailwind" I get "Error: Cannot find module 'install'"
For example the command "blitz dev" is working as expected. But I noticed that if I try to run "blitz help" I get "Error: Cannot find module 'help'"

### Paste all your error logs here:

```
C:\Users\X\myAppName>blitz install tailwind
Loaded env from C:\Users\X\myAppName\.env.local
Loaded env from C:\Users\X\myAppName\.env
Error: Cannot find module 'install'
Require stack:
- C:\Users\X\myAppName\noop.js
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1. npm install -g blitz
2. blitz new myAppName
3. cd myAppName
4. blitz install tailwind

### Run `blitz -v` and paste the output here:

```
C:\Users\X\myAppName>blitz -v
Blitz version: 2.0.0-beta.3 (global)
Blitz version: 2.0.0-beta.3 (local)
Windows 11 | win32-x64 | Node: v16.15.0


 Package manager: npm

  System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics
    Memory: 18.27 GB / 31.41 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.3 => 2.0.0-beta.3
    @blitzjs/next: 2.0.0-beta.3 => 2.0.0-beta.3
    @blitzjs/rpc: 2.0.0-beta.3 => 2.0.0-beta.3
    @prisma/client: 4.0.0 => 4.0.0
    blitz: 2.0.0-beta.3 => 2.0.0-beta.3
    next: 12.2.5 => 12.2.5
    prisma: 4.0.0 => 4.0.0
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.5.3 => 4.8.2
```

**Comment by noxify** [comment]
The recipe installer is currently not implemented.
But there is an PR which will solve this: https://github.com/blitz-js/blitz/pull/3784

**Comment by dillonraphael** [comment]
Yup as @noxify this will be coming back REALLY soon. PR is open https://github.com/blitz-js/blitz/pull/3784

I will close this issue, since it's already accounted for
