### ISSUE TITLE
Codemod should convert import statements to require when creating `next.config.js`

### ISSUE THREAD

**Issue by dillonraphael** [blitz-js/blitz#3800]
### What is the problem?

Currently when running the codemod on the step `move the config from blitz.config.ts to next.config.js`, it will take the old import statements from `blitz.config` and just move them to `next.config.js`.

Either this step (or in another step), the codemod should look for import statements and convert them to a require expression.

### What are detailed steps to reproduce this?

1. Run the codemod on a legacy blitz app
2. View the newly created `next.config.js` and find any import statements

### Run `blitz -v` and paste the output here:

```
3.0.0-beta.2
```

### Manual Fix?
If you'd like to fix this without the codemod, you can manually go into the `next.config.js` file and just replace the import statements with require your self.

**Comment by siddhsuresh** [comment]
@dillonraphael can I work on this?
