### ISSUE TITLE
Show file path on error for the `update project's import` step

### ISSUE THREAD

**Issue by dillonraphael** [blitz-js/blitz#3804]
### What is the problem?

Currently if the `update project's import` step fails with an `Unexpected Error`, we have no clue which file the error is happening on.

![unknown](https://user-images.githubusercontent.com/3496193/187560628-f1efb49a-7c05-42cf-8463-b96f12d2927e.png)

### Paste all relevant code snippets here:

We should put the logic inside a try catch block. Like what @siddhsuresh did here https://github.com/blitz-js/blitz/blob/c213d521c6e48702e5bccd12e0f4ac0d266f1809/packages/codemod/src/upgrade-legacy.ts#L1126-L1146

**Comment by siddhsuresh** [comment]
@dillonraphael can I work on this and add the try...catch block for all the instances where ```getAllFiles``` function is called?
