### ISSUE TITLE
Blitz CLI help command provides unexpected output

### ISSUE THREAD

**Issue by ravenberg** [blitz-js/blitz#3812]
### What is the problem?

As I was exploring the new Blitz beta I noticed a peculiar output when running help commands.

### Paste all your error logs here:

After installing Blitz globally I was able to setup a fresh neat new project with `blitz new`. But when exploring available commands with e.g. `blitz help` and `blitz -h` you get this:

```
Error: Cannot find module 'help'
Require stack:
- <current-working-directory>/noop.js
```

### Paste all relevant code snippets here:

```
blitz help
```

### What are detailed steps to reproduce this?

1. Install blitz globally
2. Run `blitz help`

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.3 (global)
Blitz version: 2.0.0-beta.3 (local)
macOS Monterey | darwin-arm64 | Node: v16.16.0


 Package manager: npm

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.21 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.17.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.3 => 2.0.0-beta.3
    @blitzjs/next: 2.0.0-beta.3 => 2.0.0-beta.3
    @blitzjs/rpc: 2.0.0-beta.3 => 2.0.0-beta.3
    @prisma/client: 4.0.0 => 4.0.0
    blitz: 2.0.0-beta.3 => 2.0.0-beta.3
    next: 12.2.5 => 12.2.5
    prisma: 4.0.0 => 4.0.0
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.5.3 => 4.8.2```


### Please include below any other applicable logs and screenshots that show your problem:

_No response_

**Comment by dillonraphael** [comment]
Thanks for letting us know

**Comment by luvolondon** [comment]
FYI: On my setup "blitz install" results in the same error. "blitz generate" and "blitz prisma" work as expected.

> Blitz version: 2.0.0-beta.3 (global)
Blitz version: 2.0.0-beta.3 (local)
Windows 8.1 | win32-x64 | Node: v16.17.0


> Package manager: npm

>  System:
    OS: Windows 8.1 6.3.9600
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 4.68 GB / 15.93 GB
  Binaries:
    Node: 16.17.0 - E:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.15.0 - E:\Program Files\nodejs\npm.CMD
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.3 => 2.0.0-beta.3
    @blitzjs/next: 2.0.0-beta.3 => 2.0.0-beta.3
    @blitzjs/rpc: 2.0.0-beta.3 => 2.0.0-beta.3
    @prisma/client: 4.0.0 => 4.0.0
    blitz: 2.0.0-beta.3 => 2.0.0-beta.3
    next: 12.2.5 => 12.2.5
    prisma: 4.0.0 => 4.0.0
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.5.3 => 4.8.2
