### ISSUE TITLE
Update recipes to work with blitz toolkit

### ISSUE THREAD

**Issue by dillonraphael** [blitz-js/blitz#3813]
### What is the problem?

Some recipes are out of date and need to be updated.

- [ ] `recipes/secureheaders`
- [ ] `recipes/theme-ui`
- [ ] `recipes/vanilla-extract`

The main thing that that needs to be updated is the use of `paths.blitzConfig()`. Blitz toolkit exports helpers for transforming `next.config.js`.

You can get the `next.config.js` path with `paths.nextConfig()`. `transformNextConfig` is exported from blitz and returns the following:

```ts
program: Program
configObj: []
pushToConfig: (property: j.ObjectProperty) => void
wrapConfig: (func: string | j.CallExpression) => {
   withBlitz: j.Identifier | j.CallExpression 
}
addRequireStatement: (identifier: string, packageName: string) => void
```

_(`wrapConfig().withBlitz` returns whatever is inside `withBlitz()`)_

**Comment by siddhsuresh** [comment]
Hey @dillonraphael can I work on this?
