### ISSUE TITLE
Infinite queries can't prefetch

### ISSUE THREAD

**Issue by imnoahcook** [blitz-js/blitz#3820]
### What is the problem?

I want to prefetch an infinite query, but using the format provided in the docs doesn't successfully prefetch the query and the data on the client is undefined on first fetch.
I confirmed this by `console.logging` the query results.

### Paste all your error logs here:

```
```

### Paste all relevant code snippets here:

Minimal project required
create new blitz app with cli

`pages/index.ts`
```ts
import Layout from "app/core/layouts/Layout"
import { Routes, BlitzPage } from "@blitzjs/next"
import { gSSP } from "app/blitz-server"
import testQuery from "app/core/queries/testQuery"
import { useInfiniteQuery, useQuery } from "@blitzjs/rpc"

export const getServerSideProps = gSSP(async ({ ctx }) => {
  await ctx.prefetchInfiniteQuery(testQuery, {
    name: "hello world",
  })

  return { props: {} }
})

const Home: BlitzPage = () => {
  const [data] = useInfiniteQuery(
    testQuery,
    (pageParams) => ({ ...pageParams, name: "hello world" }),
    {
      suspense: false,
      getNextPageParam: (lastPage) => lastPage,
    }
  )
  console.log("data", data)
  return <div title="Home">Hello world</div>
}

export default Home
```

`app/core/queries/testQuery.ts`
```ts
import { resolver } from "@blitzjs/rpc"
import * as z from "zod"

export const SampleInputZod = z.object({
  name: z.string(),
})

export default resolver.pipe(
  resolver.zod(SampleInputZod),
  async (input, ctx) => {
    await new Promise((r) => setTimeout(r, 4000))
    return "thanks"
  }
)
```

### What are detailed steps to reproduce this?

1. Create a new blitz app with create blitz app using default settings.
2. Replace pages/index.ts with code provided above
3. Create query file provided above
4. open dev console on chrome
5. the first results in the console will be undefined

### Run `blitz -v` and paste the output here:

```sh
Blitz version: 2.0.0-beta.3 (global)
Blitz version: 2.0.0-beta.3 (local)
macOS Monterey | darwin-x64 | Node: v16.13.0


 Package manager: pnpm

  System:
    OS: macOS 12.4
    CPU: (8) x64 Apple M1
    Memory: 59.58 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.14.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.3 => 2.0.0-beta.3
    @blitzjs/next: 2.0.0-beta.3 => 2.0.0-beta.3
    @blitzjs/rpc: 2.0.0-beta.3 => 2.0.0-beta.3
    @prisma/client: 4.0.0 => 4.0.0
    blitz: 2.0.0-beta.3 => 2.0.0-beta.3
    next: 12.2.5 => 12.2.5
    prisma: 4.0.0 => 4.0.0
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.5.3 => 4.8.2
    ```

### Please include below any other applicable logs and screenshots that show your problem:

<img width="563" alt="Screen Shot 2022-09-05 at 11 05 46 PM" src="https://user-images.githubusercontent.com/36086777/188538611-52ac966f-2956-47aa-8627-6f15d6bf4081.png">

**Comment by imnoahcook** [comment]
<img width="495" alt="Screen Shot 2022-09-05 at 11 07 08 PM" src="https://user-images.githubusercontent.com/36086777/188538746-ceae35ce-298a-48b5-926b-ec2c39d3e43e.png">

Screenshot of chrome console logs

**Comment by dillonraphael** [comment]
Thanks for creating this issue. We'll take a look at it soon
