### ISSUE TITLE
Page during SSR generates with no data

### ISSUE THREAD

**Issue by oceandrama** [blitz-js/blitz#3826]
### What is the problem?

HTML from server returns with `Loading...` fallback and all data appears only on the client
Without `<Suspense>` tag page crashes and not displayed
Error exists even in production mode

### What are detailed steps to reproduce this?

1. npm install -g blitz@latest
2. blitz new app (select TypeScript, Full and react-hook-form)
3. cd app
4. blitz dev
5. create new user
6. refresh index page
![image](https://user-images.githubusercontent.com/23439079/189545206-0fac001d-19c3-4d59-8f03-bbc2bc232cb0.png)

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.3 (global)
Blitz version: 2.0.0-beta.3 (local)
Windows 11 | win32-x64 | Node: v16.14.2


 Package manager: npm

  System:
    OS: Windows 10 10.0.22000
    CPU: (6) x64 Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
    Memory: 6.59 GB / 15.84 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.3 => 2.0.0-beta.3
    @blitzjs/next: 2.0.0-beta.3 => 2.0.0-beta.3
    @blitzjs/rpc: 2.0.0-beta.3 => 2.0.0-beta.3
    @prisma/client: 4.0.0 => 4.0.0
    blitz: 2.0.0-beta.3 => 2.0.0-beta.3
    next: 12.2.5 => 12.2.5
    prisma: 4.0.0 => 4.0.0
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.5.3 => 4.8.3
```

**Comment by dillonraphael** [comment]
This may have something todo with https://github.com/blitz-js/blitz/issues/3840
