### ISSUE TITLE
Improve docs structure (use legacy docs as a starting point)

### ISSUE THREAD

**Issue by beerose** [blitz-js/blitz#3828]
- [X] Change headings to `Blitz RPC`, `Blitz Auth` etc
- [ ] Go over each page and see how it can be improved:
  - [ ] Is there a guide?
  - [ ] Is the API covered?
  - [ ] Make sure that the information is correct and up to date with the Blitz 2.0
 - [ ] Add missing items like custom server, monorepos

**Comment by yaniket** [comment]
Hello @beerose mam can you give me the location of docs file
eg: Auth docs
     RPC docs

**Comment by beerose** [comment]
@yaniket you can find the docs repo here: https://github.com/blitz-js/blitzjs.com
