### ISSUE TITLE
`blitz db`  should print help message instead of error

### ISSUE THREAD

**Issue by nabi009** [blitz-js/blitz#383]
command: blitz db

 ›   Error: Missing 1 required arg:
 ›   command  Run specific db command
 ›   See more help with --help

the description should be clear to user, that missed command or shows db related command.
such as:
**blitz db migrate
blitz db introspect
blitz db studio
etc ....**

**Comment by flybayer** [comment]
Thank you @nabi009, you're absolutely right!

**Comment by peaonunes** [comment]
Happy to work on that if possible 😄

**Comment by flybayer** [comment]
@peaonunes yeah, that'd be awesome! Let us know if you need help

**Comment by nabi009** [comment]
![Screen Shot 2020-05-03 at 05 49 50](https://user-images.githubusercontent.com/3170831/80896327-5f819400-8d02-11ea-84d3-36dc5155fa61.png)
I have done it.

**Comment by peaonunes** [comment]
Looks nice! Feel free to open up the PR 😄 
**suggestion:** Perhaps we should use `log.warning` as it is a warning instead of a normal message? Idk. Seems to be missing the `reset` command, you can interpolate the `descriptions` static property to be in sync with the command defaults.

**Comment by nabi009** [comment]
@peaonunes thanks so much from your suggestion, your right but I did not change anything too much.
the original code is in blitz/packages/cli/src/commands/db.js
`exports.default = Db;
Db.description =`Run database commands

${chalk_1.default.bold(' migrate')}   Run any needed migrations via Prisma 2 and generate Prisma Client.

${chalk_1.default.bold(' introspect')}   Will introspect the database defined in db/schema.prisma and automatically \ngenerate a complete schema.prisma file for you. Lastly, it\'ll generate Prisma Client.

${chalk_1.default.bold(' studio')}   Open the Prisma Studio UI at http://localhost:5555 so you can easily see and\n change data in your database.
`;

Db.args = [

    {
        name: 'Commands',
        description: 'Run specific db command',
        required: true,
    },
   
];

Db.flags = {
    help: command_1.flags.help({ char: 'h' }),
};
`
and I changed it to this
`exports.default = Db;
Db.description =`Run database

${chalk_1.default.bold('👉 migrate')}   Run any needed migrations via Prisma 2 and generate Prisma Client.

${chalk_1.default.bold('👉 introspect')}   Will introspect the database defined in db/schema.prisma and automatically \ngenerate a complete schema.prisma file for you. Lastly, it\'ll generate Prisma Client.

${chalk_1.default.bold('👉 studio')}   Open the Prisma Studio UI at http://localhost:5555 so you can easily see and\n change data in your database.
`;

Db.args = [

    {
        name: 'Commands',
        description: Db.description,
        required: true,
    },
   
];

Db.flags = {
    help: command_1.flags.help({ char: 'h' }),
};`

I replace this "Run specific db command' to Db.description.
![Screen Shot 2020-05-03 at 05 55 43](https://user-images.githubusercontent.com/3170831/80912787-b1eba080-8d54-11ea-89d7-2ce302f5fd2c.png)
 now I think gives clear descriptions to the users.
1.  Error: Missing 1 required arg:
2. tells to the user that you may use these commands after db
Commands  Run database
 ›          
 ›              👉 migrate   Run any needed migrations via Prisma 2 and generate Prisma Client.
 ›          
 ›              👉 introspect   Will introspect the database defined in db/schema.prisma and automatically
 ›              generate a complete schema.prisma file for you. Lastly, it'll generate Prisma Client.
 ›          
 ›              👉 studio   Open the Prisma Studio UI at http://localhost:5555 so you can easily see and
 ›              change data in your database.
3. farther you may use --help to get full cli commands help
See more help with --help
