### ISSUE TITLE
Switch from Jest to Vitest for new Blitz app

### ISSUE THREAD

**Issue by medihack** [blitz-js/blitz#3835]
### What do you want and why?

As [discussed on Discord](https://discord.com/channels/802917734999523368/1018452312311730287/1019238651403714702) evaluate if [Vitest ](https://vitest.dev/) instead of Jest is a better fit for a new Blitz app. Especially as the Blitz monorepo itself uses Vitest as a testing library. 

### Possible implementation(s)

Next.js has an official [example](https://github.com/vercel/next.js/tree/canary/examples/with-vitest) of how to integrate Vitest.

**Comment by harshsinghatz** [comment]
Can I pick this?

**Comment by Zeko369** [comment]
Go ahead @harshsinghatz

**Comment by tmcw** [comment]
I've made some headway on this. Unfortunately the task of automatically migrating test files to vitest is blocked on #465 - recipes can only transform one fine.

**Comment by flybayer** [comment]
Thanks @tmcw! 

To clarify, this issue is mainly to change the new app template. We don't have to add a codemod or make any change to recipes afaik.

Having to stop using projects isn't ideal, but I think switching to vitest is still worth it.

**Comment by harshsinghatz** [comment]
@tmcw are you working on this migration?

**Comment by tmcw** [comment]
I've been working on a migration, but haven't made any efforts at changing the starter template, which is probably the better way to do it - so if you're still working on updating _new_ Blitz apps to use vitest, go for it.

**Comment by beerose** [comment]
Hey @tmcw and @harshsinghatz. I was asked to help with the template migration, so I'm going to cover the new app template part. I assigned myself to this issue.
