### ISSUE TITLE
Brand-new Blitz app renders four times with React strict mode turned on

### ISSUE THREAD

**Issue by medihack** [blitz-js/blitz#3836]
### What is the problem?

When enabling React strict mode a brand-new Blitz app renders 4 times on a page load (and 2 times without strict mode). Normally it should render only 2 times in strict mode (and only one time without strict mode). Is this really intended?

### Paste all your error logs here:

```
No logs needed.
```

### Paste all relevant code snippets here:

```
No code needed.
```

### What are detailed steps to reproduce this?

1. Create new Blitz app
2. Enable strict mode in `next.config.js`
3. Log to console in the home page.

Example app here: https://github.com/medihack/blitz-app

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.3 (local)
Linux 5.15 | linux-x64 | Node: v16.17.0


 Package manager: npm

  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 AMD EPYC 7B13
    Memory: 24.22 GB / 62.80 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.17.0 - /tmp/yarn--1663093115023-0.87583247247545/node
    Yarn: 1.22.19 - /tmp/yarn--1663093115023-0.87583247247545/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.3 => 2.0.0-beta.3 
    @blitzjs/next: 2.0.0-beta.3 => 2.0.0-beta.3 
    @blitzjs/rpc: 2.0.0-beta.3 => 2.0.0-beta.3 
    @prisma/client: 4.0.0 => 4.0.0 
    blitz: 2.0.0-beta.3 => 2.0.0-beta.3 
    next: 12.2.5 => 12.2.5 
    prisma: 4.0.0 => 4.0.0 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.5.3 => 4.8.3
```

**Comment by dillonraphael** [comment]
Interesting. May have something to do with suspense errors. We'll be looking into this

**Comment by medihack** [comment]
Still an issue in Beta 20.
