### ISSUE TITLE
Get rid of "blitz db seed"

### ISSUE THREAD

**Issue by medihack** [blitz-js/blitz#3838]
### What do you want and why?

Maybe we should get rid of `blitz db seed` and setup Prisma in a new Blitz app correctly that `blitz prisma db seed` can be used. Even executing `blitz db` tells me that `That command is no longer available..`.

### Possible implementation(s)

Make `blitz prisma db seed` work.

**Comment by Zeko369** [comment]
We had `blitz db seed` before prisma introduced `prisma seed`, since `blitz prisma` loads correct ENVs `blitz prisma seed` SHOULd have .env.local but this needs to be tested since I think was the main reason to keep it before (after prisma introduced seed)

**Comment by flybayer** [comment]
I think it's a reasonable idea to remove our `db seed` command in favor of prisma. But, I'm not sure if there are anyone using our db seed command without prisma?

Also, Prisma's seed mechanism is kind of goofy, requiring setting up your own ts-node or esbuild-runner command, etc.
