### ISSUE TITLE
Blitz server should show a helpful error if user tries to use `db` inside a React component

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#385]
### What is the problem?

It's too easy to mistakenly try to use the database client inside a React component. Currently you get a totally cryptic error:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in '/Users/reiwa/GitHub/hello-blitz/node_modules/@prisma/client/runtime'
```

We need to somehow detect this and throw a helpful error so the user knows exactly how resolve it

Note: it is ok to import `db` and use it inside `getServerSideProps`, `getStaticProps`, and `getStaticPaths`.

### Steps to Reproduce: 

1. `import db from 'db'` in a react component
2. Make a db call inside a react component

### Implementation

I'm not sure, but we might can do this as a babel plugin or a webpack plugin. Webpack could error if the `db` module or `@prisma/client` module is included in the client side bundle.

---

## Update:

The error you now see if trying to use `db` in your client side code is:

![image](https://user-images.githubusercontent.com/8813276/81052242-4ab52400-8eed-11ea-87c6-870aec92827b.png)

**Comment by wKovacs64** [comment]
Hmm, isn't `db` where one gets the generated model types, though?

https://github.com/blitz-js/blitz/blob/ea61978d080113c6c7d1b09b0473cb32b57474d6/examples/store/app/products/components/ProductForm.tsx#L2

Do we need to separate the client from the types? Something like:

```ts
import {Product, ProductCreateInput, ProductUpdateInput} from 'db/types'
```
