### ISSUE TITLE
Add `blitz console` option to skip preloading of queries/mutations

### ISSUE THREAD

**Issue by johnlk** [blitz-js/blitz#3858]
### What do you want and why?

I wish there were a way to skip over the pre-loading of queries and mutations when executing `blitz console`. For one, it's very slow especially when you have > 40 queries + mutations as my project does. Second, I almost never use my queries in the console.

When I SSH to my remote server and run `blitz console` it takes > 2 mins to preload queries. Locally, it's about 6 seconds. 

### Possible implementation(s)

Adding an option to skip over the query/mutation preloading. Maybe something like `--skip-preload`

### Additional context

<img width="511" alt="Screen Shot 2022-09-22 at 4 02 44 PM" src="https://user-images.githubusercontent.com/8771036/191769764-6fa28780-8c64-4233-9336-849a97ce2eca.png">

Related to #1098

**Comment by beerose** [comment]
Thanks for the suggestion! Currently blocked on https://github.com/blitz-js/blitz/issues/3862
