### ISSUE TITLE
Don't rely on hardcoded `db/prisma.schema`  — use whatever is configured in package.json

### ISSUE THREAD

**Issue by sharmapukar217** [blitz-js/blitz#3860]
I want the db folder to be prisma but there's no config available for this.

**Comment by beerose** [comment]
You can configure this in your `package.json` file:

```
"prisma": {
    "schema": "db/schema.prisma"
  },
```

Here you can find relevant docs: https://www.prisma.io/docs/concepts/components/prisma-schema#prisma-schema-file-location

**Comment by sharmapukar217** [comment]
I'm not talking about configuring for prisma, I want blitz js to use `prisma` folder rather than `db`

**Comment by beerose** [comment]
Blitz doesn't really use Prisma internally. Can you describe more about what's causing issues?

**Comment by sharmapukar217** [comment]
when I'm running blitz dev or blitz codegen, or any blitz command running or using prisma, i get "db/schema.prisma" not found 🥲  but its there at `prisma/schema.prisma`

**Comment by beerose** [comment]
Ah okay. It should be fixed with changes introduced in this PR: https://github.com/blitz-js/blitz/pull/3855.

However, I'm going to reopen this issue to make sure we don't rely on hardcoded db directory anywhere else.

**Comment by beerose** [comment]
Places to update:
- [ ] Blitz generator package
- [ ] Codegen tasks

**Comment by Zeko369** [comment]
Codegen tasks - already fixed by @dillonraphael in the last PR
Blitz generator package - in #3874
