### ISSUE TITLE
Update npm version of @blitzjs/cli

### ISSUE THREAD

**Issue by webdeb** [blitz-js/blitz#3861]
### What is the problem?

The latest deployed `@blitzjs/cli` version is 0.45.x.. 

### Paste all your error logs here:

```
PASTE_HERE (leave the ``` marks)
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
PASTE_HERE (leave the ``` marks)
```

**Comment by beerose** [comment]
Hey, `@blitzjs/cli` is deprecated. Is this causing any trouble?

**Comment by webdeb** [comment]
Ah, ok, thanks for clarification. I was getting an error while using `blitz prisma ..` that `@blitzjs/cli` is not installed.. Installed blitz globally, and its fixed now.
