### ISSUE TITLE
Add default settings.json inside of the repo to tell vscode which TS version to use

### ISSUE THREAD

**Issue by Zeko369** [blitz-js/blitz#3875]
### What do you want and why?

VSCode by default uses typescript bundled inside of itself (which is as of Oct 2nd ts4.8, while our repo is on ts4.6) which sometimes causes errors that aren't actual errors (will be when we upgrade but aren't right now)

### Possible implementation(s)

add `.vscode/settings.json` with
```json
{
  "typescript.tsdk": "node_modules/typescript/lib"
}
```

**Comment by Himanxu1** [comment]
Assign this to me .

**Comment by beerose** [comment]
@Himanxu1, @FreemRL already started working on this issue.
