### ISSUE TITLE
Blitz install stuck on "Generating file diff" in new project

### ISSUE THREAD

**Issue by mikeyXmomo** [blitz-js/blitz#3900]
### What is the problem?

`blitz install tailwind` stuck on "Generating file diff". I waited for an hour and still not done yet

### Paste all your error logs here:

```
Loaded env from /Users/macbookair/Documents/Projects/recipe-test/.env.local
Loaded env from /Users/macbookair/Documents/Projects/recipe-test/.env
✅ Installed 3 dependencies
✅ Installed 3 dependencies
✅ Successfully created postcss.config.js, tailwind.config.js
✅ Successfully created app/core/styles/index.css

+––––––––––––––––––––––––+
⎪   Import stylesheets   ⎪
+––––––––––––––––––––––––+
Imports the stylesheet we just added into your app

⠏Generating file diff...
```

### Paste all relevant code snippets here:

```
blitz install tailwind
```

### What are detailed steps to reproduce this?

1.Updated Blitz to version: 2.0.0-beta.12 with `sudo npm install -g blitz`
2. Created a new Blitz app with `blitz new`
3. `cd `into folder
4. Attempted to install tailwind with `blitz install tailwind` and stuck on "Generating file diff"

### Run `blitz -v` and paste the output here:

```
blitz -v
Blitz version: 2.0.0-beta.12 (global)
Blitz version: 2.0.0-beta.12 (local)
macOS Monterey | darwin-arm64 | Node: v18.7.0


 Package manager: npm

  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 79.05 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 3.2.2 - ~/.nvm/versions/node/v18.7.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.7.0/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.12 => 2.0.0-beta.12
    @blitzjs/next: 2.0.0-beta.12 => 2.0.0-beta.12
    @blitzjs/rpc: 2.0.0-beta.12 => 2.0.0-beta.12
    @prisma/client: 4.0.0 => 4.0.0
    blitz: 2.0.0-beta.12 => 2.0.0-beta.12
    next: 12.2.5 => 12.2.5
    prisma: 4.0.0 => 4.0.0
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.5.3 => 4.8.4
```

**Comment by dillonraphael** [comment]
Ya currently working on a fix

**Comment by rodobre** [comment]
Still experiencing this issue on 2.0.0-beta.17 with a fresh app.

Steps to reproduce on my system:

```
blitz new app_name
blitz install tailwind
```

```
blitz --version
Blitz version: 2.0.0-beta.17 (global)
Blitz version: 2.0.0-beta.17 (local)
macOS Monterey | darwin-arm64 | Node: v18.0.0


 Package manager: npm

  System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 103.11 MB / 16.00 GB
    Shell: 5.8 - /opt/homebrew/bin/zsh
  Binaries:
    Node: 18.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 9.1.1 - /opt/homebrew/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.17 => 2.0.0-beta.17
    @blitzjs/next: 2.0.0-beta.17 => 2.0.0-beta.17
    @blitzjs/rpc: 2.0.0-beta.17 => 2.0.0-beta.17
    @prisma/client: 4.6.0 => 4.6.0
    blitz: 2.0.0-beta.17 => 2.0.0-beta.17
    next: 12.2.5 => 12.2.5
    prisma: 4.6.0 => 4.6.0
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.8.4 => 4.8.4
```

**Comment by SemmelJochen** [comment]
Same thing here. Still experiencing this issue on 2.0.0-beta.18 with a fresh app on macOS Monterey 12.6.1.
blitz --version          
Blitz version: 2.0.0-beta.18 (global)
Blitz version: 2.0.0-beta.18 (local)
macOS Monterey | darwin-x64 | Node: v16.17.0


 Package manager: npm
`
  System:
    OS: macOS 12.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 979.15 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.18 => 2.0.0-beta.18 
    @blitzjs/next: 2.0.0-beta.18 => 2.0.0-beta.18 
    @blitzjs/rpc: 2.0.0-beta.18 => 2.0.0-beta.18 
    @prisma/client: 4.6.0 => 4.6.0 
    blitz: 2.0.0-beta.18 => 2.0.0-beta.18 
    next: 12.2.5 => 12.2.5 
    prisma: 4.6.0 => 4.6.0 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.8.4 => 4.9.3 
`

**Comment by nknganda** [comment]
Same issue on  Ubuntu 20.04.5 LTS (Focal Fossa)

## Steps to reproduce:

1. Installed Blitz with `npm install -g blitz`
2. Created a new Blitz app with `blitz new mysite`
3. cd into the folder
4. Attempted to install tailwind with `blitz install tailwind` and stuck on "Generating file diff"

## Logs after forcefully exiting the command:

```
Loaded env from /home/newton/Experiments/blitz-site/.env.local
Loaded env from /home/newton/Experiments/blitz-site/.env
✅ Installed 3 dependencies

  ERROR  The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

 node:fs:592:10

 - Object.openSync (node:fs:592:10)
 - Object.readFileSync (node:fs:468:35)
 - generateDiff (recipe-install/node_modules/blitz/dist/installer.cjs:350:42)
 - processTicksAndRejections (node:internal/process/task_queues:95:5)

ERROR 
 TypeError  The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
details:
{
  code: 'ERR_INVALID_ARG_TYPE'
}
error stack:
• node:fs:592 openSync
    node:fs:592:10

• node:fs:468 readFileSync
    node:fs:468:35

• installer.cjs:350 generateDiff
    recipe-install/node_modules/blitz/dist/installer.cjs:350:42

• task_queues:95 processTicksAndRejections
    node:internal/process/task_queues:95:5
```

## `blitz -v`  output:

```
 Blitz version: 2.0.0-beta.18 (global)
 Blitz version: 2.0.0-beta.18 (local)
 Linux 5.15 | linux-x64 | Node: v18.12.1

 Package manager: npm
  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 1.14 GB / 15.17 GB
    Shell: 3.1.0 - /usr/bin/fish
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 7.21.1 - ~/.npm-global/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.18 => 2.0.0-beta.18 
    @blitzjs/next: 2.0.0-beta.18 => 2.0.0-beta.18 
    @blitzjs/rpc: 2.0.0-beta.18 => 2.0.0-beta.18 
    @prisma/client: 4.6.0 => 4.6.0 
    blitz: 2.0.0-beta.18 => 2.0.0-beta.18 
    next: 12.2.5 => 12.2.5 
    prisma: 4.6.0 => 4.6.0 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.8.4 => 4.9.3
```

**Comment by iamgraeme** [comment]
Still happening, `2.0.0-beta.18` very frustrating as its hindering  me from checking out this framework 😢

**Comment by manstfuu** [comment]
same error.

```
Installed 3 dependencies

  ERROR  The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

 node:fs:592:10

 - Object.openSync (node:fs:592:10)
 - Object.readFileSync (node:fs:468:35)
 -  (recipe-install/node_modules/blitz/dist/installer.cjs:476:44)
 -     at Generator.next (<anonymous>)
 - fulfilled (recipe-install/node_modules/blitz/dist/installer.cjs:437:24)
 - processTicksAndRejections (node:internal/process/task_queues:95:5)

ERROR 
  code: 'ERR_INVALID_ARG_TYPE'
}
error stack:
• node:fs:592 openSync
    node:fs:592:10

• node:fs:468 readFileSync
    node:fs:468:35

• installer.cjs:476 <anonymous>
    recipe-install\node_modules\blitz\dist\installer.cjs:476:44

• installer.cjs:437 fulfilled
    recipe-install\node_modules\blitz\dist\installer.cjs:437:24

• task_queues:95 processTicksAndRejections
    node:internal\process\task_queues:95:5
```

**Comment by stichiboi** [comment]
Still experiencing this issue after a fresh `npm install -g blitz`

Don't know if it's relevant, but I selected the barebones blitz, no auth and no DB

**Comment by 18601673727** [comment]
Still happening on `2.0.0-beta.20`.

**Comment by mhowey** [comment]
Same thing is happening with 2.0.0-beta.22 trying to use the next-ui recipe.

**Comment by mvarchdev** [comment]
Still happening...

**Comment by natanhp** [comment]
> Same issue on Ubuntu 20.04.5 LTS (Focal Fossa)
> 
> ## Steps to reproduce:
> 1. Installed Blitz with `npm install -g blitz`
> 2. Created a new Blitz app with `blitz new mysite`
> 3. cd into the folder
> 4. Attempted to install tailwind with `blitz install tailwind` and stuck on "Generating file diff"
> 
> ## Logs after forcefully exiting the command:
> ```
> Loaded env from /home/newton/Experiments/blitz-site/.env.local
> Loaded env from /home/newton/Experiments/blitz-site/.env
> ✅ Installed 3 dependencies
> 
>   ERROR  The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
> 
>  node:fs:592:10
> 
>  - Object.openSync (node:fs:592:10)
>  - Object.readFileSync (node:fs:468:35)
>  - generateDiff (recipe-install/node_modules/blitz/dist/installer.cjs:350:42)
>  - processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> ERROR 
>  TypeError  The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
> details:
> {
>   code: 'ERR_INVALID_ARG_TYPE'
> }
> error stack:
> • node:fs:592 openSync
>     node:fs:592:10
> 
> • node:fs:468 readFileSync
>     node:fs:468:35
> 
> • installer.cjs:350 generateDiff
>     recipe-install/node_modules/blitz/dist/installer.cjs:350:42
> 
> • task_queues:95 processTicksAndRejections
>     node:internal/process/task_queues:95:5
> ```
> 
> ## `blitz -v` output:
> ```
>  Blitz version: 2.0.0-beta.18 (global)
>  Blitz version: 2.0.0-beta.18 (local)
>  Linux 5.15 | linux-x64 | Node: v18.12.1
> 
>  Package manager: npm
>   System:
>     OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
>     CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
>     Memory: 1.14 GB / 15.17 GB
>     Shell: 3.1.0 - /usr/bin/fish
>   Binaries:
>     Node: 18.12.1 - /usr/bin/node
>     Yarn: 1.22.19 - /usr/bin/yarn
>     npm: 7.21.1 - ~/.npm-global/bin/npm
>   npmPackages:
>     @blitzjs/auth: 2.0.0-beta.18 => 2.0.0-beta.18 
>     @blitzjs/next: 2.0.0-beta.18 => 2.0.0-beta.18 
>     @blitzjs/rpc: 2.0.0-beta.18 => 2.0.0-beta.18 
>     @prisma/client: 4.6.0 => 4.6.0 
>     blitz: 2.0.0-beta.18 => 2.0.0-beta.18 
>     next: 12.2.5 => 12.2.5 
>     prisma: 4.6.0 => 4.6.0 
>     react: 18.2.0 => 18.2.0 
>     react-dom: 18.2.0 => 18.2.0 
>     typescript: ^4.8.4 => 4.9.3
> ```

I am facing the same issue, here's my `blitz -v` output:
```
natanhp@ngoumah ~/D/test (master) [1]> blitz -v
Blitz version: 2.1.1 (global)
Blitz version: 2.1.1 (local)
Linux 6.10 | linux-x64 | Node: v20.11.1


 Package manager: pnpm

  System:
    OS: Linux 6.10 Fedora Linux 39 (Thirty Nine)
    CPU: (12) x64 AMD Ryzen 5 5600G with Radeon Graphics
    Memory: 16.59 GB / 30.72 GB
    Shell: 3.7.0 - /usr/bin/fish
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.1/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
  npmPackages:
    @blitzjs/auth: 2.1.1 => 2.1.1
    @blitzjs/next: 2.1.1 => 2.1.1
    @blitzjs/rpc: 2.1.1 => 2.1.1
    @prisma/client: 5.4.2 => 5.4.2
    blitz: 2.1.1 => 2.1.1
    next: 14.1.4 => 14.1.4
    prisma: 5.4.2 => 5.4.2
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.8.4 => 4.9.5
```

**Comment by JuanQuiro** [comment]
the same thing happens to me

**Comment by learning** [comment]
<img width="451" alt="screenshot" src="https://github.com/user-attachments/assets/e242123d-5f3c-4d7a-981b-cd72c170e69f">

Same issue, #4192
