### ISSUE TITLE
blitz dev + @sentry/nextjs => endless recompile loop

### ISSUE THREAD

**Issue by nickluger** [blitz-js/blitz#3905]
### What is the problem?

When using the CLI command `blitz dev` together with Sentry (the `@sentry/nextjs`) it ends up in a fast-refresh-recompile endless loop.

This does not happen when using `next dev`.

### Paste all your error logs here:

```
41 hot-dev-client.js?1600:159 [Fast Refresh] rebuilding
5 hot-dev-client.js?1600:159 [Fast Refresh] rebuilding
38 hot-dev-client.js?1600:159 [Fast Refresh] rebuilding
```

### Paste all relevant code snippets here:

```js
// next.config.js

// Sentry must be last, to upload correct source maps etc.
module.exports = withSentryConfig(withBlitz(nextConfig), { silent: true });
```

### What are detailed steps to reproduce this?

1. Create a blitz project 
2. Add the latest Sentry Next release (7.15.0). Add `sentry.client.config.ts` and `sentry.server.config.ts` automatically or manually to your project.
4. Add it to the `next.config.js` and use it together with Blitz like:

```js
const { withBlitz } = require("@blitzjs/next");
const { withSentryConfig } = require("@sentry/nextjs");

const nextConfig = {
 // ... other configuration
  sentry: {
    hideSourceMaps: false,
  },
};

module.exports = withSentryConfig(withBlitz(nextConfig));
```
5. Run `next dev` => No problems
6. Run `blitz dev` => See stuff recompile like crazy

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-alpha.59 (global)
Blitz version: 2.0.0-beta.12 (local)
macOS Monterey | darwin-arm64 | Node: v16.18.0


 Package manager: npm

  System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 71.48 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.12 => 2.0.0-beta.12
    @blitzjs/next: 2.0.0-beta.12 => 2.0.0-beta.12
    @blitzjs/rpc: 2.0.0-beta.12 => 2.0.0-beta.12
    @prisma/client: Not Found
    blitz: 2.0.0-beta.12 => 2.0.0-beta.12
    next: 12.2.5 => 12.2.5
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```

### Please include below any other applicable logs and screenshots that show your problem:

Workaround: 

1. Use `next dev`, but I don't know what implications this has on Blitz?
2. Don't use the `withSentryConfig` in dev.

**Comment by dillonraphael** [comment]
Oh interesting. Thanks for catching this. Working on stable release right now, but will definitely look into this.
