### ISSUE TITLE
@blitz/auth secure password prevent auto throwing error

### ISSUE THREAD

**Issue by sharmapukar217** [blitz-js/blitz#3908]
Why is the secure password throwing error automatically when password and hash doesn't match. I think its better to return SecurePasswod status rather than throwing "You are not authorized" error. :-)

**Comment by beerose** [comment]
Thanks for the suggestion! I think we should support both options — throwing and returning result.

**Comment by sharmapukar217** [comment]
Yes that would be best

**Comment by sharmapukar217** [comment]
Any updates on this?

**Comment by beerose** [comment]
It's up for grabs :) It won't be prioritized any time soon to be worked on by the core team, but if someone wants to try it, we can help.

**Comment by sharmapukar217** [comment]
> It's up for grabs :) It won't be prioritized any time soon to be worked on by the core team, but if someone wants to try it, we can help.

I'll be happy to provide the help. Should we be using an option to enable/disable throwing error?
