### ISSUE TITLE
Allow defining routes manifest output directory `.blitz`.

### ISSUE THREAD

**Issue by nickluger** [blitz-js/blitz#3914]
### What do you want and why?

The location of the routes manifest directory `.blitz` should be configurable, similar to Prisma client's output directory, which also per default goes into `node_modules`, but can be changed.

This is important for monorepo directories, for usage with pnpm/yarn2+ workspaces etc. Also, it's currently still not possible to use multiple Blitz apps in a single monorepo because of this. The `.blitz` directory is usually hoisted to the top-level `node_modules` and they would overwrite each other. There's a workaround for yarn classic, but none for pnpm etc. as far as I know.

We talked about this here
https://github.com/blitz-js/legacy-framework/issues/623
and here
https://github.com/blitz-js/legacy-framework/issues/623

but IMHO, configuring the directory is more future-proof & independent of package managers.

### Possible implementation(s)

Add a configuration parameter.

The one issue I see, is that Blitz re-exports the routes manifest from the `.blitz` directory, knowing its location beforehand. 

But a dummy directory is created there anyway, before `blitz codegen` is called directly or indirectly, which could be kept there with a warning message, that you defined a custom directory as output and should import routes from there.

**Comment by beerose** [comment]
Good idea!
