### ISSUE TITLE
Reference Error: React is not defined

### ISSUE THREAD

**Issue by caveman-dev** [blitz-js/blitz#3920]
### What is the problem?

While using primereact with blitz and importing few of the components  for instance InputText  ,it says react is not defined.

### Paste all your error logs here:

```
Uncaught ReferenceError: React is not defined
    at Object.react (main.js?ts=1666259916633:1190:18)
    at options.factory (webpack.js?ts=1666259916633:614:31)
    at __webpack_require__ (webpack.js?ts=1666259916633:37:33)
    at fn (webpack.js?ts=1666259916633:269:21)
    at eval (index.js?46cb:13:39)
    at ./node_modules/next/dist/client/index.js (main.js?ts=1666259916633:478:1)
    at options.factory (webpack.js?ts=1666259916633:614:31)
    at __webpack_require__ (webpack.js?ts=1666259916633:37:33)
    at fn (webpack.js?ts=1666259916633:269:21)
    at eval (next-dev.js?3515:3:9)
```

### Paste all relevant code snippets here:

import { InputText } from "primereact"
import React from "react"

const test = () => {
  return (
    <div>
      <div>hello</div>
      <InputText />
    </div>
  )
}

export default test

### What are detailed steps to reproduce this?

1.create a page in sample blitz project
2.import InputText  from primereact in it then run the project.
3.reload the url of the page 

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.4 (global)
Blitz version: 2.0.0-beta.4 (local)
Windows 10 | win32-x64 | Node: v16.15.1


 Package manager: npm

  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 1.03 GB / 7.84 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.4 => 2.0.0-beta.4
    @blitzjs/next: 2.0.0-beta.4 => 2.0.0-beta.4
    @blitzjs/rpc: 2.0.0-beta.4 => 2.0.0-beta.4
    @prisma/client: 4.0.0 => 4.0.0
    blitz: 2.0.0-beta.4 => 2.0.0-beta.4
    next: 12.2.5 => 12.2.5
    prisma: 4.0.0 => 4.0.0
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.5.3 => 4.8.4
```

### Please include below any other applicable logs and screenshots that show your problem:

![image](https://user-images.githubusercontent.com/72781588/196922291-0e724280-6e5c-4fb1-a988-9f47d15bde2b.png)

after reload
![image](https://user-images.githubusercontent.com/72781588/196922521-61df1408-f4f1-474a-89dd-5aa110bceee9.png)
![image](https://user-images.githubusercontent.com/72781588/196922643-76bbdadc-73ba-475c-8c7d-9915c0fbd0d0.png)

**Comment by dylan10293** [comment]
I am getting the same issue while running with primereact library
