### ISSUE TITLE
Better typesafety on LabeledTextField component

### ISSUE THREAD

**Issue by Braggedtooth** [blitz-js/blitz#3921]
### What do you want and why?
The default Input component is currently not type safe and writing the incorrect name will not provide any error in the linter or browser 

### Additional context

https://discord.com/channels/802917734999523368/1029509375238352936/1029509375238352936
Expected Behavior
![Expected Behavior](https://user-images.githubusercontent.com/54339202/197090384-4567e7d3-72d0-48b6-ac26-4930e19557a0.png)
 Current Behavior
![Current Behavior](https://user-images.githubusercontent.com/54339202/197090387-ed6104ba-9806-4206-829e-2d428fea5ebc.png)

**Comment by beerose** [comment]
Thanks for the issue!
