### ISSUE TITLE
Add from, to params to paginate.ts

### ISSUE THREAD

**Issue by paulm17** [blitz-js/blitz#3923]
### What do you want and why?

Would be nice to have from and to, to the paginate function.  Hasmore is nice, but is more aimed at infinite pagination.  It also would save me a lot of boilerplate.  😓 

### Possible implementation(s)

```
const pageSize = Number(take)
const pageCount = Math.floor((totalCount + take - 1) / take)
const from = (page + 1) * pageCount - (pageCount - 1)
const to = Math.min(from + take - 1, totalCount)
```

### Additional context

This allows for:

![pagination](https://i.imgur.com/frr0YZI.png)

**Comment by dillonraphael** [comment]
This could be helpful. How do you see it? An addition to `usePaginatedQuery`?

**Comment by paulm17** [comment]
Yes exactly.  So from: https://blitzjs.com/docs/use-paginated-query

For projects that support infinite scroll, there is:

> const [{ projects, hasMore }] = usePaginatedQuery(getProjects, {

For projects that want to support pagination: It changes to:

> const [{ projects, pageSize, pageCount, from, to }] = usePaginatedQuery(getProjects, {

The only concern that I have, is whether to support page at zero or one.

**Comment by paulm17** [comment]
Feel free to assign this issue to me.  Since I now have a working instance of Blitz for development.  Happy to submit a PR.

**Comment by flybayer** [comment]
@paulm17 existing paginate utility supports this, unless I'm missing something. I have the same style pagination component with current utility. 

Our `blitz generate page` template has it set up this way where we store the "page" number in the query string: https://github.com/blitz-js/blitz/blob/main/packages/generator/templates/page/index.tsx#L26-L31

`skip` is same as `from` and `to` is replaced by `skip`
