### ISSUE TITLE
Installing blitz recipes on windows fails with yarn global install

### ISSUE THREAD

**Issue by ajduet** [blitz-js/blitz#3924]
### What is the problem?

I installed the blitz cli using yarn global. When attempting to install tailwind recipe, I get an error stating the installer module is not found. This only happens when the cli is installed using yarn global. The recipe installs just fine with npm global.

### Paste all your error logs here:

```
C:\Users\...\Documents\ref_projects\blitz-app> blitz install tailwind               
Loaded env from C:\Users\...\Documents\ref_projects\blitz-app\.env.local
Loaded env from C:\Users\...\Documents\ref_projects\blitz-app\.env
Error: Cannot find module 'install'
Require stack:
- C:\Users\...\Documents\ref_projects\blitz-app\noop.js
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1. I run blitz new.
2. I run blitz install tailwind

### Run `blitz -v` and paste the output here:

version blitz@2.0.0-beta.13
I uninstalled the yarn package to try the npm package and now reinstalling with yarn, its unrecognized as a command, but the version comes from the output of the install process.
```
Blitz version: 2.0.0-beta.13 (global)
Windows 10 | win32-x64 | Node: v16.14.2


 Package manager: npm

  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 AMD Ryzen 7 4700U with Radeon Graphics
    Memory: 3.60 GB / 15.23 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @blitzjs/auth: Not Found
    @blitzjs/next: Not Found
    @blitzjs/rpc: Not Found
    @prisma/client: Not Found
    blitz: Not Found
    next: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```

**Comment by dillonraphael** [comment]
Try the latest beta version which is 15

**Comment by ryanrudd** [comment]
I was also running into this issue and the upgrade to `beta.15` resolved it for me.
