### ISSUE TITLE
Update recipes installer to use either `src` directory or `app` directory

### ISSUE THREAD

**Issue by dillonraphael** [blitz-js/blitz#3934]
NOTE: See what's placed in the current `app` directory and decide weather to support both or have everything in the `src` directory.

**Comment by krishnamauryaext** [comment]
Is this something related to renaming the `app` folder in Blitzjs application? With upgrade to nextjs13, `app` directory becoming the standard folder for lots of feature Next provides.

**Comment by dillonraphael** [comment]
> Is this something related to renaming the `app` folder in Blitzjs application?
> 
> With upgrade to nextjs13, `app` directory becoming the standard folder for lots of feature Next provides.

@krishnamauryaext exactly

**Comment by dillonraphael** [comment]
Doing some more thinking on this:

- `blitz/src/installer/utils/paths.ts` only needs to check if `blitz-server` & `blitz-client` is located in either the `app` directory or `src` directory.
- We should start assuming `mutations`, `queries` & validation files will be in the `src` directory
- Recipe layouts & components should be placed in the `app` directory

Eventually we should consider if recipes are specific to nextjs, remix etc...? Need to think about the best approach for this.

**Comment by flybayer** [comment]
I've seen that most nextjs devs seem to prefer putting all source code in `src` and so would also be using `src/app/`. I don't have a good read currently on if people would want things like components and queries and mutations to be in `src/app/` or not.

However I do think we should switch to putting all code inside `src/` where we use `src/core/components` or `src/app/core/components`
