### ISSUE TITLE
Upgrade tslog for bugfixes

### ISSUE THREAD

**Issue by nickluger** [blitz-js/blitz#3941]
### What is the problem?

Blitz is using an old version of `tslog` which is missing [several bug fixes](https://github.com/fullstack-build/tslog/releases/tag/v3.3.4).

### Paste all your error logs here:

No error logs, just an upgrade request to version `3.3.4` which provides the mentioned bugfixes.

Of course, we can upgrade to the latest version ourselves resolving/overriding Blitz' dependency, but then types no longer match, if you provide or extend the Blitz logger like 

```ts
// needs "any" casts now, if enhancing or modifying the logger
// We for example add Sentry as a transport to the logger
{ logger: enhanceBlitzLogger(BlitzLogger() as any) as any)
```

### Paste all relevant code snippets here:

-

### What are detailed steps to reproduce this?

-

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.13 (local)
macOS Monterey | darwin-arm64 | Node: v16.18.0


 Package manager: npm

  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 80.09 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.19.2 - /usr/local/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.13 => 2.0.0-beta.13
    @blitzjs/next: 2.0.0-beta.13 => 2.0.0-beta.13
    @blitzjs/rpc: 2.0.0-beta.13 => 2.0.0-beta.13
    @prisma/client: Not Found
    blitz: 2.0.0-beta.13 => 2.0.0-beta.13
    next: 12.2.5 => 12.2.5
    prisma: Not Found
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.8.4 => 4.8.4
```

**Comment by dillonraphael** [comment]
Ah ya for sure. Would be nice to have done. Could be a good second issue for someone.
