### ISSUE TITLE
blitz dev > endless fast recompile

### ISSUE THREAD

**Issue by xaronnn** [blitz-js/blitz#3944]
### What is the problem?

Endless fast recompiling while i did nothing.
Used template: TypeScript, Full Auth, Formik

I did not changed anything on template, all is default.

### Paste all your error logs here:

```
There is no errors.
```

### Paste all relevant code snippets here:

```
---
```

### What are detailed steps to reproduce this?

1.---

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.15 (global)
Blitz version: 2.0.0-beta.14 (local)
Windows 10 | win32-x64 | Node: v18.2.0


 Package manager: npm

  System:
    OS: Windows 10 10.0.25182
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 5.26 GB / 31.96 GB
  Binaries:
    Node: 18.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - ~\AppData\Roaming\npm\npm.CMD
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.14 => 2.0.0-beta.14
    @blitzjs/next: 2.0.0-beta.14 => 2.0.0-beta.14
    @blitzjs/rpc: 2.0.0-beta.14 => 2.0.0-beta.14
    @prisma/client: 4.0.0 => 4.0.0
    blitz: 2.0.0-beta.14 => 2.0.0-beta.14
    next: 12.2.5 => 12.2.5
    prisma: 4.0.0 => 4.0.0
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.5.3 => 4.8.4
```

**Comment by flybayer** [comment]
@xaronnn can you share some logs or a loom video or something? Need more info to be able to help :)

**Comment by xaronnn** [comment]
Used Template: TypeScript, Formik, AWS PGSQL, Full Auth

++ only tailwindcss (recipe), classnames installed. 

https://user-images.githubusercontent.com/28219912/200100292-9c8116ed-ceac-4de5-9c54-324146855cf0.mp4

**Comment by flybayer** [comment]
ok that's odd. Can you make a minimal reproduction and share the code?

**Comment by flybayer** [comment]
also try upgrading to latest nextjs and latest blitz!

**Comment by xaronnn** [comment]
> also try upgrading to latest nextjs and latest blitz!

It's fixed in beta.17, what's happened idk but works. It really saved me because of my CPU and RAM dead before update for leak resources. Thanks @flybayer
