### ISSUE TITLE
Prevent page flicker when refreshing page with dark mode theme

### ISSUE THREAD

**Issue by bitabs** [blitz-js/blitz#3948]
### What is the problem?

There is a brief white flicker when refreshing the page. Can only be noticed if your page has a black background.

### Paste all your error logs here:

No logs

### Paste all relevant code snippets here:

N/A

### What are detailed steps to reproduce this?

1. Ensure `<html />` has a black background
2. Refresh the page.
3. You'll notice that there's a white flicker.

### Run `blitz -v` and paste the output here:

N/A

### Please include below any other applicable logs and screenshots that show your problem:

https://user-images.githubusercontent.com/16179773/200094947-48ef7d5d-7b64-445a-bd1c-dad42a769f74.mov

# Resources
1. [Prevent page flash in nextjs with tailwindcss class-based dark-mode](https://stackoverflow.com/questions/71277655/prevent-page-flash-in-next-js-12-with-tailwind-css-class-based-dark-mode)

**Comment by dillonraphael** [comment]
Is this specific to blitz, or more of a nextjs solution that's needed?
