### ISSUE TITLE
[Linux] Retrieving the freshest of dependenciesTypeError

### ISSUE THREAD

**Issue by itranga** [blitz-js/blitz#395]
Retrieving the freshest of dependenciesTypeError: Object.fromEntries is not a function
    at /usr/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/utils/fetch-latest-version-for.js:22:23
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/blitz/node_modules/tslib/tslib.js:110:62)

Ubuntu

**Comment by simonpeterdebbarma** [comment]
@itranga Could you kindly provide more information on the version of node and yarn you are using?

**Comment by flybayer** [comment]
@itranga this should be fixed in `0.8.1` — can you test and verify?

**Comment by itranga** [comment]
"react-native-web": "^0.11.6"
node - v10.20.1
npm - 6.14.4 
yarn - 1.21.1

**Comment by flybayer** [comment]
@itranga did you try Blitz `0.8.1`?

**Comment by itranga** [comment]
blitz -v
You are using alpha software - if you have any problems, please open an issue here:
  https://github.com/blitz-js/blitz/issues/new/choose

Linux 4.15 | linux-x64 | Node: v10.20.1

blitz: 0.8.1 (global)Retrieving the freshest of dependenciesTypeError: Object.fromEntries is not a function
    at /usr/local/share/.config/yarn/global/node_modules/@blitzjs/cli/lib/src/utils/fetch-latest-version-for.js:22:23
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/share/.config/yarn/global/node_modules/tslib/tslib.js:110:62)

**Comment by flybayer** [comment]
I wonder if this is a Node version issue.

Could you test with Node v12?

**Comment by cktang88** [comment]
FWIW, I'm able to run it fine with the newest version.
```
Linux 5.3 | linux-x64 | Node: v14.4.0

blitz: 0.16.4 (global)
blitz: 0.16.4 (local)
```

**Comment by flybayer** [comment]
Thanks @cktang88! I'll go ahead and close it then
