### ISSUE TITLE
Getting Memory Leak on testing

### ISSUE THREAD

**Issue by giandanves** [blitz-js/blitz#3960]
### What is the problem?

I noticed in a medium size and on development application that I'm working with Blitz that there is a memory leak problem while running tests, on this moment we already have 58 test files and we'll have more. When my team try to run all existing tests on our github repo, the memory limit is always exceeding and the Action is failing.

We created a repo with basic tests and duplicated them over and over again to show the problem happening. Each test increases the memory heap and the run finishes taking about 1GB. It looks like something is not being cleaned up after each suite is ran. This tests are realy simple, what make me think that every blitz application should end up with this same problem. On Discord, I [found a discussion](https://discord.com/channels/802917734999523368/976463889522888804/976464608200118314) with a guy reporting the same problem months ago, but an issue was never opened. 

Here's the repository to reproduce the problem: [Memory Leak on testing](https://github.com/giandanves/memory-leak-problem#readme)

### Paste all your error logs here:

```
This bug don't throw and error, but above on prints you can see the memory growing 
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1. Just run ``yarn test`` and see how memory is growing

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.16 (local)
Linux 5.10 | linux-x64 | Node: v16.17.0


 Package manager: npm

  System:
    OS: Linux 5.10 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 4.79 GB / 7.73 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.16 => 2.0.0-beta.16
    @blitzjs/next: 2.0.0-beta.16 => 2.0.0-beta.16
    @blitzjs/rpc: 2.0.0-beta.16 => 2.0.0-beta.16
    @prisma/client: 4.0.0 => 4.0.0
    blitz: 2.0.0-beta.16 => 2.0.0-beta.16
    next: 12.2.5 => 12.2.5
    prisma: 4.0.0 => 4.0.0
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.5.3 => 4.8.4
```

### Please include below any other applicable logs and screenshots that show your problem:

![image](https://user-images.githubusercontent.com/64573088/201176677-d0834c97-ef35-4950-a1fd-1e805b0aeb00.png)

**Comment by dillonraphael** [comment]
Hmm thanks for reporting. Will need some time to debug & investigate what's happening unless someone has an idea. Set this to ready to work on.

**Comment by flybayer** [comment]
@giandanves I suspect this is related to db connection management. Are you using enhancedPrisma like below or something else?

```
const EnhancedPrisma = enhancePrisma(PrismaClient)

export * from "@prisma/client"
const db = new EnhancedPrisma()
export default db
```

**Comment by jhonnymichel** [comment]
Hi @flybayer, the reproduction repository is using blitz's defaults, so it's enhancedPrisma like in your snippet

**Comment by giandanves** [comment]
@flybayer Yeah, we use it both in our work and in the repo I created.
[Here](https://github.com/giandanves/memory-leak-problem/blob/master/db/index.ts) and on [tests.](https://github.com/giandanves/memory-leak-problem/blob/f5284cd4f603f7c74d34bd2127f5151a3614d064/app/users/queries/getUsers.test.ts#L21)
