### ISSUE TITLE
Runtime error after upgrade to beta 15 (and later) because of enhancePrisma

### ISSUE THREAD

**Issue by medihack** [blitz-js/blitz#3964]
### What is the problem?

Upgrading from 2.0.0-beta.14 to 2.0.0-beta.15 (or later) gives me the below runtime error. I see that there was a commit named `Export enhancePrisma from the server entry point`. Do I have to change anything on my site? Also tried to delete `.next` and `node_modules` folder without success.

When I console log `enhancePrisma` in the `db/index.ts` file, it is a function on the server, but `undefined` on the client in beta 15. In beta 14 both were defined. So it seems there is an export issue.

**Update**:
I investigated a bit further. `index-browser.tsx` misses now an export of `enhancePrisma` after this [commit](https://github.com/blitz-js/blitz/commit/1b798d9a03242713517a56793b8e7c51d0fb1130). I see you [had problems](https://github.com/blitz-js/blitz/pull/3928) when importing it in the `index-browser.ts` (I never had those issues with `useSession`), but simply deleting that export isn't the solution.

### Paste all your error logs here:

```
Unhandled Runtime Error
TypeError: (0 , blitz__WEBPACK_IMPORTED_MODULE_0__.enhancePrisma) is not a function

Source
db/index.ts (4:37) @ eval

  2 | import { enhancePrisma } from "blitz"
  3 | 
> 4 | const EnhancedPrisma = enhancePrisma(PrismaClient)
    |                                     ^
  5 | 
  6 | export * from "@prisma/client"
  7 | const db = new EnhancedPrisma()
```

### Paste all relevant code snippets here:

This is how my db/index.ts file looks (nothing special there).
```
import { PrismaClient } from "@prisma/client"
import { enhancePrisma } from "blitz"

const EnhancedPrisma = enhancePrisma(PrismaClient)

export * from "@prisma/client"
const db = new EnhancedPrisma()
export default db
```

### What are detailed steps to reproduce this?

I just upgraded from beta 14 to beta 15. Nothing more.

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.17 (global)
Blitz version: 2.0.0-beta.15 (local)
Linux 5.15 | linux-x64 | Node: v16.16.0


 Package manager: npm

  System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 AMD EPYC 7B13
    Memory: 27.31 GB / 62.80 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.15 => 2.0.0-beta.15 
    @blitzjs/next: 2.0.0-beta.15 => 2.0.0-beta.15 
    @blitzjs/rpc: 2.0.0-beta.15 => 2.0.0-beta.15 
    @prisma/client: ^4.1.1 => 4.6.1 
    blitz: 2.0.0-beta.15 => 2.0.0-beta.15 
    next: ^12.3.2 => 12.3.3 
    prisma: ^4.1.1 => 4.6.1 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: 4.6.3 => 4.6.3
```

**Comment by Daidalos117** [comment]
I have exactly same issue. On v14 everything fine, when upgrading to v15 starts to fail.
