### ISSUE TITLE
Next v13 Error: Cannot read properties of null (reading 'isReady')

### ISSUE THREAD

**Issue by stijnvanderlaan** [blitz-js/blitz#3972]
### What is the problem?

I updated next to 13 & blitz to beta 17, and this resulted in an error at first render:

```
Error: Cannot read properties of null (reading 'isReady')
```

Adding an null check in `useQuery` for the useRouter() return value fixes this for me:

```js
  const routerIsReady = useRouter()?.isReady || isServer && suspenseEnabled;
```

### Paste all your error logs here:

```
react-dom.development.js?3c4a:20662 Uncaught Error: Cannot read properties of null (reading 'isReady')
    at updateDehydratedSuspenseComponent (react-dom.development.js?3c4a:20662:1)
    at updateSuspenseComponent (react-dom.development.js?3c4a:20362:1)
    at beginWork (react-dom.development.js?3c4a:21624:1)
    at beginWork$1 (react-dom.development.js?3c4a:27426:1)
    at performUnitOfWork (react-dom.development.js?3c4a:26557:1)
    at workLoopSync (react-dom.development.js?3c4a:26466:1)
    at renderRootSync (react-dom.development.js?3c4a:26434:1)
    at performConcurrentWorkOnRoot (react-dom.development.js?3c4a:25738:1)
    at workLoop (scheduler.development.js?ba31:266:1)
    at flushWork (scheduler.development.js?ba31:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js?ba31:533:1)
```

### Paste all relevant code snippets here:

Adding an null check in `useQuery` for the useRouter() return value fixes this for me:

```js
  const routerIsReady = useRouter()?.isReady || isServer && suspenseEnabled;
```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
PASTE_HERE (leave the ``` marks)
```

**Comment by stijnvanderlaan** [comment]
Strangely this now does not happen anymore.

**Comment by dillonraphael** [comment]
Is there any specific code causing this? Is it router related?

**Comment by datner** [comment]
`isReady` is deprecated as of next13, are you importing `useRouter` from `'next/navigation'` perchance? 
It was removed because it became irrelevant 

![image](https://user-images.githubusercontent.com/22598347/203440603-d3997093-81b5-48d5-aa54-e4951f477d2a.png)

**Comment by stijnvanderlaan** [comment]
It looks like this error is also happening with next v12.3.4.

**Comment by datner** [comment]
@stijnvanderlaan I can't recreate this bug in any version of next, 13 or otherwise...
Your stack seems to render this question inside suspense, so I tried that too, do you have a reproduction we can use?

**Comment by flybayer** [comment]
@datner @stijnvanderlaan are you both using pnpm?

I'm switching from npm to pnpm and just started seeing this, with nextjs 12.2.5

**Comment by stijnvanderlaan** [comment]
I'm using yarn

**Comment by flybayer** [comment]
try the new release: https://github.com/blitz-js/blitz/releases/tag/v2.0.0-beta.20

**Comment by stijnvanderlaan** [comment]
Yes! This version does not have this problem, thnx!!
