### ISSUE TITLE
Fail to set publicData

### ISSUE THREAD

**Issue by hongfanmeng** [blitz-js/blitz#3973]
### What is the problem?

i set the userId after login without creating a session
```js

export default resolver.pipe(resolver.zod(Login), async ({ code }, ctx) => {
  await ctx.session.$setPublicData({ userId: 1 })
  console.debug(ctx.session.$publicData)
})

```
publicData not set after executing 
```js
{ userId: null }
```

**Comment by dillonraphael** [comment]
I'm not really understanding your issue. Why not use `ctx.session.$create` ?

**Comment by hongfanmeng** [comment]
Isn't it default to using anonymous sessions when not using `ctx.session.$create`?
https://blitzjs.com/docs/session-management#anonymous-sessions

**Comment by hongfanmeng** [comment]
I read the source code and found that setting the userId is not allowed, so in order to use jwt to login without a database session, I need to use another name.
