### ISSUE TITLE
Allow the graceful termination to be manually configurable

### ISSUE THREAD

**Issue by anteprimorac** [blitz-js/blitz#3976]
### What do you want and why?

Currently, cleanup on graceful termination of server process is impossible because blitz CLI exits process on SIGTERM and SIGINT signals.

### Possible implementation(s)

It would be nice to reuse the same env var that next.js has. https://github.com/vercel/next.js/blob/canary/packages/next/bin/next.ts#L116

**Comment by dillonraphael** [comment]
Will label as ready to work on
