### ISSUE TITLE
resolver.authorize types break when using zod (discriminated)union as resolver input 

### ISSUE THREAD

**Issue by dbrxnds** [blitz-js/blitz#3988]
### What is the problem?

When using a union or discriminated union as the `resolver.zod` input, the types of `resolver.authorize` error

https://codesandbox.io/s/distracted-farrell-fpyvkg?file=/app/animals/mutations/createAnimal.ts

### Paste all your error logs here:

-

### Paste all relevant code snippets here:

```ts
const Input = z.discriminatedUnion("status", [
  z.object({ status: z.literal("foo") }),
  z.object({ status: z.literal("bar") })
]);

const ResolverFn = resolver.pipe(
  resolver.zod(Input),
  resolver.authorize(), // Errors
  async (input, ctx) => { 	
})
```

### What are detailed steps to reproduce this?

1. Create zod input with a union / discriminated union
2. Use `resolver.authorize` as second argument to `resolver.pipe`

### Run `blitz -v` and paste the output here:

-

**Comment by dillonraphael** [comment]
A current workaround is:

```ts
const Input = z.object({
  input: z.discriminatedUnion("status", [
    z.object({ status: z.literal("foo") }),
    z.object({ status: z.literal("bar") })
  ])
});
```

But would love to have this accounted for in the `resolver.authorize()` types.
