### ISSUE TITLE
resolver config httpMethod "GET" appends useless superjson data as query params with empty params

### ISSUE THREAD

**Issue by dbrxnds** [blitz-js/blitz#3989]
### What do you want and why?

The option to set the httpMethod for a resolver is nice, but currently it uselessly adds superjson data as the query params for GET requests whenever the params passed are just NULL

### Possible implementation(s)

I think we should check if the passed params are null or undefined, and withhold appending query params whenever that is the case.

### Additional context

Reproduction:
https://codesandbox.io/s/empty-field-o3z1x6?file=/pages/foo.tsx

To check: open network tab on this page and watch the `getFoo` requests
https://o3z1x6.sse.codesandbox.io/foo

**Comment by dillonraphael** [comment]
Thanks for bringing this to our attention @dbrxnds
