### ISSUE TITLE
request for regular blog and release of a roadmap detailing support for Next 13 beta features.

### ISSUE THREAD

**Issue by laurencefass** [blitz-js/blitz#3993]
### What do you want and why?
A blog and a roadmap!

Im currently searching for information relating to support for Next 13 beta features.

The more information the better!

### Possible implementation(s)

How might we do this?
add /blog and /roadmap to your website.

### Additional context
none necessary i thinkl

Thank you.

**Comment by dillonraphael** [comment]
We do have a roadmap in the projects section of Github. Regarding next 13 beta features. We're still doing some internal investigation on how it's going to work, but will definitely document more and include the community through discussions, issues, discord & our twitter.
