### ISSUE TITLE
useQuery no loading/fetching state on parameter change

### ISSUE THREAD

**Issue by nickluger** [blitz-js/blitz#3996]
### The problem
I don't know whether this is intentional, but when using `useQuery` in `suspense` mode, and changing a query parameter, e.g. adding a filter or changing a search query, I'm not able to receive a loading state from `useQuery`.

`isLoading`, `isFetching`, `fetchStatus`, `isPreviousData` etc. all remain `false` or `idle`. 

Alongside, setting `keepPreviousData = false` seems to have no effect at all.

This way, I'm neither able to:

1. Show a loading spinner, while showing the previous data.
2. Nor, to show skeletons (the initial suspense view) while hiding the previous data.

The `isFetching` variable **does** change, though, on the **refetch** of an existing query. 

1. If I navigate away from the tab and then come back (refetch in background), the loading state is shown.
2. If I used a certain set of query parameters before, change to a another set, and then change back to the previous one, the loading state is shown as well.

### Workaround: 
Use `usePaginatedQuery` everywhere.

For some reason everything works fine, when using `usePaginatedQuery` (except for `keepPreviousData = false`, of course, but I assume, that's intentional). At least `isFetching` is flipping to `true`, though, when changing query params here.

### What I need

I expected query parameter changes to change the underlying cache key passed to `react-query`. 

Receiving correct values for `isRefetching`, `isFetching` `isPreviousData`,  I should also be able to decide, whether to just show a "loading-in-the-background-spinner" or hide the current result due to some parameter change, like a different search query.

### Paste all your error logs here:

No logs

### Paste all relevant code snippets here:

see above

### What are detailed steps to reproduce this?

1. Create a `useQuery` with any changeable parameter.
2. Log `isFetching` and friends to the console.
3. Change the parameter.
4. Watch `isFetching` and friends (see above). 

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.19 (local)
macOS Monterey | darwin-arm64 | Node: v16.18.0


 Package manager: npm

  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 68.42 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.19.2 - /usr/local/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.19 => 2.0.0-beta.19
    @blitzjs/next: 2.0.0-beta.19 => 2.0.0-beta.19
    @blitzjs/rpc: 2.0.0-beta.19 => 2.0.0-beta.19
    @prisma/client: Not Found
    blitz: 2.0.0-beta.19 => 2.0.0-beta.19
    next: 12.2.5 => 12.2.5
    prisma: Not Found
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.8.4 => 4.8.4
```

**Comment by dillonraphael** [comment]
Thanks for reporting @nickluger. Will take a look.
