### ISSUE TITLE
Update USER_GUIDE.md to include instructions on how to generate a plain JS project

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#400]
### What do you want and why?

We added `blitz new myapp --js` in `0.8.0`, so we now need to update the user guide so it shows how to generate both a JS and TS project.

**Comment by tmns** [comment]
I can do this!

**Comment by simonpeterdebbarma** [comment]
@tmns Thank you for taking on this issue! We appreciate it a lot.

**Comment by tmns** [comment]
@simonpeterdebbarma My pleasure! I hope my changes are okay with you all!

**Comment by simonpeterdebbarma** [comment]
@tmns Absolutely! We appreciate every line of code. You are officially a Contributor (you'll see yourself on the main README.md) and we would love to see more from you.
