### ISSUE TITLE
codegen does not work when version format is like "~12.3.3"

### ISSUE THREAD

**Issue by stijnvanderlaan** [blitz-js/blitz#4000]
### What is the problem?

The code gen check for version 12 or 13 but does not take in account for the "~" format.

### Paste all your error logs here:

```
The server could not finish this Suspense boundary, likely due to an error during server rendering. Switched to client rendering.
```

### Paste all relevant code snippets here:

```
if (nextVersion && nextVersion.startsWith("12")) {
```
Should be more like:
```
if (nextVersion && (nextVersion.startsWith("12") || nextVersion.startsWith("~12"))) {
```

### What are detailed steps to reproduce this?

Use next version `"~12.3.3"`

### Run `blitz -v` and paste the output here:

^2.0.0-beta.19

**Comment by dillonraphael** [comment]
Good catch. Will label this as ready to work on.
