### ISSUE TITLE
BlitzServerMiddleware has `any` types

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#4001]
### What is the problem?

BlitzServerMiddleware has `any` as the type for `req`, `res, and `next`

```ts
    BlitzServerMiddleware(async (req, res, next) => {
    }),
```

### To Fix

[This code](https://github.com/blitz-js/blitz/blob/main/packages/blitz/src/index-server.ts#L61-L67) needs fixed. The `middleware` argument should be `RequestMiddleware` instead of using a generic

**Comment by ETLopes** [comment]
Does it makes sense to be this way?

```
export const BlitzServerMiddleware = <
  TRequest extends IncomingMessage = IncomingMessage,
  TResponse extends ServerResponse = ServerResponse,
  TMiddleware extends RequestMiddleware<TRequest, TResponse> = RequestMiddleware<TRequest, TResponse>,
>(
  middleware: TMiddleware,
): BlitzServerPlugin => ({
  requestMiddlewares: [middleware],
})
```
