### ISSUE TITLE
`blitz db reset` failing with `cannot find module`

### ISSUE THREAD

**Issue by hauptrolle** [blitz-js/blitz#401]
### What is the problem?

When running `blitz db reset` I get the following error: `Error: Cannot find module '/Users/user.name/workspace/private/blitz-project/db'`

### Steps to Reproduce:

1. Setup blitz project
2. Run `blitz db reset`

### Versions:

```
macOS Catalina darwin-x64 node-v12.14.1

blitz: 0.6.1 (global)
blitz: 0.8.1 (local)
```

**Comment by Skn0tt** [comment]
Thanks for taking the time to report, it's very much appreciated ☺️

**Comment by Skn0tt** [comment]
Thanks for taking the time to report, it's very much appreciated ☺️

**Comment by johncantrell97** [comment]
Also seeing this, I'll take a stab at fixing it.

**Comment by Skn0tt** [comment]
Awesome! Let me us know if there's something we can help you with.
