### ISSUE TITLE
Rendering Suspense code mod not working and needed (by adding a message) anymore for newest next version 13.0.7

### ISSUE THREAD

**Issue by stijnvanderlaan** [blitz-js/blitz#4014]
### What is the problem?

The suspense error codemod on next is not working anymore, but the good news is, they added a check: 
When the message is the value of NEXT_DYNAMIC_NO_SSR_CODE (inside next/dist/shared/lib/no-ssr-error) it will not throw, so adding it will fix it, like so:

```ts
const e = new Error();
e.message = "DYNAMIC_SERVER_USAGE"
e.name = "Rendering Suspense fallback...";
delete e.stack;
throw e;
```

**Comment by dillonraphael** [comment]
@stijnvanderlaan I'm looking more into this. Not 100% sure how setting `e.message = "DYNAMIC_SERVER_USAGE"` at https://github.com/blitz-js/blitz/blob/a4294ad29ce721fc53b153499e068f175b6c1d40/packages/blitz-rpc/src/data-client/react-query.tsx#L97 will fix this

**Comment by stijnvanderlaan** [comment]
In the newest version of next they added an onRecoverableError:
https://github.com/vercel/next.js/blob/canary/packages/next/client/index.tsx#L510
https://github.com/vercel/next.js/blob/canary/packages/next/client/on-recoverable-error.ts#L3

Which checks for a message with the value "DYNAMIC_SERVER_USAGE" to not throw:
https://github.com/vercel/next.js/blob/canary/packages/next/shared/lib/no-ssr-error.ts

**Comment by dillonraphael** [comment]
@stijnvanderlaan Yup, but seems to we need to do `e.digest = "DYNAMIC_SERVER_USAGE"` not `e.message`

**Comment by stijnvanderlaan** [comment]
In a previous version it was message
