### ISSUE TITLE
Tailwind template: Install in `/src` directory

### ISSUE THREAD

**Issue by tordans** [blitz-js/blitz#4020]
### What is the problem?

When using the tailwindcss recipe on a new blitz app, the `styles/index.css` file is place in `/app/core/styles/index.css`.

It should be in `/src/core/styles/index.css` instead.

It looks like the folder is hard coded in https://github.com/blitz-js/blitz/blob/main/recipes/tailwind/index.ts#LL32C5-L32C5.

I am new to Blitz, so a few questions about this

- I take it that at some point recently the primary folder change from `/app` to `/src` and I assume that is because Next 13 now has a `/app` folder. Is there some place that talks about this change and maybe open todos on that?
- I see that there are more recipes that are still targeting the app folder https://github.com/search?q=repo%3Ablitz-js%2Fblitz%20app%2Fcore&type=code. Should those be updated as well?
- I there a way from within the recipe to extract the currently used folder (`app` or `src`) and use that? Because hard coding the new conventions will break the recipes for "legacy folder apps", right? It looks like https://github.com/blitz-js/blitz/commit/5ea068b28b010269ce55079982699ec5d21fc5fc is doing this, but not for the recipes steps, right?
- While we are on the topic of Tailwind, I think https://github.com/blitz-js/blitz/blob/0025856b9e5bc3370f5b3dc34a3fbe95cd0c0fda/recipes/tailwind/templates/config/tailwind.config.js#L3 should change as well, right? I changed it to `  content: ["./src/**/*.{js,ts,jsx,tsx}"],` for my app and that works fine as far as I can see…

I can create PRs for some of those changes, but would like some guidance by people who know more about it, first.

### Paste all your error logs here:

-

### Paste all relevant code snippets here:

-

### What are detailed steps to reproduce this?

-

### Run `blitz -v` and paste the output here:

```
% blitz -v
blitz -v
Blitz version: 2.0.0-beta.20 (global)
Blitz version: 2.0.0-beta.20 (local)
macOS Ventura | darwin-arm64 | Node: v18.8.0


 Package manager: npm

  System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 28.55 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    Yarn: Not Found
    npm: 8.18.0 - ~/.nvm/versions/node/v18.8.0/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.20 => 2.0.0-beta.20
    @blitzjs/next: 2.0.0-beta.20 => 2.0.0-beta.20
    @blitzjs/rpc: 2.0.0-beta.20 => 2.0.0-beta.20
    @prisma/client: 4.6.0 => 4.6.0
    blitz: 2.0.0-beta.20 => 2.0.0-beta.20
    next: 12.2.5 => 12.2.5
    prisma: 4.6.0 => 4.6.0
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.8.4 => 4.9.4
```

**Comment by dillonraphael** [comment]
Hey @tordans, we have an installer utility file that determines `app` or `src` directory. In a matter of fact there is a PR open to fix this exact issue https://github.com/blitz-js/blitz/pull/3997
