### ISSUE TITLE
`blitz g` with brackets can break the cli

### ISSUE THREAD

**Issue by tordans** [blitz-js/blitz#4021]
### What is the problem?

**This is what I get after breaking thinks:**

```
% blitz help
blitz:22: command not found: endAt:dateTime
% blitz g all post title:string author:string content:string
blitz:23: command not found: endAt:dateTime
% blitz help
blitz:24: command not found: endAt:dateTime
```

**This is likely how I broke thinks…**

I suspect the `now()` caused the issue.

```
blitz generate all date startAt:dateTime:default=now() endAt:dateTime title:string locationName:string locationUrl:string description:string id:uuid --dry-run 
```

**How _not_ to fix this…**

- `npm uninstall -g blitz`, then reinstall does not help
- force-cleaning the npm cache does not help
- removing `node_modues`, then reinstalling all does not help

**How to fix it:**

I had to remove files in a npm temp folder, which "cached" broken code.

```
// 
$ echo TMPDIR
/var/folders/_2/w9vhc5hx1fg2vfmnypv3wvmm0000gp/T/
    
% cd $TMPDIR
% cd node-jiti
% ls
  blitz-auth-build.config.ts.42bb7c8e.js
  blitz-build.config.ts.531e0b43.js
  blitz-next-build.config.ts.b5eaaddf.js
  blitz-rpc-build.config.ts.f41b01c7.js
  codemod-build.config.ts.8d2cf2eb.js
  generator-build.config.ts.515f44ba.js
  pkg-template-build.config.ts.40d86f9a.js
    
$ cat pkg-template-build.config.ts.40d86f9a.js

"use strict"; Object.defineProperty(exports, "__esModule", { value: true }); exports.default = void 0;

const config = {
  entries: ["./src/index-browser", "./src/index-server"],
  externals: ["index-browser.cjs", "index-browser.mjs", "react"],
  declaration: true,
  rollup: {
    emitCJS: true,
    esbuild: {
      target: ["es2015"] } } };var _default =



config; exports.default = _default; /* v7-eb5970095fe3c5ea */

$ cat /private/var/folders/_2/w9vhc5hx1fg2vfmnypv3wvmm0000gp/T/node-jiti/generator-build.config.ts.515f44ba.js

"use strict";Object.defineProperty(exports, "__esModule", { value: true });exports.default = void 0;

const config = {
  entries: ["./src/index"],
  externals: ["react"],
  declaration: true,
  rollup: {
    emitCJS: true,
    esbuild: {
      target: ["es2015"] } } };var _default =



config;exports.default = _default; /* v7-5f8f751e7d033013 */
```

Other blitz files hold the same content.
Once I removed them all, blitz started working again.

----

A quick fix could be to make sure only allow-listed characters (`A-Za-z-_:=`, but no `()` etc) are processed by the generator. I peeked at https://github.com/blitz-js/blitz/blob/main/packages/blitz/src/cli/commands/generate.ts but could not see where to do this…

### Paste all your error logs here:

See above.

### Paste all relevant code snippets here:

See above.

### What are detailed steps to reproduce this?

See above.

### Run `blitz -v` and paste the output here:

```
% blit
z --version
Blitz version: 2.0.0-beta.20 (global)
Blitz version: 2.0.0-beta.20 (local)
macOS Ventura | darwin-arm64 | Node: v18.8.0


 Package manager: npm

  System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 83.39 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    Yarn: Not Found
    npm: 8.18.0 - ~/.nvm/versions/node/v18.8.0/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.20 => 2.0.0-beta.20
    @blitzjs/next: 2.0.0-beta.20 => 2.0.0-beta.20
    @blitzjs/rpc: 2.0.0-beta.20 => 2.0.0-beta.20
    @prisma/client: 4.6.0 => 4.6.0
    blitz: 2.0.0-beta.20 => 2.0.0-beta.20
    next: 12.2.5 => 12.2.5
    prisma: 4.6.0 => 4.6.0
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.8.4 => 4.9.4
```

**Comment by Vandivier** [comment]
simple fix suggestion would be for `blitz g` to throw if `()` is encountered within-command

for a much stronger validation can we agree to limit field substrings like `endAt:dateTime` to be alpha-only? (ofc allowing the colon too, but i believe that gets split out in the parser so a validation regex could be alpha-only)

**Comment by dillonraphael** [comment]
@tordans Regarding where we could potentially make a check for special characters would be right here https://github.com/blitz-js/blitz/blob/a4294ad29ce721fc53b153499e068f175b6c1d40/packages/generator/src/generators/model-generator.ts#L63

**Comment by tordans** [comment]
Thanks, I created https://github.com/blitz-js/blitz/pull/4024 to address this. Looking forward to you thorough  review :-).
