### ISSUE TITLE
Console not working when using a mono repo

### ISSUE THREAD

**Issue by stijnvanderlaan** [blitz-js/blitz#4036]
### What is the problem?

Console is not working on an mono repo, where prisma is on another package.
First I get:
```
Error: db/schema.prisma does not exist and Prisma configuration not found in package.json. Please either create the db folder or add the prisma schema path to the package.json
```

When I add the following to my package.json:
```
  "prisma": {
    "schema": "../../packages/db/schema.prisma"
  },
```
It's shows the following:
```
- Use your db like this: ...project.findMany()
- Use your queries/mutations like this: getProjects({})
```

Also a workaround like, results in errors.
```
  "prisma": {
    "schema": "db/../../../packages/db/schema.prisma"
  },
```

### Paste all your error logs here:

([path] is the full path to the project directory)
```
Failed to load [path]/apps: Error: Cannot find module '[path]/apps/web/db'
Require stack:
```

Trying to access db always results in:
```
Uncaught ReferenceError: db is not defined
```

### Run `blitz -v` and paste the output here:

```
2.0.0-beta.20
```

**Comment by siddhsuresh** [comment]
Hey @stijnvanderlaan, thanks for the find! 
Yes, currently the console is not yet configured to search beyond the root directory. The required lines to be changed to add this functionality is at https://github.com/blitz-js/blitz/blob/145d5a02b35325ca8a51d2ae7ac06fd913ded8a6/packages/blitz/src/cli/utils/next-console.ts#L79-L91
