### ISSUE TITLE
Bug: Dependent Queries do not work with useQuery() 

### ISSUE THREAD

**Issue by MrLeebo** [blitz-js/blitz#404]
### What do you want and why?

I want to be able to implement a [Dependent Query](https://github.com/tannerlinsley/react-query#dependent-queries) using blitz useQuery(), but the query key is internally managed

I want this because sometimes my params are state-dependent

```ts
const [profile, setProfile] = useState(null)

// I don't want this to run until a profile is selected
useQuery(getHistory, { userId: profile.id })
```

### Possible implementation(s)

Use a query key function and allow `params` to be a function, perhaps?

```ts
const [profile, setProfile] = useState(null)

// if profile is null, the query key function will throw, canceling the query
useQuery(getHistory, () => ({ userId: profile.id }))
```

### Additional context

https://github.com/tannerlinsley/react-query#dependent-queries

**Comment by Skn0tt** [comment]
> If a query isn’t ready to be requested yet, just pass a falsy value as the query key or as an item in the query key:
> ~ React Query Docs

Judging from this and [our sources](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/use-query.ts#L36), dependent queries should be possible by passing a falsy value for params.
I don’t feel like this is convenient though, since people may want to pass null etc. for params for legitimate reasons.

Having said that, I quite like your suggestion with the throwing param suppliers!

**Comment by bobzoller** [comment]
Dependent Queries are called out in blitz-js/blitz#89 (note the lack of a _not implemented_ label?), but I came here looking because they don't seem to work --- which is to say if I pass a function that throws or a falsy value for params, the RPC still fires.

blitz@0.6.3

**Comment by Skn0tt** [comment]
Good catch! That's definitely a bug then.
So if someone wants to provide a PR for this, this is where you'd have to look:
https://github.com/blitz-js/blitz/blob/2c9e8e131889e6e323dd94f408b31295dd65fcca/packages/core/src/use-query.ts#L41

**Comment by flybayer** [comment]
## Update

Yes, this is indeed a bug. It should work exactly like @MrLeebo expected with:

```
const [profile, setProfile] = useState(null)

// if profile is null, the query key function will throw, canceling the query
useQuery(getHistory, () => ({ userId: profile.id }))
```
