### ISSUE TITLE
sessionMiddleware is not a function

### ISSUE THREAD

**Issue by oyatek** [blitz-js/blitz#4040]
### What is the problem?

Docs on upgrading to v2.0 state that `sessionMiddleware` was moved from `blitz` to `@blitzjs/auth`: [https://blitzjs.com/docs/upgrading-from-framework#manual-upgrade-steps](https://blitzjs.com/docs/upgrading-from-framework#manual-upgrade-steps)

But `sessionMiddleware` is not available in either `blitz` or `@blitzjs/auth`. I'm testing on a fresh blitz install.

Docs on `sessionMiddleware` seem to be outdated: https://blitzjs.com/docs/authorization#is-authorized-adapters

### Paste all your error logs here:

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
TypeError: sessionMiddleware is not a function
```

### Paste all relevant code snippets here:

```
const { sessionMiddleware, simpleRolesIsAuthorized } = require("@blitzjs/auth")
// ALSO TRIED:
// const { sessionMiddleware, simpleRolesIsAuthorized } = require("blitz")

// <...>

const config = {
  middleware: [
    sessionMiddleware({
      cookiePrefix: "testApp",
      isAuthorized: simpleRolesIsAuthorized,
    }),
  ],
  pageExtensions: ["ts", "tsx", "md", "mdx"],  
}
```

### What are detailed steps to reproduce this?

1. Install fresh blitzjs app
2. Add `sessionMiddleware` use to `next.config.js`
3. run `blitz dev`

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.21 (global)
Blitz version: 2.0.0-beta.21 (local)
macOS Big Sur | darwin-arm64 | Node: v16.14.2


 Package manager: npm

  System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 81.67 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/.npm-global/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.21 => 2.0.0-beta.21 
    @blitzjs/next: 2.0.0-beta.21 => 2.0.0-beta.21 
    @blitzjs/rpc: 2.0.0-beta.21 => 2.0.0-beta.21 
    @prisma/client: 4.6.0 => 4.6.0 
    blitz: 2.0.0-beta.21 => 2.0.0-beta.21 
    next: 12.2.5 => 12.2.5 
    prisma: 4.6.0 => 4.6.0 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.8.4 => 4.9.4 

```

**Comment by oyatek** [comment]
also I tried to search for `sessionMiddleware` string through all `node_modules` and didn't find an exact match.

**Comment by siddhsuresh** [comment]
Hey @oyatek, regarding the code snippet given, configuration for those fields in v2.0 is done using the `blitz-server` and `blitz-client` files and has been removed from the `next|blitz.config.js` file.

For isAuthorized:
```diff
// src/blitz-server.ts
import { setupBlitzServer } from '@blitzjs/next';
import { AuthServerPlugin, PrismaStorage } from '@blitzjs/auth';
import { simpleRolesIsAuthorized } from '@blitzjs/auth';
import { BlitzLogger } from 'blitz';
import db from 'db';
import { authConfig } from './blitz-client';

export const { gSSP, gSP, api } = setupBlitzServer({
	plugins: [
		AuthServerPlugin({
			...authConfig,
			storage: PrismaStorage(db),
+			isAuthorized: simpleRolesIsAuthorized
		})
	],
	logger: BlitzLogger({})
});
```
and for cookiePrefex:
```diff
// src/blitz-client.ts
import { AuthClientPlugin } from "@blitzjs/auth"
import { setupBlitzClient } from "@blitzjs/next"
import { BlitzRpcPlugin } from "@blitzjs/rpc"

export const authConfig = {
+  cookiePrefix: "__safeNameSlug__"
}

export const { withBlitz } = setupBlitzClient({
  plugins: [
    AuthClientPlugin(authConfig),
    BlitzRpcPlugin({}),
  ],
})
```
I will label it as ready to work on to fix the docs.

**Comment by oyatek** [comment]
Thank you, I managed to fix it. The problem was in the outdated docs. I have found a lot more problems in the docs regarding 0.45>2.0 migration, I will add another issue now that I can't solve.
