### ISSUE TITLE
Error in the 2.0 migration docs: invokeWithMiddlware from @blitzjs/rpc is not available 

### ISSUE THREAD

**Issue by oyatek** [blitz-js/blitz#4041]
### What is the problem?

I'm migrating from v0.45. 

I've been using mutations/queries in API endpoints via `invokeWithMiddlware`.

The migration docs from 0.45 to 2.0 state that `invokeWithMiddlware` is now available in `@blitzjs/rpc` but it's not. 

What is the correct way nowadays to use mutations/queries in API endpoints? I tried to search in the docs but couldn't find the answer. In past, there was clear instruction about using `invokeWithMiddlware` but now there's nothing on that topic.

### Paste all your error logs here:

```
import { invokeWithMiddleware } from "@blitzjs/rpc"
```

### Paste all relevant code snippets here:

```
none
```

### What are detailed steps to reproduce this?

1. Create an API endpoint
2. Try to use mutatation via `invokeWithMiddleware`

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.21 (global)
Blitz version: 2.0.0-beta.21 (local)
macOS Big Sur | darwin-arm64 | Node: v16.14.2


 Package manager: npm

  System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 100.78 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/.npm-global/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.21 => 2.0.0-beta.21 
    @blitzjs/next: 2.0.0-beta.21 => 2.0.0-beta.21 
    @blitzjs/rpc: 2.0.0-beta.21 => 2.0.0-beta.21 
    @prisma/client: 3.7.0 => 3.7.0 
    blitz: 2.0.0-beta.21 => 2.0.0-beta.21 
    next: 12.2.0 => 12.2.0 
    prisma: 3.7.0 => 3.7.0 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ~4.5 => 4.5.5 

```

**Comment by oyatek** [comment]
I just checked the @blitzjs/rpc - is it now called `invokeWithCtx` ?

**Comment by siddhsuresh** [comment]
Hey @oyatek, The requirement of `invokeWithMiddleware` is no longer required in `gSSP`, you can call it resolver directly like in https://github.com/blitz-js/blitz/pull/3764. Didn't the codemod not update them, since it was added in that PR?

**Comment by oyatek** [comment]
thank you!
