### ISSUE TITLE
[Linux] fetchRemote.sh script fails when interpreted with non-bash shell

### ISSUE THREAD

**Issue by tmns** [blitz-js/blitz#405]
### What is the problem?

When running `./scripts/fetchRemote.sh` as per the [contributing docs](https://github.com/blitz-js/blitz/blob/canary/CONTRIBUTING.md#sync-your-fork) with `sh` (and `dash` and possibly other shells?), the script errors out with a `[[: not found` error:

```bash
$ ./scripts/fetchRemote.sh 
./scripts/fetchRemote.sh: 5: ./scripts/fetchRemote.sh: [[: not found
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

This is due to the first line of the script being `!#/bin/sh`, which [does not understand `[[` in `if` statements](https://stackoverflow.com/a/3401197). In turn, this can be fixed by either changing the line to `!#/bin/bash` or by making the script `sh` compatible.

### Steps to Reproduce:

1. Attempt to run `fetchRemote.sh` with `sh` or another non-compatible shell

### Versions:

```
Linux 4.13 | linux-x64 | Node: v12.3.1

blitz: 0.8.1 (global)
blitz: 0.8.1 (local)

```

### Supporting Documentation
* https://github.com/blitz-js/blitz/blob/canary/CONTRIBUTING.md#sync-your-fork
* https://stackoverflow.com/questions/3401183/bash-syntax-error-not-found

*Note: I edited this to more accurately reflect the issue of the problem, which occurs regardless if `upstream` is set, as long as a non compatible shell is used.*

**Comment by Zeko369** [comment]
I forgot that's a bashism, could we maybe refactor that into something else?

**Comment by Zeko369** [comment]
@tmns Could you run `ls -l /bin/sh` and copy the output here, I want to know which shell is default on your system

**Comment by tmns** [comment]
Hi @Zeko369! Yes, this can also be refactored to just using single brackets, like so:

```
if [ $(git remote -v | grep 'upstream' | wc -l) -eq 0 ]; then
  echo "Upstream remote not found, adding one"
  git remote add upstream https://github.com/blitz-js/blitz.git
fi
```

And as for the default shell, it looks like `dash`:
```
ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Ιούν 19  2018 /bin/sh -> dash
```

**Comment by Zeko369** [comment]
DAMN YOU DASH.

Also you can add `=` instead of `-eq` because I think that chsh fails with that, or some other random shell

**Comment by Zeko369** [comment]
Ping me to try it on macOS when you add that (and add back /bin/sh)

**Comment by tmns** [comment]
Yes, also what about combining it with the use of `test` instead of brackets all together, like so:

```
if test "$(git remote -v | grep 'upstream' | wc -l)" = 0; then
  echo "Upstream remote not found, adding one"
  git remote add upstream https://github.com/blitz-js/blitz.git
fi
```
