### ISSUE TITLE
Error: ... @blitzjs/auth plugin is not initialized. Ensure it is installed and the auth plugin is added to setupBlitzServer()

### ISSUE THREAD

**Issue by oyatek** [blitz-js/blitz#4056]
### What is the problem?

I have an API endpoint, that calls a mutation, that uses `resolver.authorize()`. I get the following error.

### Paste all your error logs here:

```
Error: You are using the resolver.authorize() function, but `@blitzjs/auth` plugin is not initialized. Ensure it is installed and the auth plugin is added to setupBlitzServer()
```

### Paste all relevant code snippets here:

mutation: 
```
export default resolver.pipe(
  resolver.zod(TransactionModel.pick({ id: true })),
  resolver.authorize(),
  async ({ id }, ctx) => {
    // code here <...>
  }
)

```

blitz-server.ts:
```
import { setupBlitzServer } from "@blitzjs/next"
import { AuthServerPlugin, PrismaStorage, simpleRolesIsAuthorized } from "@blitzjs/auth"
import db from "db"

const { gSSP, gSP, api } = setupBlitzServer({
  plugins: [
    AuthServerPlugin({
      cookiePrefix: "leela",
      storage: PrismaStorage(db),
      isAuthorized: simpleRolesIsAuthorized,
    }),
  ],
})

export { gSSP, gSP, api }

```

### What are detailed steps to reproduce this?

1. Create an API endpoint
2. Try to call a mutation or query that uses `resolver.authorize()`

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.22 (global)
Blitz version: 2.0.0-beta.21 (local)
Linux 5.4 | linux-x64 | Node: v16.15.0


 Package manager: npm

  System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (1) x64 AMD EPYC Processor
    Memory: 4.88 GB / 5.80 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.npm-global/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.21 => 2.0.0-beta.21 
    @blitzjs/next: 2.0.0-beta.21 => 2.0.0-beta.21 
    @blitzjs/rpc: 2.0.0-beta.21 => 2.0.0-beta.21 
    @prisma/client: 3.7.0 => 3.7.0 
    blitz: 2.0.0-beta.21 => 2.0.0-beta.21 
    next: 12.2.5 => 12.2.5 
    prisma: 3.7.0 => 3.7.0 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ~4.5 => 4.5.5
```

**Comment by siddhsuresh** [comment]
Hey @oyatek, I am not able to replicate this on my end. 
Can you also confirm that you have placed the 
```ts
AuthClientPlugin({
  cookiePrefix: "web-cookie-prefix",
}),
```
in the blitz-client.ts file?
Can you make a minimal reproduction of this, if this doesn't work?

**Comment by oyatek** [comment]
I tried to create a fresh Blitz App and I'm still getting the error.

Steps to reproduce:
1. Create a new Blitz App
2. Create a file `/src/pages/api/test.ts`
3. Copy-paste the code below into the created file:
```
import { api } from "src/blitz-server"
import { NextApiRequest, NextApiResponse, NextApiHandler } from "next"
import changePassword from "../../auth/mutations/changePassword"

const handler: NextApiHandler = async (req: NextApiRequest, res: NextApiResponse) => {

  await changePassword({currentPassword: "fooasdasd", newPassword: "fooasdasd123123"}, {req, res})

  res.statusCode = 200
  res.setHeader("Content-Type", "application/json")
  res.end(JSON.stringify({ status: "OK" }))
}
export default api(handler)
```
4. run `blitz dev`
5. Open the browser and enter URL `/api/test/`
6. You should see the error in the browser

> Can you make a minimal reproduction of this, if this doesn't work?

What's the best way of doing that? Should I create a repo on Github?

> are you able to use the other features of blitz auth?

I'm able to use blitz auth (useSession) in Components, but it seems to be not working on the server when API endpoint is called.

**Comment by oyatek** [comment]
Maybe I'm using API endpoints incorrectly? I've migrated from v0.45 recently and I'm still learning how blitz v2 works. Maybe I'm using API endpoints in an old way?

**Comment by oyatek** [comment]
I think I've found the source of the problem. This is the new syntax, right? - 
```
import { api } from "src/blitz-server"
import db from "db"

export default api(async (_req, res, ctx) => {
  ctx.session.$authorize()
  const publicData = ctx.session.$publicData

  res.status(200).json({
    userId: ctx.session.userId,
    publicData: { ...publicData },
  })
})
```

**Comment by oyatek** [comment]
Yes, I was using the old syntax for API endpoints. I've found how it should be done now in the blitz docs.
