### ISSUE TITLE
Enhancements for Blitz linting

### ISSUE THREAD

**Issue by kumarasinghe** [blitz-js/blitz#4064]
### What do you want and why?

Firstly, thank you for making Blitz! I want to point out few things regarding the default installation.
- The current eslint configuration seems to lack some sensible defaults 
- There is no linter provided to lint CSS/SCSS.

### Possible implementation(s)

Nice to have eslint tweaks:
```js
// @blitzjs/next/eslint.js
       ...
        "extends": [
                "eslint:recommended",
                "plugin:react/recommended",
                "plugin:react-hooks/recommended",
                "plugin:@typescript-eslint/recommended",
                "plugin:jsx-a11y/strict",
                "prettier",
                "plugin:@next/next/recommended"
        ],
        "plugins": ["react", "react-hooks", "@typescript-eslint", "jsx-a11y"],
        ....

```
Add a CSS linter like stylint for the default installation:
```js
// .stylelintrc.json
{
        "extends": ["stylelint-config-standard-scss", "stylelint-config-prettier-scss"]
}

```

How might we do this?

If this makes sense I can do a PR.

**Comment by flybayer** [comment]
hey @kumarasinghe thank you for the suggestions! 

We already have almost all of these in the current eslint config, is it not working for you?

We don't have scss plugin, but since we don't have scss support set up by default, so I don't think it makes sense to include the eslint rule by default.
