### ISSUE TITLE
Invalid <Link> error on brand new generated project with blitz@2.0.0-beta.22

### ISSUE THREAD

**Issue by jorgepvenegas** [blitz-js/blitz#4066]
### What is the problem?

After starting a brand new project through the CLI, I'm having issues with nested `<a>` in `<Link>` elements.

### Paste all your error logs here:

```
PASTE_HERE (leave the ``` marks)
```

### Paste all relevant code snippets here:

```
Unhandled Runtime Error

Error: Invalid <Link> with <a> child. Please remove <a> or use <Link legacyBehavior>.
Learn more: https://nextjs.org/docs/messages/invalid-new-link-with-extra-anchor
```

Removing the nested `<a>...</a>` seems to fix the issue. But then I see 

```
Unhandled Runtime Error

Error: Text content does not match server-rendered HTML.

See more info here: https://nextjs.org/docs/messages/react-hydration-error
```

### What are detailed steps to reproduce this?

I'm following the steps from https://blitzjs.com/docs/get-started:
1. Installed Blitz globally with `yarn global add blitz`.
2. Created a new app with all the recommended choices.
3. Started the dev server with `blitz dev`.
4. Navigated to `http://localhost:3000/auth/login` by clicking the button in the root path.

### Run `blitz -v` and paste the output here:

```
PASTE_HERE (leave the ``` marks)
```

### Please include below any other applicable logs and screenshots that show your problem:

<img width="1210" alt="Screen Shot 2023-01-20 at 6 27 16 PM" src="https://user-images.githubusercontent.com/2190603/213840240-e759d704-6e7d-4f89-9acf-d2f61bcdc095.png">

**Comment by tordans** [comment]
Which version of next are you using? 13 is without the anchor. 12 is with. With beta 20 and next 12 the generator worked fine for me.

**Comment by jorgepvenegas** [comment]
blitz@2.0.0-beta.22 CLI installed Next 13.1. Downgrading to 12 seems to fix the anchor issue in particular. I reached out for help on Discord and I learned that it might be related to templates.
https://discord.com/channels/802917734999523368/1066183931776467084/1066188887015305318

**Comment by tordans** [comment]
Oh, that (Next 13) is unexpected to me. The change is quite easy, search for all `<Link(…)\n<a>` issues and remove the anchor.

**Comment by cherylli** [comment]
Got the same issue today following the tutorial (https://blitzjs.com/docs/tutorial)
```
"dependencies": {
    "@blitzjs/auth": "2.0.0-beta.22",
    "@blitzjs/next": "2.0.0-beta.22",
    "@blitzjs/rpc": "2.0.0-beta.22",
    "@prisma/client": "4.6.0",
    "blitz": "2.0.0-beta.22",
    "next": "13.1",
    "prisma": "4.6.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "zod": "3.20.2",
    "final-form": "4.20.8",
    "react-final-form": "6.5.9"
```

**Comment by rikusen0335** [comment]
As @tordans say, Next.js's Link component now doesn't need anchor tag from version 13. Just remove it.
This issue could be closed after anchor is deleted.

**Comment by bradparks** [comment]
I have the same issue, and can fix it by removing the <a> tags, as suggested.

But blitz by default uses Next 13.1, so won't everyone hit this now?

<img width="718" alt="image" src="https://user-images.githubusercontent.com/185477/215288500-71cb6e81-fde6-405b-b13d-d82fc4e540db.png">

**Comment by noxify** [comment]
Yes, every new generated blitz app will have this.

Workaround until the template is updated is to remove the `<a>` tags from the pages which have this tag.

**Comment by Yansongsongsong** [comment]
hi there, i met a lot of issues when use brand new generated project.

1. <a> was written in <Link> (as above said. downgrading nextjs or removing the <a/> worked)
2. <style> enable global and jsx (under Form.tsx, there is one class mark for <style>. removing them will fix it. see the sceenshot)
3. SSR render does not match (as above said. easy to reproduce. open page and switch to signup/signin page, and refresh)

![problem two. global and jsx marker](https://user-images.githubusercontent.com/20450379/215650475-f2657402-dac1-4c31-964f-f1e924de416c.png)

![how to fix global and jsx issue](https://user-images.githubusercontent.com/20450379/215650649-109ad4d9-ac51-4e83-af54-a709254601b3.png)

**Comment by harrysbaraini** [comment]
I'm getting the sames errors as @Yansongsongsong

**Comment by jonbell-lot23** [comment]
I understand the issue, but it still seems like this is something Blitz should fix on their side. A new user should be able to fire up Blitz and get it working without errors. So it sounds like this is the fix, correct if wrong:

* Check the version of Next, and if it's 13, write the links in the supported way

**Comment by tordans** [comment]
As far as I know ([code search](https://github.com/search?q=repo%3Ablitz-js%2Fblitz+%22next%22%3A&type=code)) this was changed only recently as in https://github.com/blitz-js/blitz/commit/7abfb9086a7c494e7cb8af36b328934cbc4843a3 / https://github.com/blitz-js/blitz/pull/3987 by @dillonraphael.

@dillonraphael is next 13 a requirement for this new intro page or could Blitz move back to next 12 until the main issues (#4070) are fixed?
