### ISSUE TITLE
Queries and mutations hang when there is no internet 

### ISSUE THREAD

**Issue by kumarasinghe** [blitz-js/blitz#4069]
### What is the problem?

When we scaffold a new Blitz project and try to Signup as a new user, the signup mutation hook hangs when there is no internet connection.

```js
    const submitHandler = async (values) => {
        try {
            await signupMutation(values);  // <------ hangs here
            router.push(Routes.Home());
            return true;
        } catch (error) {
            // This error comes from Prisma
            if (
                error.code === "P2002" &&
                error.meta?.target?.includes("email")
            ) {
                alert("This email is already being used");
            }

            return false;
        }
    };
```

### Paste all your error logs here:

```
```

### Paste all relevant code snippets here:

```

```

### What are detailed steps to reproduce this?

1. Create a new Blitz project
2. Disconnect your internet connection
3. Run the project
4. Try to sign up

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.22 (global)
Blitz version: 2.0.0-beta.22 (local)
Linux 5.15 | linux-x64 | Node: v18.12.0


 Package manager: npm

  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
    Memory: 8.86 GB / 15.06 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.0/bin/yarn
    npm: 9.1.1 - ~/.nvm/versions/node/v18.12.0/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.22 => 2.0.0-beta.22 
    @blitzjs/next: 2.0.0-beta.22 => 2.0.0-beta.22 
    @blitzjs/rpc: 2.0.0-beta.22 => 2.0.0-beta.22 
    @prisma/client: 4.6.0 => 4.6.0 
    blitz: 2.0.0-beta.22 => 2.0.0-beta.22 
    next: 13.1 => 13.1.3 
    prisma: 4.6.0 => 4.6.0 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.8.4 => 4.9.4 
```

**Comment by jhonnymichel** [comment]
could you show what happens in the browser console network tab?

**Comment by jhonnymichel** [comment]
@kumarasinghe this is the default behavior of react-query: https://tanstack.com/query/v4/docs/react/guides/network-mode#network-mode-online

> In this mode, Queries and Mutations will not fire unless you have network connection. This is the default mode. If a fetch is initiated for a query, it will always stay in the state (loading, error, success) it is in if the fetch cannot be made because there is no network connection. However, a [fetchStatus](https://tanstack.com/query/v4/docs/react/guides/queries#fetchstatus) is exposed additionally.

if you want a different behavior you can modify the network mode in the query client you're using. In the case it's the default query client blitz provides, you can try doing this in your `_app.tsx`:
```javascript
import { getQueryClient } from "@blitzjs/rpc"

const queryClient = getQueryClient()
queryClient.setDefaultOptions({
  mutations: {
    networkMode: "always",
  },
})
```
