### ISSUE TITLE
Next.js: Migrate to Next typed routes (once released)

### ISSUE THREAD

**Issue by tordans** [blitz-js/blitz#4076]
It looks like Next.js will get "native" typed routes/links in the near future https://twitter.com/shuding_/status/1620137501192253440.

This ticket is meant as a place to document and discuss what Blitz would have to change in order to use this new core feature.

Right now, the only info I could find was this Twitter thread with no Links to a Next.js Github Ticket; I could not find any Roadmap info or other Info on it either – for now.

**Comment by siddhsuresh** [comment]
Hey @tordans, this feature is released now in nextjs 13.2 https://nextjs.org/blog/next-13-2#statically-typed-links and it seems to be related to only the app directory and not the pages directory. Hence I feel there is no need to migrate from the blitz solution of `Routes`. What are your thoughts?

**Comment by tordans** [comment]
@siddhsuresh thanks for the update. It's interesting that they decided to only support the app directory.

I agree, there is no reason for Blitz to do anything right now. We can reopen, should Next JS expand support to `/pages`.

> Next.js can now statically type links in the app directory…
> …
> This feature requires using the new App Router….
