### ISSUE TITLE
Tailwind UI recipe tailwind.config.js file `content` dirs incorrect

### ISSUE THREAD

**Issue by clioh** [blitz-js/blitz#4086]
### What is the problem?

I'm new to this project but it appears the project structure has been changed but the reference to it in the tailwind config file has not. The `content` path is `{pages,app}/**/*.{js,ts,jsx,tsx}` but should be `src/{pages,app}/**/*.{js,ts,jsx,tsx}` Happy to submit a PR to change but might just be faster if the core team does it.

### Paste all your error logs here:

N/A

### Paste all relevant code snippets here:

// tailwind.config.js
module.exports = {
  content: ["src/{pages,app}/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
}

### What are detailed steps to reproduce this?

1. run `blitz install tailwind`

### Run `blitz -v` and paste the output here:

Blitz version: 2.0.0-beta.23 (local)
macOS Ventura | darwin-arm64 | Node: v19.6.1

 Package manager: npm

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 14.00 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.6.1 - /var/folders/jb/qlffsl212ls_d488b4qxr7r00000gn/T/yarn--1676882813320-0.5120061576602399/node
    Yarn: 1.22.19 - /var/folders/jb/qlffsl212ls_d488b4qxr7r00000gn/T/yarn--1676882813320-0.5120061576602399/yarn
    npm: 9.4.0 - ~/.nvm/versions/node/v19.6.1/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.23 => 2.0.0-beta.23
    @blitzjs/next: 2.0.0-beta.23 => 2.0.0-beta.23
    @blitzjs/rpc: 2.0.0-beta.23 => 2.0.0-beta.23
    @prisma/client: 4.6.0 => 4.6.0
    blitz: 2.0.0-beta.23 => 2.0.0-beta.23
    next: 13.1 => 13.1.6
    prisma: 4.6.0 => 4.6.0
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.8.4 => 4.9.5

**Comment by tordans** [comment]
Hey @clioh that sounds like https://github.com/blitz-js/blitz/issues/4020 which should have been addressed in https://github.com/blitz-js/blitz/pull/3997/files. Maybe you will find a bug in there …
