### ISSUE TITLE
`next.config.mjs` isn't fetched

### ISSUE THREAD

**Issue by noxify** [blitz-js/blitz#4087]
### What is the problem?

If we use `next.config.mjs` instead of `next.config.js`, the underlaying scripts aren't able to fetch the next config.

### Paste all your error logs here:

```
Did not find custom config file
```

### Paste all relevant code snippets here:

* https://github.com/blitz-js/blitz/blob/main/packages/generator/src/utils/log.ts#L75
* https://github.com/blitz-js/blitz/blob/main/packages/blitz/src/cli/utils/routes-manifest.ts#L162
* maybe more?

### What are detailed steps to reproduce this?

1. `git clone git@github.com:noxify/t3_turbo.git`
2. `pnpm install`
3. `pnpm run dev`

You will see the error from above in the console.

Test Repo: https://github.com/noxify/t3_turbo

### Run `blitz -v` and paste the output here:

```
❯ npx blitz -v
Blitz version: 2.0.0-beta.23 (local)
macOS Ventura | darwin-x64 | Node: v18.7.0


 Package manager: npm

  System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 19.88 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.23 => 2.0.0-beta.23 
    @blitzjs/next: 2.0.0-beta.23 => 2.0.0-beta.23 
    @blitzjs/rpc: 2.0.0-beta.23 => 2.0.0-beta.23 
    @prisma/client: Not Found
    blitz: 2.0.0-beta.23 => 2.0.0-beta.23 
    next: 13.1.6 => 13.1.6 
    prisma: Not Found
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.9.5 => 4.9.5 
```

**Comment by datner** [comment]
In general, I noticed a bias towards `cjs` compiled output over `mjs`. I also noticed that this message pops up multiple times.
