### ISSUE TITLE
`router.resolveHref` is not a function

### ISSUE THREAD

**Issue by datner** [blitz-js/blitz#4097]
### What is the problem?

in `@blitzjs/next@2.0.0-beta.23`, in [`packages/blitz-next/src/index-server.ts`](https://github.com/blitz-js/blitz/blob/f443118b9d4bfcbf9255237bf5275e6f2c4dedc6/packages/blitz-next/src/index-server.ts#L35), line 35,
`resolveHref` is imported from inside `next`. I understand why it was done but It was not the best decision.
```ts
import {resolveHref} from "next/dist/shared/lib/router/router"
```

In recent versions (not absolutely sure which one) it was moved from `src/shared/lib/router/router` to [`src/shared/lib/router/utils/resolve-href`](https://github.com/vercel/next.js/blob/c110dfd57c754f88cb239dc154a4b7d49e5696a3/packages/next/src/shared/lib/router/utils/resolve-href.ts#L16). Specifically by [this commit](https://github.com/vercel/next.js/commit/074b7e4dcc537b3090925d8420a911f4798077bd).

This function is invoked when redirection is invoked. Manually in one of the server-side functions or via `Page.authenticate` and similar, as seen [here](https://github.com/blitz-js/blitz/blob/f443118b9d4bfcbf9255237bf5275e6f2c4dedc6/packages/blitz-next/src/index-server.ts#L296).

I do not want to pin my nextjs version, so I will just locally patch my blitz package. But this should be addressed..

### Paste all your error logs here:

```
error - javascript/node_modules/.pnpm/@blitzjs+next@2.0.0-beta.23_74snetkiih5ngkf22dvyer7ojy/node_modules/@blitzjs/next/dist/index-server.cjs (188:0) @ normalizeRedirectValues
 error - TypeError: router.resolveHref is not a function
     at normalizeRedirectValues (webpack-internal:///../../node_modules/.pnpm/@blitzjs+next@2.0.0-beta.23_74snetkiih5ngkf22dvyer7ojy/node_modules/@blitzjs/next/dist/index-server.cjs:188:35)
     at eval (webpack-internal:///../../node_modules/.pnpm/@blitzjs+next@2.0.0-beta.23_74snetkiih5ngkf22dvyer7ojy/node_modules/@blitzjs/next/dist/index-server.cjs:106:11)
     at Generator.next (<anonymous>)
     at fulfilled (webpack-internal:///../../node_modules/.pnpm/@blitzjs+next@2.0.0-beta.23_74snetkiih5ngkf22dvyer7ojy/node_modules/@blitzjs/next/dist/index-server.cjs:53:24) {
   page: '/admin'
 }
```

### Paste all relevant code snippets here:

```ts
export const getServerSideProps = gSSP(() => {
    return {
      redirect: {
        destination: Routes.OtherPage(),
        permanent: false,
      }
  }
})

// or
Page.authenticate = true

```

### What are detailed steps to reproduce this?

1. redirect

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.23 (local)
macOS Monterey | darwin-arm64 | Node: v18.12.1


 Package manager: npm

  System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 10.38 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.12.1 - /opt/homebrew/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.23 => 2.0.0-beta.23
    @blitzjs/next: 2.0.0-beta.23 => 2.0.0-beta.23
    @blitzjs/rpc: 2.0.0-beta.23 => 2.0.0-beta.23
    @prisma/client: Not Found
    blitz: 2.0.0-beta.23 => 2.0.0-beta.23
    next: 13.2.3 => 13.2.3
    prisma: Not Found
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.9.5 => 4.9.5
```
`@prisma/client` is present and latest. It is just in a different workspace (monorepo)

### Please include below any other applicable logs and screenshots that show your problem:

![image](https://user-images.githubusercontent.com/22598347/224503152-ad760a7f-ef20-440d-833c-b6256274e6d8.png)

**Comment by siddhsuresh** [comment]
Hey @datner, thanks a lot for finding this bug! Assigning it to myself to be pushed in the next release.
