### ISSUE TITLE
Bug: can't override experimental flags in `withBlitz` - needed for Material UI

### ISSUE THREAD

**Issue by JoseRFelix** [blitz-js/blitz#410]
### What is the problem?

This is related to #374 

Whenever `withBlitz` is used on `next.config.js` it disables the ripple of MUI button. Maybe there is a conflict with React concurrent mode?  

### Steps to Reproduce: 

1. Run `blitz start`
2. Test button

### Steps for it to work: 

1. Head to `.blitz/caches/dev`
2. Comment out config in `next.config.js`
3. Run `yarn next dev`
4. Test button

[Source](https://github.com/Jfelix61/blitz/tree/example/material-ui)

### Versions:

```
debug: local
debug: pkgPath: /home/jfelix/Documents/programming/open-source/blitz/node_modules/@blitzjs/cli 

Linux 5.3 | linux-x64 | Node: v12.16.1

blitz: 0.8.1 (global)
blitz: 0.8.1 (local)
```

### Supporting Documentation

[`withBlitz`](https://github.com/blitz-js/blitz/blob/canary/packages/server/src/withBlitz.ts) plugin.

**Comment by merelinguist** [comment]
Thanks for the issue @Jfelix61 ! I’m going to investigate this now. My main question is whether MUI and concurrent is the issue here, or if it’s something else...

**Comment by Jfelix61** [comment]
> My main question is whether MUI and concurrent is the issue here, or if it’s something else...

Yes... Another thing I could think is that it is maybe related to module resolution.

**Comment by merelinguist** [comment]
As I suspected, concurrent mode works fine with MUI. I think I remember seeing an announcement from the MUI team for concurrent mode support, and this simple sandbox proves that it works fine: https://codesandbox.io/s/new-dawn-5tvpb?file=/next.config.js

**Comment by merelinguist** [comment]
@Jfelix61 I’ve managed to create a basic working example with Blitz + MUI. 

Please see code here: https://codesandbox.io/s/blitz-hello-world-j1o7g?file=/app/pages/index.js

And the demo here: https://j1o7g.sse.codesandbox.io/

**Comment by flybayer** [comment]
Does MUI require SSR? If not, it would be nice to also have an MUI example that doesn't use getInitialProps, because using getInitialProps in _document forces **all** pages to be SSR, if I remember correctly.

**Comment by merelinguist** [comment]
Does this help: https://github.com/zeit/next.js/discussions/11073#discussioncomment-1440?

**Comment by flybayer** [comment]
Ok perfect! gIP in _document doesn't affect automatic static optimization

**Comment by Jfelix61** [comment]
@merelinguist Ripple works when we use react's experimental version, however it creates a class mismatch:

![image](https://user-images.githubusercontent.com/21092519/81012749-13c90a80-8e28-11ea-831c-16c6ed42df2a.png)

The only way I could fix this was using react's stable `16.13.1` version, but this version breaks the ripple when used with `withBlitz`.

**Comment by flybayer** [comment]
Ok, then we can definitely change withBlitz so that experimental flags defined in `blitz.config.js` will override the Blitz defaults.

**Comment by nyn0x** [comment]
Hi, for activate [Optional catch all routes](https://blitzjs.com/docs/routing#optional-catch-all-routes) user need to add manually the key optionalCatchAll in experimental. It looks like user config isn't merge with blitz internal config.
