### ISSUE TITLE
Tests are broken in new project 

### ISSUE THREAD

**Issue by ashavijit** [blitz-js/blitz#4101]
### What is the problem?

Tests are broken in new project 

### Paste all your error logs here:

```
PASTE_HERE (leave the ``` marks)
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
PASTE_HERE (leave the ``` marks)
```

**Comment by siddhsuresh** [comment]
@ashavijit is it the same issue mentioned in https://github.com/blitz-js/blitz/issues/4080? If not please update the issue with the requested details.
