### ISSUE TITLE
Error using generate

### ISSUE THREAD

**Issue by winstonderek** [blitz-js/blitz#4117]
### What is the problem?

I'm trying to user generate to create a new model that belongs to a user

Im running in local, I'm missing some configuration or have to install something?

### Paste all your error logs here:

```
TypeError: userConfigModule.find(...).paths(...).at is not a function at /usr/local/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:955:14 at Generator.next (<anonymous>) at fulfilled (/usr/local/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:904:24)
```

### Paste all relevant code snippets here:

```
blitz g all userFinancial belongsTo:user
```

### What are detailed steps to reproduce this?

1. Install CLI blitz
2. Run command to generate a new model 

### Run `blitz -v` and paste the output here:

```
TypeError: userConfigModule.find(...).paths(...).at is not a function at /usr/local/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:955:14 at Generator.next (<anonymous>) at fulfilled (/usr/local/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:904:24)
```

**Comment by siddhsuresh** [comment]
@winstonderek what's your nodejs version?

**Comment by winstonderek** [comment]
Yes, that worked, but now database prisma has issues... Thanks anyway :)

**Comment by siddhsuresh** [comment]
@winstonderek 
Is the database issue related to blitz new templates. If so please open a new issue on this.
