### ISSUE TITLE
Trying to generate a new model

### ISSUE THREAD

**Issue by winstonderek** [blitz-js/blitz#4119]
### What is the problem?

I try no create a new model using blitz generate with this command

´blitz g all usercompany app/user  belongsTo:user companyName:string address:string vat:string country:String postalcode:String´

I want the model files to be added inside the folder /app and inside the folder user/pages/users

Thats why I specify in the command the app/user after the modal name, but has you see in the miage it creates a new folder user/pages/users
 
![Captura de pantalla 2023-04-06 a las 17 05 48](https://user-images.githubusercontent.com/6440558/230421572-53cb5a56-83e6-4749-a97f-035a0e5dea94.png)

Also I get this error and I cant see the **mutations/queries** folders and files that will ejecute the queries or updates on the database. And I also thought I was going to see and update in the db/shema.prisma adding this new table. Do I have to create all this manually? I though this command would make all this jobs.
 

### Paste all your error logs here:

```
Error generating __ModelName__Form.tsx
Error: src/usercompanies/components/UsercompanyForm.js doesn't exist
    at module.exports [as read] (/home/gitpod/.nvm/versions/node/v18.15.0/lib/node_modules/blitz/node_modules/mem-fs-editor/lib/actions/read.js:12:11)
    at FormGenerator.<anonymous> (/home/gitpod/.nvm/versions/node/v18.15.0/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:2787:42)
    at Generator.next (<anonymous>)
    at /home/gitpod/.nvm/versions/node/v18.15.0/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:2757:61
    at new Promise (<anonymous>)
    at __async$1 (/home/gitpod/.nvm/versions/node/v18.15.0/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:2741:10)
    at FormGenerator.postFileWrite (/home/gitpod/.nvm/versions/node/v18.15.0/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:2785:12)
    at FormGenerator.<anonymous> (/home/gitpod/.nvm/versions/node/v18.15.0/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:1232:22)
    at Generator.next (<anonymous>)
    at fulfilled (/home/gitpod/.nvm/versions/node/v18.15.0/lib/node_modules/blitz/node_modules/@blitzjs/generator/dist/index.cjs:904:24)
```

### Paste all relevant code snippets here:

```
blitz g all usercompany app/user  belongsTo:user companyName:string address:string vat:string country:String postalcode:String
```

### What are detailed steps to reproduce this?

1. Install Blitz CLI
2. Create a model using the command

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.25 (global)
Blitz version: 2.0.0-beta.19 (local)
Linux 5.15 | linux-x64 | Node: v18.15.0


 Package manager: npm

  System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD EPYC 7B13
    Memory: 26.73 GB / 62.80 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.19 => 2.0.0-beta.19 
    @blitzjs/next: 2.0.0-beta.19 => 2.0.0-beta.19 
    @blitzjs/rpc: 2.0.0-beta.19 => 2.0.0-beta.19 
    @prisma/client: 4.8.1 => 4.8.1 
    blitz: 2.0.0-beta.19 => 2.0.0-beta.19 
    next: 12.2.5 => 12.2.5 
    prisma: 4.8.1 => 4.8.1 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 4.5.3 => 4.5.3 
```

**Comment by siddhsuresh** [comment]
Hey @winstonderek sorry about this. No the command should generate all the mutations and queries and components required.
Is this a javascript blitz project? If so it is a known issue and I am currently working on this.

**Comment by winstonderek** [comment]
Yes is a javascript blitz project. I didn't knew there was a .ts and .js different blitz! 

Is there a way or shortcut  that you know that I can do to get the files done, and after maybe just changing the .ts extension to .js or something like that? so I don't have to create everything manually? 

Thank you in advance!
