### ISSUE TITLE
suppressFirstRenderFlicker overlay stying

### ISSUE THREAD

**Issue by aaly00** [blitz-js/blitz#4125]
### What do you want and why?

I see in this [discussion](https://github.com/blitz-js/blitz/discussions/2274#discussioncomment-1759662) @flybayer mentions that suppressFirstRenderFlicker uses a white overlay. Is there a way to style this. The app that I am building follows system dark mode and when that happens it flashes a white screen which feels a little clunky. Is there a way to style the suppressFirstRenderFlicker overlay ?

**Comment by aaly00** [comment]
@siddhsuresh Is this possible? It's breaking dark mode for my application. I could submit a PR to add support for this if it doesn't exist.

**Comment by siddhsuresh** [comment]
Hey @aaly00. sorry for the delayed response. No, there is no current way to modify the syling provided in https://github.com/blitz-js/blitz/blob/5a64f1c39c65c07823088b5be479d9aea403d5d4/packages/blitz-next/src/index-browser.tsx#LL98C13-L98C13 . 

You can provide a PR to modify this css property to make it better suited for dark mode.

Assigning you to the issue
