### ISSUE TITLE
Nextjs 13 - App Router Beta Example

### ISSUE THREAD

**Issue by raghav0622** [blitz-js/blitz#4131]
### What do you want and why?
Blitzjs is awesome tooling which provides easy to underestand utilities for fullstack application but no example in either blitz generate or official documentation has App Router Beta Example where as a documentation is provided for migration.

I am completely new to blitzjs and world of fullstack and unable to migrate to app directory from pages in existing or new application as suggested in Migration guide in Documentation

### Possible implementation(s)

Please provide a starter example in nextjs examples or blitzjs examples for App Router / Directory similar to blitz generate new app subject to change with respect to Nextjs APIs. Atleaset we would have a starter template for app directory. Migration by newbies like me may lead to unexpected errors.

I am very thankful to maintainers / contributers for providing so much

**Comment by kumosal** [comment]
you can start with this example: https://github.com/blitz-js/blitz/tree/main/apps/next13

**Comment by raghav0622** [comment]
I tried your example, this is the error i receive without any modification

event - compiled client and server successfully in 5.4s (1581 modules)
wait  - compiling...
event - compiled client and server successfully in 923 ms (1558 modules)
16:41:51.972 INFO  Authentication Redirect: (Not authenticated) /auth/login 
error - SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
16:42:00.021 INFO  Authentication Redirect: (Not authenticated) /auth/login 
error - SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
wait  - compiling /auth/login/page (client and server)...
event - compiled client and server successfully in 1730 ms (1596 modules)
error - SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)

**Comment by siddhsuresh** [comment]
Hey @raghav0622 , that example was mainly used by me to test out the new features in Next App router and can be considered experimental and not stable.

If you are experiencing the same error on your app, please create a new issue for the same.

I will make the required stable example and documentation entry when my time frees up later this week.

**Comment by raghav0622** [comment]
> Hey @raghav0622 , that example was mainly used by me to test out the new features in Next App router and can be considered experimental and not stable.
> 
> If you are experiencing the same error on your app, please create a new issue for the same.
> 
> I will make the required stable example and documentation entry when my time frees up later this week.

Thanks for amazing suport

**Comment by mbj36** [comment]
hey @siddhsuresh can we use blitz with app router by default ?

**Comment by flybayer** [comment]
@mbj36 soon, almost done in https://github.com/blitz-js/blitz/pull/4146
