### ISSUE TITLE
authenticate does not work with roles

### ISSUE THREAD

**Issue by winstonderek** [blitz-js/blitz#4155]
### What is the problem?

Trying to use 

AdminHome.authenticate = { role: "ADMIN" }

to secure some pages

however if i use 

AdminHome.authenticate = true. it works, but it does not restrict the page when using 

AdminHome.authenticate = { role: "ADMIN" }

### Paste all your error logs here:

```
no error output
```

### Paste all relevant code snippets here:

```
import Link from "next/link"
import { Routes } from "@blitzjs/next"
import Layout from "app/core/layouts/Layout"
import { FaHotel, FaCalendarCheck, FaUserCheck } from "react-icons/fa"
import { useEffect, useState } from "react"
import { useMutation } from "@blitzjs/rpc"
import addGlobals from "app/globals/mutations/addGlobals"
import { useGlobals } from "app/core/hooks/useGlobals"
import { useSession } from "@blitzjs/auth"

const AdminHome = () => {
  const [value, setValue] = useState(50)
  const [porcentaje, setPorcentaje] = useState(50)
  const [createGlobals] = useMutation(addGlobals)


  const globals = useGlobals()
  useEffect(() => {
  globals[0]?.value ? setValue(globals[0].value) : setValue('4')
  globals[1]?.value ? setPorcentaje(globals[1].value) : setPorcentaje('10')
  }, [globals]);

  function handleInputChangeCurrentValue(event) {
    setValue(event.target.value)
  }

  function handleInputChangePorcentaje(event) {
    setPorcentaje(event.target.value)
  }

  return (
    <Layout title="Admin Panel">
      here my admin stuff
    </Layout>
  )
}

//AdminHome.authenticate = true
AdminHome.authenticate = { role: "ADMIN" }
export default AdminHome
```

### What are detailed steps to reproduce this?

1. comment /uncomment this 2 lines to see that autenticate true gets a no access and the other based by rol goes into the page without restriction
2. //AdminHome.authenticate = true
AdminHome.authenticate = { role: "ADMIN" }

### Run `blitz -v` and paste the output here:

```
9.5.0
```

**Comment by thenfour** [comment]
I am having the same issue, and notice this in blitz:

https://github.com/blitz-js/blitz/blob/da76acc90a562b9655b3d894a21e0f441ef51ad9/packages/blitz-auth/src/client/index.tsx#L314C10-L314C10

````
function withBlitzAuthPlugin<TProps = any>(Page: ComponentType<TProps> | BlitzPage<TProps>) {
  const AuthRoot = (props: ComponentProps<any>) => {
...
    let {authenticate, redirectAuthenticatedTo} = getAuthValues(Page, props)

    useAuthorizeIf(
      authenticate === true,
      !authenticate ? undefined : typeof authenticate === "object" ? authenticate.role : undefined,
    )
````

When `authenticate` is not exactly `true` (as in the case where it's `{ role: "ADMIN" }`), then it won't pass the condition to check roles.

I suppose `authenticate === true` should just be changed to `!!authenticate`.

**Comment by ameshkin** [comment]
I am having some issues with authenticate as well.

In my case I'm using this code 

`DashboardPage.authenticate = { redirectTo: "/login" }`

And this is the error I get.

Warning: Cannot update a component (`MyApp`) while rendering a different component (`BlitzAuthInnerRoot`). To locate the bad setState() call inside `BlitzAuthInnerRoot`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render



I'm using blitz 2.0.0-beta.29

**Comment by siddhsuresh** [comment]
Hey @thenfour, would you open a PR with the fix?

**Comment by tordans** [comment]
One observation: It looks like `AdminEditSurveyPage.authenticate = "ADMINs"` works as indented. However, reading the code linked by @thenfour I don't understand why it would…

I also noticed, that there are tests that cover the `{redirect}` part but none that cover the `{role}` part: https://github.com/blitz-js/blitz/blob/8d29b8afa9fa1579fe08bf82aff1bd1513fac46f/integration-tests/auth-with-rpc/test/index.test.ts#L127

I don't know enough about this stuff to contribute, so I hope someone can pick this up…
