### ISSUE TITLE
Datetime type with Prisma does not work with getServerSideProps

### ISSUE THREAD

**Issue by gielcobben** [blitz-js/blitz#416]
### What is the problem?

The tutorial uses `publishedAt       DateTime` in the Prisma schema. When I re-write `app/questions/pages/[id].tsx` to use `getServerSideProps` it's throwing and error:

```
Error serializing `.questions[0].publishedAt` returned from `getServerSideProps` in "/questions/[id]". Reason: `object` ("[object Date]") cannot be serialized as JSON. Please only return JSON serializable data types.
```

### Steps to Reproduce: 

1. Follow the [tutorial](https://github.com/blitz-js/blitz/blob/canary/TUTORIAL.md).
1. Replace the code in `app/questions/pages/[id].tsx` with:

```
import { Head, Link, ssrQuery } from "blitz"
import getQuestions from "app/questions/queries/questions/getQuestions"

export const getServerSideProps = async ({ params, req, res }) => {
  const questions = await ssrQuery(getQuestions, { where: { id: parseInt(params.id) } }, { req, res })
  return { props: { questions } }
}

const ShowQuestionPage = ({ questions }) => {
  console.log(questions)

  return (
    <div className="container">
      <Head>
        <title>Question</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p>
          <Link href="/questions">
            <a>Questions</a>
          </Link>
        </p>
      </main>
    </div>
  )
}

export default ShowQuestionPage
```
1. The following error occurs:
```
Error serializing `.questions[0].publishedAt` returned from `getServerSideProps` in "/questions/[id]". Reason: `object` ("[object Date]") cannot be serialized as JSON. Please only return JSON serializable data types.
```

### Versions:

```
debug: local
debug: pkgPath: test/node_modules/@blitzjs/cli

macOS Catalina | darwin-x64 | Node: v12.16.1

blitz: 0.8.1 (global)
blitz: 0.8.1 (local)
```

### Supporting Documentation

- https://github.com/zeit/next.js/discussions/11498
- https://github.com/zeit/next.js/issues/11993

**Comment by merelinguist** [comment]
Have run into this several times now. Still not sure if there’s an _easy_ way to fix.

**Comment by gielcobben** [comment]
So, what would you recommend for Datetime types in Prisma / Blitz (for now)?

**Comment by merelinguist** [comment]
As a long-term solution, we’ll probably have to work that out somewhere within Blitz. For your purposes, though I’d recommend either:

1. Not using SSR, or

2. Just using a plain `String` type in your Prisma schema. This would look something like this:

```
model Question {
  id          Int      @default(autoincrement()) @id
  text        String
  publishedAt String
  choices     Choice[]
}
```

Then, when you’re creating your `Question`, set the `publishedAt` field to use a string, not a date object, like this:

```jsx
const question = await createQuestion({
  data: {
    text: event.target[0].value,
    publishedAt: new Date().to_string(),
    choices: {
      create: [
        { text: event.target[1].value },
        { text: event.target[2].value },
        { text: event.target[3].value },
      ],
    },
  },
})
```

**Comment by gielcobben** [comment]
Thank you, this helps a lot 🙏

Do you know if this recommendation has any implications for ordering or filtering?

**Comment by merelinguist** [comment]
Glad that helped @gielcobben! For filtering, you’d do this:

```js
import db from "db"

const date = "2020-05-25T21:28:30.923Z"

const questions = await db.question.findMany({where: {publishedAt: date}})
```

**Comment by merelinguist** [comment]
Investigated this a bit more, and since this is essentially built into Next as a feature, I don’t think it can be “solved” beyond using something like the solution above.

**Comment by merelinguist** [comment]
(See also the GUI for another example of a Blitz app which casts the date to an `Int` to avoid Next’s rehydration problems in this area.)

**Comment by osirvent** [comment]
@merelinguist Shouldn't we use `Float` instead of `Int` on Prisma Schema?

**Comment by flybayer** [comment]
I recommend using String with ISO date format instead of a number.

**Comment by hauptrolle** [comment]
Is there a solution yet?

**Comment by flybayer** [comment]
@hauptrolle yes!

Use the `superjson` library.

[See the docs on using with `getServerSideProps` here](https://github.com/blitz-js/superjson/blob/document-gssp/README.md#using-with-nextjs-getserversideprops-getinitialprops-and-getstaticprops)

**Comment by phoshenwen** [comment]
Facing the same problem, just updating @flybayer's [link](https://github.com/blitz-js/superjson#using-with-nextjs)

**Comment by flybayer** [comment]
Fyi, we have an open issue to add this to blitz core: #1043
