### ISSUE TITLE
Incorrect types when using relations in useQuery

### ISSUE THREAD

**Issue by JClackett** [blitz-js/blitz#417]
### What is the problem?

The returned type from the useQuery doesn't included the relations

### Steps to Reproduce: 

schema: 

```
model Post {
  id       Int       @default(autoincrement()) @id
  title    String
  comments Comment[]
}

model Comment {
  id      Int    @default(autoincrement()) @id
  content String
  post    Post   @relation(fields: [postId], references: [id])
  postId  Int
}
```

```
const [posts] = useQuery(getPosts, { include: { comments: true } })
```

the type is just: Post[] without comments

```
export default async function getPosts(args: FindManyPostArgs) {
  const posts = await db.post.findMany(args)
  return posts
}
```

It seems the getPosts function doesnt infer the correct types from the args passed through, if i put the { include: comments: true } in the getPosts function it is then correct, but obviously we dont wana be doing that with every query

### Versions:

```
debug: local
debug: pkgPath: /Users/jclackett/Documents/Apps/Examples/blitz/node_modules/@blitzjs/cli

macOS Catalina | darwin-x64 | Node: v13.10.1

blitz: 0.8.1 (global)
blitz: 0.8.1 (local)
```

**Comment by simonpeterdebbarma** [comment]
Hello @JClackett, thank you for submitting an Issue.

**Comment by merelinguist** [comment]
@JClackett Thanks for the issue! This is something on my radar I’ve been meaning to open an issue on. You’re right that it’s possible to do it by modifying the query, but yeah, we definitely don’t want that to be necessary for each query. That’s what I’ve had to do in the [tutorial](https://github.com/blitz-js/blitz/blob/canary/TUTORIAL.md#listing-choices), but it’s not ideal.

Is this a limitation of TypeScript? Would be cool if anyone could play around with this a bit more!

**Comment by JClackett** [comment]
Have started a discussion in prisma repo as i think it is caused by them:
https://github.com/prisma/prisma/discussions/2360

**Comment by JClackett** [comment]
Seems like a TypeScript issue, and requires function overloading, not my strong point tbh!
https://github.com/prisma/prisma/discussions/2360#discussioncomment-8807

**Comment by merelinguist** [comment]
Thanks for the investigation @JClackett! I realise this isn’t entirely Blitz’s fault but I still think it’s something that should be working so let’s keep this issue open.

**Comment by flybayer** [comment]
Nothing actionable on this for us
