### ISSUE TITLE
Easy Fix! Project Names Not Showing or Available! Docs could use a serious Brush up! 

### ISSUE THREAD

**Issue by PerfectProductions** [blitz-js/blitz#4178]
### What is the problem?

I've noticed that project names are not requested or required and would love to see this feature returned. 

For the most part there is stale code found as {project.name} in 'src/pages/projects/index.tsx' at line 30

The version in question is Blitz version: 2.0.0-beta.31 (global) and I am not sure if this is by design, however may I request to have it placed back as its rather neccessary for the community rather than having to dig into the code to fix it.

Here is a video of the issue which makes it hard for newcomers to appreciate the layout. 

https://www.awesomescreenshot.com/video/19376083?key=b037d830cf3811f9889bd7805b4a415d

Better more to the point youtube videos would be a great help also to help discover blitzs' layout and scaffolding features would be tremendous, the docs are very plain and very ordinary, if you fix this, the community should skyrocket a lot harder! Please fix your docs! (Also there appears to be a cosmetic issue viewing https://tinyurl.com/2bx786bv )

Looking forward to this framework and hoping this gets fixed quickly! Lots to give!

Thanks! 

### Paste all your error logs here:

```
No logs are provided.
```

### Paste all relevant code snippets here:

```
import { Suspense } from "react";
import { Routes } from "@blitzjs/next";
import Head from "next/head";
import Link from "next/link";
import { usePaginatedQuery } from "@blitzjs/rpc";
import { useRouter } from "next/router";
import Layout from "src/core/layouts/Layout";
import getProjects from "src/projects/queries/getProjects";

const ITEMS_PER_PAGE = 100;

export const ProjectsList = () => {
  const router = useRouter();
  const page = Number(router.query.page) || 0;
  const [{ projects, hasMore }] = usePaginatedQuery(getProjects, {
    orderBy: { id: "asc" },
    skip: ITEMS_PER_PAGE * page,
    take: ITEMS_PER_PAGE,
  });

  const goToPreviousPage = () => router.push({ query: { page: page - 1 } });
  const goToNextPage = () => router.push({ query: { page: page + 1 } });

  return (
    <div>
      <ul>
        {projects.map((project) => (
          <li key={project.id}>
            <Link href={Routes.ShowProjectPage({ projectId: project.id })}>
              {project.name} // Okay so here is the remnant of the previous project naming convention - - we need names!
            </Link>
          </li>
        ))}
      </ul>

      <button disabled={page === 0} onClick={goToPreviousPage}>
        Previous
      </button>
      <button disabled={!hasMore} onClick={goToNextPage}>
        Next
      </button>
    </div>
  );
};

const ProjectsPage = () => {
  return (
    <Layout>
      <Head>
        <title>Projects</title>
      </Head>

      <div>
        <p>
          <Link href={Routes.NewProjectPage()}>Create Project</Link>
        </p>

        <Suspense fallback={<div>Loading...</div>}>
          <ProjectsList />
        </Suspense>
      </div>
    </Layout>
  );
};

export default ProjectsPage;
```

### What are detailed steps to reproduce this?

1. Please see attached stream. 

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.31 (global)
Blitz version: 2.0.0-beta.31 (local)
Linux 6.1 | linux-arm64 | Node: v20.2.0


 Package manager: npm

  System:
    OS: Linux 6.1 Gentoo Linux
    CPU: (4) arm64 Neoverse-N1
    Memory: 16.26 GB / 23.44 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.2.0/bin/yarn
    npm: 9.7.1 - ~/.nvm/versions/node/v20.2.0/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.31 => 2.0.0-beta.31 
    @blitzjs/next: 2.0.0-beta.31 => 2.0.0-beta.31 
    @blitzjs/rpc: 2.0.0-beta.31 => 2.0.0-beta.31 
    @prisma/client: 4.6.1 => 4.6.1 
    blitz: 2.0.0-beta.31 => 2.0.0-beta.31 
    next: 13.4.5 => 13.4.5 
    prisma: 4.6.1 => 4.6.1 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.8.4 => 4.9.5 ```


### Please include below any other applicable logs and screenshots that show your problem:

_No response_

**Comment by PerfectProductions** [comment]
My understanding is that the remnant mentioned in the first post means that the naming conventiona nd the ability to name projects on creation was there previously but now isnt. 

The feature should be re-implmented again for general usage. 

Naming projects would be cool.

Thanks!

**Comment by PerfectProductions** [comment]
Possible false alarm although not documented very well.

It seems adding a database property to the scheme for example project.projectname will print the project nameafter all. 

This should be mentioned and other hidden caveats should be mentioned aswell. 

Apologioes if this is some sort of a false alarm.

Please get those docs fixed!

1) Simple approach!
2) Prisma Generate allows the user to create a new db and schema with the tables and types that are wanted.
3) Also generates pages that create add and delete etc hooks and calls to the database that are RPC related

This stuff is longwinded in the docs but the product is outstanding!

The best step to popularity with this entire framework is dead simple, basic approach to the docs, always, in any project! Thats the secret to making blitz an outstanding success!

Thanks! Great product!

**Comment by siddhsuresh** [comment]
Thanks for the issue @PerfectProductions, yes we should improve this, and @maciej-ka for the fix.
