### ISSUE TITLE
Prettier prevents Github Commits

### ISSUE THREAD

**Issue by PerfectProductions** [blitz-js/blitz#4184]
### What is the problem?

I've noticed that after a fresh install of node_modules that the node module prettier is preventing github commits and push's from my repo to said platform. 

Here is the git commit error message https://bpa.st/RI6Q

I've noticed similar issue have been found and fixed in sequential releases. 

Best of luck with this one. Thanks!

### Paste all your error logs here:

```
https://bpa.st/RI6Q

```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.31 (global)
Blitz version: 2.0.0-beta.31 (local)
Linux 6.1 | linux-arm64 | Node: v20.2.0


 Package manager: npm

  System:
    OS: Linux 6.1 Gentoo Linux
    CPU: (4) arm64 Neoverse-N1
    Memory: 18.73 GB / 23.44 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.2.0/bin/yarn
    npm: 9.7.1 - ~/.nvm/versions/node/v20.2.0/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.31 => 2.0.0-beta.31 
    @blitzjs/next: 2.0.0-beta.31 => 2.0.0-beta.31 
    @blitzjs/rpc: 2.0.0-beta.31 => 2.0.0-beta.31 
    @prisma/client: 4.6.1 => 4.6.1 
    blitz: 2.0.0-beta.31 => 2.0.0-beta.31 
    next: 13.4.5 => 13.4.5 
    prisma: 4.6.1 => 4.6.1 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.8.4 => 4.9.5 
```

**Comment by PerfectProductions** [comment]
Corrected Issue - Very hard to trace, issue simply dissapeared. Possible Issue with some kind of linking code. 

Hard to trace. 

Go over your most recent changes if you encountered this. Rewrite your code. As I have done. The issue seems to have vanished!

Will leave open so other active users may run into same thing.

**Comment by siddhsuresh** [comment]
Hey @PerfectProductions thanks for the issue. As far as I see the logs, this is an issue with the husky pre-commit hook running the prettier and exiting earlier. I am not able to reproduce this locally, are you sure this is an issue with the blitz initial template?

**Comment by PerfectProductions** [comment]
Hi. Please allow me to confirm that this is nto a bad experience. 

The experience itself would be much prettier (excuse the pun) if the docs were a bit more simple and a bit more forward. 

However, this appears to be an issue with a generated template. As you cna see, Im using paste as the poject generated.

I just not tried a push and it looks like prettier is still complaining about the generated template. Not sure why? Could be an issue with my vscode plugin, but here is the latet output, hopefully we can get to the bottom of this, as I love the blitzing! I'd love to stash it on GH. 

Deadset! Really Happy with this as a prime base! I really think we need a forum out there to help people aswell as the community is thin, and I'd love to host one if we can get some backing from the higher ups. 

Here's the latest git push attempt: 

Thanks for getting onto this recently.

> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
🔍  Finding changed files since git revision 3d94bad.
🎯  Found 3596 changed files.
/var/www/localhost/htdocs/blitz/node_modules/prettier/index.js:7529
          throw error;
          ^

SyntaxError: Unexpected token, expected ")" (29:21)
  27 |         const paste = await createPasteMutation(values);
  28 |         await router.push(Routes.ShowPastePage({ pasteId: paste.id }));
> 29 |       } catch (error: any) {
     |                     ^
  30 |         console.error(error);
  31 |   }
  32 |
    at p (/var/www/localhost/htdocs/blitz/node_modules/prettier/parser-babel.js:22:1054)
    at d (/var/www/localhost/htdocs/blitz/node_modules/prettier/parser-babel.js:22:1287)
    at Object.parse (/var/www/localhost/htdocs/blitz/node_modules/prettier/parser-babel.js:29:54501)
    at Object.parse (/var/www/localhost/htdocs/blitz/node_modules/prettier/index.js:7515:23)
    at coreFormat (/var/www/localhost/htdocs/blitz/node_modules/prettier/index.js:8829:18)
    at formatWithCursor2 (/var/www/localhost/htdocs/blitz/node_modules/prettier/index.js:9021:18)
    at /var/www/localhost/htdocs/blitz/node_modules/prettier/index.js:38183:12
    at Object.format (/var/www/localhost/htdocs/blitz/node_modules/prettier/index.js:38197:12)
    at _default (/var/www/localhost/htdocs/blitz/node_modules/pretty-quick/dist/processFiles.js:42:29)
    at _default (/var/www/localhost/htdocs/blitz/node_modules/pretty-quick/dist/index.js:60:29) {
  loc: { start: { line: 29, column: 21 } },
  codeFrame: '  27 |         const paste = await createPasteMutation(values);\n' +
    '  28 |         await router.push(Routes.ShowPastePage({ pasteId: paste.id }));\n' +
    '> 29 |       } catch (error: any) {\n' +
    '     |                     ^\n' +
    '  30 |         console.error(error);\n' +
    '  31 |   }\n' +
    '  32 |'
}

Node.js v20.2.0
husky - pre-commit hook exited with code 1 (error)

**Comment by PerfectProductions** [comment]
I'd like to close this issue realising that I have altered my code and it appears that the code alterations I;'ve comitted have allowed the build to build successfully. 

I have no further informationr egarding hte issue however I would presume that I was misusing userMutation incorrectly. 

I have rectified this issue, however, useMutation is causing infinite looping issues with a fresh install on codesandbox.io

Please see that issue as a follow-on and I would very grateful if you could help resolve that issue instead. 

This item is now officially closed and I reopen it if I come accross the issue again. 

Thanks for you assistance!
