### ISSUE TITLE
Prisma Schema and Project Addition Leaves Project Page Viewing Issue

### ISSUE THREAD

**Issue by PerfectProductions** [blitz-js/blitz#4185]
### What is the problem?

When a new project is developed by running blitz generate the projects page are unable to be viewed and produce an error via the web browser

This appears to stem from the blitz project and rpc areas of the node_modules directory tree

A temporary solution is to delete node_modules and reinstall the node_modules deps via yarn install

This should get the new project pages and mutations and queries listing correctly in the browser again

Someone should take a look at the dynamic content of the blitz framework and locate the issue in order to resolve, further information is provided which shows a relative portion of the node_modules tree to help locate the issue for a more senior developer.

Thanks!

### Paste all your error logs here:

```
2023-07-29 12:49:51.535 INFO    [blitz-rpc]     getPastes() Starting with input: {
  orderBy: {
    id: 'asc'
  },
  skip: 0,
  take: 100
}
TypeError: Cannot read properties of undefined (reading 'count')
    at count (webpack-internal:///(api)/./src/pastes/queries/getPastes.ts:18:69)
    at /var/www/localhost/htdocs/blitz/node_modules/blitz/dist/index-server.cjs:167:47
    at Generator.next (<anonymous>)
    at /var/www/localhost/htdocs/blitz/node_modules/blitz/dist/index-server.cjs:129:61
    at new Promise (<anonymous>)
    at __async (/var/www/localhost/htdocs/blitz/node_modules/blitz/dist/index-server.cjs:113:10)
    at paginate (/var/www/localhost/htdocs/blitz/node_modules/blitz/dist/index-server.cjs:134:10)
    at eval (webpack-internal:///(api)/./src/pastes/queries/getPastes.ts:15:114)
    at /var/www/localhost/htdocs/blitz/node_modules/@blitzjs/rpc/dist/index-server.cjs:62:28
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/localhost/htdocs/blitz/node_modules/@blitzjs/rpc/dist/index-server.cjs:37:24)
2023-07-29 12:49:51.536 ERROR   [blitz-rpc]     getPastes()

 TypeError  Cannot read properties of undefined (reading 'count')
error stack:
  • 

  • index-server.cjs
        /node_modules/blitz/dist/index-server.cjs:167
  • 

  • index-server.cjs
        /node_modules/blitz/dist/index-server.cjs:129
  • 

  • index-server.cjs    __async
        /node_modules/blitz/dist/index-server.cjs:113
  • index-server.cjs    paginate
        /node_modules/blitz/dist/index-server.cjs:134
  • 

  • index-server.cjs
        /node_modules/@blitzjs/rpc/dist/index-server.cjs:62
  • 

  • index-server.cjs    fulfilled
        /node_modules/@blitzjs/rpc/dist/index-server.cjs:37
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1. blitz generate all paste pasteid:Int pastedescription:string pastename:string
2. once pages are generated visit http://localhost:3000/pastes
3  Screenshot of outcome, https://tinyurl.com/2bjouazq

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.31 (global)
Blitz version: 2.0.0-beta.31 (local)
Linux 6.1 | linux-arm64 | Node: v20.2.0


 Package manager: npm

  System:
    OS: Linux 6.1 Gentoo Linux
    CPU: (4) arm64 Neoverse-N1
    Memory: 19.01 GB / 23.44 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.2.0/bin/yarn
    npm: 9.7.1 - ~/.nvm/versions/node/v20.2.0/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.31 => 2.0.0-beta.31 
    @blitzjs/next: 2.0.0-beta.31 => 2.0.0-beta.31 
    @blitzjs/rpc: 2.0.0-beta.31 => 2.0.0-beta.31 
    @prisma/client: 4.6.1 => 4.6.1 
    blitz: 2.0.0-beta.31 => 2.0.0-beta.31 
    next: 13.4.5 => 13.4.5 
    prisma: 4.6.1 => 4.6.1 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.8.4 => 4.9.5 ```


### Please include below any other applicable logs and screenshots that show your problem:

Screenshot of general project creation and project page listing error, https://tinyurl.com/2bjouazq

**Comment by siddhsuresh** [comment]
@PerfectProductions sorry for this experience, this should have been seamless. I want to confirm with you whether the generate command resolved correctly and you can see the required mutations and queries as expected?

I will take a look at this but I am not able to understand, you mentioned re-installing `node-modules` fixed this? This generate AFAIK does not even touch the `node-modules` folder, so this is confusing.

**Comment by PerfectProductions** [comment]
I confirm that being sure not to try to add the default id: value whilst using blitz generate resolves the issue. 

for example:

Don't: blitz generate all projectname pasteid:Int pastedescription:string pastename:string

Do: blitz generate all projectname pastedescription:string pastename:string

Removing "pasteid:Int " from step 1. resolves the issue.

I am happy for this item to be closed and hopefully if other newcomers have this issue then perhaps this record will help resolve this for them!

Thanks for you interest!

Item confirmed as resolved without pull required.

(PS: Please see my codesandbox bug report as it appears to be a genuine issue!)

Thanks!
