### ISSUE TITLE
TypeScript issue when trying to extend Session with custom properties

### ISSUE THREAD

**Issue by zenchantlive** [blitz-js/blitz#4187]
### What is the problem?

Title: TypeScript issue when trying to extend Session with custom properties

Description:

Hello, I'm having an issue when trying to extend the Session interface with custom properties in a Blitz.js app. I have followed the guide on using third-party Passport.js authentication with Google OAuth, and as part of the authentication flow, I am storing additional properties such as userId, roles, and source in the session's public data.

Here's the code snippet for that:

typescript
Copy code
const user = await db.user.upsert({
    where: { email },
    create: {
        email,
        name: profile.displayName,
        hashedPassword: dummyPassword,
        role: "user"
    },
    update: { email },
})

const publicData = {
    userId: user.id,
    roles: [user.role],
    source: "google",
}
done(undefined, { publicData })
In my application, I need to access these properties. However, TypeScript is throwing an error saying these properties don't exist on the Session type.

I tried to augment the Session interface like so:

typescript
Copy code
// types.ts
import { PublicData } from "@blitzjs/auth"

declare module "@blitzjs/auth" {
  interface PublicData extends PublicData {
    userId: number;
    roles: string[];
    source: string;
  }
}
But this results in a recursive reference error: Type 'PublicData' recursively references itself as a base type.

Could you please advise on how to correctly extend the Session interface to include these custom properties? Or is there a recommended workaround for this issue?

Thank you for your assistance.

### Paste all your error logs here:

```
PASTE_HERE (leave the ``` marks)
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
PASTE_HERE (leave the ``` marks)
```

**Comment by siddhsuresh** [comment]
Hey @zenchantlive thank you for the issue, just for future reference this would be better suited for the discord help system. 

For this use case of extending the `session` object in blitz can be done in the following way:

```ts
declare module "@blitzjs/auth" {
  export interface Session {
    isAuthorized: SimpleRolesIsAuthorized<Role>
    PublicData: {
      userId: number;
      roles: string[];
      source: string;  
  }
}
```
