### ISSUE TITLE
Noise in logs

### ISSUE THREAD

**Issue by reymon359** [blitz-js/blitz#4202]
### What is the problem?

I updated yesterday from beta 22 to beta 32, and now my logs are full of noise. What is the config I need to add in `[[...blitz]].ts` to have the previous INFO logs

This is my current `[[...blitz]].ts` file

```
import { rpcHandler } from "@blitzjs/rpc"
import { api } from "src/blitz-server"

export default api(rpcHandler({ onError: console.log }))
```

Previous
<img width="1012" alt="Screenshot 2023-08-24 at 08 57 57" src="https://github.com/blitz-js/blitz/assets/31936665/79394cd3-2269-44f6-847e-bfcc2475becf">

Now
<img width="1352" alt="Screenshot 2023-08-24 at 07 50 47" src="https://github.com/blitz-js/blitz/assets/31936665/32c486b9-0348-4a0a-ad49-cec66f3d23bf">

### Paste all your error logs here:

```
PASTE_HERE (leave the ``` marks)
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
PASTE_HERE (leave the ``` marks)
```

**Comment by siddhsuresh** [comment]
Hey @reymon359 apologies for the late response. 
You can do it using the following method in your `rpcHandler`
```
import { rpcHandler } from "@blitzjs/rpc"
import { api } from "src/blitz-server"

export default api(
  rpcHandler({
    onError: console.log,
    formatError: (error) => {
      error.message = `FormatError handler: ${error.message}`
      return error
    },
    logging: {
      verbose: true,
      allowList: ["/api/rpc/getCurrentUser"],
      blockList: ["/getCurrentUser"],
      disablelevel: "info"
    },
  })
)

```

**Comment by reymon359** [comment]
@siddhsuresh Thanks a lot! this is exactly what I was looking for ❤️

**Comment by reymon359** [comment]
Hey @siddhsuresh although your solution worked locally

<img width="692" alt="Screenshot 2023-09-06 at 20 16 54" src="https://github.com/blitz-js/blitz/assets/31936665/2bedc8dd-837c-47d2-84ec-b3bb913766e2">

when I deployed it to prod, the logs are like this

<img width="1074" alt="Screenshot 2023-09-06 at 20 17 05" src="https://github.com/blitz-js/blitz/assets/31936665/38b72e36-5de0-4270-b05b-83dc83dd2933">

How can I fix the logs in prod?
