### ISSUE TITLE
Error: socket hang up  code: 'ECONNRESET'

### ISSUE THREAD

**Issue by reymon359** [blitz-js/blitz#4203]
### What is the problem?

Hey there, I updated yesterday from beta 22 to beta 32 and I am facing  `Error: socket hang up `in production which crashes the app.

I have tried upgrading node to v16 and v18 and downgrading next from 13.4.5 to 13.4.2 but it keeps failing.

What is the node version and next.js version I have to use to make it work? 

I don't want to just downgrade again to beta 22 and be discouraged to upgrade again

### Paste all your error logs here:

```
Aug 24 08:10:28 AM  Error: socket hang up
Aug 24 08:10:28 AM      at connResetException (node:internal/errors:705:14)
Aug 24 08:10:28 AM      at Socket.socketOnEnd (node:_http_client:518:23)
Aug 24 08:10:28 AM      at Socket.emit (node:events:525:35)
Aug 24 08:10:28 AM      at Socket.emit (node:domain:489:12)
Aug 24 08:10:28 AM      at endReadableNT (node:internal/streams/readable:1358:12)
Aug 24 08:10:28 AM      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
Aug 24 08:10:28 AM    code: 'ECONNRESET'
Aug 24 08:10:28 AM  }
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.32 (global)
Blitz version: 2.0.0-beta.32 (local)
macOS Monterey | darwin-arm64 | Node: v16.20.2


 Package manager: pnpm

  System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.96 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.32 => 2.0.0-beta.32 
    @blitzjs/next: 2.0.0-beta.32 => 2.0.0-beta.32 
    @blitzjs/rpc: 2.0.0-beta.32 => 2.0.0-beta.32 
    @prisma/client: 4.6.1 => 4.6.1 
    blitz: 2.0.0-beta.32 => 2.0.0-beta.32 
    next: 13.4.2 => 13.4.2 
    prisma: 4.6.1 => 4.6.1 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.8.4 => 4.9.4 
```

### Please include below any other applicable logs and screenshots that show your problem:

<img width="1134" alt="Screenshot 2023-08-24 at 09 03 55" src="https://github.com/blitz-js/blitz/assets/31936665/22e042bb-5d03-4207-9e17-88f234988dca">

**Comment by siddhsuresh** [comment]
Hey @reymon359 I have not been able to replicate this, do you have a minimal repository where is occurs?
