### ISSUE TITLE
Crashing on thrown objects

### ISSUE THREAD

**Issue by papsavas** [blitz-js/blitz#4217]
### Blitz RPC crashes on frontend when you throw custom objects from server.

Custom error data from server to client seems like a nightmare. The [superjson](https://blitzjs.com/docs/error-handling#handling-server-errors-on-the-client) approach does not always work and is overcomplicated, especially for multiple props 

### Paste all your error logs here:

![image](https://github.com/blitz-js/blitz/assets/50584606/f6114cee-30cb-4384-beee-4bfcfdf5fa15)

![image](https://github.com/blitz-js/blitz/assets/50584606/0eddf7ec-d64b-434a-8b9b-d21eee713a09)

### Paste all relevant code snippets here:

```ts
// test.tsx
import test from "@rpc/queries/foo/test.ts"
const MyComponent = () => {
 const [testQuery] = useQuery(test, undefined);
 ...
}

// rpc/queries/foo/test.ts
import { resolver } from '@blitzjs/rpc';

export default resolver.pipe(resolver.authorize(), async (input, ctx) => {
  throw { foo: 'bar' };
});
```

### What are detailed steps to reproduce this?

1. Create a query or mutation that throws a regular js object `{foo:"bar"}`
2. use query or mutation in a client component

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.32 (local)
Windows 11 | win32-x64 | Node: v18.17.1


 Package manager: pnpm

  System:
    OS: Windows 10 10.0.22621
    CPU: (24) x64 AMD Ryzen 9 7900X 12-Core Processor
    Memory: 20.15 GB / 31.16 GB
  Binaries:
    Node: 18.17.1 - ~\AppData\Local\Volta\tools\image\node\18.17.1\node.EXE
    Yarn: Not Found
    npm: 9.6.7 - ~\AppData\Local\Volta\tools\image\node\18.17.1\npm.CMD
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.32 => 2.0.0-beta.32
    @blitzjs/next: 2.0.0-beta.32 => 2.0.0-beta.32
    @blitzjs/rpc: 2.0.0-beta.32 => 2.0.0-beta.32
    @prisma/client: ^5.2.0 => 5.2.0
    blitz: 2.0.0-beta.32 => 2.0.0-beta.32
    next: ^13.4.12 => 13.4.12
    prisma: ^5.2.0 => 5.2.0
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: 5.2.2 => 5.2.2
```

**Comment by siddhsuresh** [comment]
@papsavas The method for working with superjson and throwing errors in server and catching them in client, usually entails defining a custom error class

Example from blitz source code
```ts
export class AuthenticationError extends Error {
  name = "AuthenticationError"
  statusCode = 401
  constructor(message = "You must be logged in to access this") {
    super(message)
  }
  get _clearStack() {
    return true
  }
}
```

Then registering that with superjson

```ts
SuperJson.registerClass(AuthenticationError, {
    identifier: "BlitzAuthenticationError",
    allowProps: errorProps,
  })
```

Now you can throw this error in your queries and mutations and catch them as is in client side

Following this process will make this process streamlined
