### ISSUE TITLE
[Regression] @blitzjs/rpc requires @blitzjs/auth

### ISSUE THREAD

**Issue by adamstoffel** [blitz-js/blitz#4218]
### What is the problem?

Attempting to use the `@blitzjs/rpc` package without the `@blitzjs/auth` package causes the Next.js build to fail.

[This PR](https://github.com/blitz-js/blitz/pull/3943) was intended to decouple @blitzjs/rpc and @blitzjs/auth, however I believe a regression was introduced in [this commit](https://github.com/blitz-js/blitz/commit/37aeaa7fa2cb33be4f192ee0e29b104fcd655d5d#diff-bc92cf3a3314fe4848bf91a4fa2abe18fb477f18bba1c35007be21ef84d2dbca) (part of [v2.0.0-beta.24](https://github.com/blitz-js/blitz/releases/tag/v2.0.0-beta.24)) which re-introduced the dependency. 

Based on the code below it looks like the author probably tried to avoid the hard dependency using `import()`, but this still triggers a failed build when `@blitzjs/auth` is not installed.

### Paste all your error logs here:

Output of `npm run build` without `@blitzjs/auth` installed:
```
✔ Next.js was successfully patched with a React Suspense fix
✔ Routes manifest was successfully generated
- info Linting and checking validity of types
Failed to compile.

./node_modules/@blitzjs/rpc/dist/chunks/invoke.mjs
Module not found: Can't resolve '@blitzjs/auth'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@blitzjs/rpc/dist/index-browser.mjs
./node_modules/@blitzjs/next/dist/index-browser.mjs
./src/pages/_app.tsx


> Build failed because of webpack errors
- info Creating an optimized production build .
```

### Paste all relevant code snippets here:

From [`package/blitz-rpc/src/client/invoke.ts`](https://github.com/blitz-js/blitz/blob/main/packages/blitz-rpc/src/client/invoke.ts):
```
  if (isServer) {
    const {getBlitzContext} = await import("@blitzjs/auth").catch((e) => {
      throw new Error(
        `invoke with isServer parameter can only be used in a Blitz powered Nextjs app directory. Make sure you have installed the @blitzjs/auth package.`,
      )
    })
```

### What are detailed steps to reproduce this?

1. Run `blitz new` and choose Minimal - no DB, no auth
2. `npm uninstall @blitzjs/auth`
3. `npm run build`
4. Build fails - `@blitzjs/rpc` is still accessing `@blitzjs/auth` in `@blitzjs/rpc/dist/chunks/invoke.mjs`

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.33 (global)
Blitz version: 2.0.0-beta.33 (local)
Windows 11 | win32-x64 | Node: v18.17.1


 Package manager: npm

  System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
    Memory: 16.94 GB / 31.84 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @blitzjs/auth: Not Found
    @blitzjs/next: 2.0.0-beta.33 => 2.0.0-beta.33
    @blitzjs/rpc: 2.0.0-beta.33 => 2.0.0-beta.33
    @prisma/client: Not Found
    blitz: 2.0.0-beta.33 => 2.0.0-beta.33
    next: 13.4.5 => 13.4.5
    prisma: Not Found
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.8.4 => 4.9.5
```

**Comment by siddhsuresh** [comment]
@adamstoffel yeah, I think you are right. Not sure what the best strategy to fix it yet, but will work on it.
