### ISSUE TITLE
The last release `beta.34` did not make it to npm

### ISSUE THREAD

**Issue by tordans** [blitz-js/blitz#4231]
### What is the problem?

At https://www.npmjs.com/package/blitz the current version is `2.0.0-beta.33` which is what is used with the new-command.

One has to force the `.34` manually to get https://github.com/blitz-js/blitz/releases/tag/v2.0.0-beta.34

**Comment by siddhsuresh** [comment]
Sorry about the @tordans. Updated in npm now
