### ISSUE TITLE
Error when using Blitz with Next.js: Cannot find module 'next/dist/client/resolve-href

### ISSUE THREAD

**Issue by truenone** [blitz-js/blitz#4239]
### What is the problem?

I'm encountering an issue while using Blitz, to create Next.js projects. After following the installation steps as mentioned in the guide, I'm getting the following error:

### Paste all your error logs here:

```
Error: Cannot find module 'next/dist/client/resolve-href'
Require stack:
- C:\Users\PC\Desktop\IXWithBlitz\IXDevelopment\node_modules\.pnpm\@blitzjs+next@2.0.0-beta.34_izxue7oh7l7g5chsmd5ntkhdhq\node_modules\@blitzjs\next\dist\index-server.cjs
- C:\Users\PC\Desktop\IXWithBlitz\IXDevelopment\next.config.js
```

### next.config.js
```js
// @ts-check
const { withBlitz } = require("@blitzjs/next")

/**
 * @type {import('@blitzjs/next').BlitzConfig}
 **/
const config = {}

module.exports = withBlitz(config)
```

### What are detailed steps to reproduce this?

1. Create a new directory for your Next.js project.
2. Install Blitz using the recommended method, for example: npm install -g blitz.
3. Initialize a new Blitz project: blitz new my-blitz-app.
4. Navigate to the project directory: cd my-blitz-app.
5. Start the development server: blitz dev.
6. Observe the error mentioned above.

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.34 (global)
Blitz version: 2.0.0-beta.34 (local)
Windows 11 | win32-x64 | Node: v18.14.0


 Package manager: pnpm

  System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 5500
    Memory: 5.97 GB / 15.90 GB
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.34 => 2.0.0-beta.34
    @blitzjs/next: 2.0.0-beta.34 => 2.0.0-beta.34
    @blitzjs/rpc: 2.0.0-beta.34 => 2.0.0-beta.34
    @prisma/client: 4.6.1 => 4.6.1
    blitz: 2.0.0-beta.34 => 2.0.0-beta.34
    next: 13.4.5 => 13.4.5
    prisma: 4.6.1 => 4.6.1
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.8.4 => 4.9.5
```

### Please include below any other applicable logs and screenshots that show your problem:

I've tried to follow the provided troubleshooting link (https://nextjs.org/docs/messages/next-config-error), but it didn't resolve the issue. This error seems related to the 'next' module, specifically 'next/dist/client/resolve-href'.

**Comment by truenone** [comment]
Ok. Just update "next"  to "next": "13.5.4"

Its solved my problem.

**Comment by tordans** [comment]
https://github.com/blitz-js/blitz/pull/4237
