### ISSUE TITLE
`blitz start` server crashes when running `blitz generate`

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#426]
### What is the problem?

`blitz start` server crashes

### Steps to Reproduce: 

1. `blitz new myapp`
2. `cd myapp`
3. `blitz start`
4. In another terminal, run `blitz generate all project`
5. Server crashes with error:

```
[ info ]  bundled successfully, waiting for typecheck results...
[ ready ] compiled successfully - ready on http://localhost:3000
'next dev' failed with status code: null
```

### Versions:

```
macOS Catalina | darwin-x64 | Node: v12.16.2

blitz: 0.8.2 (global)
```

**Comment by MrLeebo** [comment]
@flybayer I can't repro this in blitz 0.10.0, can you check again to see if it's already been resolved?

**Comment by flybayer** [comment]
I can't repro either!
