### ISSUE TITLE
duplicate files added with the generator

### ISSUE THREAD

**Issue by fcristel** [blitz-js/blitz#4266]
### What is the problem?

it seems like the generator ads duplicate files?

### Paste all your error logs here:

```
PASTE_HERE (leave the ``` marks)
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```
√ Pick your new app template » Full - includes DB and auth (Recommended)
√ Install dependencies? » yarn
√ Pick a form library (you can switch to something else later if you want) » Formik (Recommended)
Hang tight while we set up your new Blitz app!
CREATE    .env
CREATE    .env.local
CREATE    .env.test
CREATE    .eslintrc.js
CREATE    .eslintrc.json
CREATE    README.md
CREATE    db\dev.db
CREATE    db\index.ts
CREATE    db\migrations\.keep
CREATE    db\schema.prisma
CREATE    db\seeds.ts
CREATE    integrations\.keep
CREATE    mailers\.keep
CREATE    mailers\forgotPasswordMailer.ts
CREATE    next-env.d.ts
CREATE    next.config.js
CREATE    package.json
CREATE    public\favicon.ico
CREATE    public\logo.png
CREATE    src\app\auth\components\ForgotPasswordForm.tsx
CREATE    src\app\auth\components\LoginForm.tsx
CREATE    src\app\auth\components\LogoutButton.tsx
CREATE    src\app\auth\components\ResetPasswordForm.tsx
CREATE    src\app\auth\components\SignupForm.tsx
CREATE    src\app\auth\forgot-password\page.tsx
CREATE    src\app\auth\layout.tsx
CREATE    src\app\auth\login\page.tsx
CREATE    src\app\auth\mutations\changePassword.ts
CREATE    src\app\auth\mutations\forgotPassword.test.ts
CREATE    src\app\auth\mutations\forgotPassword.ts
CREATE    src\app\auth\mutations\login.ts
CREATE    src\app\auth\mutations\logout.ts
CREATE    src\app\auth\mutations\resetPassword.test.ts
CREATE    src\app\auth\mutations\resetPassword.ts
CREATE    src\app\auth\mutations\signup.ts
CREATE    src\app\auth\reset-password\page.tsx
CREATE    src\app\auth\signup\page.tsx
CREATE    src\app\auth\validations.ts
CREATE    src\app\blitz-auth-config.ts
CREATE    src\app\blitz-client.ts
CREATE    src\app\blitz-server.ts
CREATE    src\app\error.tsx
CREATE    src\app\layout.tsx
CREATE    src\app\loading.tsx
CREATE    src\app\page.tsx
CREATE    src\app\styles\Home.module.css
CREATE    src\app\styles\globals.css
CREATE    src\app\users\hooks\useCurrentUser.ts
CREATE    src\app\users\queries\getCurrentUser.ts
CREATE    src\auth\components\LoginForm.tsx
CREATE    src\auth\components\SignupForm.tsx
CREATE    src\auth\mutations\changePassword.ts
CREATE    src\auth\mutations\forgotPassword.test.ts
CREATE    src\auth\mutations\forgotPassword.ts
CREATE    src\auth\mutations\login.ts
CREATE    src\auth\mutations\logout.ts
CREATE    src\auth\mutations\resetPassword.test.ts
CREATE    src\auth\mutations\resetPassword.ts
CREATE    src\auth\mutations\signup.ts
CREATE    src\auth\schemas.ts
CREATE    src\blitz-client.ts
CREATE    src\blitz-server.ts
CREATE    src\core\components\Form.tsx
CREATE    src\core\components\LabeledTextField.tsx
CREATE    src\core\layouts\Layout.tsx
CREATE    src\pages\404.tsx
CREATE    src\pages\_app.tsx
CREATE    src\pages\_document.tsx
CREATE    src\pages\api\rpc\[[...blitz]].ts
CREATE    src\pages\auth\forgot-password.tsx
CREATE    src\pages\auth\login.tsx
CREATE    src\pages\auth\reset-password.tsx
CREATE    src\pages\auth\signup.tsx
CREATE    src\pages\index.tsx
CREATE    src\styles\Home.module.css
CREATE    src\styles\globals.css
CREATE    src\users\hooks\useCurrentUser.ts
CREATE    src\users\queries\getCurrentUser.ts
CREATE    test\index.test.tsx
CREATE    test\setup.ts
CREATE    test\utils.tsx
CREATE    tsconfig.json
CREATE    types.ts
CREATE    vitest.config.ts

√ Retrieving the freshest of dependencies
√ Resolving packages
√ Fetching packages
√ Linking dependencies
√ Building fresh packages
✔ Next.js was successfully patched with a React Suspense fix
Duplicate page detected. \src\app\auth\mutations\changePassword.ts and \src\auth\mutations\changePassword.ts both resolve to /api/rpc/changePassword.
Duplicate page detected. \src\app\auth\mutations\forgotPassword.ts and \src\auth\mutations\forgotPassword.ts both resolve to /api/rpc/forgotPassword.
Duplicate page detected. \src\app\auth\mutations\login.ts and \src\auth\mutations\login.ts both resolve to /api/rpc/login.
Duplicate page detected. \src\app\auth\mutations\logout.ts and \src\auth\mutations\logout.ts both resolve to /api/rpc/logout.
Duplicate page detected. \src\app\auth\mutations\resetPassword.ts and \src\auth\mutations\resetPassword.ts both resolve to /api/rpc/resetPassword.
Duplicate page detected. \src\app\auth\mutations\signup.ts and \src\auth\mutations\signup.ts both resolve to /api/rpc/signup.
Duplicate page detected. \src\app\users\queries\getCurrentUser.ts and \src\users\queries\getCurrentUser.ts both resolve to /api/rpc/getCurrentUser.
✔ Routes manifest was successfully generated
√ Committing your app

 Your new Blitz app is ready! Next steps:

### What are detailed steps to reproduce this?

1. updated to latest with npm install -g blitz@latest
2. fresh install using blitz new [name]

### Run `blitz -v` and paste the output here:

```
PASTE_HERE (leave the ``` marks)
```
Blitz version: 2.0.0 (global)
Blitz version: 2.0.0 (local)
Windows 11 | win32-x64 | Node: v20.9.0

 Package manager: npm

  System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 12.97 GB / 31.74 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.3 - ~\AppData\Roaming\npm\npm.CMD
  npmPackages:
    @blitzjs/auth: 2.0.0 => 2.0.0
    @blitzjs/next: 2.0.0 => 2.0.0
    @blitzjs/rpc: 2.0.0 => 2.0.0
    @prisma/client: 5.4.2 => 5.4.2
    blitz: 2.0.0 => 2.0.0
    next: 13.5.4 => 13.5.4
    prisma: 5.4.2 => 5.4.2
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.8.4 => 4.9.5

**Comment by siddhsuresh** [comment]
sorry about this @fcristel, I see that the stable release to `npm` has some outdated code, will be fixed in a new patch.
