### ISSUE TITLE
deploy failed on vercel

### ISSUE THREAD

**Issue by gengjiawen** [blitz-js/blitz#4303]
Repro: https://github.com/gengjiawen/blitzjs-demo
Image:
![CleanShot 2024-02-21 at 21 50 13@2x](https://github.com/blitz-js/blitz/assets/3759816/eeaf0688-dcb7-424c-8ee5-66b7020a17b2)

              @gengjiawen can you open an issue for this? I can't help without more information or a repro. Thanks!

_Originally posted by @siddhsuresh in https://github.com/blitz-js/blitz/issues/4299#issuecomment-1956577459_

**Comment by gengjiawen** [comment]
@siddhsuresh Can you take a look, thx.

**Comment by tordans** [comment]
@gengjiawen can you be a bit more specific? Thanks!

We are also having this problem...

**Comment by siddhsuresh** [comment]
thanks for the issue @gengjiawen! I will take a look today. 

Does this happen locally for you? Since I am no longer able to replicate this after the latest fix.

**Comment by gengjiawen** [comment]
> Does this happen locally for you

If you refer to the deploy issue, The deploy issue only happens on nextjs. My local yarn start works.

**Comment by siddhsuresh** [comment]
okay thanks for the info. will keep that in mind and debug

**Comment by cfragkos** [comment]
probably related to #4309. Please fix it fast

**Comment by gengjiawen** [comment]
@siddhsuresh vercel also breaks this, not sure it's the same problem.

Repro is use this in app router api
```ts
async function handle(req: Request) {
  const ctx = await getBlitzContext()
  if (!ctx.session.userId) {
    return new Response("Unauthorized", { status: 401 })
  }
```
Error:
```console
⨯ Error: Internal Blitz Error: globalThis.__BLITZ_SESSION_COOKIE_PREFIX is not set
    at prefix (/var/task/.next/server/chunks/3637.js:93:126631)
    at Object.COOKIE_CSRF_TOKEN (/var/task/.next/server/chunks/3637.js:93:126968)
    at /var/task/.next/server/chunks/3637.js:93:107389
    at Generator.next (<anonymous>)
    at /var/task/.next/server/chunks/3637.js:93:105600
    at new Promise (<anonymous>)
    at __async$1 (/var/task/.next/server/chunks/3637.js:93:105378)
    at getBlitzContext (/var/task/.next/server/chunks/3637.js:93:107231)
    at handle (/var/task/.next/server/app/api/claude/route.js:1:1912)
    at /var/task/node_modules/.pnpm/next@13.5.4_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0_sass@1.71.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:14:39754
```

**Comment by siddhsuresh** [comment]
@gengjiawen where is `getBlitzContext` being imported from? if you are importing from "@blitz/auth" instead import it from "app/blitz-server"

**Comment by gengjiawen** [comment]
> @gengjiawen where is `getBlitzContext` being imported from? if you are importing from "@blitz/auth" instead import it from "app/blitz-server"

import from blitz-server will result in build error.

```
Attempted import error: 'setupBlitzServer' is not exported from '@blitzjs/next' (imported as 'setupBlitzServer').
```

**Comment by gengjiawen** [comment]
since this has been 3 weeks, I  have created https://github.com/blitz-js/blitz/pull/4311 to fix this issue.

**Comment by flybayer** [comment]
Hey folks, we have investigated, can reproduce, but so far are unable to understand what is happening on Vercel.

Are any of you able to reach out to Vercel support and enlist their help?

**Comment by cfragkos** [comment]
Yes I am in contact, and got them to investigate, they were quick to blame the 3rd party dependency, but I pressed them after investigating the source code that the way tou import and use debug is not wrong and it's their problem, so it seems they will look into it, I suggest you also reach out because you have more technical knowledge to explain than me

**Comment by cfragkos** [comment]
Got my answer today
```
Hi again,

Thank you for waiting. I have reviewed this issue with our team's framework-related expert and can confirm that investigating why the "debug" package is not working on Next.js 14 would require implementation-level debugging which is not in the purview of this support team.

The Blitz.js repo is the best place for this, so, that you're able to get support from framework developers and maintainers.

If there are any other platform-related Qs or issues that you may have, do let me know!

```
