### ISSUE TITLE
BlitzRoutes: Support app router

### ISSUE THREAD

**Issue by Syarx** [blitz-js/blitz#4306]
### What do you want and why?

Currently the Blitz Routes generates objects only from pages and not app

**Comment by florian-klemt** [comment]
+1

**Comment by Vandivier** [comment]
+1

**Comment by Vandivier** [comment]
+1

**Comment by tordans** [comment]
@siddhsuresh was this issue closed during the big cleanup when everything was closed or is it actually a the message "we don't consider this relevant for blitz"?

It looks like https://www.flightcontrol.dev/blog/fix-nextjs-routing-to-have-full-type-safety has the logic, but what is missing is the generator, right?
