### ISSUE TITLE
[Feature] Run prettier on output of `blitz generate`

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#440]
### What do you want and why?

All files generated by `blitz generate` should be automatically formatted by Prettier

### Possible implementation(s)

Probably this should be added to `write()` inside `packages/generator/src/generator.ts`

**Comment by lednhatkhanh** [comment]
I would like to take this issue, is it ok?

**Comment by simonpeterdebbarma** [comment]
@lednhatkhanh Yes, assigning this Issue to you. Feel free to create a Pull Request.
