### ISSUE TITLE
yarn upgrade blitz prompts for @prisma/cli version selection

### ISSUE THREAD

**Issue by harris1717** [blitz-js/blitz#448]
### What is the problem?

`yarn upgrade blitz` can't find any versions for "@prisma/cli" that matches "2.x". A version list is given to choose from. I've had luck with the latest beta (2.0.0-beta.4 at this time). A similar situation occurs for @prisma/client.

### Steps to Reproduce: 

1. Run `yarn upgrade blitz`.

### Versions:

```
debug: local
debug: pkgPath: C:\Users\Jru\Code\my-blitz\voting\node_modules\@blitzjs\cli

Windows 10 | win32-x64 | Node: v12.16.0

blitz: 0.8.2 (global)
blitz: 0.9.0-canary.1 (local)
```

### Supporting Documentation

Please include applicable logs and screenshots that show your problem.

![image](https://user-images.githubusercontent.com/8636691/81096541-8c85a080-8ed4-11ea-8a62-2afb620ee530.png)

package.json
```json
{
  "name": "voting",
  "version": "1.0.0",
  "scripts": {
    "start": "blitz start",
    "build": "blitz db migrate && blitz build",
    "lint": "eslint --ignore-path .gitignore --ext .js,.ts,.tsx .",
    "test": "echo \"No tests yet\""
  },
  "browserslist": [
    "defaults"
  ],
  "prettier": {
    "semi": false,
    "printWidth": 110
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged && pretty-quick --staged",
      "pre-push": "blitz test"
    }
  },
  "lint-staged": {
    "*.{js,ts,tsx}": [
      "eslint --fix",
      "git add"
    ]
  },
  "dependencies": {
    "@prisma/cli": "2.x",
    "@prisma/client": "2.x",
    "blitz": "0.9.0-canary.1",
    "react": "experimental",
    "react-dom": "experimental"
  },
  "devDependencies": {
    "@types/react": "16.x",
    "@typescript-eslint/eslint-plugin": "2.x",
    "@typescript-eslint/parser": "2.x",
    "babel-eslint": "10.x",
    "eslint": "6.x",
    "eslint-config-react-app": "5.x",
    "eslint-plugin-flowtype": "4.x",
    "eslint-plugin-import": "2.x",
    "eslint-plugin-jsx-a11y": "6.x",
    "eslint-plugin-react": "7.x",
    "eslint-plugin-react-hooks": "3.x",
    "husky": "4.x",
    "lint-staged": "10.x",
    "prettier": "2.x",
    "pretty-quick": "2.x",
    "typescript": "3.x"
  },
  "private": true
}
```

**Comment by wKovacs64** [comment]
Hey @harris1717, can you check if you are still experiencing this issue with `blitz@0.9.1`?

Your `package.json` looks like the dependency updater might have failed while running `blitz new` (e.g. due to loss of network connectivity). Those `Y.x` dependency versions are part of the Blitz app template but a successfully generated project should resolve those to actual version numbers (which would prevent the issue described here). #479 was merged recently to address Prisma and React versions in the event of a failed dependency update, however.
