### ISSUE TITLE
Find an alternative to REPL#setupHistory

### ISSUE THREAD

**Issue by Skn0tt** [blitz-js/blitz#458]
### What do you want and why?

https://github.com/blitz-js/blitz/blob/e12d17b6c14e29d8fd179e44e9b6d9ceceee8240/packages/cli/src/commands/console.ts#L67

[`REPL#setupHistory`](https://nodejs.org/dist/latest-v12.x/docs/api/repl.html#repl_replserver_setuphistory_historypath_callback) is not available in Node v10, see #454 for reference.

We'll need to find a way around using that :D

### Possible implementation(s)

Maybe there's some way to re-implement or polyfill setupHistory on our side?

### Additional context

![A cute duck](https://media.giphy.com/media/82nxC1u2BC8VU1wiZq/giphy.gif)

**Comment by Blanen** [comment]
I found: https://medium.com/@tjwebb/a-custom-node-repl-with-history-is-not-as-hard-as-it-looks-3eb2ca7ec0bd
