### ISSUE TITLE
[Meta] GitHub Codespaces

### ISSUE THREAD

**Issue by Skn0tt** [blitz-js/blitz#459]
### What do you want and why?

During [Satellite 2020](https://githubsatellite.com), GitHub announced [Codespaces](https://github.com/features/codespaces). It's basically a cloud-based VS Code that's displayed in the browser.
This is a great feature for Blitz, as it enables us to remove the whole development env setup from the process.
It definitely has the potential to make contributing to Blitz a lot easier.

### Possible implementation(s)

- Sign up for Early Access
- Figure out how our development environment should look
  - Which version of Node.js should be installed?
  - Which VS Code extensions do we want to be installed?
- Implement that! 😄

### Additional context

![A dog coding on Codespaces](https://media.giphy.com/media/kudIERso2pFiE/source.gif)

**Comment by Zeko369** [comment]
We could also setup a workflow with postgres fairly easily, because we can set it up in the initial container setup rather than using sqlite3

**Comment by flybayer** [comment]
I requested early access!

Putting this in the icebox until there's something actionable for us to do.
