### ISSUE TITLE
Blitz console does not work in plain JS projects

### ISSUE THREAD

**Issue by tmns** [blitz-js/blitz#461]
### What is the problem?

In a freshly generated JS project, attempting to access the `db` object within `blitz console` causes a `ReferenceError` to be thrown.  

This in turn blocks you from being able to interact with the db via the console, such as performing queries like `db.question.findMany().then(console.log)`, which is given as an example in the tutorial here: https://github.com/blitz-js/blitz/blob/canary/TUTORIAL.md#playing-with-the-api.

### Steps to Reproduce:

1. `blitz new myapp --js`
2. `cd myapp`
3. Follow the steps in either the default `index.js` page or the [relevant tutorial section](https://github.com/blitz-js/blitz/blob/canary/TUTORIAL.md#creating-models) for editing your model and migrating your DB
4. `blitz console`
5. Attempt to access the db object, like so:
```bash
$ blitz console
[..snip..]
◢ Loading your codeCouldn't find tsconfig.json. tsconfig-paths will be skipped
✔ Loading your code
⚡️ > db.question.findMany().then(console.log)
Thrown:
ReferenceError: db is not defined
```

Note there is also an error about `tsconfig.json` that is printed out next to the first `Loading your code`. I'm not sure if that is actually related to the reference error though.

### Versions:

```
Linux 4.13 | linux-x64 | Node: v12.3.1

blitz: 0.8.1 (global)
```

---

# Update from @flybayer 

The core issue is the node repl is unable to load es modules.

You can add an error log statement to [this line](https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/utils/load-blitz.ts#L50) to see the following error for every file it's loading.

```
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.exports.forceRequire (/Users/b/c/blitz/packages/cli/src/utils/module.ts:7:10)
    at /Users/b/c/blitz/packages/cli/src/utils/load-blitz.ts:45:24
    at Array.map (<anonymous>)
/Users/b/c/blitz/examples/plain-js/app/projects/mutations/deleteProject.js:1
import db from 'db';
```

So we need to find a way to load these into the repl. Maybe we have to compile them to cjs first??

**Comment by flybayer** [comment]
I updated this issue title and added extra details to the original post.

The core issue is the plain js node repl crashes when loading esmodules. We need to find a way around this.

**Comment by enzoferey** [comment]
Would using [esm](https://www.npmjs.com/package/esm) to replace `require` [here](https://github.com/blitz-js/blitz/blob/828c8d2f23024f35461a260d7ddb9368dbbe63b4/packages/cli/src/utils/module.ts#L5) be an option ?

**Comment by flybayer** [comment]
@enzoferey oooh, that's a good idea! Definitely worth trying.

The other thing I thought about trying is using `babel-node`

**Comment by enzoferey** [comment]
I will try to fix this in either way 👍
