### ISSUE TITLE
Create package for official Blitz installers

### ISSUE THREAD

**Issue by aem** [blitz-js/blitz#462]
### What do you want and why?

We need a place to publish official Blitz installers, similar to how Gatsby hosts all installers inside [`gatsby-recipes`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-recipes/recipes). 

### Possible implementation(s)

These can either go inside the `blitz` monorepo or in their own repo, I don't have strong feelings about that. 

This package **does not** need to be published to npm, the installer will download the raw source files from Github and run them directly (to be discussed in a future issue).

**Comment by flybayer** [comment]
Done
