### ISSUE TITLE
Write tests for installer executors 

### ISSUE THREAD

**Issue by aem** [blitz-js/blitz#466]
### What do you want and why?

The installer executors are currently untested, we should write some tests for those to prevent regression given their core nature.

### Possible implementation(s)

- [ ] Base executor functions
- [ ] Add dependency executor
- [ ] File prompt
- [ ] File transform executor
- [ ] New file executor

**Comment by rembrandtreyes** [comment]
I would like to tackle this, but my testing skills are severely lacking. I tried implementing some tests, but couldn't get much out of them. @aem do you have any recommendations for documentation/articles I could read to get a rundown on how to test some of these installer files.
