### ISSUE TITLE
Write tests for installer class

### ISSUE THREAD

**Issue by aem** [blitz-js/blitz#467]
### What do you want and why?

The core installer class is untested right now. It's not too worrying given that there's not much logic there, it just calls a bunch of functions in order, but I assume we'll need to eventually add more logic there so we should have tests in place for when that happens

**Comment by ganeshmani** [comment]
I would like to work on this issue if that's okay.

**Comment by flybayer** [comment]
@ganeshmani yeah for sure! Ask @aem if you have any questions :)

**Comment by aem** [comment]
@ganeshmani yes absolutely!

**Comment by merelinguist** [comment]
It’d be nice to have instructions on how recipe authors can write tests too.

**Comment by aem** [comment]
definitely. with the TS-based recipes that's pretty simple, i think we may have to provide a test runtime for the MDX recipes which will definitely require a bit more thought

**Comment by flybayer** [comment]
@ganeshmani did you make any progress on this? If not that's fine, we can unassign you so someone else can try.

**Comment by ganeshmani** [comment]
@flybayer Sorry for not being active on this issue. yeah, you can unassign me from this issue since working on a tight schedule.

**Comment by flybayer** [comment]
Ok, no problem! :)
