### ISSUE TITLE
Feature request: Stripe Recipe

### ISSUE THREAD

**Issue by needcaffeine** [blitz-js/blitz#477]
### What do you want and why?

To make Blitz the first choice framework for makers, it would be great to have Stripe integration so we can quickly go from a blank slate to selling products on the site.

### Possible implementation(s)

This can likely be achieved as a Blitz installer. Stripe integration I believe just requires a serverless endpoint and configuration. Might need to explore this more before suggesting how exactly it could work.

**Comment by flybayer** [comment]
Great request @needcaffeine!

What are the exact use cases that you want to be made easy?

This can certainly be added as a Blitz installer, once installers are ready to use. Might also be an opportunity for a plugin too.

**Comment by needcaffeine** [comment]
What I envision is an equivalent to say Laravel, where one can bake an entire application with auth all the way to Stripe checkout integration, and focus only on their business problems. Stripe currently supports [Checkout](https://stripe.com/payments/checkout), which takes care of a LOT for us. Just something to keep in mind for installers/plugins.

**Comment by flybayer** [comment]
@needcaffeine How does Laravel do this and what do you like and not like about it?

**Comment by dwightwatson** [comment]
[Laravel Cashier](https://laravel.com/docs/7.x/billing) is actually more of a wrapper around Stripe's subscription service, with PDF invoice generation. It used to support Braintree too but that was later removed when it couldn't maintain feature parity. It does support one-off payments but it's not really the primary focus.

**Comment by needcaffeine** [comment]
@flybayer Apologies, I don't actually know how Laravel does this because I don't use it. I just happened to notice that it's a pain point for me and other makers because I recently made a thing, and then had to go digging into documentation to make payments work. Maybe it _isn't_ a thing you want Blitz to focus on, which I totally understand.

**Comment by flybayer** [comment]
Ok yeah that makes sense. This can definitely be added as an installer/recipe once that support is added.

**Comment by mbrookson** [comment]
Could this be implemented with the new Stripe portal feature? 👀 has kind of like an oauth redirect flow.

https://youtu.be/u8H6awDJVpM

**Comment by alfonmga** [comment]
I'm not sure if this is related, but how do I can get the raw body of a request? this is needed for verify Stripe webhooks.

https://flaviocopes.com/express-get-raw-body/

**Comment by Khaledgarbaya** [comment]
Hey Folks, I have working example using Blitz and Stripe checkout/portal. I don' think that a recipe will be a good choice here because it will introduce a lot of files and people can do this differently. However I will happy to add a simple example to the repo. If that's ok with you I can do ion the upcoming days

**Comment by flybayer** [comment]
@Khaledgarbaya yeah, that'd be a good starting point at least!

**Comment by tmcw** [comment]
Setting up subscriptions requires quite a few moving parts! I've set up a PR for review against a vanilla Blitz app. Would love some input on it, and thoughts on whether it could be translated to a recipe: https://github.com/placemark/blitz-saas/pull/1
