### ISSUE TITLE
[RFC] Code of Conduct

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#5]
## Request For Comments

**This is a proposal for the Blitz Code of Conduct.**

Please share any and all feedback. 

It's heavily inspired from [Hood.ie](http://hood.ie/code-of-conduct/).

---

# The Blitz Community Code of Conduct

The Blitz core members take this CoC **very** serious. All members, contributors and volunteers in this community are required to act according to the following Code of Conduct. You are required to follow these guidelines to keep Blitz a positive, growing project and community and help us provide and ensure a safe environment for everyone.

## Responsibility and Enforcement

If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact us immediately: contact Brandon Bayer ([Twitter](https://twitter.com/flybayer) | [Email](mailto:b@bayer.ws)). We are here to help you. Your reports will be taken seriously and not dismissed or argued with.

## What We Believe and How We Act

- We are committed to providing a friendly, safe and welcoming environment for everyone, regardless of age, body size, culture, ethnicity, gender expression, gender identity, level of experience, nationality, personal ability or disability, physical appearance, physical or mental difference, race, religion, set of skills, sexual orientation, socio-economic status, and subculture. We welcome people regardless of these or other attributes.
- Our community is based on mutual respect, tolerance, and encouragement.
- We believe that a diverse community where people treat each other with respect is stronger, more vibrant and has more potential contributors and more sources for ideas. We aim for more diversity.
- We are kind, welcoming and courteous to everyone.
- We’re respectful of others, their positions, their skills, their commitments and their efforts.
- We’re attentive in our communications, whether in person or online, and we’re tactful when approaching differing views.
- We are aware that language shapes reality. Thus, we use inclusive, gender-neutral language in the documents we provide and when we talk to people. When referring to a group of people, we aim to use gender-neutral terms like “team”, “folks”, “everyone”. (For details, we recommend [this post](https://modelviewculture.com/pieces/gendered-language-feature-or-bug-in-software-documentation)).
- We respect that people have differences of opinion and criticize constructively.

## Don'ts 

- Don’t discriminate against anyone.
- Sexism and racism of any kind (including sexist and racist “jokes”), demeaning or insulting behaviour and harassment are seen as direct violations to this Code of Conduct. Harassment includes offensive verbal comments related to age, body size, culture, ethnicity, gender expression, gender identity, level of experience, nationality, personal ability or disability, physical appearance, physical or mental difference, race, religion, set of skills, sexual orientation, socio-economic status, and subculture. Harassment also includes sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, inappropriate physical contact, and unwelcome sexual attention.
- On Slack and other online or offline communications channels, don't use overtly sexual nicknames or other nicknames that might detract from a friendly, safe and welcoming environment for all.
- Don’t be mean or rude.
- Respect that some individuals and cultures consider the casual use of profanity offensive and off-putting.
- Unwelcome / non-consensual sexual advances over Slack or any other channels related with this community are not okay.
- Derailing, tone arguments and otherwise playing on people’s desires to be nice are not welcome, especially in discussions about violations to this Code of Conduct.
- Please avoid unstructured critique.
- Likewise any spamming, trolling, flaming, baiting or other attention-stealing behavior is not welcome.
- Sponsors of Blitz are also subject to this Code of Conduct. In particular, sponsors are required to not use sexualized images, activities, or other material which is not according to this Code of Conduct.

## Consequences for Violations to this Code of Conduct

If a participant engages in any behavior  violating this Code of Conduct, the core members of this community will take any action they deem appropriate, including warning the offender or expulsion from the community, exclusion from any interaction and loss of all rights in this community.

## Decisions About Consequences of Violations

Decisions about consequences of violations of this Code of Conduct are made by this community’s core members and may not be discussed with the person responsible for the violation.

## For Questions or Feedback

If you have any questions or feedback on this Code of Conduct, we’re happy to hear from you.

## Thanks for the Inspiration To

- [Hood.ie](http://hood.ie/code-of-conduct/)

**Comment by merelinguist** [comment]
Looks great! Very comprehensive 👍

**Comment by jasonblalock** [comment]
Looks great to me!

Need a `)` in the second to last bullet, "What We Believe..." section:

> (For details, we recommend this post.

**Comment by robdrosenberg** [comment]
Awesome to see a new project making it a priority for everyone to feel included and empowered! Well done @flybayer

**Comment by mabadir** [comment]
Looks great. I’d recommend creating a twitter account for Blitz that people can follow and interact with the community.

**Comment by D8ATech** [comment]
Seems like a common sense CoC.  Sorry it has to be spelled out but if anyone has a problem with it they should probably not be involved.

**Comment by flybayer** [comment]
Adopted via #9!

**Comment by aem** [comment]
Something that may be great to add on top of what's here is examples of how we expect our team to handle conflicts + reports. [WeAllJS](https://wealljs.org/code-of-conduct) has a good example here - clear steps the team will take with complains, as well as actual dialogue examples of how situations will be handled.

**Comment by flybayer** [comment]
Great idea @aem — that's a very good CoC! I'll open a PR soon with improvements.
