### ISSUE TITLE
ArangoDB Example or Plugin

### ISSUE THREAD

**Issue by mysticaltech** [blitz-js/blitz#505]
### What do you want and why?

I would love support for the [ArangoDB](https://www.arangodb.com/) multi-model DB, as it's a key-value, Document, Graph Database, and Search Engine all in one! Unbeatable quality and technological architecture. It would be a perfect match.

They don't support GraphQL out of the box but it would be easily implementable with their JS client  https://github.com/arangodb/arangojs coupled with a tool like https://github.com/prisma-labs/graphql-yoga.

Graph databases are really the future, it opens the mind and data modeling becomes much more natural.

Thanks and keep up the good work!

**Comment by flybayer** [comment]
Hey @mysticaltech, this is totally possible today! Prisma 2 is included by default, but it's trivially to remove Prisma and use ArangoDB today. No changes needed.

For a really nice DX like we have with Prisma (for CLI commands, code scaffolding, etc), we'll need to add a blitz plugin for Arango. Plugins are lower priority than authentication, which we are working on now. So it'll be a little time before we have plugin support.

**Comment by flybayer** [comment]
Going to close this since this is a more niche request. Happy to take a PR to add a recipe though
