### ISSUE TITLE
Most new lines are removed from template files for plain JS apps

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#509]
### What is the problem?

Most new lines are removed from template files for plain JS apps

Example for `db/index.js`:

```
import { PrismaClient } from "@prisma/client"
export * from "@prisma/client"
const prisma = new PrismaClient()
export default prisma
```

### Steps to Reproduce

1. `blitz new myapp --js`
2. Inspect `myapp/db/index.js` and see that it doesn't match the template at `packages/generator/templates/app/db/index.ts`

This also happens for `blitz generate`

### Versions

```
latest canary branch
```

**Comment by merelinguist** [comment]
Related: https://github.com/microsoft/TypeScript/issues/843#issuecomment-210254059

**Comment by flybayer** [comment]
Note: Try adding `retainLines` option to `@babeljs/generator`
