### ISSUE TITLE
When generating app using `blitz new`, move styles from `index.tsx` to a separate `styles.ts` file

### ISSUE THREAD

**Issue by emgoto** [blitz-js/blitz#515]
### What do you want and why?

When generating a new app using `blitz new`, I think all the styles inside of `index.tsx` should live in a separate `styles.ts` file.

This is just a matter of personal opinion but I did feel when I opened that `index.tsx` file for the first time that it looked pretty messy with everything in one file! Of course I removed everything in the index code straightaway anyway (and most people will probably do the same), but I think it's good if you start off a bit more opinionated about where people should put their styles.

### Possible implementation
```js
/* styles.ts */
import css from 'styled-jsx/css'

export default css`div { color: green; }`

/* index.tsx */
import styles, from './styles'

<div>
    <style jsx>{styles}</style>
    // imagine rest of code here
</div>
)
```

**Comment by dwightwatson** [comment]
If we accept that most developers are going to dump everything on the launch home page by default, should it just be wrapped up in a component that is bundled with Blitz? That way it's dead simple to remove the boilerplate.

**Comment by flybayer** [comment]
Thanks for the suggestion @emgoto!

I'm 50/50 on this. Having it all in one file makes it easy to delete it all, but you are right that it's a bit overwhelming.

**Comment by flybayer** [comment]
Let's leave the styles in the index file as is. However we could compact the styles to make them take up less room. A PR for that is welcome :)
