### ISSUE TITLE
Extract `usePaginatedQuery` out of `useQuery` into a separate hook

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#517]
### What do you want and why?

Currently the blitz `useQuery` hook wraps both `useQuery` and `usePaginatedQuery` from react-query. This has caused a hook violation (https://github.com/blitz-js/blitz/issues/334) so we need to switch to having a separate `usePaginatedQuery` hook, just like react-query.

### Possible implementation(s)

Start in this file: https://github.com/blitz-js/blitz/blob/canary/packages/core/src/use-query.ts

And separate out the paginated hook to `use-paginated-query.ts`

**Comment by eliasjohansson** [comment]
I can work on this, do you mind if I do #239 at the same time? :)

**Comment by flybayer** [comment]
@eliasjohansson  Cool! Yeah, that probably makes sense to do all three at once. You can assign these issues to yourself and mark as `status/assigned`
