### ISSUE TITLE
[RFC] Database seeding

### ISSUE THREAD

**Issue by Zeko369** [blitz-js/blitz#531]
### What do you want and why?

Create a CLI command to run seeds

### Possible implementation(s)

Template apps should add `seeds.ts` file in db folder, we should also add to docs that you can have `seeds/index.ts` so people could split seeds into multiple files for larger projects.

We should discuss adding `faker` as a dependency by default (it's quite large) and generating seeds by default (asking people first on model generation)

### Example

Create 5 categories, 50% of which are published. Then create at least 5 links for each of them (could be 5-10 links), each link has optional description (50% of the time it's not set)

```ts
import { name, lorem } from 'faker';
import db from 'db';

const seeds = (): Promise<any> => {
	const categories = await Promise.all(
		repeat(5, () => db.category.create({
			title: name.title(),
			published: maybe(0.5)
		}))
	);

	return await Promise.all(
		categories.map((category) =>
	    	repeat(randomNumberOffset(5, 5), () =>
      			db.link.create({
					title: name.title(),
					description: maybeValue(0.5, lorem.paragraph()),
					category
				})
    		)
  		)
	)
};

export default seeds;
```

I think we should think about this in the future [prisma transactions](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/transactions#future-transaction-support-in-prisma-client)

### Cleanup before seeds, example

```ts
// If we can import clean function from seeds.ts file we use that before running seeds, otherwise we ask the User it they would like to run db:reset before

const clean = () => Promise<any> => {
	// keep first 4
	return await db.category.deleteMany({ where: { id: { gt: 4 } } });
}

export { clean }
```

### Helpers

Adding nice helpers will keep code clean and more readable, also some of these will make it easier to reuse code (create parent -> create children for each parent, we can do this with prisma for smaller stuff but when you're 3 layers deep in Prisma create object not even Prisma Slack can help you 😆 )

```ts
// Math.random() > x
maybe(x);

// maybe(0.3) ? faker.name.title() : undefined;
maybeValue(0.3, faker.name.title());

// Random number in range 5 - 8 (`5 + Math.floor(Math.random() * 3)`)
randomNumberOffset(5, 3);

// returns array of [20, ..., 20]
await Promise.all(repeat(10, () => Promise.resolve(10)));
// Shorter and more readable version of this
await Promise.all(Array.from(new Array(10), () => Promise.resolve(10)));
```

**Comment by merelinguist** [comment]
Great idea!

**Comment by flybayer** [comment]
Thanks Fran! 

I think we probably shouldn't add faker by default and also don't add any seeds by default. The default seed file can have some example code commented out.

The helpers are a good idea, but I think we should be very conservative about what helpers we add, if any. There's already a ton of npm packages for similar things. 

I think adding helper functions and suggested libraries to documentation would be a great way to solve this.

**Comment by Zeko369** [comment]
Agree with not using faker by default, but suggesting it in the comments.

I think that we should give people the right abstractions for seeding. `maybe` and `maybeValue` would make the code a lot more readable compared to just using `Math.random() > x`. If we give them to users in a form of docs not everyone will use them, but if we have them in the standard library, a lot more people will use them and we'll get the desirable effect of having a standardised way of seeding the DB in all blitz apps (convention over configuration)

**Comment by flybayer** [comment]
Arguably, you don't really need any abstractions for data seeding. It's fairly straightforward stuff :)

I think convention over configuration applies more at higher level things. I.e. the fact that we have a way to seed your database. *How* you actually do your seeding doesn't need to be standardized because everyone's requirements are different.

**Comment by Zeko369** [comment]
Ok, I'll create functions for seeding, and we can just keep these helpers in docs
