### ISSUE TITLE
blitz-next-compilation: Refactor next server scripts out to a separate package.

### ISSUE THREAD

**Issue by ryardley** [blitz-js/blitz#54]
Problem
* We want to build Blitz so that the components that maintain dependencies to specific core downstream technology decisions are kept together. 
* We should not couple the args parser with the scripts the args parser calls because we should be able to substitute out the args parser for something else at a later point.
* `@oclif` imposes restrictions sets up expectations on how the CLI package is built and tested.

Solution

We should relocate the `dev`, `prod` and `build` scripts alongside the `withBlitz` next config helper to a `@blitzjs/server` package. The idea of this package is to control the server runtime. This should be the only _node_ based package that holds a dependency conceptual or otherwise to next.js. 

Exceptions

Isomorphic code in `@blitzjs/core` that accesses `next/router` can be considered more of an "application" concern rather than a "server" concern and thus remain in `core` have it's own adaptor to next. This makes sense if you think hypothetically about a different stack such as express/react router.

**Comment by flybayer** [comment]
Awesome, this sounds great
