### ISSUE TITLE
Add ability to run blitz start production without building code

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#540]
### What do you want and why?

Services like render have different memory limits for build vs run step. So we need build the code in the build step and then only run the code in the run step. But currently `blitz start --production` rebuilds the code even if the code is already built.

### Possible implementation(s)

We could add a new command or command argument.

Or

We can change `blitz start --production` to use the built assets if they exist. We would add some type of checksum that makes it easy to verify that the code has not changed since the code was built. If the code has changed, then we run a new build.

I really think we should do the later.

cc @ryardley thoughts on this?

**Comment by ryardley** [comment]
Yep I agree. If the assets have been changed they should be rebuilt.

**Comment by ryardley** [comment]
Should we make it so all builds are idempotent like this but only fire if source files have changed?
