### ISSUE TITLE
Make blitz server stop and log a nice error if it finds duplicate react pages

### ISSUE THREAD

**Issue by ryardley** [blitz-js/blitz#55]
Ensure that Blitz throws and error when there are duplicate pages within the app folder.

**Comment by merelinguist** [comment]
@ryardley Could you give an example of what a duplicate page looks like?

**Comment by ryardley** [comment]
When two pages get compiled to a single page output the synchronizer should whinge instead of silently clobber.

The following should raise an Error:

```
/app/users/pages/help.tsx
/pages/help.tsx
```
