### ISSUE TITLE
Link CLI tool and @blitzjs/* packages

### ISSUE THREAD

**Issue by enzoferey** [blitz-js/blitz#558]
### What is the problem?

When linking the package for local development, other packages under `@blitzjs/*` are not linked as well.

### Steps to Reproduce

1. Run `yarn dev`.
2. Run `yarn link-cli`.
3. Create a new project with `blitz new`.
4. Run `yarn link "blitz"` inside the project.
5. Run any `blitz` command, the usage type will be `local` instead of expected (?) `global-linked`.

### Versions

```
local
debug: local
debug: pkgPath: /Users/enzoferey/Documents/myapp/node_modules/@blitzjs/cli 

macOS Catalina | darwin-x64 | Node: v12.14.1

blitz: 0.11.0 (global)
blitz: 0.11.0 (local)
```

### Other

Of course, doing a manual `yarn link` on the `@blitzjs/*` packages directly allow you fix the issue temporally, but I feel this is not the expected behaviour.

### Possible solutions

What is stopping us from moving the `global-link` condition to the first position of the [chain](https://github.com/blitz-js/blitz/blob/canary/packages/blitz/src/bin/cli.ts#L35) ? In which cases would it cause unexpected behaviour ?

Also, I wonder what's the meaning of [this](https://github.com/blitz-js/blitz/blob/canary/packages/blitz/src/bin/cli.ts#L20) condition. Wouldn't be checking data in the `package.json` based on `pkgDir.sync(__dirname)` more reliable ?

**Comment by flybayer** [comment]
Hey, this does sound like it can be improved.

You're welcome to try tweaking that `cli.ts` file. Just know it's quite tricky to get everything working correctly, including when published to npm. And from what you've described, I'm not sure if this is the issue. But again you're welcome to try!

I haven't done multi package development like this before, so I'm not sure what to expect.

You can also look at [how redwood is handling this](https://github.com/redwoodjs/redwood/blob/master/CONTRIBUTING.md#local-development) to maybe get some good ideas.

**Comment by MrLeebo** [comment]
And even after you `yarn link` everything, I would always get the [invalid hook call warning](https://reactjs.org/warnings/invalid-hook-call-warning.html) in the new app. That's with identical React/ReactDOM versions between the app and blitz. They don't resolve to the same instance using `yarn link`. I found it easiest to just test local development changes using the examples/store app and undo the changes before committing.

**Comment by flybayer** [comment]
Yeah, that's what I do too (develop on the store example)

**Comment by enzoferey** [comment]
Understood, makes sense indeed, I didn't think about using examples as development environment.

I think this issue doesn't have any reason of being anymore, so I'm closing.

Do you think we should add this recommendation to the `CONTRIBUTING` docs ? Let me know over here 👍

**Comment by flybayer** [comment]
@enzoferey ok, yeah it'd be great to add this to the contributing docs, but add it here: https://github.com/blitz-js/blitzjs.com/blob/master/docs/how-to-contribute.mdx because the website will go live very soon
