### ISSUE TITLE
[Easy] Upgrade Next to 9.4.4

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#570]
### What do you want and why?

Upgrade Next to 9.4.4 in all the package.json's in our repo.

**NOTE: this is super easy change, so veterans, please leave it for a new Blitz contributor or someone new to contributing to open source :)**

**Comment by kevotovar** [comment]
Can I take this issue?

**Comment by jclancy93** [comment]
@kevotovar go for it! Just assigned you 🙂

**Comment by kevotovar** [comment]
Thanks!
