### ISSUE TITLE
DB is imported in generated api routes, even if it isn’t used

### ISSUE THREAD

**Issue by merelinguist** [blitz-js/blitz#572]
### What is the problem?

Even if I’m not using a database, Blitz still expects it to be there to use queries. 

### Steps to Reproduce

1. Create a project

2. Delete the `db` directory

3. Create a query

4. Output looks like this:

```
import {rpcHandler} from '@blitzjs/server'
import resolver from 'app/_rpc/queries/scrapeRecipe'
import db from 'db'
export default rpcHandler('query', 'scrapeRecipe', resolver, () => db.connect())
```

### Versions

```
debug: local
debug: pkgPath: /Users/dylan/dev/recipes/node_modules/@blitzjs/cli 

macOS Catalina | darwin-x64 | Node: v14.0.0

blitz: 0.11.0 (global)
blitz: 0.11.0 (local)
```

**Comment by flybayer** [comment]
Ah yeah! This will move into the prisma plugin eventually, but for now we can probably just wrap a try/catch around `require(db)` and also change to `db && db.connect()`

**Comment by MykalMachon** [comment]
I'd like to take a stab at this if no one else is working on it! 
seems like a good place to get started with contributing 😃

**Comment by ivandevp** [comment]
Go ahead @MykalMachon! 👍
