### ISSUE TITLE
Long unresponsive delay after starting `blitz console`

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#579]
### What is the problem?

There's a several second delay after starting `blitz console` where it is unresponsive.

The loading spinner appears saying "loading code" which is fine and correct, but after that finishes and the prompt appears, it's frozen.

Maybe there's something being loaded after the spinner is marked as success?

### Steps to Reproduce

1. `blitz console`
2. Try to type stuff as soon as the prompt appears

### Versions

```
0.12.0
```

**Comment by jportela** [comment]
I'll tackle this 👀

**Comment by alkamin** [comment]
On `0.17.1-canary.4` I'm still experiencing this.

**Comment by flybayer** [comment]
Someone needs to dig into this and figure out exactly what is causing the delay. Then we can figure out the proper fix.

**Comment by flybayer** [comment]
Duplicate of https://github.com/blitz-js/blitz/issues/1098
