### ISSUE TITLE
Implement the `mutate` function for `useQuery`

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#582]
### What do you want and why?

We need to add a `mutate` function that's returned from `useQuery`. This allows you to manually update the query cache without refetching from the network.

- [ ] `mutate` must be fully typed for Typescript usage. The input type is the same as the query function return type.
- [ ] After being called, `mutate` must automatically trigger a refetch for the initial query to ensure it has the correct data

```tsx
export default function (props}) {
  const [product, {mutate}] = useQuery(getProduct, {where: {id: props.id}})

  return (
    <Formik
      initialValues={product}
      onSubmit={async (values) => {
        try {
          const product = await updateProduct(values)
          mutate(product)
        } catch (error) {
          alert("Error saving product")
        }
      }}>
      {/* ... */}
    </Formik>
  )
}
```

**Comment by eliasjohansson** [comment]
I'll have a go at this today :)
