### ISSUE TITLE
[RFC] New Link component

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#585]
### What do you want and why?

A new Link component that's much easier to use that the default Next.js Link!

1. The Next.js `Link` component is terribly cumbersome to use:

```js
<Link href="/products/[id]" as={'/products/' + product.id}>
  <a>{product.name}</a>
</Link>
```

2. You can't use this Link component to link to external sites.
3. It doesn't have a way to set "active link" styles.

## Proposal

I think this is the best option I've considered. It's quite natural and intuitive. And it doesn't require you to think about what the actual page is named.

```js
<Link href={'/products/' + product.id}>
  {product.name}
</Link>
```

Other Next.js link options will still be supported, like `replace` and `scroll`

### Active Styles

Active styles are applied when `href === pathname`

`activeClassName: string`

```js
<Link href={'/products/' + product.id} activeClassName="active">
  {product.name}
</Link>
```
`activeStyle`: a normal React `style` object applied when the current link is active

```js
<Link href={'/products/' + product.id} activeStyle={{fontWeight: 'bold'}}>
  {product.name}
</Link>
```

### Linking to External Sites

We can support linking to other sites by rendering a plain `<a>` tag if `href` includes a protocol (`://`)

```js
<Link href="http://blitzjs.com">
  Blitz
</Link>

<Link href="mailto://hey@example.com">
  Blitz
</Link>
```

### Href as an Object

Same format as Next.js

```js
<Link href={{ pathname: '/products/' + product.id, query: { sort: 'asc' } }}>
  {product.name}
</Link>
```

### Converting Next apps to Blitz apps

People with existing Next apps will be importing `Link` from `next/link`, so this will continue to work as expected. But if they change to import `Link` from `blitz`, then they will need to update the usage of Link. This could probably be done via a codemod.

## Implementation 

This is complex to implement because we must compute a route manifest at build time and use that during runtime to map this api to what Next requires. But it's totally possible.

- We need to use `React.forwardRef`

---

What do you all think about this? Any other rough spots with the Next.js Link that we can improve?

**Comment by merelinguist** [comment]
Yes yes yes! Looks awesome!

**Comment by devilcoders** [comment]
I think it would be great to expose a function to figure out if link is active. The `===` is not always the rule. You may have subpath, but you want to highlight parent as active.

**Comment by ryardley** [comment]
Great idea. Not so sure about the idea of including styling within the link component. Ideally we want to manage the link behaviour and stay out of styling. In fact we would probably want to delegate all styling to whatever system the user is using such as styled-components etc. I would vote for a render prop to manage active etc. 

```tsx
<Link href={'/products/' + product.id} >
  {({active}) => (
    <MyStyledProductName active={active}>product.name</MyStyledProductName>
  )}
</Link>
```

**Comment by franky47** [comment]
For the linking to external sites, it would be probably better to always render an anchor tag, for semantics and routing to work the hard way if the bundle is not finished loading/hydrating.

Also, mailto addresses can also be `mailto:foo@bar.com`, without the double slash.

**Comment by flybayer** [comment]
> For the linking to external sites, it would be probably better to always render an anchor tag, for semantics and routing to work the hard way if the bundle is not finished loading/hydrating.
> 
> Also, mailto addresses can also be `mailto:foo@bar.com`, without the double slash.

Absolutely. What I meant is that we render an `<a>` element without the Next router attached to it.
