### ISSUE TITLE
Switch from `next.config.js` to `blitz.config.js`

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#59]
`blitz.config.js` will be the same as `next.config.js` except that it automatically adds the `withBlitz` config wrapper.

- [x] Change Blitz server to use `blitz.config.js`, but transform it to `next.config.js` with the `withBlitz` wrapper
- [x] Update examples to use the `blitz.config.js`

**Comment by ryardley** [comment]
Gonna have a look at this tonight.

**Comment by ryardley** [comment]
Started working on this and got distracted as I noticed a few simpler and modular ways we can implement the synchroniser. Will throw up a hack for this tomorrow so it works and refactor the synchroniser later.

**Comment by flybayer** [comment]
Ok sounds good! @ryardley

**Comment by flybayer** [comment]
Closed in #130
