### ISSUE TITLE
Blitz warns about api routes in global `/pages` folder

### ISSUE THREAD

**Issue by ryardley** [blitz-js/blitz#597]
### What is the problem?

We want to make upgrading a next app to blitz super easy. Currently adding blitz to a next app warns about having `/api` routes in the global pages folder. 

This should only warn if you add an api folder to a pages folder within `/app`

### Steps to Reproduce

1. In a blitz app create a global `/pages` folder and add and `/pages/api` route to it. 
1. Try to start Blitz this should not show a warning. 

Note warnings should show if you attempt to add `api` routes to `pages` folders nested under `/app`

### Versions

```
debug: local
debug: pkgPath: /Users/rudiyardley/projects/yatou/yatou/node_modules/@blitzjs/cli 

macOS Catalina | darwin-x64 | Node: v12.16.1

blitz: 0.12.0 (global)
blitz: 0.12.0 (local)
```

### Other
![image](https://user-images.githubusercontent.com/1256409/83370707-84515000-a403-11ea-883d-9c5d78680b1f.png)

**Comment by flybayer** [comment]
As you might have guessed, I don't think we should do this 😅 

Like we discussed in #471, I totally agree on making it easy to migrate Next apps to Blitz apps. However, I don't think we should introduce inconsistencies in Blitz features based on Next-to-blitz migrations.

Supporting `/pages/api` but not `/app/pages/api` is going to be confusing to people who start using Blitz without any knowledge of Next.

We can do all of the migration stuff with a Recipe. We can support running this inside any Next.js project. One command to do everything for you.

```
npx blitz install blitz
```

**Comment by ryardley** [comment]
What is wrong with being compatible with next? If we do this we get huge adoption wins. Next compatibility is pretty much the #1 thing this project has going for it. If you throw it out you loose users. 

Try and put yourself in the shoes of someone who has a large next codebase and want to try blitz. 

Relying on an installer is a really bad idea because: 
* People want to try blitz because it is Next++ 
* It becomes more and more likely you will diverge from an easy manual next migration - we will end up with more and more steps to convert a next app to a blitz app - this is definitely a bad thing!
* If I have to maintain a large codebase the last thing I want to do is run a magic installer on it just to try some of blitz's features.
* People cannot try blitz and change their minds. How do you reverse the installer?
* People cannot adopt blitz incrementally and slowly migrate their routes. Incremental adoption is really important.

There is no technical reason why we can't easily ensure Next compatibility and I am convinced not doing so is a mistake. 

Changing the `next.config.js` to `blitz.config.js` could be considered branding but really anything beyond that is just a pain and should be totally unnecessary when we are enhancing next with scalable architecture and persistence.

**Comment by ryardley** [comment]
A solution that would be a win for both would be to display a warning when nesting within the global next  `/pages` folder but still allow it for compatability reasons.

**Comment by ryardley** [comment]
A second compromise is to remove the warning and allow api routes optionally within pages. That way you ensure consistency throughout. The docs need not have any examples like this. We can talk about api being next to pages as the blitz folder structure but quietly support anything next allows out of the box. I think I prefer this compromise and attitude more.

**Comment by flybayer** [comment]
> Next compatibility is pretty much the # 1 thing this project has going for it. If you throw it out you loose users.

Ok, you made some great points, and I now better understand where you are coming from. :)

Let's support `pages/api` everywhere. Root and nested inside `app/`
