### ISSUE TITLE
BUG on generated routes with --context

### ISSUE THREAD

**Issue by osirvent** [blitz-js/blitz#600]
### What is the problem?
bug on import generated route for queries and mutations when `--context` is used

### Steps to Reproduce

1. `blitz g all project --context=marketing`
2. 
<img width="641" alt="imagen" src="https://user-images.githubusercontent.com/5927133/83393819-bbb9ff80-a3f7-11ea-895f-762e56b8e3fd.png">
3.
<img width="609" alt="imagen" src="https://user-images.githubusercontent.com/5927133/83394022-1fdcc380-a3f8-11ea-93de-2b5d6de865a0.png">

### Versions

```
debug: local
debug: pkgPath: /Users/osirvent/dev/blitzjs/tests/test2/node_modules/@blitzjs/cli 

macOS Catalina | darwin-x64 | Node: v12.17.0

blitz: 0.12.0 (global)
blitz: 0.12.0 (local)
```

### Other

Please include applicable logs and screenshots that show your problem.

**Comment by flybayer** [comment]
Uh oh! Thank you for opening an issue! :)

**Comment by peaonunes** [comment]
Happy to took at it.

**Comment by flybayer** [comment]
@peaonunes you bet!
