### ISSUE TITLE
Validate that the GUI works on Windows

### ISSUE THREAD

**Issue by merelinguist** [blitz-js/blitz#604]
### What do you want and why?

Just landed the initial GUI PR, and it would be awesome if someone could check if it all works on Windows. I think I’ve mostly done things the right way but I don’t have access to a machine to check!

### Possible implementation(s)

1. Fork, clone the repo, etc
2. `cd packages/gui`
3. `yarn start`
4. Open `localhost:3000`
4. Click through the app and note anything which doesn’t work

**Comment by MykalMachon** [comment]
Hi @merelinguist :wave:! 
I just noticed the PR landed, great work to yourself and all the other contributors, it looks awesome :tada:

I'm on a windows machine and am currently in the process of testing the GUI out! 

So far, the only thing that I've noticed is **that GUI seems to error out if yarn isn't installed** ( I don't have yarn on my machine, but I'm installing it right now) if this is the case, I would think we should either
1. document that yarn is a requirement for the gui
2. create an issue for this and develop a fallback where when yarn isn't found, npm is used. 

I will get back to you after I've installed yarn and let you know if everything else seems to work :+1: again, great work i'm stoked on the GUI.

**Comment by merelinguist** [comment]
Wow, thanks so much for this work, @MykalMachon! To summarise the issues:

- [ ] Yarn is assumed in the [project creation](https://github.com/blitz-js/blitz/blob/f53a560b84bea40f9c4e6f0c99a423b4dc10b0de/packages/gui/app/mutations/createProject.ts#L23). We should fallback on npm if Yarn is not installed. Tracked in https://github.com/blitz-js/blitz/issues/606
- [ ] The [glob regex](https://github.com/blitz-js/blitz/blob/f53a560b84bea40f9c4e6f0c99a423b4dc10b0de/packages/gui/utils/getDirMtime.ts#L7) I’ve written is not cross-platform. More on that [here](https://github.com/mrmlnc/fast-glob#how-to-write-patterns-on-windows). Tracked in https://github.com/blitz-js/blitz/issues/607

**Comment by MykalMachon** [comment]
Hi @merelinguist!
it seems that both of the issues above are now resolved and merged in so this issue can probably be marked as resolved as well correct?

If there's more work involved in validating that the GUI is working on windows let me know; I'd love to help here wherever I can 😄

**Comment by merelinguist** [comment]
Yep good spot! I’ll tune you in as we continue adding features that need to be tested x-platform ;)
