### ISSUE TITLE
[GUI] Yarn is assumed in project creation

### ISSUE THREAD

**Issue by merelinguist** [blitz-js/blitz#606]
### What is the problem?

Yarn is assumed in the [project creation](https://github.com/blitz-js/blitz/blob/f53a560b84bea40f9c4e6f0c99a423b4dc10b0de/packages/gui/app/mutations/createProject.ts#L23). We should fallback on npm if Yarn is not installed.

**Comment by jamiedavenport** [comment]
I'd like to pick this up if nobody else already plans to

**Comment by merelinguist** [comment]
@jamiedavenport Thank you, go right ahead!
