### ISSUE TITLE
Fix glob in GUI for Windows

### ISSUE THREAD

**Issue by merelinguist** [blitz-js/blitz#607]
### What is the problem?

The [glob regex](https://github.com/blitz-js/blitz/blob/f53a560b84bea40f9c4e6f0c99a423b4dc10b0de/packages/gui/utils/getDirMtime.ts#L7) I’ve written for calculating directory age is not cross-platform. More on that [here](https://github.com/mrmlnc/fast-glob#how-to-write-patterns-on-windows).

**Comment by MykalMachon** [comment]
I would love to pick this up if no one else is working on it!

**Comment by merelinguist** [comment]
@MykalMachon Super! Go right ahead. 🎆
