### ISSUE TITLE
TS is assumed in GUI project creation

### ISSUE THREAD

**Issue by merelinguist** [blitz-js/blitz#618]
### What do you want and why?

TypeScript is assumed in the [project creation](https://github.com/blitz-js/blitz/blob/f53a560b84bea40f9c4e6f0c99a423b4dc10b0de/packages/gui/app/mutations/createProject.ts#L22). We should provide an option to choose between TypeScript and JavaScript.

cc/ @jletey

**Comment by jletey** [comment]
@merelinguist Thx for opening this, I'm working on it rn :)

**Comment by flybayer** [comment]
Hey @jletey, did you make any progress on this?

**Comment by jletey** [comment]
@flybayer Sorry for my inactivity on this 😬 I'll get right on it and open a PR this weekend!

**Comment by flybayer** [comment]
@jletey ok cool, no problem :)
