### ISSUE TITLE
Open the GUI with a CLI command

### ISSUE THREAD

**Issue by merelinguist** [blitz-js/blitz#620]
### What do you want and why?

We need to bundle the GUI with the CLI, and provide a command to open it with `blitz gui`.

cc/ @peaonunes

**Comment by peaonunes** [comment]
Nice to have it as a separate issue! Can you put me as assignee ? I'm afraid I cannot assign myself.

**Comment by peaonunes** [comment]
I think we can charge it to be not ready to work. Right?

**Comment by flybayer** [comment]
Yes, icebox :)
