### ISSUE TITLE
Remove `--hostname` and `--port` from `blitz build`

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#624]
### What is the problem?

The `blitz build` command current accepts `--hostname` and `--port` but these are invalid because blitz build does not start a server. It only compiles code.

Here's the file where these need to be removed from: https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/build.ts

**Comment by ganeshmani** [comment]
@flybayer it seems like a quick fix. can i jump in and fix?

**Comment by flybayer** [comment]
@ganeshmani you bet!
