### ISSUE TITLE
Cache header in RPC calls

### ISSUE THREAD

**Issue by timsuchanek** [blitz-js/blitz#627]
If I understand correctly, in dev time,  `useQuery` directly calls the function, while it's replaced with an rpc in build time.

How can I set a cache header in that function, of e.g. `cache-control: max-age=3600` for when it's an rpc? I would like to control on a per-function level, how much I can cache and when to fetch new data.

**Comment by flybayer** [comment]
Hi Tim! Minor correction: RPC is also used in development. This works the same way webpack does, for example. Webpack does a build for both development and production.

We had a fairly long discussion on http cache headers [starting at this comment](https://github.com/blitz-js/blitz/issues/85#issuecomment-625353454). Read that discussion and let me know what you think.

**Comment by flybayer** [comment]
Ok cool. What is your use case for caching queries?

**Comment by timsuchanek** [comment]
I have a news feed, that only needs to be updated every 30min.
I would like the data to be cached (also like the next 50-200 items), so when I use a pagination query, it's immediately there in my infinite scroll.

**Comment by flybayer** [comment]
Alright, then you should be able to accomplish that with [`useQuery`](https://blitzjs.com/docs/use-query) because that provides caching.

You can custom `cacheTime` and `staleTime` to get the behavior you want.

**Note:** we also have `useInfiniteQuery` for infinite scrolling that will be in the next release in a couple days. The same cache parameters apply.

**Comment by timsuchanek** [comment]
Ok sounds good. Is `cacheTime` and `staleTime` here a frontend-only feature or will it also be propagated to the function and actually cache in the server?

**Comment by flybayer** [comment]
It's frontend only. We're adding HTTP middleware for the server (#326) that you can use to do anything custom on the backend.
