### ISSUE TITLE
Add Form.post, Form.patch, Form.delete

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#63]
Currently, Blitz provides a `Form` component that automatically does the proper fetch request.

For users who don't want to use the Form component and would rather make the request imperatively, we need to add `post`, `patch`, and `delete` as methods on the component. Then the user can use their own form stuff with an onSubmit hook that calls the Blitz `Form.[METHOD]` function.

Existing component:
```jsx
<Form action={`/api/posts/${post.id}`} method="PATCH">
</Form>
```

New APIs to add:
```
await Form.post(`/api/posts/${post.id}`, formData)
await Form.patch(`/api/posts/${post.id}`, formData)
await Form.delete(`/api/posts/${post.id}`, formData)
```

For now, don't handle errors, same as `<Form>`. Error handling is something we need to figure out.

We should start some documentation somewhere. Could probably start adding it to https://github.com/blitz-js/blitzjs.com, even though we don't have a design. We can start `mdx` files no problem.

**Comment by rishabhpoddar** [comment]
One point to keep in mind for automatic form submissions is to have CSRF protection. We are planning on storing the anti-CSRF token in the localstorage, so any automatic form submission should read from that before and then pass that as a header to the backend API.
