### ISSUE TITLE
When specifying a server port that's already in use, blitz will pick another port instead of throwing an error

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#630]
### What is the problem?

When specifying a server port like `blitz start -p 4000`, blitz should throw an error instead of picking another port.

The automatic available port detection should only be used if a specific port is not specified by the user.

The offending line of code is here: https://github.com/blitz-js/blitz/blob/canary/packages/server/src/next-utils.ts#L40

This will require a change to how we handle the `-p` argument which happens here: https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/start.ts#L17

Currently, `config.port` is always set, so `next-utils.ts` has no way to know whether to use automatic port detection or not.

So maybe we need to manually parse the input arguments here to see if the user specified a port or not: https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/start.ts#L31

### Steps to Reproduce

1. Start a server on port 3000
2. `blitz start -p 3000` -> server started on 3001 instead of throwing an error

### Versions

```
0.12.0
```

**Comment by ganeshmani** [comment]
@flybayer  i can take this issue. if that's okay

**Comment by flybayer** [comment]
@ganeshmani yes for sure! You have commit access now, so you in the future you can comment and assign it to yourself
