### ISSUE TITLE
Re-export some missing items from Next

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#634]
### What do you want and why?

We need to re-export `Error` from `next/error`. This got overlooked previously.

Also need to re-export `AppProps`, `InferGetStaticPropsType` and `InferGetServerSidePropsType` from `next`

### Possible implementation(s)

Add the re-exports in this file: https://github.com/blitz-js/blitz/blob/canary/packages/core/src/index.ts

---

This is a very simple change, so Blitz contributor veterans, please leave this for someone new to blitz or new to open-source contributing :)

**Comment by gvasquez11** [comment]
Hey there I would love to take this issue if possible :)

**Comment by flybayer** [comment]
@gvasquez11 yes, for sure! Let me know if you need help :)

**Comment by gvasquez11** [comment]
@flybayer I looked at the 'The Contributing Guide' in order to try and find how to test on my local machine since I had some failed cases :( but the link didn't work. Any advice would be much appreciated :)

**Comment by flybayer** [comment]
@gvasquez11 oops, here it is: https://blitzjs.com/docs/contributing
