### ISSUE TITLE
Rename `NextScript` to `BlitzScript`

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#635]
### What do you want and why?

Rename `NextScript` to `BlitzScript`. We are renaming everything else and this one is the oddball. 

### Possible implementation(s)

Change this line: https://github.com/blitz-js/blitz/blob/canary/packages/core/src/index.ts#L31

Then you'll also need to rename it in the following files:

- https://github.com/blitz-js/blitz/blob/canary/examples/store/app/pages/_document.tsx
- https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/app/app/pages/_document.tsx
- https://github.com/blitz-js/blitz/blob/canary/examples/tailwind/app/pages/_document.tsx
- https://github.com/blitz-js/blitz/blob/canary/examples/tailwind/app/pages/_document.tsx
- https://github.com/blitz-js/blitz/blob/canary/examples/plain-js/app/pages/_document.js

---

Blitz contributor veterans, please leave this for someone new to blitz or to open-source :)

**Comment by reymon359** [comment]
Hi there, I would like to implement this one to get used to the codebase.

**Comment by flybayer** [comment]
@reymon359 awesome, it's all yours! Let me know if you have any questions/issues :)

**Comment by reymon359** [comment]
Thank you! I will work on a Pull Request and if I need anything I will let you know :)

**Comment by ivandevp** [comment]
This issue has been done in #638
