### ISSUE TITLE
Update example apps to use Prisma 2, and new pagination

### ISSUE THREAD

**Issue by merelinguist** [blitz-js/blitz#656]
### What do you want and why?

Prisma has updated its pagination style: https://github.com/prisma/prisma/releases/tag/2.0.0-beta.7. We should update all the examples (in the `examples` folder):

1) Update the prisma dependency version to `2.0.0` for each
2) In the store example, update the blitz queries and their usage for the new Prisma version

**Comment by osirvent** [comment]
I think I could try this PR

**Comment by flybayer** [comment]
@osirvent cool, it's all yours!
