### ISSUE TITLE
Add ability to use the node debugger

### ISSUE THREAD

**Issue by osirvent** [blitz-js/blitz#666]
### What do you want and why?

Be able to easily debug a Blitz app

### Possible implementation(s)

`NODE_OPTIONS='--inspect' blitz start`

### Additional context

https://dev.to/vvo/5-steps-to-debugging-next-js-node-js-from-vscode-or-chrome-devtools-497o

**Comment by flybayer** [comment]
The issue here is that we need to pass the `NODE_OPTIONS` env variable on to `next` when we spawn it in this file: https://github.com/blitz-js/blitz/blob/canary/packages/server/src/next-utils.ts

Need to do it for both dev and production.
