### ISSUE TITLE
Prevent `blitz db migrate` from attempting to create new migration files in production.

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#670]
### What is the problem?

Currently `blitz db migrate` always runs `prisma migrate save` and `prisma migrate up`.

`migrate up` will create new migration files if needed and `migrate up` will apply existing migration files.

For safety, `migrate save` should only run if `NODE_ENV !== 'production'`. But `migrate up` should always run.

Here's the line of code where this happens: https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/db.ts#L43

**Comment by toshi1127** [comment]
I want to work in this, Can I take this issue?

**Comment by flybayer** [comment]
@toshi1127 yes!! :)

**Comment by flybayer** [comment]
Closed in #683
