### ISSUE TITLE
Add `AppProps` to new app template in `_app.tsx`

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#671]
### What do you want and why?

Update [this file](https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/app/app/pages/_app.tsx) to include `AppProps` like this:

```tsx
import { AppProps } from 'blitz'

export default function MyApp({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />
}
```

---

Open source veterans, please leave this issue for someone new to Blitz and/or open-source :)

**Comment by tehnuge** [comment]
@flybayer I made a PR for this [here](https://github.com/blitz-js/blitz/pull/674).
