### ISSUE TITLE
Add a spinner during `blitz new` when prettier is running

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#672]
### What do you want and why?

Currently there's a awkward pause during `blitz new` after dependencies are installed. It makes the user thing something is broken.

However, it's just prettier running. So we need to add a spinner so the user knows what is happening.

### Possible implementation(s)

[Right here is the code where prettier runs](https://github.com/blitz-js/blitz/blob/canary/packages/generator/src/generators/app-generator.ts#L152)

You need to add something like this:

```ts
const spinner = log.spinner(log.withBrand('Formatting your code')).start()

// on success
spinner.succeed()

// on error
spinner.fail(chalk.yellow.bold("We had an error running Prettier, but don't worry your app will still run fine :)"))
```

---

Veterans, please leave this for someone new to Blitz or open-source :)

**Comment by fnoah** [comment]
@flybayer I'd like to work on this as a first issue in order to get to know the Blitz codebase.

**Comment by flybayer** [comment]
@fnoah awesome, it's all yours! :)
