### ISSUE TITLE
Model generation making incorrect assumption based on plurality

### ISSUE THREAD

**Issue by wKovacs64** [blitz-js/blitz#696]
### What is the problem?

Generating a model with a pluralized property results in the singular version in the model instead (e.g. `votes` -> `vote`).

### Steps to Reproduce

1. `blitz generate model choice votes:int`

Results:

```
model Choice {
  id         Int      @default(autoincrement()) @id
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
  vote       Int      @default(0)
}
```

### Versions

```
debug: monorepo
debug: pkgPath: C:\dev\contrib\blitz\node_modules\@blitzjs\cli

Windows 10 | win32-x64 | Node: v12.17.0

blitz: 0.15.0 (global)
blitz: 0.15.0 (local)
```

### Other

N/A

**Comment by flybayer** [comment]
Thanks @wKovacs64! We definitely shouldn't auto pluralize or depluralize field names.

**Comment by toshi1127** [comment]
I want to work in this, Can I take this issue?

**Comment by flybayer** [comment]
@toshi1127 you bet! Next time feel free to also assign it to yourself :)
