### ISSUE TITLE
Generated pages include embedded expression braces from templates

### ISSUE THREAD

**Issue by wKovacs64** [blitz-js/blitz#698]
### What is the problem?

Super minor, but I noticed the generated pages include braces `{ }` from [inline conditional rendering logic](https://github.com/blitz-js/blitz/blob/b8e2e10288cefd637678556a80d897fd26ed74ac/packages/generator/templates/page/new.tsx#L47-L57) in the corresponding templates, like so:

```jsx
<p>
  {
    <Link href="/projects">
      <a>Projects</a>
    </Link>
  }
</p>
```

When I expected:

```jsx
<p>
  <Link href="/projects">
    <a>Projects</a>
  </Link>
</p>
```

This is not a huge deal as it still renders correctly, but I could see it surprising someone.

### Steps to Reproduce

1. `blitz generate pages project`
1. Examine any of the generated pages and find certain elements surrounded by braces

### Versions

```
debug: monorepo
debug: pkgPath: C:\dev\contrib\blitz\node_modules\@blitzjs\cli

Windows 10 | win32-x64 | Node: v12.17.0

blitz: 0.15.0 (global)
blitz: 0.15.0 (local)
```

### Other

N/A

**Comment by peaonunes** [comment]
Happy to have a look at it.

**Comment by flybayer** [comment]
@peaonunes @aem has some thoughts on this. It's not an easy thing to solve 😬

**Comment by peaonunes** [comment]
😬 oops. happy to delay that if we do not have a goto approach. I can switch collaborate to something with a higher priority.
