### ISSUE TITLE
File changes within the integration directory are not hot reloaded

### ISSUE THREAD

**Issue by Romstar** [blitz-js/blitz#701]
### What is the problem?
File changes located within the Integration directory are not hot reloaded

### Steps to Reproduce

1. Create a custom file within the Integrations directory i.e. test.ts
2. Import custom file within the server-side portion of your app
3. Modify the file and witness no update but modify any of the other files and notice the changes immediately.

### Versions

```
Linux 5.6 | linux-x64 | Node: v12.18.1

blitz: 0.15.1 (global)
```

### Other

The current workaround is to rerun the application via blitz start.

Please include applicable logs and screenshots that show your problem.

**Comment by flybayer** [comment]
This is a bit surprising to me. I thought Next should do HMR for this properly.

Definitely needs fixed.

**Comment by Romstar** [comment]
Just kidding, it seems to be working fine right now.  Not quite sure what happened there.

**Comment by flybayer** [comment]
Haha ok, feel free to re-open if it comes back :)
