### ISSUE TITLE
Tutorial documentation referencing the wrong file.

### ISSUE THREAD

**Issue by pooyatolideh** [blitz-js/blitz#709]
### What is the problem?

"Writing a minimal form" tutorial directs the user to `app/questions/pages/questions/new.tsx` to replace the `<div>` that says `Put your form fields here [...]`  but in the current Blitz setup that element appears to be inside `app/questions/components/QuestionForm.tsx`

**Note:** the entire **Writing a minimal form** seems to be slightly outdated as a result of the file changes.

### Steps to Reproduce

1. create a new Blitz app
2. follow documentation Tutorial steps all the way till "Writing a minimal form"
3. open `app/questions/pages/questions/new.tsx` and you won't see `<div>Put your form fields here [...]</div>` in there.

### Versions
macOS Catalina | Node 12.16 | Blitz 0.15.2

### Other

![image](https://user-images.githubusercontent.com/42389180/85212182-32bf2580-b31e-11ea-89fe-92e6e629f3dd.png)

![image](https://user-images.githubusercontent.com/42389180/85212208-80d42900-b31e-11ea-9aad-713b42746ded.png)

**Comment by flybayer** [comment]
@pooyatolideh hey thanks for this! We happen to have a PR already in progress to fix this over on the website repo: https://github.com/blitz-js/blitzjs.com/pull/83

So I'll go ahead and close this :)
