### ISSUE TITLE
Incomplete component example for "Adding a Vote Button" section of Tutorial

### ISSUE THREAD

**Issue by pooyatolideh** [blitz-js/blitz#710]
### What is the problem?
Currently the `[questionId].tsx` file that's autogenerated comes with a JSON print out.

Tutorial's instructions for adding a vote button only suggest adding a `<li>` code block to that file. However, there's a bit more involved, and learners won't know that until they read the completed file example. That's a bit confusing and perhaps it can be fixed using the following instructions:

```
Inside `[questionId].tsx` replace 
------
<h1>Question {question.id}</h1>
<pre>{JSON.stringify(question, null, 2)}</pre>
-----

with 

----
      <h1>{question.text}</h1>
      <ul>
        {question.choices.map((choice) => (
          <li key={choice.id}>
            {choice.text} - {choice.votes} votes
            <button onClick={() => handleVote(choice.id, choice.votes)}>Vote</button>
          </li>
        ))}
      </ul>
----
```

## Steps to Reproduce
1. Go to Blitz documentation -> tutorial
2. scroll down to this part of the tutorial:
_"Now that you’ve improved the question page, it’s time for the vote button."_

### Other

![image](https://user-images.githubusercontent.com/42389180/85213049-3f944700-b327-11ea-986c-35992c33e10a.png)

**Comment by flybayer** [comment]
@pooyatolideh thanks for this too! We just published an updated version of [the tutorial](https://blitzjs.com/docs/tutorial). I'm pretty sure the this issue is addressed. Can you review it and see?
