### ISSUE TITLE
Upgrade React Query to v2

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#712]
### What do you want and why?

[React Query v2](https://github.com/tannerlinsley/react-query/releases/tag/v2.0.0) was just released and has some breaking changes.

We need to upgrade to this version, update our usage of it as needed, and update our docs to reflect the changes.

**Comment by toshi1127** [comment]
I'd like to tackle this issue.

**Comment by flybayer** [comment]
Sweet :)

**Comment by flybayer** [comment]
Closed in #720
