### ISSUE TITLE
Update new app template Readme

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#713]
### What do you want and why?

The [current new app template readme](https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/app/README.md) is a bit outdated. We should update it to match the default new app homepage. It'd also be good to add other helpful information, like links to docs, tutorial, github, slack. 

And anything else that would be helpful.

**Comment by peaonunes** [comment]
Happy to help improving this 😄

**Comment by flybayer** [comment]
@peaonunes all yours! :)
