### ISSUE TITLE
blitz db reset broken in Prisma 2 (need to change `raw` to `rawQuery`)

### ISSUE THREAD

**Issue by johncantrell97** [blitz-js/blitz#714]
### What is the problem?
It looks like the code to reset prisma database is using PrismaClient's raw() method.  Looking at the docs for the official Prisma 2.0+ release I think they might have changed this to a method called rawQuery() instead.

I downgraded back to Prisma 2.0.0-beta6 and it was working again for me.

I was getting this error:

Resetting the database has failed with an error from the database:  TypeError: db.raw is not a function

### Steps to Reproduce

1. Add prisma with a non-beta version of Prisma 2
2. Run `blitz db reset`

### Versions

macOS Catalina | darwin-x64 | Node: v12.13.1

blitz: 0.8.1 (global)
blitz: 0.15.3 (local)

**Comment by SigurdMW** [comment]
I could look into this one. Is it just to replace the calls to `db.raw` with `db.rawQuery` in the files where it appears like this one: /packages/cli/src/commands/db.ts ?
