### ISSUE TITLE
Demo application page transitions very slow

### ISSUE THREAD

**Issue by danawoodman** [blitz-js/blitz#72]
Just pointing out something I noticed when using the demo application: it seems page transitions are very slow. On average I'm seeing 300ms-1.5sec on a 50mbps connection. 

Curious if this is expected because of the Now serverless functions being by nature slow or something else?

![](https://p198.p4.n0.cdn.getcloudapp.com/items/E0uqNPo6/Screen%20Shot%202020-03-26%20at%2010.53.36.png?v=1136409d74ba7512347d5dc832d3e786)

Running on Brave (Chromium)

**Comment by flybayer** [comment]
Hey, thanks for your interest! Yeah, that demo is not optimized and was extremely prototype code! :) But I think the main issue here is pages aren't being prefetched and the DB is in America.

We're currently deep in architecture design. The current design is way better than the initial demo!
