### ISSUE TITLE
Change model generation syntax to something that works on all terminals

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#724]
### What is the problem?

Our current model generation command for setting default values uses brackets like this:

```
blitz generate model choice votes:int:default[0]
```

But the problem is that this doesn't work in zsh (see https://github.com/blitz-js/blitz/discussions/723)

We need to find a better way to do this that works in for all terminals.

### Other

The very first thing that someone can do to help with this issue is to research available solutions and characters we could use for this that work in all terminals.

Once we agree on the best solution, then someone can make the change in the code.

**Comment by merelinguist** [comment]
See this review of terminal-safe characters from a while ago: https://github.com/vercel/next.js/issues/7607#issuecomment-503767041

**Comment by flybayer** [comment]
Also parenthesis `()` can't be used because that is command substitution in fish
