### ISSUE TITLE
Add bundle size reporting to PRs

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#747]
### What do you want and why?

I want a bot that automatically reports the bundle size on a PR here in this repo and how much it is has changed, if any.

It should report the bundle sizes of all the packages that are published.

### Possible implementation(s)

https://github.com/preactjs/compressed-size-action

**Comment by robertgrzonka** [comment]
👋🏼 I'd love to take this one!

**Comment by flybayer** [comment]
@robertgrzonka awesome, all yours! :)
