### ISSUE TITLE
Add envinfo to `blitz -v` output

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#748]
### What do you want and why?

I want to add some [`envinfo`](https://github.com/tabrindle/envinfo) output to the `blitz -v` command. envinfo is a sweet utility to get lots of debugging data easily.

Also, I would like to add a line that indicates if the package manager is npm or yarn. We already have the `has-yarn` dependency installed which can be used for that.

### Possible implementation(s)

I think the basics that we need is the output of this:

```
npx envinfo --system --binaries --npmPackages blitz,typescript,react,react-dom,@prisma/cli,@prisma/client
```

So I picture the output of `blitz -v` looking like this:

```
/t/a1> blitz -v
You are using alpha software - if you have any problems, please open an issue here:
  https://github.com/blitz-js/blitz/issues/new/choose

blitz: 0.16.4 (global)
blitz: 0.16.4 (local)

  Package manager: npm        (<-- NOTE - this added, but doesn't come from envinfo)
  System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 1.37 GB / 16.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.16.3 - /var/folders/dn/t7l73r1d08q_0djz0hz06bt80000gn/T/fnm-shell-7340312/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /var/folders/dn/t7l73r1d08q_0djz0hz06bt80000gn/T/fnm-shell-7340312/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/cli: 2.2.1 => 2.2.1
    @prisma/client: 2.2.1 => 2.2.1
    blitz: 0.16.4 => 0.16.4
    react: 0.0.0-experimental-33c3af284 => 0.0.0-experimental-33c3af284
    react-dom: 0.0.0-experimental-33c3af284 => 0.0.0-experimental-33c3af284
    typescript: 3.9.6 => 3.9.6
```

[Here's the file that where this change needs to be made](https://github.com/blitz-js/blitz/blob/canary/packages/blitz/src/bin/cli.ts#L41)

**Comment by robertgrzonka** [comment]
🙋🏼‍♂️

**Comment by chris-tse** [comment]
Hi there! If no one else has been working on this yet, I'd like to give this a try.

**Comment by flybayer** [comment]
@chris-tse awesome, it's all yours!
