### ISSUE TITLE
React Suspense error because of next-compose-plugins

### ISSUE THREAD

**Issue by simonedelmann** [blitz-js/blitz#749]
### What is the problem?
When using `next-compose-plugins` there is an error message in the browser's console:

> Warning: Cannot hydrate Suspense in legacy mode. Switch from ReactDOM.hydrate(element, container) to ReactDOM.createBlockingRoot(container, { hydrate: true }).render(element) or remove the Suspense components from the server rendered components.

### Steps to Reproduce

1. `blitz new myApp`
2. Add `<Suspense>` component in `pages/index.tsx`:

```typescript
import { Suspense } from "react"

const Home = () => (
  <Suspense fallback={null}>
    <div>Page Content</div>
  </Suspense>
)

export default Home

```

3. Add `next-compose-plugins` within `blitz.config.js`:

```typescript
const withPlugins = require("next-compose-plugins")

module.exports = withPlugins([], {
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    // Note: we provide webpack above so you should not `require` it
    // Perform customizations to webpack config
    // Important: return the modified config
    return config
  },
  webpackDevMiddleware: (config) => {
    // Perform customizations to webpack dev middleware config
    // Important: return the modified config
    return config
  },
})
```

### Versions

```
debug: blitzPkgPath: /Users/simon/Code/test/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/simon/Code/test/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js 

macOS Catalina | darwin-x64 | Node: v14.4.0

blitz: 0.16.3 (global)
blitz: 0.16.4 (local)
```

### Other

This didn't occurs in blitz 0.15.2.

**Comment by simonedelmann** [comment]
Some more information about my use case of `next-compose-plugins`: 
I need to use `next-transpile-modules` to transpile [heroicons](https://github.com/refactoringui/heroicons). 

My `blitz.config.js` looked like this:
```typescript
const nextConfig = { ... }
const withPlugins = require("next-compose-plugins")
const withTM = require("next-transpile-modules")(["heroicons"])
module.exports = withPlugins([withTM], nextConfig)
```
As `next-compose-plugins` is totally optional, a simple workaround was to avoid using it entirely:
```typescript
const nextConfig = { ... }
const withTM = require("next-transpile-modules")(["heroicons"])
module.exports = withTM(nextConfig)
```

**Comment by flybayer** [comment]
This could very well be because our internal wrapper, `withBlitz`, uses next-compose-plugins. So in this case next-compose-plugins is used twice and nested.

We can remove our internal usage if this is the case.

**Comment by flybayer** [comment]
A workaround might be to set `reactMode` in your config.

```
module.exports = {
   experimental: {
      reactMode: "concurrent", 
   },
}
```

**Comment by simonedelmann** [comment]
@flybayer I can confirm setting reactMode to `concurrent` fixes the bug. Furthermore the bug is because of multiple use of `next-compose-plugins`.
See code for some more working and non working examples. 

```typescript
const nextConfig = { ... }
const nextConfigWithConcurrent = {
  ...nextConfig,
  experimental: { reactMode: "concurrent" }
}

const withPlugins = require("next-compose-plugins")
const withTM = require("next-transpile-modules")(["heroicons"])

// Does work
module.exports = withTM(nextConfig)

// Does NOT work
module.exports = withPlugins([withTM], nextConfig) 

// Does work, because concurrentMode is set explicit.
module.exports = withPlugins([withTM], nextConfigWithConcurrent)

 // Dos NOT work, nested use of next-compose plugins overrides the experimental setting
module.exports = withPlugins([withTM], withPlugins([withTM], nextConfigWithConcurrent))
```

**Comment by flybayer** [comment]
Ok thanks!

The solution is to remove our usage of `next-compose-plugins` in [`with-blitz.ts`](https://github.com/blitz-js/blitz/blob/canary/packages/server/src/with-blitz.ts). Instead manually add `withTM` in there during development.

Additionally, we should change it so that `withTM` is only added during monorepo development. I can help figure out the logic for that if needed.
