### ISSUE TITLE
Add e2e tests to auth example

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#754]
### What do you want and why?

Add Cypress e2e tests to the `auth` example app. You can copy the cypress setup from the `store` example.

- Test anonymous sessions via the "track view" button
- Test sign up
- Test login & logout
- Test that anonymous session data is transferred to authenticated session data (via the "track view" button)

**Comment by rubenmoya** [comment]
Hello! I'd love to give this issue a try!

**Comment by flybayer** [comment]
Awesome @rubenmoya! Let me know if you have any questions.
