### ISSUE TITLE
Session management `authorize()` method has wrong stack trace

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#755]
### What is the problem?

In our session management, we have this method: `ctx.session.authorize('admin')` that will throw `AuthenticationError` and `AuthorizationError` depending on if the user is logged in and has the role of admin.

The problem is that we throw an error inside that function and the stacktrace the user sees is a stack trace from inside Blitz.

What we want is for the stack trace to show the call site of `ctx.session.authorize('admin')`. I'm not sure if this is possible, but I think so using `arguments.callee`.

**Comment by MrLeebo** [comment]
@flybayer Perhaps this was resolved already by another issue? When I repro this, the app code function that is calling `ctx.session.$authorize("ADMIN")` is at the front of the stack trace.

**Comment by flybayer** [comment]
ok, great!
