### ISSUE TITLE
Add tests to session management

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#757]
### What do you want and why?

We need to add comprehensive unit tests to our session management.

Feel free to submit PRs for single or few tests. And feel free to ask clarification questions.

Source file: https://github.com/blitz-js/blitz/blob/canary/packages/core/src/server/auth/sessions.ts
Unit tests: https://github.com/blitz-js/blitz/blob/canary/packages/core/src/server/auth/sessions.test.ts
Integration tests: https://github.com/blitz-js/blitz/tree/canary/test/integration/auth

**Comment by cbadger85** [comment]
I'd like to try and tackle this issue! I haven't contributed to open source before, but I'm pretty handy with jest.

**Comment by flybayer** [comment]
@cbadger85 that'd be awesome! Here's our [contributing docs](https://blitzjs.com/docs/contributing). And here's a great free egghead video on the basics of open source like forking, submitting a PR, etc: https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github

Let me know if you have any questions!

**Comment by geeklisted** [comment]
Is this issue still ready to work?  Seems there have been a couple of merges.

**Comment by flybayer** [comment]
@geeklisted yeah, still plenty to tests to add! :)

**Comment by geeklisted** [comment]
I hope to try and contribute some tests over the course of the week.  Excited to see a project heading back to the good ole' days of Web development.

**Comment by clgeoio** [comment]
@geeklisted, I am probably going to get stuck in to the server/supertokens file soon. We should coordinate our efforts :)

**Comment by swinner2** [comment]
Looks like these files have been moved around @flybayer

**Comment by flybayer** [comment]
@swinner2 original issue updated!

**Comment by flybayer** [comment]
Sufficient tests for now
