### ISSUE TITLE
blitz start command returns error- 

### ISSUE THREAD

**Issue by shimjudavid** [blitz-js/blitz#760]
### What is the problem?

blitz start command return following error- 

### Steps to Reproduce

1. blitz start

Error: Cannot find module 'next'
Require stack:
- /Users/EmaxSoftware/Apps/ReactApps/blitzapp/noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at resolveFileName (/usr/local/lib/node_modules/blitz/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/usr/local/lib/node_modules/blitz/node_modules/resolve-from/index.js:43:9)
    at module.exports (/usr/local/lib/node_modules/blitz/node_modules/resolve-from/index.js:46:47)
    at module.exports (/usr/local/lib/node_modules/blitz/node_modules/resolve-cwd/index.js:4:30)
    at resolveBinAsync (/usr/local/lib/node_modules/blitz/node_modules/@blitzjs/server/dist/server.cjs.development.js:284:35)
    at normalize (/usr/local/lib/node_modules/blitz/node_modules/@blitzjs/server/dist/server.cjs.development.js:376:28)
    at Object.dev (/usr/local/lib/node_modules/blitz/node_modules/@blitzjs/server/dist/server.cjs.development.js:1166:28)
    at Start.<anonymous> (/usr/local/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/commands/start.js:21:36)
    at Generator.next (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/EmaxSoftware/Apps/ReactApps/blitzapp/noop.js' ]
}

### Versions

```
output of `blitz --version --verbose`
```

### Other

Please include applicable logs and screenshots that show your problem.

**Comment by flybayer** [comment]
@shimjudavid sorry about that!

What's the output of `blitz --version --verbose`?

And did this happen immediately after running `blitz new blitzapp`?

**Comment by shimjudavid** [comment]
Output of blitz --version --verbose is- 
debug: blitzPkgPath: /usr/local/lib/node_modules/blitz/dist/index.js
debug: cliPkgPath: /usr/local/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js 

macOS Catalina | darwin-x64 | Node: v13.1.0

blitz: 0.16.4 (global)
blitz: 1.0.0 (local)


And this happened when I run blitz start

**Comment by shimjudavid** [comment]
blitz new blitzapp command returned following - 

You are using alpha software - if you have any problems, please open an issue here:
  https://github.com/blitz-js/blitz/issues/new/choose


Hang tight while we set up your new Blitz app!

CREATE    .babelrc.js
CREATE    .env
CREATE    .eslintrc.js
CREATE    .npmrc
CREATE    .prettierignore
CREATE    README.md
CREATE    app/components/.keep
CREATE    app/components/ErrorBoundary.tsx
CREATE    app/layouts/.keep
CREATE    app/pages/_app.tsx
CREATE    app/pages/_document.tsx
CREATE    app/pages/index.tsx
CREATE    blitz.config.js
CREATE    db/index.ts
CREATE    db/migrations/.keep
CREATE    db/schema.prisma
CREATE    integrations/.keep
CREATE    package.json
CREATE    public/favicon.ico
CREATE    public/logo.png
CREATE    tsconfig.json
CREATE    utils/.keep
CREATE    .gitignore

✔ Retrieving the freshest of dependencies
✔ Resolving packages
✖ Fetching packages
browserslist@4.13.0: The engine "node" is incompatible with this module. Expected version "^6 || ^7 || ^8 || ^9 || ^10 || ^11 || ^12 || >=13.7". Got "13.1.0"
✖ Fetching packages
Found incompatible module.
✖ We had an error running Prettier, but don't worry your app will still run fine :)

Your new Blitz app is ready! Next steps:

   1. cd blitzapp
   2. blitz start
   3. You create new pages by placing components inside app/pages/

**Comment by flybayer** [comment]
Ok @shimjudavid, I was able to reproduce. The issue is with your Node version.

I tested with Node `13.14.0` and it appears to work good.

Can you upgrade Node and try again?

**Comment by shimjudavid** [comment]
@flybayer Yes Node version was the issue. I downgraded to the latest stable version of Node which is v12.18.2 and it is working fine. Thank you.

**Comment by flybayer** [comment]
Awesome!
