### ISSUE TITLE
Inline svg Error "cannot find module" 

### ISSUE THREAD

**Issue by lauridskern** [blitz-js/blitz#763]
### What is the problem?
React inline svg throws error "cannot find module"
### Steps to Reproduce

1. Install babel-plugin-inline-react-svg
2. Add plugin to babbel config `plugins: ["inline-react-svg"]`
3. Add typescript .svg declarations to `next-env.d`

```
declare module "*.svg" {
  const content: string;
  export default content;
}
```

### Versions

`0.16.4`

### Other

Please include applicable logs and screenshots that show your problem.

**Comment by flybayer** [comment]
@lauridskern does that work in a Next.js app?

I don't think it will. I think you need to [add more babel config](https://medium.com/anna-coding/how-to-import-svg-in-next-js-with-typescript-88ebff26ce17) or instead [use a webpack loader](https://stackoverflow.com/questions/55175445/cant-import-svg-into-next-js).

**Comment by LoriKarikari** [comment]
There is [this example](https://github.com/vercel/next.js/tree/canary/examples/svg-components) in the Next.js repo and it seems it's using the same approach as @lauridskern. I'm also encountering this problem after copying the config from this example.

**Comment by flybayer** [comment]
Ok, thanks @LoriKarikari. If you haven't already, can you try with absolute import?

**Comment by flybayer** [comment]
@ryardley we have another file processing issue here

**Comment by LoriKarikari** [comment]
@flybayer I tried absolute imports too but it doesn't work.

**Comment by pbteja1998** [comment]
This bug still exists.

**Comment by nitaking** [comment]
@lauridskern 

You try it.

👇install
```bash
yarn add babel-plugin-inline-react-svg
yarn add babel-plugin-module-resolver
```

👇edit `babel.config.js`

```diff
module.exports = {
  presets: ["next/babel"],
--  plugins: [],
++  plugins: [
++    ["module-resolver", { "root": ["."] }],
++    "inline-react-svg",
++  ],
}
```

I work sample repo: https://github.com/nitaking/sample-blitz-svg-setting and commit: https://github.com/nitaking/sample-blitz-svg-setting/commit/58649f378bbce466fa43e29418c1a03260bfbb92

---
As you can see here, it looks like an Issue that exists in Nextjs.
https://github.com/vercel/next.js/issues/14892

**Comment by LoriKarikari** [comment]
Thanks for the solution @nitaking!

**Comment by paulm17** [comment]
So I went though this just now.  

Since there is *.module.scss and *.module.css in global.d.ts, can't the following be added there now?

	declare module "*.svg" {
	    const content: string
	    export default content
	}

Thanks
