### ISSUE TITLE
Add small feature to our github bot: auto set status to 'assigned' when an issue is assigned

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#773]
### What do you want and why?

We have a [custom github bot](https://github.com/blitz-js/bot-github) that automates some stuff in our repo like keeping `status/*` tags in sync with the issue's position on our Project board.

The feature I want is to automatically set the `status/assigned` label on an issue with it is marked as assigned via the github UI.

Note: **only** set `status/assigned` if an issue goes from noone assigned to someone assigned. This label should **not** be added if someone is already assigned and a second person is added to the assignment.

Let me know if you have any questions!

**Comment by rohanjulka19** [comment]
Hi, I would like to open a PR for this issue.

**Comment by flybayer** [comment]
@rohanjulka19 awesome! Let me know if you have any questions

**Comment by rohanjulka19** [comment]
Thank you for assigning, I have opened a PR in the bot-Github repo here is the link https://github.com/blitz-js/bot-github/pull/7

**Comment by flybayer** [comment]
Woohoo! It works!

Closed in https://github.com/blitz-js/bot-github/pull/7

@all-contributors add @rohanjulka19 for infra
