### ISSUE TITLE
Integrate superjson serialization & deserialization to the RPC layer

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#784]
### What do you want and why?

Switch to use [superjson](https://github.com/blitz-js/superjson) instead of `JSON.stringify` and `result.json()`.

### Possible implementation(s)

Relevant files:
- https://github.com/blitz-js/blitz/blob/canary/packages/core/src/rpc.ts
- https://github.com/blitz-js/blitz/blob/canary/packages/server/src/rpc.ts

### Additional context

Related #700

**Comment by robertgrzonka** [comment]
This sound interesting, I'd love to take it as second issue if everything works as expected in my previous PR :)

**Comment by flybayer** [comment]
@robertgrzonka awesome!

**Comment by Skn0tt** [comment]
While SuperJSON is a lot more capable than normal JSON, there's still some stuff that's not supported:

- `Map` with non-uniform key types
- `Map` with complex key types
- ES6 Classes
- potentially more ...

We'll have to address these limitations in the Docs to prevent high expectations to burn. I'd be down to write the Docs for this! :D

**Comment by flybayer** [comment]
No problem, because they will be able to do a lot more than they can now!! :)

**Comment by merelinguist** [comment]
@robertgrzonka How’s this going? 😄

**Comment by flybayer** [comment]
Btw, I just published superjson `1.1.0` which has bug fixes you will want :)

**Comment by flybayer** [comment]
@robertgrzonka have you started on this? I need it finished within a day, so I can take over if you want!

**Comment by Skn0tt** [comment]
> While SuperJSON is a lot more capable than normal JSON, there's still some stuff that's not supported:

Forget about this - SuperJSON will support all of these in the coming days ^^ Maybe I'm a bit over-confident, but I don't think users will notice any edge cases once Blitz.js properly integrated SuperJSON. No Docs required then ;D

**Comment by flybayer** [comment]
Hey @robertgrzonka, I'm going ahead and working on this. Hopefully you hadn't started 😬 I'm really sorry about this. I didn't realize I needed this so suddenly this week 😕. Hopefully there's no hard feelings!
