### ISSUE TITLE
Upgrade everything to eslint v7 - internal code and in the new app template

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#821]
### What do you want and why?

`eslint-config-react-app` [relatively recently added support for eslint v7](https://github.com/facebook/create-react-app/pull/8978) so we can upgrade all our internal tooling to to the latest eslint packages and we can upgrade all the eslint packages [in the new blitz app template](https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/app/package.json)

I think this task should be fairly straightforward. Updating the major version numbers in the new app template will be manual, but all the other eslint packages in the repo should be able to be upgraded via the `yarn upgrade-interactive --latest` command.

**Comment by nettofarah** [comment]
hey, @flybayer. My friend @pragmaticivan and I wanted to try and tackle this issue together.
Here's pt1 https://github.com/blitz-js/blitz/pull/852

Thanks!
