### ISSUE TITLE
Happy path scaffolding is not unforgiving

### ISSUE THREAD

**Issue by hegelstad** [blitz-js/blitz#826]
### What is the problem?
![image](https://user-images.githubusercontent.com/6997343/89216909-90a48580-d5cb-11ea-840c-9df7479112bd.png)

### Steps to Reproduce

1. Add additional attributes (manually) to the first model generated.
2. Press create a "..."
3. Get an alert that values for the additional attributes are missing.

### Versions

```
debug: blitzPkgPath: /Users/nikolai/github/edusight-app/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/nikolai/github/edusight-app/node_modules/@blitzjs/cli/lib/src/index.js

macOS Catalina | darwin-x64 | Node: v12.16.1

blitz: 0.17.0 (global)
blitz: 0.17.0 (local)```

### Other

Please include applicable logs and screenshots that show your problem.

**Comment by flybayer** [comment]
@hegelstad sorry for such a long delay in responding!! 

You're absolutely right this is not great. We have a plan to fix this, but it requires some other changes to the CLI and generators. So I'm going to put this in the icebox for now, but we'll definitely fix this as soon as we can.

**Comment by flybayer** [comment]
Closing in favor of https://github.com/blitz-js/blitz/issues/259
