### ISSUE TITLE
Blitz recipes failing on Ubuntu Server

### ISSUE THREAD

**Issue by jose-donato** [blitz-js/blitz#833]
### What is the problem?
I am trying to use the new feature blitz recipes (blitz install tailwind) and i'm getting typescript errors.
### Steps to Reproduce

1. `blitz new test`
2. `cd test`
3. `blitz install tailwind`

### Versions

```
Linux 5.4 | linux-x64 | Node: v12.18.3

blitz: 0.17.0 (global)
blitz: 0.17.0 (local)
```

### Other

Typescript errors:
![image](https://user-images.githubusercontent.com/43375532/89331409-a2e4f900-d689-11ea-8b65-de1886d4bf09.png)

**Comment by flybayer** [comment]
Sorry about that @jose-donato! It appears to be a platform compatibility issue with Linux. We'll get it fixed.

**Comment by flybayer** [comment]
cc @aem

**Comment by jose-donato** [comment]
No worries. thanks for the awesome framework and the fast reply. Looking forward to start contributing!

**Comment by aem** [comment]
Oops. I know what's going on here. For local Blitz dev we don't need to manually install the types because it's always running through the yarn workspace, but for prod builds the types aren't included. I'll add those to the existing recipes and update the docs as well

**Comment by aem** [comment]
I'm no longer totally sure what's going on here. On a Linux VM with a brand new `node`/`npm`/`yarn`/`blitz` setup I was able to create a new app and install the recipe without a problem.

@jose-donato is there any chance you generated a plain JS project rather than a TS project?

**Comment by jose-donato** [comment]
Yes, of course. I'll try that as soon as i can.

**Comment by aem** [comment]
Oops sorry for the confusion, I wasn't asking you to generate your own JS project, but if you generated a JS project instead of TS then this would make sense, that's all

**Comment by jose-donato** [comment]
Oh, sorry. I misunderstood. Nop, i just used `blitz new <name>`

**Comment by jose-donato** [comment]
Tried with another linux distro (Lubuntu 19.04) and it is working fine!

**Comment by aem** [comment]
Interesting. I wonder if the server distro does something weird with symlinks, temp directories, or how child processes get access to the filesystem. Any of those three could cause this. I'll do a little more digging, but good to know at least that it's limited to a specific distro

**Comment by jose-donato** [comment]
Just to give a little update, i tried again in the same machine and it worked. I don't know if i was being noob in the first time or it was really an error. 

Anyway thanks for the help!

**Comment by aem** [comment]
Glad to know it's working now, even if we don't know why! 😆 I'm going to close for now but let us know if this reappears!
