### ISSUE TITLE
Update RPC generation with new Prisma connect function

### ISSUE THREAD

**Issue by merelinguist** [blitz-js/blitz#838]
### What do you want and why?

Prisma [`2.4` ](https://github.com/prisma/prisma/releases/tag/2.4.0) deprecated several top-level client methods, including one which we use, `prisma.connect`. This means that using any Blitz queries or mutations will result in a console warning about the deprecated usage.

### Possible implementation(s)

This is the offending line: https://github.com/blitz-js/blitz/blob/canary/packages/server/src/stages/rpc/index.ts#L93

`db.connect` needs to be swapped for `db.$connect`.

### Additional context

Note that this is sort of a breaking change, since Prisma would have to be upgraded by the user for this to work, but it would be better to fix it earlier rather than later, imo.

**Comment by flybayer** [comment]
For backward comparability, if `.$connect` exists, use it, otherwise use `.connect`

**Comment by agoxlea** [comment]
I'm new here. Can I take this one?
