### ISSUE TITLE
Generate typescript types when `blitz generate all <model>`

### ISSUE THREAD

**Issue by jose-donato** [blitz-js/blitz#842]
### What do you want and why?

Wouldn't be interesting if when we run `blitz generate all <model>` created a folder (and file inside it) with the typescript types for the model?
For example, if I am creating a model called Category, it would also generate a folder called "types" and inside it a file called "CategoryType.ts". 
The contents would be, for example:
```
type CategoryType = {
    id?: string;
    name: string;
    url: string;
    items: any;
}
export default CategoryType
```

This would be useful when we want to use the Category somewhere. If I need to use the category types as props i would just import this type:

![image](https://user-images.githubusercontent.com/43375532/89662312-cac39f00-d8cb-11ea-9b78-c198bb092a04.png)

 

### Possible implementation(s)

How might we do this? Not sure about this. But if the community thinks it would be a good addition for the project i can definitely dive into it.

### Additional context

![image](https://user-images.githubusercontent.com/43375532/89662519-1ece8380-d8cc-11ea-9be0-d869c2da997c.png)

**Comment by flybayer** [comment]
Hey @jose-donato, since you didn't specify, I'm assuming you are using Prisma for the database client. 

If you are, then you'll be very happy to know that Typescript type generation is one of the key features of prisma.

So with this `db/schema.prisma` file,

```prisma
model Category {
  id             Int       @default(autoincrement()) @id
  name           String?
  url            String?
  items          Item[]
}

model Item {
  // other stuff
}
```

You can access the `Category` and `Item` TS types like this:

```ts
```

**Comment by jose-donato** [comment]
Yes, I'm using prisma. 
That is interesting and i did not know.

Thanks!
