### ISSUE TITLE
Possible issue with web socket

### ISSUE THREAD

**Issue by mikeroosa** [blitz-js/blitz#854]
### What is the problem?
After generating a new app and clicking around on different links, my app seems to lock up and I can only visit previously visited pages. Even F5 to refresh the browser doesn't work. No output in the web console or server console.

### Steps to Reproduce

See linked video.

I started by clicking around on some projects, then clicked Create Project. At the 25 sec mark, I clicked Edit but nothing happened. Then at the 35 second mark, I clicked on Submit and again nothing happened. The only thing I could do is visit previously viewed pages at this point. Then I hit the reload button and the app does not reload.

### Versions

```
➜  myBlitzApp git:(master) ✗ blitz --version --verbose
You are using alpha software - if you have any problems, please open an issue here:
  https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: /Users/roosam/Projects/playground/myBlitzApp/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/roosam/Projects/playground/myBlitzApp/node_modules/@blitzjs/cli/lib/src/index.js

macOS Catalina | darwin-x64 | Node: v13.11.0

blitz: 0.17.0 (global)
blitz: 0.17.0 (local)

➜  myBlitzApp git:(master) ✗
```

### Other

Please include applicable logs and screenshots that show your problem.
https://res.cloudinary.com/davljbsnb/video/upload/v1596982437/Personal/Screen_Recording_2020-08-09_at_10.11.43_AM.mov

**Comment by flybayer** [comment]
That is definitely weird! Looks like an issue with Next.js fast refresh. 

Could you try upgrading to Node v13.14.0 and see if you have the issue with that? We have had issues with lower versions of v13.

**Comment by mikeroosa** [comment]
Seeing same behavior after upgrading to 14.7

➜  myBlitzApp git:(master) ✗ blitz --version --verbose
You are using alpha software - if you have any problems, please open an issue here:
  https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: /Users/roosam/Projects/playground/myBlitzApp/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/roosam/Projects/playground/myBlitzApp/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js

macOS Catalina | darwin-x64 | Node: v14.7.0

blitz: 0.17.0 (global)
blitz: 0.17.0 (local)

**Comment by mikeroosa** [comment]
After doing some research on this I came across a post on next.js that said someone else was having a similar issue. They ran on a different port and the problem went away.

I did blitz start --port=6789 and it works fine on that port.

**Comment by flybayer** [comment]
interesting! Probably a computer restart would fix it.
