### ISSUE TITLE
Automatically detect http/https on localhost and use secure cookies accordingly 

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#855]
### What do you want and why?

Currently [we are setting cookies as `secure`](https://github.com/blitz-js/blitz/blob/canary/packages/server/src/supertokens.ts#L699) (which requires HTTPS) if `NODE_ENV === 'production'`. This causes an issue if you run `blitz start --production` on your local machine because the url will be `http://localhost:3000` so cookies won't work because it's not https.

So instead we also want to check and only enable `secure` if request is not from `localhost`

**Edit**: updated to remove https localhost check

**Comment by toddgeist** [comment]
I looked into this.  getting "localhost" from the req.headers.host is easy.  But how do we get the protocol?  Node 14 has  req.protocol. But node 12 doesn't.  Any ideas?

**Comment by flybayer** [comment]
Ok then let's just disable for localhost regardless of protocol
