### ISSUE TITLE
Prevent Prisma from logging secrets in queries

### ISSUE THREAD

**Issue by dwightwatson** [blitz-js/blitz#856]
### What do you want and why?

I noticed that the Blitz logs include what appear to be output from Prisma when queries are run. This is great, except for when potentially sensitive information is shown in these queries.

```
> Running login({
  "email": "dwightwatson@github.com",
  "password": "secretpassword"
})
```

Other frameworks have features that help protect sensitive parameters. Rails has `filter_parameter_logging` and Laravel prevents this arguments from being re-flashed. In both these examples it defaults to an array that contains "password", giving developers the ability to filter additional parameters if required.

Especially with Blitz supporting auth out of the box it probably makes sense that we filter these secret parameters if possible.

### Possible implementation(s)

If I'm correct in thinking this logging is powered by Prisma we'll probably need to [switch to event-based logging](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/logging) and provide it to the Prisma client.

**Comment by flybayer** [comment]
@dwightwatson you're absolutely right. This is logging by Blitz. 

I've had this on my todo list for awhile. I'll do this as part of a logging system overhaul I have planned.
