### ISSUE TITLE
MDX is not supported

### ISSUE THREAD

**Issue by scisteffan** [blitz-js/blitz#857]
### What is the problem?

When adding MDX files they are not compiled into the NextJS application, so you cannot use the MDX Next plugins.

### Steps to Reproduce

1. Follow instructions at https://www.npmjs.com/package/@next/mdx for a new blitz project, updating `blitz.config.js` instead of `next.config.js`
2. Create new file at `app/pages/about.mdx`
3. Visit `http://localhost:3000/about` - *404 error*
4. Check the files at `.blitz/caches/dev/pages` - *about.mdx is missing*

### Versions

```
You are using alpha software - if you have any problems, please open an issue here:
    https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: /Users/steffanharris/Documents/Projects/BlitzJS/mdx-test/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/steffanharris/Documents/Projects/BlitzJS/mdx-test/node_modules/@blitzjs/cli/lib/src/index.js 

macOS Catalina | darwin-x64 | Node: v12.16.3

blitz: 0.17.1-canary.3 (global)
blitz: 0.17.1-canary.3 (local)

  Package manager: yarn 
  System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 515.31 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v12.16.3/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.2.0 => 2.2.0 
    @prisma/client: 2.2.0 => 2.2.0 
    blitz: 0.17.1-canary.3 => 0.17.1-canary.3 
    react: 0.0.0-experimental-33c3af284 => 0.0.0-experimental-33c3af284 
    react-dom: 0.0.0-experimental-33c3af284 => 0.0.0-experimental-33c3af284 
    typescript: 3.9.6 => 3.9.6
```

**Comment by flybayer** [comment]
Yep, definitely a bug!

Here's the line that needs updated: https://github.com/blitz-js/blitz/blob/canary/packages/server/src/stages/pages/index.ts#L8.

And be sure to add a test to this file: https://github.com/blitz-js/blitz/blob/canary/packages/server/src/stages/pages/pages-path-transformer.test.ts

**Comment by scisteffan** [comment]
I'm happy to take this one on board.

**Comment by flybayer** [comment]
Awesome, it's all yours!
