### ISSUE TITLE
usePaginatedQuery docs example incorrect

### ISSUE THREAD

**Issue by scisteffan** [blitz-js/blitz#858]
### What is the problem?

When I use the example usePaginatedQuery code in the docs (https://blitzjs.com/docs/use-paginated-query) the next button is not appearing / disappearing correctly.

### Steps to Reproduce

1. Go to https://blitzjs.com/docs/use-paginated-query and implement the code
2. Ensure the maximum number of items on the page is set to 3
3. Add 3 items to the database - *next button does not disappear*

### Versions

```
You are using alpha software - if you have any problems, please open an issue here:
    https://github.com/blitz-js/blitz/issues/new/choose

debug: blitzPkgPath: /Users/steffanharris/Documents/Projects/BlitzJS/usepaginatedquery-test/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/steffanharris/Documents/Projects/BlitzJS/usepaginatedquery-test/node_modules/@blitzjs/cli/lib/src/index.js 

macOS Catalina | darwin-x64 | Node: v12.16.3

blitz: 0.17.1-canary.3 (global)
blitz: 0.17.1-canary.3 (local)

  Package manager: yarn 
  System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 1.86 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v12.16.3/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.4.1 => 2.4.1 
    @prisma/client: 2.4.1 => 2.4.1 
    blitz: 0.17.1-canary.3 => 0.17.1-canary.3 
    react: 0.0.0-experimental-33c3af284 => 0.0.0-experimental-33c3af284 
    react-dom: 0.0.0-experimental-33c3af284 => 0.0.0-experimental-33c3af284 
    typescript: 3.9.7 => 3.9.7 
```

### Other

<img width="432" alt="Screenshot 2020-08-11 at 16 16 38" src="https://user-images.githubusercontent.com/2676185/89915336-22287e80-dbee-11ea-92ae-0c34b06bde59.png">

**Comment by flybayer** [comment]
Thanks @scisteffan! You're definitely right.

This needs updated in the `store` example in this repo, and [on the usePaginatedQuery doc page](https://github.com/blitz-js/blitzjs.com/edit/main/docs/use-paginated-query.mdx).

**Comment by scisteffan** [comment]
I'd love to take this one on board!

**Comment by flybayer** [comment]
You got it!

**Comment by scisteffan** [comment]
So I updated the store, noticed that the Prisma client version is stuck at 2.0.0 whereas my new blitz project is 2.4.1. This new version has undefined as a union type on the query inputs (FindManyProjectArgs) meaning we need to add the non-null assertion operator on `skip` and `take` for usePaginatedQuery and useInfiniteQuery.

**Comment by scisteffan** [comment]
Just want to confirm it's ok to update the version of Prisma client? That might be a separate issue since it could break things.

**Comment by flybayer** [comment]
Yeah you can update prisma client as part of this

**Comment by scisteffan** [comment]
Note I ended up setting tsconfig strick null checking rather than updating prisma client.
