### ISSUE TITLE
Getting error of unwanted types in vanilla js app

### ISSUE THREAD

**Issue by svobik7** [blitz-js/blitz#864]
### What is the problem?
After creation of new blitz app using `--js` flag and following main three steps from app homepage I am getting error `Syntax error: Unexpected token, expected ";"`

### Steps to Reproduce

1. `blitz new myApp --js`
2. `blitz generate all project name:string`
3. `blitz db migrate`
4. `blitz start`
4. Go to `http://localhost:3000/projects`

### Versions

```
macOS Catalina | darwin-x64 | Node: v12.14.1

blitz: 0.17.0 (global)
blitz: 0.17.0 (local)
```

### Other

<img width="953" alt="Screenshot 2020-08-12 at 14 50 02" src="https://user-images.githubusercontent.com/761766/90017414-c9b7b680-dcab-11ea-8ab7-fbbb9582aa20.png">

Seems this line cause the error https://github.com/blitz-js/blitz/blob/90a762448959dadb4513eea8ba78047fd9174d8f/packages/server/src/stages/rpc/index.ts#L72.

I think this "as typeof" statement could be removed completely from `isomorphicHandlerTemplate` as it is used only internally by blitz app. 

Or am I missing something? I am ready to PR.

**Comment by flybayer** [comment]
Thanks for reporting this! I think we can remove that entire `as` statement, so we just need to try that and see.

You're welcome to submit a PR!
