### ISSUE TITLE
Bump Prisma Version to Latest in Examples

### ISSUE THREAD

**Issue by chenkie** [blitz-js/blitz#866]
### What do you want and why?

The examples currently use an older version of Prisma (client and CLI). These should be updated to latest to make all the newest features available for users trying out the examples 👍

The more information the better!

### Possible implementation(s)

Bump to 2.4.1

### Additional context

Here's a search through the examples directory for Prisma: https://github.com/blitz-js/blitz/search?q=%22%40prisma%2Fcli%22&unscoped_q=%22%40prisma%2Fcli%22

**Comment by cardotrejos** [comment]
I'm searching my first open-source projects to work on, can I take this issue?

**Comment by flybayer** [comment]
@cardotrejos you sure can!! Let me know if you have any questions :)
