### ISSUE TITLE
Add timeout to git commit during new app creation

### ISSUE THREAD

**Issue by Weilbyte** [blitz-js/blitz#882]
### What do you want and why?

Ran into an issue while running `blitz new [appname]`. The issue itself wasn't related to blitz but rather an issue with my git configuration. Git hung while Blitz was trying commit and all I could see for several minutes was just the `✔ Formatting your code` that goes before the the commit.  

I had no idea what was taking so long so I CTRL^C. 
![image](https://user-images.githubusercontent.com/43392677/90207623-0936ed80-dde7-11ea-8fb2-a54222967ac7.png)

While it was a git issue that caused this, I believe the Blitz app generator should try to handle these situations in some better way, or should ask the user if they want to commit the app.

### Possible implementation(s)

Either prompt the user if they want to commit or have a timeout for the commands that get spawned [here](https://github.com/blitz-js/blitz/blob/b3814fc7c001cb735bac10de2d898fc161d4ae79/packages/generator/src/generators/app-generator.ts#L189).

### Additional context

`blitz -v` output: 
```
Linux 4.19 | linux-x64 | Node: v14.7.0

blitz: 0.17.0 (global)
```

**Comment by flybayer** [comment]
@Weilbyte great suggestion!

Let's add a timeout to the git commit command, probably 2 seconds would be good

**Comment by Weilbyte** [comment]
@flybayer  Sounds good, it should also run the commit with `--no-gpg-sign` so that if the user has `commit.gpgsign` enabled they won't be prompted (they can sign the commit afterwards themselves if they so desire).

**Comment by Weilbyte** [comment]
Will begin working on this :)
