### ISSUE TITLE
Fast Refresh is disabled without latest React

### ISSUE THREAD

**Issue by dwightwatson** [blitz-js/blitz#885]
### What is the problem?

Looks like not using the latest version of React has disabled Fast Refresh for the time being.

Everything else still works, just that development feature isn't available.

We're currently attached to a specific React commit - I'm not sure of the exact details why that one - but is there potential to just target `^16.10.0` like the attached Next.js docs suggest?

### Steps to Reproduce

1. Create a new blitz app
2. Run `blitz start`
3. See the following warning:

```
warn  - Fast Refresh is disabled in your application due to an outdated `react` version. Please upgrade 16.10 or newer! Read more: https://err.sh/next.js/react-version
```

### Versions

```
debug: blitzPkgPath: /Users/Dwight/Sites/myapp/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/Dwight/Sites/myapp/node_modules/@blitzjs/cli/lib/src/index.js 

macOS Catalina | darwin-x64 | Node: v14.7.0

blitz: 0.17.0 (global)
blitz: 0.17.1-canary.4 (local)
```

**Comment by merelinguist** [comment]
Which version of React _are_ you using?

**Comment by dwightwatson** [comment]
Maybe I misunderstand how `package.json` constraints work. My app has the same React preferences as a new Blitz app.

Checking `React.version` returns `16.13.1-experimental-33c3af284` instead - which is greater than `16.10`.

```
"react": "0.0.0-experimental-33c3af284",
"react-dom": "0.0.0-experimental-33c3af284",
```

Must be something else going on here.

**Comment by dwightwatson** [comment]
Sorry, I've verified this is an issue with Blitz 0.17.1-canary.4.

```sh
blitz new app
cd app
blitz start
```

```
You are using alpha software - if you have any problems, please open an issue here:
    https://github.com/blitz-js/blitz/issues/new/choose

✔ Prepped for launch
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

ready - started server on http://localhost:3000
warn  - Fast Refresh is disabled in your application due to an outdated `react` version. Please upgrade 16.10 or newer! Read more: https://err.sh/next.js/react-version
info  - Using external babel configuration from /Users/Dwight/Sites/app/.blitz/caches/dev/babel.config.js
event - compiled successfully
```

The installed React version is `16.13.1-experimental-33c3af284`.

**Comment by merelinguist** [comment]
I’m not sure why fast refresh is not supported, but you could try upgrading to a newer version of React. N.B., however, that we do require the experimental build of React in order to support Suspense for data fetching.

**Comment by merelinguist** [comment]
I usually just tag it as `"react": "experimental"`.

**Comment by dwightwatson** [comment]
When using `experimental` I still get the same warning.

**Comment by flybayer** [comment]
Here's the problem: https://github.com/vercel/next.js/issues/16103

So according to Tim, that is just a warning and doesn't actually disable fast refresh.

**Comment by dwightwatson** [comment]
Cool, good to know!
