### ISSUE TITLE
Feature request: Add "no git" option to app generator

### ISSUE THREAD

**Issue by Weilbyte** [blitz-js/blitz#889]
### What do you want and why?

An option/flag to disable the git operations during `blitz new` app generation would be handy in some situations. 

### Possible implementation(s)

Add another option, for example `--no-git`. App generator will check if that option is passed and if it is, it will skip the git operations.

**Comment by flybayer** [comment]
Good suggestion :)

**Comment by Weilbyte** [comment]
On it :)
