### ISSUE TITLE
Add conditional check to blitz webpack config to fix usage without `db/index.ts` file

### ISSUE THREAD

**Issue by Weilbyte** [blitz-js/blitz#890]
### What do you want and why?

If running `blitz start` without a `db` folder, Blitz will error out saying that it cannot resolve `./db/index`. However, if running with a blank `db/index` file then it's all okay. 

It would be nice if Blitz could catch the `Can't resolve` and warn the user that it's running without a database. 

I know Blitz is meant for database applications but I think handling that error would do some good. 

### Possible implementation(s)

Catch resolve error on start and run without a database (warn user that its running without a database as well), similar to how it runs with an empty `db/index` file.

**Comment by flybayer** [comment]
Yes, that's a bug! [This line is where the problem is](https://github.com/blitz-js/blitz/blob/canary/packages/server/src/with-blitz.ts#L18).

We need to conditionally add that line only if the `db/index.*` file exists.

**Comment by Weilbyte** [comment]
Will attempt to tackle this soon.

**Comment by Weilbyte** [comment]
PR up => https://github.com/blitz-js/blitz/pull/906
