### ISSUE TITLE
`blitz new` doesn't trigger `npm i` command in linux system

### ISSUE THREAD

**Issue by adnanfuat** [blitz-js/blitz#894]
BLITZ installing doesn't trigger "npm i" command in linux system

**blitz -vV** :
[see screenshot](https://prnt.sc/u03m1s)

This is video of the problem

https://www.youtube.com/watch?v=1D3a7eg8ZJA

**Comment by flybayer** [comment]
Thanks for reporting this @adnanfuat!

**Comment by Weilbyte** [comment]
Does the same thing happen with `yarn` or is it npm-exclusive?

**Comment by Weilbyte** [comment]
Unable to reproduce. Both `yarn` and `npm` installations start fine.

##### NPM 
```
debug: blitzPkgPath: /home/weil/Projects/npmtest/node_modules/blitz/dist/index.js
debug: cliPkgPath: /home/weil/Projects/npmtest/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js 

Linux 5.7 | linux-x64 | Node: v14.8.0

blitz: 0.17.0 (global)
blitz: 0.17.1-canary.5 (local)
```
##### Yarn
```
debug: blitzPkgPath: /home/weil/Projects/yarntest/node_modules/blitz/dist/index.js
debug: cliPkgPath: /home/weil/Projects/yarntest/node_modules/@blitzjs/cli/lib/src/index.js 

Linux 5.7 | linux-x64 | Node: v14.8.0

blitz: 0.17.0 (global)
blitz: 0.17.1-canary.5 (local)
```
##### NPM/Yarn info

npm => `/usr/bin/npm`
yarn => `/usr/bin/yarn` 

@adnanfuat can you show output of `which npm` and `which yarn`? Also can you attempt running with the Blitz canary version?

**Comment by Weilbyte** [comment]
@adnanfuat 👋 
Are you still experiencing this issue? If so please provide some more information as I was not able to replicate this.
