### ISSUE TITLE
Add single mutation generator

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#900]
### What do you want and why?

We're adding a single query generator with https://github.com/blitz-js/blitz/pull/837, so now we need to also add a single mutation generator. The changes will be very similar to that PR, but for mutations instead of queries.

**Comment by aem** [comment]
I can tackle single page generator as a part of this too

**Comment by flybayer** [comment]
Great!

**Comment by flybayer** [comment]
done
