### ISSUE TITLE
Cannot run `blitz db reset` on fresh install

### ISSUE THREAD

**Issue by pqt** [blitz-js/blitz#938]
### What is the problem?
When trying to reset the database I get a successful connection (I assume that's what loading database means). And then a failure to read `datasources` after confirming I am okay with clearing out the database.

Other prisma options like introspect and studio work as expected. This is just using sqlite at the moment, not hooked up to Postgres or anything external.

**It may be related specifically to the MacOS (Big Sur) Developer Beta** but I haven't tested this specifically. If it's not possible to reproduce then I can test this further.

### Steps to Reproduce

1. Start a new project using `blitz new [appName]`
2. Run migrations
3. Try to reset migrations (`blitz db reset`)

### Versions

```
debug: blitzPkgPath: /Users/austin/Developer/forcir/forcir/node_modules/blitz/dist/index.js
debug: cliPkgPath: /Users/austin/Developer/forcir/forcir/node_modules/@blitzjs/cli/lib/src/index.js 

macOS Big Sur | darwin-x64 | Node: v12.18.3

blitz: 0.18.0 (global)
blitz: 0.18.0 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.0
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 5.51 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.5.1 => 2.5.1 
    @prisma/client: 2.5.1 => 2.5.1 
    blitz: 0.18.0 => 0.18.0 
    react: 0.0.0-experimental-33c3af284 => 0.0.0-experimental-33c3af284 
    react-dom: 0.0.0-experimental-33c3af284 => 0.0.0-experimental-33c3af284 
    typescript: 3.9.7 => 3.9.7
```

### Other

![](https://i.imgur.com/PrO2nZr.png)

**Comment by alkamin** [comment]
I experienced this as well

**Comment by flybayer** [comment]
For whoever wants to look into fixing this, the problem code [is here](https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/db.ts#L221). 

I think we might need to switch to this:

```ts
import {getConfig} from '@prisma/sdk'
```


getConfig should return something like this:
```
{
  generators: [...],
  datasources: [
    {
      name: 'db',
      provider: [ 'sqlite', 'postgresql' ],
      activeProvider: 'sqlite',
      url: { fromEnvVar: null, value: 'sqlite://' }
    }
  ]
}
```

**Comment by firrae** [comment]
So I did a but of digging on my fresh Blitz project. I've found that the issue is likely at [this line](https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/db.ts#L231). Currently this is creating an empty Prisma client with no connection information. Debugging found there to be no `engine` sub-object on `db` hence the error message we get. Also maybe this is just because there's not connection, but `db.engine` is `db._engine` currently.

Prisma is new to me, so I'm not sure how to proceed yet, but maybe someone could point me in the correct direction or use this to finish the job?

**Comment by firrae** [comment]
For the record, I have added the block above to my `config` file and `getConfig` is returning it so far as I can tell but it still fails.

**Comment by flybayer** [comment]
@firrae thanks for checking into that. Does it work if you switch to `db._engine`?

**Comment by firrae** [comment]
@flybayer negative, it seems to be not initiated with the DB information from what I can tell. `_engine` has an empty array for `datasource` (if I remember correctly, I'll double check this evening).

**Comment by flybayer** [comment]
Hmm, then I don't know how to provide any more guidance without just digging in and getting my hands dirty to figure out what's going on.
