### ISSUE TITLE
Undefined function `deleteCookie` when loading a page with an expired session

### ISSUE THREAD

**Issue by Bathlamos** [blitz-js/blitz#949]
### What is the problem?
Using the code described at https://blitzjs.com/docs/auth#emailpassword, I encounter a client-side runtime error when loading a page locally with an expired session cookie. This error disappears when I clear my cookies or when I access the page using an incognito browser.

### Steps to Reproduce

1. As far as I can tell, it suffices to add the authentication middleware to blitz.config.js and obtain an expired session (or wait for a valid session to expire). 

### Versions

```
macOS Catalina | darwin-x64 | Node: v14.7.0

blitz: 0.17.0 (global)
blitz: 0.18.0 (local)
```

### Other

The error goes as follows:

Upon page load, the following code executes: https://github.com/blitz-js/blitz/blob/canary/packages/core/src/supertokens.ts

It seems like the following sequence of calls occurs based on breakpoints:
1. `publicDataStore.initialize()` gets called
1. This calls `updateState`, which calls `getData`
1. `getData` calls `deleteCookie`, which is undefined at that time.

It also seems like calling `publicDataStore.initialize` later in the file might solve the issue. Thoughts?

**Comment by LoriKarikari** [comment]
Thanks for reporting this issue @Bathlamos!

**Comment by flybayer** [comment]
Hey @Bathlamos I'm not totally following you as to what the issue is 🤔  Can you share the exact error that you get?

**Comment by Bathlamos** [comment]
Hey @flybayer, if you're referring to the console error, it's `Uncaught TypeError: deleteCookie is not a function`.

**Comment by flybayer** [comment]
@Bathlamos can you paste here the entire logs from your terminal when this happens? Just the error message itself isn't really enough to figure out what's going on. So include all the logs possible :)

Also, can you try with Node v12? It's possible this is a Node v14 issue 🤔

**Comment by Bathlamos** [comment]
Apologies, it's difficult to reproduce the error. I just encountered it again, this time in my development environment, so pasting the log here. I'm trying with Node v12.18.3 and so far this looks like it's working. I'll post again if I encounter this error using Node v12.

![image](https://user-images.githubusercontent.com/4612142/91752938-16006300-eb95-11ea-929c-35ae84bb286f.png)

**Comment by flybayer** [comment]
Ok thank you for that!

**Comment by Bathlamos** [comment]
Unfortunately, I'm encountering the same error again in production under Node 12 (see below —same error, just minified code). Would you benefit from the specific cookies and database content leading to this error? I'm fairly sure that simply setting a very low `sessionExpiryMinutes` in the middleware config and then waiting for a session to expire is enough to replicate.

![image](https://user-images.githubusercontent.com/4612142/91765145-7ea40b80-eba6-11ea-8446-710e7b41e188.png)

**Comment by flybayer** [comment]
Ok yeah I think I know enough to fix it, I just haven't got to it yet. Will try to soon
