### ISSUE TITLE
Blitz recipes don't work with layout.

### ISSUE THREAD

**Issue by oiojin831** [blitz-js/blitz#950]
Using chakra-ui recipes turns only  `<Component {...pageProps} />` in to Chakra aware Code.
```ts
{getLayout(
  <ThemeProvider>
    <CSSReset />
    <Component {...pageProps}
  </ThemeProvider>
)}
```

It Chakra's `<ThemeProvider>` should wrap layout as well
```ts
<ThemeProvider>
  <CSSReset />
  {getLayout(
    <Component {...pageProps}
  )}
</ThemeProvider>
````

**Comment by LoriKarikari** [comment]
Thanks for reporting this issue @oiojin831.

**Comment by flybayer** [comment]
This is also a problem for all the other recipes that add context, like emotion etc.

**Comment by konradkalemba** [comment]
@flybayer I can work on this.
