### ISSUE TITLE
Cannot resolve modules when running custom scripts

### ISSUE THREAD

**Issue by johncantrell97** [blitz-js/blitz#952]
I am trying to write the equivalent of rails 'rake tasks' where I can write some typescript or javascript that is meant to be executed manually using node/ts-node via an npm script.  

Here is the simplest example repo I could setup to reproduce the issue:

https://github.com/johncantrell97/blitzTask/commit/2994c4137d867e15a60465bcc1eb50fa311653ff

This commit adds tasks/example.ts which imports a util that logs a message to the console.  If I import it as shown in the commit and try to run it using `npm run example:task` I get the error `Error: Cannot find module 'utils/exampleUtil'`

If I update the import to be relative:

`import exampleUtil from '../utils/exampleUtil'`

it works fine. 

This is a problem in my main project because all of my imports are using absolute paths from the baseDir defined in my tsconfig.json file. I'd prefer not to change all of them to relative imports for a few reasons.

ts-node supposedly uses tsconfig.json and can be manually passed in via --project flag as I have done in this commit.  However, it does not appear to be respecting the baseDir for module resolution.

Any ideas how I can fix this?

**Comment by johncantrell97** [comment]
Figured it out.  

Turns out ts-node does not support using baseDir and paths tsconfig.json options.  Someone wrote a plugin to fix this gap (https://github.com/dividab/tsconfig-paths) which worked for me.  

Here's the several year long thread about the issue on ts-node repo ( https://github.com/TypeStrong/ts-node/issues/138 ) in case you're curious about where I found the solution.

ts-node also needs to be configured to use commonjs modules which you can override for ts-node only by adding this to your tsconfig.json:

```
"ts-node": {
  "compilerOptions": {
    "module": "commonjs"
  }
}
```

With that in place and the tsconfig-paths library added to your project you can run a script like this:

`ts-node -r tsconfig-paths/register index.ts`

and it works fine.

**Comment by waptik** [comment]
> ts-node -r tsconfig-paths/register

Thanks man! I was looking for something of the sort.
Kudos to you.

**Comment by flybayer** [comment]
https://github.com/folke/esbuild-runner is an even better option now than ts-node
