### ISSUE TITLE
Add CLI Command For Migrate Up

### ISSUE THREAD

**Issue by firrae** [blitz-js/blitz#954]
### What do you want and why?
The ability to run the prisma command `migrate up --experimental` on its own while passing in valid parameters as defined [here](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-cli/command-reference#examples-4).

I have a need for this as creating a new migration if I want to swap DBs for testing seems excessive.

### Possible implementation(s)
I figure this would be likely similar to existing `db` commands, I'd take it even without some of the more specific commands that take in extra variables.

### Additional context

Prisma docs on their `migrate up` command: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-cli/command-reference#migrate-up.

**Comment by flybayer** [comment]
Thanks @firrae! Once prisma migrate comes out of experimental status, we'll overhaul our Prisma integration.

For now the workaround is to call prisma directly like this: 
```
prisma migrate up --experimental --schema db/schema.prisma
```

**Comment by firrae** [comment]
@flybayer good to know, I didn't think I could do that but if it works I'll go that route for now. Thanks.
