### ISSUE TITLE
useInfiniteQuery not working properly since v0.18

### ISSUE THREAD

**Issue by alan2207** [blitz-js/blitz#956]
### What is the problem?

`useInfiniteQuery` is not working properly since upgrading to v0.18. It keeps returning the first results

### This is how it works now.
<img width="1287" alt="Screenshot 2020-08-28 at 20 35 45" src="https://user-images.githubusercontent.com/12713315/91603881-0eab4080-e96e-11ea-8dd5-c334ceda30bc.png">

### And this is how it should work.
<img width="988" alt="Screenshot 2020-08-28 at 20 45 53" src="https://user-images.githubusercontent.com/12713315/91604723-7910b080-e96f-11ea-97cd-61872921a5bc.png">

I have been exploring through the commits that could affect this and can confirm that this is the commit that is causing it:
https://github.com/blitz-js/blitz/commit/24162830ae69d31846c85e502aed833f62d79f09

### Steps to Reproduce

1. Set up and start the store example app: https://github.com/blitz-js/blitz/tree/canary/examples/store
2. Open [Infinite Product Listings (client-rendered)](http://localhost:3000/products/infinite)
3. Try loading more products

### Versions

```
macOS Catalina | darwin-x64 | Node: v12.18.3

blitz: 0.18.0 (global)
blitz: 0.18.0 (local)

  Package manager: yarn 
  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 119.87 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
```

**Comment by flybayer** [comment]
Oops, definitely a bug! Thanks for reporting this!
