### ISSUE TITLE
Return 404 when there's no default export from a query/mutation file

### ISSUE THREAD

**Issue by cherta** [blitz-js/blitz#957]
### What do you want and why?

I think sometimes it's useful having code that's not automatically exposed as an endpoint, but it's sitting there in a query or a mutation file. For example, when doing trunk based development you want the code in place, but not yet exposed to the world.

A common way to do this are feature flags, but those carry their own issues, another common approach I take is to code the feature, but hide the endpoint. In rails this is easy to do because a controller needs to be connected on the routes file.

### Possible implementation(s)

I think this should be as simple as returning 404 if there's no default export on a query or a mutation. Currently it tries to apply a middleware to an undefined object and it fails.

### Additional context

N/A

**Comment by flybayer** [comment]
Thanks @cherta! Your request definitely makes sense. My only thought is if there's some way we can distinguish between when there's intentionally no default export vs when it's accidental.

But probably either way a 404 or 500 error will cause the dev who did it accidentally to figure it out 🤔 

I say let's switch this behavior unless someone has more compelling reason not to.

**Comment by cherta** [comment]
I see your point @flybayer, but for me the error of not exporting something should not be a runtime concern, but a build time one. I see this more as a linter / compile step issue than an execution problem.

Do you see this as a potential good first PR, or it's too complex for me to try solving it?

**Comment by flybayer** [comment]
Yeah I think you could do it as a first PR.

Depending on where the actual runtime error orginates from, you'll probably want to [make the change here](https://github.com/blitz-js/blitz/blob/canary/packages/server/src/stages/rpc/index.ts#L96) or [here](https://github.com/blitz-js/blitz/blob/canary/packages/server/src/stages/rpc/index.ts#L68). And if default export isn't there, then use a default 404 handler code, something like this:

```
export default (req, res) => res.status(404).end()
```
