### ISSUE TITLE
Failed to find request token in session when twitter login and using Nginx proxy

### ISSUE THREAD

**Issue by PixelsCommander** [blitz-js/blitz#966]
### What is the problem?

I use Blitz in production mode on Nginx proxied server. When I try to use Twitter auth I get an error "Failed to find request token in session". Most likely the cookie is not set for the session.

### Steps to Reproduce

1. Enable Nginx proxy with SSL
2. Run Blitz in production
3. Follow auth tutorial and implement Twitter login
4. Try to login with Twitter
5. Expected result - it logs in
6. Actual result - it does not log, only anonymous session cookies are set

### Versions

```
Linux 5.4 | linux-x64 | Node: v12.18.3

blitz: 0.18.0 (global)
blitz: 0.19.0 (local)

  Package manager: yarn
  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (8) x64 Intel Core Processor (Haswell, no TSX)
    Memory: 4.78 GB / 15.27 GB
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.0.0-beta.3 => 2.0.0-beta.3
    @prisma/client: 2.0.0-beta.3 => 2.0.0-beta.3
    blitz: 0.19.0 => 0.19.0
    react: 0.0.0-experimental-33c3af284 => 0.0.0-experimental-33c3af284
    react-dom: 0.0.0-experimental-33c3af284 => 0.0.0-experimental-33c3af284
    typescript: 3.9.6 => 3.9.6`
```

### Other

Please include applicable logs and screenshots that show your problem.

**Comment by flybayer** [comment]
Hey @PixelsCommander thanks for reporting this! I also saw [the discussion thread you posted](https://github.com/blitz-js/blitz/discussions/967). We definitely haven't tested this scenario yet.

Does the default email/password login work with this Nginx setup?

**Comment by flybayer** [comment]
If this is just an issue with the passport adapter but not regular auth, then probably we need to add a way to configure `secureProxy` for `cookie-session` which [is used here](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/passport-adapter.ts#L40).

**Comment by PixelsCommander** [comment]
Good hint. I'll check if this makes any impact.

**Comment by PixelsCommander** [comment]
It seems to be something to do on server side;

If your server is running behind a proxy and you are using secure: true, you need to configure your server to read the request headers added by your proxy to determine whether the request is using a secure connection.

For more information about working behind proxies, consult the framework you are using:

For Koa - app.proxy = true
For Express - trust proxy setting
If your Koa or Express server is properly configured, the protocol property of the request will be set to match the protocol reported by the proxy in the X-Forwarded-Proto header.

Example

```
var http = require('http')
var Cookies = require('cookies')

// Optionally define keys to sign cookie values
// to prevent client tampering
var keys = ['keyboard cat']

var server = http.createServer(function (req, res) {
  // Create a cookies object
  var cookies = new Cookies(req, res, { keys: keys })

  // Get a cookie
  var lastVisit = cookies.get('LastVisit', { signed: true })

  // Set the cookie to a value
  cookies.set('LastVisit', new Date().toISOString(), { signed: true })

  if (!lastVisit) {
    res.setHeader('Content-Type', 'text/plain')
    res.end('Welcome, first time visitor!')
  } else {
    res.setHeader('Content-Type', 'text/plain')
    res.end('Welcome back! Nothing much changed since your last visit at ' + lastVisit + '.')
  }
})

server.listen(3000, function () {
  console.log('Visit us at http://127.0.0.1:3000/ !')
})

```

**Comment by PixelsCommander** [comment]
I see that Next has Express integration https://github.com/vercel/next.js/tree/canary/examples/custom-server-express but not sure if using it would be the best solution for the problem because multiple Blitz features would be broken.

**Comment by flybayer** [comment]
Hmm. So does the default email/password login work with this Nginx setup?

**Comment by PixelsCommander** [comment]
Sorry, had no chance to test because login/password is not planned to be implemented. The whole thing is Twitter oriented so the decision was to go with Twitter login only. 

What I see is that NGINX itself does not break the thing. If I run Nginx + Dev version without SSL it works. Also, I had the same error locally until you made the localhost/https fix for cookies in 0.19.

**Comment by flybayer** [comment]
Ok yeah I understand. Based on the error message I _think_ it's just a configuration thing for `cookie-session`.

**Comment by PixelsCommander** [comment]
You are right, now I am passing secureProxy to passAuth then to cookie-session constructor. This gets it a bit further and now cookies are set and the server logs current user data. 

But I am getting CSRFTokenMismatchError which breaks authorization. Is this somehow expected?

**Comment by flybayer** [comment]
You should not get a `CSRFTokenMismatchError` error. For a temporary workaround you can set the `DISABLE_CSRF_PROTECTION=true` environment variable to see if it works without that.

**Comment by PixelsCommander** [comment]
Tried. No CSRF error but the user is not defined on the client while I see that query from getServerSideProps logs

```
> Running getCurrentUser(null)
✔ getCurrentUser returned {
  "id": 2,
  "createdAt": "2020-08-31T08:03:00.582Z",
  "updatedAt": "2020-09-02T17:40:45.772Z",
  "name": "React",
  "email": "hi@react.amsterdam",
  "hashedPassword": null,
  "role": "user",
  "scanPercentage": null,
  "scanInProgress": false,
  "lastScanTime": "2020-09-01T15:31:55.993Z"
}
```

and cookies I have set in the browser are:

<img width="1121" alt="Screenshot 2020-09-02 at 19 45 15" src="https://user-images.githubusercontent.com/810671/92017862-a933c700-ed54-11ea-93fc-505f06b94735.png">

**Comment by flybayer** [comment]
Everything looks right. What do you mean by "user is not defined on the client" ?

**Comment by PixelsCommander** [comment]
getCurrentUser logs correct data to the server console, but the client request gets an empty response

<img width="539" alt="Screenshot 2020-09-02 at 20 47 46" src="https://user-images.githubusercontent.com/810671/92023462-19464b00-ed5d-11ea-9944-7b5e1d0d61f0.png">
<img width="539" alt="Screenshot 2020-09-02 at 20 47 39" src="https://user-images.githubusercontent.com/810671/92023476-1b100e80-ed5d-11ea-87c1-0f903fe4118e.png">
<img width="1080" alt="Screenshot 2020-09-02 at 20 47 35" src="https://user-images.githubusercontent.com/810671/92023481-1ba8a500-ed5d-11ea-9878-f951b7775e3f.png">

**Comment by PixelsCommander** [comment]
Oh, gosh, it works

**Comment by PixelsCommander** [comment]
This was an aftermath of me fighting the cookies issue with Nginx. So "over configured" it here and there.

**Comment by PixelsCommander** [comment]
Currently, I have this implemented as a prop passed to cookie-session but guys reject any related PRs and suggest we build a compatibility layer that is configured to send https in req if the proxy is secure https://github.com/expressjs/cookie-session/pull/144 . This supposed to be our equivalent of "trust proxy" in Express or app.proxy = true in Koa 

Could you suggest on implementation?

Looks like it could be one of two, while I am oversimplifying.

```
if (config.secureProxy) {
1      cookieSessionMiddleware.secure = true;
2      req.protocol = 'https';
    }
```

**Comment by flybayer** [comment]
Ok cool! So what config did you have to change for cookie-session to make it work?

**Comment by PixelsCommander** [comment]
It is a bit complicated.

In short - there is no option in cookie-session for that. The only way we can do it now is to change req.protocol passed to cookie-session to 'https' based on some configuration. This is how it is done in Express and Koa.

**Comment by flybayer** [comment]
I'm trying to understand the core thing that makes it work with the proxy or not. Is it a matter of `secure` cookies or not?

**Comment by flybayer** [comment]
I found this code [in a Next.js example](https://github.com/vercel/next.js/blob/279ae19c7e4cb75bd79873b0036332222781b792/examples/amp-first/pages/index.js#L242). Perhaps we can expose a config item on the password adapter that if it's true, we would set `req.protocol` based on the result of this code.

```ts
function getProtocol(req) {
  if (req.connection.encrypted) {
    return 'https'
  }
  const forwardedProto = req.headers['x-forwarded-proto']
  if (forwardedProto) {
    return forwardedProto.split(/\s*,\s*/)[0]
  }
  return 'http'
}
```

**Comment by PixelsCommander** [comment]
Sounds good.

Should this be a global Blitz configuration or option passed to `passportAuth`?

What is the best place to modify `req.protocol`? `passportAuth`?

**Comment by flybayer** [comment]
Yeah an option to `passportAuth`. You can create a middleware that modifies `req.protocol` and conditionally [add it here](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/passport-adapter.ts#L38) if the config option is set.

**Comment by PixelsCommander** [comment]
@flybayer https://github.com/blitz-js/blitz/pull/1033 this one to be merged to fix the issue

**Comment by kotx** [comment]
> I found this code [in a Next.js example](https://github.com/vercel/next.js/blob/279ae19c7e4cb75bd79873b0036332222781b792/examples/amp-first/pages/index.js#L242). Perhaps we can expose a config item on the passport adapter that if it's true, we would set `req.protocol` based on the result of this code.
> 
> ```ts
> function getProtocol(req) {
>   if (req.connection.encrypted) {
>     return 'https'
>   }
>   const forwardedProto = req.headers['x-forwarded-proto']
>   if (forwardedProto) {
>     return forwardedProto.split(/\s*,\s*/)[0]
>   }
>   return 'http'
> }
> ```

maybe this should extract the protocol from the more standard [`forwarded`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) header as well?

**Comment by flybayer** [comment]
@kotx yeah that sounds like a good idea. Want to make a PR?

**Comment by kotx** [comment]
@flybayer Sure, but I was checking it out and got a bit stuck- for some reason `req.headers['forwarded']` is undefined, even if I define it in a test file like so:
```js
// @ts-ignore
let reqForwardSecure: Request = {
  connection: new Socket(),
  method: 'GET',
  url: '/stuff?q=thing',
  headers: {
    forwarded: 'by=unknown;for=unknown;host=localhost;proto=https',
  },
}
```
Any pointers? I have a [Gitpod](https://gitpod.io) [snapshot here](https://gitpod.io#snapshot/75e5135c-fd1b-448c-85e3-beca151d588e) if it helps.

**Comment by kotx** [comment]
@flybayer Here you go ^^
