### ISSUE TITLE
Initial migration for new apps is not included in the initial git commit

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#968]
### What is the problem?

Initial migration for new apps is not included in the initial git commit

### Steps to Reproduce

1. `blitz new myapp`
2. `cd myapp`
3. `git status` -> see that there are a few migration files that aren't committed to git.

### Versions

```
0.18.0
```

### Other

The problem is that we [commit the code here](https://github.com/blitz-js/blitz/blob/canary/packages/generator/src/generators/app-generator.ts#L214) but then [run db migrate here](https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/new.ts#L108).

So we need to shuffle around how we do that. Open to your idea on how to fix it.

**Comment by engelkes-finstreet** [comment]
I would like to look into this
