### ISSUE TITLE
Need to update Readme contents for new apps

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#969]
### What is the problem?

The readme for new blitz apps is not correct. We need to update the "Whats included?" section to include all the files that are now in new apps by default.

### Steps to Reproduce

1. `blitz new myapp`
2. `cd myapp`
3. See that the files listed in readme.md do not match files in the project.

### Versions

```
0.18.0
```

### Other

[Here is the readme template file](https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/app/README.md) that needs updated.

**Comment by jschepmans** [comment]
Hi, I'd like to work on this! It would be my first issue :)

**Comment by flybayer** [comment]
@jschepmans awesome! It's all yours :)
