### ISSUE TITLE
Add e2e tests for Blitz examples

### ISSUE THREAD

**Issue by ryardley** [blitz-js/blitz#97]
We should have a way to test our example apps in as a real world way as possible.

Create a testing system to run tests against our example apps. 

Ideally the tests should be able to test a developer running cli commands and then investigating the results through the cli output or the e2e browser.

**Comment by Zeko369** [comment]
I'd like to do this. Maybe we should also think about adding cyperss and/or jest to our generated app by default?

**Comment by flybayer** [comment]
@Zeko369 yeah for sure! We need someone to set up a really nice out-of-the-box testing experience for blitz apps.

**Comment by Zeko369** [comment]
I'll add cyperss to current apps and then we discuss adding it to the template

**Comment by flybayer** [comment]
@Zeko369 ok sounds like a plan

**Comment by flybayer** [comment]
Closed in #335
