### ISSUE TITLE
Husky git hooks are not set up properly in new apps

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#973]
### What is the problem?

Husky git hooks do not work right away after creating a new blitz app. You have to first run `npm rebuild husky`.

### Steps to Reproduce

1. `blitz new myapp`
2. See that `husky.sh` is missing from `myapp/.git/hooks/`

### Versions

```
0.18.0
```

### Other

I don't know 100% why this is happening, but probably it's because we install yarn dependencies before initializing the git repo. So we could either initialize the git repo before installing deps (but still wait to commit changes until the end). Or we can run `npm rebuild husky` after setting up the git repo.

[Here's the code where we initialize the git repo](https://github.com/blitz-js/blitz/blob/canary/packages/generator/src/generators/app-generator.ts#L214).

**Comment by bpas247** [comment]
> So we could either initialize the git repo before installing deps (but still wait to commit changes until the end). Or we can run `npm rebuild husky` after setting up the git repo.

I think I'm more of a fan of the former 🙂 since the latter might increase the time it takes to create a new app.
