### ISSUE TITLE
Add `no-use-before-define` to our eslint config

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#983]
### What do you want and why?

We [had a bug](https://github.com/blitz-js/blitz/pull/982) because we violated this rule, so we need to add this rule to our config.

1. Add `"no-use-before-define": ["error", {functions: false, classes: false}],` to `.eslintrc.js` in the Blitz repo root.
2. Fix all lint errors that violate this new rule

**Comment by clgeoio** [comment]
happy to pick this up
