### ISSUE TITLE
Add `setQueryData` utility for updating query cache

### ISSUE THREAD

**Issue by jan-wilhelm** [blitz-js/blitz#984]
### What do you want and why?
Some components don't need the actual data of a `useQuery` hook but just need access to the `mutate` and `refetch` functions. Having to wrap those in a `<Suspense  />` component just for that purpose is unintuitive and confusing.

Especially for optimistic UIs it is not very handy that I have to call useQuery  just to be able to update the value of that query.

Example: Think of a `ChatMessageInput` component that renders a textarea for a chat application. There’s a `getChat` query. Now when sending a message through the textarea, I want the ChatMessageInput component to be able to optimistically update the value of that query.

Currently, it seems like I need to do this:

```typescript
const [chat, { mutate, refetch }] = useQuery(getChat, {chatId});
const [message, setMessage] = useState("");

const submit = async () => {
    mutate(
      {/*...*/},
      { refetch: false }
    );
    await sendMessage({ chatId, message });
  }
}
```

Instead, being able to use something like
```typescript
import { queryCache } from 'react-query' 
queryCache.invalidateQueries(/*...*/)
```
without actually having to load the hook would be preferable here.

This is especially true if you take into account that you would want such a `ChatMessageInput` to render the textarea even while the chat query is loading. Therefore you would have to either pass the same UI component as a fallback component to a wrapping `<Suspense>` or disable suspense mode for this query.

### Possible implementation(s)
Not sure, not too familiar with how Blitz internally uses `react-query`

**Comment by flybayer** [comment]
Hey @jan-wilhelm that definitely makes sense. I need to investigate this and see if we can do something to make this nice, but for sure right now you can access `react-query` directly and manually modify the `queryCache`.

**Comment by flybayer** [comment]
Here's [our internal usage of useQuery](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/use-query.ts#L63).

And [here's where we define the `mutate` function](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/utils/query-cache.ts#L12). As I'm looking at this right now, I wonder if we don't have a bug because the queryKeys don't match between those 🤔

**Comment by flybayer** [comment]
@jan-wilhelm ok what if we added a `getQueryKey` function that you could use anywhere in your app like this:

```ts
import getChat from 'app/queries/getChat'
import {getQueryKey} from 'blitz'
import {queryCache} from 'react-query'

// ...

const queryKey = getQueryKey(getChat, {/* exact same params I use with useQuery */})
queryCache.setQueryData(queryKey, {/* optimistic UI update data */})
```

**Comment by flybayer** [comment]
We could also add something like this:

```ts
import getChat from 'app/queries/getChat'
import {mutateQuery} from 'blitz'

// ..

mutateQuery(getChat, {
  queryParams: /* same params as used with useQuery */,  <-- optional
  newData: /* new data to set */,
  refetch: true,                  <-- also invalidate this query
})
```

Btw, if you pass `enabled: false` to useQuery options, that will disable suspense too.

**Comment by jan-wilhelm** [comment]
yeah either of those options would definitely solve that problem from a technical point of view, but I am not sure if they're the best APIs (keeping DX in mind).

I think the second suggestion is a little more intuitive, because it doesn't require the developer to keep a mental model of a "query key". Instead they can just say "here, I've got this query, that I call with these params, now please go and change that value" so we're kind of hiding the "implementation detail" of a query key.

Just my thoughts, perhaps there's an even better API though... ? :)

**Comment by flybayer** [comment]
@jan-wilhelm yeah might be something better! Let me know if you have any ideas

**Comment by jan-wilhelm** [comment]
now that we have merged #1226 , wouldn't it be quite easy to add a similar `mutateQuery` helper?

**Comment by flybayer** [comment]
@jan-wilhelm yes!

**Comment by aericson** [comment]
I'd be interested to take a look at it. If no one has started working on it :D

**Comment by aericson** [comment]
@flybayer 

shouldn't we call it `setQueryData` instead of `mutateQuery`. mutate seems to imply that it would have side effects on server data.

**Comment by flybayer** [comment]
@aericson you have a good point! I'm fine with that, but if we do that we should rename the `mutate` helper that's returned from `useQuery` to also be `setQueryData`.

**Comment by aericson** [comment]
@flybayer thanks for the tip to rename `mutate`! I created a PR (RFC) that includes a few choices that I'm not so sure about. I'd appreciate it if you could take a look at it.

Thanks!
