### ISSUE TITLE
Add a timeout to the "retrieving freshest dependencies" step during new app creation

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#989]
### What do you want and why?

We occasionally have situations were new app creation get's stuck forever at the "retrieving freshest dependencies" step.

To mitigate the impact for this, we need to add a timeout to this step. Currently it never times out.

### Possible implementation(s)

[Add a timeout config to both uses of `got` in this file](https://github.com/blitz-js/blitz/blob/017c1ff813530a4720b238d7b3284c33462b61e3/packages/generator/src/utils/npm-fetch.ts). And [here's the doc for `got` timeout](https://github.com/sindresorhus/got#timeout).

I think we should try a timeout of 3s (per request).

**Comment by cardotrejos** [comment]
I want to take this one. I haven't use got, but I think I understand the solution.
